'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {crmResponse,savedCRMRequest} from '@/utils/crm/client'
type Lead={id:string;name:string;email:string|null;phone:string|null}
type Item={leadId:string;leadName:string;state:string;handoffId:string|null;payload:Record<string,unknown>|null;revision:number|null;approved:boolean;externalId:string|null;outcome:string|null;stale:boolean}
type Batch={batchId:string;requestedAt:string;selectionCount:number;manifestHash:string;approved:boolean;stopped:boolean;counts:Record<string,number>;items:Item[];canApproveOwnBatch?:boolean}
const button='rounded-lg border border-gray-300 px-3 py-2 text-sm disabled:opacity-50 dark:border-gray-600'
const labels:Record<string,string>={queued:'Awaiting transfer',searching:'Checking destination',sending:'Waiting for CRM confirmation',confirmed:'Confirmed destination',needs_reconciliation:'Uncertain — needs destination review',failed:'Stopped before sending',cancelled:'Stopped',already_linked:'Already linked · excluded',contact_required:'Missing email or phone · excluded',handoff_in_progress:'Unfinished transfer · excluded',legacy_link_review_required:'Older link needs review · excluded',qualification_required:'Provider qualification required · excluded',configuration_required:'CRM setup required · excluded',payload_too_large:'Saved values are too large · excluded',missing_transfer:'Transfer unavailable · needs review'}
const stateLabel=(state:string)=>labels[state]||'Needs review'
export function CRMBulkTransfers({propertyId,canManage,onReviewTransfer}:{propertyId:string;canManage:boolean;onReviewTransfer:(id:string)=>void}){
 const [search,setSearch]=useState(''),[leadPage,setLeadPage]=useState(1),[leadPages,setLeadPages]=useState(1),[leads,setLeads]=useState<Lead[]>([]),[leadTotal,setLeadTotal]=useState(0),[selection,setSelection]=useState<Record<string,string>>({}),[loadingLeads,setLoadingLeads]=useState(true)
 const [batches,setBatches]=useState<Batch[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[preview,setPreview]=useState<Batch|null>(null),[paused,setPaused]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null)
 const alive=useRef(true),working=useRef(false),selected=useRef<string|null>(null),sequence=useRef(0),reloadController=useRef<AbortController|null>(null)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;reloadController.current?.abort();selected.current=null}},[])
 const review=useCallback(async(id:string)=>{selected.current=id;const seq=++sequence.current;const data=await crmResponse(await fetch(`/api/crm/batches?${new URLSearchParams({propertyId,batchId:id})}`));if(alive.current&&selected.current===id&&sequence.current===seq){setPreview(data);setPaused(data.deliveryPaused)}},[propertyId])
 const reload=useCallback(async()=>{reloadController.current?.abort();const controller=new AbortController();reloadController.current=controller;const data=await crmResponse(await fetch(`/api/crm/batches?${new URLSearchParams({propertyId,page:String(page)})}`,{signal:controller.signal}));if(alive.current&&!controller.signal.aborted){setBatches(data.batches);setPages(data.pages);setPaused(data.deliveryPaused);if(selected.current)await review(selected.current)}},[propertyId,page,review])
 useEffect(()=>{
  const params=new URLSearchParams(window.location.search),batchId=params.get('batchId')
  if(params.get('propertyId')!==propertyId||!batchId||!/^[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}$/i.test(batchId))return
  void review(batchId).catch(err=>{if(alive.current)setError(err.message)})
 },[propertyId,review])
 useEffect(()=>{void reload().catch(err=>{if(alive.current&&err.name!=='AbortError')setError(err.message)})},[reload])
 useEffect(()=>{
  const controller=new AbortController();setLoadingLeads(true)
  const timer=setTimeout(()=>{void fetch(`/api/crm/batches?${new URLSearchParams({view:'leads',propertyId,search,page:String(leadPage)})}`,{signal:controller.signal}).then(crmResponse).then(data=>{if(!controller.signal.aborted){setLeads(data.leads);setLeadTotal(data.total);setLeadPages(data.pages);setLoadingLeads(false)}}).catch(err=>{if(!controller.signal.aborted){setLeads([]);setError(err.message);setLoadingLeads(false)}})},search?250:0)
  return()=>{clearTimeout(timer);controller.abort()}
 },[propertyId,search,leadPage])
 function choose(lead:Lead,checked:boolean){setSelection(current=>{const next={...current};if(checked){if(Object.keys(next).length<100)next[lead.id]=lead.name||lead.email||'Unnamed lead'}else delete next[lead.id];return next})}
 async function command(action:'prepare'|'approve'|'stop'){
  if(working.current||!canManage)return
  working.current=true;setBusy(true);setError(null);setNotice(null)
  try{
   const input={action,propertyId,...(action==='prepare'?{leadIds:Object.keys(selection).sort()}:{batchId:preview!.batchId,manifestHash:preview!.manifestHash})}
   const request=await savedCRMRequest('bulk-'+action,input)
   const data=await crmResponse(await fetch('/api/crm/batches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request.body)}));request.acknowledge()
   if(!alive.current)return
   if(action==='prepare')setSelection({})
   await review(data.batchId);await reload()
   setNotice(action==='prepare'?'Selection saved. Review every prepared transfer and any excluded leads.':action==='approve'?'Approval saved. The worker will process the exact prepared transfers. Delivery is confirmed separately for each lead.':'Stop recorded. Transfers already writing or awaiting confirmation remain on hold; review their individual results.')
  }catch(err){if(alive.current)setError(err instanceof Error?err.message:'The batch result could not be confirmed.')}
  finally{working.current=false;if(alive.current)setBusy(false)}
 }
 const selectedCount=Object.keys(selection).length,queued=preview?.counts.queued||0,canStop=!!preview&&!preview.stopped&&!!((preview.counts.queued||0)+(preview.counts.searching||0))
 return <section aria-label="Bulk CRM transfers" className="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800">
  <div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Bulk CRM transfers</h2><p className="mt-1 text-sm text-gray-500">Save up to 100 selected leads, review their exact values, then approve the prepared transfers together.</p></div><button className={button} disabled={busy} onClick={()=>{setError(null);void reload().catch(err=>{if(alive.current&&err.name!=='AbortError')setError(err.message)})}}>Reload saved batches</button></div>
  {paused&&<p className="mt-3 text-sm text-amber-700">Outbound transfers are paused. You can prepare, review and stop saved work.</p>}
  {error&&<p role="alert" className="mt-3 rounded-lg border border-amber-300 p-3 text-sm">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}
  <label className="mt-4 block text-sm">Find leads for batch<input className="mt-1 block w-full rounded-lg border bg-transparent p-2" value={search} maxLength={200} onChange={e=>{setSearch(e.target.value);setLeadPage(1)}}/></label>
  <p className="mt-3 text-xs text-gray-500">{leadTotal} matching leads · Page {leadPage} of {leadPages}</p>
  {loadingLeads?<p className="mt-3 text-sm">Loading leads…</p>:<div className="mt-3 space-y-2">{leads.length===0?<p className="text-sm">No matching leads.</p>:leads.map(lead=><label key={lead.id} className="flex items-start gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" aria-label={`Select ${lead.name||lead.email||'Unnamed lead'}`} checked={!!selection[lead.id]} disabled={busy||!canManage||selectedCount>=100&&!selection[lead.id]} onChange={e=>choose(lead,e.target.checked)}/><span className="min-w-0 break-words"><span className="font-medium">{lead.name||'Unnamed lead'}</span><span className="mt-1 block text-xs text-gray-500">{lead.email||lead.phone||'No contact details'}</span></span></label>)}</div>}
  <div className="mt-3 flex flex-wrap gap-2"><button className={button} disabled={busy||loadingLeads||leadPage===1} onClick={()=>setLeadPage(p=>p-1)}>Previous lead page</button><button className={button} disabled={busy||loadingLeads||leadPage>=leadPages} onClick={()=>setLeadPage(p=>p+1)}>Next lead page</button></div>
  <div className="mt-4 rounded-lg border p-3"><h3 className="text-sm font-medium">Selected leads ({selectedCount}/100)</h3><p className="mt-1 text-xs text-gray-500">Selection stays while you search or change pages. Only saving the batch preserves it after a reload.</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(selection).map(([id,name])=><button key={id} className={button} disabled={busy} aria-label={`Remove ${name} from batch`} onClick={()=>setSelection(current=>{const next={...current};delete next[id];return next})}>{name} ×</button>)}</div><button className={`${button} mt-3`} disabled={busy||!canManage||selectedCount===0} onClick={()=>void command('prepare')}>Save batch for review</button></div>
  {preview&&<div className="mt-5 rounded-lg border border-indigo-200 p-4"><h3 className="font-medium">Saved batch review</h3><p className="mt-1 text-sm">{preview.selectionCount} selected leads · {new Date(preview.requestedAt).toLocaleString()}</p><p className="mt-2 text-sm">{preview.stopped?'Stop recorded. Confirmed and uncertain results remain in the history.':preview.approved?'Approval recorded. Check each saved result below.':'Review the exact prepared values. Excluded leads will not be sent by this batch.'}</p>
   <ul className="mt-3 space-y-1 text-sm">{Object.entries(preview.counts).map(([state,count])=><li key={state}>{stateLabel(state)}: {count}</li>)}</ul>
   <div className="mt-4 space-y-3">{preview.items.map(item=><article key={item.leadId} className="rounded-lg border p-3"><h4 className="font-medium">{item.leadName||'Unnamed lead'}</h4><p className="mt-1 text-sm">{item.state==='queued'?(item.approved?'Approved · Waiting for worker':'Ready for review'):stateLabel(item.state)}</p>{item.outcome==='destination_confirmed'&&<p className="mt-1 text-sm">Destination link confirmed; the original write remains unconfirmed.</p>}{item.stale&&<p className="mt-2 text-sm text-amber-700">Lead or connection changed. Stop this batch and prepare a fresh selection.</p>}{item.payload&&<details className="mt-3" open><summary className="cursor-pointer text-sm">Saved transfer values · Connection version {item.revision}</summary><dl className="mt-2 space-y-2">{Object.entries(item.payload).map(([key,value])=><div key={key}><dt className="break-all text-xs font-medium">{key}</dt><dd className="whitespace-pre-wrap break-words text-sm">{typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl></details>}{item.externalId&&<p className="mt-2 break-all text-xs">Destination record: {item.externalId}</p>}{['sending','needs_reconciliation'].includes(item.state)&&<p className="mt-2 text-sm text-amber-700">Review this transfer to check the destination. This batch will not resend it.</p>}{item.handoffId&&<button className={`${button} mt-3`} disabled={busy} onClick={()=>onReviewTransfer(item.handoffId!)}>Review this transfer</button>}</article>)}</div>
   <div className="mt-4 flex flex-wrap gap-2">{!preview.approved&&!preview.stopped&&queued>0&&<button className={button} disabled={busy||paused||!canManage||!preview.canApproveOwnBatch||preview.items.some(item=>item.stale)} onClick={()=>void command('approve')}>Approve {queued} saved transfers</button>}{canStop&&canManage&&<button className={button} disabled={busy} onClick={()=>void command('stop')}>Stop remaining batch transfers</button>}</div>{!preview.canApproveOwnBatch&&!preview.approved&&!preview.stopped&&queued>0&&<p className="mt-2 text-sm">The operator who saved this selection must approve it.</p>}
  </div>}
  <div className="mt-5 space-y-3"><h3 className="text-sm font-medium">Saved batches</h3>{batches.length===0?<p className="text-sm text-gray-500">No saved batches on this page.</p>:batches.map(batch=><article key={batch.batchId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="text-sm font-medium">{batch.selectionCount} selected leads</p><p className="mt-1 text-xs text-gray-500">{new Date(batch.requestedAt).toLocaleString()} · {batch.stopped?'Stop recorded':batch.approved?'Approval recorded':'Saved for review'}</p><p className="mt-1 text-xs">{Object.entries(batch.counts).map(([state,count])=>`${stateLabel(state)}: ${count}`).join(' · ')}</p></div><button className={button} disabled={busy} onClick={()=>{setPreview(null);void review(batch.batchId).catch(err=>{if(alive.current)setError(err.message)})}}>Review saved batch</button></article>)}<div className="flex gap-2"><button className={button} disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>Previous batch page</button><button className={button} disabled={busy||page>=pages} onClick={()=>setPage(p=>p+1)}>Next batch page</button></div></div>
 </section>
}
