
'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {crmResponse,savedCRMRequest} from '@/utils/crm/client'
type Handoff={receipt?:{result?:{outcome?:string}};id:string;leadName:string;kind:'lead'|'note';state:string;revision:number;platform:string;requestedAt:string;externalId:string|null;approved:boolean}
type RecoveryCheck={id:string;state:string;requestedAt:string;evidenceHash:string|null;evidence:{status:string;reason?:string;externalId?:string;observedContact?:Record<string,string>}|null}
type Preview={confirmationKind?:string;recoveryChecks:RecoveryCheck[];handoffId:string;kind:'lead'|'note';payload:Record<string,unknown>;payloadHash:string;deliveryState:string;canApprove:boolean;approved:boolean;revision:number}
const button='rounded-lg border border-gray-300 px-3 py-2 text-sm disabled:opacity-50 dark:border-gray-600'
function stateLabel(item:Handoff){return ({queued:item.approved?'Approved · Waiting for worker':'Ready for review',searching:'Checking for an existing record',sending:'Waiting for CRM confirmation',confirmed:item.receipt?.result?.outcome==='destination_confirmed'?'Destination link confirmed':'Confirmed',needs_reconciliation:'Review uncertain result',failed:'Stopped before sending',cancelled:'Stopped'} as Record<string,string>)[item.state]||'State unavailable'}
export function CRMDeliveryHistory({propertyId,leadId,canManage,requestedReview}:{propertyId:string;leadId:string;canManage:boolean;requestedReview?:{id:string;requestId:string}|null}){
 const [rows,setRows]=useState<Handoff[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0)
 const [preview,setPreview]=useState<Preview|null>(null),[paused,setPaused]=useState(true)
 const [error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(false)
 const section=useRef<HTMLElement|null>(null)
 const alive=useRef(true),working=useRef(false),selected=useRef<string|null>(null),previewSequence=useRef(0),controller=useRef<AbortController|null>(null)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();selected.current=null}},[])
 const review=useCallback(async(id:string)=>{selected.current=id;const sequence=++previewSequence.current;const data=await crmResponse(await fetch(`/api/crm/deliveries?${new URLSearchParams({propertyId,handoffId:id})}`));if(alive.current&&selected.current===id&&previewSequence.current===sequence)setPreview(data)},[propertyId])
 useEffect(()=>{if(requestedReview){setError(null);void review(requestedReview.id).then(()=>{if(alive.current)section.current?.scrollIntoView({block:'start'})}).catch(err=>{if(alive.current)setError(err.message)})}},[requestedReview,review])
 const reload=useCallback(async()=>{controller.current?.abort();const current=new AbortController();controller.current=current;const data=await crmResponse(await fetch(`/api/crm/deliveries?${new URLSearchParams({propertyId,page:String(page)})}`,{signal:current.signal}));if(alive.current&&!current.signal.aborted){setRows(data.handoffs);setPages(data.pages);setTotal(data.total);setPaused(data.deliveryPaused);setReady(true);if(selected.current)await review(selected.current)}},[propertyId,page,review])
 useEffect(()=>{void reload().catch(err=>{if(alive.current&&err.name!=='AbortError')setError(err.message)})},[reload])
 async function command(action:'prepare'|'run'|'stop'|'check_destination'|'accept_destination',id?:string,check?:RecoveryCheck){
  if(working.current||!canManage)return
  working.current=true;setBusy(true);setError(null);setNotice(null)
  try{
   const input:Record<string,unknown>={action,propertyId,...(action==='prepare'?{leadId}:action==='run'?{handoffId:preview!.handoffId,payloadHash:preview!.payloadHash}:{handoffId:id,...(check?{checkId:check.id,evidenceHash:check.evidenceHash}: {})})}
   const request=await savedCRMRequest('delivery-'+action,input)
   const result=await crmResponse(await fetch('/api/crm/deliveries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request.body)}));request.acknowledge()
   if(!alive.current)return
   await reload()
   if(action==='prepare'){if(result.state==='already_linked')setNotice('This lead already has a confirmed CRM link.');else{setNotice('Transfer prepared. Review the exact saved values before sending.');await review(result.handoffId)}}
   else if(action==='run'){await review(preview!.handoffId);setNotice('Check the saved result below. An approval is not a delivery confirmation.')}
   else if(action==='stop'){if(result.state==='cancelled'){setPreview(null);selected.current=null;setNotice('Transfer stopped before a provider write.')}else{await review(id!);setNotice('The transfer changed while the stop was requested. Review its saved result.')}}
   else{await review(id!);setNotice(action==='accept_destination'?'Destination link confirmed from saved read evidence. No transfer was resent.':'Destination check saved. Review its evidence below. No transfer was resent.')}
  }catch(err){if(alive.current)setError(err instanceof Error?err.message:'Transfer result could not be confirmed.')}
  finally{working.current=false;if(alive.current)setBusy(false)}
 }
 return <section ref={section} aria-label="Individual CRM transfers" className="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">CRM transfers</h2><p className="mt-1 text-sm text-gray-500">Review saved values and confirmed results for this property.</p></div><button className={button} disabled={busy} onClick={()=>{setError(null);void reload().catch(err=>{if(alive.current&&err.name!=='AbortError')setError(err.message)})}}>Reload saved transfers</button></div>
 {paused&&<p className="mt-3 rounded-lg border border-amber-200 p-3 text-sm">Outbound transfers are paused. Saved reviews do not send data.</p>}
 {error&&<p role="alert" className="mt-3 rounded-lg border border-amber-300 p-3 text-sm">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}
 <div className="mt-5 space-y-3"><p className="text-sm">Choose a real lead in the preview source above to prepare its transfer. Provider qualification is required.</p><p className="text-sm text-gray-500">This screen shows saved lead and note sync attempts. To sync leads, use Sync to CRM on the Leads page.</p><button className={button} disabled={busy||!ready||!canManage||!leadId} onClick={()=>void command('prepare')}>Prepare lead transfer</button></div>
 {preview&&<div className="mt-5 rounded-lg border border-indigo-200 p-4"><h3 className="font-medium">Saved {preview.kind==='note'?'note':'lead transfer'} values</h3><p className="mt-1 text-xs text-gray-500">Connection version {preview.revision} · {preview.deliveryState==='queued'?'Awaiting delivery':preview.deliveryState.replaceAll('_',' ')}</p>{preview.confirmationKind==='destination_confirmed'&&<p className="mt-3 text-sm">The destination link is confirmed from reviewed provider evidence. The original write remains unconfirmed; no transfer was resent.</p>}<dl className="mt-3 space-y-3">{Object.entries(preview.payload).map(([key,value])=><div key={key}><dt className="break-all text-sm font-medium">{key}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm">{typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl>{['sending','needs_reconciliation'].includes(preview.deliveryState)&&<div className="mt-4 border-t pt-4"><h4 className="font-medium">Check the destination</h4><p className="mt-1 text-sm text-gray-500">Read the saved connection to look for the original lead. This does not send the transfer again. A record found here confirms a destination link, not the original write.</p>{preview.kind==='lead'?<button className={`${button} mt-3`} disabled={busy||!canManage} onClick={()=>void command('check_destination',preview.handoffId)}>Check destination without resending</button>:<p className="mt-3 text-sm text-amber-700">This note needs its own provider receipt. A lead lookup cannot confirm that the note arrived.</p>}</div>}
 <div className="mt-4 space-y-3">{preview.recoveryChecks?.map(check=><article key={check.id} className="rounded-lg border p-3 text-sm"><h4 className="font-medium">Destination check · {new Date(check.requestedAt).toLocaleString()}</h4>{!check.evidence?<p className="mt-2">{check.state==='cancelled'?'Check stopped because access or the saved connection changed.':'Read result not yet saved. Reload to recover it, or start another read check.'}</p>:check.evidence.status==='match'?<><p className="mt-2 break-all">Provider record: {check.evidence.externalId}</p><dl className="mt-2 space-y-1">{Object.entries(check.evidence.observedContact||{}).map(([key,value])=><div key={key}><dt className="font-medium">Verified {key}</dt><dd className="break-all">{value}</dd></div>)}</dl>{['sending','needs_reconciliation'].includes(preview.deliveryState)&&<button className={`${button} mt-3`} disabled={busy||!canManage} onClick={()=>void command('accept_destination',preview.handoffId,check)}>Confirm this destination link</button>}</>:<p className="mt-2 text-amber-700">{check.evidence.status==='no_match'?'No matching record was confirmed. This does not prove the original write failed.':'The provider evidence did not confirm this destination.'} The transfer remains on hold.</p>}</article>)}</div>
 {preview.kind==='lead'&&preview.canApprove&&<button className={`${button} mt-4 border-indigo-500 text-indigo-700 dark:text-indigo-300`} disabled={busy||paused||!canManage} onClick={()=>void command('run')}>{preview.approved?'Run approved transfer':'Approve these values and send'}</button>}</div>}
 {!ready?<p className="mt-5 text-sm">Loading saved transfers…</p>:<div className="mt-5 space-y-3"><p className="text-xs text-gray-500">{total} saved transfers · Page {page} of {pages}</p>{rows.length===0?<p className="text-sm text-gray-500">No saved transfers on this page.</p>:rows.map(row=><article className="rounded-lg border border-gray-200 p-4 dark:border-gray-700" key={row.id}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-medium">{row.leadName||'Unnamed lead'} · {row.kind==='note'?'Note':'Lead transfer'}</h3><p className="mt-1 text-sm">{stateLabel(row)}</p><p className="mt-1 text-xs text-gray-500">{row.platform} · Version {row.revision} · {new Date(row.requestedAt).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>{setPreview(null);void review(row.id).catch(err=>{if(alive.current)setError(err.message)})}}>Review saved values</button>{canManage&&['queued','searching'].includes(row.state)&&<button className={button} disabled={busy} onClick={()=>void command('stop',row.id)}>Stop transfer</button>}</div></div>{['sending','needs_reconciliation'].includes(row.state)&&<p className="mt-3 text-sm text-amber-700">This attempt may have reached the CRM. Its destination must be reconciled before another attempt; it will not automatically send again.</p>}{row.externalId&&<p className="mt-2 break-all text-xs text-gray-500">Destination record: {row.externalId}</p>}</article>)}<div className="flex gap-3"><button className={button} disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>Previous transfers</button><button className={button} disabled={busy||page>=pages} onClick={()=>setPage(p=>p+1)}>Next transfers</button></div></div>}
 </section>
}
