'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {crmResponse,savedCRMRequest} from '@/utils/crm/client'
type Receipt={stage:string;result:{externalId?:string;identity?:{id:string;type:string};reason?:string;confirmed?:boolean;matches?:boolean;absent?:boolean;recovered?:boolean};receivedAt:string}
type Operation={id:string;integrationId:string;revision:number;state:string;payload:Record<string,unknown>;payloadHash:string;canApprove:boolean;currentConfiguration:boolean;activated:boolean;requestedAt:string;receipts:Receipt[]}
const button='rounded-lg border border-gray-300 px-3 py-2 text-sm disabled:opacity-50 dark:border-gray-600'
const states:Record<string,string>={prepared:'Saved test · Review required',queued:'Approved · Waiting for worker',running:'Provider test in progress',verified:'Lead delivery verified · Cleanup confirmed',failed:'Test did not qualify delivery',needs_reconciliation:'Test record needs recovery',cancelled:'Stopped before creating a test record'}
const stages:Record<string,string>={preflight:'Account and mapping checked',create_intent:'Test creation started',created:'Test record identified',readback:'Saved values read back',search:'Duplicate search checked',cleanup_intent:'Test cleanup started',cleanup:'Test record confirmed absent',failure:'Test held for review'}
const reasons:Record<string,string>={provider_contract_required:'This provider contract has not been qualified.',provider_identity_unconfirmed:'The provider account could not be verified. Check account access.',provider_account_changed:'The connected provider account changed. Review the original test in that account.',schema_or_search_unconfirmed:'Writable fields, required values or the initial duplicate search could not be verified. Review the approved mapping and provider permissions.',test_record_already_present_or_search_unconfirmed:'The initial search found an existing test record or could not confirm absence.',test_destination_unconfirmed:'The original creation result is uncertain. Review the provider account before trying another test.',test_record_changed:'The test record no longer matches the reviewed values. Automatic cleanup is held.',delivery_paused:'Outbound delivery is paused.',create_acknowledgement_unconfirmed:'The provider did not confirm creation. Recover the original test; do not create another.',test_record_read_unconfirmed:'The original test record could not be read.',cleanup_waits_for_delivery_permission:'Cleanup is waiting for delivery permission.',cleanup_not_confirmed:'Cleanup has not been confirmed. Review the original record in the provider; recovery will check for its absence.'}
export function CRMQualification({propertyId,integrationId,revision,platform,canManage,disabled,onActivated}:{propertyId:string;integrationId:string;revision:number;platform:string;canManage:boolean;disabled:boolean;onActivated:()=>Promise<void>}){
 const [operations,setOperations]=useState<Operation[]>([]),[paused,setPaused]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[consent,setConsent]=useState<Record<string,boolean>>({})
 const alive=useRef(true),working=useRef(false),controller=useRef<AbortController|null>(null)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort()}},[])
 const reload=useCallback(async()=>{controller.current?.abort();const current=new AbortController();controller.current=current;const data=await crmResponse(await fetch(`/api/crm/qualification?propertyId=${propertyId}`,{signal:current.signal}));if(alive.current&&!current.signal.aborted){setOperations(data.operations);setPaused(data.deliveryPaused)}},[propertyId])
 useEffect(()=>{void reload().catch(err=>{if(alive.current&&err.name!=='AbortError')setError(err.message)})},[reload])
 async function command(action:'prepare'|'run'|'recover'|'activate'|'stop',operation?:Operation){
  if(working.current||!canManage)return;working.current=true;setBusy(true);setError(null);setNotice(null)
  try{
   const input={action,propertyId,...(action==='prepare'?{integrationId,revision}:{operationId:operation!.id,payloadHash:operation!.payloadHash})}
   const saved=await savedCRMRequest('qualification-'+action,input)
   await crmResponse(await fetch('/api/crm/qualification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(saved.body)}));saved.acknowledge()
   if(!alive.current)return
   await reload();if(action==='activate')await onActivated()
   setNotice(action==='prepare'?'Test values saved for review. No CRM record has been created.':action==='activate'?'Lead delivery activated for this exact connection and mapping. Note delivery remains unavailable.':'Request recorded. Review the saved result and cleanup evidence below.')
  }catch(err){if(alive.current)setError(err instanceof Error?err.message:'The test result could not be confirmed.')}
  finally{working.current=false;if(alive.current)setBusy(false)}
 }
 const supported=['hubspot','salesforce'].includes(platform)
 return <section aria-label="CRM provider qualification" className="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Verify lead delivery</h2><p className="mt-1 text-sm text-gray-500">Create one reviewed test contact, read it back, check duplicate search and confirm its cleanup. Activation is a separate decision.</p></div><button className={button} disabled={busy} onClick={()=>{setError(null);void reload().catch(err=>{if(alive.current&&err.name!=='AbortError')setError(err.message)})}}>Reload saved provider tests</button></div>
  {paused&&<p className="mt-3 text-sm text-amber-700">Outbound delivery is paused. You can prepare reviews and inspect saved results. Creating a test record, cleanup and activation wait for delivery permission.</p>}
  {!supported&&<p className="mt-3 text-sm">This provider requires a tenant-specific delivery contract before activation. Saved connection and schema checks remain available.</p>}
  {error&&<p role="alert" className="mt-3 text-sm text-amber-700">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}
  <button className={`${button} mt-4`} disabled={busy||disabled||!canManage||!supported} onClick={()=>void command('prepare')}>Prepare provider test for review</button>
  <div className="mt-5 space-y-4">{operations.map(operation=><article key={operation.id} className="rounded-lg border p-4"><h3 className="font-medium">{states[operation.state]||'Saved state unavailable'}</h3><p className="mt-1 text-xs text-gray-500">Connection version {operation.revision} · {new Date(operation.requestedAt).toLocaleString()}{!operation.currentConfiguration?' · Earlier configuration':''}</p>{operation.activated&&<p className="mt-2 text-sm">Lead delivery activated for this verified setup.</p>}<details className="mt-3" open={operation.state==='prepared'}><summary className="cursor-pointer text-sm">Exact test values</summary><dl className="mt-2 space-y-2">{Object.entries(operation.payload).map(([key,value])=><div key={key}><dt className="break-all text-xs font-medium">{key}</dt><dd className="break-words text-sm">{String(value)}</dd></div>)}</dl></details>
   <ol className="mt-3 space-y-2 text-sm">{operation.receipts.map(receipt=><li key={receipt.stage}><span className="font-medium">{stages[receipt.stage]||'Saved evidence'}</span>{receipt.result.externalId&&<span className="block break-all text-xs">Test record: {receipt.result.externalId}</span>}{receipt.result.identity&&<span className="block break-all text-xs">Provider account: {receipt.result.identity.id} · {receipt.result.identity.type}</span>}{receipt.result.reason&&<span className="block text-amber-700">{reasons[receipt.result.reason]||'Review the saved provider evidence before continuing.'}</span>}{receipt.result.matches===false&&<span className="block text-amber-700">This check did not confirm the expected result.</span>}{receipt.stage==='created'&&receipt.result.confirmed===false&&<span className="block text-amber-700">Found during recovery. The original create acknowledgement remains unconfirmed.</span>}</li>)}</ol>
   {operation.state==='needs_reconciliation'&&<p className="mt-3 text-sm text-amber-700">A test record may still exist. Recovery checks the original record and completes pending cleanup; it never repeats creation. An uncertain cleanup is read again without issuing another delete. If the record still exists after that check, review it in the provider before removing this connection.</p>}
   {operation.state==='failed'&&<p className="mt-3 text-sm">Review writable field names, required values and provider evidence. A failed test never activates delivery.</p>}
   <div className="mt-3 flex flex-wrap gap-2">{operation.state==='prepared'&&operation.currentConfiguration&&<><label className="flex w-full items-start gap-2 text-sm"><input type="checkbox" checked={!!consent[operation.id]} disabled={busy||!canManage||paused} onChange={e=>setConsent(current=>({...current,[operation.id]:e.target.checked}))}/>I reviewed these values and authorize this test record and its cleanup. CRM automations may react to the test.</label><button className={button} disabled={busy||disabled||paused||!canManage||!operation.canApprove||!consent[operation.id]} onClick={()=>void command('run',operation)}>Approve and run this provider test</button></>}
   {['queued','running','needs_reconciliation'].includes(operation.state)&&operation.currentConfiguration&&<button className={button} disabled={busy||!canManage} onClick={()=>void command('recover',operation)}>Recover saved provider test</button>}
   {['prepared','queued','running'].includes(operation.state)&&!operation.receipts.some(r=>r.stage==='create_intent')&&<button className={button} disabled={busy||!canManage} onClick={()=>void command('stop',operation)}>Stop provider test</button>}
   {operation.state==='verified'&&operation.currentConfiguration&&!operation.activated&&<button className={button} disabled={busy||disabled||paused||!canManage} onClick={()=>void command('activate',operation)}>Activate verified lead delivery</button>}</div>
  </article>)}</div>
 </section>
}
