import{beforeEach,it,expect,vi}from'vitest'
const d=vi.hoisted(()=>({actor:vi.fn(),org:vi.fn(),read:vi.fn(),decide:vi.fn()}))
vi.mock('@/utils/team/store',async()=>{const{InventoryError}=await import('@/utils/knowledge/inventory');return{TeamError:InventoryError,teamActor:d.actor,currentTeamOrganization:d.org,readTeam:d.read,decideTeam:d.decide}})
import{InventoryError}from'@/utils/knowledge/inventory'
import{GET,POST,PATCH,DELETE}from'./route'
const id='11111111-1111-1111-1111-111111111111',body={orgId:id,requestId:id,operation:'create_invitation',email:'fixture@example.invalid',role:'viewer',expiresInDays:7,reason:'Reviewed recipient',confirmed:true},req=(b:unknown=body,headers:Record<string,string>={origin:'http://local'})=>new Request('http://local/api/team',{method:'POST',headers,body:typeof b==='string'?b:JSON.stringify(b)})
beforeEach(()=>{vi.clearAllMocks();d.actor.mockResolvedValue('actual-actor');d.org.mockResolvedValue(id);d.read.mockResolvedValue({state:'ready',items:[]});d.decide.mockResolvedValue({state:'saved'})})
it('authenticates before parsing or consulting team scope',async()=>{d.actor.mockRejectedValue(new InventoryError('Unauthorized',401));expect((await POST(req('bad'))).status).toBe(401);expect((await GET(new Request('http://local'))).status).toBe(401);expect(d.org).not.toHaveBeenCalled();expect(d.decide).not.toHaveBeenCalled()})
it('binds current actor and private no-referrer receipt, rejecting actor and token injection',async()=>{const r=await POST(req());expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('private, no-store');expect(r.headers.get('referrer-policy')).toBe('no-referrer');expect(d.decide).toHaveBeenCalledWith('actual-actor',body);expect((await POST(req({...body,actorId:id}))).status).toBe(400);expect((await POST(req({...body,token:'a'.repeat(64)}))).status).toBe(400)})
it('rejects cross-origin and missing origins plus streamed and declared body limits',async()=>{expect((await POST(req(body,{origin:'http://outside'}))).status).toBe(403);expect((await POST(req(body,{}))).status).toBe(403);expect((await POST(req('x'.repeat(16385)))).status).toBe(413);expect((await POST(req('{}',{origin:'http://local','content-length':'16385'}))).status).toBe(413);expect(d.decide).not.toHaveBeenCalled()})
it('derives current org, closes legacy writes and does not disclose internal failures',async()=>{expect((await GET(new Request('http://local/api/team'))).status).toBe(200);expect(d.read).toHaveBeenCalledWith('actual-actor',id,{kind:'members',offset:0});expect((await PATCH()).status).toBe(410);expect((await DELETE()).status).toBe(410);d.read.mockRejectedValue(new Error('private query'));const r=await GET(new Request('http://local/api/team'));expect(r.status).toBe(503);expect(await r.json()).toEqual({error:'Team access is unavailable.'})})

it('checks the public request Host when a local proxy normalizes the URL hostname',async()=>{expect((await POST(req(body,{origin:'http://127.0.0.1:9430',host:'127.0.0.1:9430'}))).status).toBe(200);expect((await POST(req(body,{origin:'http://outside',host:'127.0.0.1:9430'}))).status).toBe(403)})
