import type {FactCommand} from './fact-contracts'
import {knowledgeFetch} from './material-client'
export {knowledgeFetch as factFetch}
export type PendingFact={id:string;propertyId:string;operation:string;hash:string}
const key=(propertyId:string)=>`p11.facts.pending.v1:${propertyId}`
export function pendingFact(propertyId:string):PendingFact|null{try{const v=JSON.parse(sessionStorage.getItem(key(propertyId))||'null');return v?.propertyId===propertyId&&typeof v.id==='string'&&typeof v.hash==='string'?v:null}catch{return null}}
export function clearPendingFact(propertyId:string,id:string){if(pendingFact(propertyId)?.id===id)sessionStorage.removeItem(key(propertyId))}
export function factsUrl(propertyId:string,input:Record<string,string|number|undefined>={}){const q=new URLSearchParams({propertyId});for(const[k,v]of Object.entries(input))if(v!==undefined)q.set(k,String(v));return `/api/assistant-facts?${q}`}
export async function postFact(command:Omit<FactCommand,'requestId'>){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(command))),hash=Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join(''),prior=pendingFact(command.propertyId);if(prior&&prior.hash!==hash)throw new Error('Check the previous unconfirmed facts decision before changing it.');const id=prior?.id||crypto.randomUUID();sessionStorage.setItem(key(command.propertyId),JSON.stringify({id,hash,propertyId:command.propertyId,operation:command.operation}));try{const data=await knowledgeFetch('/api/assistant-facts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,requestId:id})});if(!['saved','replayed'].includes(data.state)||typeof data.versionId!=='string')throw new Error('The facts receipt could not be verified. Check its saved decision.');clearPendingFact(command.propertyId,id);return data}catch(e){if(e instanceof Error&&'status'in e&&[400,403,409,413].includes(Number(e.status)))clearPendingFact(command.propertyId,id);throw e}}
