import {beforeEach,it,expect,vi} from 'vitest'
import {createHash} from 'node:crypto'
const d=vi.hoisted(()=>({rpc:vi.fn(),upload:vi.fn(),download:vi.fn(),extract:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc:d.rpc,storage:{from:()=>({upload:d.upload,download:d.download})}})}))
vi.mock('./inventory',()=>({InventoryError:class extends Error{constructor(message:string,readonly status=503){super(message)}},inventoryActor:vi.fn()}))
vi.mock('./file-extraction',()=>({extractOriginal:d.extract}))
import {uploadOriginal,verifyOriginal,runFileExtraction,downloadOriginal,decideFile} from './file-store'
import type {OriginalFile} from './file-contracts'
const id='11111111-1111-1111-1111-111111111111',property='22222222-2222-2222-2222-222222222222',bytes=new TextEncoder().encode('Exact\r\n🏡'),hash=createHash('sha256').update(bytes).digest('hex')
const original:OriginalFile={id,property_id:property,org_id:property,actor_id:id,input:{title:'Original',fileName:'source.txt',mimeType:'text/plain',size:bytes.length,byteHash:hash,reason:'Retain exact original',materialId:null},storage_path:property+'/'+id+'/original',state:'pending',revision:1,latest_extraction_id:null,accepted_version_id:null,created_at:'date',stored_at:null}
function form(){const f=new FormData();f.set('file',new File([bytes],'source.txt',{type:'text/plain'}));f.set('propertyId',property);f.set('requestId',id);f.set('title','Original');f.set('reason','Retain exact original');f.set('materialId','');return f}
beforeEach(()=>{vi.clearAllMocks();d.rpc.mockImplementation(async(name)=>({error:null,data:name==='read_knowledge_files'?{state:'ready',file:{...original}}:name==='begin_knowledge_file'?{state:'saved',fileId:id}:{state:'ready',fileState:'stored'}}));d.upload.mockResolvedValue({error:null});d.download.mockResolvedValue({error:null,data:new Blob([bytes])});d.extract.mockResolvedValue({recipe:'unpdf-1.4.0-pages-v1',fileHash:hash,complete:true,totalPages:1,pages:['Exact source'],text:'Exact source',blankPages:[],limitations:[],errorCode:null})})
it('saves intent before immutable storage and verifies exact bytes before finalization',async()=>{expect(await uploadOriginal(id,form())).toMatchObject({state:'saved',fileState:'stored'});expect(d.upload).toHaveBeenCalledWith(original.storage_path,bytes,{contentType:'text/plain',upsert:false});const args=d.rpc.mock.calls.find(c=>c[0]==='begin_knowledge_file')![1];expect(args.p_input.byteHash).toBe(hash);expect(d.rpc.mock.invocationCallOrder[0]).toBeLessThan(d.upload.mock.invocationCallOrder[0]);expect(d.download.mock.invocationCallOrder[0]).toBeLessThan(d.rpc.mock.invocationCallOrder.at(-1)!);expect(d.extract).not.toHaveBeenCalled()})
it('recovers an existing immutable object after a lost storage reply',async()=>{d.upload.mockResolvedValue({error:{message:'already exists'}});expect((await uploadOriginal(id,form())).fileState).toBe('stored')})
it('refuses finalization when private storage is unavailable or differs',async()=>{d.download.mockResolvedValueOnce({error:{message:'missing'},data:null});await expect(uploadOriginal(id,form())).rejects.toThrow('private storage');expect(d.rpc.mock.calls.some(c=>c[0]==='finish_knowledge_file_storage')).toBe(false);d.download.mockResolvedValueOnce({error:null,data:new Blob([new Uint8Array(bytes.length)])});await expect(verifyOriginal(original)).rejects.toThrow('do not match')})
it('rejects old unreviewed upload bodies, unsupported files and false PDF signatures before saving',async()=>{const f=form();f.delete('requestId');await expect(uploadOriginal(id,f)).rejects.toThrow('reviewed upload');const other=form();other.set('file',new File(['notpdf'],'bad.pdf'));await expect(uploadOriginal(id,other)).rejects.toThrow('PDF signature');expect(d.rpc).not.toHaveBeenCalled()})
it('a stopped upload does not store or extract late bytes',async()=>{d.rpc.mockImplementation(async name=>({error:null,data:name==='read_knowledge_files'?{state:'ready',file:{...original,state:'stopped'}}:{state:'replayed',fileId:id}}));expect((await uploadOriginal(id,form())).fileState).toBe('stopped');expect(d.upload).not.toHaveBeenCalled();expect(d.extract).not.toHaveBeenCalled()})
it('claims once and persists the same local receipt again after uncertain persistence',async()=>{let writes=0;d.rpc.mockImplementation(async name=>({data:name==='claim_knowledge_file_extraction'?{state:'invoke_once',claimToken:id,file:original}:++writes===1?null:{state:'ready'},error:name==='record_knowledge_file_extraction'&&writes===1?{}:null}));await runFileExtraction(id);expect(d.extract).toHaveBeenCalledTimes(1);const calls=d.rpc.mock.calls.filter(c=>c[0]==='record_knowledge_file_extraction');expect(calls).toHaveLength(2);expect(calls[0][1]).toEqual(calls[1][1])})
it('does not invoke a running or stopped extraction again',async()=>{for(const state of['running','stopped']){d.rpc.mockResolvedValue({data:{state},error:null});expect((await runFileExtraction(id)).state).toBe(state)}expect(d.extract).not.toHaveBeenCalled();expect(d.download).not.toHaveBeenCalled()})
it('private downloads require exact prepared evidence and recheck access after bytes',async()=>{let reads=0;d.rpc.mockImplementation(async()=>({error:null,data:++reads===1?{state:'ready',fileId:id,prepared:true,byteHash:hash}:{state:'ready',file:{...original,state:'stored'}}}));expect((await downloadOriginal(id,property,id,id)).bytes).toEqual(bytes);expect(d.rpc).toHaveBeenCalledTimes(3);expect(d.download.mock.invocationCallOrder[0]).toBeLessThan(d.rpc.mock.invocationCallOrder[2])})
it('late access revocation prevents download response',async()=>{let reads=0;d.rpc.mockImplementation(async()=>({error:null,data:++reads===1?{state:'ready',fileId:id,prepared:true,byteHash:hash}:reads===2?{state:'ready',file:{...original,state:'stored'}}:{state:'forbidden'}}));await expect(downloadOriginal(id,property,id,id)).rejects.toThrow('unavailable')})
it('a read failure never becomes empty success and decisions never invoke a model',async()=>{d.rpc.mockResolvedValue({data:null,error:{message:'private database detail'}});await expect(decideFile(id,{requestId:id,propertyId:property,fileId:id,expectedRevision:1,operation:'download',reason:'Read retained original'})).rejects.toThrow('could not be confirmed');expect(d.extract).not.toHaveBeenCalled()})
