import type {FileCommand} from './file-contracts'
import {knowledgeFetch} from './material-client'
export type PendingFile={id:string;propertyId:string;fileId:string;operation:string;hash:string}
const key=(propertyId:string)=>`p11.files.pending.v1:${propertyId}`
export function pendingFile(propertyId:string):PendingFile|null{try{const p=JSON.parse(sessionStorage.getItem(key(propertyId))||'null');return p?.propertyId===propertyId&&typeof p.id==='string'&&typeof p.fileId==='string'&&typeof p.hash==='string'?p:null}catch{return null}}
export function clearPendingFile(propertyId:string,id:string){if(pendingFile(propertyId)?.id===id)sessionStorage.removeItem(key(propertyId))}
export async function fileDigest(value:BufferSource){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',value)),n=>n.toString(16).padStart(2,'0')).join('')}
export function fileUrl(propertyId:string,input:Record<string,string|number|undefined>={}){const q=new URLSearchParams({propertyId});for(const[k,v]of Object.entries(input))if(v!==undefined)q.set(k,String(v));return`/api/knowledge/files?${q}`}
async function beginPending(propertyId:string,fileId:string|undefined,operation:string,value:unknown,fixedId?:string){const hash=await fileDigest(new TextEncoder().encode(JSON.stringify(value))),prior=pendingFile(propertyId);if(prior&&prior.hash!==hash)throw new Error('Check the previous file decision before changing this request.');if(prior&&fixedId&&prior.id!==fixedId)throw new Error('Check the earlier file decision first.');const id=prior?.id||fixedId||crypto.randomUUID(),pending={id,propertyId,fileId:fileId||id,operation,hash};sessionStorage.setItem(key(propertyId),JSON.stringify(pending));return pending}
async function finish(p:PendingFile,init:RequestInit){try{const result=await knowledgeFetch('/api/knowledge/files',init);if(!['saved','replayed'].includes(result.state)||result.fileId!==p.fileId)throw new Error('The file receipt could not be verified. Check the retained decision.');clearPendingFile(p.propertyId,p.id);return{...result,decisionId:p.id}}catch(e){if(e instanceof Error&&'status'in e&&[400,403,409,413].includes(Number(e.status)))clearPendingFile(p.propertyId,p.id);throw e}}
export async function postFile(command:Omit<FileCommand,'requestId'>){const fileId='fileId'in command&&typeof command.fileId==='string'?command.fileId:undefined,p=await beginPending(command.propertyId,fileId,command.operation,command);return finish(p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,requestId:p.id})})}
export async function postOriginal(propertyId:string,file:File,title:string,reason:string,materialId:string|null,requestId?:string){const byteHash=await fileDigest(await file.arrayBuffer()),p=await beginPending(propertyId,undefined,'upload',{propertyId,title,reason,materialId,fileName:file.name,size:file.size,byteHash},requestId);const form=new FormData();form.set('file',file);form.set('propertyId',propertyId);form.set('requestId',p.id);form.set('title',title);form.set('reason',reason);form.set('materialId',materialId||'');return finish(p,{method:'POST',body:form})}
