import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({create:vi.fn(),constructor:vi.fn()}))
vi.mock('openai',()=>({default:class{embeddings={create:d.create};constructor(options:unknown){d.constructor(options)}}}))
import {prepareKnowledgeText,executeKnowledgeSearch} from './material-model'
import {materialCommand,validText} from './material-contracts'
beforeEach(()=>vi.clearAllMocks())
it('retains CRLF BOM emoji and short original text exactly',()=>{const source='\ufeffHi.\r\n🏡';const input=prepareKnowledgeText(source);expect(input.chunks.join('')).toBe(source);expect(input.chunks).toHaveLength(1);expect(input.contentHash).toMatch(/^[a-f0-9]{64}$/)})
it('chunks the full 256 KiB without cutting UTF8 characters',()=>{const source='a'.repeat(4095)+'🏡'.repeat(64512)+'z';const input=prepareKnowledgeText(source);expect(input.chunks.join('')).toBe(source);expect(input.chunks.every(c=>Buffer.byteLength(c)<=4096)).toBe(true);expect(input.chunks.every(validText)).toBe(true)})
it.each(['','   ','x\0y','x\ud800','\udc00x','x'.repeat(262145)])('rejects invalid or oversized text',source=>{expect(()=>prepareKnowledgeText(source)).toThrow('invalid_source')})
it('strict save contract rejects legacy arbitrary metadata and incomplete predecessor intent',()=>{const value={requestId:'11111111-1111-1111-1111-111111111111',propertyId:'33333333-3333-3333-3333-333333333333',operation:'save',materialId:null,previousVersionId:null,title:'Policy',content:'Hi',reason:'Reviewed original'};expect(materialCommand.safeParse(value).success).toBe(true);expect(materialCommand.safeParse({...value,metadata:{source:'pasted_text'}}).success).toBe(false);const{previousVersionId,...missing}=value;expect(previousVersionId).toBeNull();expect(materialCommand.safeParse(missing).success).toBe(false)})
it('uses one bounded canonical request and retains usage and provider receipt without a guessed cost',async()=>{const response={model:'text-embedding-3-small',data:[{index:0,embedding:[1,2,3]}],usage:{prompt_tokens:12,total_tokens:12},_request_id:'provider-fixture'};d.create.mockResolvedValue(response);const input=prepareKnowledgeText('Reviewed source');expect(await executeKnowledgeSearch(input)).toEqual({status:'received',providerRequestId:'provider-fixture',response:{model:response.model,data:response.data,usage:response.usage}});expect(d.constructor).toHaveBeenCalledWith(expect.objectContaining({baseURL:'https://api.openai.com/v1',maxRetries:0,timeout:60000}));expect(d.create).toHaveBeenCalledTimes(1);expect(d.create).toHaveBeenCalledWith({model:input.model,dimensions:1536,input:input.chunks,encoding_format:'float'})})
