import {createHash} from 'node:crypto'
import {createServiceClient} from '@/utils/supabase/admin'
import {InventoryError,inventoryActor} from './inventory'
import type {WebCommand,WebDetail,WebReceipt} from './web-contracts'
import {captureWebsite} from './web-provider'
export {InventoryError as WebError,inventoryActor as webActor}
type Value=Record<string,unknown>
const messages:Record<string,string>={policy_changed:'The monitoring policy changed. Reload and review the current settings.',forbidden:'This website capture is unavailable in your current property.',not_found:'This retained website capture or decision is unavailable.',request_conflict:'This request differs from its saved decision.',decision_cancelled:'This unused request was cancelled. Begin a new capture.',capture_changed:'This capture changed. Reload and review its current result.',source_changed:'The destination source changed. Reload before accepting replacement text.',still_running:'Recover or stop the earlier capture before requesting another.',closed_request:'This capture is already closed. Read its retained result.',history_changed:'Website history changed. Reload before continuing.',original_unavailable:'This capture has no complete retained original to download.',receipt_changed:'The saved capture receipt cannot be replaced.'}
export function webExecutionStatus(){return{paused:process.env.OUTBOUND_DELIVERY_PAUSED==='true'}}
export async function webRpc(name:string,args:Value){const db=createServiceClient()as unknown as{rpc:(name:string,args:Value)=>Promise<{data:Value|null;error:unknown}>};const{data,error}=await db.rpc(name,args);if(error||!data)throw new InventoryError('This website operation could not be confirmed. Check its saved decision before retrying.');if(!['ready','saved','replayed','cancelled','queued','running','held','stopped','invoke_once'].includes(String(data.state)))throw new InventoryError(messages[String(data.state)]||'Review the saved website capture before continuing.',data.state==='forbidden'?403:data.state==='not_found'?404:409);return data}
export async function readWeb(actor:string,propertyId:string,input:Value):Promise<Value&{execution:{paused:boolean}}>{return{...await webRpc('read_knowledge_web_captures',{p_property_id:propertyId,p_actor_id:actor,p_input:input}),execution:webExecutionStatus()}}
export async function runWebCapture(id:string){if(webExecutionStatus().paused)return{state:'paused'};const claim=await webRpc('claim_knowledge_web_capture',{p_id:id});if(claim.state!=='invoke_once')return claim;let receipt:WebReceipt;try{receipt=await captureWebsite(String(claim.url))}catch{receipt={recipe:'public-utf8-html-v1',complete:false,requestedUrl:String(claim.url),fetchedAt:new Date().toISOString(),limitations:[],errorCode:'fetch_unconfirmed'}}if(Buffer.byteLength(JSON.stringify(receipt))>7*1024*1024)receipt={...receipt,body:undefined,bodyHash:undefined,text:undefined,complete:false,errorCode:'receipt_limit'};const args={p_id:id,p_claim_token:claim.claimToken,p_receipt:JSON.parse(JSON.stringify(receipt))};try{return await webRpc('record_knowledge_web_capture',args)}catch{return webRpc('record_knowledge_web_capture',args)}}
export async function decideWeb(actor:string,command:WebCommand){const{requestId,propertyId,operation,...input}=command;const result=await webRpc(operation==='cancel_unused'?'cancel_unused_knowledge_decision':operation==='capture'?'begin_knowledge_web_capture':'decide_knowledge_web_capture',{p_id:requestId,p_property_id:propertyId,p_actor_id:actor,p_input:['cancel_unused','capture'].includes(operation)?input:{...input,operation}});return['capture','recover'].includes(operation)?{...result,execution:await runWebCapture(String(result.captureId))}:result}
export async function downloadWeb(actor:string,propertyId:string,captureId:string,decisionId:string){const decision=await readWeb(actor,propertyId,{kind:'decision',decisionId});if(decision.captureId!==captureId||decision.prepared!==true)throw new InventoryError('Prepare this exact website original download first.',409);const detail=await readWeb(actor,propertyId,{kind:'capture',captureId})as unknown as WebDetail;const receipt=detail.capture.receipt;if(typeof receipt?.body!=='string'||receipt.bodyHash!==decision.bodyHash)throw new InventoryError(messages.original_unavailable,409);const bytes=Buffer.from(receipt.body,'utf8');if(createHash('sha256').update(bytes).digest('hex')!==receipt.bodyHash)throw new InventoryError('The retained original does not match its saved hash.',409);return bytes}
