import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({rpc:vi.fn(),status:vi.fn(),run:vi.fn()}));vi.mock('./web-store',()=>({webRpc:d.rpc,webExecutionStatus:d.status,runWebCapture:d.run}))
import {checkScheduledWebsites,decideWebPolicy} from './web-policy-store'
beforeEach(()=>{vi.clearAllMocks();d.status.mockReturnValue({paused:false});d.rpc.mockResolvedValue({state:'ready',requests:[]})})
it('global pause prevents dispatch as well as fetch',async()=>{d.status.mockReturnValue({paused:true});expect(await checkScheduledWebsites()).toMatchObject({state:'paused',scheduled:0,ready:0});expect(d.rpc).not.toHaveBeenCalled();expect(d.run).not.toHaveBeenCalled()})
it('records a bounded mixed batch without hidden retries or publication',async()=>{d.rpc.mockResolvedValue({state:'ready',requests:[{id:'a',propertyId:'p'},{id:'b',propertyId:'p'},{id:'c',propertyId:'q'}]});d.run.mockResolvedValueOnce({state:'ready'}).mockResolvedValueOnce({state:'held'}).mockRejectedValueOnce(new Error('unknown'));expect(await checkScheduledWebsites()).toEqual({state:'review_required',scheduled:3,ready:1,unconfirmed:1,results:[{captureId:'a',propertyId:'p',state:'ready'},{captureId:'b',propertyId:'p',state:'held'},{captureId:'c',propertyId:'q',state:'unconfirmed'}]});expect(d.rpc).toHaveBeenCalledExactlyOnceWith('dispatch_knowledge_web_checks',{p_limit:5});expect(d.run.mock.calls).toEqual([['a'],['b'],['c']])})
it('does not mistake an in-progress or stopped request for refreshed knowledge',async()=>{d.rpc.mockResolvedValue({state:'ready',requests:[{id:'a',propertyId:'p'},{id:'b',propertyId:'p'}]});d.run.mockResolvedValueOnce({state:'running'}).mockResolvedValueOnce({state:'stopped'});expect(await checkScheduledWebsites()).toMatchObject({state:'review_required',ready:0,unconfirmed:1})})
it('fails closed on an oversized or unreadable dispatch receipt',async()=>{for(const requests of[null,Array.from({length:6},()=>({id:'a'}))]){d.rpc.mockResolvedValue({state:'ready',requests});await expect(checkScheduledWebsites()).rejects.toThrow('batch')}expect(d.run).not.toHaveBeenCalled()})
it('submits exact versioned policy to the native authority boundary',async()=>{await decideWebPolicy('actor',{requestId:'id',propertyId:'property',operation:'save',enabled:true,expectedRevision:2,intervalHours:48,dailyLimit:2,confirmed:true,reason:'Reviewed scope'});expect(d.rpc).toHaveBeenCalledWith('save_knowledge_web_policy',{p_id:'id',p_property_id:'property',p_actor_id:'actor',p_input:{enabled:true,expectedRevision:2,intervalHours:48,dailyLimit:2,confirmed:true,reason:'Reviewed scope'}})})
