import {beforeEach,afterEach,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
const d=vi.hoisted(()=>({rpc:vi.fn(),capture:vi.fn()}));vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc:d.rpc})}));vi.mock('./web-provider',()=>({captureWebsite:d.capture}));vi.mock('./inventory',()=>({inventoryActor:vi.fn(),InventoryError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {runWebCapture,downloadWeb,webRpc} from './web-store'
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false')});afterEach(()=>vi.unstubAllEnvs())
it('paused execution does not claim or contact a website',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect(await runWebCapture('capture')).toEqual({state:'paused'});expect(d.rpc).not.toHaveBeenCalled();expect(d.capture).not.toHaveBeenCalled()})
it('recovery never repeats a claimed fetch',async()=>{d.rpc.mockResolvedValue({data:{state:'running'},error:null});expect(await runWebCapture('capture')).toEqual({state:'running'});expect(d.capture).not.toHaveBeenCalled()})
it('retries only exact receipt persistence after one fetch',async()=>{const receipt={recipe:'public-utf8-html-v1',complete:true,body:'Exact source',text:'Exact source'};d.rpc.mockResolvedValueOnce({data:{state:'invoke_once',claimToken:'token',url:'https://example.test'},error:null}).mockResolvedValueOnce({data:null,error:{message:'uncertain save'}}).mockResolvedValueOnce({data:{state:'ready'},error:null});d.capture.mockResolvedValue(receipt);expect(await runWebCapture('capture')).toEqual({state:'ready'});expect(d.capture).toHaveBeenCalledOnce();expect(d.rpc.mock.calls[1]).toEqual(d.rpc.mock.calls[2])})
it('downloads only exact prepared original bytes after a current scoped read',async()=>{const body='\uFEFFExact\r\n🏡',bodyHash=createHash('sha256').update(body).digest('hex');d.rpc.mockResolvedValueOnce({data:{state:'ready',captureId:'capture',prepared:true,bodyHash},error:null}).mockResolvedValueOnce({data:{state:'ready',capture:{receipt:{body,bodyHash}}},error:null});expect(await downloadWeb('actor','property','capture','decision')).toEqual(Buffer.from(body));expect(d.rpc).toHaveBeenLastCalledWith('read_knowledge_web_captures',{p_property_id:'property',p_actor_id:'actor',p_input:{kind:'capture',captureId:'capture'}})})
it('holds a wrong prepared identity or revoked read access',async()=>{d.rpc.mockResolvedValue({data:{state:'ready',captureId:'another',prepared:true},error:null});await expect(downloadWeb('actor','property','capture','decision')).rejects.toMatchObject({status:409});d.rpc.mockResolvedValue({data:{state:'forbidden'},error:null});await expect(webRpc('read_knowledge_web_captures',{})).rejects.toMatchObject({status:403})})
