import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({actor:vi.fn(),read:vi.fn(),decide:vi.fn()}))
vi.mock('@/utils/readiness/store',()=>({readinessActor:d.actor,readReadiness:d.read,decideReadiness:d.decide,ReadinessError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {GET,POST,PUT} from './route'
import {ReadinessError} from '@/utils/readiness/store'
const id='11111111-1111-1111-1111-111111111111',body={requestId:id,propertyId:id,operation:'build',enabledCapabilities:[],reason:'Review task'}
beforeEach(()=>{vi.clearAllMocks();d.actor.mockResolvedValue('actual-actor');d.read.mockResolvedValue({state:'ready',items:[]});d.decide.mockResolvedValue({state:'saved',propertyId:id})})
it('authenticates before parse or native reads',async()=>{d.actor.mockRejectedValue(new ReadinessError('Unauthorized',401));expect((await GET(new Request('http://local'))).status).toBe(401);expect((await POST(new Request('http://local',{method:'POST',body:'bad'}))).status).toBe(401);expect(d.decide).not.toHaveBeenCalled()})
it('writes exact actor-bound strict decision and private receipt',async()=>{const result=await POST(new Request('http://local',{method:'POST',body:JSON.stringify(body)}));expect(result.status).toBe(200);expect(result.headers.get('Cache-Control')).toBe('private, no-store');expect(d.decide).toHaveBeenCalledWith('actual-actor',body);expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify({...body,actorId:id})}))).status).toBe(400)})
it('rejects both declared and streamed overlimits',async()=>{for(const request of[new Request('http://local',{method:'POST',headers:{'content-length':'32769'},body:'{}'}),new Request('http://local',{method:'POST',body:'x'.repeat(32769)})])expect((await POST(request)).status).toBe(413);expect(d.decide).not.toHaveBeenCalled()})
it('does not disclose internal failures and closes old unversioned writes',async()=>{d.read.mockRejectedValue(new Error('sensitive query detail'));const response=await GET(new Request(`http://local?propertyId=${id}`));expect(response.status).toBe(503);expect(await response.json()).toEqual({error:'Readiness review is unavailable.'});expect((await PUT()).status).toBe(410)})
it('validates selected history and keeps known permission failures',async()=>{expect((await GET(new Request(`http://local?propertyId=${id}&kind=version`))).status).toBe(400);d.read.mockRejectedValue(new ReadinessError('Forbidden',403));expect((await GET(new Request(`http://local?propertyId=${id}`))).status).toBe(403)})
