'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {reviewJson} from './ReviewCasePanel'
import {ReviewPublicationPanel} from './ReviewPublicationPanel'
type ResponseRow={id:string;version:number;source_version:number|null;response_text:string;status:string;tone:string|null;response_type:string|null;ai_model:string|null;context_hash:string|null;content_hash:string|null;created_at:string;superseded_at:string|null;decision_reason:string|null;posting_mode:string|null;posted_at:string|null}
type Generation={id:string;source_version:number;state:string;version:number;response_id:string|null;error_code:string|null;created_at:string}
type Workspace={responses:ResponseRow[];responseCursor:string|null;generations:Generation[];generationCursor:string|null;sourceVersion:number;contextHash:string;responseSetHash:string;pendingResponses:Array<{id:string;legacy:boolean}>;source:{propertyName:string;brandVoice:string|null;websiteUrl:string|null;defaultTone:string};canApprove:boolean;modelExecutionPaused:boolean}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50',field='mt-1 w-full rounded-lg border bg-transparent p-2'
const labels:Record<string,string>={queued:'Saved; waiting to start',running:'Started; result unconfirmed',result_ready:'Result saved; ready to recover',completed:'Draft saved for review',held:'Generation needs review',stopped:'Stopped'}
const issues:Record<string,string>={stale_context:'The review or property facts changed. This result has not replaced the current response.',stale_responses:'Pending responses changed before this draft could be saved.',source_or_access_changed:'The source, pending drafts or requester access changed before execution.',invalid_output:'The saved result did not meet its response and evidence requirements.',model_uncertain:'The model outcome is unconfirmed. This request will not run again automatically.'}
export function ReviewResponsePanel(props:{propertyId:string;reviewId:string;onSaved?:()=>void}){return <ResponsePanel key={`${props.propertyId}:${props.reviewId}`} {...props}/>}
function ResponsePanel({propertyId,reviewId,onSaved}:{propertyId:string;reviewId:string;onSaved?:()=>void}){
 const [data,setData]=useState<Workspace|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[pending,setPending]=useState<Record<string,unknown>|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[generationReason,setGenerationReason]=useState('')
 const active=useRef(true),controller=useRef<AbortController|null>(null),url=`/api/reviewflow/respond?propertyId=${propertyId}&reviewId=${reviewId}`
 const reload=useCallback(async()=>{controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);setError('');try{const result=await reviewJson<Workspace>(url,{signal:c.signal});if(!c.signal.aborted)setData(result)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Saved responses unavailable.')}finally{if(!c.signal.aborted)setLoading(false)}},[url])
 useEffect(()=>{active.current=true;void reload();return()=>{active.current=false;controller.current?.abort()}},[reload])
 const poll=data&&!data.modelExecutionPaused&&data.generations.some(r=>['queued','running'].includes(r.state))
 useEffect(()=>{if(!poll||busy||pending)return;const timer=setTimeout(()=>void reload(),5000);return()=>clearTimeout(timer)},[poll,busy,pending,data,reload])
 async function send(body:Record<string,unknown>){if(busy)return;setBusy(true);setPending(body);setError('');setNotice('');try{const result=await reviewJson<{result:Record<string,unknown>;modelExecutionPaused:boolean}>('/api/reviewflow/respond',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!active.current)return;setPending(null);setGenerationReason('');setNotice(result.result.state==='held'?'The saved result needs review. It has not changed the response.':body.action==='stop_generation'?'Generation stopped. Late results will remain saved without replacing drafts.':body.action==='generate'&&result.modelExecutionPaused?'Generation request saved. Model execution is paused.':'Decision saved. Review the confirmed response status below.');await reload();onSaved?.()}catch(e){if(active.current)setError(e instanceof Error?e.message:'Decision unconfirmed. Retry the same decision.')}finally{if(active.current)setBusy(false)}}
 function decide(input:Record<string,unknown>){void send({propertyId,requestId:crypto.randomUUID(),...input})}
 async function more(kind:'response'|'generation'){if(!data)return;setBusy(true);setError('');try{const result=await reviewJson<Workspace>(`${url}&${kind}Cursor=${kind==='response'?data.responseCursor:data.generationCursor}`);if(active.current)setData(prev=>prev?kind==='response'?{...prev,responseCursor:result.responseCursor,responses:[...prev.responses,...result.responses.filter(r=>!prev.responses.some(p=>p.id===r.id))]}:{...prev,generationCursor:result.generationCursor,generations:[...prev.generations,...result.generations.filter(r=>!prev.generations.some(p=>p.id===r.id))]}:result)}catch(e){if(active.current)setError(e instanceof Error?e.message:'More history unavailable.')}finally{if(active.current)setBusy(false)}}
 const locked=loading||busy||!!pending||!!error
 return <section aria-label="Saved review responses" className="space-y-4 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Public response drafts</h3><button className={button} disabled={loading||busy} onClick={()=>{setPending(null);void reload()}}>Reload responses</button></div>
 <p className="text-sm text-slate-500">Save and review the exact response before publication. Editing creates a new draft and replaces pending approvals.</p>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}{pending&&<button className={button} disabled={busy} onClick={()=>void send(pending)}>Retry same response decision</button>}
 {loading&&!data?<p role="status">Loading saved responses…</p>:data&&<>
  {data.modelExecutionPaused&&<p className="text-sm text-amber-700">Model execution is paused. You can write drafts and recover model results already saved.</p>}
  <ResponseEditor key={`${data.contextHash}:${data.responseSetHash}`} data={data} reviewId={reviewId} locked={locked} decide={decide}/>
  <div className="space-y-3"><h4 className="font-medium">Response history</h4>{data.responses.length===0&&<p className="text-sm text-slate-500">No response drafts have been saved.</p>}{data.responses.map(row=><ResponseReview key={`${row.id}:${row.version}`} row={row} data={data} locked={locked} decide={decide}/>)}{data.responseCursor&&<button className={button} disabled={locked} onClick={()=>void more('response')}>Load more response history</button>}</div>
  <div className="space-y-3"><h4 className="font-medium">Saved generation requests</h4><label className="block text-sm">Reason for generation decision<textarea className={field} aria-label="Reason for generation decision" value={generationReason} maxLength={2000} disabled={locked} onChange={e=>setGenerationReason(e.target.value)}/></label>{data.generations.length===0&&<p className="text-sm text-slate-500">No saved response generation requests.</p>}{data.generations.map(r=><article key={r.id} aria-label={`Response generation ${r.id}`} className="space-y-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><p className="font-medium">{labels[r.state]||'Review required'}</p><p className="text-xs text-slate-500">{new Date(r.created_at).toLocaleString()}</p>{r.source_version!==data.sourceVersion&&<p className="text-amber-700">Based on an earlier review version.</p>}{r.error_code&&<p>{issues[r.error_code]||'Review this saved result before starting new work.'}</p>}<div className="flex flex-wrap gap-2">{['queued','running','result_ready'].includes(r.state)&&<button className={button} disabled={locked||generationReason.trim().length<3} onClick={()=>decide({action:'stop_generation',generationRequestId:r.id,expectedVersion:r.version,reason:generationReason})}>Stop response generation</button>}{['queued','result_ready'].includes(r.state)&&<button className={button} disabled={locked||generationReason.trim().length<3||(r.state==='queued'&&data.modelExecutionPaused)} onClick={()=>decide({action:'recover_generation',generationRequestId:r.id,expectedVersion:r.version,reason:generationReason})}>{r.state==='result_ready'?'Recover saved response':'Start saved generation'}</button>}</div></article>)}{data.generationCursor&&<button className={button} disabled={locked} onClick={()=>void more('generation')}>Load more generation history</button>}</div>
 <ReviewPublicationPanel propertyId={propertyId} reviewId={reviewId} refreshKey={`${data.contextHash}:${data.responses.map(r=>`${r.id}:${r.version}`).join(',')}`} onSaved={()=>{void reload();onSaved?.()}}/>
 </>}
 </section>
}
function ResponseEditor({data,reviewId,locked,decide}:{data:Workspace;reviewId:string;locked:boolean;decide:(v:Record<string,unknown>)=>void}){
 const current=data.responses.find(r=>!r.superseded_at&&['draft','approved'].includes(r.status)),[text,setText]=useState(current?.response_text||''),[reason,setReason]=useState(''),[tone,setTone]=useState(current?.tone||data.source.defaultTone||'professional'),[replace,setReplace]=useState(false)
 const base={reviewId,sourceVersion:data.sourceVersion,contextHash:data.contextHash,responseSetHash:data.responseSetHash,replacePending:replace,tone,reason},disabled=locked||reason.trim().length<3||(data.pendingResponses.length>0&&!replace)
 return <div className="space-y-3 text-sm"><details><summary className="cursor-pointer font-medium">Property facts used for this draft</summary><p className="pt-2">{data.source.propertyName}</p>{data.source.brandVoice&&<p>{data.source.brandVoice}</p>}{data.source.websiteUrl&&<p className="break-all">{data.source.websiteUrl}</p>}<p className="text-slate-500">Review these facts and the source review before approving a public response.</p></details>
 <label className="block">Response text<textarea className={field} aria-label="Response text" rows={6} maxLength={1400} value={text} disabled={locked} onChange={e=>setText(e.target.value)}/></label><label className="block">Response tone<select className={field} aria-label="Response tone" value={tone} disabled={locked} onChange={e=>setTone(e.target.value)}>{['professional','empathetic','friendly','apologetic'].map(t=><option key={t} value={t}>{t}</option>)}</select></label><label className="block">Reason for draft<textarea className={field} aria-label="Reason for draft" maxLength={2000} value={reason} disabled={locked} onChange={e=>setReason(e.target.value)}/></label>
 {data.pendingResponses.length>0&&<label className="flex items-start gap-2"><input type="checkbox" checked={replace} disabled={locked} onChange={e=>setReplace(e.target.checked)}/><span>Replace the {data.pendingResponses.length} pending draft(s) and approvals with a new draft. Their history will be retained.</span></label>}
 <div className="flex flex-wrap gap-2"><button className={button} disabled={disabled||text.trim().length<20} onClick={()=>decide({action:'draft',...base,responseText:text})}>Save response draft</button><button className={button} disabled={disabled||data.generations.some(r=>['queued','running','result_ready'].includes(r.state))} onClick={()=>decide({action:'generate',...base})}>{data.modelExecutionPaused?'Save generation request':'Generate response draft'}</button></div>
 </div>
}
function ResponseReview({row,data,locked,decide}:{row:ResponseRow;data:Workspace;locked:boolean;decide:(v:Record<string,unknown>)=>void}){
 const [reason,setReason]=useState(''),legacy=!row.source_version||!row.context_hash||!row.content_hash,stale=row.context_hash!==data.contextHash,active=!row.superseded_at&&['draft','approved'].includes(row.status),disabled=locked||reason.trim().length<3||!data.canApprove||legacy
 const input={responseId:row.id,expectedVersion:row.version,sourceVersion:row.source_version,contextHash:row.context_hash,contentHash:row.content_hash,reason}
 return <article aria-label={`Saved response ${row.id}`} className="space-y-3 rounded-lg border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{row.superseded_at?'Superseded':row.status==='approved'?'Approved; not yet published':row.status==='posted'?row.posting_mode==='manual_confirmed'?'Publication reported by staff':'Publication recorded':row.status==='rejected'?'Rejected':'Draft awaiting review'}</strong><span className="text-xs text-slate-500">{new Date(row.created_at).toLocaleString()}</span></div><p className="whitespace-pre-wrap">{row.response_text}</p><p className="text-xs text-slate-500">{row.ai_model?`Generated with ${row.ai_model}`:'Staff draft'} · {row.tone||'Tone not recorded'}</p>{row.decision_reason&&<p>Decision: {row.decision_reason}</p>}{legacy?<p className="text-amber-700">This older response has no verified source version. Review its text and save a new draft before approval.</p>:stale&&active?<p className="text-amber-700">The review or property facts changed. Save a new draft using the current source before approving.</p>:null}
 {active&&!legacy&&<><label className="block">Reason for response decision<textarea className={field} aria-label="Reason for response decision" value={reason} maxLength={2000} disabled={locked||!data.canApprove} onChange={e=>setReason(e.target.value)}/></label>{!data.canApprove&&<p className="text-slate-500">A manager or admin must review this response.</p>}<div className="flex flex-wrap gap-2">{row.status==='draft'&&<button className={button} disabled={disabled||stale} onClick={()=>decide({action:'approve',...input})}>Approve exact response</button>}<button className={button} disabled={disabled} onClick={()=>decide({action:'reject',...input})}>Reject response</button></div></>}
 </article>
}
