'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {reviewJson} from './ReviewCasePanel'
type Counts={selected:number;pending:number;analyzed:number;staffReview:number;held:number;stopped:number}
type Batch={id:string;state:string;version:number;selection_count:number;summary:Counts;created_at:string}
type Item={id:string;reviewId:string;sourceVersion:number;position:number;state:string;analysisRequestId:string|null;ownsRequest:boolean|null;errorCode:string|null;source:{text:string;reviewerName:string;platform:string;rating:number|null}}
type Detail={id:string;state:string;version:number;selected:number;summary:Counts;maxModelCalls:number|null;model:{name:string;promptVersion:string;maxOutputTokens:number};createdAt:string;approvedAt:string|null;items:Item[];nextPosition:number|null}
type Workspace={batches:Batch[];nextCursor:string|null;canManage:boolean;modelExecutionPaused:boolean}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50',field='mt-1 w-full rounded-lg border bg-transparent p-2',labels:Record<string,string>={prepared:'Selection saved; approval required',queued:'Approved; waiting to start',running:'Analysis in progress',needs_review:'Finished with items needing staff review',completed:'Selection analyzed',stopped:'Queue stopped'}
export function ReviewAnalysisBatchPanel({propertyId,onReview,initialId}:{propertyId:string;onReview?:(id:string)=>void;initialId?:string}){return <AnalysisBatch key={propertyId} propertyId={propertyId} onReview={onReview} initialId={initialId}/>}
function AnalysisBatch({propertyId,onReview,initialId}:{propertyId:string;onReview?:(id:string)=>void;initialId?:string}){
 const [data,setData]=useState<Workspace|null>(null),[detail,setDetail]=useState<Detail|null>(null),[selected,setSelected]=useState(initialId||''),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState<Record<string,unknown>|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[prepareReason,setPrepareReason]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false)
 const active=useRef(true),controller=useRef<AbortController|null>(null),detailController=useRef<AbortController|null>(null),url=`/api/reviewflow/analyze-batch?propertyId=${propertyId}`
 const reload=useCallback(async()=>{controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);try{const r=await reviewJson<Workspace>(url,{signal:c.signal});if(!c.signal.aborted)setData(r)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Saved analysis queues unavailable.')}finally{if(!c.signal.aborted)setLoading(false)}},[url])
 const load=useCallback(async(id:string)=>{detailController.current?.abort();const c=new AbortController();detailController.current=c;setDetailLoading(true);try{const r=await reviewJson<{batch:Detail}>(`${url}&batchId=${id}`,{signal:c.signal});if(!c.signal.aborted)setDetail(r.batch)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Saved analysis selection unavailable.')}finally{if(!c.signal.aborted)setDetailLoading(false)}},[url])
 useEffect(()=>{active.current=true;void reload();return()=>{active.current=false;controller.current?.abort();detailController.current?.abort()}},[reload])
 useEffect(()=>{if(initialId)setSelected(initialId)},[initialId])
 useEffect(()=>{setDetail(null);setConfirmed(false);setReason('');if(selected)void load(selected)},[selected,load])
 useEffect(()=>{if(!selected||!detail||!['queued','running'].includes(detail.state)||data?.modelExecutionPaused||error||busy||pending)return;const t=setInterval(()=>{void load(selected);void reload()},5000);return()=>clearInterval(t)},[selected,detail,data?.modelExecutionPaused,error,busy,pending,load,reload])
 async function decide(body:Record<string,unknown>){if(busy)return;setBusy(true);setPending(body);setError('');setNotice('');try{const r=await reviewJson<{result:{batchId?:string;state:string}}>('/api/reviewflow/analyze-batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!active.current)return;setPending(null);setConfirmed(false);setReason('');const id=r.result.batchId||selected;setSelected(id);await reload();if(id)await load(id);setNotice(body.action==='prepare'?'The current selection is saved. Review its scope before execution.':body.action==='stop'?'This queue is stopped. Late results are retained; independent analysis is not cancelled.':'Analysis decision saved. The counts below show confirmed progress.')}catch(e){if(active.current)setError(e instanceof Error?e.message:'Analysis queue decision unconfirmed. Retry the same decision.')}finally{if(active.current)setBusy(false)}}
 const submit=(input:Record<string,unknown>)=>void decide({propertyId,requestId:crypto.randomUUID(),...input})
 async function moreHistory(){if(!data?.nextCursor)return;setBusy(true);try{const r=await reviewJson<Workspace>(`${url}&cursor=${data.nextCursor}`);if(active.current)setData(prev=>prev?{...prev,nextCursor:r.nextCursor,batches:[...prev.batches,...r.batches.filter(b=>!prev.batches.some(p=>p.id===b.id))]}:r)}catch(e){if(active.current)setError(e instanceof Error?e.message:'Queue history unavailable.')}finally{if(active.current)setBusy(false)}}
 async function moreItems(){if(!detail||detail.nextPosition===null)return;setBusy(true);try{const r=await reviewJson<{batch:Detail}>(`${url}&batchId=${detail.id}&afterPosition=${detail.nextPosition}`);if(active.current)setDetail(prev=>prev?.id===r.batch.id?{...r.batch,items:[...prev.items,...r.batch.items.filter(i=>!prev.items.some(p=>p.id===i.id))]}:prev)}catch(e){if(active.current)setError(e instanceof Error?e.message:'Saved selection page unavailable.')}finally{if(active.current)setBusy(false)}}
 const locked=loading||busy||!!pending||!!error,control=(action:string)=>detail&&submit({action,batchId:detail.id,expectedVersion:detail.version,reason,...(action==='approve'?{maxModelCalls:detail.selected}:{})})
 return <section aria-label="Property review analysis" className="space-y-4 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Analyze this property’s reviews</h3><button className={button} disabled={loading||busy} onClick={()=>{setPending(null);setError('');void reload();if(selected)void load(selected)}}>Reload analysis queues</button></div><p className="text-sm text-slate-500">Save all current review versions that have no recorded analysis. The selection stays fixed, can be reviewed page by page, and resumes from saved results. New reviews require a new selection.</p>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}{pending&&<button className={button} disabled={busy} onClick={()=>void decide(pending)}>Retry same queue decision</button>}{loading&&!data?<p>Loading saved analysis queues…</p>:data&&<>{data.modelExecutionPaused&&<p className="text-sm text-amber-700">Model execution is paused. Saved selections, decisions and existing result recovery are available.</p>}<label className="block text-sm">Reason for this analysis selection<textarea aria-label="Reason for this analysis selection" className={field} value={prepareReason} disabled={locked} maxLength={2000} onChange={e=>setPrepareReason(e.target.value)}/></label><button className={button} disabled={locked||prepareReason.trim().length<3} onClick={()=>submit({action:'prepare',scope:'unanalyzed_current',reason:prepareReason})}>Save full review selection</button><div className="space-y-2">{!data.batches.length&&<p className="text-sm text-slate-500">No saved analysis queues.</p>}{data.batches.map(b=><button key={b.id} aria-pressed={selected===b.id} className={`${button} block w-full text-left ${selected===b.id?'border-rose-500':''}`} disabled={busy||!!pending} onClick={()=>{setError('');setSelected(b.id)}}>{labels[b.state]||b.state} · {b.selection_count} reviews · {new Date(b.created_at).toLocaleString()}</button>)}{data.nextCursor&&<button className={button} disabled={locked} onClick={()=>void moreHistory()}>Load more analysis queues</button>}</div></>}
 {detailLoading&&!detail&&<p>Loading saved selection…</p>}{detail&&<article aria-label="Saved analysis selection" className="space-y-3 rounded-lg border p-3"><h4 className="font-medium">{labels[detail.state]||detail.state}</h4><p className="text-sm">{detail.selected} exact review versions selected on {new Date(detail.createdAt).toLocaleString()}.</p><Counts value={detail.summary}/><p className="text-sm text-slate-500">Analysis uses {detail.model.name}, up to {detail.model.maxOutputTokens} output tokens per review. It does not generate or publish responses. A saved uncertain model call is never repeated automatically.</p>{['queued','running'].includes(detail.state)&&<p className="text-sm">The scheduled worker continues approved work. You can recover available results here. Items waiting for an unconfirmed or independently requested analysis remain visible.</p>}{detail.state==='needs_review'&&<p className="text-sm text-amber-700">Open the affected reviews to inspect evidence or make a new analysis decision. A completed selection does not resolve its staff cases.</p>}
 {data?.canManage&&['prepared','queued','running'].includes(detail.state)&&<><label className="block text-sm">Reason for queue decision<textarea aria-label="Reason for queue decision" className={field} value={reason} disabled={locked} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>{detail.state==='prepared'&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={locked} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I approve up to {detail.selected} model analyses for this saved selection.</span></label>}<div className="flex flex-wrap gap-2">{detail.state==='prepared'?<button className={button} disabled={locked||detailLoading||!confirmed||reason.trim().length<3} onClick={()=>control('approve')}>Approve saved analysis scope</button>:<button className={button} disabled={locked||detailLoading||reason.trim().length<3} onClick={()=>control('recover')}>Recover analysis queue</button>}<button className={button} disabled={locked||detailLoading||reason.trim().length<3} onClick={()=>control('stop')}>Stop analysis queue</button></div></>}{!data?.canManage&&['prepared','queued','running'].includes(detail.state)&&<p className="text-sm">A manager or admin must approve or control this selection.</p>}
 <div className="space-y-3">{detail.items.map(i=><article key={i.id} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><p className="font-medium">Review {i.position} · {i.source.platform} · Version {i.sourceVersion} · {i.state.replaceAll('_',' ')}</p><p>{i.source.reviewerName} · {i.source.rating===null?'No rating':`${i.source.rating}/5`}</p><p className="mt-2 whitespace-pre-wrap break-words">{i.source.text}</p>{i.errorCode&&<p className="mt-2 text-amber-700">{({source_changed:'This source changed after selection.',source_unavailable:'Readable source text is required.',batch_authority_changed:'The original approval is no longer authorized.',batch_stopped:'The queue was stopped.',model_uncertain:'The model result is unconfirmed.',invalid_output:'The saved model result requires review.',current_analysis_reused:'A current saved analysis was reused.'} as Record<string,string>)[i.errorCode]||'Open this review to inspect its saved analysis.'}</p>}{i.analysisRequestId&&i.ownsRequest===false&&<p className="text-slate-500">Following an independently requested analysis.</p>}{onReview&&<button className={`${button} mt-2`} onClick={()=>onReview(i.reviewId)}>Open review {i.position}</button>}</article>)}{detail.nextPosition!==null&&<button className={button} disabled={locked||detailLoading} onClick={()=>void moreItems()}>Load more selected reviews</button>}</div>
 </article>}</section>
}
function Counts({value}:{value:Counts}){return <p role="status" className="text-sm">{value.analyzed||0} analyzed · {value.staffReview||0} need staff review · {value.pending||0} waiting · {value.held||0} held · {value.stopped||0} stopped</p>}
