'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
type CaseRow={id:string;version:number;status:string;priority:string;owner_profile_id:string|null;sla_due_at:string|null;remediation_state:string;resolution_notes:string|null;reopened_count:number}
type Ticket={id:string;version:number;title:string;description:string|null;status:string;priority:string;assigned_to:string|null;resolution_notes:string|null}
type Member={id:string;full_name:string|null}
type EventRow={id:string;event_type:string;actor_profile_id:string|null;actor_label:string|null;payload:{reason?:string;note?:string;resolutionNotes?:string;previousResolution?:string;before?:{status?:string};after?:{status?:string}};created_at:string}
type Workspace={case:CaseRow|null;sourceVersion:number;events:EventRow[];nextCursor:string|null}
type Tickets={tickets:Ticket[];nextCursor:string|null}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50',field='mt-1 w-full rounded-lg border bg-transparent p-2'
export async function reviewJson<T>(url:string,init:RequestInit={}):Promise<T>{const response=await fetch(url,{...init,cache:'no-store',signal:init.signal?AbortSignal.any([init.signal,AbortSignal.timeout(20_000)]):AbortSignal.timeout(20_000)});const body=await response.json();if(!response.ok)throw new Error(body.error||'The saved review workspace is unavailable.');return body}
const label=(value:string)=>value.replaceAll('_',' ').replaceAll('.',' ')
export function ReviewCasePanel(props:{propertyId:string;reviewId:string;refreshVersion?:number;onSaved?:()=>void}){return <CasePanel key={`${props.propertyId}:${props.reviewId}`} {...props}/>}
function CasePanel({propertyId,reviewId,refreshVersion,onSaved}:{propertyId:string;reviewId:string;refreshVersion?:number;onSaved?:()=>void}){
 const [data,setData]=useState<Workspace|null>(null),[tickets,setTickets]=useState<Tickets|null>(null),[members,setMembers]=useState<Member[]>([]),[memberCursor,setMemberCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<Record<string,unknown>|null>(null)
 const active=useRef(true),controller=useRef<AbortController|null>(null)
 const url=`/api/reviewflow/cases?propertyId=${propertyId}&reviewId=${reviewId}`,ticketUrl=`/api/reviewflow/tickets?propertyId=${propertyId}&reviewId=${reviewId}`,memberUrl=`/api/reviewflow/cases?view=members&propertyId=${propertyId}`
 const reload=useCallback(async()=>{controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);setError('');try{const [saved,work,team]=await Promise.all([reviewJson<Workspace>(url,{signal:c.signal}),reviewJson<Tickets>(ticketUrl,{signal:c.signal}),reviewJson<{members:Member[];nextCursor:string|null}>(memberUrl,{signal:c.signal})]);if(c.signal.aborted)return;setData(saved);setTickets(work);setMembers(team.members);setMemberCursor(team.nextCursor)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Case could not be loaded.')}finally{if(!c.signal.aborted)setLoading(false)}},[url,ticketUrl,memberUrl])
 useEffect(()=>{active.current=true;void reload();return()=>{active.current=false;controller.current?.abort()}},[reload])
 // A delayed drawer refresh must not erase a newer decision or its error.
 useEffect(()=>{if(data&&!loading&&!busy&&!pending&&!error&&refreshVersion!==undefined&&refreshVersion>(data.case?.version||0))void reload()},[data,loading,busy,pending,error,refreshVersion,reload])
 async function save(body:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setNotice('');setPending(body);try{await reviewJson('/api/reviewflow/cases',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!active.current)return;setPending(null);setNotice('Decision and case history saved.');await reload();onSaved?.()}catch(e){if(active.current)setError(e instanceof Error?e.message:'Decision unconfirmed. Retry the same decision.')}finally{if(active.current)setBusy(false)}}
 function decide(input:Record<string,unknown>){if(!data)return;void save({propertyId,requestId:crypto.randomUUID(),reviewId,sourceVersion:data.sourceVersion,...(data.case?{caseId:data.case.id,expectedVersion:data.case.version}:{}),...input})}
 async function more(kind:'events'|'tickets'|'members'){setBusy(true);setError('');try{if(kind==='events'){const next=await reviewJson<Workspace>(`${url}&cursor=${data?.nextCursor}`);if(active.current)setData(prev=>prev?{...prev,nextCursor:next.nextCursor,events:[...prev.events,...next.events.filter(e=>!prev.events.some(p=>p.id===e.id))]}:next)}else if(kind==='tickets'){const next=await reviewJson<Tickets>(`${ticketUrl}&cursor=${tickets?.nextCursor}`);if(active.current)setTickets(prev=>({nextCursor:next.nextCursor,tickets:[...prev?.tickets||[],...next.tickets.filter(t=>!prev?.tickets.some(p=>p.id===t.id))]}))}else{const next=await reviewJson<{members:Member[];nextCursor:string|null}>(`${memberUrl}&cursor=${memberCursor}`);if(active.current){setMembers(prev=>[...prev,...next.members.filter(m=>!prev.some(p=>p.id===m.id))]);setMemberCursor(next.nextCursor)}}}catch(e){if(active.current)setError(e instanceof Error?e.message:'The next page is unavailable.')}finally{if(active.current)setBusy(false)}}
 const locked=loading||busy||!!pending||!!error
 return <section aria-label="Case decisions" className="space-y-4 rounded-xl border p-4">
  <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Case and staff work</h3><button className={button} disabled={busy||loading} onClick={()=>{setPending(null);void reload()}}>Reload case</button></div>
  <p className="text-sm text-slate-500">Record who owns this issue, the staff work and the actual outcome. A response being posted does not by itself confirm that the issue was resolved.</p>
  {error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}{pending&&<button className={button} disabled={busy} onClick={()=>void save(pending)}>Retry same case decision</button>}
  {loading&&!data?<p role="status">Loading saved case…</p>:data&&<CaseEditor key={`${data.case?.id||'new'}:${data.case?.version||0}:${data.sourceVersion}`} data={data} members={members} locked={locked} decide={decide}/>}
  {memberCursor&&<button className={button} disabled={locked} onClick={()=>void more('members')}>Load more team members</button>}
  {!!data?.case&&<div className="space-y-3"><h4 className="font-medium">Staff tickets</h4>{tickets?.tickets.length===0&&<p className="text-sm text-slate-500">No staff tickets are saved for this review.</p>}{tickets?.tickets.map(ticket=><TicketEditor key={`${ticket.id}:${ticket.version}:${data.case?.version}`} ticket={ticket} members={members} locked={locked||['resolved','dismissed'].includes(data.case?.status||'')} decide={decide}/>)}{tickets?.nextCursor&&<button className={button} disabled={locked} onClick={()=>void more('tickets')}>Load more staff tickets</button>}</div>}
  {!!data?.events.length&&<div className="space-y-3"><h4 className="font-medium">Saved case history</h4>{data.events.map(e=><article key={e.id} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><p className="font-medium">{label(e.event_type)}</p><p className="text-xs text-slate-500">{new Date(e.created_at).toLocaleString()} · {e.actor_profile_id?(members.find(m=>m.id===e.actor_profile_id)?.full_name||'Staff member'):label(e.actor_label||'Recorded workflow')}</p>{e.payload.reason&&<p>{e.payload.reason}</p>}{e.payload.note&&<p className="whitespace-pre-wrap">{e.payload.note}</p>}{e.payload.resolutionNotes&&<p className="whitespace-pre-wrap">Outcome: {e.payload.resolutionNotes}</p>}{e.payload.previousResolution&&<p className="whitespace-pre-wrap">Previous outcome: {e.payload.previousResolution}</p>}</article>)}{data.nextCursor&&<button className={button} disabled={locked} onClick={()=>void more('events')}>Load more case history</button>}</div>}
 </section>
}
function TeamSelect({members,value,onChange,disabled,label}:{members:Member[];value:string;onChange:(v:string)=>void;disabled:boolean;label:string}){return <select aria-label={label} className={field} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Unassigned</option>{value&&!members.some(m=>m.id===value)&&<option value={value}>Current assignee (load more team members)</option>}{members.map(m=><option key={m.id} value={m.id}>{m.full_name||'Team member'}</option>)}</select>}
function CaseEditor({data,members,locked,decide}:{data:Workspace;members:Member[];locked:boolean;decide:(v:Record<string,unknown>)=>void}){
 const row=data.case,closed=!!row&&['resolved','dismissed'].includes(row.status)
 const [reason,setReason]=useState(''),[notes,setNotes]=useState(''),[note,setNote]=useState(''),[priority,setPriority]=useState(row?.priority||'medium'),[status,setStatus]=useState(row?.status||'open'),[owner,setOwner]=useState(row?.owner_profile_id||''),[remediation,setRemediation]=useState(row?.remediation_state||'none'),[deadline,setDeadline]=useState(row?.sla_due_at?new Date(new Date(row.sla_due_at).getTime()-new Date(row.sla_due_at).getTimezoneOffset()*60_000).toISOString().slice(0,16):''),[title,setTitle]=useState(''),[description,setDescription]=useState('')
 const disabled=locked||reason.trim().length<3
 return <div className="space-y-3 text-sm">
  {row&&<p>Case: <strong>{label(row.status)}</strong>{row.reopened_count>0?` · Reopened ${row.reopened_count} time(s)`:''}</p>}
  {row?.resolution_notes&&<p className="whitespace-pre-wrap rounded-lg bg-slate-50 p-3 dark:bg-slate-800">Recorded outcome: {row.resolution_notes}</p>}
  <label className="block">Reason for case decision<textarea aria-label="Reason for case decision" className={field} value={reason} disabled={locked} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>
  {!row?<button className={button} disabled={disabled} onClick={()=>decide({action:'create',reason})}>Open case</button>:<>
   {!closed&&<details><summary className="cursor-pointer font-medium">Assignment, priority and follow-up</summary><div className="space-y-3 pt-3">
    <label className="block">Case status<select aria-label="Case status" className={field} value={status} disabled={locked} onChange={e=>setStatus(e.target.value)}>{!['open','triaged','remediation'].includes(row.status)&&<option value={row.status}>{label(row.status)} (response workflow)</option>}{['open','triaged','remediation'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>
    <label className="block">Case priority<select aria-label="Case priority" className={field} value={priority} disabled={locked} onChange={e=>setPriority(e.target.value)}>{['low','medium','high','urgent'].map(p=><option key={p} value={p}>{label(p)}</option>)}</select></label>
    <label className="block">Case owner<TeamSelect label="Case owner" members={members} value={owner} onChange={setOwner} disabled={locked}/></label>
    <label className="block">Follow-up due (your local time)<input type="datetime-local" className={field} value={deadline} disabled={locked} onChange={e=>setDeadline(e.target.value)}/></label>
    <label className="block">Remediation progress<select aria-label="Remediation progress" className={field} value={remediation} disabled={locked} onChange={e=>setRemediation(e.target.value)}>{['none','recommended','in_progress','completed'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>
    <button className={button} disabled={disabled} onClick={()=>decide({action:'update',reason,...(['open','triaged','remediation'].includes(status)?{status}:{}),priority,ownerId:owner||null,slaDueAt:deadline?new Date(deadline).toISOString():null,remediationState:remediation})}>Save case details</button>
   </div></details>}
   <label className="block">Case note<textarea className={field} value={note} maxLength={4000} disabled={locked} onChange={e=>setNote(e.target.value)}/></label><button className={button} disabled={disabled||note.trim().length<3} onClick={()=>decide({action:'note',reason,note})}>Add case note</button>
   {closed?<button className={button} disabled={disabled} onClick={()=>decide({action:'reopen',reason})}>Reopen case</button>:<>
    <details><summary className="cursor-pointer font-medium">Create staff ticket</summary><div className="space-y-3 pt-3"><label className="block">Ticket title<input className={field} value={title} maxLength={200} disabled={locked} onChange={e=>setTitle(e.target.value)}/></label><label className="block">Ticket details<textarea className={field} value={description} maxLength={4000} disabled={locked} onChange={e=>setDescription(e.target.value)}/></label><p>New tickets use the case priority and owner shown above.</p><button className={button} disabled={disabled||title.trim().length<3} onClick={()=>decide({action:'ticket.create',reason,title,description,priority,ownerId:owner||null})}>Save staff ticket</button></div></details>
    <label className="block">Resolution or dismissal evidence<textarea className={field} value={notes} maxLength={4000} disabled={locked} onChange={e=>setNotes(e.target.value)} placeholder="What was done and how was the result confirmed?"/></label>
    <p className="text-xs text-slate-500">Resolve or close open staff tickets first. This records a staff-reported outcome; it does not send a response or prove resident satisfaction.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={disabled||notes.trim().length<3} onClick={()=>decide({action:'resolve',reason,resolutionNotes:notes})}>Resolve case</button><button className={button} disabled={disabled||notes.trim().length<3} onClick={()=>decide({action:'dismiss',reason,resolutionNotes:notes})}>Dismiss case</button></div>
   </>}
  </>}
 </div>
}
function TicketEditor({ticket,members,locked,decide}:{ticket:Ticket;members:Member[];locked:boolean;decide:(v:Record<string,unknown>)=>void}){
 const [reason,setReason]=useState(''),[notes,setNotes]=useState(''),[status,setStatus]=useState(ticket.status),[priority,setPriority]=useState(ticket.priority),[owner,setOwner]=useState(ticket.assigned_to||''),[title,setTitle]=useState(ticket.title),[description,setDescription]=useState(ticket.description||'');const closed=['resolved','closed'].includes(ticket.status),disabled=locked||reason.trim().length<3
 const identity={ticketId:ticket.id,expectedTicketVersion:ticket.version,reason}
 return <article aria-label={`Staff ticket ${ticket.title}`} className="space-y-3 rounded-lg border p-3 text-sm"><h5 className="font-medium">{ticket.title} · {label(ticket.status)}</h5>{ticket.resolution_notes&&<p className="whitespace-pre-wrap">Outcome: {ticket.resolution_notes}</p>}<details><summary className="cursor-pointer">Review ticket</summary><div className="space-y-3 pt-3">
 <label className="block">Reason for ticket decision<textarea className={field} value={reason} disabled={locked} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>
 {closed?<button className={button} disabled={disabled} onClick={()=>decide({action:'ticket.reopen',...identity})}>Reopen ticket</button>:<>
 <label className="block">Ticket title<input className={field} value={title} disabled={locked} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><label className="block">Ticket details<textarea className={field} value={description} disabled={locked} maxLength={4000} onChange={e=>setDescription(e.target.value)}/></label>
 <label className="block">Ticket status<select aria-label="Ticket status" className={field} value={status} disabled={locked} onChange={e=>setStatus(e.target.value)}>{['open','in_progress','resolved','closed'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="block">Ticket priority<select aria-label="Ticket priority" className={field} value={priority} disabled={locked} onChange={e=>setPriority(e.target.value)}>{['low','medium','high','urgent'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="block">Ticket owner<TeamSelect label="Ticket owner" members={members} value={owner} onChange={setOwner} disabled={locked}/></label>
 {['resolved','closed'].includes(status)&&<label className="block">Ticket resolution evidence<textarea className={field} value={notes} disabled={locked} maxLength={4000} onChange={e=>setNotes(e.target.value)}/></label>}
 <button className={button} disabled={disabled||title.trim().length<3||(['resolved','closed'].includes(status)&&notes.trim().length<3)} onClick={()=>decide({action:'ticket.update',...identity,title,description,status,priority,ownerId:owner||null,...(['resolved','closed'].includes(status)?{resolutionNotes:notes}:{})})}>Save ticket decision</button>
 </>}
 </div></details></article>
}
