'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {ReviewCasePanel,reviewJson} from './ReviewCasePanel'
type Ticket={id:string;review_id:string|null;title:string;priority:string;status:string;description:string|null;reviews?:{reviewer_name:string|null;review_text:string|null};assigned_user?:{full_name:string|null}|null}
type Listing={tickets:Ticket[];nextCursor:string|null}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50'
export function TicketList(props:{propertyId:string;onSelectTicket?:(ticket:Ticket)=>void;compact?:boolean;limit?:number}){return <Tickets key={props.propertyId} {...props}/>}
function Tickets({propertyId,onSelectTicket,compact=false,limit=30}:{propertyId:string;onSelectTicket?:(ticket:Ticket)=>void;compact?:boolean;limit?:number}){
 const [filter,setFilter]=useState('open'),[data,setData]=useState<Listing|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Ticket|null>(null)
 const controller=useRef<AbortController|null>(null)
 const url=`/api/reviewflow/tickets?propertyId=${propertyId}&limit=${limit}${filter?`&status=${filter}`:''}`
 const load=useCallback(async(cursor?:string)=>{controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);setError('');try{const next=await reviewJson<Listing>(url+(cursor?`&cursor=${cursor}`:''),{signal:c.signal});if(!c.signal.aborted)setData(prev=>cursor&&prev?{...next,tickets:[...prev.tickets,...next.tickets.filter(t=>!prev.tickets.some(p=>p.id===t.id))]}:next)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Tickets could not be loaded.')}finally{if(!c.signal.aborted)setLoading(false)}},[url])
 useEffect(()=>{setData(null);void load();return()=>controller.current?.abort()},[load])
 return <div className="space-y-4"><div className="flex flex-wrap gap-2">{!compact&&<label className="text-sm">Ticket status <select aria-label="Filter ticket status" className="rounded-lg border bg-transparent p-2" value={filter} onChange={e=>setFilter(e.target.value)}>{['open','in_progress','resolved','closed',''].map(s=><option key={s} value={s}>{s?s.replaceAll('_',' '):'All statuses'}</option>)}</select></label>}<button className={button} disabled={loading} onClick={()=>void load()}>Reload tickets</button></div>
 {error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{loading&&!data&&<p role="status">Loading saved tickets…</p>}{!loading&&!error&&data?.tickets.length===0&&<p className="rounded-lg border p-5 text-sm text-slate-500">No saved tickets match these filters.</p>}
 {data?.tickets.map(ticket=><article key={ticket.id} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium">{ticket.title}</h3><span className="text-sm">{ticket.priority} · {ticket.status.replaceAll('_',' ')}</span></div>{ticket.reviews&&<p className="text-sm">{ticket.reviews.reviewer_name||'Anonymous reviewer'}: {ticket.reviews.review_text}</p>}{ticket.description&&<p className="whitespace-pre-wrap text-sm text-slate-500">{ticket.description}</p>}{ticket.assigned_user&&<p className="text-sm">Assigned to {ticket.assigned_user.full_name||'Team member'}</p>}<button className={button} disabled={!ticket.review_id||!!error} onClick={()=>{setSelected(ticket);onSelectTicket?.(ticket)}}>Review case and ticket</button></article>)}
 {data?.nextCursor&&<button className={button} disabled={loading||!!error} onClick={()=>void load(data.nextCursor!)}>Load more tickets</button>}
 {selected?.review_id&&<div role="dialog" aria-label="Ticket case workspace" aria-modal="true" className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-3 sm:p-8"><div className="mx-auto max-w-2xl space-y-3 rounded-xl bg-white p-4 dark:bg-slate-900"><button className={button} onClick={()=>setSelected(null)}>Close ticket workspace</button><ReviewCasePanel propertyId={propertyId} reviewId={selected.review_id} onSaved={()=>void load()}/></div></div>}
 </div>
}
