import type {TeamCommand,JoinCommand}from './contracts'
export type TeamWrite=TeamCommand extends infer C?C extends{requestId:string}?Omit<C,'requestId'>:never:never
export type JoinWrite=Omit<Extract<JoinCommand,{operation:'accept'|'decline'}>,'requestId'>
export type PendingTeam={id:string;hash:string}
const key=(scope:string)=>'p11.team.pending.v1:'+scope
export function pendingTeam(scope:string):PendingTeam|null{try{const value=JSON.parse(sessionStorage.getItem(key(scope))||'null');return typeof value?.id==='string'&&typeof value?.hash==='string'?value:null}catch{return null}}
export function clearPendingTeam(scope:string,id:string){if(pendingTeam(scope)?.id===id)sessionStorage.removeItem(key(scope))}
export async function teamFetch(url:string,init?:RequestInit){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(url,{...init,cache:'no-store',signal:controller.signal}),data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'Team access could not be confirmed.'),{status:r.status});return data}finally{clearTimeout(timer)}}
export function teamUrl(input:Record<string,string|number|undefined>={}){const q=new URLSearchParams();for(const[k,v]of Object.entries(input))if(v!==undefined)q.set(k,String(v));return'/api/team?'+q}
export async function postTeam(scope:string,command:TeamWrite|JoinWrite,join=false){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(command))),hash=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join(''),prior=pendingTeam(scope);if(prior&&prior.hash!==hash)throw new Error('Check the earlier team decision before changing this request.');const id=prior?.id||crypto.randomUUID();sessionStorage.setItem(key(scope),JSON.stringify({id,hash}));try{const r=await teamFetch(join?'/api/team/join':'/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,requestId:id})});if(!['saved','replayed'].includes(r.state)||r.decisionId!==id||'orgId'in command&&r.orgId!==command.orgId)throw new Error('The team receipt could not be verified. Check its saved result.');clearPendingTeam(scope,id);return r}catch(e){if(e instanceof Error&&'status'in e&&[400,403,409,413].includes(Number(e.status)))clearPendingTeam(scope,id);throw e}}
