import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import {emptyLegalDraft} from './contracts'
import {webcrypto} from 'node:crypto'
import {postLegal,pendingLegal,clearPendingLegal,legalReviewUrl} from './client'
const data=new Map<string,string>(),fetchMock=vi.fn(),property='11111111-1111-1111-1111-111111111111',command={propertyId:property,operation:'save' as const,expectedStateHash:'a'.repeat(64),sourceVersionId:null,draft:emptyLegalDraft(),reason:'Review private task'}
beforeEach(()=>{data.clear();vi.stubGlobal('crypto',webcrypto);vi.stubGlobal('sessionStorage',{getItem:(k:string)=>data.get(k)||null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)});vi.stubGlobal('fetch',fetchMock);fetchMock.mockReset()})
afterEach(()=>vi.unstubAllGlobals())
it('retains only scoped identity and digest after a lost response',async()=>{fetchMock.mockRejectedValue(new Error('lost response'));await expect(postLegal(command)).rejects.toThrow('lost');const pending=pendingLegal(property)!;expect(Object.keys(pending).sort()).toEqual(['hash','id','propertyId']);expect([...data.values()].join('')).not.toContain('Private');expect(pendingLegal('another')).toBeNull()})
it('reuses the same identity for the same request and blocks changed content while unresolved',async()=>{fetchMock.mockRejectedValue(new Error('lost'));await expect(postLegal(command)).rejects.toThrow();const id=pendingLegal(property)!.id;await expect(postLegal({...command,reason:'Changed exact request'})).rejects.toThrow('earlier legal');expect(fetchMock).toHaveBeenCalledTimes(1);await expect(postLegal(command)).rejects.toThrow();expect(JSON.parse(fetchMock.mock.calls[1][1].body).requestId).toBe(id)})
it('accepts only the exact property and decision receipt before clearing recovery',async()=>{fetchMock.mockImplementation(async(_url,init)=>{const b=JSON.parse(init.body);return Response.json({state:'saved',propertyId:b.propertyId,decisionId:b.requestId,versionId:b.requestId})});await postLegal(command);expect(pendingLegal(property)).toBeNull()})
it('keeps recovery on mismatched success and clear calls cannot discard a different identity',async()=>{fetchMock.mockResolvedValue(Response.json({state:'saved',propertyId:property,decisionId:'wrong'}));await expect(postLegal(command)).rejects.toThrow('verified');clearPendingLegal(property,'wrong');expect(pendingLegal(property)).not.toBeNull()})
it('clears a definitive stale rejection so renewed review can create a new decision',async()=>{fetchMock.mockResolvedValue(Response.json({error:'Task changed'},{status:409}));await expect(postLegal(command)).rejects.toThrow('changed');expect(pendingLegal(property)).toBeNull()})
it('storage failure prevents an untracked write',async()=>{vi.stubGlobal('sessionStorage',{getItem:()=>null,setItem:()=>{throw new Error('Storage unavailable')}});await expect(postLegal(command)).rejects.toThrow('Storage unavailable');expect(fetchMock).not.toHaveBeenCalled();expect(legalReviewUrl(property,{kind:'history',offset:20})).toContain('kind=history&offset=20')})
