import {beforeEach,it,expect,vi} from 'vitest'
import type {NextRequest} from 'next/server'
const d=vi.hoisted(()=>({auth:vi.fn(),start:vi.fn(),confirm:vi.fn(),finish:vi.fn(),actor:vi.fn(),check:vi.fn()}));vi.mock('@/utils/services/api-helpers',()=>({hasValidCronAuth:d.auth}));vi.mock('@/utils/services/cron-job-runs',()=>({startCronJobRun:d.start,confirmCronJobRun:d.confirm,finishCronJobRun:d.finish}));vi.mock('@/utils/knowledge/inventory',()=>({inventoryActor:d.actor,InventoryError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}));vi.mock('@/utils/knowledge/web-policy-store',()=>({checkScheduledWebsites:d.check}))
import {GET,POST} from './route'
const req=()=>new Request('http://local/api/cron/knowledge-refresh')as NextRequest
beforeEach(()=>{vi.clearAllMocks();d.auth.mockReturnValue(true);d.start.mockResolvedValue({id:'run'});d.confirm.mockResolvedValue(undefined);d.check.mockResolvedValue({state:'paused',scheduled:0,ready:0,unconfirmed:0,results:[]})})
it('authenticates before recording or dispatching',async()=>{d.auth.mockReturnValue(false);expect((await GET(req())).status).toBe(401);expect(d.start).not.toHaveBeenCalled();expect(d.check).not.toHaveBeenCalled()})
it('records an honest paused outcome without claiming refreshed sources',async()=>{const result=await GET(req());expect(result.status).toBe(200);expect(await result.json()).toMatchObject({state:'paused',scheduled:0,published:0});expect(d.confirm).toHaveBeenCalledWith({id:'run'},expect.objectContaining({status:'success',summary:expect.objectContaining({state:'paused',published:0})}))})
it('records partial private capture outcomes',async()=>{d.check.mockResolvedValue({state:'review_required',scheduled:2,ready:1,unconfirmed:1,results:[{captureId:'a',state:'ready'},{captureId:'b',state:'unconfirmed'}]});expect((await GET(req())).status).toBe(200);expect(d.confirm).toHaveBeenCalledWith({id:'run'},expect.objectContaining({status:'partial',summary:expect.objectContaining({published:0,unconfirmed:1})}))})
it('halts when the run cannot be recorded and reports uncertain completion',async()=>{d.start.mockResolvedValueOnce(null);expect((await GET(req())).status).toBe(503);expect(d.check).not.toHaveBeenCalled();d.confirm.mockRejectedValueOnce(new Error('write failed'));expect((await GET(req())).status).toBe(503);expect(d.finish).toHaveBeenCalled()})
it('dispatch failure never reports successful refresh',async()=>{d.check.mockRejectedValueOnce(new Error('secret failure'));const r=await GET(req());expect(r.status).toBe(503);expect(JSON.stringify(await r.json())).not.toContain('secret');expect(d.confirm).not.toHaveBeenCalled()})
it('directs manual refresh to reviewed captures',async()=>{d.actor.mockResolvedValue('actor');expect((await POST()).status).toBe(410);expect(d.start).not.toHaveBeenCalled()})
