import {it,expect} from 'vitest'
import {conversationDecision,conversationRead} from './conversation-work'
const id='12345678-1234-1234-1234-123456789012',base={id,propertyId:id,expectedActorId:id},source={conversationId:id,sourceHash:'a'.repeat(64)}
it.each(['takeover','release','archive','restore'])('%s requires current source and reason',operation=>{const input={...base,...source,operation,reason:'Reviewed exact current transcript'};expect(conversationDecision.safeParse(input).success).toBe(true);for(const patch of[{sourceHash:undefined},{reason:' '},{conversationId:'other'}])expect(conversationDecision.safeParse({...input,...patch}).success).toBe(false)})
it('bounds exact staff reply content and rejects supplied authors or histories',()=>{const input={...base,...source,operation:'reply',content:'Actual staff reply'};expect(conversationDecision.safeParse(input).success).toBe(true);for(const patch of[{content:' '},{content:'a'.repeat(10001)},{actorId:id},{messages:[]},{isHumanMode:true}])expect(conversationDecision.safeParse({...input,...patch}).success).toBe(false)})
it('requires a retained review for historical export',()=>{expect(conversationDecision.safeParse({...base,operation:'export',conversationId:id,reviewId:id}).success).toBe(true);expect(conversationDecision.safeParse({...base,operation:'export',conversationId:id,reviewId:id,artifact:'invented'}).success).toBe(false)})
it.each(['delivered','read','verified'])('cannot invent a recipient outcome %s',outcome=>{expect(conversationDecision.safeParse({...base,operation:'report',preparationId:id,artifactHash:'a'.repeat(64),outcome}).success).toBe(false)})
it('bounds complete private history and strict query fields',()=>{expect(conversationRead.safeParse({propertyId:id,kind:'history',offset:'25'}).success).toBe(true);for(const patch of[{offset:'-1'},{offset:'1.2'},{kind:'all_tenants'},{actorId:id}])expect(conversationRead.safeParse({propertyId:id,...patch}).success).toBe(false)})
it('unused cancellation carries identity only',()=>{expect(conversationDecision.safeParse({...base,operation:'cancel'}).success).toBe(true);expect(conversationDecision.safeParse({...base,operation:'cancel',content:'hidden'}).success).toBe(false)})
