'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
type Message={id:string;role:string|null;content:string|null;created_at:string|null}
type Conversation={id:string;is_human_mode:boolean|null;mode_revision:number;inbox_archived_at:string|null;channel:string|null}
type Source={conversation:Conversation;lead:{first_name?:string;last_name?:string;email?:string;phone?:string}|null;messages:Message[]}
type Command={id:string;actor_id:string;conversation_id:string|null;created_at:string;input:Record<string,unknown>;source:Source|null;result:Result}
type Result={id:string;status:string;conversationId?:string;artifact?:string;artifactHash?:string;outcome?:string}
type Item={id:string;channel?:string;createdAt:string|null;humanMode?:boolean;archivedAt?:string|null;lead?:{name:string;email:string}|null;messageCount?:number;lastMessage?:{content:string}|null;operation?:string;actorName?:string;status?:string}
type PageData={actorId:string;canManage:boolean;items:Item[];count:number;offset:number;hash:string;complete:true}
type Transcript=Omit<PageData,'items'>&{items:Message[];conversation:{conversation:Conversation;lead:Source['lead']}}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-40',field='w-full rounded-lg border bg-transparent p-2 text-sm'
async function json(response:Response){const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'The conversation result could not be confirmed.'),{status:response.status});return data}
export function LumaConversationInbox({propertyId,initialConversationId,leadId}:{propertyId:string;initialConversationId?:string|null;leadId?:string}){
 const[list,setList]=useState<PageData|null>(null),[transcript,setTranscript]=useState<Transcript|null>(null),[selected,setSelected]=useState(initialConversationId||''),[archived,setArchived]=useState(false),[history,setHistory]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<string|null>(null),[reason,setReason]=useState(''),[reply,setReply]=useState(''),[saved,setSaved]=useState<Command|null>(null),[savedOffset,setSavedOffset]=useState(0),[prepared,setPrepared]=useState<Result|null>(null)
 const actor=useRef(''),storage=useRef(''),epoch=useRef(0),mounted=useRef(true)
 const read=useCallback(async(params:Record<string,string>)=>json(await fetch('/api/lumaleasing/admin/conversation-work?'+new URLSearchParams({propertyId,...(leadId?{leadId}:{}),...params}),{cache:'no-store'})),[propertyId,leadId])
 const load=useCallback(async(offset=0,hash?:string)=>{const ticket=++epoch.current;setBusy(true);setError('');try{const data=await read({kind:history?'history':'list',archived:String(archived),offset:String(offset),...(hash?{hash}:{})});if(!mounted.current||ticket!==epoch.current)return;if(data.complete!==true)throw new Error('The complete conversation page could not be confirmed.');actor.current=data.actorId;storage.current=`p11.luma-conversations.v1:${data.actorId}:${propertyId}`;setList(data);const id=sessionStorage.getItem(storage.current);setPending(id&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(id)?id:null)}catch(e){if(mounted.current&&ticket===epoch.current)setError(e instanceof Error?e.message:'Conversation inbox unavailable.')}finally{if(mounted.current&&ticket===epoch.current)setBusy(false)}},[read,history,archived,propertyId])
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false}},[load])
 async function open(id:string,offset=0,hash?:string){setBusy(true);setError('');setSaved(null);setPrepared(null);try{const data=await read({kind:'messages',conversationId:id,offset:String(offset),...(hash?{hash}:{})});if(data.complete!==true)throw new Error('The transcript could not be confirmed.');if(mounted.current){setSelected(id);setTranscript(data)}}catch(e){setError(e instanceof Error?e.message:'Transcript unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{if(initialConversationId)void open(initialConversationId)},[initialConversationId]) // eslint-disable-line react-hooks/exhaustive-deps
 function clearPending(){sessionStorage.removeItem(storage.current);setPending(null)}
 async function inspect(id:string,recovery=false){setBusy(true);setError('');try{const data=await read({kind:'command',commandId:id}),command:Command=data.command;if(recovery)clearPending();setSaved(command);setSavedOffset(0);if(command.conversation_id)setSelected(command.conversation_id);if(command.input.operation==='export'&&command.actor_id===actor.current)setPrepared(command.result);else setPrepared(null);if(recovery){setNotice(command.result.status==='cancelled'?'Unused conversation request closed.':'Saved conversation decision recovered.');await load();if(command.conversation_id){const current=await read({kind:'messages',conversationId:command.conversation_id});setTranscript(current)}}}catch(e){setError(e instanceof Error?e.message:'Saved decision unavailable.')}finally{setBusy(false)}}
 async function send(input:Record<string,unknown>,existing?:string){if(!actor.current)return;const id=existing||crypto.randomUUID();sessionStorage.setItem(storage.current,id);setPending(id);setBusy(true);setError('');setNotice('');try{const result:Result=await json(await fetch('/api/lumaleasing/admin/conversation-work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,propertyId,expectedActorId:actor.current,...input})}));setReason('');if(input.operation==='reply')setReply('');if(result.status==='export_prepared')setPrepared(result);else setPrepared(null);const details=await read({kind:'command',commandId:id});setSaved(details.command);setSavedOffset(0);if(result.conversationId){setSelected(result.conversationId);setTranscript(await read({kind:'messages',conversationId:result.conversationId}))}clearPending();await load();setNotice(result.status==='cancelled'?'Unused conversation request closed.':result.status==='reply_saved'?'Reply saved in the visitor conversation. Visitor receipt has not been confirmed.':result.status==='reported'?(result.outcome==='failed'?'The browser download failed; its outcome was recorded.':'Browser download initiation recorded.'):result.status==='export_prepared'?'Exact saved transcript download prepared.':'Conversation decision saved.')}catch(e){if((e as{status?:number}).status===400)clearPending();setError(e instanceof Error?e.message:'Check the saved conversation request.')}finally{setBusy(false)}}
 async function download(){if(!prepared?.artifact||!prepared.artifactHash)return;let outcome='download_initiated',url:string|undefined;try{url=URL.createObjectURL(new Blob([prepared.artifact],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='lumaleasing-transcript.json';document.body.appendChild(a);a.click();a.remove()}catch{outcome='failed'}finally{if(url)URL.revokeObjectURL(url)}await send({operation:'report',preparationId:prepared.id,artifactHash:prepared.artifactHash,outcome})}
 const locked=busy||!!pending,current=transcript?.conversation.conversation,canManage=!!list?.canManage&&!locked,source={conversationId:selected,sourceHash:transcript?.hash}
 const messages=(items:Message[])=>items.map(m=><li key={m.id} className="space-y-1 rounded-lg border p-3"><div className="flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>{m.role==='user'?'Visitor':m.role==='system'?'Conversation notice':'Assistant or staff'}</span><span>{m.created_at?new Date(m.created_at).toLocaleString():'Time not recorded'}</span></div><p className="whitespace-pre-wrap break-words text-sm">{m.content??'Content not recorded'}</p></li>)
 return <section aria-label="Conversation inbox" className="min-w-0 space-y-5 rounded-xl border bg-white p-4 dark:bg-slate-950">
  <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Conversation inbox</h2><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void load()}>Refresh inbox</button><button className={button} disabled={busy} onClick={()=>setHistory(v=>!v)}>{history?'Back to conversations':'Conversation decision history'}</button></div></div>
  <p className="text-sm text-slate-600">Open the complete conversation before taking over or replying. Archived conversations keep their history; a new visitor message returns them to the inbox.</p>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}{busy&&<p className="text-sm">Loading saved conversation work…</p>}
  {pending&&<div className="space-y-2 rounded-lg border border-amber-300 p-3"><p className="text-sm">An earlier conversation request needs confirmation before another decision.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void inspect(pending,true)}>Check saved conversation request</button><button className={button} disabled={busy} onClick={()=>void send({operation:'cancel'},pending)}>Cancel unused conversation request</button></div></div>}
  {!history&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={archived} disabled={busy} onChange={e=>setArchived(e.target.checked)}/>Include archived conversations</label>}
  {list&&<section aria-label={history?'Conversation decision list':'Saved conversations'} className="space-y-3"><p className="text-sm">{list.count} {history?'decisions':'conversations'} · {list.count?`${list.offset+1}–${Math.min(list.offset+25,list.count)}`:'None saved'}</p><ul className="divide-y">{list.items.map(item=><li key={item.id} className="py-3"><button className="w-full min-w-0 space-y-1 rounded-lg p-2 text-left hover:bg-slate-50 disabled:opacity-40" disabled={busy} onClick={()=>history?void inspect(item.id):void open(item.id)}><span className="block font-medium">{history?`${item.status?.replaceAll('_',' ')} · ${item.actorName}`:`Open conversation: ${item.lead?.name||item.lead?.email||'Anonymous visitor'}`}</span><span className="block text-sm text-slate-500">{item.createdAt?new Date(item.createdAt).toLocaleString():'Time not recorded'}{!history&&` · ${item.messageCount} messages · ${item.humanMode?'Staff responding':'Assistant mode'}${item.archivedAt?' · Archived':''}`}</span>{!history&&item.lastMessage&&<span className="block truncate text-sm">{item.lastMessage.content}</span>}</button></li>)}</ul><div className="flex gap-2"><button className={button} disabled={busy||list.offset===0} onClick={()=>void load(Math.max(0,list.offset-25),list.hash)}>Previous inbox page</button><button className={button} disabled={busy||list.offset+25>=list.count} onClick={()=>void load(list.offset+25,list.hash)}>Next inbox page</button></div></section>}
  {transcript&&current&&<section aria-label="Current conversation" className="space-y-4 border-t pt-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">Current conversation</h3><button className={button} disabled={busy} onClick={()=>void open(selected)}>Refresh conversation</button></div><p className="text-sm">{current.is_human_mode?'A team member controls this conversation.':'The assistant controls this conversation.'}{current.inbox_archived_at?' Archived from the inbox.':''}</p><p className="break-words text-sm">{[transcript.conversation.lead?.first_name,transcript.conversation.lead?.last_name,transcript.conversation.lead?.email].filter(Boolean).join(' · ')}</p><p className="text-sm">{transcript.count} messages · {transcript.count?`${transcript.offset+1}–${Math.min(transcript.offset+25,transcript.count)}`:'None saved'}</p><ol className="space-y-3">{messages(transcript.items)}</ol><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||transcript.offset===0} onClick={()=>void open(selected,Math.max(0,transcript.offset-25),transcript.hash)}>Previous messages</button><button className={button} disabled={busy||transcript.offset+25>=transcript.count} onClick={()=>void open(selected,transcript.offset+25,transcript.hash)}>Next messages</button><button className={button} disabled={locked} onClick={()=>void send({operation:'review',...source})}>Save transcript review</button></div>
   {list?.canManage?<div className="space-y-3 rounded-lg border p-4"><label className="block text-sm">Conversation decision reason<textarea className={field} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="flex flex-wrap gap-2"><button className={button} disabled={!canManage||!reason.trim()} onClick={()=>void send({operation:current.is_human_mode?'release':'takeover',...source,reason:reason.trim()})}>{current.is_human_mode?'Return to assistant':'Take over conversation'}</button><button className={button} disabled={!canManage||!reason.trim()} onClick={()=>void send({operation:current.inbox_archived_at?'restore':'archive',...source,reason:reason.trim()})}>{current.inbox_archived_at?'Restore conversation to inbox':'Archive conversation from inbox'}</button></div>{current.is_human_mode&&!current.inbox_archived_at&&<><label className="block text-sm">Reply to visitor<textarea className={field} maxLength={10000} value={reply} onChange={e=>setReply(e.target.value)}/></label><button className={button} disabled={!canManage||!reply.trim()} onClick={()=>void send({operation:'reply',...source,content:reply})}>Send staff reply</button><p className="text-xs text-slate-500">This saves the reply for the visitor’s widget. It does not send an email or text message.</p></>}</div>:<p className="text-sm">A current property manager or administrator can take over, reply or archive.</p>}
  </section>}
  {saved&&<section aria-label="Saved conversation decision" className="space-y-3 border-t pt-5"><h3 className="font-semibold">Saved conversation decision</h3><p className="text-sm">{saved.result.status.replaceAll('_',' ')} · {new Date(saved.created_at).toLocaleString()}</p>{typeof saved.input.reason==='string'&&<p className="whitespace-pre-wrap text-sm">{saved.input.reason}</p>}{typeof saved.input.content==='string'&&<p className="whitespace-pre-wrap break-words text-sm">Saved reply: {saved.input.content}</p>}{saved.source&&<><p className="text-sm">Original transcript at this decision: {saved.source.messages.length} messages. Later messages and decisions are not added to this snapshot.</p><ol className="space-y-3">{messages(saved.source.messages.slice(savedOffset,savedOffset+25))}</ol><div className="flex flex-wrap gap-2"><button className={button} disabled={savedOffset===0} onClick={()=>setSavedOffset(v=>Math.max(0,v-25))}>Previous saved messages</button><button className={button} disabled={savedOffset+25>=saved.source.messages.length} onClick={()=>setSavedOffset(v=>v+25)}>Next saved messages</button>{saved.input.operation==='review'&&<button className={button} disabled={locked} onClick={()=>void send({operation:'export',conversationId:saved.conversation_id,reviewId:saved.id})}>Prepare transcript download</button>}</div></>}</section>}
  {prepared?.artifact&&<button className={button} disabled={locked} onClick={()=>void download()}>Download prepared transcript</button>}
 </section>
}
