"use client"
import {useCallback,useEffect,useRef,useState}from 'react'
type Item={id:string;operation?:string;state?:string;createdAt?:string;originalRetained?:boolean;responseRetained?:boolean;input?:{operation:string;reason:string};created_at?:string;actor_id?:string}
type Model={intent:{id:string;purpose:string;params:{messages?:Array<{role:string;content:unknown}>};source:unknown;reserved_units:number;created_at:string};receipt:{outcome:string;response:unknown;issue:string|null;created_at:string}|null}
type Source={request:{request_id:string;operation:string;state:string;expires_at:string;response:unknown};original:{raw_input:string;config_source:unknown;created_at:string}|null;response:{response:unknown;http_status:number;created_at:string}|null;models:Model[]}
type Read={state:string;propertyId:string;actorId:string;canReview:boolean;items:Item[];total:number;offset:number;hash:string;sourceHash:string;source:Source|null;operation?:string}
type Pending={id:string;requestId:string}
const button='rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:opacity-40'
function Original({title,value}:{title:string;value:unknown}){return <details className="mt-3 rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-medium">{title}</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs">{typeof value==='string'?value:JSON.stringify(value,null,2)}</pre></details>}
export function RequestEvidence({propertyId}:{propertyId:string}){
 const[open,setOpen]=useState(false),[data,setData]=useState<Read|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[pending,setPending]=useState<Pending|null>(null),[notice,setNotice]=useState('')
 const life=useRef<AbortController|null>(null),actor=useRef(''),selection=useRef<string|null>(null),pendingRef=useRef<Pending|null>(null)
 const key=useCallback((id:string)=>`p11.luma.request-review:${id}:${propertyId}`,[propertyId])
 const request=useCallback(async(query:Record<string,string|number>={},body?:Record<string,unknown>)=>{const params=new URLSearchParams({propertyId,...Object.fromEntries(Object.entries(query).map(([k,v])=>[k,String(v)]))});const signal=life.current?AbortSignal.any([life.current.signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000);const response=await fetch('/api/lumaleasing/admin/request-evidence'+(body?'':'?'+params),{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify({...body,propertyId,expectedActorId:actor.current}):undefined,signal});const result=await response.json();if(!response.ok)throw new Error(result.error||'Saved request history is unavailable.');if(result.propertyId!==propertyId||(actor.current&&result.actorId!==actor.current))throw new Error('Your current account or property changed. Reload this page.');return result as Read},[propertyId])
 const load=useCallback(async(id:string|null=null,offset=0,hash?:string)=>{setBusy(true);setError('');try{const result=await request({...id?{requestId:id}:{},offset,...hash?{hash}:{}});if(life.current?.signal.aborted)return;actor.current=result.actorId;selection.current=id;setData(result);if(!pendingRef.current){try{const stored=JSON.parse(sessionStorage.getItem(key(result.actorId))||'null');if(stored&&/^[0-9a-f-]{36}$/i.test(stored.id)&&/^[0-9a-f-]{36}$/i.test(stored.requestId)){pendingRef.current=stored;setPending(stored)}}catch{}}}catch(e){if(!life.current?.signal.aborted)setError(e instanceof Error?e.message:'Could not load request history.')}finally{if(!life.current?.signal.aborted)setBusy(false)}},[request,key])
 useEffect(()=>{const controller=new AbortController();life.current=controller;return()=>controller.abort()},[])
 useEffect(()=>{if(open)void load()},[open,load])
 function clear(){pendingRef.current=null;setPending(null);try{sessionStorage.removeItem(key(actor.current))}catch{}}
 async function check(){if(!pending)return;setBusy(true);setError('');try{const result=await request({reviewId:pending.id});setNotice(result.operation==='cancel'?'Unused review cancelled.':'Saved decision recovered.');clear();await load(pending.requestId)}catch(e){setError(e instanceof Error?e.message:'The decision remains unconfirmed.')}finally{setBusy(false)}}
 async function decide(operation:'retain_hold'|'release_saved_response'|'cancel'){
  if(!data?.source&&!pending)return
  const p=pending??{id:crypto.randomUUID(),requestId:data!.source!.request.request_id};pendingRef.current=p;setPending(p);try{sessionStorage.setItem(key(actor.current),JSON.stringify(p))}catch{}
  setBusy(true);setError('');setNotice('');try{const result=await request({}, {...p,operation,...operation==='cancel'?{}:{reason,sourceHash:data?.sourceHash}});setNotice(result.operation==='cancel'?'Unused review cancelled.':result.operation==='release_saved_response'?'The exact saved response is available for the visitor’s same-request retry.':'Review saved. The request remains in its current state.');clear();setReason('');await load(p.requestId)}catch(e){setError(e instanceof Error?e.message:'The decision remains unconfirmed.')}finally{setBusy(false)}
 }
 const source=data?.source
 return <section aria-label="Saved visitor requests" className="rounded-xl border border-slate-200 bg-white p-5 text-slate-900">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Saved visitor requests</h2><p className="mt-1 text-sm text-slate-500">Private request, answer and recovery evidence for this property.</p></div><button className={button}onClick={()=>setOpen(v=>!v)}>{open?'Hide request history':'View request history'}</button></div>
  {open&&<div className="mt-4 space-y-4">
   <p className="text-sm text-slate-600">A saved model response proves what came back. It does not prove a message was shown, a contact was saved or a tour was booked. Unconfirmed model calls are never repeated automatically.</p>
   {error&&<p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}
   {pending&&<div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm"><p>A review decision needs confirmation. Check it before making another decision.</p><div className="mt-2 flex flex-wrap gap-2"><button className={button}disabled={busy}onClick={()=>void check()}>Check saved review</button><button className={button}disabled={busy}onClick={()=>void decide('cancel')}>Cancel unused review</button></div></div>}
   <div className="flex gap-2"><button className={button}disabled={busy}onClick={()=>void load(selection.current)}>Refresh request history</button>{source&&<button className={button}disabled={busy}onClick={()=>void load()}>All visitor requests</button>}</div>
   {busy&&<p role="status">Loading saved evidence…</p>}
   {data&&!source&&<><p>{data.total} visitor requests</p><ul className="divide-y divide-slate-200">{data.items.map(item=><li key={item.id}className="py-3"><button className="text-left text-sm underline"disabled={busy}onClick={()=>void load(item.id)}>{item.operation} · {item.state} · {item.id.slice(0,8)}</button><p className="text-xs text-slate-500">{item.createdAt&&new Date(item.createdAt).toLocaleString()} · {item.originalRetained?'Original retained':'Legacy request: original unavailable'} · {item.responseRetained?'Handler response retained':'Handler response not retained'}</p></li>)}</ul></>}
   {source&&<section aria-label="Request evidence detail" className="rounded-xl bg-slate-50 p-4 text-sm">
    <h3 className="font-semibold">{source.request.operation} request · {source.request.request_id.slice(0,8)}</h3><p className="mt-2">Saved state: {source.request.state}{source.request.state==='running'&&Date.parse(source.request.expires_at)<=Date.now()?' — processing time expired; review required':''}</p>
    {source.original?<><Original title="Original visitor input"value={source.original.raw_input}/><Original title="Widget settings used"value={source.original.config_source}/></>:<p className="mt-2">This legacy request has no retained original input. It cannot be reconstructed.</p>}
    {source.response?<Original title={`Actual saved handler response · HTTP ${source.response.http_status}`}value={source.response.response}/>:<p className="mt-2">No complete handler response was retained. Model output alone cannot be released as a completed request.</p>}
    <h4 className="mt-4 font-medium">Model calls ({source.models.length})</h4>{source.models.map(model=><div key={model.intent.id}className="mt-3 rounded-lg border border-slate-200 bg-white p-3"><p className="font-medium">{model.intent.purpose} · {model.receipt?.outcome==='received'?'Response retained':'Response unconfirmed'}</p><p className="text-xs text-slate-500">{new Date(model.intent.created_at).toLocaleString()} · {model.intent.reserved_units.toLocaleString()} reserved token units, not billed usage</p><Original title="Exact model input"value={model.intent.params}/><Original title="Input context"value={model.intent.source}/>{model.receipt?.outcome==='received'?<Original title="Actual model response and reported usage"value={model.receipt.response}/>:<p className="mt-2">{model.receipt?.issue||'No receipt was saved. Invocation or completion is unknown.'} No automatic repeat is allowed.</p>}</div>)}
    {data?.canReview?<div className="mt-4"><label className="block">Review reason<textarea value={reason}onChange={e=>setReason(e.target.value)}maxLength={2000}className="mt-1 w-full rounded-lg border border-slate-300 p-2"/></label><div className="mt-2 flex flex-wrap gap-2"><button className={button}disabled={busy||!!pending||reason.trim().length<3}onClick={()=>void decide('retain_hold')}>Save investigation note</button>{source.response&&source.response.http_status<500&&source.request.state!=='completed'&&<button className={button}disabled={busy||!!pending||reason.trim().length<3}onClick={()=>void decide('release_saved_response')}>Release exact saved response</button>}</div><p className="mt-2 text-xs text-slate-500">Release only makes the original complete response available to the visitor’s same-request retry. It does not send a message or repeat any action. Current widget authority must still match.</p></div>:<p className="mt-4">A current property manager must make recovery decisions.</p>}
    <h4 className="mt-4 font-medium">Review history ({data?.total??0})</h4><ul>{data?.items.map(item=><li className="mt-2"key={item.id}>{item.input?.operation.replaceAll('_',' ')} · {item.created_at&&new Date(item.created_at).toLocaleString()}<p className="whitespace-pre-wrap">{item.input?.reason}</p></li>)}</ul>
   </section>}
   {data&&<div className="flex flex-wrap items-center gap-3"><button className={button}disabled={busy||data.offset===0}onClick={()=>void load(selection.current,Math.max(0,data.offset-20),data.hash)}>Previous request page</button><span className="text-sm">{data.total?data.offset+1:0}–{Math.min(data.offset+20,data.total)} of {data.total}</span><button className={button}disabled={busy||data.offset+20>=data.total}onClick={()=>void load(selection.current,data.offset+20,data.hash)}>Next request page</button></div>}
  </div>}
 </section>
}
