import {beforeEach,afterEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({rpc:vi.fn(),read:vi.fn(),execute:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>{const q={select:()=>q,eq:()=>q,maybeSingle:d.read};return{rpc:d.rpc,from:()=>q}}}))
vi.mock('./brand-evidence-model',async original=>({...await original<typeof import('./brand-evidence-model')>(),executeBrandEvidence:d.execute}))
import {runBrandEvidence,recoverBrandEvidence,requestBrandEvidence,buildBrandEvidencePreview} from './brand-evidence-store'
import {prepareBrandEvidence} from './brand-evidence-model'
const source='A1 source '.repeat(10),model=prepareBrandEvidence(source,'https://example.com','Competitor'),preview={claims:[],notes:'No supported statements'},receipt={status:'received',finishReason:'stop',content:JSON.stringify(preview)}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');vi.stubEnv('OPENAI_API_KEY','fixture-key');d.execute.mockResolvedValue(receipt);d.read.mockResolvedValue({data:{state:'result_ready',model_input:model,raw_result:receipt,result_hash:'hash'},error:null});d.rpc.mockImplementation(async(name)=>({data:name==='claim_marketvision_brand'?{state:'invoke_once',claimToken:'token',modelInput:model}:name==='record_marketvision_brand_result'?{state:'saved',requestState:'result_ready'}:{state:'saved',requestState:'preview_ready'},error:null}))})
afterEach(()=>vi.unstubAllEnvs())
it('does not claim or invoke while paused or unconfigured',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect(await runBrandEvidence('request')).toEqual({state:'paused'});vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');vi.stubEnv('OPENAI_API_KEY','');expect(await runBrandEvidence('request')).toEqual({state:'provider_unavailable'});expect(d.rpc).not.toHaveBeenCalled();expect(d.execute).not.toHaveBeenCalled()})
it('a running request is not invoked again',async()=>{d.rpc.mockResolvedValue({data:{state:'running'},error:null});expect(await runBrandEvidence('request')).toEqual({state:'running'});expect(d.execute).not.toHaveBeenCalled()})
it('retries only result persistence after a lost database receipt',async()=>{let writes=0;d.rpc.mockImplementation(async(name)=>{if(name==='claim_marketvision_brand')return{data:{state:'invoke_once',claimToken:'token',modelInput:model},error:null};if(name==='record_marketvision_brand_result'&&writes++===0)return{data:null,error:{message:'lost'}};return{data:{state:'saved',requestState:name==='record_marketvision_brand_result'?'result_ready':'preview_ready'},error:null}});await runBrandEvidence('request');expect(d.execute).toHaveBeenCalledTimes(1);const receipts=d.rpc.mock.calls.filter(c=>c[0]==='record_marketvision_brand_result');expect(receipts).toHaveLength(2);expect(receipts[0][1]).toEqual(receipts[1][1])})
it('model errors become uncertain receipts without automatic reinvocation',async()=>{d.execute.mockRejectedValue(new Error('private error'));d.rpc.mockImplementation(async name=>({data:name==='claim_marketvision_brand'?{state:'invoke_once',claimToken:'token',modelInput:model}:{state:'saved',requestState:'held'},error:null}));expect(await runBrandEvidence('request')).toMatchObject({requestState:'held'});expect(d.rpc).toHaveBeenLastCalledWith('record_marketvision_brand_result',expect.objectContaining({p_result:{status:'uncertain',errorCode:'model_uncertain'}}));expect(d.execute).toHaveBeenCalledTimes(1)})
it('saved result recovery works while models are paused',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');await recoverBrandEvidence('request');expect(d.execute).not.toHaveBeenCalled();expect(d.rpc).toHaveBeenCalledWith('prepare_marketvision_brand_preview',expect.objectContaining({p_preview:preview,p_result_hash:'hash'}))})
it('invalid output is retained and held instead of filtered into partial success',async()=>{d.read.mockResolvedValue({data:{state:'result_ready',model_input:model,raw_result:{...receipt,content:'broken'},result_hash:'hash'},error:null});await buildBrandEvidencePreview('request');expect(d.rpc).toHaveBeenLastCalledWith('prepare_marketvision_brand_preview',expect.objectContaining({p_preview:null,p_error_code:'invalid_output'}))})
it('existing requests recover their original recipe without preparing a replacement',async()=>{d.read.mockResolvedValue({data:{id:'request'},error:null});await requestBrandEvidence({requestId:'request',propertyId:'property',competitorId:'competitor',sourceVersion:1,sourceId:'source',confirmedSourceScope:true,reason:'Reviewed source'},'actor');expect(d.rpc).toHaveBeenCalledWith('begin_marketvision_brand',expect.objectContaining({p_model_input:{}}));expect(d.execute).not.toHaveBeenCalled()})
