import {createServiceClient} from '@/utils/supabase/admin'
import {MarketStoreError} from './decision-store'
import {prepareExtraction,executeExtraction,parseExtraction,type ExtractionModelInput,type ExtractionReceipt} from './extraction-model'
import type {extractionRequest} from './extraction-contracts'
import type {z} from 'zod'
type RecordValue=Record<string,unknown>
const messages:Record<string,string>={source_unavailable:'The retained source no longer matches this competitor. Fetch the current page before requesting or applying its prices.',forbidden:'This property is unavailable.',not_found:'This saved source request is unavailable in the selected property.',stale_competitor:'Competitor details changed. Reload before saving the source.',competitor_archived:'Restore this competitor before extracting or applying prices.',unsupported_pricing_basis:'This extraction supports monthly rental prices. This property needs a different pricing contract.',stale_request:'This request changed. Reload its saved status.',stale_preview:'This preview changed. Reload and review its exact values.',stale_source:'Saved competitor or unit values changed. Refresh the review baseline and check the candidate changes again.',source_contract_changed:'The property type changed. Save a new source request for the current pricing contract.',request_conflict:'This decision differs from the saved request. Inspect its history.',result_conflict:'The saved model receipt cannot be replaced.',closed_request:'This extraction is already closed.',preview_required:'A saved pricing preview is required before this decision.',cursor_changed:'Reload extraction history before loading another page.'}
export async function extractionRpc(name:string,args:RecordValue,allowed=['ready','saved','replayed','queued','running','result_ready','preview_ready','held','stopped','completed','busy','invoke_once']){const db=createServiceClient() as unknown as{rpc:(name:string,args:RecordValue)=>Promise<{data:RecordValue|null;error:unknown}>};const {data,error}=await db.rpc(name,args);if(error||!data)throw new MarketStoreError('The extraction decision could not be confirmed. Retry the same decision or inspect saved history.');if(!allowed.includes(String(data.state)))throw new MarketStoreError(messages[String(data.state)]||'Review the current extraction state before continuing.',data.state==='forbidden'?403:data.state==='not_found'?404:409);return data}
export async function requestExtraction(input:z.infer<typeof extractionRequest>,actor:string){const {requestId,propertyId,...source}=input,db=createServiceClient();const prior=await db.from('marketvision_extraction_requests').select('id').eq('id',requestId).eq('property_id',propertyId).maybeSingle();if(prior.error)throw new MarketStoreError('Saved source requests could not be loaded.');if(prior.data)return extractionRpc('begin_marketvision_extraction',{p_id:requestId,p_property_id:propertyId,p_actor_id:actor,p_input:source,p_model_input:{}})
 const {data:competitor,error}=await db.from('competitors').select('id,version,property_type').eq('id',source.competitorId).eq('property_id',propertyId).maybeSingle();if(error)throw new MarketStoreError('Competitor details could not be loaded.');if(!competitor)throw new MarketStoreError(messages.not_found,404);if(competitor.version!==source.sourceVersion)throw new MarketStoreError(messages.stale_competitor,409)
 return extractionRpc('begin_marketvision_extraction',{p_id:requestId,p_property_id:propertyId,p_actor_id:actor,p_input:source,p_model_input:prepareExtraction(source.content,competitor.property_type??'')})
}
export async function buildExtractionPreview(id:string){const {data:run,error}=await createServiceClient().from('marketvision_extraction_requests').select('id,state,model_input,raw_result,result_hash').eq('id',id).maybeSingle();if(error||!run)throw new MarketStoreError('The saved extraction receipt could not be loaded.');if(run.state!=='result_ready')return {state:run.state}
 let preview:unknown=null,errorCode:string|null=null;try{preview=parseExtraction(run.model_input as unknown as ExtractionModelInput,run.raw_result as unknown as ExtractionReceipt)}catch(e){errorCode=e instanceof Error&&e.message==='incomplete_output'?'incomplete_output':'invalid_output'}
 return extractionRpc('prepare_marketvision_extraction_preview',{p_id:id,p_result_hash:run.result_hash,p_preview:preview,p_error_code:errorCode})
}
export function extractionExecutionStatus(){return {paused:process.env.OUTBOUND_DELIVERY_PAUSED==='true',configured:!!process.env.OPENAI_API_KEY}}
export async function runExtraction(id:string){const status=extractionExecutionStatus();if(status.paused)return {state:'paused'};if(!status.configured)return {state:'provider_unavailable'};const claim=await extractionRpc('claim_marketvision_extraction',{p_id:id});if(claim.state==='result_ready')return buildExtractionPreview(id);if(claim.state!=='invoke_once')return claim
 let receipt:ExtractionReceipt;try{receipt=await executeExtraction(claim.modelInput as unknown as ExtractionModelInput)}catch{receipt={status:'uncertain',errorCode:'model_uncertain'}}
 const args={p_id:id,p_claim_token:claim.claimToken,p_result:receipt};let result:RecordValue;try{result=await extractionRpc('record_marketvision_extraction_result',args)}catch{result=await extractionRpc('record_marketvision_extraction_result',args)}
 return result.requestState==='result_ready'?buildExtractionPreview(id):result
}
/** Receipt recovery stays local even while outbound execution is paused. */
export async function recoverExtraction(id:string){const {data,error}=await createServiceClient().from('marketvision_extraction_requests').select('state').eq('id',id).maybeSingle();if(error||!data)throw new MarketStoreError('Saved extraction status could not be loaded.');return data.state==='result_ready'?buildExtractionPreview(id):data.state==='queued'?runExtraction(id):{state:data.state}}
