import {z} from 'zod'
import {marketId,publicMarketUrl,unitValues} from './decision-contracts'
const reason=z.string().trim().min(3).max(2000),version=z.number().int().positive(),hash=z.string().regex(/^[a-f0-9]{64}$/)
export const extractionRead=z.object({propertyId:marketId,competitorId:marketId,requestId:marketId.optional(),cursor:marketId.optional()}).strict()
export const extractionRequest=z.object({requestId:marketId,propertyId:marketId,competitorId:marketId,sourceVersion:version,sourceRequestId:marketId.optional(),confirmedSourceScope:z.literal(true).optional(),content:z.string().trim().min(50).max(50000),sourceUrl:z.string().trim().max(2000).refine(v=>!v||publicMarketUrl(v)),effectiveAt:z.string().datetime({offset:true}).nullable().refine(v=>v===null||new Date(v).getTime()<=Date.now()+300000),reason}).strict()
export const extractionControl=z.object({requestId:marketId,propertyId:marketId,extractionId:marketId,expectedVersion:version,action:z.enum(['stop','recover','rebase']),reason}).strict()
export const extractionApply=z.object({requestId:marketId,propertyId:marketId,extractionId:marketId,expectedVersion:version,previewHash:hash,confirmedMonthlyRentUsd:z.literal(true),selection:z.array(z.object({sourceIndex:z.number().int().min(0).max(49),values:unitValues}).strict()).min(1).max(50),reason}).strict().refine(v=>new Set(v.selection.map(x=>x.sourceIndex)).size===v.selection.length&&new Set(v.selection.map(x=>x.values.unit_type)).size===v.selection.length,'Select each candidate and unit type only once')
export const pricingFields=['unit_type','bedrooms','bathrooms','sqft_min','sqft_max','rent_min','rent_max','deposit','available_count','move_in_specials'] as const
const number=(max:number)=>z.number().min(0).max(max).nullable(),integer=(max:number)=>z.number().int().min(0).max(max).nullable()
export const extractionCandidate=z.object({unit_type:z.string().trim().min(1).max(100),bedrooms:integer(20),bathrooms:number(20),sqft_min:integer(1000000),sqft_max:integer(1000000),rent_min:number(99999999.99),rent_max:number(99999999.99),deposit:number(99999999.99),available_count:integer(1000000),move_in_specials:z.string().max(5000).nullable(),evidence:z.array(z.object({field:z.enum(pricingFields),quote:z.string().min(1).max(500)}).strict()).min(1).max(30)}).strict().refine(v=>v.rent_min===null||v.rent_max===null||v.rent_min<=v.rent_max).refine(v=>v.sqft_min===null||v.sqft_max===null||v.sqft_min<=v.sqft_max)
export const extractionOutput=z.object({pricingBasis:z.enum(['monthly_rent_usd','unconfirmed']),units:z.array(extractionCandidate).max(50),notes:z.string().max(5000).nullable()}).strict()
export type ExtractionPreview=z.infer<typeof extractionOutput>
export function validateExtractionPreview(content:string,value:unknown){const parsed=extractionOutput.parse(value);for(const unit of parsed.units){for(const evidence of unit.evidence)if(!content.includes(evidence.quote))throw new Error('Evidence does not occur in the saved source.');for(const field of pricingFields)if(unit[field]!==null&&!unit.evidence.some(e=>e.field===field))throw new Error('A candidate value lacks a retained source quotation.')}return parsed}
