import {z} from 'zod'
import {marketId} from './decision-contracts'
export const runCategories=['all','attention','active','complete','closed','legacy']as const
export const MonitoringQuery=z.object({propertyId:marketId,filter:z.enum(runCategories).default('all'),requestId:marketId.optional(),cursor:marketId.optional()}).strict().refine(v=>!v.requestId||!v.cursor)
export const MonitoringRow=z.object({id:marketId,created_at:z.string(),updated_at:z.string(),kind:z.enum(['brand','source','extraction','brief','handoff','intake','legacy']),request_state:z.string(),category:z.enum(['attention','active','complete','closed','legacy']),label:z.string(),competitor_id:marketId.nullable(),brief_id:marketId.nullable(),handoff_id:marketId.nullable(),legacy_status:z.string().nullable()})
export type SavedMarketRun=z.infer<typeof MonitoringRow>
export const MonitoringPage=z.object({state:z.literal('ready'),runs:z.array(MonitoringRow).max(20),nextCursor:marketId.nullable(),counts:z.object(Object.fromEntries(runCategories.map(k=>[k,z.number().int().nonnegative()]))as Record<typeof runCategories[number],z.ZodNumber>),workers:z.array(z.object({name:z.enum(['process-market-sources','process-market-extractions']),lastStartedAt:z.string().nullable(),lastFinishedAt:z.string().nullable(),lastStatus:z.string().nullable()})).length(2),readAt:z.string()})
export const MonitoringDetail=z.object({state:z.literal('ready'),run:MonitoringRow})
export type MarketRunPage=z.infer<typeof MonitoringPage>
export interface MarketRuntime {sourcePaused:boolean;extractionPaused:boolean;extractionConfigured:boolean;automaticMonitoring:false}
const labels:Record<string,string>={queued:'Waiting to start',running:'In progress',received:'Captured page needs review',held:'Needs attention',result_ready:'Saved model result needs completion',preview_ready:'Pricing candidates need review',prepared:'Awaiting review or local completion',ready:'Saved report complete',completed:'Completed',stopped:'Stopped',rejected:'Rejected',withdrawn:'Withdrawn',missing_record:'Saved work needs repair'}
export function marketRunStatus(r:SavedMarketRun){if(r.kind==='brand'&&r.request_state==='preview_ready')return 'Brand statements need review';if(r.kind==='brand'&&r.request_state==='completed')return 'Brand review saved';if(r.kind==='intake')return r.request_state==='preview_ready'?'Competitor candidates need review':r.request_state==='applied'?'Reviewed competitors added':r.request_state==='stopped'?'Stopped':'Saved intake needs review';if(r.kind==='legacy')return 'Historical record · '+(r.legacy_status??'unknown result');if(r.kind==='handoff'&&r.request_state==='completed')return 'Draft created';if(r.kind==='extraction'&&r.request_state==='completed')return 'Reviewed prices applied';return labels[r.request_state]??'Saved status needs review'}
