import {describe,it,expect} from 'vitest'
import {buildSavedBrief} from './saved-brief'
import {renderBriefExport} from './brief-export'
import {BriefRequest,BriefReview,BriefExport} from './brief-contracts'
const id=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`
function source(){return {propertyId:id(1),propertyName:'Example <script> property',snapshotAt:'2026-09-22T12:00:00Z',windowStart:'2026-09-15T12:00:00Z',windowDays:7,competitors:[1,2].map(n=>({id:id(n+10),name:`Comp ${n}`,address:null,amenities:[],version:1})),units:[1,2].map(n=>({id:id(n+100),competitor_id:id(n+10),unit_type:`A${n}`,bedrooms:1,rent_min:1000*n,rent_max:null,sqft_min:null,sqft_max:null,available_count:null,capture_id:null,last_updated_at:null,version:1})),history:[],captures:[],subjectUnits:[{id:id(200),unit_type:'Subject',bedrooms:1,rent_min:1800,rent_max:null,last_updated_at:null,source_url:null,source:'manual',effective_at:null,expires_at:null}]}}
describe('retained market brief',()=>{
 it('uses comparable plan means and stable cited review prompts without synthetic probability or impact',()=>{const s=source(),a=buildSavedBrief(id(2),'hash',s),b=buildSavedBrief(id(2),'hash',s);expect(a).toEqual(b);expect(a.positions[0]).toMatchObject({subjectMean:1800,competitorMean:1500,differencePercent:20,competitors:2});expect(a.recommendations).toHaveLength(2);expect(a.recommendations[1].evidence).toHaveLength(2);expect(a.recommendations[1].subjectIds).toEqual([id(200)]);expect(a.recommendations[1]).not.toHaveProperty('confidence');expect(a.recommendations[1]).not.toHaveProperty('impact');expect(a.synthesisModel).toBeNull()})
 it('preserves zero and unknown values without claiming a pricing difference from a zero baseline',()=>{const s=source();s.units.forEach(u=>u.rent_min=0);const a=buildSavedBrief(id(2),'hash',s);expect(a.positions[0].competitorMean).toBe(0);expect(a.positions[0].differencePercent).toBeNull();expect(a.recommendations.some(r=>r.kind==='comparison_review')).toBe(false)})
 it('does not infer a subject comparison when subject evidence is absent',()=>{const s=source();s.subjectUnits=[];const a=buildSavedBrief(id(2),'hash',s);expect(a.positions[0].subjectMean).toBeNull();expect(a.recommendations.some(r=>r.kind==='comparison_review')).toBe(false)})
 it('separates new report recommendation identities from retries',()=>{expect(buildSavedBrief(id(2),'hash',source()).recommendations[0].id).not.toBe(buildSavedBrief(id(3),'hash',source()).recommendations[0].id)})
 it('exports exact deterministic content with date limits and escaped markdown',()=>{const a=buildSavedBrief(id(2),'hash',source()),md=renderBriefExport(a,'markdown');expect(md).not.toContain('<script>');expect(md).toContain('2026-09-22T12:00:00Z');expect(md).toContain('price effective unknown');expect(md).toBe(renderBriefExport(a,'markdown'));expect(JSON.parse(renderBriefExport(a,'json')).brief).toEqual(a)})
 it('rejects incomplete evidence instead of inventing a brief',()=>{expect(()=>buildSavedBrief(id(2),'hash',{})).toThrow()})
 it('requires exact review identities and a reason; rejects forged recommendations and artifact bytes',()=>{const base={propertyId:id(1),requestId:id(2),briefId:id(3),expectedVersion:2,reason:'Reviewed exact report'};expect(BriefRequest.safeParse({propertyId:id(1),requestId:id(2),windowDays:1.5,reason:'Reviewed'}).success).toBe(false);expect(BriefReview.safeParse({...base,recommendationId:id(4),expectedReviewId:null,decision:'consider',acknowledgedSourceChange:false}).success).toBe(true);expect(BriefReview.safeParse({...base,recommendationId:id(4),decision:'consider',acknowledgedSourceChange:false,title:'Forged'}).success).toBe(false);expect(BriefExport.safeParse({...base,format:'json',content:'fake bytes'}).success).toBe(false)})
})
