import {createHash} from 'node:crypto'
import {z} from 'zod'
import {AnalysisSnapshot,analyzeMarket,type MarketAnalysis} from './analysis'
export const BriefSources=AnalysisSnapshot.extend({subjectUnits:z.array(z.object({id:z.string(),unit_type:z.string(),bedrooms:z.number().int().min(0),rent_min:z.number().nonnegative().nullable(),rent_max:z.number().nonnegative().nullable(),last_updated_at:z.string().nullable(),source_url:z.string().nullable(),source:z.string(),effective_at:z.string().nullable(),expires_at:z.string().nullable()}))})
export interface BriefRecommendation {id:string;title:string;rationale:string;kind:'source_review'|'comparison_review';priority:'review';evidence:MarketAnalysis['evidence'];subjectIds:string[];limitations:string[]}
export interface SavedMarketBrief {schemaVersion:'market-brief-v2';reportId:string;propertyId:string;propertyName:string;sourceHash:string;snapshotAt:string;windowDays:number;synthesisModel:null;analysis:MarketAnalysis;positions:Array<{bedrooms:number;subjectMean:number|null;subjectPlans:number;competitorMean:number|null;competitorPlans:number;competitors:number;differencePercent:number|null;subjectIds:string[]}>;subjectUnits:z.infer<typeof BriefSources>['subjectUnits'];recommendations:BriefRecommendation[];limitations:string[]}
function stableId(reportId:string,key:string){const hash=createHash('sha256').update(`${reportId}:${key}`).digest('hex').slice(0,32);return `${hash.slice(0,8)}-${hash.slice(8,12)}-${hash.slice(12,16)}-${hash.slice(16,20)}-${hash.slice(20)}`}
export function buildSavedBrief(reportId:string,sourceHash:string,raw:unknown):SavedMarketBrief{
 const snapshot=BriefSources.parse(raw),analysis=analyzeMarket(snapshot)
 const bedroomCounts=[...new Set([...snapshot.subjectUnits.map(u=>u.bedrooms),...analysis.position.map(p=>p.bedrooms)])].sort((a,b)=>a-b)
 const positions=bedroomCounts.map(bedrooms=>{const subjects=snapshot.subjectUnits.filter(u=>u.bedrooms===bedrooms&&u.rent_min!==null),market=analysis.position.find(p=>p.bedrooms===bedrooms),subjectMean=subjects.length?Math.round(subjects.reduce((total,u)=>total+u.rent_min!,0)/subjects.length*100)/100:null,competitorMean=market?.avgRent??null
 return {bedrooms,subjectMean,subjectPlans:subjects.length,competitorMean,competitorPlans:market?.pricedPlans??0,competitors:market?.competitors??0,differencePercent:subjectMean!==null&&competitorMean!==null&&competitorMean>0&&market!.competitors>=2?Math.round((subjectMean-competitorMean)/competitorMean*10000)/100:null,subjectIds:subjects.map(u=>u.id)}})
 const limitations=['This is a deterministic summary of saved advertised prices, not a forecast or a measured business outcome.','A recommendation is a review prompt. No calibrated confidence, expected revenue or automatic reward is inferred.','Bedroom groups do not control for concessions, lease duration, amenities, floor-plan size or availability. Verify comparability before changing prices.']
 const recommendations:BriefRecommendation[]=[]
 if(analysis.summary.unknownEffectiveDates>0 || analysis.summary.pricedPlans<analysis.summary.totalUnitsTracked || analysis.trendCoverage.netChangePct===null){recommendations.push({id:stableId(reportId,'source-review'),kind:'source_review',priority:'review',title:'Verify source coverage before relying on this comparison',rationale:`${analysis.summary.pricedPlans} of ${analysis.summary.totalUnitsTracked} plans have known starting rents; ${analysis.summary.unknownEffectiveDates} have no known price-effective date. ${analysis.trendCoverage.matchedPlans} plans have comparable saved history for this period.`,evidence:analysis.evidence,subjectIds:[],limitations:[...limitations,'Unknown source dates must not be interpreted as current prices.']})}
 for(const p of positions){if(p.differencePercent===null || p.differencePercent===0)continue;recommendations.push({id:stableId(reportId,`comparison:${p.bedrooms}`),kind:'comparison_review',priority:'review',title:`Review the ${p.bedrooms===0?'studio':`${p.bedrooms}-bedroom`} comparison`,rationale:`The subject plan mean is $${p.subjectMean}; the saved competitor plan mean is $${p.competitorMean} across ${p.competitors} competitors (${p.differencePercent>0?'+':''}${p.differencePercent}%). This difference alone does not support a rent change.`,evidence:analysis.position.find(m=>m.bedrooms===p.bedrooms)?.citations??[],subjectIds:p.subjectIds,limitations})}
 return {schemaVersion:'market-brief-v2',reportId,propertyId:snapshot.propertyId,propertyName:snapshot.propertyName,sourceHash,snapshotAt:snapshot.snapshotAt,windowDays:snapshot.windowDays,synthesisModel:null,analysis,positions,subjectUnits:snapshot.subjectUnits,recommendations,limitations}
}
