import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({actor:vi.fn(),read:vi.fn(),decide:vi.fn()}))
vi.mock('@/utils/property-units/store',()=>({unitActor:d.actor,readUnits:d.read,decideUnit:d.decide,UnitError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {GET,POST} from './route'
import {UnitError} from '@/utils/property-units/store'
const id='11111111-1111-1111-1111-111111111111',body={requestId:id,propertyId:id,unitId:id,versionId:id,expectedDraftId:id,expectedAppliedId:null,expectedDecisionId:id,expectedUnitHash:'a'.repeat(64),dataHash:'b'.repeat(64),operation:'approve',confirmed:true,reason:'Review exact source'}
beforeEach(()=>{vi.clearAllMocks();d.actor.mockResolvedValue('actor');d.read.mockResolvedValue({state:'ready',items:[]});d.decide.mockResolvedValue({state:'saved',unitId:id})})
it('authenticates before parsing or reading',async()=>{d.actor.mockRejectedValue(new UnitError('Unauthorized',401));expect((await GET(new Request('http://local'))).status).toBe(401);expect((await POST(new Request('http://local',{method:'POST',body:'bad'}))).status).toBe(401);expect(d.decide).not.toHaveBeenCalled()})
it('requires strict exact decisions and no direct provider controls',async()=>{for(const value of[{...body,provider:'openai'},{...body,confirmed:false},{propertyId:id,operation:'approve'}])expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(value)}))).status).toBe(400);expect(d.decide).not.toHaveBeenCalled()})
it('saves an exact actor-bound decision with private response',async()=>{const result=await POST(new Request('http://local',{method:'POST',body:JSON.stringify(body)}));expect(result.status).toBe(200);expect(result.headers.get('Cache-Control')).toBe('private, no-store');expect(d.decide).toHaveBeenCalledWith('actor',body)})
it('enforces actual streamed and declared byte limits',async()=>{expect((await POST(new Request('http://local',{method:'POST',headers:{'content-length':'262145'},body:'{}'}))).status).toBe(413);expect((await POST(new Request('http://local',{method:'POST',body:'x'.repeat(262145)}))).status).toBe(413);expect(d.decide).not.toHaveBeenCalled()})
it('reads fail closed and never mutate facts',async()=>{expect((await GET(new Request(`http://local?propertyId=${id}`))).status).toBe(200);expect(d.decide).not.toHaveBeenCalled();expect((await GET(new Request(`http://local?propertyId=${id}&kind=unit`))).status).toBe(400);d.read.mockRejectedValue(new Error('secret detail'));const result=await GET(new Request(`http://local?propertyId=${id}`));expect(result.status).toBe(503);expect(await result.json()).toEqual({error:'Floor-plan review is unavailable.'})})
