import { beforeEach, describe, it, expect, vi } from 'vitest';
const { actor, rpc } = vi.hoisted(() => ({ actor: vi.fn(), rpc: vi.fn() }));
vi.mock('@/utils/propertyaudit/decision-store', async () => { const { InventoryError } = await import('@/utils/knowledge/inventory'); return { auditActor: actor, auditRpc: rpc, InventoryError }; });
import { GET, POST } from './route';
const id = 'aa760000-0000-4000-8000-000000000001', property = 'aa760000-0000-4000-8000-000000000002', user = 'aa760000-0000-4000-8000-000000000003', download = 'aa760000-0000-4000-8000-000000000004';
const options = { format: 'queries_csv', template: 'comprehensive', sections: ['summary'] };
const source = { version: 1, property: { id: property, name: 'Fixture' }, runs: [], queries: [{ id: 'q', text: 'Exact saved question' }], findings: [] };
const record = { id, property_id: property, actor_id: user, state: 'prepared', options, source, source_hash: 'saved-source' };
const ready = { state: 'ready', id, propertyId: property, record, canResume: true, observations: [] };
function req(body: unknown, origin = 'http://localhost:9430') { return new Request('http://localhost:9430/api/propertyaudit/reports', { method: 'POST', headers: { origin, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); }
function decision(extra = {}) { return { operation: 'prepare', id, propertyId: property, expectedActorId: user, options, ...extra }; }
beforeEach(() => { vi.clearAllMocks(); actor.mockResolvedValue(user); rpc.mockImplementation(async (name) => name === 'read_geo_reports' ? ready : { state: 'saved', id, propertyId: property, status: name === 'prepare_geo_report' ? 'prepared' : 'ready' }); });
describe('recorded audit report API', () => {
    it('captures once and renders only the saved source', async () => { const r = await POST(req(decision())); expect(r.status).toBe(200); expect(rpc.mock.calls.map(x => x[0])).toEqual(['prepare_geo_report', 'read_geo_reports', 'finish_geo_report']); expect(rpc.mock.calls[2][1].p_artifact).toContain('Exact saved question'); expect(rpc.mock.calls[2][1].p_source_hash).toBe('saved-source'); });
    it('recovers a ready report without rendering or recapturing', async () => { rpc.mockResolvedValue({ ...ready, record: { ...record, state: 'ready', artifact: 'ORIGINAL bytes', artifact_hash: 'hash' } }); const r = await POST(req({ operation: 'resume', id, propertyId: property, expectedActorId: user })); expect(r.status).toBe(200); expect(rpc).toHaveBeenCalledTimes(1); expect((await r.json()).status).toBe('ready'); });
    it('resumes incomplete rendering from retained evidence', async () => { expect((await POST(req({ operation: 'resume', id, propertyId: property, expectedActorId: user }))).status).toBe(200); expect(rpc.mock.calls.map(x => x[0])).toEqual(['read_geo_reports', 'finish_geo_report']); });
    it('holds another requester from resuming', async () => { rpc.mockResolvedValue({ ...ready, canResume: false }); expect((await POST(req({ operation: 'resume', id, propertyId: property, expectedActorId: user }))).status).toBe(403); expect(rpc).toHaveBeenCalledTimes(1); });
    it('honors cancelled identity without reading or rendering', async () => { rpc.mockResolvedValue({ state: 'replayed', id, propertyId: property, status: 'cancelled' }); expect((await POST(req(decision()))).status).toBe(200); expect(rpc).toHaveBeenCalledTimes(1); });
    it('cancels only the request identity, never overwrites source options', async () => { expect((await POST(req({ operation: 'cancel', id, propertyId: property, expectedActorId: user }))).status).toBe(200); expect(rpc).toHaveBeenCalledWith('prepare_geo_report', expect.objectContaining({ p_id: id, p_options: {}, p_cancel: true })); });
    it('requires same-origin decisions', async () => { expect((await POST(req(decision(), 'https://attacker.invalid'))).status).toBe(403); expect(actor).not.toHaveBeenCalled(); expect(rpc).not.toHaveBeenCalled(); });
    it('requires current actor identity before native decision', async () => { actor.mockResolvedValue(id); expect((await POST(req(decision()))).status).toBe(409); expect(rpc).not.toHaveBeenCalled(); });
    it.each([{ format: 'pdf' }, { schedule: true }, { recipients: ['client@fixture.invalid'] }, { sections: [] }, { runId: 'invalid' }])('rejects unsupported options %j', async (extra) => { expect((await POST(req(decision({ options: { ...options, ...extra } })))).status).toBe(400); expect(rpc).not.toHaveBeenCalled(); });
    it('does not claim completion when saved source is malformed', async () => { rpc.mockResolvedValue({ ...ready, record: { ...record, source: {} } }); expect((await POST(req({ operation: 'resume', id, propertyId: property, expectedActorId: user }))).status).toBe(503); expect(rpc).toHaveBeenCalledTimes(1); });
    it('uses private uncached history with actual actor', async () => { rpc.mockResolvedValue({ state: 'ready', propertyId: property, items: [], count: 0 }); const r = await GET(new Request(`http://localhost/api/propertyaudit/reports?propertyId=${property}`)); expect(r.status).toBe(200); expect((await r.json()).actorId).toBe(user); expect(r.headers.get('Cache-Control')).toContain('no-store'); });
    it('blocks artifacts lacking a prepared download for this actor', async () => { rpc.mockResolvedValue({ ...ready, record: { ...record, state: 'ready', artifact: 'private bytes' } }); const r = await GET(new Request(`http://localhost/api/propertyaudit/reports?propertyId=${property}&id=${id}&artifact=1&downloadId=${download}`)); expect(r.status).toBe(403); });
    it('serves retained bytes with safe actual metadata after download preparation', async () => { rpc.mockResolvedValue({ ...ready, record: { ...record, state: 'ready', artifact: 'EXACT bytes' }, observations: [{ id: download, actor_id: user, outcome: 'prepared' }] }); const r = await GET(new Request(`http://localhost/api/propertyaudit/reports?propertyId=${property}&id=${id}&artifact=1&downloadId=${download}`)); expect(r.status).toBe(200); expect(await r.text()).toBe('EXACT bytes'); expect(r.headers.get('Content-Type')).toContain('text/csv'); expect(r.headers.get('Content-Disposition')).toContain('.csv'); expect(r.headers.get('Content-Security-Policy')).toContain("default-src 'none'"); });
    it('records download preparation separately from browser outcome', async () => { await POST(req({ operation: 'download', id: download, propertyId: property, expectedActorId: user, reportId: id })); expect(rpc).toHaveBeenLastCalledWith('observe_geo_report', expect.objectContaining({ p_outcome: 'prepared', p_report_id: id })); await POST(req({ operation: 'observe', id: download, propertyId: property, expectedActorId: user, reportId: id, outcome: 'download_initiated' })); expect(rpc).toHaveBeenLastCalledWith('observe_geo_report', expect.objectContaining({ p_outcome: 'download_initiated' })); });
    it('never accepts a claim of verified client receipt', async () => { expect((await POST(req({ operation: 'observe', id: download, propertyId: property, expectedActorId: user, reportId: id, outcome: 'delivered' }))).status).toBe(400); });
    it('rejects malformed history continuation and oversized decisions', async () => { expect((await GET(new Request(`http://localhost/api/propertyaudit/reports?propertyId=${property}&offset=-1`))).status).toBe(400); expect((await POST(req({ ...decision(), padding: 'a'.repeat(17000) }))).status).toBe(413); });
    it('keeps native/database errors visible', async () => { rpc.mockRejectedValue(new Error('DB failed')); expect((await POST(req(decision()))).status).toBe(503); });
});
