import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest'
import {NextRequest} from 'next/server'
const m=vi.hoisted(()=>({auth:vi.fn(),rpc:vi.fn(),fetch:vi.fn()}))
vi.mock('@/utils/supabase/server',()=>({createClient:async()=>({auth:{getUser:m.auth}})}))
vi.mock('@/utils/crm/workspace',()=>({crmRpc:m.rpc}))
vi.mock('@/utils/services/runtime-config',()=>({getDataEngineUrl:()=> 'http://worker.local'}))
import {GET,POST} from './route'
const property='33333333-3333-3333-3333-333333333333',requestId='df9e624c-df84-4974-bc6c-1032c748e844'
const run={action:'run',propertyId:property,requestId,handoffId:property,payloadHash:'a'.repeat(64)}
const req=(b:unknown)=>new NextRequest('http://localhost/api/crm/deliveries',{method:'POST',body:JSON.stringify(b)})
beforeEach(()=>{vi.resetAllMocks();vi.stubGlobal('fetch',m.fetch);vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');m.auth.mockResolvedValue({data:{user:{id:'actor'}},error:null})})
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals()})
describe('CRM delivery boundary',()=>{
 it('requires authentication before any private read or request',async()=>{m.auth.mockResolvedValue({data:{user:null},error:null});expect((await GET(new NextRequest('http://localhost/api/crm/deliveries?propertyId='+property))).status).toBe(401);expect((await POST(req(run))).status).toBe(401);expect(m.rpc).not.toHaveBeenCalled()})
 it('cannot accept client credentials, origin or actor',async()=>{const prepare={action:'prepare',propertyId:property,requestId,leadId:property};for(const extra of [{credentials:{api_key:'secret'}},{origin:'workflow'},{actorId:'forged'}])expect((await POST(req({...prepare,...extra}))).status).toBe(400);expect(m.rpc).not.toHaveBeenCalled()})
 it('prepares a saved operator request without dispatching',async()=>{m.rpc.mockResolvedValue({state:'queued'});expect((await POST(req({action:'prepare',propertyId:property,requestId,leadId:property,note:'Saved conversation summary'}))).status).toBe(200);expect(m.rpc).toHaveBeenCalledWith('request_crm_handoff',{p_property_id:property,p_actor_id:'actor',p_lead_id:property,p_request_key:'operator/'+requestId,p_origin:'operator',p_note:'Saved conversation summary'});expect(m.fetch).not.toHaveBeenCalled()})
 it('pauses before recording execution approval or contacting the worker',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect((await POST(req(run))).status).toBe(423);expect(m.rpc).not.toHaveBeenCalled();expect(m.fetch).not.toHaveBeenCalled()})
 it.each(['forbidden','owner_required','preview_conflict','stale_source','stale_configuration'])('holds %s approval before worker dispatch',async state=>{m.rpc.mockResolvedValue({state});expect((await POST(req(run))).status).toBe(state==='forbidden'?403:409);expect(m.fetch).not.toHaveBeenCalled()})
 it('only forwards the approved private handoff identity',async()=>{m.rpc.mockResolvedValueOnce({state:'applied'}).mockResolvedValueOnce({state:'saved',deliveryState:'confirmed'});m.fetch.mockResolvedValue(new Response('{}'));expect((await POST(req(run))).status).toBe(200);expect(JSON.parse(m.fetch.mock.calls[0][1].body)).toEqual({handoff_id:property});expect(m.rpc.mock.calls[0][1].p_payload_hash).toBe(run.payloadHash)})
 it('recovers an uncertain worker acknowledgment from saved state without retrying',async()=>{m.rpc.mockResolvedValueOnce({state:'replayed'}).mockResolvedValueOnce({state:'saved',deliveryState:'sending'});m.fetch.mockRejectedValue(new Error('private token'));const response=await POST(req(run));expect(await response.json()).toEqual({state:'saved',deliveryState:'sending'});expect(m.fetch).toHaveBeenCalledTimes(1)})
 it('cannot cancel away an uncertain write',async()=>{m.rpc.mockResolvedValue({state:'reconciliation_required'});expect((await POST(req({action:'stop',propertyId:property,requestId,handoffId:property}))).status).toBe(409);expect(m.fetch).not.toHaveBeenCalled()})
 it('reads exact saved values through current scope without provider work',async()=>{m.rpc.mockResolvedValue({state:'saved',payload:{email:'private@example.invalid'}});const r=await GET(new NextRequest('http://localhost/api/crm/deliveries?propertyId='+property+'&handoffId='+property));expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(m.rpc).toHaveBeenCalledWith('preview_crm_handoff',{p_property_id:property,p_actor_id:'actor',p_handoff_id:property});expect(m.fetch).not.toHaveBeenCalled()})
})

describe('CRM destination recovery',()=>{
 it('allows read-only recovery while transfers are paused and forwards only saved check identity',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');m.rpc.mockResolvedValueOnce({state:'queued',checkId:requestId}).mockResolvedValueOnce({state:'saved',deliveryState:'needs_reconciliation'});m.fetch.mockResolvedValue(new Response('{}'));expect((await POST(req({action:'check_destination',propertyId:property,requestId,handoffId:property}))).status).toBe(200);expect(JSON.parse(m.fetch.mock.calls[0][1].body)).toEqual({check_id:requestId});expect(m.fetch.mock.calls[0][0]).toContain('/reconciliation-operation')})
 it('does not accept raw provider evidence or external IDs from the browser',async()=>{expect((await POST(req({action:'accept_destination',propertyId:property,requestId,handoffId:property,checkId:requestId,evidenceHash:'a'.repeat(64),externalId:'forged'}))).status).toBe(400);expect(m.rpc).not.toHaveBeenCalled()})
 it('accepts only persisted evidence and never contacts a delivery worker',async()=>{m.rpc.mockResolvedValue({state:'applied'});expect((await POST(req({action:'accept_destination',propertyId:property,requestId,handoffId:property,checkId:requestId,evidenceHash:'a'.repeat(64)}))).status).toBe(200);expect(m.rpc).toHaveBeenCalledWith('accept_crm_reconciliation',{p_property_id:property,p_actor_id:'actor',p_handoff_id:property,p_check_id:requestId,p_evidence_hash:'a'.repeat(64),p_request_id:requestId});expect(m.fetch).not.toHaveBeenCalled()})
 it.each(['worker_pending','forbidden','request_conflict'])('holds %s before recovery provider calls',async state=>{m.rpc.mockResolvedValue({state});expect((await POST(req({action:'check_destination',propertyId:property,requestId,handoffId:property}))).status).toBe(state==='forbidden'?403:409);expect(m.fetch).not.toHaveBeenCalled()})
})
