import {beforeEach,afterEach,describe,it,expect,vi}from 'vitest'
import {postReadiness,pendingReadiness,clearPendingReadiness}from './client'
const propertyId='33333333-3333-3333-3333-333333333333',command={propertyId,operation:'build' as const,enabledCapabilities:[],reason:'Private reviewer explanation'}
beforeEach(()=>{const m=new Map<string,string>();vi.stubGlobal('sessionStorage',{getItem:(k:string)=>m.get(k)||null,setItem:(k:string,v:string)=>m.set(k,v),removeItem:(k:string)=>m.delete(k)});vi.stubGlobal('fetch',vi.fn())});afterEach(()=>vi.unstubAllGlobals())
describe('readiness lost-result recovery',()=>{
 it('retains only property request and digest when result is unknown',async()=>{vi.mocked(fetch).mockRejectedValue(new Error('Lost result'));await expect(postReadiness(command)).rejects.toThrow('Lost');expect(Object.keys(pendingReadiness(propertyId)!)).toEqual(['id','propertyId','hash']);expect(JSON.stringify(pendingReadiness(propertyId))).not.toContain('Private');const first=pendingReadiness(propertyId)!.id;await expect(postReadiness(command)).rejects.toThrow();expect(pendingReadiness(propertyId)!.id).toBe(first)})
 it('does not send changed content before resolving an earlier unknown result',async()=>{vi.mocked(fetch).mockRejectedValue(new Error('lost'));await expect(postReadiness(command)).rejects.toThrow();await expect(postReadiness({...command,reason:'Changed request'})).rejects.toThrow('earlier');expect(fetch).toHaveBeenCalledTimes(1)})
 it('accepts exact build receipt even when deduplication reuses an earlier snapshot',async()=>{vi.mocked(fetch).mockImplementation(async(_url,init)=>{const b=JSON.parse(String(init?.body));return Response.json({state:'saved',propertyId,decisionId:b.requestId,snapshotId:'previous-snapshot'})});await expect(postReadiness(command)).resolves.toMatchObject({snapshotId:'previous-snapshot'});expect(pendingReadiness(propertyId)).toBeNull()})
 it('mismatched review receipt stays pending',async()=>{vi.mocked(fetch).mockImplementation(async(_url,init)=>{const b=JSON.parse(String(init?.body));return Response.json({state:'saved',propertyId,decisionId:b.requestId,snapshotId:'wrong'})});await expect(postReadiness({propertyId,operation:'approve',snapshotId:'expected',snapshotHash:'a'.repeat(64),sourceHash:'b'.repeat(64),confirmed:true,reason:'Review exact check'})).rejects.toThrow('verified');expect(pendingReadiness(propertyId)).not.toBeNull()})
 it('clears a definitive conflict but not a different pending identity',async()=>{vi.mocked(fetch).mockResolvedValue(Response.json({error:'Changed'},{status:409}));await expect(postReadiness(command)).rejects.toThrow('Changed');expect(pendingReadiness(propertyId)).toBeNull();vi.mocked(fetch).mockRejectedValue(new Error('lost'));await expect(postReadiness(command)).rejects.toThrow();clearPendingReadiness(propertyId,'wrong');expect(pendingReadiness(propertyId)).not.toBeNull()})
})
