import {describe,it,expect}from 'vitest'
import {evaluateReadinessSources,evaluateCapabilityReadiness,type ReadinessSources}from './evaluator'
import {normalizeBrandAssetRow,hashBrandForgeContract}from '@/utils/brandforge/normalize'
const now=new Date('2026-09-23T00:00:00Z')
function sources():ReadinessSources{const brand:Record<string,unknown>={id:'brand',approval_status:'approved',generation_status:'complete'};brand.contract_hash=hashBrandForgeContract(normalizeBrandAssetRow(brand));return{property:{id:'property',org_id:'org',name:'Supplied property',address:{street:'1 Supplied Lane',city:'City',state:'State'},amenities:['Supplied amenity'],settings:{additionalUrls:[]}},contacts:[{id:'contact',is_primary:true,email:'fixture@example.invalid',phone:'555-0100'}],brand,assets:[],units:[],pointsOfInterest:[],neighborhoodTotal:0,legal:{id:'legal',approved_at:'2026-01-01',status:'approved',effective_at:'2026-01-01',jurisdiction:'Supplied area',legal_entity_name:'Supplied entity',...Object.fromEntries(['privacy_policy','terms','accessibility','fair_housing','pricing_disclaimer','analytics_consent','communications_consent'].map(k=>[k,{text:'Supplied text'}]))},integrations:[],analyticsDestinations:[],chatbotContext:null,chatbotEligibility:{state:'unavailable'},eligibleUnitIds:[],unexpiredAssetIds:[]}as unknown as ReadinessSources}
describe('complete readiness evaluation',()=>{
 it('retains current evidence without inventing optional inventory or automatic approval',()=>{const r=evaluateReadinessSources(sources(),[],'a'.repeat(64),now);expect(r.status).toBe('ready');expect(r.payload.assets).toEqual([]);expect(r.payload.units).toEqual([]);expect(r.domains.units.blocking).toBe(false);expect(r.payload.readinessEvidence.sourceHash).toBe('a'.repeat(64))})
 it('requires the actual approved brand contract hash',()=>{const s=sources();s.brand!.contract_hash='b'.repeat(64);expect(evaluateReadinessSources(s,[],'a'.repeat(64),now).domains.brand.blocking).toBe(true);s.brand!.approval_status='draft';s.brand!.contract_hash=hashBrandForgeContract(normalizeBrandAssetRow(s.brand!));expect(evaluateReadinessSources(s,[],'a'.repeat(64),now).domains.brand.blocking).toBe(true)})
 it('missing or future-effective legal evidence cannot be overridden',()=>{const s=sources();s.legal!.communications_consent={text:' '};expect(evaluateReadinessSources(s,[],'a'.repeat(64),now).domains.legal.approvalPolicy).toBe('required');expect(evaluateReadinessSources(s,[],'a'.repeat(64),now).domains.legal.blocking).toBe(true);s.legal!.communications_consent={text:'Supplied'};s.legal!.effective_at='2099-01-01';expect(evaluateReadinessSources(s,[],'a'.repeat(64),now).domains.legal.blocking).toBe(true)})
 it('source boundaries change a check even when selected public facts match',()=>{expect(evaluateReadinessSources(sources(),[],'a'.repeat(64),now).contentHash).not.toBe(evaluateReadinessSources(sources(),[],'b'.repeat(64),now).contentHash)})
 it('holds chatbot capability when current serving evidence has expired',()=>{const s=sources();s.chatbotContext={id:'bot',status:'current',requires_review:false}as ReadinessSources['chatbotContext'];expect(evaluateReadinessSources(s,['chatbot'],'a'.repeat(64),now).payload.enabledCapabilities).toEqual([]);s.chatbotEligibility={state:'ready'};expect(evaluateReadinessSources(s,['chatbot'],'a'.repeat(64),now).payload.enabledCapabilities).toEqual(['chatbot'])})
 it('uses real connection statuses and current CRM review receipts',()=>{const integration={id:'crm',platform:'hubspot',status:'connected',verified_at:null,mapping_validated:true,crm_approved_review_id:'review',crm_validation_receipt_id:'receipt'},input={enabledCapabilities:['crm'],integrations:[integration],analyticsDestinations:[],hasChatbotContext:false};expect(evaluateCapabilityReadiness(input)).toEqual([]);expect(evaluateCapabilityReadiness({...input,integrations:[{...integration,crm_validation_receipt_id:null}]})).toHaveLength(1);expect(evaluateCapabilityReadiness({...input,integrations:[{...integration,status:'expired'}]})).toHaveLength(1)})
 it('does not use future or expired approved units',()=>{const s=sources();s.units=[{id:'future',active:true,review_status:'approved',effective_at:'2099-01-01'},{id:'old',active:true,review_status:'approved',expires_at:'2026-01-01'}]as unknown as ReadinessSources['units'];expect(evaluateReadinessSources(s,[],'a'.repeat(64),now).payload.units).toEqual([])})
})
