import {test as base,expect,type Page} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {execFileSync} from 'node:child_process'
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,baseURL=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430',origin=new URL(baseURL).origin,password='local-credential-fixture-password',nextPassword='new-local-credential-fixture-password',headers={origin}
const service=()=>createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!),auth=()=>createClient(url,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
type User={id:string;email:string}
type Fixture={db:ReturnType<typeof service>;org:string;member:User;admin:User;unassigned:User}
function sql(input:string){return execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input,stdio:['pipe','pipe','pipe']})}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['127.0.0.1','localhost'].includes(new URL(url).hostname)||!['127.0.0.1','localhost'].includes(new URL(baseURL).hostname))throw new Error('Disposable local credential fixtures required')
 const db=service(),org=randomUUID(),users:User[]=[];expect((await db.from('organizations').insert({id:org,name:'Account credential browser fixture'})).error).toBeNull()
 try{for(const[role,organization]of[['viewer',org],['admin',org],['viewer',null]]as const){const email='credential-browser-'+randomUUID()+'@p11.test',r=await db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:'Credential fixture account',private:'PRIVATE-AUTH-FIXTURE'}});expect(r.error).toBeNull();const id=r.data.user!.id;users.push({id,email});expect((await db.from('profiles').upsert({id,role,org_id:organization})).error).toBeNull()}await provide({db,org,member:users[0],admin:users[1],unassigned:users[2]})}
 finally{sql(`BEGIN;SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id=NULL,role='viewer'WHERE org_id='${org}';DELETE FROM public.organizations WHERE id='${org}';COMMIT;`);for(const u of users)expect((await db.auth.admin.deleteUser(u.id)).error).toBeNull();expect((await db.from('account_credential_requests').select('*',{count:'exact',head:true}).in('actor_id',users.map(u=>u.id))).count).toBe(0)}
}})
test.setTimeout(180000)
async function login(page:Page,u:User){await page.goto('/auth/login?redirect=%2Faccount%2Fsecurity');await page.getByLabel('Email address').fill(u.email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/account\/security/,{timeout:30000});await expect(work(page).getByLabel('Current password')).toBeVisible()}
const work=(p:Page)=>p.getByRole('region',{name:'Recorded password changes'})
async function fill(page:Page,old=password,next=nextPassword){const w=work(page);await w.getByLabel('Current password',{exact:true}).fill(old);await w.getByLabel('New password',{exact:true}).fill(next);await w.getByLabel('Confirm new password',{exact:true}).fill(next)}
async function current(page:Page){const r=await page.request.get('/api/account/credentials');expect(r.status()).toBe(200);expect(r.headers()['cache-control']).toContain('no-store');return r.json()}
async function decision(page:Page,data:Record<string,unknown>){return page.request.post('/api/account/credentials',{headers,data})}
async function accepts(u:User,p:string){const c=auth(),r=await c.auth.signInWithPassword({email:u.email,password:p});if(r.data.session)await c.auth.admin.signOut(r.data.session.access_token,'local');return !r.error}

test('actual password commit survives a lost reply without retaining or resubmitting credentials',async({page,fixture:f},info)=>{
 await login(page,f.member);const w=work(page);let lost=false;await page.route('**/api/account/credentials',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await fill(page);await w.getByRole('button',{name:'Update Password',exact:true}).click();await expect(w).toContainText('A password request needs review.');const pending=await page.evaluate(actor=>JSON.parse(sessionStorage.getItem('p11.account-credentials.pending.v1:'+actor)!),f.member.id);expect(Object.keys(pending)).toEqual(['id']);expect(JSON.stringify(pending)).not.toContain('password');const saved=await f.db.from('account_credential_requests').select('state').eq('id',pending.id).single();expect(saved.data?.state).toBe('confirmed');await page.reload();await w.getByRole('button',{name:'Check saved password request'}).click();await expect(w.getByRole('status')).toContainText('Your password change is confirmed.');expect(await accepts(f.member,password)).toBe(false);expect(await accepts(f.member,nextPassword)).toBe(true);await w.getByRole('button',{name:'Password request history'}).click();await expect(w).toContainText('Showing 3 of 3 password events');await w.getByRole('button',{name:/^confirmed ·/}).click();await expect(w.getByLabel('Saved password request details')).toContainText('confirmed');const detail=await page.request.get('/api/account/credentials?kind=detail&requestId='+pending.id),serialized=JSON.stringify(await detail.json());expect(serialized).not.toContain(nextPassword);expect(serialized).not.toContain('PRIVATE-AUTH');expect(serialized).not.toContain('claimId');const account=await f.db.auth.admin.getUserById(f.member.id);expect(account.data.user?.user_metadata.private).toBe('PRIVATE-AUTH-FIXTURE');await page.setViewportSize({width:390,height:844});await w.screenshot({path:info.outputPath('password-mobile.png')})
})
test('wrong current password does not change credentials or leave a verification session',async({page,fixture:f})=>{
 await login(page,f.member);await fill(page,'wrong-synthetic-password');await work(page).getByRole('button',{name:'Update Password',exact:true}).click();await expect(work(page).getByRole('status')).toContainText('Your current password could not be verified.');await expect(work(page).getByLabel('Current password')).toHaveValue('');await expect(work(page).getByLabel('New password',{exact:true})).toHaveValue('');const sessions=await page.request.get('/api/account/sessions');expect((await sessions.json()).sessions).toHaveLength(1);expect(await accepts(f.member,password)).toBe(true);expect(await accepts(f.member,nextPassword)).toBe(false);const r=await f.db.from('account_credential_requests').select('state,cleanup_outcome').eq('actor_id',f.member.id);expect(r.data).toEqual([{state:'verification_failed',cleanup_outcome:'not_created'}]);await fill(page);await work(page).getByRole('button',{name:'Update Password',exact:true}).click();await expect(work(page).getByRole('status')).toContainText('Your password change is confirmed.')
})
test('unused cancellation holds a delayed password request and permits a new explicit change',async({page,fixture:f})=>{
 await login(page,f.member);let intercepted:Record<string,unknown>|null=null;await page.route('**/api/account/credentials',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='change'&&!intercepted){intercepted=route.request().postDataJSON();await route.abort('failed')}else await route.continue()});await fill(page);await work(page).getByRole('button',{name:'Update Password',exact:true}).click();await expect(work(page)).toContainText('A password request needs review.');await work(page).getByRole('button',{name:'Cancel uncommitted password change'}).click();await expect(work(page).getByRole('status')).toContainText('request is cancelled');const late=await decision(page,intercepted!);expect(late.status()).toBe(200);expect((await late.json()).status).toBe('cancelled');expect(await accepts(f.member,password)).toBe(true);await fill(page);await work(page).getByRole('button',{name:'Update Password',exact:true}).click();await expect(work(page).getByRole('status')).toContainText('Your password change is confirmed.')
})
test('cancellation after execution claim prevents a late real Auth transaction from changing the password',async({page,fixture:f})=>{
 await login(page,f.member);const source=await current(page),sessions=await(await page.request.get('/api/account/sessions')).json(),id=randomUUID(),claim=await f.db.rpc('claim_account_credential',{p_id:id,p_actor_id:f.member.id,p_session_id:sessions.sessionId,p_aal:'aal1',p_source_hash:source.sourceHash});expect(claim.data.state).toBe('claimed');expect((await f.db.rpc('advance_account_credential',{p_id:id,p_actor_id:f.member.id,p_claim_id:claim.data.claimId,p_aal:'aal1',p_verified:true,p_cleanup:'confirmed'})).data.state).toBe('execute');await work(page).getByRole('button',{name:'Reload password controls'}).click();await work(page).getByRole('button',{name:'Cancel uncommitted password change'}).click();await expect(work(page).getByRole('status')).toContainText('cannot be committed');const c=auth(),signed=await c.auth.signInWithPassword({email:f.member.email,password});expect(signed.error).toBeNull();try{const late=await c.auth.updateUser({password:nextPassword,data:{p11_credential_request:claim.data.claimId}});expect(late.error).not.toBeNull()}finally{if(signed.data.session)await c.auth.admin.signOut(signed.data.session.access_token,'local')}expect(await accepts(f.member,password)).toBe(true);expect(await accepts(f.member,nextPassword)).toBe(false);expect((await f.db.from('account_credential_requests').select('state').eq('id',id).single()).data?.state).toBe('cancelled')
})
test('failed native confirmation rolls back the real password change and exposes safe recovery',async({page,fixture:f})=>{
 await login(page,f.member);const fn='credential_fixture_'+f.member.id.replaceAll('-','');sql(`CREATE FUNCTION public.${fn}()RETURNS trigger LANGUAGE plpgsql SET search_path=''AS $$BEGIN IF NEW.actor_id='${f.member.id}'AND NEW.kind='confirmed'THEN RAISE EXCEPTION 'Synthetic credential evidence failure';END IF;RETURN NEW;END$$;CREATE TRIGGER ${fn} BEFORE INSERT ON public.account_credential_events FOR EACH ROW EXECUTE FUNCTION public.${fn}();`)
 try{await fill(page);await work(page).getByRole('button',{name:'Update Password',exact:true}).click();await expect(work(page).getByRole('status')).toContainText('password change is unconfirmed');expect(await accepts(f.member,password)).toBe(true);expect(await accepts(f.member,nextPassword)).toBe(false)}finally{sql(`DROP TRIGGER ${fn} ON public.account_credential_events;DROP FUNCTION public.${fn}();`)}await work(page).getByRole('button',{name:'Cancel uncommitted password change'}).click();await expect(work(page).getByRole('status')).toContainText('request is cancelled');await fill(page);await work(page).getByRole('button',{name:'Update Password',exact:true}).click();await expect(work(page).getByRole('status')).toContainText('Your password change is confirmed.')
})
test('credential history remains private without an organization and fully pages interrupted requests',async({page,browser,fixture:f})=>{
 await login(page,f.unassigned);for(let i=0;i<23;i++)expect((await decision(page,{operation:'cancel',requestId:randomUUID()})).status()).toBe(200);const w=work(page);await w.getByRole('button',{name:'Password request history'}).click();await expect(w).toContainText('Showing 20 of 23 password events');await w.getByRole('button',{name:'Load more password events'}).click();await expect(w).toContainText('Showing 23 of 23 password events');const id=(await f.db.from('account_credential_requests').select('id').eq('actor_id',f.unassigned.id).limit(1)).data![0].id,context=await browser.newContext({baseURL}),other=await context.newPage();try{await login(other,f.admin);expect((await other.request.get('/api/account/credentials?kind=detail&requestId='+id)).status()).toBe(404);expect((await decision(other,{operation:'check',requestId:id})).status()).toBe(404);expect((await decision(page,{operation:'check',requestId:id,actorId:f.admin.id})).status()).toBe(400);expect((await page.request.post('/api/account/credentials',{headers:{origin:'https://outside.invalid'},data:{operation:'check',requestId:id}})).status()).toBe(403)}finally{await context.close()}await page.route('**/api/account/credentials?*',route=>route.fulfill({status:503,json:{error:'Synthetic password history unavailable'}}));await w.getByRole('button',{name:'Reload password controls'}).click();await expect(w.getByRole('alert')).toContainText('unavailable');await expect(w.getByLabel('Current password')).toHaveCount(0)
})
