import {test as base,expect,type Page} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {execFileSync} from 'node:child_process'
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,baseURL=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430',origin=new URL(baseURL).origin,password='local-recovery-fixture-password',nextPassword='new-local-recovery-fixture-password'
const service=()=>createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}}),auth=()=>createClient(url,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
function sql(input:string){return execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input,stdio:['pipe','pipe','pipe']})}
type Fixture={id:string;email:string;db:ReturnType<typeof service>;mailIds:string[]}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['127.0.0.1','localhost'].includes(new URL(url).hostname)||!['127.0.0.1','localhost'].includes(new URL(baseURL).hostname))throw new Error('Disposable local recovery fixtures required')
 const db=service(),email='recovery-browser-'+randomUUID()+'@p11.test',r=await db.auth.admin.createUser({email,password,email_confirm:true});expect(r.error).toBeNull();const id=r.data.user!.id,mailIds:string[]=[]
 try{await provide({id,email,db,mailIds})}finally{expect((await db.auth.admin.deleteUser(id)).error).toBeNull();const found=await(await fetch('http://127.0.0.1:54324/api/v1/search?query='+encodeURIComponent('to:'+email))).json();const ids=found.messages.filter((m:{To:{Address:string}[]})=>m.To.some(t=>t.Address===email)).map((m:{ID:string})=>m.ID);if(ids.length)expect((await fetch('http://127.0.0.1:54324/api/v1/messages',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({IDs:ids})})).ok).toBe(true)}
}})
test.setTimeout(120000)
const work=(p:Page)=>p.getByRole('region',{name:'Recorded password changes'})
async function requestLink(p:Page,f:Fixture){await p.goto('/auth/forgot-password');await p.getByLabel('Email address').fill(f.email);await p.getByRole('button',{name:/Send reset link/i}).click();await expect(p.getByText('Check your email',{exact:true})).toBeVisible();let id='';await expect.poll(async()=>{const s=await(await fetch('http://127.0.0.1:54324/api/v1/search?query='+encodeURIComponent('to:'+f.email))).json();id=s.messages?.find((m:{To:{Address:string}[]})=>m.To.some(t=>t.Address===f.email))?.ID;return !!id}).toBe(true);f.mailIds.push(id);const m=await(await fetch('http://127.0.0.1:54324/api/v1/message/'+id)).json(),link=m.HTML.match(/href="([^"]+)"/)[1].replaceAll('&amp;','&');expect(new URL(link).hostname).toBe('127.0.0.1');return link}
async function openLink(p:Page,link:string){const r=await fetch(link,{redirect:'manual'}),callback=new URL(r.headers.get('location')!);expect(callback.pathname).toBe('/auth/reset-password');expect(['localhost','127.0.0.1']).toContain(callback.hostname);expect(callback.searchParams.has('code')).toBe(true);/* The local Auth config uses port 3000; transport the exact callback to this isolated preview port. */await p.goto('/auth/reset-password'+callback.search);await expect(work(p)).toBeVisible();await expect(p).toHaveURL(origin+'/auth/reset-password');return callback.search}
async function reset(p:Page){await work(p).getByLabel('New password',{exact:true}).fill(nextPassword);await work(p).getByLabel('Confirm new password').fill(nextPassword);await work(p).getByRole('button',{name:'Update Password',exact:true}).click()}
async function accepts(f:Fixture,p:string){const c=auth(),r=await c.auth.signInWithPassword({email:f.email,password:p});if(r.data.session)await c.auth.admin.signOut(r.data.session.access_token,'local');return !r.error}
async function login(p:Page,f:Fixture){await p.goto('/auth/login?redirect=%2Faccount%2Fsecurity');await p.getByLabel('Email address').fill(f.email);await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await expect(p).toHaveURL(/account\/security/,{timeout:30000})}
test('real recovery email opens a no-organization account and confirms one password reset',async({page,fixture:f},info)=>{await openLink(page,await requestLink(page,f));await expect(work(page).getByLabel('Current password')).toHaveCount(0);await reset(page);await expect(work(page).getByRole('status').filter({hasText:'Your password change is confirmed.'})).toBeVisible();expect(await accepts(f,password)).toBe(false);expect(await accepts(f,nextPassword)).toBe(true);await expect(work(page).getByLabel('New password',{exact:true})).toHaveCount(0);const source=await(await page.request.get('/api/account/credentials')).json(),r=await page.request.post('/api/account/credentials',{headers:{origin},data:{operation:'reset',requestId:randomUUID(),sourceHash:source.sourceHash,newPassword:password,confirmed:true}});expect(r.status()).toBe(409);expect((await r.json()).error).toContain('already been used');expect((await f.db.from('account_credential_requests').select('state,purpose').eq('actor_id',f.id)).data).toEqual([{state:'confirmed',purpose:'recovery'}]);await work(page).getByRole('button',{name:'Password request history'}).click();await expect(work(page)).toContainText('recovery verified');await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('recovery-mobile.png'),fullPage:true})})
test('ordinary password sign-in cannot use recovery reset or supplied recovery metadata',async({page,fixture:f})=>{await login(page,f);await page.goto('/auth/reset-password');await expect(work(page)).toContainText('A fresh recovery link is required');const source=await(await page.request.get('/api/account/credentials')).json();const r=await page.request.post('/api/account/credentials',{headers:{origin},data:{operation:'reset',requestId:randomUUID(),sourceHash:source.sourceHash,newPassword:nextPassword,confirmed:true}});expect(r.status()).toBe(409);expect(await accepts(f,password)).toBe(true);expect((await f.db.from('account_credential_requests').select('id',{count:'exact',head:true}).eq('actor_id',f.id)).count).toBe(0)})
test('a lost reset response recovers native confirmation without resubmitting a password',async({page,fixture:f})=>{await openLink(page,await requestLink(page,f));let lost=false;await page.route('**/api/account/credentials',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await reset(page);await expect(work(page)).toContainText('A password request needs review.');const stored=await page.evaluate(id=>JSON.parse(sessionStorage.getItem('p11.account-credentials.pending.v1:'+id)!),f.id);expect(Object.keys(stored)).toEqual(['id']);await page.reload();await work(page).getByRole('button',{name:'Check saved password request'}).click();await expect(work(page).getByRole('status').filter({hasText:'Your password change is confirmed.'})).toBeVisible();expect(await accepts(f,nextPassword)).toBe(true);expect((await f.db.from('account_credential_requests').select('id',{count:'exact',head:true}).eq('actor_id',f.id)).count).toBe(1)})
test('cancelled unused reset blocks a delayed submission and allows a fresh reviewed request',async({page,fixture:f})=>{await openLink(page,await requestLink(page,f));let intercepted:unknown=null;await page.route('**/api/account/credentials',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='reset'&&!intercepted){intercepted=route.request().postDataJSON();await route.abort('failed')}else await route.continue()});await reset(page);await expect(work(page)).toContainText('A password request needs review.');await work(page).getByRole('button',{name:'Cancel uncommitted password change'}).click();await expect(work(page).getByRole('status')).toContainText('request is cancelled');const late=await page.request.post('/api/account/credentials',{headers:{origin},data:intercepted});expect((await late.json()).status).toBe('cancelled');expect(await accepts(f,password)).toBe(true);await reset(page);await expect(work(page).getByRole('status').filter({hasText:'Your password change is confirmed.'})).toBeVisible()})
test('expired recovery authority is rejected while saved account history remains available',async({page,fixture:f})=>{await openLink(page,await requestLink(page,f));sql(`UPDATE auth.mfa_amr_claims SET created_at=statement_timestamp()-interval '16 minutes' WHERE session_id IN(SELECT id FROM auth.sessions WHERE user_id='${f.id}') AND authentication_method='recovery';`);await reset(page);await expect(work(page).getByRole('alert')).toContainText('fresh recovery link');expect(await accepts(f,password)).toBe(true);await work(page).getByRole('button',{name:'Reload password controls'}).click();await expect(work(page).getByLabel('New password',{exact:true})).toHaveCount(0)})
test('ordinary password login has no authenticator controls and local authenticator enrollment is disabled',async({page,fixture:f})=>{await login(page,f);await expect(page.getByRole('main')).not.toContainText('Authenticator');await expect(page.getByRole('region',{name:'Recorded password changes'})).toBeVisible();const c=auth(),signed=await c.auth.signInWithPassword({email:f.email,password});expect(signed.error).toBeNull();try{const enrolled=await c.auth.mfa.enroll({factorType:'totp'});expect(enrolled.error).not.toBeNull()}finally{await c.auth.signOut({scope:'local'})}})
test('another browser cannot exchange a recovery link without its original verifier',async({page,browser,fixture:f})=>{const link=await requestLink(page,f),r=await fetch(link,{redirect:'manual'}),callback=new URL(r.headers.get('location')!),context=await browser.newContext({baseURL}),other=await context.newPage();try{await other.goto('/auth/reset-password'+callback.search);await expect(other.getByRole('main').getByRole('alert')).toContainText('another browser');await expect(other.getByLabel('New password',{exact:true})).toHaveCount(0)}finally{await context.close()}expect(await accepts(f,password)).toBe(true)})

