import {test as base,expect,type Page} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {execFileSync} from 'node:child_process'
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,baseURL=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430',origin=new URL(baseURL).origin,password='local-session-fixture-password',headers={origin}
const client=()=>createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type User={id:string;email:string}
type Fixture={db:ReturnType<typeof client>;org:string;member:User;admin:User;unassigned:User}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['127.0.0.1','localhost'].includes(new URL(url).hostname)||!['127.0.0.1','localhost'].includes(new URL(baseURL).hostname))throw new Error('Disposable local session fixtures required')
 const db=client(),org=randomUUID(),users:User[]=[];expect((await db.from('organizations').insert({id:org,name:'Account session browser fixture'})).error).toBeNull()
 try{for(const[role,organization]of[['viewer',org],['admin',org],['viewer',null]]as const){const email='session-browser-'+randomUUID()+'@p11.test',r=await db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:'Session fixture account'}});expect(r.error).toBeNull();const id=r.data.user!.id;users.push({id,email});expect((await db.from('profiles').upsert({id,role,org_id:organization})).error).toBeNull()}await provide({db,org,member:users[0],admin:users[1],unassigned:users[2]})}
 finally{execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id=NULL,role='viewer'WHERE org_id='${org}';DELETE FROM public.organizations WHERE id='${org}';COMMIT;`,stdio:['pipe','pipe','pipe']});for(const u of users)expect((await db.auth.admin.deleteUser(u.id)).error).toBeNull();expect((await db.from('account_session_requests').select('*',{count:'exact',head:true}).in('actor_id',users.map(u=>u.id))).count).toBe(0)}
}})
test.setTimeout(180000)
async function login(page:Page,u:User,redirect='/account/security',reauth=false){await page.goto('/auth/login?redirect='+encodeURIComponent(redirect)+(reauth?'&reauth=1':''));await page.getByLabel('Email address').fill(u.email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})}
const work=(page:Page)=>page.getByRole('region',{name:'Private account sessions'})
async function read(page:Page){const r=await page.request.get('/api/account/sessions');expect(r.status()).toBe(200);expect(r.headers()['cache-control']).toContain('no-store');return r.json()}
async function decision(page:Page,data:Record<string,unknown>){return page.request.post('/api/account/sessions',{headers,data})}

test('reviewed other-session sign-out recovers a lost response and revokes the actual other session',async({page,browser,fixture:f},info)=>{
 await login(page,f.member);const context=await browser.newContext({baseURL}),other=await context.newPage();try{await login(other,f.member);const w=work(page);await w.getByRole('button',{name:'Reload sessions'}).click();await expect(w).toContainText('2 recorded sessions');let lost=false;await page.route('**/api/account/sessions',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await w.getByRole('button',{name:'Review other-session sign-out'}).click();await expect(w).toContainText('including any opened just afterward');await w.getByRole('button',{name:'Confirm other-session sign-out'}).click();await expect(w).toContainText('A session request is unconfirmed.');const pending=await page.evaluate(actor=>JSON.parse(sessionStorage.getItem('p11.account-sessions.pending.v1:'+actor)!),f.member.id);expect(Object.keys(pending)).toEqual(['id','scope','sourceHash']);await page.reload();await w.getByRole('button',{name:'Check saved session request'}).click();await expect(w.getByRole('status')).toContainText('provider confirmed other sessions');await expect(w).toContainText('1 recorded session');expect((await other.request.get('/api/account/sessions')).status()).toBe(401);await w.getByRole('button',{name:'Session request history'}).click();await expect(w).toContainText('Showing 1 of 1 session requests');await w.getByRole('button',{name:/Other sessions · acknowledged/}).click();await expect(w.getByLabel('Saved session request details')).toContainText('acknowledged');expect((await f.db.from('account_session_requests').select('state').eq('id',pending.id).single()).data?.state).toBe('acknowledged');await page.setViewportSize({width:390,height:844});await w.screenshot({path:info.outputPath('sessions-mobile.png')})}finally{await context.close()}
})
test('unused cancellation holds a late request and stale review cannot revoke a new session',async({page,browser,fixture:f})=>{
 await login(page,f.member);const w=work(page);let intercepted:Record<string,unknown>|null=null;await page.route('**/api/account/sessions',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='revoke'&&!intercepted){intercepted=route.request().postDataJSON();await route.abort('failed')}else await route.continue()});await w.getByRole('button',{name:'Review this-session sign-out'}).click();await w.getByRole('button',{name:'Confirm this-session sign-out'}).click();await expect(w).toContainText('A session request is unconfirmed.');await w.getByRole('button',{name:'Cancel only if not started'}).click();await expect(w.getByRole('status')).toContainText('No sign-out was started');const delayed=await decision(page,intercepted!);expect(delayed.status()).toBe(200);expect((await delayed.json()).status).toBe('cancelled');const current=await read(page),context=await browser.newContext({baseURL}),other=await context.newPage();try{await login(other,f.member);const stale=await decision(page,{operation:'revoke',requestId:randomUUID(),scope:'others',sourceHash:current.sourceHash,confirmed:true});expect(stale.status()).toBe(409);expect((await stale.json()).error).toContain('list changed');expect((await read(other)).sessions).toHaveLength(2)}finally{await context.close()}
})
test('private history survives membership removal and is hidden from an organization administrator',async({page,browser,fixture:f})=>{
 await login(page,f.member);const id=randomUUID();expect((await decision(page,{operation:'cancel_unused',requestId:id})).status()).toBe(200);const context=await browser.newContext({baseURL}),other=await context.newPage();try{await login(other,f.admin);expect((await other.request.get('/api/account/sessions?kind=detail&requestId='+id)).status()).toBe(404);expect((await decision(other,{operation:'check',requestId:id})).status()).toBe(404);expect((await decision(page,{operation:'check',requestId:id,actorId:f.admin.id})).status()).toBe(400);expect((await page.request.post('/api/account/sessions',{headers:{origin:'https://outside.invalid'},data:{operation:'check',requestId:id}})).status()).toBe(403);expect((await f.db.from('profiles').update({org_id:null}).eq('id',f.member.id)).error).toBeNull();await page.reload();await expect(page).toHaveURL(/account\/security/);await work(page).getByRole('button',{name:'Session request history'}).click();await expect(work(page)).toContainText('Showing 1 of 1 session requests');expect((await page.request.get('/api/account/sessions?kind=detail&requestId='+id)).status()).toBe(200)}finally{await context.close()}
})
test('lost current-session sign-out recovers after a fresh sign-in without removing other sessions',async({page,browser,fixture:f})=>{
 await login(page,f.member);const context=await browser.newContext({baseURL}),other=await context.newPage();try{await login(other,f.member);await work(page).getByRole('button',{name:'Reload sessions'}).click();await expect(work(page)).toContainText('2 recorded sessions');let lost=false;await page.route('**/api/account/sessions',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await work(page).getByRole('button',{name:'Review this-session sign-out'}).click();await work(page).getByRole('button',{name:'Confirm this-session sign-out'}).click();await expect(work(page)).toContainText('A session request is unconfirmed.');expect((await read(other)).sessions).toHaveLength(1);await login(page,f.member,'/account/security',true);await work(page).getByRole('button',{name:'Check saved session request'}).click();await expect(work(page).getByRole('status')).toContainText('provider confirmed this session');expect((await read(other)).sessions).toHaveLength(2);await work(page).getByRole('button',{name:'Session request history'}).click();await expect(work(page)).toContainText('Showing 1 of 1 session requests')}finally{await context.close()}
})
test('session history pages completely and an interrupted native provider claim stays truthful',async({page,fixture:f})=>{
 await login(page,f.unassigned);const current=await read(page),id=randomUUID(),r=await f.db.rpc('claim_account_session',{p_id:id,p_actor_id:f.unassigned.id,p_session_id:current.sessionId,p_aal:'aal1',p_input:{scope:'local',sourceHash:current.sourceHash,confirmed:true}});expect(r.error).toBeNull();expect(r.data.state).toBe('claimed');for(let i=0;i<23;i++)expect((await decision(page,{operation:'cancel_unused',requestId:randomUUID()})).status()).toBe(200);const w=work(page);await w.getByRole('button',{name:'Session request history'}).click();await expect(w).toContainText('Showing 20 of 24 session requests');await w.getByRole('button',{name:'Load more session requests'}).click();await expect(w).toContainText('Showing 24 of 24 session requests');await w.getByRole('button',{name:/This session · claimed/}).click();await expect(w.getByRole('status')).toContainText('provider result is unconfirmed');await w.getByRole('button',{name:'Check current session evidence'}).click();await expect(w.getByRole('status')).toContainText('never sends another sign-out');expect((await read(page)).sessions).toHaveLength(1);expect((await f.db.from('account_session_requests').select('provider_result,state').eq('id',id).single()).data).toMatchObject({provider_result:null,state:'claimed'});await page.route('**/api/account/sessions?*',route=>route.fulfill({status:503,json:{error:'Synthetic session read unavailable'}}));await w.getByRole('button',{name:'Reload sessions'}).click();await expect(w.getByRole('alert')).toContainText('unavailable');await expect(w.getByRole('button',{name:'Review this-session sign-out'})).toHaveCount(0)
})
test('normal account menu sign-out records only the current session and the profile link works',async({page,browser,fixture:f})=>{
 await login(page,f.member,'/dashboard/profile');await page.getByRole('button',{name:'Security',exact:true}).click();await page.getByRole('link',{name:'View Sessions',exact:true}).click();await expect(work(page)).toContainText('1 recorded session');const context=await browser.newContext({baseURL}),other=await context.newPage();try{await login(other,f.member);await page.goto('/dashboard/profile');await page.getByRole('button',{name:'SF Session fixture account',exact:true}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page).toHaveURL(/auth\/login/);expect((await read(other)).sessions).toHaveLength(1);const requests=await f.db.from('account_session_requests').select('scope,state').eq('actor_id',f.member.id);expect(requests.data).toEqual([{scope:'local',state:'acknowledged'}])}finally{await context.close()}
})
