import {expect,test as base,type Page,type Locator} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {execFileSync} from 'node:child_process'
const org='22222222-2222-2222-2222-222222222222',dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||'',client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={db:ReturnType<typeof client>;property:string;other:string;document:string}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),other=randomUUID(),document=randomUUID()
 try{
  expect((await db.from('properties').insert([{id:property,org_id:org,name:'Assistant facts browser fixture',address:{city:'Retained fixture city'}},{id:other,org_id:org,name:'Other assistant facts browser fixture'}])).error).toBeNull()
  expect((await db.from('documents').insert(Array.from({length:26},(_,i)=>({id:i===0?document:randomUUID(),property_id:property,content:i===0?'Ordinary source policy: the courtyard welcomes quiet reading.\r\nFull Unicode 🏡 retained.':`Complete plain source ${i}`,metadata:{source:'pasted_text',title:`Original source ${i}`}})))).error).toBeNull()
  expect((await db.from('property_chatbot_contexts').insert({property_id:property,status:'current',requires_review:false,context_markdown:'Earlier context without a recorded publication.',last_generated_at:new Date().toISOString()})).error).toBeNull()
  await provide({db,property,other,document})
 }finally{for(const id of[property,other]){execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;CREATE TEMP TABLE fixture_contexts AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${id}';CREATE TEMP TABLE fixture_jobs AS SELECT id FROM public.shared_jobs WHERE property_id='${id}';SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${id}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${id}';SET LOCAL session_replication_role=origin;DELETE FROM public.properties WHERE id='${id}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']});for(const table of['documents','knowledge_sources','assistant_fact_workspaces','assistant_fact_versions','assistant_fact_decisions','knowledge_materials','knowledge_embedding_requests','shared_action_events','shared_jobs'])expect((await db.from(table).select('*',{count:'exact',head:true}).eq('property_id',id)).count).toBe(0)}}
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})
async function open(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/community');await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();const w=page.getByRole('region',{name:'Reviewed assistant facts'});await expect(w).toContainText('Complete current source set');return w}
async function reason(w:Locator,text:string){await w.getByLabel('Reason for this facts decision',{exact:true}).fill(text)}
async function prepare(w:Locator){await reason(w,'Review complete current source facts');await w.getByRole('button',{name:'Prepare complete facts draft'}).click();await expect(w.getByLabel('Exact retained facts')).toBeVisible()}
async function publish(w:Locator){await reason(w,'Approve these exact facts for Luma');await w.getByRole('checkbox').check();await w.getByRole('button',{name:'Publish reviewed facts',exact:true}).click();await expect(w.getByRole('button',{name:'Reconfirm published facts',exact:true})).toBeVisible();await expect(w).toContainText('Reviewed facts available to Luma')}
async function serving(f:Fixture){const result=await f.db.rpc('read_serving_assistant_facts',{p_property_id:f.property});expect(result.error).toBeNull();return result.data}
test('complete ordinary source facts reach Luma only after exact review, with retained correction withdrawal and republication',async({page,fixture},info)=>{
 const w=await open(page,fixture);await expect(w).toContainText('26 stored text chunks');await prepare(w);await expect(w.getByLabel('Exact retained facts')).toContainText('courtyard welcomes quiet reading');await expect(w.getByLabel('Exact retained facts')).toContainText('Complete plain source 25');expect((await serving(fixture)).state).toBe('legacy');await publish(w);expect((await serving(fixture)).contextMarkdown).toContain('Full Unicode 🏡 retained.');await w.getByRole('button',{name:'Correct facts draft'}).click();await w.getByLabel('Corrected facts text',{exact:true}).fill('Reviewed courtyard policy: quiet reading is welcome.');await reason(w,'Correct exact wording after source review');await w.getByRole('button',{name:'Save facts correction'}).click();await expect(w.getByLabel('Exact retained facts')).toHaveText('Reviewed courtyard policy: quiet reading is welcome.');expect((await serving(fixture)).contextMarkdown).toContain('Full Unicode 🏡 retained.');await publish(w);expect((await serving(fixture)).contextMarkdown).toBe('Reviewed courtyard policy: quiet reading is welcome.');await reason(w,'Withdraw exact assistant facts publication');await w.getByRole('checkbox').check();await w.getByRole('button',{name:'Withdraw published facts'}).click();await expect(w).toContainText('Published facts were withdrawn.');expect(await serving(fixture)).toMatchObject({state:'withheld',reason:'withdrawn'});await publish(w);await w.getByRole('button',{name:'Facts version history'}).click();await expect(w).toContainText('Showing 2 of 2.');await w.getByRole('button',{name:'Read retained facts version'}).last().click();await expect(w.getByLabel('Exact retained facts')).toContainText('Full Unicode 🏡 retained.');await expect(page).toHaveURL(/assistantFactVersion=/);await page.reload();await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await expect(w.getByLabel('Exact retained facts')).toContainText('Full Unicode 🏡 retained.');expect((await fixture.db.from('shared_jobs').select('*',{count:'exact',head:true}).eq('property_id',fixture.property)).count).toBe(0);await page.setViewportSize({width:390,height:844});await w.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('assistant-facts-mobile.png')})
})
test('content-only source changes withhold adopted facts until a new complete reviewed publication',async({page,fixture})=>{
 const w=await open(page,fixture);await prepare(w);await publish(w);expect((await fixture.db.from('documents').update({content:'Changed courtyard policy: reservations are required.'}).eq('id',fixture.document)).error).toBeNull();expect((await serving(fixture)).reason).toBe('sources_changed');await w.getByRole('button',{name:'Reload current facts'}).click();await expect(w).toContainText('Property knowledge changed after the last review.');await expect(w.getByRole('button',{name:'Reconfirm published facts'})).toBeDisabled();await prepare(w);await expect(w.getByLabel('Exact retained facts')).toContainText('reservations are required');await publish(w);expect((await serving(fixture)).contextMarkdown).toContain('reservations are required');const events=await fixture.db.from('shared_action_events').select('action,training_eligible,request,result').eq('property_id',fixture.property);expect(events.data?.every(row=>!row.training_eligible)).toBe(true);expect(JSON.stringify(events.data)).not.toContain('reservations are required')
})
test('lost draft reply recovers one decision, and read failures or property switches cannot show stale private facts',async({page,fixture})=>{
 const w=await open(page,fixture);let lost=false;await page.route('**/api/assistant-facts',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='prepare'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await reason(w,'Retain complete exact source facts');await w.getByRole('button',{name:'Prepare complete facts draft'}).click();await expect(w).toContainText('A previous prepare facts decision is unconfirmed.');await page.reload();await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await w.getByRole('button',{name:'Check saved facts decision'}).click();await expect(w.getByLabel('Exact retained facts')).toContainText('courtyard welcomes quiet reading');expect((await fixture.db.from('assistant_fact_versions').select('*',{count:'exact',head:true}).eq('property_id',fixture.property)).count).toBe(1);await page.route('**/api/assistant-facts?*',r=>r.fulfill({status:503,json:{error:'Fixture facts read unavailable'}}));await w.getByRole('button',{name:'Reload current facts'}).click();await expect(w.getByRole('alert')).toContainText('Fixture facts read unavailable');await expect(w.getByLabel('Exact retained facts')).toHaveCount(0);await page.unroute('**/api/assistant-facts?*');await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.other);await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await expect(w).toContainText('0 stored text chunks');await expect(w.getByLabel('Exact retained facts')).toHaveCount(0);await w.getByRole('button',{name:'Reload current facts'}).click();await expect(w).toContainText('0 stored text chunks');await expect(w.getByLabel('Exact retained facts')).toHaveCount(0)
})
test('large complete drafts require an explicit shorter correction and do not truncate retained evidence',async({page,fixture})=>{
 expect((await fixture.db.from('documents').insert({property_id:fixture.property,content:'LARGE SOURCE BEGIN '+('original long evidence '.repeat(4000))+' COMPLETE SOURCE END',metadata:{title:'Complete large source'}})).error).toBeNull();const w=await open(page,fixture);await prepare(w);await expect(w).toContainText('This complete draft is too large to publish.');await expect(w.getByLabel('Exact retained facts')).toContainText('COMPLETE SOURCE END');await expect(w.getByRole('button',{name:'Publish reviewed facts',exact:true})).toBeDisabled();expect((await serving(fixture)).state).toBe('legacy');await w.getByRole('button',{name:'Correct facts draft'}).click();await w.getByLabel('Corrected facts text',{exact:true}).fill('Reviewed concise property facts based on the retained original evidence.');await reason(w,'Deliberate concise facts after full source review');await w.getByRole('button',{name:'Save facts correction'}).click();await publish(w);const version=await fixture.db.from('assistant_fact_versions').select('source_snapshot').eq('property_id',fixture.property).eq('origin','edited').single();expect(JSON.stringify(version.data?.source_snapshot)).toContain('COMPLETE SOURCE END')
})


test('older approved context displays a review reminder without withdrawing its facts',async({page,fixture},info)=>{
 expect((await fixture.db.from('property_chatbot_contexts').update({last_generated_at:'2026-07-23T23:30:03Z'}).eq('property_id',fixture.property)).error).toBeNull()
 const w=await open(page,fixture)
 await expect(w.getByText('Routine facts review recommended.',{exact:false})).toBeVisible()
 expect(await serving(fixture)).toMatchObject({state:'legacy',freshnessReviewDue:true})
 const stored=await fixture.db.from('property_chatbot_contexts').select('status,requires_review,context_markdown').eq('property_id',fixture.property).single()
 expect(stored.data).toMatchObject({status:'current',requires_review:false,context_markdown:'Earlier context without a recorded publication.'})
 await page.screenshot({path:info.outputPath('approved-facts-review-reminder.png'),fullPage:true})
})
