// Fixture reporting dates follow the browser calendar, including the UTC/local midnight boundary.
import { test as base, expect, type Page } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
const baseURL = process.env.PLAYWRIGHT_BASE_URL || 'http://127.0.0.1:9430', origin = new URL(baseURL).origin, url = process.env.NEXT_PUBLIC_SUPABASE_URL!, password = 'local-bi-goal-fixture-password';
const service = () => createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } });
function sql(input: string) { return execFileSync('docker', ['exec', '-i', 'supabase_db_p11-platform', 'psql', '-U', 'postgres', '-d', 'postgres', '-X', '-v', 'ON_ERROR_STOP=1'], { input, stdio: ['pipe', 'pipe', 'pipe'] }); }
type Fixture = {
    id: string;
    email: string;
    org: string;
    property: string;
    db: ReturnType<typeof service>;
    today: string;
};
const test = base.extend<{
    fixture: Fixture;
}>({ fixture: async ({page}, provide) => {
        if (!['127.0.0.1', 'localhost'].includes(new URL(url).hostname) || !['127.0.0.1', 'localhost'].includes(new URL(baseURL).hostname))
            throw new Error('Local disposable fixtures only');
        const db = service(), email = 'bi-csv-browser-' + randomUUID() + '@p11.test', created = await db.auth.admin.createUser({ email, password, email_confirm: true });
        expect(created.error).toBeNull();
        const id = created.data.user!.id, org = randomUUID(), property = randomUUID(), today = await page.evaluate(() => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; });
        try {
            sql(`BEGIN;INSERT INTO public.organizations(id,name)VALUES('${org}','BI CSV browser fixture');SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id='${org}',role='admin' WHERE id='${id}';INSERT INTO public.properties(id,org_id,name)VALUES('${property}','${org}','BI CSV fixture property');COMMIT;`);
            await provide({ id, email, org, property, db, today });
        }
        finally {
            sql(`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${property}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${property}';SET LOCAL session_replication_role=origin;DELETE FROM public.fact_marketing_performance WHERE property_id='${property}';DELETE FROM public.properties WHERE id='${property}';SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id=NULL,role='viewer' WHERE org_id='${org}';DELETE FROM public.organizations WHERE id='${org}';COMMIT;`);
            expect((await db.auth.admin.deleteUser(id)).error).toBeNull();
        }
    } });
test.setTimeout(120000);

const panel=(p:Page)=>p.getByRole('dialog',{name:'CSV imports',exact:true}),detail=(p:Page)=>panel(p).getByRole('region',{name:'Saved CSV detail',exact:true});
async function open(p:Page){await p.getByRole('button',{name:'Import Data',exact:true}).click();await p.getByRole('button',{name:/Upload CSV/}).click();await expect(panel(p).getByRole('button',{name:'Refresh import history',exact:true})).toBeEnabled()}
async function login(p:Page,f:Fixture){await p.goto('/auth/login?redirect=%2Fdashboard%2Fbi');await p.getByLabel('Email address').fill(f.email);await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await expect(p).toHaveURL(/dashboard\/bi/,{timeout:30000});await open(p)}
const csv=(date:string,n=1,spend=12.5)=>'Date,Campaign ID,Campaign,Impressions,Clicks,Cost,Conversions\n'+Array.from({length:n},(_,i)=>`${date},campaign-${i},CSV campaign ${i},100,10,${spend},0.000125`).join('\n');
async function choose(p:Page,f:Fixture,n=1){await panel(p).getByLabel('Source account ID',{exact:true}).fill('123-456-7890');await panel(p).getByLabel('Campaign label',{exact:true}).fill('Reviewed CSV campaign');await panel(p).getByRole('checkbox',{name:/US dollars/}).check();await panel(p).getByLabel('CSV files',{exact:true}).setInputFiles({name:'reviewed-daily.csv',mimeType:'text/csv',buffer:Buffer.from(csv(f.today,n))})}
async function prepare(p:Page,f:Fixture,n=1){await choose(p,f,n);await panel(p).getByRole('button',{name:'Save CSV previews',exact:true}).click();await expect(detail(p).getByRole('heading',{name:'reviewed-daily.csv · preview',exact:true})).toBeVisible()}
async function apply(p:Page){await detail(p).getByLabel('Import decision reason',{exact:true}).fill('Confirmed actual reporting account, campaign identity and every selected row.');await detail(p).getByRole('button',{name:'Import reviewed rows',exact:true}).click();await expect(detail(p).getByRole('heading',{name:'reviewed-daily.csv · applied',exact:true})).toBeVisible()}
async function records(f:Fixture){const r=await f.db.from('fact_marketing_performance').select('*').eq('property_id',f.property);expect(r.error).toBeNull();return r.data!}
async function imports(f:Fixture){const r=await f.db.from('bi_csv_imports').select('*').eq('property_id',f.property).order('created_at');expect(r.error).toBeNull();return r.data!}
async function post(p:Page,f:Fixture,input:Record<string,unknown>){return p.request.post('/api/analytics/csv-imports',{headers:{origin},data:{id:randomUUID(),propertyId:f.property,expectedActorId:f.id,...input}})}
test('exact retained CSV, complete preview paging, explicit import and mobile evidence',async({page,fixture:f},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page,f);await prepare(page,f,31);expect(await records(f)).toHaveLength(0);await expect(detail(page)).toContainText('Account 1234567890');await detail(page).getByRole('button',{name:'Next import rows',exact:true}).click();await expect(detail(page)).toContainText('26–31');await expect(detail(page).getByText('CSV campaign 30',{exact:true})).toBeVisible();await detail(page).getByText('Exact original CSV',{exact:true}).click();await expect(detail(page).locator('pre')).toContainText('0.000125');await detail(page).getByText('Exact original CSV',{exact:true}).click();await page.screenshot({path:info.outputPath('csv-preview-desktop.png')});await page.setViewportSize({width:390,height:844});await detail(page).getByRole('heading').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('csv-preview-mobile.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await apply(page);expect(await records(f)).toHaveLength(31);expect((await records(f))[0].conversions).toBe(0.000125);expect((await imports(f))[0].original).toMatchObject({csvContent:csv(f.today,31)});const actions=await f.db.from('shared_action_events').select('*').eq('property_id',f.property).like('action','bi.csv.%');expect(actions.data).toHaveLength(2);expect(actions.data!.every(x=>!x.training_eligible)).toBe(true);expect(JSON.stringify(actions.data)).not.toContain('CSV campaign 30');expect(errors).toEqual([])
})
test('missed preparation reply recovers exact saved original after reload',async({page,fixture:f})=>{
 await login(page,f);await choose(page,f);await page.route('**/api/analytics/csv-imports',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='prepare'){await route.fetch();await route.abort()}else await route.continue()});await panel(page).getByRole('button',{name:'Save CSV previews',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Check saved import request',exact:true})).toBeEnabled();const pending=await page.evaluate(({actor,property})=>JSON.parse(sessionStorage.getItem(`p11.csv-import.v1:${actor}:${property}`)!),{actor:f.id,property:f.property});expect(Object.keys(pending).sort()).toEqual(['id','kind']);await page.unroute('**/api/analytics/csv-imports');await page.reload();await open(page);await panel(page).getByRole('button',{name:'Check saved import request',exact:true}).click();await expect(detail(page).getByRole('heading',{name:'reviewed-daily.csv · preview',exact:true})).toBeVisible();expect(await imports(f)).toHaveLength(1);expect(await records(f)).toHaveLength(0)
})
test('missed application reply recovers a single import and upload log',async({page,fixture:f})=>{
 await login(page,f);await prepare(page,f);await page.route('**/api/analytics/csv-imports',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='apply'){await route.fetch();await route.abort()}else await route.continue()});await detail(page).getByLabel('Import decision reason',{exact:true}).fill('Reviewed original and destination');await detail(page).getByRole('button',{name:'Import reviewed rows',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Check saved import request',exact:true})).toBeEnabled();await page.unroute('**/api/analytics/csv-imports');await page.reload();await open(page);await panel(page).getByRole('button',{name:'Check saved import request',exact:true}).click();await expect(detail(page).getByRole('heading',{name:'reviewed-daily.csv · applied',exact:true})).toBeVisible();expect(await records(f)).toHaveLength(1);expect((await f.db.from('marketing_data_uploads').select('id').eq('property_id',f.property)).data).toHaveLength(1)
})
test('unused preparation cancellation fences late replay without importing rows',async({page,fixture:f})=>{
 await login(page,f);await choose(page,f);let input:Record<string,unknown>={};await page.route('**/api/analytics/csv-imports',async route=>{if(route.request().method()==='POST'){input=route.request().postDataJSON();await route.abort()}else await route.continue()});await panel(page).getByRole('button',{name:'Save CSV previews',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Cancel unused import request',exact:true})).toBeEnabled();await page.unroute('**/api/analytics/csv-imports');await panel(page).getByRole('button',{name:'Cancel unused import request',exact:true}).click();await expect(panel(page).getByRole('status')).toContainText('Unused request closed');const late=await page.request.post('/api/analytics/csv-imports',{headers:{origin},data:input});expect(late.status()).toBe(200);expect((await late.json()).status).toBe('cancelled');expect(await records(f)).toHaveLength(0)
})
test('changed destination requires new preview and preserves original ancestry',async({page,fixture:f})=>{
 await login(page,f);await prepare(page,f);const original=(await imports(f))[0];sql(`INSERT INTO fact_marketing_performance(property_id,date,channel_id,source_account_id,currency_code,campaign_id,campaign_name,impressions,clicks,spend,conversions)VALUES('${f.property}','${f.today}','google_ads','1234567890','USD','campaign-0','Concurrent current report',100,10,30,0.5);`);await detail(page).getByLabel('Import decision reason',{exact:true}).fill('Review old target');await detail(page).getByRole('button',{name:'Import reviewed rows',exact:true}).click();await expect(panel(page).getByRole('alert')).toContainText('destination data changed');expect((await records(f))[0].spend).toBe(30);await panel(page).getByRole('button',{name:'Cancel unused import request',exact:true}).click();await expect(panel(page).getByRole('status')).toContainText('Unused request closed');await detail(page).getByRole('button',{name:'Prepare new preview from original',exact:true}).click();await expect.poll(async()=> (await imports(f)).length).toBe(2);await expect(detail(page)).toContainText('1 existing target rows');expect((await imports(f))[1].parent_id).toBe(original.id);await apply(page);expect((await records(f))[0].spend).toBe(12.5)
})
test('complete current and legacy history plus role withdrawal remain readable',async({page,fixture:f})=>{
 await login(page,f);await prepare(page,f);for(let n=0;n<26;n++)expect((await post(page,f,{operation:'cancel_preview'})).status()).toBe(200);sql(`INSERT INTO marketing_data_uploads(property_id,platform,report_type,file_name,rows_imported)SELECT '${f.property}','google_ads','time_series','old-'||n||'.csv',1 FROM generate_series(1,28)n;`);await panel(page).getByRole('button',{name:'Refresh import history',exact:true}).click();await expect(panel(page)).toContainText('27 saved imports');await panel(page).getByRole('button',{name:'Next imports',exact:true}).click();await expect(panel(page)).toContainText('26–27');await panel(page).getByRole('button',{name:'Earlier upload history',exact:true}).click();await expect(panel(page)).toContainText('28 saved imports');await panel(page).getByRole('button',{name:'Next imports',exact:true}).click();await expect(panel(page)).toContainText('26–28');sql(`BEGIN;SELECT set_config('p11.team_scope','${f.org}',true);UPDATE profiles SET role='viewer'WHERE id='${f.id}';COMMIT;`);await detail(page).getByLabel('Import decision reason',{exact:true}).fill('Permission removed before final import');await detail(page).getByRole('button',{name:'Import reviewed rows',exact:true}).click();await expect(panel(page).getByRole('alert')).toContainText('cannot make this import decision');expect(await records(f)).toHaveLength(0)
})
test('multiple files retain separate previews and invalid values never import',async({page,fixture:f})=>{
 await login(page,f);await choose(page,f);await panel(page).getByLabel('CSV files',{exact:true}).setInputFiles([{name:'first.csv',mimeType:'text/csv',buffer:Buffer.from(csv(f.today))},{name:'second.csv',mimeType:'text/csv',buffer:Buffer.from(csv(f.today,1,25))}]);await panel(page).getByRole('button',{name:'Save CSV previews',exact:true}).click();await expect(panel(page)).toContainText('2 saved imports');expect(await imports(f)).toHaveLength(2);expect(await records(f)).toHaveLength(0);const bad=await post(page,f,{operation:'prepare',original:{filename:'bad.csv',csvContent:csv(f.today).replace('12.5','unknown'),platform:'google_ads',sourceAccountId:'1234567890',campaignName:'Bad input',currencyCode:'USD'}});expect(bad.status()).toBe(400);expect(await imports(f)).toHaveLength(2);expect((await page.request.post('/api/analytics/upload',{headers:{origin},data:{}})).status()).toBe(410)
})

test('failed initial history read and invalid file validation remain directly retryable',async({page,fixture:f})=>{
 let blocked=true;await page.route('**/api/analytics/csv-imports?**',async route=>{if(blocked){await route.fulfill({status:503,json:{error:'Temporary history interruption'}})}else await route.continue()});await login(page,f);await expect(panel(page).getByRole('alert')).toContainText('Temporary history interruption');blocked=false;await panel(page).getByRole('button',{name:'Refresh import history',exact:true}).click();await choose(page,f);await panel(page).getByLabel('CSV files',{exact:true}).setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from(csv(f.today).replace('12.5','unknown'))});await panel(page).getByRole('button',{name:'Save CSV previews',exact:true}).click();await expect(panel(page).getByRole('alert')).toContainText('complete numeric value');await expect(panel(page).getByRole('button',{name:'Check saved import request',exact:true})).toHaveCount(0);await expect(panel(page).getByRole('button',{name:'Save CSV previews',exact:true})).toBeEnabled();expect(await imports(f)).toHaveLength(0)
})
