// Fixture reporting dates follow the browser calendar, including the UTC/local midnight boundary.
import { test as base, expect, type Page } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
const baseURL = process.env.PLAYWRIGHT_BASE_URL || 'http://127.0.0.1:9430', origin = new URL(baseURL).origin, url = process.env.NEXT_PUBLIC_SUPABASE_URL!, password = 'local-bi-goal-fixture-password';
const service = () => createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } });
function sql(input: string) { return execFileSync('docker', ['exec', '-i', 'supabase_db_p11-platform', 'psql', '-U', 'postgres', '-d', 'postgres', '-X', '-v', 'ON_ERROR_STOP=1'], { input, stdio: ['pipe', 'pipe', 'pipe'] }); }
type Fixture = {
    id: string;
    email: string;
    org: string;
    property: string;
    db: ReturnType<typeof service>;
    today: string;
};
const test = base.extend<{
    fixture: Fixture;
}>({ fixture: async ({page}, provide) => {
        if (!['127.0.0.1', 'localhost'].includes(new URL(url).hostname) || !['127.0.0.1', 'localhost'].includes(new URL(baseURL).hostname))
            throw new Error('Local disposable fixtures only');
        const db = service(), email = 'bi-data-browser-' + randomUUID() + '@p11.test', created = await db.auth.admin.createUser({ email, password, email_confirm: true });
        expect(created.error).toBeNull();
        const id = created.data.user!.id, org = randomUUID(), property = randomUUID(), today = await page.evaluate(() => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; });
        try {
            sql(`BEGIN;INSERT INTO public.organizations(id,name)VALUES('${org}','BI data browser fixture');SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id='${org}',role='admin' WHERE id='${id}';INSERT INTO public.properties(id,org_id,name)VALUES('${property}','${org}','BI data fixture property');COMMIT;`);
            await provide({ id, email, org, property, db, today });
        }
        finally {
            sql(`BEGIN;SET LOCAL session_replication_role=replica;DELETE FROM public.bi_data_row_state WHERE property_id='${property}';UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${property}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${property}';SET LOCAL session_replication_role=origin;DELETE FROM public.fact_marketing_performance WHERE property_id='${property}';DELETE FROM public.properties WHERE id='${property}';SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id=NULL,role='viewer' WHERE org_id='${org}';DELETE FROM public.organizations WHERE id='${org}';COMMIT;`);
            expect((await db.auth.admin.deleteUser(id)).error).toBeNull();
        }
    } });
test.setTimeout(120000);

const panel=(p:Page)=>p.getByRole('dialog',{name:'Marketing data review',exact:true}),results=(p:Page)=>panel(p).getByRole('region',{name:'Data review results',exact:true}),row=(p:Page)=>panel(p).getByRole('region',{name:'Exact source row',exact:true});
async function seed(f:Fixture,n=1){sql(`INSERT INTO public.fact_marketing_performance(date,property_id,channel_id,source_account_id,currency_code,campaign_id,campaign_name,impressions,clicks,spend,conversions,raw_source)SELECT '${f.today}','${f.property}','google_ads','1234567890','USD','campaign-'||n,'Data campaign '||n,100,10,12.50,0.125,'provider-original' FROM generate_series(1,${n})n`)}
async function open(p:Page){await p.getByRole('button',{name:'Review data',exact:true}).click();await expect(results(p)).toBeVisible()}
async function login(p:Page,f:Fixture){await p.goto('/auth/login?redirect=%2Fdashboard%2Fbi');await p.getByLabel('Email address').fill(f.email);await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await expect(p).toHaveURL(/dashboard\/bi/,{timeout:30000});await open(p)}
async function save(p:Page){await panel(p).getByRole('button',{name:'Save exact data review',exact:true}).click();await expect(results(p).getByRole('heading',{name:'Saved data snapshot',exact:true})).toBeVisible()}
async function select(p:Page){await results(p).getByRole('button',{name:/Data campaign /}).first().click();await expect(row(p)).toBeVisible()}
async function exclude(p:Page){await select(p);await row(p).getByLabel('Data decision reason',{exact:true}).fill('Reviewed duplicate source against actual provider export.');await row(p).getByRole('button',{name:'Exclude reviewed row',exact:true}).click();await expect(panel(p).getByRole('status')).toContainText('Decision saved.')}
async function refresh(p:Page){await panel(p).getByRole('button',{name:'Refresh current data',exact:true}).click();await expect(results(p).getByRole('heading',{name:'Current source data',exact:true})).toBeVisible()}
async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const r=await f.db.rpc(name,{p_actor_id:f.id,p_property_id:f.property,...args});expect(r.error).toBeNull();return r.data}
async function states(f:Fixture){const r=await f.db.from('bi_data_row_state').select('*').eq('property_id',f.property);expect(r.error).toBeNull();return r.data!}
async function post(p:Page,f:Fixture,input:Record<string,unknown>){return p.request.post('/api/analytics/reconciliation',{headers:{origin},data:{id:randomUUID(),propertyId:f.property,expectedActorId:f.id,...input}})}
test('complete saved review, reversible exclusion, exact original and responsive history',async({page,fixture:f},info)=>{
 await seed(f,31);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page,f);await expect(results(page)).toContainText('31 source rows');await results(page).getByRole('button',{name:'Next data page',exact:true}).click();await expect(results(page)).toContainText('26–31 shown');await save(page);await exclude(page);expect((await states(f)).filter(x=>x.excluded)).toHaveLength(1);const read=await f.db.rpc('read_marketing_facts',{p_property_id:f.property,p_start_date:f.today,p_end_date:f.today});expect(read.data.row_count).toBe(30);await refresh(page);await save(page);const excluded=(await states(f))[0];const source=await rpc(f,'read_bi_data_review',{p_start:f.today,p_end:f.today,p_kind:'current'});const index=source.items.findIndex((x:{id:string})=>x.id===excluded.row_id);if(index<0)await results(page).getByRole('button',{name:'Next data page',exact:true}).click();const r=(await f.db.from('fact_marketing_performance').select('*').eq('id',excluded.row_id)).data![0];await results(page).getByRole('button',{name:new RegExp(r.campaign_name+' ·')}).click();await row(page).getByLabel('Data decision reason',{exact:true}).fill('Original export confirmed this row should remain included.');await page.setViewportSize({width:390,height:844});await row(page).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('data-review-mobile.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await row(page).getByRole('button',{name:'Restore reviewed row',exact:true}).click();await expect(panel(page).getByRole('status')).toContainText('Decision saved.');expect((await states(f))[0].excluded).toBe(false);expect(r.spend).toBe(12.5);await panel(page).getByRole('button',{name:'Data decision history',exact:true}).click();await expect(results(page)).toContainText('4 decisions');expect(errors).toEqual([])
})
test('missed save and exclusion replies recover a single durable decision after reload',async({page,fixture:f})=>{
 await seed(f);await login(page,f);await page.route('**/api/analytics/reconciliation',async route=>{if(route.request().method()==='POST'){await route.fetch();await route.abort()}else await route.continue()});await panel(page).getByRole('button',{name:'Save exact data review',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Check saved data request',exact:true})).toBeEnabled();await page.unroute('**/api/analytics/reconciliation');await page.reload();await open(page);await panel(page).getByRole('button',{name:'Check saved data request',exact:true}).click();await expect(results(page)).toContainText('Saved data snapshot');await select(page);await row(page).getByLabel('Data decision reason',{exact:true}).fill('Retained original confirms an overlapping source.');await page.route('**/api/analytics/reconciliation',async route=>{await route.fetch();await route.abort()});await row(page).getByRole('button',{name:'Exclude reviewed row',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Check saved data request',exact:true})).toBeEnabled();expect((await states(f))[0].excluded).toBe(true);await page.unroute('**/api/analytics/reconciliation');await page.reload();await open(page);await panel(page).getByRole('button',{name:'Check saved data request',exact:true}).click();await expect(results(page)).toContainText('Saved data snapshot');expect((await f.db.from('bi_data_commands').select('id').eq('property_id',f.property)).data).toHaveLength(2)
})
test('stale source is held and unused request cancellation fences late submission',async({page,fixture:f})=>{
 await seed(f);await login(page,f);await save(page);sql(`UPDATE public.fact_marketing_performance SET spend=20 WHERE property_id='${f.property}'`);await select(page);await row(page).getByLabel('Data decision reason',{exact:true}).fill('Old displayed source');await row(page).getByRole('button',{name:'Exclude reviewed row',exact:true}).click();await expect(panel(page).getByRole('alert')).toContainText('data or history changed');expect(await states(f)).toHaveLength(0);await panel(page).getByRole('button',{name:'Cancel unused data request',exact:true}).click();await expect(panel(page).getByRole('status')).toContainText('Unused request closed');await save(page);let request:Record<string,unknown>={};await select(page);await row(page).getByLabel('Data decision reason',{exact:true}).fill('New displayed source');await page.route('**/api/analytics/reconciliation',async route=>{request=route.request().postDataJSON();await route.abort()});await row(page).getByRole('button',{name:'Exclude reviewed row',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Cancel unused data request',exact:true})).toBeEnabled();await page.unroute('**/api/analytics/reconciliation');await panel(page).getByRole('button',{name:'Cancel unused data request',exact:true}).click();await expect(panel(page).getByRole('status')).toContainText('Unused request closed');const late=await page.request.post('/api/analytics/reconciliation',{headers:{origin},data:request});expect((await late.json()).status).toBe('cancelled');expect(await states(f)).toHaveLength(0)
})
test('exact historical download is distinct from its browser outcome and remains private',async({page,fixture:f})=>{
 await seed(f);await login(page,f);await save(page);await panel(page).getByRole('button',{name:'Prepare data review download',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Download prepared data review',exact:true})).toBeEnabled();sql(`UPDATE public.fact_marketing_performance SET spend=99 WHERE property_id='${f.property}'`);const download=page.waitForEvent('download');await panel(page).getByRole('button',{name:'Download prepared data review',exact:true}).click();const received=await download;const stream=await received.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));const original=JSON.parse(Buffer.concat(chunks).toString());expect(original.source.rows[0].source.spend).toBe(12.5);await expect(panel(page).getByRole('status')).toContainText('Browser download outcome recorded');const events=await f.db.from('shared_action_events').select('*').eq('property_id',f.property).like('action','bi.data.%');expect(events.data).toHaveLength(3);expect(events.data!.find(x=>x.action==='bi.data.export_reported')!.evidence).toBe('browser_observed');expect(events.data!.every(x=>!x.training_eligible)).toBe(true);expect(JSON.stringify(events.data)).not.toContain('Data campaign');await panel(page).getByRole('button',{name:'Saved data reviews',exact:true}).click();await results(page).getByRole('button',{name:/1 rows/}).click();await select(page);await expect(row(page).locator('pre')).toContainText('12.5')
})
test('excluded known identity holds CSV replacement until reviewed restoration',async({page,fixture:f})=>{
 await seed(f);await login(page,f);await save(page);await exclude(page);const original={filename:'reviewed.csv',csvContent:`Date,Campaign ID,Campaign,Impressions,Clicks,Cost,Conversions\n${f.today},campaign-1,Data campaign 1,100,10,25,0.125`,platform:'google_ads',sourceAccountId:'1234567890',campaignName:'Actual campaign',currencyCode:'USD'};const id=randomUUID();const prep=await page.request.post('/api/analytics/csv-imports',{headers:{origin},data:{id,propertyId:f.property,expectedActorId:f.id,operation:'prepare',original}});expect(prep.status()).toBe(200);const record=(await f.db.from('bi_csv_imports').select('*').eq('id',id)).data![0];const apply=await page.request.post('/api/analytics/csv-imports',{headers:{origin},data:{id:randomUUID(),propertyId:f.property,expectedActorId:f.id,operation:'apply',importId:id,previewHash:record.preview_hash,targetHash:record.target_hash,reason:'Reviewed exact replacement'}});expect(apply.status()).toBe(409);expect((await apply.json()).error).toContain('excluded');expect((await states(f))[0].excluded).toBe(true)
})
test('viewer can review original sources but cannot exclude data; origin is enforced',async({page,fixture:f})=>{
 await seed(f);sql(`BEGIN;SELECT set_config('p11.team_scope','${f.org}',true);UPDATE public.profiles SET role='viewer' WHERE id='${f.id}';COMMIT;`);await login(page,f);await save(page);await select(page);await expect(row(page)).toContainText('Only a property manager');expect(await row(page).getByRole('button',{name:'Exclude reviewed row',exact:true}).count()).toBe(0);const record=(await f.db.from('bi_data_reviews').select('id').eq('property_id',f.property)).data![0],fact=(await f.db.from('fact_marketing_performance').select('id').eq('property_id',f.property)).data![0];expect((await post(page,f,{operation:'exclude',reviewId:record.id,rowId:fact.id,kind:'daily',reason:'Viewer attempt'})).status()).toBe(403);expect((await page.request.post('/api/analytics/reconciliation',{headers:{origin:'https://other.invalid'},data:{id:randomUUID(),propertyId:f.property,expectedActorId:f.id,operation:'cancel'}})).status()).toBe(403);expect(await states(f)).toHaveLength(0)
})
test('failed first read remains refreshable without creating a review',async({page,fixture:f})=>{
 await seed(f);let blocked=true;await page.route('**/api/analytics/reconciliation?**',async route=>{if(blocked)await route.fulfill({status:503,json:{error:'Temporary source interruption'}});else await route.continue()});await page.goto('/auth/login?redirect=%2Fdashboard%2Fbi');await page.getByLabel('Email address').fill(f.email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/dashboard\/bi/);await page.getByRole('button',{name:'Review data',exact:true}).click();await expect(panel(page).getByRole('alert')).toContainText('Temporary source interruption');blocked=false;await refresh(page);await expect(results(page)).toContainText('1 source rows');expect((await f.db.from('bi_data_reviews').select('id').eq('property_id',f.property)).data).toHaveLength(0)
})
