import{test as base,expect,type Page}from'@playwright/test'
import{createClient}from'@supabase/supabase-js'
import{randomUUID}from'node:crypto'
import{execFileSync}from'node:child_process'
import{readFileSync}from'node:fs'
const baseURL=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430',origin=new URL(baseURL).origin,url=process.env.NEXT_PUBLIC_SUPABASE_URL!,password='local-bi-report-fixture-password'
const service=()=>createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
function sql(input:string){return execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input,stdio:['pipe','pipe','pipe']})}
type Fixture={id:string;email:string;org:string;property:string;db:ReturnType<typeof service>;today:string}
const test=base.extend<{fixture:Fixture}>({fixture:async({page},provide)=>{
 if(!['127.0.0.1','localhost'].includes(new URL(url).hostname)||!['127.0.0.1','localhost'].includes(new URL(baseURL).hostname))throw new Error('Local disposable fixtures only')
 const db=service(),email='bi-browser-'+randomUUID()+'@p11.test',created=await db.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull();const id=created.data.user!.id,org=randomUUID(),property=randomUUID(),today=await page.evaluate(()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`})
 try{
  sql(`BEGIN;INSERT INTO public.organizations(id,name)VALUES('${org}','BI browser fixture');SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id='${org}',role='viewer' WHERE id='${id}';INSERT INTO public.properties(id,org_id,name)VALUES('${property}','${org}','BI report fixture property');INSERT INTO public.fact_marketing_performance(property_id,date,channel_id,source_account_id,currency_code,campaign_id,campaign_name,impressions,clicks,spend,conversions)SELECT '${property}','${today}','google_ads','1111111111','USD','campaign-'||n,CASE WHEN n=31 THEN '=SUM(2,3) "quoted" final campaign' ELSE 'Report campaign '||n END,100,10,10.01,0.125 FROM generate_series(0,31)n;INSERT INTO public.fact_marketing_performance(property_id,date,channel_id,source_account_id,currency_code,campaign_id,campaign_name,impressions,clicks,spend,conversions)VALUES('${property}','${today}','google_ads','2222222222','USD','campaign-0','Report campaign 0 second account',0,0,0,0),('${property}','${today}'::date-30,'google_ads','1111111111','USD','prior','Prior zero baseline',0,0,0,0);COMMIT;`)
  await provide({id,email,org,property,db,today})
 }finally{sql(`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${property}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${property}';SET LOCAL session_replication_role=origin;DELETE FROM public.fact_marketing_performance WHERE property_id='${property}';DELETE FROM public.properties WHERE id='${property}';SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id=NULL,role='viewer' WHERE org_id='${org}';DELETE FROM public.organizations WHERE id='${org}';COMMIT;`);expect((await db.auth.admin.deleteUser(id)).error).toBeNull()}
}})
test.setTimeout(120000)
const saved=(p:Page)=>p.getByRole('region',{name:'Saved marketing reports'}),coverage=(p:Page)=>p.getByRole('region',{name:'Report coverage'})
async function login(p:Page,f:Fixture){await p.goto('/auth/login?redirect=%2Fdashboard%2Fbi');await p.getByLabel('Email address').fill(f.email);await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await expect(p).toHaveURL(/dashboard\/bi/,{timeout:30000});await expect(coverage(p)).toContainText('33 stored records',{timeout:30000});await expect(saved(p).getByRole('button',{name:'Refresh saved reports'})).toBeEnabled()}
async function save(p:Page,name='Client review'){await saved(p).getByLabel('Report name').fill(name);await saved(p).getByRole('button',{name:'Save current report'}).click();await expect(saved(p).getByRole('status')).toContainText('Report saved');await expect(saved(p).getByRole('button',{name:'Download CSV'})).toBeEnabled()}
const endpoint=(f:Fixture,kind='current')=>'/api/analytics/reports?'+new URLSearchParams({propertyId:f.property,kind,...(kind==='current'?{startDate:f.today,endDate:f.today,compare:'true'}:{})})
test('native saved report keeps exact figures and produces complete CSV and PDF after later imports',async({page,fixture:f},info)=>{
 await login(page,f);await expect(coverage(page)).toContainText('1 of 30 selected dates');await expect(page.getByText('+100%',{exact:true})).toHaveCount(0);await save(page)
 const rows=await f.db.from('bi_reports').select('id,source_hash,source').eq('property_id',f.property);expect(rows.error).toBeNull();expect(rows.data).toHaveLength(1);const id=rows.data![0].id
 expect(JSON.stringify(rows.data![0].source)).not.toContain('raw_source')
 expect((await f.db.from('fact_marketing_performance').update({spend:20.01}).eq('property_id',f.property).eq('campaign_id','campaign-0').eq('source_account_id','1111111111')).error).toBeNull()
 await page.getByRole('button',{name:'Refresh data',exact:true}).click();await expect(coverage(page)).toContainText('33 stored records')
 const csvWait=page.waitForEvent('download');await saved(page).getByRole('button',{name:'Download CSV'}).click();const csv=await csvWait;await csv.saveAs(info.outputPath('retained-report.csv'));const text=readFileSync(info.outputPath('retained-report.csv'),'utf8');expect(text).toContain('$320.32');expect(text).not.toContain('$330.32');expect(text).toContain(id);expect(text).toContain('"\'=SUM(2,3) ""quoted"" final campaign"');expect(text).toContain('Not available');expect(text).toContain('0.125');await expect(saved(page).getByRole('status')).toContainText('Browser download started')
 const pdfWait=page.waitForEvent('download');await saved(page).getByRole('button',{name:'Download PDF'}).click();const pdf=await pdfWait;await pdf.saveAs(info.outputPath('retained-report.pdf'));expect(readFileSync(info.outputPath('retained-report.pdf')).subarray(0,4).toString()).toBe('%PDF');await expect(saved(page).getByRole('status')).toContainText('Browser download started')
 const events=await f.db.from('shared_action_events').select('action,evidence,phase,training_eligible').eq('property_id',f.property).like('action','bi.%');expect(events.data?.filter(x=>x.action==='bi.export.prepared')).toHaveLength(2);expect(events.data?.filter(x=>x.action==='bi.export.reported')).toHaveLength(2);expect(events.data?.filter(x=>x.action==='bi.export.reported').every(x=>x.evidence==='browser_observed'&&x.phase==='observed'&&!x.training_eligible)).toBe(true)
 await page.screenshot({path:info.outputPath('reports-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('reports-mobile.png'),fullPage:true})
})

test('account filters and campaign drawer use one snapshot without a second live trend fetch',async({page,fixture:f})=>{await login(page,f);let trendCalls=0;await page.route('**/api/analytics/campaigns?**',route=>{trendCalls++;return route.abort()});await page.getByLabel('Report account',{exact:true}).selectOption(JSON.stringify(['google_ads','2222222222']));await expect(coverage(page)).toContainText('1 stored records');await page.getByRole('button',{name:/Campaign Breakdown/}).click();await page.getByRole('row').filter({hasText:'second account'}).click();await expect(page.getByRole('dialog',{name:'Campaign details'})).toContainText('Account 2222222222');await expect(page.getByRole('dialog',{name:'Campaign details'})).toContainText('Not available');expect(trendCalls).toBe(0);await page.getByRole('button',{name:'Close campaign details'}).click();await expect(page.getByRole('dialog')).toHaveCount(0)})

test('lost save reply is recovered after reload without a duplicate decision or stored metrics',async({page,fixture:f})=>{await login(page,f);let lost=false;await page.route('**/api/analytics/reports',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='save'&&!lost){lost=true;await route.fetch();await route.abort()}else await route.continue()});await saved(page).getByLabel('Report name').fill('Lost reply');await saved(page).getByRole('button',{name:'Save current report'}).click();await expect(saved(page)).toContainText('A save request needs confirmation');await expect(saved(page).getByRole('alert')).toBeVisible();const pending=await page.evaluate(({id,property})=>JSON.parse(sessionStorage.getItem(`p11.bi-report.v1:${id}:${property}`)!),{id:f.id,property:f.property});expect(Object.keys(pending).sort()).toEqual(['id','kind']);await page.reload();await saved(page).getByRole('button',{name:'Check request result'}).click();await expect(saved(page).getByRole('status')).toContainText('Report saved');expect((await f.db.from('bi_reports').select('id',{count:'exact',head:true}).eq('property_id',f.property)).count).toBe(1)})

test('unused cancellation fences the delayed original save',async({page,fixture:f})=>{await login(page,f);let intercepted:unknown;await page.route('**/api/analytics/reports',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='save'&&!intercepted){intercepted=route.request().postDataJSON();await route.abort()}else await route.continue()});await saved(page).getByLabel('Report name').fill('Delayed report');await saved(page).getByRole('button',{name:'Save current report'}).click();await saved(page).getByRole('button',{name:'Cancel unused save'}).click();await expect(saved(page).getByRole('status')).toContainText('Unused save request cancelled');const late=await page.request.post('/api/analytics/reports',{headers:{origin},data:intercepted});expect(late.status()).toBe(200);expect((await late.json()).status).toBe('cancelled');expect((await f.db.from('bi_reports').select('state').eq('property_id',f.property)).data).toEqual([{state:'cancelled'}])})

test('changed source holds a save until the user reloads and reviews newer numbers',async({page,fixture:f})=>{await login(page,f);expect((await f.db.from('fact_marketing_performance').update({spend:30}).eq('property_id',f.property).eq('campaign_id','campaign-0').eq('source_account_id','1111111111')).error).toBeNull();await saved(page).getByLabel('Report name').fill('Outdated report');await saved(page).getByRole('button',{name:'Save current report'}).click();await expect(saved(page).getByRole('alert')).toContainText('Marketing data changed');expect((await f.db.from('bi_reports').select('id',{count:'exact',head:true}).eq('property_id',f.property)).count).toBe(0);await saved(page).getByRole('button',{name:'Cancel unused save'}).click();await expect(saved(page).getByRole('status')).toContainText('cancelled');await page.getByRole('button',{name:'Refresh data',exact:true}).click();await expect(coverage(page)).toContainText('33 stored records');await save(page,'Reviewed current data')})

test('lost export preparation does not start a file and resumes exactly the same export',async({page,fixture:f})=>{await login(page,f);await save(page);let lost=false,downloads=0;page.on('download',()=>downloads++);await page.route('**/api/analytics/reports',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='export'&&!lost){lost=true;await route.fetch();await route.abort()}else await route.continue()});await saved(page).getByRole('button',{name:'Download CSV'}).click();await expect(saved(page)).toContainText('An export request needs confirmation');expect(downloads).toBe(0);await saved(page).getByRole('button',{name:'Check request result'}).click();await expect(saved(page).getByRole('status')).toContainText('Export is prepared');expect(downloads).toBe(0);await saved(page).getByRole('button',{name:'Download prepared export'}).click();await expect(saved(page).getByRole('status')).toContainText('Browser download started');expect(downloads).toBe(1);expect((await f.db.from('bi_report_exports').select('id',{count:'exact',head:true}).eq('property_id',f.property)).count).toBe(1)})

test('lost browser observation recovers recorded outcome without another download',async({page,fixture:f})=>{await login(page,f);await save(page);let lost=false,downloads=0;page.on('download',()=>downloads++);await page.route('**/api/analytics/reports',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='observe'&&!lost){lost=true;await route.fetch();await route.abort()}else await route.continue()});await saved(page).getByRole('button',{name:'Download CSV'}).click();await expect(saved(page)).toContainText('An export request needs confirmation');await expect.poll(()=>lost).toBe(true);await expect(saved(page).getByRole('alert')).toBeVisible();await page.reload();await saved(page).getByRole('button',{name:'Check request result'}).click();await expect(saved(page).getByRole('status')).toContainText('Export history confirmed');expect(downloads).toBe(1);expect((await f.db.from('bi_export_observations').select('outcome').eq('property_id',f.property)).data).toEqual([{outcome:'download_started'}])})

test('browser download failure records failure without a success claim',async({page,fixture:f})=>{await login(page,f);await save(page);await page.evaluate(()=>{URL.createObjectURL=()=>{throw new Error('fixture download failure')}});await saved(page).getByRole('button',{name:'Download CSV'}).click();await expect(saved(page).getByRole('status')).toContainText('could not start the download');expect((await f.db.from('bi_export_observations').select('outcome').eq('property_id',f.property)).data).toEqual([{outcome:'download_failed'}])})

test('current report failure clears stale figures while saved reports remain available',async({page,fixture:f})=>{await login(page,f);await save(page);await page.route('**/api/analytics/reports?**',route=>new URL(route.request().url()).searchParams.get('startDate')?route.fulfill({status:503,json:{error:'Fixture report unavailable'}}):route.continue());await page.getByRole('button',{name:'Refresh data',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Fixture report unavailable'})).toBeVisible();await expect(coverage(page)).toHaveCount(0);await expect(saved(page).getByRole('button',{name:'Save current report'})).toBeDisabled();await expect(saved(page).getByRole('button',{name:'Download CSV'})).toBeEnabled()})

test('later filter result wins over an earlier request and date presets include exactly seven dates',async({page,fixture:f})=>{await login(page,f);let release!:()=>void,started=false;const gate=new Promise<void>(resolve=>{release=resolve});await page.route('**/api/analytics/reports?**',async route=>{const q=new URL(route.request().url()).searchParams;if(q.has('startDate')&&q.get('channel')==='google_ads'&&!q.has('account')&&!started){started=true;const r=await route.fetch();await gate;try{await route.fulfill({response:r})}catch{}}else await route.continue()});await page.getByLabel('Report channel',{exact:true}).selectOption('google_ads');await expect.poll(()=>started).toBe(true);await page.getByLabel('Report channel',{exact:true}).selectOption('meta_ads');await expect(coverage(page)).toContainText('0 stored records');release();await expect(coverage(page)).toContainText('0 stored records');await page.getByRole('button',{name:/^Last 30 days/}).click();await page.getByRole('button',{name:/^Last 7 days/}).click();await expect(coverage(page)).toContainText('7 selected dates')})

test('native history covers subsequent pages and rejects cross-property or changed-account requests',async({page,fixture:f})=>{await login(page,f);for(let n=0;n<22;n++){const r=await page.request.post('/api/analytics/reports',{headers:{origin},data:{operation:'cancel',propertyId:f.property,expectedActorId:f.id,id:randomUUID()}});expect(r.status()).toBe(200)}await saved(page).getByRole('button',{name:'Refresh saved reports'}).click();await expect(saved(page)).toContainText('22 saved or cancelled requests');await saved(page).getByRole('button',{name:'More reports'}).click();await expect(saved(page)).toContainText('21–22 of 22');const bad=await page.request.get(endpoint(f,'history').replace(f.property,randomUUID()));expect(bad.status()).toBe(403);expect((await page.request.post('/api/analytics/reports',{headers:{origin},data:{operation:'cancel',propertyId:f.property,expectedActorId:randomUUID(),id:randomUUID()}})).status()).toBe(409);expect((await page.request.post('/api/analytics/reports',{headers:{origin:'https://other.test'},data:{operation:'cancel',propertyId:f.property,expectedActorId:f.id,id:randomUUID()}})).status()).toBe(403)})

test('permission removal prevents saved report reads and downloads',async({page,fixture:f})=>{await login(page,f);await save(page);sql(`BEGIN;SELECT set_config('p11.team_scope','${f.org}',true);UPDATE public.profiles SET org_id=NULL WHERE id='${f.id}';COMMIT;`);const r=await page.request.get(endpoint(f,'history'));expect(r.status()).toBe(403);await saved(page).getByRole('button',{name:'Download CSV'}).click();await expect(saved(page).getByRole('alert')).toContainText('unavailable to your account');expect((await f.db.from('bi_report_exports').select('id',{count:'exact',head:true}).eq('property_id',f.property)).count).toBe(0)})


test('campaign pages include every record and reset when the search changes',async({page,fixture:f})=>{await login(page,f);await page.getByRole('button',{name:/Campaign Breakdown/}).click();const rows=page.locator('tbody tr');await expect(rows).toHaveCount(25);await page.getByRole('button',{name:'Next campaigns'}).click();await expect(rows).toHaveCount(8);await expect(rows.filter({hasText:'second account'})).toBeVisible();await page.getByPlaceholder('Search campaigns...').fill('Report campaign 15');await expect(rows).toHaveCount(1);await expect(rows).toContainText('Report campaign 15');await page.getByPlaceholder('Search campaigns...').fill('');await expect(rows).toHaveCount(25)})

test('unavailable browser storage prevents an untracked report mutation',async({page,fixture:f})=>{await login(page,f);await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('fixture quota','QuotaExceededError')}});await saved(page).getByLabel('Report name').fill('Storage unavailable');await saved(page).getByRole('button',{name:'Save current report'}).click();await expect(saved(page).getByRole('alert')).toContainText('allow browser storage');expect((await f.db.from('bi_reports').select('id',{count:'exact',head:true}).eq('property_id',f.property)).count).toBe(0)})
