import {test,expect} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {writeFileSync,mkdirSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {execFileSync} from 'node:child_process'

// This is an explicit, retained rehearsal, continued by the isolated export/offboarding drill.
// Ordinary test runs do not create durable client fixtures.
const output=process.env.P11_CLIENT_LIFECYCLE_ARTIFACT_DIR
const baseURL=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430'
test.skip(!output,'Run with an explicit local lifecycle evidence directory')
test.setTimeout(240000)
test('one client travels from onboarding through brand, brief, inquiry, booking, CRM preparation and reporting',async({page},info)=>{
 page.setDefaultTimeout(15000)
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL!
 for(const address of[url,baseURL])if(!['localhost','127.0.0.1'].includes(new URL(address).hostname))throw new Error('Local rehearsal only')
 const folder=resolve(output!);mkdirSync(folder,{recursive:true})
 const db=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
 const email=`lifecycle-${randomUUID()}@p11.test`,password=`Fixture-${randomUUID()}`
 const created=await db.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull()
 const actor=created.data.user!.id,record:Record<string,unknown>={source:'synthetic',actor,email,stages:[],providerCalls:false,trainingEligible:false}
 const save=(name:string,details:Record<string,unknown>={})=>{Object.assign(record,details);(record.stages as string[]).push(name);writeFileSync(join(folder,'journey.json'),JSON.stringify(record,null,2),{mode:0o600})}
 save('fixture-created')
 async function rpc(name:string,args:Record<string,unknown>){const r=await db.rpc(name,args);expect(r.error,JSON.stringify(r.error)).toBeNull();return r.data}
 function sql(input:string){execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-X','-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1'],{input,stdio:['pipe','pipe','pipe']})}
 await page.goto('/auth/login');await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/onboarding/)
 await page.getByLabel(/Organization name/i).fill('Synthetic lifecycle client');await page.getByLabel(/Legal name/i).fill('Synthetic lifecycle client');await page.getByRole('button',{name:'Continue',exact:true}).click()
 await page.getByLabel(/Property name/i).fill('Lifecycle courtyard');await page.getByPlaceholder('City',{exact:true}).fill('San Diego');await page.getByLabel(/Unit count/i).fill('24');await page.getByRole('button',{name:'Continue',exact:true}).click()
 await page.getByPlaceholder('Jane Smith').fill('Synthetic client contact');await page.getByPlaceholder('jane@property.com').fill('client@fixture.invalid');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Save and review setup'}).click();await page.getByRole('button',{name:'Complete Setup',exact:true}).click();await expect(page.getByRole('region',{name:'Completed organization setup'})).toBeVisible()
 const setup=(await rpc('read_organization_setup',{p_actor_id:actor,p_input:{}})).setup,property=setup.property_id as string,org=setup.org_id as string;save('onboarding-complete',{property,org})
 await page.getByRole('link',{name:'Open my property'}).click();await expect(page.getByRole('combobox',{name:'Property',exact:true})).toHaveValue(property)
 await page.route('**/api/community/knowledge-sources?*',r=>r.fulfill({status:503,json:{error:'Knowledge service temporarily unavailable'}}));await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Error loading data'})).toContainText('temporarily unavailable');await page.unroute('**/api/community/knowledge-sources?*');await page.getByRole('button',{name:'Retry loading data'}).click();await expect(page.getByRole('alert').filter({hasText:'Error loading data'})).toHaveCount(0)
 await expect(page.getByRole('status',{name:'Loading property data'})).toHaveCount(0);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Knowledge Base',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Knowledge Base',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Overview',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('client-property-mobile.png')});await page.setViewportSize({width:1280,height:900});save('property-mobile-keyboard-retry')
 await page.goto(`/dashboard/properties/${property}/edit`);await page.getByLabel('Property city',{exact:true}).fill('Carlsbad');await page.getByLabel('Reason for this property change',{exact:true}).fill('Correct the client city before preparing website work');await page.getByRole('button',{name:'Save property changes',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Property change saved.'})).toBeVisible();save('property-fact-corrected')
 await page.goto('/dashboard/community');await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();const files=page.getByRole('region',{name:'Private original files'});await files.getByRole('button',{name:'Add private original'}).click();await files.getByLabel('Original file',{exact:true}).setInputFiles({name:'courtyard-facts.txt',mimeType:'text/plain',buffer:Buffer.from('Lifecycle courtyard has 24 homes in Carlsbad. Tours are available by appointment.')});await files.getByLabel('File title',{exact:true}).fill('Supplied courtyard facts');await files.getByLabel('Reason for retaining this file',{exact:true}).fill('Retain the synthetic client source');await files.getByRole('button',{name:'Retain exact original'}).click();await expect(files).toContainText('Original retained and verified');await files.getByLabel('Reason for this file decision',{exact:true}).fill('Review the supplied facts');await files.getByRole('button',{name:'Extract original text'}).click();await expect(files.getByLabel('Reviewed file text',{exact:true})).toHaveValue(/24 homes in Carlsbad/);await files.getByLabel('Reason for this file decision',{exact:true}).fill('Accept the exact extracted client facts');await files.getByRole('checkbox').check();await files.getByRole('button',{name:'Save reviewed file text'}).click();await expect(files.getByRole('link',{name:'Open reviewed text'})).toBeVisible();const original=(await db.from('knowledge_files').select('id,storage_path').eq('property_id',property).single()).data!;save('original-extracted-and-reviewed',{original:original.id,originalStoragePath:original.storage_path})

 // A client-supplied asset is an input fixture; its approval is a real browser action.
 const asset=randomUUID();expect((await db.from('content_assets').insert({id:asset,org_id:org,property_id:property,name:'Courtyard supplied font',asset_type:'font',asset_role:'font',file_url:'https://example.invalid/font.woff2',rights_status:'owned',approval_status:'pending'})).error).toBeNull()
 await page.goto(`/dashboard/brandforge/${property}/assets`);await page.getByRole('button',{name:'Review brand asset Courtyard supplied font',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Brand asset review'});await dialog.getByLabel('Brand license or permission notes').fill('Synthetic supplied material; local rehearsal only');await dialog.getByLabel('Reason for this brand asset decision').fill('Review the supplied client font');await dialog.getByRole('button',{name:'Approve for brand use',exact:true}).click();await expect.poll(async()=>(await db.from('content_assets').select('approval_status').eq('id',asset).single()).data?.approval_status).toBe('approved');save('brand-reviewed',{asset})
 await page.goto('/dashboard/siteforge');await page.getByLabel('What would you like to build or change?').fill('Build the Lifecycle courtyard website using the approved brand and a clear tour inquiry form.');await page.getByLabel('References and source notes').fill(`Approved supplied font ${asset}; property ${property}.`);await page.getByRole('button',{name:'Save brief',exact:true}).click();await expect(page.getByRole('region',{name:'Saved Codex briefs',exact:true})).toContainText('1 saved brief snapshots');const brief=(await db.from('siteforge_codex_briefs').select('id,document').eq('property_id',property).single()).data!;expect(brief.document).toContain(asset);expect(brief.document).toContain('Carlsbad');save('codex-brief-saved',{brief:brief.id})
 // Widget setup and visitor session are input fixtures; contact capture, scoring and booking use real endpoints.
 const session=randomUUID(),conversation=randomUUID(),key='lifecycle_'+randomUUID();sql(`BEGIN;INSERT INTO public.lumaleasing_config(property_id,api_key,is_active)VALUES('${property}','${key}',true);INSERT INTO public.widget_sessions(id,property_id,visitor_id,last_activity_at)VALUES('${session}','${property}','${session}',clock_timestamp());INSERT INTO public.conversations(id,property_id,widget_session_id,channel)VALUES('${conversation}','${property}','${session}','widget');INSERT INTO public.messages(conversation_id,role,content)VALUES('${conversation}','user','I would like to tour the courtyard.');COMMIT;`)
 const body={requestId:randomUUID(),sessionId:session,conversationId:conversation,firstName:'Lifecycle',lastName:'Visitor',email:`visitor-${session}@fixture.invalid`},send=()=>page.request.post('/api/lumaleasing/lead',{headers:{origin:new URL(baseURL).origin,'x-api-key':key},data:body});const response=await send();expect(response.status(),await response.text()).toBe(200);const lead=(await response.json()).leadId;expect((await(await send()).json()).leadId).toBe(lead);expect((await db.from('conversations').select('lead_id').eq('id',conversation).single()).data?.lead_id).toBe(lead);expect((await db.from('lead_scores').select('id').eq('lead_id',lead)).data!.length).toBeGreaterThan(0);save('inquiry-linked-and-scored',{lead,session,conversation})
 await page.goto('/dashboard/leads');await page.getByText('Lifecycle Visitor',{exact:true}).click();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('dialog').getByLabel('First Name',{exact:true}).fill('Corrected');await page.getByRole('button',{name:'Save Changes',exact:true}).click();await expect.poll(async()=>(await db.from('leads').select('first_name').eq('id',lead).single()).data?.first_name).toBe('Corrected');save('lead-corrected');await page.getByRole('button',{name:/^Tours/}).click();await page.getByRole('button',{name:'New Tour',exact:true}).click();const booking=page.getByRole('dialog',{name:'Schedule tour'});await booking.getByLabel('Property timezone',{exact:true}).selectOption('America/Los_Angeles');await booking.getByRole('button',{name:'Save property timezone',exact:true}).click();await expect(booking.getByText('Date and time use America/Los_Angeles.',{exact:false})).toBeVisible();await booking.getByLabel('Tour date',{exact:true}).fill(new Date(Date.now()+3*86400000).toISOString().slice(0,10));await booking.getByRole('button',{name:'Save booking',exact:true}).click();await expect(booking.getByRole('status')).toContainText('Outbound delivery is currently paused');const tours=(await db.from('tours').select('id,lead_id').eq('property_id',property)).data!;expect(tours).toHaveLength(1);expect(tours[0].lead_id).toBe(lead);save('tour-booked-with-delivery-paused',{tour:tours[0].id});await booking.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Cancel tour',exact:true}).click();await page.getByLabel('Reason for change',{exact:true}).fill('Synthetic prospect changed plans');await page.getByRole('button',{name:'Confirm cancellation',exact:true}).click();await expect(page.getByText('Cancellation recorded',{exact:true})).toBeVisible();expect((await db.from('tours').select('status').eq('id',tours[0].id).single()).data?.status).toBe('cancelled');save('tour-cancelled-with-history')
 await page.goto('/dashboard/settings/crm');await page.getByLabel('API key or access token').fill('synthetic-local-key');await page.getByLabel('Email CRM field',{exact:true}).fill('email');await page.getByLabel('First name CRM field',{exact:true}).fill('first_name');await page.getByRole('button',{name:'Save mapping for review'}).click();await expect(page.getByText('Mapping saved for review.',{exact:true})).toBeVisible()
 const connection=(await db.from('integration_credentials').select('*').eq('property_id',property).single()).data!,preview=randomUUID(),receipt=randomUUID();await rpc('preview_crm_mapping',{p_property_id:property,p_actor_id:actor,p_request_id:preview,p_integration_id:connection.id,p_revision:connection.crm_revision});await rpc('approve_crm_mapping',{p_property_id:property,p_actor_id:actor,p_request_id:randomUUID(),p_preview_id:preview});expect((await db.from('crm_validation_receipts').insert({id:receipt,property_id:property,integration_id:connection.id,revision:connection.crm_revision,credentials_hash:await rpc('crm_configuration_hash',{p_value:connection.credentials}),mapping_hash:await rpc('crm_configuration_hash',{p_value:connection.field_mapping}),provider_identity:{fixture:true},capabilities:{fixture:true,leadSearch:true,leadRead:true,leadWrite:true,noteWrite:true},evidence:{simulated:true},state:'verified'})).error).toBeNull();expect((await db.from('integration_credentials').update({crm_validation_receipt_id:receipt,mapping_validated:true,status:'connected'}).eq('id',connection.id)).error).toBeNull()
 await page.reload();await page.getByLabel('Preview source').selectOption(lead);let losePrepare=true;const handoffRequests:string[]=[];await page.route('**/api/crm/deliveries',async r=>{if(r.request().method()==='POST'&&r.request().postDataJSON()?.action==='prepare'){handoffRequests.push(r.request().postDataJSON().requestId);if(losePrepare){losePrepare=false;const saved=await r.fetch();expect(saved.ok()).toBe(true);await r.abort('failed');return}}await r.continue()});await page.getByRole('button',{name:'Prepare lead transfer',exact:true}).click();await expect(page.getByRole('region',{name:'Individual CRM transfers'}).getByRole('alert')).toContainText('Failed to fetch');await page.reload();await page.getByLabel('Preview source').selectOption(lead);await page.getByRole('button',{name:'Prepare lead transfer',exact:true}).click();expect(handoffRequests).toHaveLength(2);expect(handoffRequests[1]).toBe(handoffRequests[0]);expect((await db.from('crm_handoffs').select('id').eq('property_id',property)).data).toHaveLength(1);save('crm-interrupted-and-recovered');await expect(page.getByRole('region',{name:'Individual CRM transfers'})).toContainText(body.email);await expect(page.getByRole('region',{name:'Individual CRM transfers'})).toContainText('Corrected');await expect(page.getByRole('button',{name:'Approve these values and send'})).toBeDisabled();await page.getByRole('button',{name:'Stop transfer',exact:true}).click();await expect(page.getByText('Transfer stopped before a provider write.',{exact:true})).toBeVisible();save('crm-prepared-and-stopped',{crm:connection.id,crmProviderEvidence:'synthetic; not live qualification'})
 const overview=await page.request.get('/api/dashboard/overview?propertyId='+property);expect(overview.status()).toBe(200);expect((await overview.json()).metrics.totalLeads.value).toBe(1)
 await page.goto('/dashboard/bi');const report=page.getByRole('region',{name:'Saved marketing reports'});await report.getByLabel('Report name').fill('Lifecycle client empty-source report');await report.getByRole('button',{name:'Save current report'}).click();await expect(report.getByRole('status')).toContainText('Report saved');expect((await db.from('bi_reports').select('id').eq('property_id',property)).data).toHaveLength(1);save('report-saved-without-invented-marketing-results')
 const actions=(await db.from('shared_action_events').select('action,training_eligible,property_id,org_id').eq('property_id',property)).data!;expect(actions.length).toBeGreaterThan(8);expect(actions.every(a=>a.org_id===org&&!a.training_eligible)).toBe(true);expect((await db.from('crm_handoff_receipts').select('id').eq('property_id',property)).data).toHaveLength(0);save('journey-passed',{actionCount:actions.length,actions:[...new Set(actions.map(a=>a.action))]});await page.screenshot({path:info.outputPath('client-report-desktop.png')});await page.context().storageState({path:join(folder,'private-browser-session.json')})

})
