import {test as base,expect,type Page}from '@playwright/test'
import {createClient}from '@supabase/supabase-js'
import {randomUUID}from 'node:crypto'
import {execFileSync}from 'node:child_process'
const baseURL=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430',url=process.env.NEXT_PUBLIC_SUPABASE_URL!,password='local-search-fixture-password'
const service=()=>createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
function sql(input:string){return execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input,stdio:['pipe','pipe','pipe']})}
type Fixture={id:string;email:string;org:string;property:string;key:string;conversation:string;session:string;db:ReturnType<typeof service>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(url).hostname)||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname))throw new Error('Local disposable fixtures only')
 const db=service(),email='console-search-browser-'+randomUUID()+'@p11.test',created=await db.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull();const id=created.data.user!.id,org=randomUUID(),property=randomUUID(),conversation=randomUUID(),session=randomUUID(),key='luma_conversation_'+randomUUID()
 try{sql(`BEGIN;INSERT INTO public.organizations(id,name)VALUES('${org}','Console search browser fixture');SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id='${org}',role='admin' WHERE id='${id}';INSERT INTO public.properties(id,org_id,name)VALUES('${property}','${org}','Console search fixture property');INSERT INTO public.lumaleasing_config(property_id,api_key,is_active)VALUES('${property}','${key}',true);INSERT INTO public.widget_sessions(id,property_id,last_activity_at)VALUES('${session}','${property}',clock_timestamp());INSERT INTO public.conversations(id,property_id,widget_session_id,channel)VALUES('${conversation}','${property}','${session}','widget');INSERT INTO public.messages(conversation_id,role,content)VALUES('${conversation}','user','Private original visitor question');COMMIT;`);await provide({id,email,org,property,key,conversation,session,db})}
 finally{sql(`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${property}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${property}';SET LOCAL session_replication_role=origin;DELETE FROM public.tour_bookings WHERE property_id='${property}';DELETE FROM public.messages WHERE conversation_id IN(SELECT id FROM public.conversations WHERE property_id='${property}');DELETE FROM public.conversations WHERE property_id='${property}';DELETE FROM public.widget_sessions WHERE property_id='${property}';DELETE FROM public.leads WHERE property_id='${property}';DELETE FROM public.properties WHERE id='${property}';SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id=NULL,role='viewer' WHERE org_id='${org}';DELETE FROM public.organizations WHERE id='${org}';COMMIT;`);expect((await db.auth.admin.deleteUser(id)).error).toBeNull()}
}})
test.setTimeout(120000)

const dialog=(page:Page)=>page.getByRole('dialog',{name:'Search console',exact:true}),results=(page:Page)=>dialog(page).getByRole('region',{name:'Saved search results',exact:true}),source=(page:Page)=>dialog(page).getByRole('region',{name:'Selected saved search source',exact:true})
async function login(page:Page,f:Fixture){await page.goto('/auth/login?redirect=%2Fdashboard%2Flumaleasing');await page.getByLabel('Email address').fill(f.email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/dashboard\/lumaleasing/,{timeout:30000});await page.getByRole('button',{name:'Search console',exact:true}).click();await expect(dialog(page)).toBeVisible()}
async function search(page:Page,q:string,filter='all'){await dialog(page).getByLabel('Search text',{exact:true}).fill(q);await dialog(page).getByLabel('Search type',{exact:true}).selectOption(filter);await expect(dialog(page).getByRole('button',{name:'Search records',exact:true})).toBeEnabled();await dialog(page).getByRole('button',{name:'Search records',exact:true}).click()}
async function pick(page:Page,title:string){await results(page).getByRole('button',{name:new RegExp('^'+title)}).click();await expect(source(page)).toBeVisible()}
test('complete literal search and saved paging exceed old samples without leaking private query text',async({page,fixture:f},info)=>{
 sql(`INSERT INTO public.leads(property_id,first_name,last_name,email,source,status)SELECT '${f.property}','Needle',n::text,'contact-'||n||'@fixture.invalid','widget','new'FROM generate_series(1,45)n;INSERT INTO public.documents(property_id,content,metadata)SELECT '${f.property}','Unmatched stored original '||n,jsonb_build_object('title','Earlier source '||n)FROM generate_series(1,65)n;INSERT INTO public.documents(property_id,content,metadata)VALUES('${f.property}','Needle beyond the earlier fifty-row sample.','{"title":"Needle source"}');`);await login(page,f);await search(page,'Needle');await expect(results(page)).toContainText('46 matching records');await expect(results(page).getByRole('listitem')).toHaveCount(20);await results(page).getByRole('button',{name:'Next results'}).click();await expect(results(page)).toContainText('21–40 of 46');await results(page).getByRole('button',{name:'Next results'}).click();await expect(results(page).getByRole('listitem')).toHaveCount(6);const actions=(await f.db.from('shared_action_events').select('*').eq('property_id',f.property).eq('action','console.search.saved')).data!;expect(actions).toHaveLength(1);expect(JSON.stringify(actions)).not.toContain('Needle');expect(actions[0].training_eligible).toBe(false);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('search-mobile.png')});await page.keyboard.press('Escape');await expect(dialog(page)).toHaveCount(0);await expect(page.getByRole('button',{name:'Search console'})).toBeFocused();
})
test('lost query and selected-source responses recover once with original historical text',async({page,fixture:f})=>{
 const document=randomUUID();sql(`INSERT INTO public.documents(id,property_id,content,metadata)VALUES('${document}','${f.property}','Exact private original Needle text.','{"title":"Retained source"}');`);await login(page,f);await page.route('**/api/search',async route=>{await route.fetch();await route.abort()});await search(page,'Needle','knowledge');await expect(dialog(page).getByRole('button',{name:'Check saved search request'})).toBeEnabled();await page.unroute('**/api/search');await page.reload();await page.getByRole('button',{name:'Search console'}).click();await dialog(page).getByRole('button',{name:'Check saved search request'}).click();await expect(results(page)).toContainText('1 matching records');expect((await f.db.from('console_search_commands').select('id').eq('property_id',f.property).contains('input',{operation:'search'})).data).toHaveLength(1);
 sql(`UPDATE public.documents SET content='Corrected current source text' WHERE id='${document}';`);await page.route('**/api/search',async route=>{await route.fetch();await route.abort()});await results(page).getByRole('button',{name:/Retained source/}).click();await expect(dialog(page).getByRole('button',{name:'Check saved search request'})).toBeEnabled();await page.unroute('**/api/search');await page.reload();await page.getByRole('button',{name:'Search console'}).click();await dialog(page).getByRole('button',{name:'Check saved search request'}).click();await expect(source(page)).toContainText('Exact private original Needle text.');await expect(source(page)).toContainText('current source changed');expect((await f.db.from('console_search_commands').select('id').eq('property_id',f.property).contains('input',{operation:'select'})).data).toHaveLength(1);await source(page).getByRole('button',{name:'Open stored knowledge text',exact:true}).click();await expect(page).toHaveURL(/dashboard\/community\?knowledgeGroup=/);await expect(page.getByRole('region',{name:'Saved knowledge inventory'})).toContainText('Corrected current source text',{timeout:30000});
})
test('selected lead outside the first table page opens its actual drawer',async({page,fixture:f})=>{
 const lead=randomUUID();sql(`INSERT INTO public.leads(property_id,first_name,last_name,source,status)SELECT '${f.property}','Recent',n::text,'widget','new'FROM generate_series(1,35)n;INSERT INTO public.leads(id,property_id,first_name,last_name,email,source,status,created_at,updated_at)VALUES('${lead}','${f.property}','Outside','First Page','outside@fixture.invalid','widget','new','2020-01-01','2020-01-01');`);await login(page,f);await search(page,'Outside','lead');await expect(results(page)).toContainText('1 matching records');await pick(page,'Outside First Page');await source(page).getByRole('button',{name:'Open lead',exact:true}).click();await expect(page).toHaveURL(new RegExp('lead='+lead));await expect(page.getByRole('heading',{name:'Lead Details',exact:true})).toBeVisible();await expect(page.getByText('outside@fixture.invalid',{exact:true}).last()).toBeVisible();
})
test('conversation and reviewed knowledge links open their exact saved resources',async({page,fixture:f})=>{
 sql(`INSERT INTO public.messages(conversation_id,role,content)VALUES('${f.conversation}','user','Distinct search message Needle.');`);const material=randomUUID();expect((await f.db.rpc('save_knowledge_material',{p_id:material,p_property_id:f.property,p_actor_id:f.id,p_input:{materialId:null,previousVersionId:null,title:'Needle reviewed source',content:'Retained reviewed material original.',reason:'Local search fixture'}})).error).toBeNull();await login(page,f);await search(page,'Distinct search message','conversation');await pick(page,'Conversation');await expect(source(page)).toContainText('Distinct search message Needle.');await source(page).getByRole('button',{name:'Open conversation',exact:true}).click();await expect(page).toHaveURL(new RegExp('conversation='+f.conversation));await expect(page.getByRole('region',{name:'Current conversation',exact:true})).toContainText('Distinct search message Needle.');await page.getByRole('button',{name:'Search console'}).click();await search(page,'Needle reviewed source','knowledge');await pick(page,'Needle reviewed source');await source(page).getByRole('button',{name:'Open knowledge source',exact:true}).click();await expect(page).toHaveURL(new RegExp('knowledgeSource='+material+'&knowledgeVersion='+material));await expect(page.getByText('Retained reviewed material original.',{exact:true}).first()).toBeVisible();
})
test('literal punctuation, failed access reads and unused cancellation are explicit',async({page,fixture:f})=>{
 sql(`INSERT INTO public.leads(property_id,first_name,last_name,source,status)VALUES('${f.property}','Literal%_,','(Original)','widget','new'),('${f.property}','LiteralOther','Original','widget','new');`);await page.route('**/api/search?**',r=>r.fulfill({status:503,json:{error:'Temporary saved search read failure'}}));await login(page,f);await expect(dialog(page).getByRole('alert')).toContainText('Temporary saved search read failure');await page.unroute('**/api/search?**');await dialog(page).getByRole('button',{name:'Retry search access'}).click();await search(page,'Literal%_, (Original)','lead');await expect(results(page)).toContainText('1 matching records');let body:Record<string,unknown>={};await page.route('**/api/search',async route=>{body=route.request().postDataJSON();await route.abort()});await search(page,'Cancelled search');await expect(dialog(page).getByRole('button',{name:'Cancel unused search request'})).toBeEnabled();await page.unroute('**/api/search');await dialog(page).getByRole('button',{name:'Cancel unused search request'}).click();await expect(dialog(page).getByRole('status')).toContainText('Unused search request closed');const late=await page.request.post('/api/search',{headers:{origin:new URL(baseURL).origin},data:body});expect(late.status()).toBe(200);expect((await late.json()).status).toBe('cancelled');await expect(results(page)).toHaveCount(0);
})
