import { expect, test as base } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID,createHash } from 'node:crypto'
import sharp from 'sharp'
import { execFileSync } from 'node:child_process'
const dbURL = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const local = ['127.0.0.1','localhost']
const client = () => createClient(dbURL, process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture = { property: string; lead: string; second: string; actor: string; privatePaths:string[]; db: ReturnType<typeof client> }
const test = base.extend<{ fixture: Fixture }>({ fixture: async ({}, provide) => {
 if(!dbURL || !local.includes(new URL(dbURL).hostname) || !local.includes(new URL(process.env.PLAYWRIGHT_BASE_URL || 'http://127.0.0.1:9430').hostname)) throw new Error('Isolated local test required')
 const db = client(), property = randomUUID(), lead = randomUUID(), second = randomUUID(), privatePaths:string[]=[]
 const check = async (promise: PromiseLike<{ error: unknown }>) => { const r = await promise; if(r.error)throw r.error }
 try {
  const actor = await db.from('profiles').select('id').eq('org_id','22222222-2222-2222-2222-222222222222').eq('role','admin').limit(1).single();if(actor.error)throw actor.error
  await check(db.from('properties').insert({ id: property, org_id: '22222222-2222-2222-2222-222222222222', name: 'ForgeStudio media browser fixture', property_type: 'multifamily' }))
  await check(db.from('leads').insert([{id:lead,property_id:property,first_name:'CRM One',email:'leadpulse-one@fixture.invalid',source:'referral'},{id:second,property_id:property,first_name:'CRM Two',source:'website form'}]))
  await provide({ property, lead, second, actor: actor.data.id, db, privatePaths })
 } finally {
  if(privatePaths.length){const removed=await db.storage.from('forgestudio-media-results').remove(privatePaths);if(removed.error)throw removed.error}
  const objects=await db.storage.from('property-assets').list(property+'/forgestudio/generated');if(objects.error)throw objects.error;if(objects.data?.length){const removed=await db.storage.from('property-assets').remove(objects.data.map(o=>property+'/forgestudio/generated/'+o.name));if(removed.error)throw removed.error}
  execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN; SET LOCAL session_replication_role=replica; UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${property}'; DELETE FROM public.property_vertical_profile_versions WHERE property_id='${property}'; SET LOCAL session_replication_role=origin; CREATE TEMP TABLE crm_fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${property}'; CREATE TEMP TABLE crm_fixture_leads ON COMMIT DROP AS SELECT id FROM public.leads WHERE property_id='${property}'; UPDATE public.leads SET property_id=NULL WHERE property_id='${property}'; DELETE FROM public.properties WHERE id='${property}'; DELETE FROM public.shared_jobs WHERE id IN (SELECT id FROM crm_fixture_jobs); DELETE FROM public.leads WHERE id IN (SELECT id FROM crm_fixture_leads); COMMIT;`,stdio:['pipe','pipe','pipe']})
  expect((await db.from('properties').select('id').eq('id', property)).data).toHaveLength(0)
  expect((await db.from('forgestudio_media_requests').select('id').eq('property_id',property)).data).toHaveLength(0)
  expect((await db.from('forgestudio_media_receipts').select('id').eq('property_id',property)).data).toHaveLength(0)
 }
} })
test.beforeEach(async ({page}) => { await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/) })


async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const r=await f.db.rpc(name,args);if(r.error)throw r.error;return r.data}



const media=(page:import('@playwright/test').Page)=>page.getByRole('region',{name:'Saved media requests'})
async function openLibrary(page:import('@playwright/test').Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.route('**/api/cron/process-forgestudio-media',()=>{throw new Error('Browser fixtures must never invoke a model worker')});await page.goto('/dashboard/forgestudio?tab=assets');await expect(media(page)).toBeVisible()}
const request=(name:string)=>({modality:'image',tier:'final',prompt:'Generate abstract geometric campaign artwork with no property claims',aspectRatio:'1:1',name,altText:'Abstract campaign artwork',maxCostUsd:1})
async function seed(f:Fixture,name:string){const id=randomUUID();expect((await rpc(f,'begin_forgestudio_media',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_input:{request:request(name),model:'fixture/image',estimatedCostUsd:.04,modelPolicyVersion:'fixture'}})).state).toBe('saved');return id}
async function intent(f:Fixture,id:string){const token=randomUUID();expect((await f.db.from('forgestudio_media_requests').update({state:'claimed',claim_token:token,worker:'browser-fixture',lease_expires_at:new Date(Date.now()+600000).toISOString()}).eq('id',id).eq('property_id',f.property)).error).toBeNull();expect((await rpc(f,'advance_forgestudio_media',{p_id:id,p_claim_token:token,p_action:'model_intent',p_payload:{}})).state).toBe('proceed_once');return token}
async function result(f:Fixture,id:string,token:string){const bytes=await sharp({create:{width:80,height:60,channels:3,background:'#7c3aed'}}).png().toBuffer(),manifest={contentHash:createHash('sha256').update(bytes).digest('hex'),size:bytes.length,mimeType:'image/png',extension:'png',width:80,height:60};expect((await rpc(f,'advance_forgestudio_media',{p_id:id,p_claim_token:token,p_action:'result_manifest',p_payload:manifest})).state).toBe('saved');const path=`${f.property}/media/${id}/result`;expect((await f.db.storage.from('forgestudio-media-results').upload(path,bytes,{contentType:'image/png',upsert:false})).error).toBeNull();f.privatePaths.push(path);return manifest}

test('a lost media request and stop reply recover one decision with generation paused',async({page,fixture},info)=>{
 await openLibrary(page,fixture);await expect(media(page).getByText('Generation is paused.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Generate media',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Generate media'});await dialog.getByLabel('Asset name',{exact:true}).fill('Saved campaign artwork');await dialog.getByLabel('Generation instructions').fill('Generate abstract campaign artwork with no invented property claims');await dialog.getByLabel('Image or video description').fill('Abstract campaign artwork');let lost=true;await page.route('**/api/forgestudio/media-jobs',async route=>{if(route.request().method()==='POST'&&lost){lost=false;expect((await route.fetch()).status()).toBe(202);await route.abort('connectionreset')}else await route.continue()});await dialog.getByRole('button',{name:'Save generation request'}).click();await expect(dialog.getByRole('alert')).toBeVisible();await dialog.getByRole('button',{name:'Save generation request'}).click();await expect(dialog).not.toBeVisible();const row=media(page).getByRole('article',{name:'Saved campaign artwork'});await expect(row).toBeVisible();expect((await fixture.db.from('forgestudio_media_requests').select('id,state').eq('property_id',fixture.property)).data).toHaveLength(1);await row.getByLabel('Reason for Saved campaign artwork').fill('Stop this paused test request');let lostStop=true;await page.route('**/api/forgestudio/media-jobs',async route=>{if(route.request().method()==='PATCH'&&lostStop){lostStop=false;expect((await route.fetch()).status()).toBe(200);await route.abort('connectionreset')}else await route.continue()});await row.getByRole('button',{name:'Stop this request'}).click();await expect(media(page).getByRole('alert')).toBeVisible();await row.getByRole('button',{name:'Stop this request'}).click();await expect(row.getByText('Stopped.',{exact:false})).toBeVisible();expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','studio.media.stopped')).data).toHaveLength(1);expect((await fixture.db.from('forgestudio_media_receipts').select('id').eq('property_id',fixture.property).eq('kind','model_intent')).data).toHaveLength(0);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await media(page).screenshot({path:info.outputPath('forgestudio-media-mobile.png')})
})

test('a saved generated file recovers after reload and a lost acknowledgement without a model call',async({page,fixture})=>{
 const id=await seed(fixture,'Recover generated background'),token=await intent(fixture,id),manifest=await result(fixture,id,token);await openLibrary(page,fixture);await page.reload();const row=media(page).getByRole('article',{name:'Recover generated background'});await expect(row.getByRole('button',{name:'Recover saved file'})).toBeVisible();await row.getByLabel('Reason for Recover generated background').fill('Verified the same saved result after an interrupted library save');let lost=true;await page.route('**/api/forgestudio/media-jobs',async route=>{if(route.request().method()==='PATCH'&&lost){lost=false;expect((await route.fetch()).status()).toBe(200);await route.abort('connectionreset')}else await route.continue()});await row.getByRole('button',{name:'Recover saved file'}).click();await expect(media(page).getByRole('alert')).toBeVisible();await row.getByRole('button',{name:'Recover saved file'}).click();await expect(row.getByText('Saved in the asset library for usage review.')).toBeVisible();const asset=(await fixture.db.from('content_assets').select('*').eq('id',id).single()).data!;expect(asset.approval_status).toBe('pending');expect(asset.content_hash).toBe(manifest.contentHash);expect((await fixture.db.from('forgestudio_media_receipts').select('id').eq('request_id',id).eq('kind','model_intent')).data).toHaveLength(1);expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','studio.media.completed')).data).toHaveLength(1);expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','studio.media.recovered')).data).toHaveLength(1);const stored=await fixture.db.storage.from('property-assets').download(asset.storage_path!);expect(stored.error).toBeNull();expect(createHash('sha256').update(Buffer.from(await stored.data!.arrayBuffer())).digest('hex')).toBe(manifest.contentHash)
})

test('stopped model work retains a late private result without adding it to the library',async({page,fixture})=>{
 const id=await seed(fixture,'Stop running artwork'),token=await intent(fixture,id);await openLibrary(page,fixture);const row=media(page).getByRole('article',{name:'Stop running artwork'});await row.getByLabel('Reason for Stop running artwork').fill('Stop this artwork before saving a result');await row.getByRole('button',{name:'Stop this request'}).click();await expect(row.getByText('Stopped.',{exact:false})).toBeVisible();await result(fixture,id,token);await media(page).getByRole('button',{name:'Reload media requests'}).click();await expect(row.getByText('Stopped.',{exact:false})).toBeVisible();await expect(row.getByRole('button',{name:'Recover saved file'})).toHaveCount(0);expect((await fixture.db.from('content_assets').select('id').eq('id',id)).data).toHaveLength(0);expect((await fixture.db.from('forgestudio_media_requests').select('state,result_manifest').eq('id',id).single()).data?.state).toBe('stopped')
})

test('media request pagination, stale decisions and failed reads remain recoverable',async({page,fixture})=>{
 const ids=[];for(let i=0;i<32;i++)ids.push(await seed(fixture,'Artwork '+String(i).padStart(2,'0')));await openLibrary(page,fixture);await expect(media(page).getByRole('article')).toHaveCount(30);await media(page).getByRole('button',{name:'Load more media requests'}).click();await expect(media(page).getByRole('article')).toHaveCount(32);const row=media(page).getByRole('article',{name:'Artwork 00',exact:true});await row.getByLabel('Reason for Artwork 00').fill('Stop this queued fixture artwork');expect((await fixture.db.from('forgestudio_media_requests').update({updated_at:new Date().toISOString()}).eq('id',ids[0])).error).toBeNull();await row.getByRole('button',{name:'Stop this request'}).click();await expect(media(page).getByRole('alert')).toHaveText('This media request changed. Reload its saved status before deciding.');await page.route('**/api/forgestudio/media-jobs?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved media history unavailable'})}));await media(page).getByRole('button',{name:'Reload media requests'}).click();await expect(media(page).getByRole('alert')).toHaveText('Saved media history unavailable');await page.unroute('**/api/forgestudio/media-jobs?*');await media(page).getByRole('button',{name:'Reload media requests'}).click();await expect(media(page).getByRole('alert')).toHaveCount(0);await media(page).getByRole('button',{name:'Load more media requests'}).click();await row.getByRole('button',{name:'Stop this request'}).click();await expect(row.getByText('Stopped.',{exact:false})).toBeVisible()
})
