import { expect, test as base } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const local = ['127.0.0.1','localhost']
const client = () => createClient(dbURL, process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture = { otherProperty:string; property: string; lead: string; second: string; actor: string; db: ReturnType<typeof client> }
const test = base.extend<{ fixture: Fixture }>({ fixture: async ({}, provide) => {
 if(!dbURL || !local.includes(new URL(dbURL).hostname) || !local.includes(new URL(process.env.PLAYWRIGHT_BASE_URL || 'http://127.0.0.1:9430').hostname)) throw new Error('Isolated local test required')
 const db = client(), property = randomUUID(), otherProperty=randomUUID(), lead = randomUUID(), second = randomUUID()
 const check = async (promise: PromiseLike<{ error: unknown }>) => { const r = await promise; if(r.error)throw r.error }
 try {
  const actor = await db.from('profiles').select('id').eq('org_id','22222222-2222-2222-2222-222222222222').eq('role','admin').limit(1).single();if(actor.error)throw actor.error
  await check(db.from('properties').insert({ id: property, org_id: '22222222-2222-2222-2222-222222222222', name: 'ForgeStudio renewal browser fixture', property_type: 'multifamily' }))
  await check(db.from('leads').insert([{id:lead,property_id:property,first_name:'CRM One',email:'leadpulse-one@fixture.invalid',source:'referral'},{id:second,property_id:property,first_name:'CRM Two',source:'website form'}]))
  await check(db.from('properties').insert({id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ForgeStudio renewal browser fixture'}))
  await provide({ otherProperty, property, lead, second, actor: actor.data.id, db })
 } finally {
  for(const cleanupProperty of [property,otherProperty]){
  execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN; SET LOCAL session_replication_role=replica; UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${cleanupProperty}'; DELETE FROM public.property_vertical_profile_versions WHERE property_id='${cleanupProperty}'; SET LOCAL session_replication_role=origin; CREATE TEMP TABLE crm_fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${cleanupProperty}'; CREATE TEMP TABLE crm_fixture_leads ON COMMIT DROP AS SELECT id FROM public.leads WHERE property_id='${cleanupProperty}'; UPDATE public.leads SET property_id=NULL WHERE property_id='${cleanupProperty}'; DELETE FROM public.properties WHERE id='${cleanupProperty}'; DELETE FROM public.shared_jobs WHERE id IN (SELECT id FROM crm_fixture_jobs); DELETE FROM public.leads WHERE id IN (SELECT id FROM crm_fixture_leads); COMMIT;`,stdio:['pipe','pipe','pipe']})
  expect((await db.from('properties').select('id').eq('id', property)).data).toHaveLength(0)
  expect((await db.from('forgestudio_renewals').select('id').eq('property_id',property)).data).toHaveLength(0)
  expect((await db.from('social_attribution_events').select('id').eq('property_id',property)).data).toHaveLength(0)
  }
 }
} })
test.beforeEach(async ({page}) => { await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/) })
async function openConnections(page:import('@playwright/test').Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/forgestudio?tab=connections');await expect(page.getByRole('heading',{name:'Connected accounts',exact:true})).toBeVisible();await expect(page.getByText('Loading saved accounts…')).toHaveCount(0)}
async function authorization(f:Fixture){const id=randomUUID();const call=async(name:string,args:Record<string,unknown>)=>{const r=await f.db.rpc(name,args);if(r.error)throw r.error;return r.data};const payload={platform:'facebook',credentialFingerprint:'a'.repeat(64),redirectUri:'http://localhost/callback',scopes:['pages_show_list','pages_read_engagement','pages_manage_posts']};await call('begin_forgestudio_authorization',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_payload:payload,p_credentials:{appId:'fixture-app',appSecretEncrypted:'encv1:fixture-secret'}});const claimed=await call('claim_forgestudio_authorization',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_platform:'facebook',p_code_hash:'b'.repeat(64),p_credential_fingerprint:'a'.repeat(64)});expect(claimed.state).toBe('exchange_once');await call('finish_forgestudio_authorization',{p_id:id,p_claim_token:claimed.claimToken,p_result:{status:'observed',observedAt:new Date().toISOString(),accounts:['first','second'].map(accountId=>({accountId,accountName:`Candidate ${accountId}`,platform:'facebook',accessTokenEncrypted:'encv1:fixture-access',pageAccessTokenEncrypted:'encv1:fixture-page',pageId:accountId,scopes:payload.scopes,expiresAt:new Date(Date.now()+86400_000).toISOString(),permissionEvidence:{source:'provider_response',expiryKnown:true}}))}});return id}

async function savedConnection(f:Fixture){const authorizationId=await authorization(f);const r=await f.db.rpc('apply_forgestudio_authorization',{p_id:randomUUID(),p_property_id:f.property,p_actor_id:f.actor,p_payload:{authorizationId,expectedVersion:2,accountIds:['first'],reason:'Review renewal fixture account'}});if(r.error)throw r.error;expect(r.data.state).toBe('saved');return r.data.connectionIds[0] as string}
async function startRenewal(f:Fixture,id:string,requestId=randomUUID(),reason='Renew saved fixture access'){const r=await f.db.rpc('begin_forgestudio_renewal',{p_id:requestId,p_property_id:f.property,p_actor_id:f.actor,p_payload:{connectionId:id,expectedVersion:1,reason},p_credential_fingerprint:'a'.repeat(64),p_credentials:{appId:'fixture-app',appSecretEncrypted:'encv1:fixture-secret',redirectUri:'http://localhost/callback'}});if(r.error)throw r.error;expect(r.data.state).toBe('exchange_once');return{id:requestId,claim:r.data.claimToken}}

test('renewal is paused while safe history retains unconfirmed access and private credentials stay hidden',async({page,fixture},info)=>{
 const id=await savedConnection(fixture);await openConnections(page,fixture);await page.getByLabel('Reason for account decision').fill('Renew exact saved account');await expect(page.getByRole('button',{name:'Renew saved access for Candidate first',exact:true})).toBeDisabled()
 const blocked=await page.request.post('/api/forgestudio/social/renewal',{data:{propertyId:fixture.property,requestId:randomUUID(),connectionId:id,expectedVersion:1,reason:'Renew exact saved account'}});expect(blocked.status()).toBe(503);expect(await blocked.text()).toContain('paused');expect((await fixture.db.from('forgestudio_renewals').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
 const renewal=await startRenewal(fixture,id);await page.getByRole('button',{name:'Reload connections'}).click();await expect(page.getByRole('region',{name:'Access renewal history'})).toContainText('Renewal started; result unconfirmed');await expect(page.getByText('Access renewal started — awaiting a saved result',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Renew saved access for Candidate first',exact:true})).toHaveCount(0)
 const response=await page.request.get(`/api/forgestudio/social/renewal?propertyId=${fixture.property}`);const text=await response.text();expect(text).not.toContain('encv1:');expect(text).not.toContain('claim_token');expect(text).not.toContain('credentials')
 const replay=await page.request.post('/api/forgestudio/social/renewal',{data:{propertyId:fixture.property,requestId:renewal.id,connectionId:id,expectedVersion:1,reason:'Renew saved fixture access'}});expect(replay.status()).toBe(202);expect((await replay.json()).state).toBe('exchanging');expect((await fixture.db.from('forgestudio_renewals').select('id').eq('connection_id',id)).data).toHaveLength(1)
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('region',{name:'Access renewal history'}).screenshot({path:info.outputPath('renewal-mobile.png')})
})

test('unconfirmed rotation remains held after reload with a recorded provider outcome',async({page,fixture})=>{
 const id=await savedConnection(fixture),r=await startRenewal(fixture,id);const saved=await fixture.db.rpc('finish_forgestudio_renewal',{p_id:r.id,p_claim_token:r.claim,p_result:{status:'uncertain',observedAt:new Date().toISOString(),accounts:[],reason:'Simulated lost provider reply'}});if(saved.error)throw saved.error;expect(saved.data.renewalState).toBe('held');await openConnections(page,fixture);const history=page.getByRole('region',{name:'Access renewal history'});await expect(history).toContainText('New authorization required');await expect(page.getByText('Access renewal unconfirmed — authorize again',{exact:true})).toBeVisible();await page.reload();await expect(history).toContainText('Start fresh authorization.')
 expect((await fixture.db.from('shared_action_events').select('action,phase').eq('property_id',fixture.property).eq('action','studio.credentials.renewal_completed')).data).toEqual([{action:'studio.credentials.renewal_completed',phase:'failed'}]);expect((await fixture.db.from('social_publications').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
})

test('renewal history failures can be reloaded and a cursor from another property is rejected',async({page,fixture})=>{
 const id=await savedConnection(fixture),r=await startRenewal(fixture,id);await page.route('**/api/forgestudio/social/renewal?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved renewal history unavailable'})}));await openConnections(page,fixture);await expect(page.getByRole('alert').filter({hasText:'Saved renewal history unavailable'})).toBeVisible();await page.unroute('**/api/forgestudio/social/renewal?*');await page.getByRole('button',{name:'Reload connections'}).click();await expect(page.getByRole('region',{name:'Access renewal history'})).toContainText('Renewal started; result unconfirmed')
 const bad=await page.request.get(`/api/forgestudio/social/renewal?propertyId=${fixture.otherProperty}&cursor=${r.id}`);expect(bad.status()).toBe(409);expect(await bad.text()).not.toContain(fixture.property)
})
