import {expect,test as base,type Page} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {execFileSync} from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||'',client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={db:ReturnType<typeof client>;property:string;other:string;document:string}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),other=randomUUID(),document=randomUUID()
 try{
  expect((await db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'Knowledge inventory browser fixture'},{id:other,org_id:'22222222-2222-2222-2222-222222222222',name:'Other knowledge inventory browser fixture'}])).error).toBeNull()
  expect((await db.from('knowledge_sources').insert(Array.from({length:25},(_,i)=>({property_id:property,source_type:'manual',source_name:`Inventory source ${i}`,status:i===0?'failed':'completed',documents_created:999,extracted_data:{ingestion_run_id:`run-${i}`},last_synced_at:'2026-09-21T12:00:00Z',error_message:i===0?'Recorded fixture import failure':null})))).error).toBeNull()
  expect((await db.from('documents').insert([
   ...Array.from({length:25},(_,i)=>({id:i===0?document:randomUUID(),property_id:property,content:`Exact original large source chunk ${i+1}`,metadata:{source:'pasted_text',title:'Large saved run',ingestion_run_id:'large-fixture-run',chunk_index:i}})),
   ...Array.from({length:25},(_,i)=>({id:randomUUID(),property_id:property,content:`Separate source ${i}`,metadata:{source:'pasted_text',title:`Separate saved run ${i}`,ingestion_run_id:`run-${i}`,chunk_index:0}})),
   {id:randomUUID(),property_id:property,content:'Legacy source content',metadata:{source:'pasted_text',title:'Legacy retained material'}},
   {id:randomUUID(),property_id:property,content:'Other legacy source content',metadata:{source:'pasted_text',title:'Other legacy retained material'}},
   {id:randomUUID(),property_id:property,content:'x'.repeat(12001),metadata:{}}
  ])).error).toBeNull()
  expect((await db.from('property_units').insert({property_id:property,org_id:'22222222-2222-2222-2222-222222222222',canonical_key:'read-only-floorplan',unit_type:'Read-only floorplan fixture',bedrooms:0,bathrooms:1,rent_min:0,rent_max:0})).error).toBeNull()
  await provide({db,property,other,document})
 }finally{for(const id of[property,other]){execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${id}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${id}';SET LOCAL session_replication_role=origin;DELETE FROM public.properties WHERE id='${id}';COMMIT;`,stdio:['pipe','pipe','pipe']});for(const table of['documents','knowledge_sources','property_units','shared_action_events'])expect((await db.from(table).select('*',{count:'exact',head:true}).eq('property_id',id)).count).toBe(0)}}
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})
async function open(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/community');await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();return page.getByRole('region',{name:'Saved knowledge inventory'})}
test('complete source and material paging retains separate runs and exact addressable chunk previews',async({page,fixture},info)=>{
 const writes:string[]=[];await page.route(/\/api\/(?:brandforge\/analyze-existing|properties\/sync-units-to-kb|cron\/knowledge-refresh)/,r=>{writes.push(r.request().url());return r.abort()})
 const inventory=await open(page,fixture);await expect(inventory).toContainText('Showing 20 of 25 source records.');await inventory.getByRole('button',{name:'Load more sources'}).click();await expect(inventory).toContainText('Showing 25 of 25 source records.');await expect(inventory).toContainText('Recorded fixture import failure');await expect(inventory).toContainText('Reported chunks: 999');await inventory.getByRole('button',{name:'Stored material',exact:true}).click();await expect(inventory).toContainText('Showing 20 of 29 material groups.');await inventory.getByRole('button',{name:'Load more material'}).click();await expect(inventory).toContainText('Showing 29 of 29 material groups.');await expect(inventory).toContainText('Legacy grouping by source label and title; original file identity is not verified.')
 await inventory.getByRole('listitem').filter({has:page.getByRole('heading',{name:'Large saved run',exact:true})}).getByRole('button',{name:'Inspect stored chunks'}).click();await expect(inventory).toContainText('Showing 20 of 25 text chunks.');await expect(inventory).toContainText('Exact original large source chunk 1');await inventory.getByRole('button',{name:'Load more chunks'}).click();await expect(inventory).toContainText('Showing 25 of 25 text chunks.');await expect(inventory).toContainText('Exact original large source chunk 25');await expect(page).toHaveURL(/knowledgeGroup=/)
 await page.reload();await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await expect(page.getByRole('region',{name:'Saved knowledge inventory'})).toContainText('Exact original large source chunk 1');await page.setViewportSize({width:390,height:844});await page.getByRole('region',{name:'Saved knowledge inventory'}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('knowledge-inventory-mobile.png')});expect(writes).toEqual([]);expect((await fixture.db.from('documents').select('*',{count:'exact',head:true}).eq('property_id',fixture.property)).count).toBe(53)
})
test('changed inventory holds paging and failed reads stay unavailable until an explicit retry',async({page,fixture})=>{
 const inventory=await open(page,fixture);await expect(inventory).toContainText('Showing 20 of 25 source records.');expect((await fixture.db.from('documents').update({content:'New saved source version'}).eq('id',fixture.document)).error).toBeNull();await inventory.getByRole('button',{name:'Load more sources'}).click();await expect(inventory.getByRole('alert')).toContainText('Saved knowledge changed');await expect(inventory).toContainText('The displayed page is from the earlier read.');await expect(inventory.getByRole('button',{name:'Load more sources'})).toBeDisabled();await inventory.getByRole('button',{name:'Retry reading knowledge'}).click();await expect(inventory.getByRole('alert')).toHaveCount(0)
 await page.route('**/api/community/knowledge-inventory?*',r=>r.fulfill({status:503,json:{error:'Fixture inventory outage'}}));await inventory.getByRole('button',{name:'Reload inventory'}).click();await expect(inventory.getByRole('alert')).toContainText('Fixture inventory outage');await expect(inventory.getByText('No source records in this property.')).toHaveCount(0);await expect(inventory.getByRole('list')).toHaveCount(0);await page.unroute('**/api/community/knowledge-inventory?*');await inventory.getByRole('button',{name:'Retry reading knowledge'}).click();await expect(inventory).toContainText('Showing 20 of 25 source records.')
})
test('selected material cannot cross a property switch and denied reads do not show another property material',async({page,fixture})=>{
 const inventory=await open(page,fixture);await inventory.getByRole('button',{name:'Stored material',exact:true}).click();await inventory.getByRole('button',{name:'Inspect stored chunks'}).first().click();await expect(page).toHaveURL(/knowledgeGroup=/);await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.other);await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();const next=page.getByRole('region',{name:'Saved knowledge inventory'});await expect(next.getByRole('alert')).toContainText('unavailable in the selected property');await expect(next.getByRole('list')).toHaveCount(0);await next.getByRole('button',{name:'Source records',exact:true}).click();await expect(next).toContainText('No source records in this property.');await expect(next).not.toContainText('Inventory source')
 const hidden=await page.request.get('/api/community/knowledge-inventory?propertyId=ffffffff-ffff-4fff-8fff-ffffffffffff');expect(hidden.status()).toBe(403);expect(await hidden.json()).not.toHaveProperty('items')
})
