import {expect,test as base,type Page,type Locator} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID,createHash} from 'node:crypto'
import {execFileSync} from 'node:child_process'
import {readFile} from 'node:fs/promises'
const org='22222222-2222-2222-2222-222222222222',actor='11111111-1111-1111-1111-111111111111',dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||'',client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={db:ReturnType<typeof client>;property:string;other:string}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),other=randomUUID()
 try{expect((await db.from('properties').insert([{id:property,org_id:org,name:'Website capture browser fixture'},{id:other,org_id:org,name:'Other website capture browser fixture'}])).error).toBeNull();expect((await db.from('property_chatbot_contexts').insert({property_id:property,status:'current',requires_review:false,context_markdown:'Earlier context',last_generated_at:new Date().toISOString()})).error).toBeNull();await provide({db,property,other})}
 finally{for(const id of[property,other]){
  execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;CREATE TEMP TABLE fixture_contexts AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${id}';CREATE TEMP TABLE fixture_jobs AS SELECT id FROM public.shared_jobs WHERE property_id='${id}';SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${id}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${id}';SET LOCAL session_replication_role=origin;DELETE FROM public.properties WHERE id='${id}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of['knowledge_web_captures','knowledge_web_decisions','knowledge_web_links','knowledge_materials','knowledge_material_versions','documents','shared_action_events'])expect((await db.from(table).select('*',{count:'exact',head:true}).eq('property_id',id)).count).toBe(0)
 }}
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})
test.setTimeout(180000)
async function open(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/community');await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();const w=page.getByRole('region',{name:'Reviewed website captures'});await expect(w).toContainText('Showing 0 of 0 website captures.');await expect(w).toContainText('Website fetching is paused.');return w}
async function reason(w:Locator){await w.getByLabel('Reason for this website decision',{exact:true}).fill('Review exact synthetic website source')}
async function fields(w:Locator){await w.getByLabel('Capture title',{exact:true}).fill('Retained website policy');await w.getByLabel('Public page address',{exact:true}).fill('https://example.invalid/policy');await reason(w)}
async function request(w:Locator){await w.getByRole('button',{name:'Add website capture'}).click();await fields(w);await w.getByRole('button',{name:'Save website capture request'}).click();await expect(w.getByLabel('Selected website capture')).toContainText('Capture status: queued')}
async function latest(f:Fixture){const r=await f.db.from('knowledge_web_captures').select('*').eq('property_id',f.property).order('capture_sequence',{ascending:false}).limit(1).single();expect(r.error).toBeNull();return r.data!}
async function receipt(f:Fixture,id:string,body='\uFEFFOriginal exact page.\r\nFull Unicode 🏡',token?:string){if(!token){const claim=await f.db.rpc('claim_knowledge_web_capture',{p_id:id});expect(claim.error).toBeNull();expect(claim.data.state).toBe('invoke_once');token=claim.data.claimToken}const value={recipe:'public-utf8-html-v1',complete:true,requestedUrl:'https://example.invalid/policy',finalUrl:'https://example.invalid/final',contentType:'text/plain; charset=utf-8',statusCode:200,fetchedAt:new Date().toISOString(),body,bodyHash:createHash('sha256').update(body).digest('hex'),text:body,limitations:['Synthetic local receipt; no website was contacted.']};const r=await f.db.rpc('record_knowledge_web_capture',{p_id:id,p_claim_token:token,p_receipt:value});expect(r.error).toBeNull();return r.data}
async function accept(w:Locator){await reason(w);await w.getByRole('checkbox',{name:'I reviewed this exact original, extracted text, correction and destination source.'}).check();await w.getByRole('button',{name:'Save reviewed website text'}).click();await expect(w.getByRole('link',{name:'Open reviewed website text'})).toBeVisible()}

test('lost capture reply recovers a paused request, exact private original download and reviewed source ancestry',async({page,fixture},info)=>{
 const w=await open(page,fixture);let lost=false;await page.route('**/api/knowledge/websites',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='capture'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await w.getByRole('button',{name:'Add website capture'}).click();await fields(w);await w.getByRole('button',{name:'Save website capture request'}).click();await expect(w).toContainText('A previous capture website decision is unconfirmed.');expect(await page.evaluate(id=>sessionStorage.getItem('p11.web.pending.v1:'+id),fixture.property)).not.toContain('example.invalid');await page.reload();await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await w.getByRole('button',{name:'Check saved website decision'}).click();await expect(w).toContainText('Capture status: queued');const capture=await latest(fixture);expect(capture.claim_token).toBeNull();expect((await fixture.db.from('knowledge_web_captures').select('*',{head:true,count:'exact'}).eq('property_id',fixture.property)).count).toBe(1)
 const body='\uFEFFOriginal exact page.\r\nFull Unicode 🏡';expect((await receipt(fixture,capture.id,body)).state).toBe('ready');await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w.getByLabel('Reviewed website text',{exact:true})).toHaveValue(body.replaceAll('\r\n','\n'));await w.getByText('Retained original response',{exact:true}).click();await expect(w.getByLabel('Exact website original')).toContainText('Full Unicode 🏡');await reason(w);const downloaded=page.waitForEvent('download');await w.getByRole('button',{name:'Download website original'}).click();const download=await downloaded;expect(await readFile((await download.path())!)).toEqual(Buffer.from(body))
 await w.getByLabel('Reviewed website text',{exact:true}).fill('Reviewed website correction retained explicitly.');await accept(w);expect((await fixture.db.from('documents').select('*',{head:true,count:'exact'}).eq('property_id',fixture.property)).count).toBe(0);expect((await fixture.db.from('shared_jobs').select('*',{head:true,count:'exact'}).eq('property_id',fixture.property)).count).toBe(0);const events=await fixture.db.from('shared_action_events').select('request,result,training_eligible').eq('property_id',fixture.property);expect(events.data!.every(e=>!e.training_eligible)).toBe(true);expect(JSON.stringify(events.data)).not.toContain('Original exact page')
 await w.getByRole('button',{name:'Website decision history'}).click();await expect(w).toContainText('Showing 3 of 3.');await page.setViewportSize({width:390,height:844});await w.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('website-capture-mobile.png')});await w.getByRole('link',{name:'Open reviewed website text'}).click();const material=page.getByRole('region',{name:'Reviewed knowledge sources'});await expect(material).toContainText('Reviewed website correction retained explicitly.');await expect(material.getByRole('link',{name:'Read retained capture'})).toBeVisible();await material.getByRole('link',{name:'Read retained capture'}).click();await expect(w.getByLabel('Selected website capture')).toContainText('reviewed text saved')
})
test('fresh capture replacement rejects a concurrent source edit and then retains a reviewed private revision',async({page,fixture})=>{
 const w=await open(page,fixture);await request(w);await receipt(fixture,(await latest(fixture)).id);await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w.getByLabel('Reviewed website text',{exact:true})).toBeVisible();await accept(w);const first=await latest(fixture);await w.getByRole('button',{name:'Request a new capture'}).click();await reason(w);await w.getByRole('button',{name:'Save website capture request'}).click();await expect(w).toContainText('Capture status: queued');const replacement=await latest(fixture);expect(replacement.parent_capture_id).toBe(first.id);await receipt(fixture,replacement.id,'New replacement exact text.');await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w.getByLabel('Reviewed website text',{exact:true})).toHaveValue('New replacement exact text.');const correction=randomUUID();expect((await fixture.db.rpc('save_knowledge_material',{p_id:correction,p_property_id:fixture.property,p_actor_id:actor,p_input:{materialId:first.material_id,previousVersionId:first.accepted_version_id,title:'Concurrent corrected source',content:'A concurrent operator correction.',reason:'Review concurrent source correction'}})).data.state).toBe('saved');await reason(w);await w.getByRole('checkbox',{name:'I reviewed this exact original, extracted text, correction and destination source.'}).check();await w.getByRole('button',{name:'Save reviewed website text'}).click();await expect(w.getByRole('alert')).toContainText('destination source changed');expect((await latest(fixture)).accepted_version_id).toBeNull();await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w.getByLabel('Reviewed website text',{exact:true})).toBeVisible();await accept(w);const versions=await fixture.db.from('knowledge_material_versions').select('content,previous_version_id').eq('property_id',fixture.property).order('version_sequence');expect(versions.data).toHaveLength(3);expect(versions.data![2]).toMatchObject({content:'New replacement exact text.',previous_version_id:correction});expect((await fixture.db.from('knowledge_materials').select('active_version_id').eq('id',first.material_id).single()).data?.active_version_id).toBeNull();await w.getByRole('button',{name:'Read earlier capture'}).click();await expect(page).toHaveURL(new RegExp('knowledgeCapture='+first.id));await expect(w.getByLabel('Selected website capture')).toContainText('reviewed text saved')
})
test('unused cancellation fences delayed requests and late replies stay attached to stopped captures',async({page,fixture})=>{
 const w=await open(page,fixture);let delayed:Record<string,unknown>|null=null;await page.route('**/api/knowledge/websites',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='capture'&&!delayed){delayed=route.request().postDataJSON();await route.abort('failed')}else await route.continue()});await w.getByRole('button',{name:'Add website capture'}).click();await fields(w);await w.getByRole('button',{name:'Save website capture request'}).click();await expect(w).toContainText('A previous capture website decision is unconfirmed.');await w.getByRole('button',{name:'Cancel unused website decision'}).click();await expect(w).toContainText('Unused website decision cancelled.');const copy=delayed as unknown as Record<string,unknown>,input={...copy};delete input.requestId;delete input.propertyId;delete input.operation;expect((await fixture.db.rpc('begin_knowledge_web_capture',{p_id:copy.requestId,p_property_id:fixture.property,p_actor_id:actor,p_input:input})).data.state).toBe('decision_cancelled');await page.unroute('**/api/knowledge/websites');await request(w);const c=await latest(fixture),claim=await fixture.db.rpc('claim_knowledge_web_capture',{p_id:c.id});expect(claim.data.state).toBe('invoke_once');await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w).toContainText('Capture status: running');await reason(w);await w.getByRole('button',{name:'Stop website capture'}).click();await expect(w).toContainText('Capture status: stopped');expect((await receipt(fixture,c.id,'Late exact complete response',claim.data.claimToken)).state).toBe('stopped');await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w.getByRole('button',{name:'Save reviewed website text'})).toHaveCount(0);expect((await latest(fixture)).receipt.text).toBe('Late exact complete response');expect((await fixture.db.from('knowledge_materials').select('*',{count:'exact',head:true}).eq('property_id',fixture.property)).count).toBe(0)
})
test('large complete page requires deliberate shorter text without truncating original evidence',async({page,fixture})=>{
 const w=await open(page,fixture);await request(w);const c=await latest(fixture),body='FULL BEGIN '+('Original complete policy. '.repeat(12000))+' COMPLETE END';expect((await receipt(fixture,c.id,body)).state).toBe('ready');await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w.getByLabel('Reviewed website text',{exact:true})).toHaveValue(body);await reason(w);await w.getByRole('checkbox',{name:'I reviewed this exact original, extracted text, correction and destination source.'}).check();await expect(w.getByRole('button',{name:'Save reviewed website text'})).toBeDisabled();await w.getByLabel('Reviewed website text',{exact:true}).fill('Deliberate concise correction based on the complete retained original.');await accept(w);expect((await latest(fixture)).receipt.body).toBe(body)
})
test('all captures remain reachable and unavailable reads or property switches clear private evidence',async({page,fixture})=>{
 const w=await open(page,fixture);expect((await fixture.db.from('knowledge_web_captures').insert(Array.from({length:24},(_,i)=>({id:randomUUID(),property_id:fixture.property,org_id:org,actor_id:actor,input:{title:'Website capture '+i,url:'https://example.invalid/policy',materialId:null,reason:'Synthetic page history'},input_hash:'fixture'})))).error).toBeNull();await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w).toContainText('Showing 20 of 24 website captures.');await w.getByRole('button',{name:'Load more website captures'}).click();await expect(w).toContainText('Showing 24 of 24 website captures.');await w.getByRole('button',{name:/^Website capture 0 /}).click();await expect(w.getByLabel('Selected website capture')).toBeVisible();await page.route('**/api/knowledge/websites?*',route=>route.fulfill({status:503,json:{error:'Fixture website reads unavailable'}}));await w.getByRole('button',{name:'Reload website captures'}).click();await expect(w.getByRole('alert')).toContainText('unavailable');await expect(w.getByLabel('Selected website capture')).toHaveCount(0);await page.unroute('**/api/knowledge/websites?*');await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.other);await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await expect(w).toContainText('Showing 0 of 0 website captures.');await expect(w.getByLabel('Selected website capture')).toHaveCount(0)
})
