import {expect,test as base,type Page}from '@playwright/test'
import {createClient}from '@supabase/supabase-js'
import {randomUUID}from 'node:crypto'
import {execFileSync}from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||'',client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;lead:string;otherLead:string;legacy:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),lead=randomUUID(),otherLead=randomUUID(),legacy=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'Lead activity browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'Other lead activity browser fixture'}]))
  await check(db.from('leads').insert([{id:lead,property_id:property,first_name:'Note',last_name:'Fixture',email:'notes@example.invalid',source:'manual',status:'new'},{id:otherLead,property_id:property,first_name:'Other',last_name:'Fixture',email:'other-notes@example.invalid',source:'manual',status:'new'}]))
  await check(db.from('lead_activities').insert({id:legacy,lead_id:lead,type:'note',description:'Earlier note with unknown author',created_at:null,metadata:{privateRaw:'Never display arbitrary metadata'}}))
  await provide({property,otherProperty,lead,otherLead,legacy,actor,db})
 }finally{
  await check(db.from('leads').delete().in('id',[lead,otherLead]))
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['lead_note_records','lead_note_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})
const panel=(page:Page)=>page.getByRole('region',{name:'Lead activity and notes',exact:true})
async function open(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/leads');await page.getByText('Note Fixture',{exact:true}).click();await page.getByRole('button',{name:'Activity',exact:true}).click();await expect(panel(page).getByRole('button',{name:'Reload timeline'})).toBeEnabled()}
async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const r=await f.db.rpc(name,args);expect(r.error).toBeNull();return r.data}
async function correct(page:Page,content:string){await panel(page).getByLabel('Corrected note',{exact:true}).fill(content);await panel(page).getByLabel('Reason for note change',{exact:true}).fill('Correct the recorded preference');await panel(page).getByRole('button',{name:'Save note correction',exact:true}).click()}
test('lost replies preserve one note and correction, with withdrawal, restoration and original history after reload',async({page,fixture},info)=>{
 await open(page,fixture);await expect(panel(page)).toContainText('Time not recorded');await expect(panel(page)).not.toContainText('Never display arbitrary metadata')
 let drop=true;await page.route(`**/api/leads/${fixture.lead}/activities`,async route=>{if(route.request().method()==='POST'&&drop){drop=false;const response=await route.fetch();expect(response.ok(),await response.text()).toBe(true);await route.abort('failed')}else await route.continue()})
 await panel(page).getByLabel('New internal note',{exact:true}).fill('Prefers a west-facing home');await panel(page).getByRole('button',{name:'Save internal note',exact:true}).click();await expect(panel(page).getByRole('alert')).toContainText('Failed to fetch');await panel(page).getByRole('button',{name:'Save internal note',exact:true}).click();await expect(panel(page)).toContainText('No message or CRM transfer was sent')
 let note=(await fixture.db.from('lead_note_records').select('id,version,original_activity').eq('lead_id',fixture.lead).single()).data!;expect(note.version).toBe(1);expect((await fixture.db.from('lead_note_decisions').select('id').eq('note_id',note.id)).data).toHaveLength(1)
 const row=panel(page).getByRole('listitem').filter({hasText:'Recorded operator note'});drop=true;await row.getByRole('button',{name:'Correct note',exact:true}).click();await correct(page,'Prefers an east-facing home');await expect(panel(page).getByRole('alert')).toContainText('Failed to fetch');await panel(page).getByRole('button',{name:'Save note correction',exact:true}).click();await expect(row).toContainText('Prefers an east-facing home');await page.unroute(`**/api/leads/${fixture.lead}/activities`)
 expect((await fixture.db.from('lead_note_decisions').select('id').eq('note_id',note.id)).data).toHaveLength(2)
 await row.getByRole('button',{name:'Withdraw note',exact:true}).click();await panel(page).getByLabel('Reason for note change',{exact:true}).fill('Withdraw an obsolete preference');await panel(page).getByRole('button',{name:'Confirm note withdrawal',exact:true}).click();await expect(row).toContainText('Note withdrawn');await expect(row).not.toContainText('Prefers an east-facing home');await page.reload();await page.getByText('Note Fixture',{exact:true}).click();await page.getByRole('button',{name:'Activity',exact:true}).click();await row.getByRole('button',{name:'Restore note',exact:true}).click();await panel(page).getByLabel('Reason for note change',{exact:true}).fill('Preference confirmed again');await panel(page).getByRole('button',{name:'Confirm note restoration',exact:true}).click();await expect(row).toContainText('Prefers an east-facing home')
 await row.getByRole('button',{name:'Open note history',exact:true}).click();const history=panel(page).getByRole('region',{name:'Note decision history'});await expect(history.locator('details')).toHaveCount(4);await history.locator('summary').filter({hasText:'Note corrected'}).click();await expect(history).toContainText('Prefers a west-facing home');await expect(history).toContainText('Prefers an east-facing home')
 note=(await fixture.db.from('lead_note_records').select('id,version,original_activity').eq('id',note.id).single()).data!;expect(note.version).toBe(4);expect((note.original_activity as{description:string}).description).toBe('Prefers a west-facing home');expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).like('action','lead.note.%')).data).toHaveLength(4)
 await page.setViewportSize({width:390,height:844});await panel(page).scrollIntoViewIfNeeded();expect(await panel(page).evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath('lead-note-mobile.png')})
})
test('stale edits fail visibly, legacy provenance survives correction, and every activity page remains available',async({page,fixture})=>{
 await open(page,fixture);const legacy=panel(page).getByRole('listitem').filter({hasText:'Earlier note with unknown author'});await legacy.getByRole('button',{name:'Correct note',exact:true}).click()
 const data=await rpc(fixture,'read_lead_activity',{p_property_id:fixture.property,p_lead_id:fixture.lead,p_actor_id:fixture.actor}),entry=data.activities.find((x:{id:string})=>x.id===fixture.legacy)
 await rpc(fixture,'save_lead_note',{p_id:randomUUID(),p_property_id:fixture.property,p_lead_id:fixture.lead,p_actor_id:fixture.actor,p_input:{action:'correct',noteId:entry.id,expectedVersion:entry.version,sourceHash:entry.sourceHash,content:'Concurrent reviewed correction',reason:'Another operator reviewed the original'}})
 await correct(page,'Stale attempted correction');await expect(panel(page).getByRole('alert')).toContainText('changed after it was displayed');await expect(panel(page).getByLabel('Corrected note',{exact:true})).toHaveValue('Stale attempted correction');await panel(page).getByRole('button',{name:'Reload timeline'}).click();await expect(panel(page)).toContainText('Concurrent reviewed correction');await expect(panel(page)).toContainText('Earlier note with recorded revisions');await expect(panel(page)).toContainText('Original author not recorded')
 expect((await page.request.post(`/api/leads/${fixture.lead}/activities`,{data:{type:'email_sent',description:'Forged delivery',propertyId:fixture.property}})).status()).toBe(400)
 expect((await fixture.db.from('lead_activities').insert(Array.from({length:25},(_,i)=>({lead_id:fixture.lead,type:'status_change',description:`Synthetic activity ${i+1}`,created_at:'2026-09-20T12:00:00Z'})))).error).toBeNull();await panel(page).getByRole('button',{name:'Reload timeline'}).click();await expect(panel(page)).toContainText('26 recorded activities');await expect(panel(page).getByRole('listitem')).toHaveCount(20);await panel(page).getByRole('button',{name:'Older activities'}).click();await expect(panel(page).getByRole('listitem')).toHaveCount(26);await expect(panel(page)).toContainText('Concurrent reviewed correction');expect((await fixture.db.from('lead_note_decisions').select('id').eq('lead_id',fixture.lead)).data).toHaveLength(1)
})
test('failed reads stay visible and delayed reads cannot cross lead or property changes',async({page,fixture})=>{
 await page.route(`**/api/leads/${fixture.lead}/activities?*`,r=>r.fulfill({status:503,json:{error:'Timeline temporarily unavailable'}}));await open(page,fixture);await expect(panel(page).getByRole('alert')).toContainText('Timeline temporarily unavailable');await expect(panel(page)).not.toContainText('No activity has been recorded');await expect(panel(page).getByRole('button',{name:'Save internal note'})).toBeDisabled();await page.unroute(`**/api/leads/${fixture.lead}/activities?*`);await panel(page).getByRole('button',{name:'Reload timeline'}).click();await expect(panel(page)).toContainText('Earlier note with unknown author')
 let release:()=>void=()=>{},start:()=>void=()=>{};let held=new Promise<void>(r=>{release=r}),started=new Promise<void>(r=>{start=r});await page.route(`**/api/leads/${fixture.lead}/activities?*`,async r=>{const response=await r.fetch();start();await held;await r.fulfill({response}).catch(()=>{})});await panel(page).getByRole('button',{name:'Reload timeline'}).click();await started;await page.getByRole('button',{name:'Close lead details'}).click();await page.getByText('Other Fixture',{exact:true}).click();await page.getByRole('button',{name:'Activity',exact:true}).click();release();await expect(panel(page)).toContainText('No activity has been recorded');await expect(panel(page)).not.toContainText('Earlier note with unknown author');await page.unroute(`**/api/leads/${fixture.lead}/activities?*`)
 await page.getByRole('button',{name:'Close lead details'}).click();await page.getByText('Note Fixture',{exact:true}).click();await page.getByRole('button',{name:'Activity',exact:true}).click();await expect(panel(page)).toContainText('Earlier note with unknown author');held=new Promise<void>(r=>{release=r});started=new Promise<void>(r=>{start=r});await page.route(`**/api/leads/${fixture.lead}/activities?*`,async r=>{const response=await r.fetch();start();await held;await r.fulfill({response}).catch(()=>{})});await panel(page).getByRole('button',{name:'Reload timeline'}).click();await started;await page.getByRole('button',{name:'Close lead details'}).click();await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);release();await expect(panel(page)).toHaveCount(0);await expect(page.getByText('Note Fixture',{exact:true})).toHaveCount(0)
})
