import {test as base,expect,type Page}from '@playwright/test'
import {createClient}from '@supabase/supabase-js'
import {randomUUID,createHash}from 'node:crypto'
import {execFileSync}from 'node:child_process'
const baseURL=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430',origin=new URL(baseURL).origin,url=process.env.NEXT_PUBLIC_SUPABASE_URL!,password='local-conversation-fixture-password'
const service=()=>createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})
function sql(input:string){return execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input,stdio:['pipe','pipe','pipe']})}
type Fixture={id:string;email:string;org:string;property:string;key:string;conversation:string;session:string;db:ReturnType<typeof service>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(url).hostname)||!['localhost','127.0.0.1'].includes(new URL(baseURL).hostname))throw new Error('Local disposable fixtures only')
 const db=service(),email='luma-conversation-browser-'+randomUUID()+'@p11.test',created=await db.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull();const id=created.data.user!.id,org=randomUUID(),property=randomUUID(),conversation=randomUUID(),session=randomUUID(),key='luma_conversation_'+randomUUID()
 try{sql(`BEGIN;INSERT INTO public.organizations(id,name)VALUES('${org}','Luma conversation browser fixture');SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id='${org}',role='admin' WHERE id='${id}';INSERT INTO public.properties(id,org_id,name)VALUES('${property}','${org}','Luma conversation fixture property');INSERT INTO public.lumaleasing_config(property_id,api_key,is_active)VALUES('${property}','${key}',true);INSERT INTO public.widget_sessions(id,property_id,last_activity_at)VALUES('${session}','${property}',clock_timestamp());INSERT INTO public.conversations(id,property_id,widget_session_id,channel)VALUES('${conversation}','${property}','${session}','widget');INSERT INTO public.messages(conversation_id,role,content)VALUES('${conversation}','user','Private original visitor question');COMMIT;`);await provide({id,email,org,property,key,conversation,session,db})}
 finally{sql(`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${property}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${property}';SET LOCAL session_replication_role=origin;DELETE FROM public.messages WHERE conversation_id IN(SELECT id FROM public.conversations WHERE property_id='${property}');DELETE FROM public.conversations WHERE property_id='${property}';DELETE FROM public.widget_sessions WHERE property_id='${property}';DELETE FROM public.properties WHERE id='${property}';SELECT set_config('p11.team_scope','${org}',true);UPDATE public.profiles SET org_id=NULL,role='viewer' WHERE org_id='${org}';DELETE FROM public.organizations WHERE id='${org}';COMMIT;`);expect((await db.auth.admin.deleteUser(id)).error).toBeNull()}
}})
test.setTimeout(120000)
const inbox=(p:Page)=>p.getByRole('region',{name:'Conversation inbox',exact:true}),current=(p:Page)=>p.getByRole('region',{name:'Current conversation',exact:true}),saved=(p:Page)=>p.getByRole('region',{name:'Saved conversation decision',exact:true})
async function login(p:Page,f:Fixture){await p.goto('/auth/login?redirect=%2Fdashboard%2Flumaleasing%3Ftab%3Dconversations');await p.getByLabel('Email address').fill(f.email);await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await expect(p).toHaveURL(/dashboard\/lumaleasing/,{timeout:30000});await expect(inbox(p)).toBeVisible()}
async function open(p:Page){await inbox(p).getByRole('button',{name:/Open conversation:/}).first().click();await expect(current(p).getByRole('button',{name:'Save transcript review'})).toBeEnabled()}
async function reason(p:Page){await current(p).getByLabel('Conversation decision reason',{exact:true}).fill('Private reviewed staff decision reason')}
async function takeover(p:Page){await reason(p);await current(p).getByRole('button',{name:'Take over conversation',exact:true}).click()}
async function read(f:Fixture){const r=await f.db.rpc('read_luma_conversations',{p_actor_id:f.id,p_property_id:f.property,p_conversation_id:f.conversation,p_kind:'messages'});expect(r.error).toBeNull();return r.data}
async function state(f:Fixture){const r=await f.db.from('conversations').select('is_human_mode,mode_revision,inbox_archived_at').eq('id',f.conversation).single();expect(r.error).toBeNull();return r.data!}
async function visitor(f:Fixture,content:string){const r=await f.db.rpc('save_luma_message_at_revision',{p_property_id:f.property,p_conversation_id:f.conversation,p_role:'user',p_content:content,p_mode_revision:null});expect(r.error).toBeNull();return r.data}
async function post(p:Page,f:Fixture,input:Record<string,unknown>){return p.request.post('/api/lumaleasing/admin/conversation-work',{headers:{origin},data:{id:randomUUID(),propertyId:f.property,expectedActorId:f.id,...input}})}
async function actualVisitor(p:Page,f:Fixture,content:string){expect((await state(f)).is_human_mode).toBe(true);return p.request.post('/api/lumaleasing/chat',{headers:{origin,'x-api-key':f.key},data:{requestId:randomUUID(),sessionId:f.session,messages:[{role:'user',content}]}})}
test('complete inbox and transcript pages preserve exact saved downloads and mobile layout',async({page,fixture:f},info)=>{
 sql(`INSERT INTO public.conversations(property_id,channel,created_at)SELECT '${f.property}','widget','2020-01-01'::timestamptz FROM generate_series(1,30);INSERT INTO public.messages(conversation_id,role,content,created_at)SELECT '${f.conversation}','user','Private source message '||n,clock_timestamp()+n*interval '1 second'FROM generate_series(1,31)n;`);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page,f);const list=inbox(page).getByRole('region',{name:'Saved conversations',exact:true});await expect(list).toContainText('31 conversations');await expect(list.getByRole('listitem')).toHaveCount(25);await list.getByRole('button',{name:'Next inbox page'}).click();await expect(list.getByRole('listitem')).toHaveCount(6);await list.getByRole('button',{name:'Previous inbox page'}).click();await open(page);await expect(current(page)).toContainText('32 messages');await current(page).getByRole('button',{name:'Next messages'}).click();await expect(current(page).getByRole('listitem')).toHaveCount(7,{timeout:30000});await current(page).getByRole('button',{name:'Save transcript review'}).click();await expect(saved(page)).toContainText('Original transcript at this decision: 32 messages');await visitor(f,'Private message arriving after saved review');await saved(page).getByRole('button',{name:'Prepare transcript download'}).click();await expect(inbox(page).getByRole('button',{name:'Download prepared transcript'})).toBeEnabled();const prepared=(await f.db.from('luma_conversation_commands').select('result').eq('property_id',f.property).contains('input',{operation:'export'})).data![0].result;const pending=page.waitForEvent('download');await inbox(page).getByRole('button',{name:'Download prepared transcript'}).click();const download=await pending,stream=await download.createReadStream(),chunks:Buffer[]=[];for await(const c of stream!)chunks.push(Buffer.from(c));const bytes=Buffer.concat(chunks);expect(createHash('sha256').update(bytes).digest('hex')).toBe(prepared.artifactHash);expect(JSON.parse(bytes.toString()).source.messages).toHaveLength(32);expect(bytes.toString()).not.toContain('arriving after saved review');await expect(inbox(page).getByRole('status')).toContainText('Browser download initiation recorded');await page.setViewportSize({width:390,height:844});await current(page).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('conversation-inbox-mobile.png')});expect(errors).toEqual([])
})
test('lost takeover and reply results recover once and the real widget reads the staff reply',async({page,fixture:f},info)=>{
 await login(page,f);await open(page);await page.route('**/api/lumaleasing/admin/conversation-work',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);await route.abort()});await takeover(page);await expect(inbox(page).getByRole('button',{name:'Check saved conversation request'})).toBeEnabled();expect((await state(f)).mode_revision).toBe(1);await page.unroute('**/api/lumaleasing/admin/conversation-work');await page.reload();await expect(inbox(page).getByRole('button',{name:'Check saved conversation request'})).toBeEnabled();await inbox(page).getByRole('button',{name:'Check saved conversation request'}).click();await expect(current(page).getByLabel('Reply to visitor')).toBeVisible();expect((await f.db.from('messages').select('id').eq('conversation_id',f.conversation).eq('role','system')).data).toHaveLength(1)
 await page.route('**/api/lumaleasing/admin/conversation-work',async route=>{await route.fetch();await route.abort()});await current(page).getByLabel('Reply to visitor').fill('Private saved staff response for the visitor.');await current(page).getByRole('button',{name:'Send staff reply'}).click();await expect(inbox(page).getByRole('button',{name:'Check saved conversation request'})).toBeEnabled();await page.unroute('**/api/lumaleasing/admin/conversation-work');await page.reload();await inbox(page).getByRole('button',{name:'Check saved conversation request'}).click();await expect(current(page)).toContainText('Private saved staff response for the visitor.');expect((await f.db.from('messages').select('id').eq('conversation_id',f.conversation).eq('content','Private saved staff response for the visitor.')).data).toHaveLength(1)
 const publicHistory=await page.request.get('/api/lumaleasing/session/history?sessionId='+f.session,{headers:{'x-api-key':f.key}});expect(publicHistory.status()).toBe(200);const history=await publicHistory.json();expect(history.messages.some((m:{content:string})=>m.content==='Private saved staff response for the visitor.')).toBe(true);expect(JSON.stringify(history)).not.toContain('staff decision reason');const publicReply=await actualVisitor(page,f,'A new fixture question for the team');expect(publicReply.status()).toBe(200);expect(await publicReply.json()).toMatchObject({isHumanMode:true,waitingForHuman:true});await current(page).getByRole('button',{name:'Refresh conversation'}).click();await reason(page);await current(page).getByRole('button',{name:'Return to assistant',exact:true}).click();await expect(current(page)).toContainText('The assistant controls this conversation.');expect((await state(f)).mode_revision).toBe(2);const late=await f.db.rpc('save_luma_message_at_revision',{p_property_id:f.property,p_conversation_id:f.conversation,p_role:'assistant',p_content:'Obsolete original provider answer',p_mode_revision:0});expect(late.data).toMatchObject({saved:false,stale:true,human:false});expect((await f.db.from('messages').select('id').eq('conversation_id',f.conversation).eq('content','Obsolete original provider answer')).data).toHaveLength(0);const events=(await f.db.from('shared_action_events').select('*').eq('property_id',f.property).like('action','luma.conversation.%')).data!;expect(events.every(e=>!e.training_eligible)).toBe(true);expect(JSON.stringify(events)).not.toContain('Private');expect(events.some(e=>e.service_principal==='lumaleasing.message_store'&&e.actor_id===null)).toBe(true);await page.screenshot({path:info.outputPath('conversation-recovered.png')})
})
test('stale transcript and unused cancellation preserve control and prevent a late reply',async({page,fixture:f})=>{
 await login(page,f);await open(page);await visitor(f,'New message arrived while staff was reading');await takeover(page);await expect(inbox(page).getByRole('alert')).toContainText('conversation changed');expect((await state(f)).is_human_mode).toBe(false);await expect(current(page).getByLabel('Conversation decision reason')).toHaveValue('Private reviewed staff decision reason');await inbox(page).getByRole('button',{name:'Cancel unused conversation request'}).click();await expect(inbox(page).getByRole('status')).toContainText('Unused conversation request closed');await current(page).getByRole('button',{name:'Refresh conversation'}).click();await takeover(page);await expect(current(page).getByLabel('Reply to visitor')).toBeVisible();let captured:Record<string,unknown>={};await page.route('**/api/lumaleasing/admin/conversation-work',async route=>{captured=route.request().postDataJSON();await route.abort()});await current(page).getByLabel('Reply to visitor').fill('This cancelled draft must not be sent.');await current(page).getByRole('button',{name:'Send staff reply'}).click();await expect(inbox(page).getByRole('button',{name:'Cancel unused conversation request'})).toBeEnabled();await page.unroute('**/api/lumaleasing/admin/conversation-work');await inbox(page).getByRole('button',{name:'Cancel unused conversation request'}).click();await expect(inbox(page).getByRole('status')).toContainText('Unused conversation request closed');const late=await page.request.post('/api/lumaleasing/admin/conversation-work',{headers:{origin},data:captured});expect((await late.json()).status).toBe('cancelled');expect((await f.db.from('messages').select('id').eq('conversation_id',f.conversation).eq('content','This cancelled draft must not be sent.')).data).toHaveLength(0)
})
test('archiving retains the transcript and an actual visitor message reopens the inbox',async({page,fixture:f})=>{
 await login(page,f);await open(page);await takeover(page);await expect(current(page).getByLabel('Reply to visitor')).toBeVisible();await reason(page);await current(page).getByRole('button',{name:'Archive conversation from inbox'}).click();await expect(inbox(page).getByRole('region',{name:'Saved conversations',exact:true})).toContainText('0 conversations');await inbox(page).getByLabel('Include archived conversations').check();await expect(inbox(page).getByRole('region',{name:'Saved conversations',exact:true})).toContainText('1 conversations');await reason(page);await current(page).getByRole('button',{name:'Restore conversation to inbox'}).click();await expect(current(page).getByRole('button',{name:'Archive conversation from inbox'})).toBeVisible();await reason(page);await current(page).getByRole('button',{name:'Archive conversation from inbox'}).click();await expect(current(page)).toContainText('Archived from the inbox.');const response=await actualVisitor(page,f,'A new message returns this fixture to the team');expect(response.status()).toBe(200);expect((await state(f)).inbox_archived_at).toBeNull();await inbox(page).getByLabel('Include archived conversations').uncheck();await expect(inbox(page).getByRole('region',{name:'Saved conversations',exact:true})).toContainText('1 conversations');expect((await f.db.from('luma_conversation_service_events').select('id').eq('property_id',f.property).eq('kind','inbox_reopened')).data).toHaveLength(1)
})
test('viewer reads exact sources while direct mutations, origin changes and old bypasses are held',async({page,fixture:f})=>{
 sql(`BEGIN;SELECT set_config('p11.team_scope','${f.org}',true);UPDATE public.profiles SET role='viewer' WHERE id='${f.id}';COMMIT;`);await login(page,f);await open(page);await expect(current(page)).toContainText('A current property manager');await expect(current(page).getByRole('button',{name:'Take over conversation'})).toHaveCount(0);const source=await read(f);expect((await post(page,f,{operation:'takeover',conversationId:f.conversation,sourceHash:source.hash,reason:'Viewer request'})).status()).toBe(403);expect((await page.request.post('/api/lumaleasing/admin/conversation-work',{headers:{origin:'https://other.invalid'},data:{id:randomUUID(),propertyId:f.property,expectedActorId:f.id,operation:'cancel'}})).status()).toBe(403);expect((await page.request.post('/api/conversations/'+f.conversation+'/takeover',{headers:{origin}})).status()).toBe(410);expect((await page.request.delete('/api/conversations?conversationId='+f.conversation,{headers:{origin}})).status()).toBe(410);expect((await page.request.post('/api/chat',{headers:{origin},data:{propertyId:f.property,conversationId:f.conversation,isHumanMessage:true,messages:[{role:'assistant',content:'Forged reply'}]}})).status()).toBe(410);await current(page).getByRole('button',{name:'Save transcript review'}).click();await expect(saved(page)).toContainText('review saved');expect((await state(f)).is_human_mode).toBe(false)
})
test('complete decision history and saved source recovery survive read failures',async({page,fixture:f})=>{
 for(let n=0;n<28;n++){const r=await f.db.rpc('decide_luma_conversation',{p_id:randomUUID(),p_actor_id:f.id,p_property_id:f.property,p_input:{operation:'cancel'}});expect(r.error).toBeNull()}let blocked=true;await page.route('**/api/lumaleasing/admin/conversation-work?**',async route=>{if(blocked)await route.fulfill({status:503,json:{error:'Temporary conversation read interruption'}});else await route.continue()});await login(page,f);await expect(inbox(page).getByRole('alert')).toContainText('Temporary conversation read interruption');blocked=false;await inbox(page).getByRole('button',{name:'Refresh inbox'}).click();await open(page);await current(page).getByRole('button',{name:'Save transcript review'}).click();await expect(saved(page)).toContainText('review saved');await inbox(page).getByRole('button',{name:'Conversation decision history',exact:true}).click();const history=inbox(page).getByRole('region',{name:'Conversation decision list',exact:true});await expect(history).toContainText('29 decisions');await expect(history.getByRole('listitem')).toHaveCount(25);await history.getByRole('button',{name:'Next inbox page'}).click();await expect(history.getByRole('listitem')).toHaveCount(4);await history.getByRole('button',{name:'Previous inbox page'}).click();await history.getByRole('button',{name:/review saved/}).click();await expect(saved(page)).toContainText('Private original visitor question');await page.goto('/dashboard/luma');await expect(page).toHaveURL(/lumaleasing\?tab=conversations/);await expect(inbox(page)).toBeVisible()
})
