import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;competitor:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),competitor=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision alerts browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision other alerts browser fixture'}]))

  await provide({property,otherProperty,competitor,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['competitors','market_alerts','marketvision_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})

const panel=(page:Page)=>page.getByRole('region',{name:'Recorded market alerts'})
async function openAlerts(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/marketvision?tab=alerts');await expect(panel(page).getByRole('heading',{name:'Market alerts',exact:true})).toBeVisible()}
async function drop(page:Page,method:string){let did=false;await page.route('**/api/marketvision/alerts',async route=>{if(route.request().method()===method&&!did){did=true;const res=await route.fetch();expect(res.ok(),await res.text()).toBe(true);await route.abort('failed')}else await route.continue()})}
async function seed(f:Fixture,count:number){const records=Array.from({length:count},(_,i)=>({id:randomUUID(),property_id:f.property,alert_type:'competitor_update',title:`Earlier alert ${i}`,description:'Unverified historical operator prompt',data:{privateReceipt:'must stay private'},created_at:'2020-01-01T00:00:00Z'}));expect((await f.db.from('market_alerts').insert(records)).error).toBeNull();return records}

test('visible selection survives a lost reply and excludes unseen arrivals; dismissal and restoration retain evidence',async({page,fixture},info)=>{
 await seed(fixture,52);await openAlerts(page,fixture);const p=panel(page);await expect(p).toContainText('52 recorded alerts · 52 unread');const shown=await p.getByRole('heading',{level:4}).allTextContents();expect(shown).toHaveLength(50)
 const late=randomUUID();expect((await fixture.db.from('market_alerts').insert({id:late,property_id:fixture.property,alert_type:'competitor_update',title:'Late unseen alert',description:'Arrived after the displayed selection'})).error).toBeNull()
 await drop(page,'PUT');await p.getByRole('button',{name:'Mark 50 displayed alerts read'}).click();await expect(p.getByRole('alert')).toContainText('Failed to fetch');await p.getByRole('button',{name:'Mark 50 displayed alerts read'}).click();await expect(p).toContainText('53 recorded alerts · 3 unread');await page.unroute('**/api/marketvision/alerts');expect((await fixture.db.from('market_alerts').select('is_read').eq('id',late).single()).data?.is_read).toBe(false);expect((await fixture.db.from('marketvision_decisions').select('id').eq('property_id',fixture.property).eq('kind','alert.read')).data).toHaveLength(1)
 await p.getByRole('button',{name:/Dismiss.*Late unseen alert/}).click();await p.getByLabel('Reason for alert decision').fill('Dismiss unverified duplicate pending separate source review');await p.getByRole('button',{name:'Confirm dismissal'}).click();await expect(p).toContainText('53 recorded alerts · 2 unread · 1 dismissed');await p.getByLabel('Alert view',{exact:true}).selectOption('dismissed');await expect(p.getByRole('heading',{name:'Late unseen alert'})).toBeVisible();await p.getByRole('button',{name:/Restore.*Late unseen alert/}).click();await p.getByLabel('Reason for alert decision').fill('Restore for another operator review');await p.getByRole('button',{name:'Confirm restoration'}).click();await expect(p).toContainText('53 recorded alerts · 3 unread · 0 dismissed');await p.getByLabel('Alert view',{exact:true}).selectOption('all');await p.getByRole('button',{name:'Older alerts'}).click();await expect(p.getByRole('heading',{level:4})).toHaveCount(53);await expect(p).not.toContainText('must stay private');await expect(p).toContainText('Earlier source · verification unavailable')
 await page.setViewportSize({width:390,height:844});await p.getByRole('heading',{name:'Market alerts',exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('market-alerts-mobile.png')})
})

test('reported alerts recover creation and stale reviews cannot overwrite newer decisions',async({page,fixture})=>{
 await openAlerts(page,fixture);const p=panel(page);await expect(p).toContainText('0 recorded alerts');await p.getByText('Report an alert',{exact:true}).click();await p.getByLabel('Alert title',{exact:true}).fill('Review a reported promotion');await p.getByLabel('Reported details',{exact:true}).fill('Client notes mention a promotion; confirm its original source.');await p.getByLabel('Reason for reported alert').fill('Record this operator report for follow-up');await drop(page,'POST');await p.getByRole('button',{name:'Save reported alert'}).click();await expect(p.getByRole('alert')).toContainText('Failed to fetch');await p.getByRole('button',{name:'Save reported alert'}).click();await expect(p).toContainText('1 recorded alerts · 1 unread');await page.unroute('**/api/marketvision/alerts');await expect(p).toContainText('Operator report · not independently verified');const record=(await fixture.db.from('market_alerts').select('id,version').eq('property_id',fixture.property).single()).data!
 expect((await page.request.put('/api/marketvision/alerts',{data:{propertyId:fixture.property,action:'read_all'}})).status()).toBe(400)
 await p.getByRole('button',{name:/Dismiss.*Review a reported promotion/}).click();await p.getByLabel('Reason for alert decision').fill('Review an older displayed version');expect((await fixture.db.rpc('review_marketvision_alerts',{p_id:randomUUID(),p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{action:'read',alerts:[{id:record.id,expectedVersion:record.version}],reason:'Another operator reviewed the current alert'}})).error).toBeNull();await p.getByRole('button',{name:'Confirm dismissal'}).click();await expect(p.getByRole('alert')).toContainText('changed after it was displayed');expect((await fixture.db.from('market_alerts').select('is_read,is_dismissed').eq('id',record.id).single()).data).toMatchObject({is_read:true,is_dismissed:false});await p.getByRole('button',{name:'Reload alerts'}).click();await expect(p).toContainText('1 recorded alerts · 0 unread');expect((await page.request.put('/api/marketvision/alerts',{data:{propertyId:fixture.otherProperty,requestId:randomUUID(),action:'dismiss',alerts:[{id:record.id,expectedVersion:2}],reason:'Wrong property fixture'}})).status()).toBe(404)
})

test('failed and delayed alert reads never become empty success or cross property boundaries',async({page,fixture})=>{
 await seed(fixture,2);await page.route('**/api/marketvision/alerts?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Alert counts temporarily unavailable'})}));await openAlerts(page,fixture);const p=panel(page);await expect(p.getByRole('alert')).toContainText('Alert counts temporarily unavailable');await expect(p).not.toContainText('No alerts in this view');await page.unroute('**/api/marketvision/alerts?*');await p.getByRole('button',{name:'Reload alerts'}).click();await expect(p).toContainText('2 recorded alerts');let release:()=>void=()=>{},start:()=>void=()=>{};const held=new Promise<void>(resolve=>{release=resolve}),started=new Promise<void>(resolve=>{start=resolve});await page.route('**/api/marketvision/alerts?*',async route=>{if(new URL(route.request().url()).searchParams.get('propertyId')===fixture.property){const response=await route.fetch();start();await held;await route.fulfill({response}).catch(()=>{})}else await route.continue()});await p.getByRole('button',{name:'Reload alerts'}).click();await started;await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);release();await page.unroute('**/api/marketvision/alerts?*');await expect(panel(page)).toContainText('0 recorded alerts');await expect(panel(page)).not.toContainText('Earlier alert 0')
})
