import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;competitor:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),competitor=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision listing browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision other listing browser fixture'}]))

  await provide({property,otherProperty,competitor,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['competitors','scrape_config','marketvision_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})


async function openMarket(page:Page,f:Fixture,tab='Competitors'){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/marketvision');await page.getByRole('button',{name:tab,exact:true}).click()}
async function drop(page:Page,path:string,method:string){let dropped=false;await page.route(`**/api/marketvision/${path}`,async r=>{if(r.request().method()===method&&!dropped){dropped=true;const reply=await r.fetch();expect(reply.ok(),await reply.text()).toBe(true);await r.abort('failed')}else await r.continue()})}
async function seed(f:Fixture){const r=await f.db.rpc('save_marketvision_competitor',{p_id:f.competitor,p_property_id:f.property,p_actor_id:f.actor,p_input:{action:'create',reason:'Isolated browser source fixture',values:{name:'Fixture competitor',property_type:'multifamily',amenities:[]},units:[]}});expect(r.error).toBeNull()}

test('listing decisions recover lost replies, retain history, and preserve other sources',async({page,fixture},info)=>{
 await seed(fixture);expect((await fixture.db.from('competitors').update({ils_listings:{rent_com:'https://www.rent.com/retained-source'}}).eq('id',fixture.competitor)).error).toBeNull();await openMarket(page,fixture);await page.getByRole('heading',{name:'Fixture competitor'}).click();const panel=page.getByRole('region',{name:'Competitor listing'});
 await expect(panel).toContainText('No Apartments.com listing is saved.');await panel.getByLabel('Listing URL',{exact:true}).fill('https://www.apartments.com/reviewed-community/abc/');await panel.getByLabel('Reason for listing change').fill('Reviewed the exact competitor source');await drop(page,'listings','PUT');await panel.getByRole('button',{name:'Save listing',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('Failed to fetch');await panel.getByRole('button',{name:'Save listing',exact:true}).click();await expect(panel.getByRole('status')).toContainText('Listing saved. Fetching prices is a separate decision.');await page.unroute('**/api/marketvision/listings');expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','market.listing.saved')).data).toHaveLength(1);
 const c=(await fixture.db.from('competitors').select('ils_listings,last_scraped_at').eq('id',fixture.competitor)).data![0];expect(c.ils_listings).toEqual({rent_com:'https://www.rent.com/retained-source',apartments_com:'https://www.apartments.com/reviewed-community/abc/'});expect(c.last_scraped_at).toBeNull();expect((await fixture.db.from('market_source_captures').select('id').eq('property_id',fixture.property)).data).toHaveLength(0);
 await panel.getByRole('button',{name:'Remove listing',exact:true}).click();await panel.getByLabel('Reason for listing change').fill('Source link no longer applies');await drop(page,'listings','PUT');await panel.getByRole('button',{name:'Confirm listing removal'}).click();await expect(panel.getByRole('alert')).toContainText('Failed to fetch');await panel.getByRole('button',{name:'Confirm listing removal'}).click();await expect(panel).toContainText('Listing removed. Previous source evidence is retained.');await page.unroute('**/api/marketvision/listings');await expect(panel).toContainText('No Apartments.com listing is saved.');expect((await fixture.db.from('competitors').select('ils_listings').eq('id',fixture.competitor)).data![0].ils_listings).toEqual({rent_com:'https://www.rent.com/retained-source'});
 const history=page.getByRole('region',{name:'Saved market decisions'});await history.locator('details').first().locator('summary').click();await expect(history).toContainText('Apartments.com listing');await expect(history).toContainText('https://www.apartments.com/reviewed-community/abc/');await page.setViewportSize({width:390,height:844});await panel.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('market-listing-mobile.png')});
})

test('stale listing changes require reload and malformed URLs cannot save',async({page,fixture})=>{
 await seed(fixture);await openMarket(page,fixture);await page.getByRole('heading',{name:'Fixture competitor'}).click();const panel=page.getByRole('region',{name:'Competitor listing'});await expect(panel.getByRole('button',{name:'Save listing',exact:true})).toBeEnabled();await panel.getByLabel('Listing URL',{exact:true}).fill('https://evil.com/apartments.com/fake');await panel.getByLabel('Reason for listing change').fill('Review source input validation');await panel.getByRole('button',{name:'Save listing',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('Use the complete public Apartments.com listing URL.');await panel.getByLabel('Listing URL',{exact:true}).fill('https://www.apartments.com/stale-source/abc/');expect((await fixture.db.from('competitors').update({ils_listings:{apartments_com:'https://www.apartments.com/current-source/abc/'}}).eq('id',fixture.competitor)).error).toBeNull();await panel.getByRole('button',{name:'Save listing',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('Competitor details changed.');await panel.getByRole('button',{name:'Reload saved listing'}).click();await expect(panel.getByLabel('Listing URL',{exact:true})).toHaveValue('https://www.apartments.com/current-source/abc/');await expect(panel.getByLabel('Reason for listing change')).toHaveValue('');await panel.getByLabel('Listing URL',{exact:true}).fill('https://www.apartments.com/corrected-source/abc/');await panel.getByLabel('Reason for listing change').fill('Reviewed current source and corrected link');await panel.getByRole('button',{name:'Save listing',exact:true}).click();await expect(panel.getByRole('status')).toContainText('Listing saved.');expect((await page.request.get(`/api/marketvision/listings?propertyId=${fixture.otherProperty}&competitorId=${fixture.competitor}`)).status()).toBe(404);
})

test('failed source reads disable changes and property switching clears prior source data',async({page,fixture})=>{
 await seed(fixture);await page.route('**/api/marketvision/listings?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved sources unavailable'})}));await openMarket(page,fixture);await page.getByRole('heading',{name:'Fixture competitor'}).click();const panel=page.getByRole('region',{name:'Competitor listing'});await expect(panel.getByRole('alert')).toContainText('Saved sources unavailable');await expect(panel.getByRole('button',{name:'Save listing',exact:true})).toBeDisabled();await expect(panel.getByText('No Apartments.com listing is saved.')).toHaveCount(0);await page.unroute('**/api/marketvision/listings?*');await panel.getByRole('button',{name:'Reload saved listing'}).click();await expect(panel.getByRole('button',{name:'Save listing',exact:true})).toBeEnabled();expect((await page.request.post('/api/marketvision/apartments-com',{data:{action:'add_listing',competitorId:fixture.competitor,url:'https://www.apartments.com/old-path/abc/'}})).status()).toBe(409);expect((await page.request.post('/api/marketvision/apartments-com',{data:{action:'refresh_single',competitorId:fixture.competitor}})).status()).toBe(503);
 await page.getByRole('button',{name:'Close competitor details'}).click();await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);await page.getByRole('button',{name:'Competitors',exact:true}).click();await expect(page.getByRole('heading',{name:'Fixture competitor'})).toHaveCount(0);await expect(page.getByRole('region',{name:'Competitor listing'})).toHaveCount(0);
})
