import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID, createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;competitor:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),competitor=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision brand browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision other brand browser fixture'}]))

  await provide({property,otherProperty,competitor,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['competitors','market_alerts','marketvision_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})

const panel=(page:Page)=>page.getByRole('region',{name:'Saved brand evidence'})
const text='Garden living beside the park. Welcome home to our community. Contact our team for availability.',preview={claims:[{category:'positioning',kind:'source_claim',statement:'The page promotes garden living.',quote:'Garden living beside the park'},{category:'voice',kind:'interpretation',statement:'Inviting language.',quote:'Welcome home'}],notes:'One public page; source claims are not verified.'}
async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const {data,error}=await f.db.rpc(name,args);expect(error).toBeNull();return data}
async function source(f:Fixture){expect((await f.db.from('competitors').insert({id:f.competitor,property_id:f.property,name:'Brand browser competitor',property_type:'multifamily',website_url:'https://example.com/brand/'})).error).toBeNull();const id=randomUUID();await rpc(f,'begin_marketvision_source',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_input:{competitorId:f.competitor,expectedVersion:1,source:'website',reason:'Retain synthetic brand page for local verification'}});const claim=await rpc(f,'claim_marketvision_source',{p_id:id}),body=`<p>${text}</p>`;await rpc(f,'record_marketvision_source_result',{p_id:id,p_claim_token:claim.claimToken,p_result:{status:'received',transport:'public_http_v1',parserVersion:'public-html-v1',requestedUrl:'https://example.com/brand/',finalUrl:'https://example.com/brand/',statusCode:200,contentType:'text/html',fetchedAt:new Date().toISOString(),body,bodyHash:createHash('sha256').update(body).digest('hex'),text,textTruncated:false}});return id}
async function receipt(f:Fixture,id:string){const claim=await rpc(f,'claim_marketvision_brand',{p_id:id});expect(claim.state).toBe('invoke_once');await rpc(f,'record_marketvision_brand_result',{p_id:id,p_claim_token:claim.claimToken,p_result:{status:'received',content:JSON.stringify(preview),finishReason:'stop',usage:{inputTokens:100,outputTokens:30},estimatedCostUsd:0.000033,costBasis:'Synthetic estimate; not invoice evidence'}})}
async function open(page:Page,f:Fixture,query=''){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto(`/dashboard/marketvision?tab=brand-intel${query}`);await expect(panel(page).getByRole('heading',{name:'Brand evidence',exact:true})).toBeVisible();await expect(panel(page).getByRole('button',{name:'Reload brand evidence'})).toBeEnabled()}
async function drop(page:Page,method:string){let did=false;await page.route('**/api/marketvision/brand-evidence',async route=>{if(route.request().method()===method&&!did){did=true;const res=await route.fetch();expect(res.ok(),await res.text()).toBe(true);await route.abort('failed')}else await route.continue()})}
async function review(page:Page){const p=panel(page);await p.getByLabel('Decision for statement 1').selectOption('include');await p.getByLabel('Decision for statement 2').selectOption('skip');await p.getByLabel('Reviewed statement 1',{exact:true}).fill('The captured page describes garden living.');await p.getByRole('checkbox',{name:/I reviewed every quotation/}).check();await p.getByRole('checkbox',{name:/This reviewed set replaces/}).check();await p.getByLabel('Reason for brand decision').fill('Reviewed exact quotation and corrected statement')}
test('source request, paused receipt recovery, corrections, lost approval and withdrawal retain complete evidence',async({page,fixture},info)=>{
 await source(fixture);await open(page,fixture,`&brandCompetitorId=${fixture.competitor}`);const p=panel(page),sources=p.getByRole('region',{name:'Retained public sources'});await sources.getByRole('button',{name:/Page retained/}).click();await sources.getByRole('checkbox').check();await sources.getByLabel('Reason for source decision').fill('Analyze this reviewed retained brand source');await drop(page,'POST');await sources.getByRole('button',{name:'Request brand analysis from retained page'}).click();await expect(sources.getByRole('alert')).toContainText('Failed to fetch');await sources.getByRole('button',{name:'Request brand analysis from retained page'}).click();await expect(page).toHaveURL(/brandRequestId=/);await page.unroute('**/api/marketvision/brand-evidence');await expect(panel(page)).toContainText('Waiting for analysis');const id=new URL(page.url()).searchParams.get('brandRequestId')!;expect((await fixture.db.from('marketvision_brand_requests').select('id,claim_token').eq('property_id',fixture.property)).data).toEqual([{id,claim_token:null}]);await receipt(fixture,id);await p.getByRole('button',{name:'Reload brand evidence'}).click();await expect(p).toContainText('Saved result needs completion');await p.getByLabel('Reason for brand decision').fill('Recover locally retained model result');await p.getByRole('button',{name:'Recover saved analysis'}).click();await expect(p).toContainText('Statements need review');await review(page);await drop(page,'PATCH');await p.getByRole('button',{name:'Save reviewed statements'}).click();await expect(p.getByRole('alert')).toContainText('Failed to fetch');await p.getByRole('button',{name:'Save reviewed statements'}).click();await expect(p).toContainText('Brand review saved. It does not verify');await page.unroute('**/api/marketvision/brand-evidence');expect((await fixture.db.from('marketvision_brand_reviews').select('id,claims').eq('property_id',fixture.property)).data).toHaveLength(1);expect((await fixture.db.from('marketvision_brand_requests').select('preview').eq('id',id).single()).data?.preview).toEqual(preview)
 await page.reload();await expect(panel(page).getByRole('button',{name:'Withdraw current evidence'})).toBeVisible();await p.getByLabel('Reason for brand decision').fill('Withdraw for source review without erasing the prior decision');await p.getByRole('button',{name:'Withdraw current evidence'}).click();await expect(p).toContainText('Evidence withdrawn. Earlier reviews remain in history.');const ctx=await rpc(fixture,'read_marketvision_brand_context',{p_property_id:fixture.property});expect(ctx.evidence).toEqual([]);expect((await fixture.db.from('marketvision_brand_reviews').select('id').eq('property_id',fixture.property)).data).toHaveLength(2)
 await page.goto(`/dashboard/marketvision?tab=monitoring&runId=${id}`);await expect(page.getByRole('region',{name:'Market monitoring history'})).toContainText('Brand review saved');await expect(panel(page).getByRole('heading',{name:'Brand browser competitor',exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});await panel(page).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('brand-evidence-mobile.png')})
})
test('changed source baseline blocks approval and earlier analysis cannot become qualified context',async({page,fixture})=>{
 const sourceId=await source(fixture),id=randomUUID();const created=await page.request.post('/api/marketvision/brand-evidence',{data:{requestId:id,propertyId:fixture.property,competitorId:fixture.competitor,sourceId,sourceVersion:3,confirmedSourceScope:true,reason:'Retain source for stale review qualification'}});expect(created.status()).toBe(200);await receipt(fixture,id);await open(page,fixture,`&brandCompetitorId=${fixture.competitor}&brandRequestId=${id}`);const p=panel(page);await p.getByLabel('Reason for brand decision').fill('Complete locally saved preview');await p.getByRole('button',{name:'Recover saved analysis'}).click();await expect(p).toContainText('Statements need review');await review(page);expect((await fixture.db.from('competitors').update({name:'Changed brand competitor'}).eq('id',fixture.competitor)).error).toBeNull();await p.getByRole('button',{name:'Save reviewed statements'}).click();await expect(p.getByRole('alert')).toContainText('no longer matches');expect((await fixture.db.from('marketvision_brand_reviews').select('id').eq('property_id',fixture.property)).data).toHaveLength(0);await p.getByRole('button',{name:'Reload brand evidence'}).click();await expect(p.getByRole('alert')).toContainText('Competitor details changed');expect((await page.request.post('/api/marketvision/brand-intelligence',{data:{propertyId:fixture.property,forceRefresh:true}})).status()).toBe(410)
})
test('failed and delayed reads remain visible and never cross the property boundary',async({page,fixture})=>{
 await source(fixture);await page.route('**/api/marketvision/brand-evidence?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Brand evidence temporarily unavailable'})}));await open(page,fixture);const p=panel(page);await expect(p.getByRole('alert')).toContainText('Brand evidence temporarily unavailable');await expect(p).not.toContainText('No saved records');await page.unroute('**/api/marketvision/brand-evidence?*');await p.getByRole('button',{name:'Reload brand evidence'}).click();await expect(p).toContainText('Brand browser competitor');let release:()=>void=()=>{},start:()=>void=()=>{};const held=new Promise<void>(resolve=>{release=resolve}),started=new Promise<void>(resolve=>{start=resolve});await page.route('**/api/marketvision/brand-evidence?*',async route=>{if(new URL(route.request().url()).searchParams.get('propertyId')===fixture.property){const response=await route.fetch();start();await held;await route.fulfill({response}).catch(()=>{})}else await route.continue()});await p.getByRole('button',{name:'Reload brand evidence'}).click();await started;await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);release();await expect(panel(page)).toContainText('0 saved competitor records');await expect(panel(page)).not.toContainText('Brand browser competitor')
})
