import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;competitor:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),competitor=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision intake browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision other intake browser fixture'}]))

  await provide({property,otherProperty,competitor,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['competitors','marketvision_intakes','marketvision_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})

const panel=(page:Page)=>page.getByRole('region',{name:'Saved competitor intake'})
async function openIntake(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/marketvision?tab=intake');await expect(panel(page).getByRole('heading',{name:'Review competitor notes'})).toBeVisible();await expect(panel(page)).toContainText('0 saved intake records')}
async function dropped(page:Page,method:string){let did=false;await page.route('**/api/competitors/intake',async route=>{if(route.request().method()===method&&!did){did=true;const res=await route.fetch();expect(res.ok(),await res.text()).toBe(true);await route.abort('failed')}else await route.continue()})}
async function prepare(page:Page){const p=panel(page);await p.getByLabel('Competitor notes',{exact:true}).fill('North sample (Reported City): starting at $2000. https://example.com/\n\nSouth sample: reported brand promotion.');await p.getByLabel('Reason for intake',{exact:true}).fill('Review client-provided competitor notes');await p.getByRole('button',{name:'Save review preview'}).click()}

test('saved intake recovers lost preparation and application replies with exact review and no enrichment',async({page,fixture},info)=>{
 let enrichment=0;page.on('request',req=>{if(req.url().includes('/enrich'))enrichment++})
 await openIntake(page,fixture);await dropped(page,'POST');await prepare(page);await expect(panel(page).getByRole('alert')).toContainText('Failed to fetch');await panel(page).getByRole('button',{name:'Save review preview'}).click();await expect(panel(page).getByRole('heading',{name:'Awaiting review',exact:true})).toBeVisible();await page.unroute('**/api/competitors/intake')
 const rows=(await fixture.db.from('marketvision_intakes').select('id,input,preview').eq('property_id',fixture.property)).data!;expect(rows).toHaveLength(1);expect((await fixture.db.from('competitors').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
 await page.reload();await panel(page).getByRole('button',{name:/Awaiting review/}).click();const detail=panel(page).getByRole('article',{name:'Saved intake details'});await detail.getByLabel('Add candidate 1').check();await detail.getByLabel('Name 1',{exact:true}).fill('Corrected North');await detail.getByLabel('Property type 1').selectOption('townhome');await detail.getByLabel('Location 1',{exact:true}).fill('Reviewed City');await detail.getByLabel('Source address 1').fill('https://example.com/reviewed');await detail.getByLabel('I reviewed the selected identities', {exact:false}).check();await detail.getByLabel('Reason for intake decision').fill('Add corrected North; skip the unrelated second entry')
 await page.setViewportSize({width:390,height:844});await detail.getByRole('heading',{name:'Awaiting review',exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('market-intake-mobile.png')})
 await dropped(page,'PUT');await detail.getByRole('button',{name:'Apply reviewed intake'}).click();await expect(detail.getByRole('alert')).toContainText('Failed to fetch');await detail.getByRole('button',{name:'Apply reviewed intake'}).click();await expect(panel(page).getByRole('heading',{name:'Review applied',exact:true})).toBeVisible();await page.unroute('**/api/competitors/intake');await expect(panel(page)).toContainText('1 competitor identities added; 1 candidates skipped');expect(enrichment).toBe(0)
 const competitors=(await fixture.db.from('competitors').select('id,name,address,website_url').eq('property_id',fixture.property)).data!;expect(competitors).toHaveLength(1);expect(competitors[0]).toMatchObject({name:'Corrected North',address:'Reviewed City',website_url:'https://example.com/reviewed'});expect((await fixture.db.from('competitor_units').select('id').eq('competitor_id',competitors[0].id)).data).toHaveLength(0);expect((await fixture.db.from('marketvision_decisions').select('id').eq('property_id',fixture.property).eq('kind','intake.applied')).data).toHaveLength(1)
 await page.goto(`/dashboard/marketvision?tab=monitoring&runId=${rows[0].id}`);await expect(panel(page).getByRole('heading',{name:'Review applied',exact:true})).toBeVisible();await expect(page.getByRole('article',{name:'Selected saved market work'})).toContainText('Reviewed competitors added');expect((await page.request.get(`/api/competitors/intake?propertyId=${fixture.otherProperty}&requestId=${rows[0].id}`)).status()).toBe(404)
})

test('concurrent intake reviews cannot duplicate an existing competitor and retain recoverable previews',async({page,fixture})=>{
 await openIntake(page,fixture);const payload={propertyId:fixture.property,rawText:'Same competitor: client-reported identity.',reason:'Concurrent operator review fixture'}
 const ids=[randomUUID(),randomUUID()];for(const requestId of ids){const res=await page.request.post('/api/competitors/intake',{data:{...payload,requestId}});expect(res.ok(),await res.text()).toBe(true)}
 const decisions=[];for(const id of ids){const res=await page.request.get(`/api/competitors/intake?propertyId=${fixture.property}&requestId=${id}`),entry=(await res.json()).intake;decisions.push({propertyId:fixture.property,requestId:randomUUID(),intakeId:id,expectedVersion:entry.version,previewHash:entry.preview_hash,action:'apply',reason:'Approve same reported identity',acknowledgeUnverified:true,candidates:[{id:entry.preview[0].id,action:'add',propertyType:'multifamily',name:'Same competitor',location:null,url:null}]})}
 const results=await Promise.all(decisions.map(data=>page.request.put('/api/competitors/intake',{data})));expect(results.map(r=>r.status()).sort()).toEqual([200,409]);expect((await fixture.db.from('competitors').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
 const pending=(await fixture.db.from('marketvision_intakes').select('id').eq('property_id',fixture.property).eq('state','preview_ready').single()).data!;await page.goto(`/dashboard/marketvision?tab=monitoring&runId=${pending.id}`);await expect(panel(page)).toContainText('Already saved: Same competitor');await panel(page).getByLabel('Reason for intake decision').fill('Stop duplicate after another operator saved the competitor');await panel(page).getByRole('button',{name:'Stop intake',exact:true}).click();await expect(panel(page).getByRole('heading',{name:'Stopped',exact:true})).toBeVisible();expect((await fixture.db.from('competitors').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
})

test('intake history failures stay visible and delayed results cannot cross a property switch',async({page,fixture})=>{
 await page.route('**/api/competitors/intake?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Intake history temporarily unavailable'})}));await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),fixture.property);await page.goto('/dashboard/marketvision?tab=intake');await expect(panel(page).getByRole('alert')).toContainText('Intake history temporarily unavailable');await expect(panel(page)).not.toContainText('0 saved intake records');await page.unroute('**/api/competitors/intake?*');await panel(page).getByRole('button',{name:'Reload intake'}).click();await expect(panel(page)).toContainText('0 saved intake records');await prepare(page);await expect(panel(page).getByRole('heading',{name:'Awaiting review',exact:true})).toBeVisible()
 let release:()=>void=()=>{},start:()=>void=()=>{};const held=new Promise<void>(resolve=>{release=resolve}),started=new Promise<void>(resolve=>{start=resolve});await page.route('**/api/competitors/intake?*',async route=>{if(new URL(route.request().url()).searchParams.get('propertyId')===fixture.property){const response=await route.fetch();start();await held;await route.fulfill({response}).catch(()=>{})}else await route.continue()});await panel(page).getByRole('button',{name:'Reload intake'}).click();await started;await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);release();await page.unroute('**/api/competitors/intake?*');await expect(panel(page)).toContainText('0 saved intake records');await expect(panel(page)).not.toContainText('North sample');await expect(panel(page).getByLabel('Competitor notes',{exact:true})).toHaveValue('')
})


test('earlier intake is paged read-only with original notes and no retry action',async({page,fixture})=>{
 const batches=Array.from({length:23},(_,i)=>({id:randomUUID(),property_id:fixture.property,submitted_by:fixture.actor,raw_text:`Earlier private operator notes ${i}.`,status:'completed'}));expect((await fixture.db.from('competitor_intake_batches').insert(batches)).error).toBeNull();expect((await fixture.db.from('competitor_intake_candidates').insert({batch_id:batches[0].id,property_id:fixture.property,seed_name:'Earlier candidate',seed_snippet:'An earlier reported identity.',seed_claims:{priceText:'$900000'},enrichment_status:'completed',error_message:'private provider error omitted'})).error).toBeNull()
 await openIntake(page,fixture);await panel(page).getByLabel('Intake history',{exact:true}).selectOption('legacy');await expect(panel(page)).toContainText('23 saved intake records');await expect(panel(page).getByRole('button',{name:/Earlier status: completed/})).toHaveCount(20);await panel(page).getByRole('button',{name:'Older intake records'}).click();await expect(panel(page).getByRole('button',{name:/Earlier status: completed/})).toHaveCount(23);await panel(page).getByRole('button',{name:new RegExp(batches[0].id)}).click();const detail=panel(page).getByRole('article',{name:'Earlier intake details'});await expect(detail).toContainText('Earlier candidate');await detail.getByText('Original notes',{exact:true}).click();await expect(detail).toContainText('Earlier private operator notes 0.');await expect(detail.getByRole('button')).toHaveCount(0);await expect(detail).not.toContainText('private provider error');expect((await page.request.get(`/api/competitors/intake?propertyId=${fixture.otherProperty}&view=legacy&requestId=${batches[0].id}`)).status()).toBe(404)
})
