import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;competitor:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),competitor=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision handoffs browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision other handoffs browser fixture'}]))

  await provide({property,otherProperty,competitor,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['competitors','scrape_config','marketvision_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})


async function drop(page:Page,path:string,method:string){let dropped=false;await page.route(`**/api/marketvision/${path}`,async r=>{if(r.request().method()===method&&!dropped){dropped=true;const reply=await r.fetch();expect(reply.ok(),await reply.text()).toBe(true);await r.abort('failed')}else await r.continue()})}
async function seedBrief(f:Fixture){
 const second=randomUUID();for(const [id,name,rent]of [[f.competitor,'North sample',1000],[second,'South sample',2000]]as const){const r=await f.db.rpc('save_marketvision_competitor',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_input:{action:'create',reason:'Isolated saved brief source',values:{name,property_type:'multifamily',amenities:[]},units:[{unit_type:'One bedroom',bedrooms:1,rent_min:rent,rent_max:null}]}});expect(r.error).toBeNull()}
 expect((await f.db.from('property_units').insert({org_id:'22222222-2222-2222-2222-222222222222',property_id:f.property,unit_type:'Subject one bedroom',canonical_key:'subject-one',bedrooms:1,rent_min:1800,source:'manual',active:true,review_status:'approved'})).error).toBeNull()
}
async function openBrief(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/marketvision');await expect(page.getByRole('button',{name:'Save new brief',exact:true})).toBeDisabled();await expect(page.getByRole('region',{name:'Saved market briefs'})).toContainText('No saved-source briefs yet.')}
const panel=(page:Page)=>page.getByRole('region',{name:'Saved market briefs'})
async function createBrief(page:Page){const p=panel(page);await p.getByLabel('Reason for this brief',{exact:true}).fill('Review saved competitor pricing for the weekly meeting');await p.getByRole('button',{name:'Save new brief',exact:true}).click();return p}
async function latest(f:Fixture){const r=await f.db.from('marketvision_briefs').select('*').eq('property_id',f.property).order('created_at',{ascending:false}).limit(1).single();expect(r.error).toBeNull();return r.data!}


const handoffs=(page:Page)=>page.getByRole('region',{name:'ForgeStudio handoffs'})
async function considered(page:Page,f:Fixture){
 await seedBrief(f);await openBrief(page,f);await createBrief(page);const p=panel(page);await expect(p.getByRole('heading',{name:'Saved brief details',exact:true})).toBeVisible();const article=p.getByRole('article').filter({has:page.getByRole('heading',{name:'Review the 1-bedroom comparison',exact:true})});await p.getByLabel('Reason for report review or download').fill('Consider the pricing comparison for a draft topic');await article.getByRole('button',{name:'Mark for consideration'}).click();await expect(article).toContainText('Marked for consideration');return p
}
async function fillHandoff(page:Page){const h=handoffs(page);await h.getByText('Prepare a draft for approval',{exact:true}).click();await h.getByLabel('Reviewed comparison').selectOption({label:'Review the 1-bedroom comparison'});await h.getByLabel('Draft title',{exact:true}).fill('Saved market comparison draft');await h.getByLabel('Draft objective').fill('Review approved property differentiators for a useful community introduction');await h.getByLabel('Reason for draft handoff').fill('Prepare a draft based on the reviewed market snapshot');return h}
async function latestHandoff(f:Fixture){const r=await f.db.from('marketvision_handoffs').select('*').eq('property_id',f.property).order('created_at',{ascending:false}).limit(1).single();expect(r.error).toBeNull();return r.data!}

test('exact handoff survives lost prepare and approval replies, reloads and opens one ForgeStudio draft',async({page,fixture},info)=>{
 await considered(page,fixture);let h=await fillHandoff(page);await drop(page,'handoffs','POST');await h.getByRole('button',{name:'Save draft for approval'}).click();await expect(h.getByRole('alert')).toContainText('Failed to fetch');await h.getByRole('button',{name:'Save draft for approval'}).click();await expect(h.getByRole('heading',{name:'Saved draft for approval',exact:true})).toBeVisible();await page.unroute('**/api/marketvision/handoffs');const intent=await latestHandoff(fixture);expect((await fixture.db.from('marketvision_handoffs').select('id').eq('property_id',fixture.property)).data).toHaveLength(1);expect((await fixture.db.from('social_content_briefs').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
 await page.reload();h=handoffs(page);await expect(h.getByRole('heading',{name:'Saved draft for approval',exact:true})).toBeVisible();await h.getByLabel('Reason for handoff decision').fill('Approve the exact retained draft contents');await drop(page,'handoffs','PUT');await h.getByRole('button',{name:'Approve and create draft'}).click();await expect(h.getByRole('alert')).toContainText('Failed to fetch');await h.getByRole('button',{name:'Approve and create draft'}).click();await expect(h.getByRole('link',{name:'Open saved ForgeStudio draft'})).toBeVisible();await page.unroute('**/api/marketvision/handoffs');const saved=await latestHandoff(fixture);expect(saved.state).toBe('completed');expect(saved.receipt.generationStarted).toBe(false);expect(saved.receipt.businessOutcome).toBe('unknown');expect((await fixture.db.from('social_content_briefs').select('id').eq('property_id',fixture.property)).data).toEqual([{id:intent.target_id}]);const target=(await fixture.db.from('social_content_briefs').select('*').eq('id',intent.target_id).single()).data!;expect(target.source_facts).toEqual(intent.draft.sourceFacts);expect(target.format_plan).toEqual(intent.draft.formatPlan)
 const actions=(await fixture.db.from('shared_action_events').select('action,actor_id,shared_job_ref,shared_attempt_ref').eq('property_id',fixture.property).in('action',['market.handoff.prepared','market.handoff.decided','studio.brief.saved'])).data!;expect(actions).toHaveLength(3);expect(actions.every(a=>a.actor_id===fixture.actor)).toBe(true);expect(actions.filter(a=>a.action.startsWith('market.')).every(a=>a.shared_job_ref===intent.id&&a.shared_attempt_ref===intent.attempt_id)).toBe(true)
 await h.getByRole('link',{name:'Open saved ForgeStudio draft'}).click();const draft=page.getByRole('region',{name:'Saved ForgeStudio draft'});await expect(draft).toContainText('Saved market comparison draft');await expect(draft).toContainText('Review approved property differentiators');await expect(draft.getByRole('button',{name:'Generate from saved draft'})).toBeVisible();await page.reload();await expect(draft).toContainText('Saved market comparison draft');expect((await fixture.db.from('forgestudio_generations').select('id').eq('property_id',fixture.property)).data).toHaveLength(0);expect((await page.request.get(`/api/forgestudio/briefs/${intent.target_id}?propertyId=${fixture.otherProperty}`)).status()).toBe(404);await page.setViewportSize({width:390,height:844});await draft.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('market-handoff-mobile.png')})
})

test('changed reviews and sources fence approval while rejection and withdrawal remain recoverable',async({page,fixture})=>{
 const p=await considered(page,fixture);let h=await fillHandoff(page);await h.getByRole('button',{name:'Save draft for approval'}).click();await expect(h.getByRole('heading',{name:'Saved draft for approval',exact:true})).toBeVisible();const intent=await latestHandoff(fixture)
 const shared=await page.request.post('/api/substrate/approvals',{data:{propertyId:fixture.property,actionAttemptId:intent.attempt_id,decisionStatus:'approved',decisionReason:'Generic bypass attempt'}});expect(shared.status()).toBe(501);expect((await page.request.post('/api/marketvision/proposals',{data:{propertyId:fixture.property,proposalType:'forgestudio_messaging_brief',recommendation:{id:'forged',title:'fake',rationale:'fake'}}})).status()).toBe(410)
 const article=p.getByRole('article').filter({has:page.getByRole('heading',{name:'Review the 1-bedroom comparison',exact:true})});await p.getByLabel('Reason for report review or download').fill('Dismiss after further human review');await article.getByRole('button',{name:'Dismiss prompt'}).click();await expect(article).toContainText('Dismissed');h=handoffs(page);await h.getByRole('button',{name:'Reload handoffs'}).click();await expect(h.getByRole('alert')).toContainText('recommendation review changed');await h.getByLabel('Reason for handoff decision').fill('Reject because recommendation is now dismissed');await expect(h.getByRole('button',{name:'Approve and create draft'})).toBeDisabled();await h.getByRole('button',{name:'Reject handoff'}).click();await expect(h).toContainText('Rejected')
 await p.getByLabel('Reason for report review or download').fill('Reconsider for a different draft');await article.getByRole('button',{name:'Mark for consideration'}).click();await expect(article).toContainText('Marked for consideration');h=await fillHandoff(page);await h.getByRole('button',{name:'Save draft for approval'}).click();await expect(h.getByRole('button',{name:'Approve and create draft'})).toBeVisible();expect((await fixture.db.from('competitor_units').update({rent_min:3456}).eq('competitor_id',fixture.competitor)).error).toBeNull();await h.getByLabel('Reason for handoff decision').fill('Check the source fence before creating');await h.getByRole('button',{name:'Approve and create draft'}).click();await expect(h.getByRole('alert')).toContainText('Source evidence changed');await h.getByRole('button',{name:'Reload handoffs'}).click();await expect(h.getByRole('button',{name:'Approve and create draft'})).toBeDisabled();await h.getByLabel('Reason for handoff decision').fill('Withdraw after source records changed');await h.getByRole('button',{name:'Withdraw handoff'}).click();await expect(h).toContainText('Withdrawn');expect((await fixture.db.from('social_content_briefs').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
})

test('failed reads are visible and older handoffs remain accessible',async({page,fixture})=>{
 await considered(page,fixture);const report=await latest(fixture),rec=report.result.recommendations.find((r:{kind:string})=>r.kind==='comparison_review'),review=(await fixture.db.from('marketvision_decisions').select('id').eq('property_id',fixture.property).eq('kind','brief.reviewed').single()).data!
 for(let i=0;i<22;i++){const id=randomUUID(),input={briefId:report.id,expectedVersion:2,recommendationId:rec.id,expectedReviewId:review.id,title:`Saved handoff history ${i}`,objective:'Review only approved property facts',channel:'facebook',format:'image',reason:'Save isolated history pagination fixture'};const prepared=await fixture.db.rpc('prepare_marketvision_handoff',{p_id:id,p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:input});expect(prepared.error).toBeNull();expect(prepared.data.state).toBe('saved');const closed=await fixture.db.rpc('decide_marketvision_handoff',{p_id:randomUUID(),p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{handoffId:id,expectedVersion:1,draftHash:prepared.data.draftHash,decision:'withdraw',reason:'Withdraw this isolated history fixture'}});expect(closed.error).toBeNull();expect(closed.data.state).toBe('saved')}
 await page.route('**/api/marketvision/handoffs?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved handoff history unavailable'})}));await page.reload();const h=handoffs(page);await expect(h.getByRole('alert')).toContainText('Saved handoff history unavailable');await expect(h).not.toContainText('No handoffs for this saved brief.');await page.unroute('**/api/marketvision/handoffs?*');await h.getByRole('button',{name:'Reload handoffs'}).click();await expect(h.getByRole('button',{name:/Saved handoff history/})).toHaveCount(20);await h.getByRole('button',{name:'Older handoffs'}).click();await expect(h.getByRole('button',{name:/Saved handoff history/})).toHaveCount(22);await h.getByRole('button',{name:/Saved handoff history 0\s/}).click();await expect(h.getByRole('article')).toContainText('Saved handoff history 0')
})
