import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;competitor:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),competitor=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision monitoring browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision other monitoring browser fixture'}]))

  await provide({property,otherProperty,competitor,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['competitors','scrape_config','marketvision_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})


async function drop(page:Page,path:string,method:string){let dropped=false;await page.route(`**/api/marketvision/${path}`,async r=>{if(r.request().method()===method&&!dropped){dropped=true;const reply=await r.fetch();expect(reply.ok(),await reply.text()).toBe(true);await r.abort('failed')}else await r.continue()})}
async function seedBrief(f:Fixture){
 const second=randomUUID();for(const [id,name,rent]of [[f.competitor,'North sample',1000],[second,'South sample',2000]]as const){const r=await f.db.rpc('save_marketvision_competitor',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_input:{action:'create',reason:'Isolated saved brief source',values:{name,property_type:'multifamily',amenities:[]},units:[{unit_type:'One bedroom',bedrooms:1,rent_min:rent,rent_max:null}]}});expect(r.error).toBeNull()}
 expect((await f.db.from('property_units').insert({org_id:'22222222-2222-2222-2222-222222222222',property_id:f.property,unit_type:'Subject one bedroom',canonical_key:'subject-one',bedrooms:1,rent_min:1800,source:'manual',active:true,review_status:'approved'})).error).toBeNull()
}


const history=(p:Page)=>p.getByRole('region',{name:'Market monitoring history'})
async function seedWork(f:Fixture){
 await seedBrief(f);const {data:c}=await f.db.from('competitors').select('version').eq('id',f.competitor).single();const saved=await f.db.rpc('save_marketvision_competitor',{p_id:randomUUID(),p_property_id:f.property,p_actor_id:f.actor,p_input:{action:'save',competitorId:f.competitor,expectedVersion:c!.version,reason:'Add an isolated source address',values:{name:'North sample',website_url:'https://example.com/floorplans/',property_type:'multifamily',amenities:[]}}});expect(saved.error).toBeNull();const current=(await f.db.from('competitors').select('version').eq('id',f.competitor).single()).data!;
 const sourceId=randomUUID(),briefId=randomUUID();expect((await f.db.rpc('begin_marketvision_source',{p_id:sourceId,p_property_id:f.property,p_actor_id:f.actor,p_input:{competitorId:f.competitor,expectedVersion:current.version,source:'website',reason:'Isolated queued source work'}})).error).toBeNull();expect((await f.db.rpc('begin_marketvision_brief',{p_id:briefId,p_property_id:f.property,p_actor_id:f.actor,p_input:{windowDays:30,reason:'Isolated monitoring report'}})).error).toBeNull();return{sourceId,briefId}
}
async function openMonitoring(page:Page,f:Fixture,runId?:string){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto(`/dashboard/marketvision?tab=monitoring${runId?`&runId=${runId}`:''}`);await expect(history(page).getByRole('heading',{name:'Execution status',exact:true})).toBeVisible()}

test('monitoring retains complete history and opens original source recovery without repeating work',async({page,fixture},info)=>{
 const ids=await seedWork(fixture);expect((await fixture.db.from('shared_jobs').insert(Array.from({length:22},()=>({org_id:'22222222-2222-2222-2222-222222222222',property_id:fixture.property,domain:'marketvision.ingestion',subject_type:'observation_refresh',subject_id:fixture.property,lifecycle_status:'succeeded',payload:{privateSource:'not returned'}})))).error).toBeNull();await openMonitoring(page,fixture);const h=history(page);await expect(h).toContainText('24 saved records');await expect(h).toContainText('Public-page acquisition: Paused');await expect(h).toContainText('Scheduled discovery and automatic price changes are not activated');await expect(h.getByRole('link',{name:/Open saved work/})).toHaveCount(20);await h.getByRole('button',{name:'Older saved work'}).click();await expect(h.getByRole('link',{name:/Open saved work/})).toHaveCount(24)
 await h.getByLabel('Saved-work view').selectOption('legacy');await expect(h.getByRole('link',{name:/Open saved work/})).toHaveCount(20);await h.getByRole('link',{name:/Open saved work/}).first().click();await expect(page.getByRole('article',{name:'Selected saved market work'})).toContainText('original evidence, provider receipts');await expect(h.getByRole('button',{name:'Retry',exact:true})).toHaveCount(0);await h.getByRole('link',{name:'Close saved work'}).click();await expect(page).not.toHaveURL(/runId=/);await expect(page.getByRole('article',{name:'Selected saved market work'})).toHaveCount(0);await h.getByLabel('Saved-work view').selectOption('active');await expect(h.getByRole('link',{name:/Open saved work/})).toHaveCount(1);await h.getByRole('link',{name:/Open saved work.*North sample/}).click();await expect(page).toHaveURL(new RegExp(ids.sourceId));const source=page.getByRole('region',{name:'Retained public sources'});await expect(source.getByRole('heading',{name:'Waiting to fetch',exact:true})).toBeVisible();await page.reload();await source.getByLabel('Reason for source decision').fill('Stop the original queued source from monitoring');await drop(page,'sources','PUT');await source.getByRole('button',{name:'Stop page request'}).click();await expect(source.getByRole('alert')).toContainText('Failed to fetch');await source.getByRole('button',{name:'Stop page request'}).click();await expect(source.getByRole('heading',{name:'Stopped',exact:true})).toBeVisible();await page.unroute('**/api/marketvision/sources');const saved=(await fixture.db.from('marketvision_source_requests').select('state,claim_token').eq('id',ids.sourceId).single()).data!;expect(saved).toMatchObject({state:'stopped',claim_token:null});expect((await fixture.db.from('marketvision_source_requests').select('id').eq('property_id',fixture.property)).data).toHaveLength(1);expect((await fixture.db.from('marketvision_decisions').select('id').eq('property_id',fixture.property).eq('kind','source.stopped')).data).toHaveLength(1)
 await h.getByRole('button',{name:'Reload saved work'}).click();await expect(h.getByRole('article',{name:'Selected saved market work'})).toContainText('Stopped');await page.setViewportSize({width:390,height:844});await h.getByRole('heading',{name:'Saved work and recovery',exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('market-monitoring-mobile.png')})
})

test('monitoring opens an interrupted saved report and retains original completion across reload',async({page,fixture})=>{
 const ids=await seedWork(fixture);await openMonitoring(page,fixture,ids.briefId);const report=page.getByRole('region',{name:'Saved market briefs'});await expect(report.getByRole('heading',{name:'Saved evidence awaits completion'})).toBeVisible();await report.getByLabel('Reason for report review or download').fill('Complete the original report from monitoring');await report.getByRole('button',{name:'Complete saved brief'}).click();await expect(report.getByRole('heading',{name:'Saved brief details',exact:true})).toBeVisible();await page.reload();await expect(report.getByRole('heading',{name:'Saved brief details',exact:true})).toBeVisible();await expect(history(page).getByRole('article',{name:'Selected saved market work'})).toContainText('Saved report complete');expect((await fixture.db.from('marketvision_briefs').select('id').eq('property_id',fixture.property)).data).toHaveLength(1);expect((await page.request.get(`/api/marketvision/runs?propertyId=${fixture.otherProperty}&requestId=${ids.briefId}`)).status()).toBe(404);expect((await page.request.post('/api/marketvision/scrape',{data:{propertyId:fixture.property,action:'refresh'}})).status()).toBe(410);expect((await page.request.post('/api/marketvision/apartments-com',{data:{propertyId:fixture.property,action:'find_listings'}})).status()).toBe(410)
})

test('failed and delayed history cannot become empty success or leak into another property',async({page,fixture})=>{
 await seedWork(fixture);await page.route('**/api/marketvision/runs?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Monitoring history temporarily unavailable'})}));await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),fixture.property);await page.goto('/dashboard/marketvision?tab=monitoring');const h=history(page);await expect(h.getByRole('alert')).toContainText('Monitoring history temporarily unavailable');await expect(h).not.toContainText('No saved work in this view.');await page.unroute('**/api/marketvision/runs?*');await h.getByRole('button',{name:'Reload saved work'}).click();await expect(h).toContainText('2 saved records');let release:()=>void=()=>{},resolveStarted:()=>void=()=>{};const held=new Promise<void>(resolve=>{release=resolve}),started=new Promise<void>(resolve=>{resolveStarted=resolve});await page.route('**/api/marketvision/runs?*',async r=>{if(new URL(r.request().url()).searchParams.get('propertyId')===fixture.property){const response=await r.fetch();resolveStarted();await held;await r.fulfill({response}).catch(()=>{})}else await r.continue()});await h.getByRole('button',{name:'Reload saved work'}).click();await started;await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);release();await page.unroute('**/api/marketvision/runs?*');await expect(history(page)).toContainText('0 saved records',{timeout:30000});await expect(history(page)).not.toContainText('North sample');await expect(history(page).getByRole('link',{name:/Open saved work/})).toHaveCount(0)
})

test('direct monitoring links open the exact earlier handoff and queued extraction',async({page,fixture})=>{
 await seedBrief(fixture);const briefId=randomUUID(),reviewId=randomUUID(),first=randomUUID(),second=randomUUID();const create=await page.request.post('/api/marketvision/brief',{data:{requestId:briefId,propertyId:fixture.property,windowDays:30,reason:'Prepare an exact monitoring handoff report'}});expect(create.ok(),await create.text()).toBe(true);const report=(await fixture.db.from('marketvision_briefs').select('result').eq('id',briefId).single()).data!.result,rec=report.recommendations.find((r:{kind:string})=>r.kind==='comparison_review');expect(rec).toBeTruthy();const reviewed=await page.request.post('/api/marketvision/brief/review',{data:{requestId:reviewId,propertyId:fixture.property,briefId,expectedVersion:2,recommendationId:rec.id,expectedReviewId:null,decision:'consider',acknowledgedSourceChange:false,reason:'Consider this comparison for draft planning'}});expect(reviewed.ok(),await reviewed.text()).toBe(true)
 const intent={propertyId:fixture.property,briefId,expectedVersion:2,recommendationId:rec.id,expectedReviewId:reviewId,title:'Earlier exact draft',objective:'Review approved property differentiators',channel:'facebook',format:'image',reason:'Keep the exact draft for manager review'};const prepared=await page.request.post('/api/marketvision/handoffs',{data:{requestId:first,...intent}});expect(prepared.ok(),await prepared.text()).toBe(true);const result=(await prepared.json()).result;expect((await page.request.put('/api/marketvision/handoffs',{data:{requestId:randomUUID(),propertyId:fixture.property,handoffId:first,expectedVersion:1,draftHash:result.draftHash,decision:'withdraw',reason:'Withdraw this earlier draft'}})).ok()).toBe(true);expect((await page.request.post('/api/marketvision/handoffs',{data:{requestId:second,...intent,title:'Newer separate draft'}})).ok()).toBe(true)
 await openMonitoring(page,fixture,first);const h=page.getByRole('region',{name:'ForgeStudio handoffs'});await expect(h.getByRole('article')).toContainText('Earlier exact draft');await expect(h.getByRole('article')).toContainText('Withdrawn');await expect(h.getByRole('article')).not.toContainText('Newer separate draft');await page.reload();await expect(h.getByRole('article')).toContainText('Earlier exact draft')
 const extractionId=randomUUID(),competitor=(await fixture.db.from('competitors').select('version').eq('id',fixture.competitor).single()).data!;const extraction=await page.request.post('/api/marketvision/extract-pricing',{data:{requestId:extractionId,propertyId:fixture.property,competitorId:fixture.competitor,sourceVersion:competitor.version,sourceUrl:'',content:'Operator-provided fixture page: one bedroom starting at 1200 dollars monthly rent in USD. Verify every price before use.',effectiveAt:null,reason:'Save an isolated pricing extraction for monitoring'}});expect(extraction.ok(),await extraction.text()).toBe(true);await page.goto(`/dashboard/marketvision?tab=monitoring&runId=${extractionId}`);await expect(page.getByRole('article',{name:'Current extraction'}).getByRole('heading',{name:'Waiting to start',exact:true})).toBeVisible();const saved=(await fixture.db.from('marketvision_extraction_requests').select('state,claim_token').eq('id',extractionId).single()).data!;expect(saved).toMatchObject({state:'queued',claim_token:null})
})
