import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID, createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;competitor:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),competitor=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision briefs browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'MarketVision other briefs browser fixture'}]))

  await provide({property,otherProperty,competitor,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';CREATE TEMP TABLE fixture_contexts ON COMMIT DROP AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['competitors','scrape_config','marketvision_decisions','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})


async function openMarket(page:Page,f:Fixture,tab='Competitors'){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/marketvision');await page.getByRole('button',{name:tab,exact:true}).click()}
async function drop(page:Page,path:string,method:string){let dropped=false;await page.route(`**/api/marketvision/${path}`,async r=>{if(r.request().method()===method&&!dropped){dropped=true;const reply=await r.fetch();expect(reply.ok(),await reply.text()).toBe(true);await r.abort('failed')}else await r.continue()})}
async function seedBrief(f:Fixture){
 const second=randomUUID();for(const [id,name,rent]of [[f.competitor,'North sample',1000],[second,'South sample',2000]]as const){const r=await f.db.rpc('save_marketvision_competitor',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_input:{action:'create',reason:'Isolated saved brief source',values:{name,property_type:'multifamily',amenities:[]},units:[{unit_type:'One bedroom',bedrooms:1,rent_min:rent,rent_max:null}]}});expect(r.error).toBeNull()}
 expect((await f.db.from('property_units').insert({org_id:'22222222-2222-2222-2222-222222222222',property_id:f.property,unit_type:'Subject one bedroom',canonical_key:'subject-one',bedrooms:1,rent_min:1800,source:'manual',active:true,review_status:'approved'})).error).toBeNull()
}
async function openBrief(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/marketvision');await expect(page.getByRole('button',{name:'Save new brief',exact:true})).toBeDisabled();await expect(page.getByRole('region',{name:'Saved market briefs'})).toContainText('No saved-source briefs yet.')}
const panel=(page:Page)=>page.getByRole('region',{name:'Saved market briefs'})
async function createBrief(page:Page){const p=panel(page);await p.getByLabel('Reason for this brief',{exact:true}).fill('Review saved competitor pricing for the weekly meeting');await p.getByRole('button',{name:'Save new brief',exact:true}).click();return p}
async function latest(f:Fixture){const r=await f.db.from('marketvision_briefs').select('*').eq('property_id',f.property).order('created_at',{ascending:false}).limit(1).single();expect(r.error).toBeNull();return r.data!}
async function lose(page:Page,path:string){let dropped=false;await page.route(`**/api/marketvision/${path}`,async r=>{if(r.request().method()==='POST'&&!dropped){dropped=true;const response=await r.fetch();expect(response.ok(),await response.text()).toBe(true);await r.abort('failed')}else await r.continue()})}

test('briefs retain exact evidence and recover lost request, review and download responses',async({page,fixture},info)=>{
 await seedBrief(fixture);await openBrief(page,fixture);await lose(page,'brief');const p=await createBrief(page);await expect(p.getByRole('alert')).toContainText('Failed to fetch');await p.getByRole('button',{name:'Save new brief',exact:true}).click();await expect(p.getByRole('heading',{name:'Saved brief details',exact:true})).toBeVisible();await page.unroute('**/api/marketvision/brief');const r=await latest(fixture);expect((await fixture.db.from('marketvision_briefs').select('id').eq('property_id',fixture.property)).data).toHaveLength(1);expect(r.result.positions[0]).toMatchObject({subjectMean:1800,competitorMean:1500,differencePercent:20});expect(r.result.synthesisModel).toBeNull();expect((await fixture.db.from('shared_action_events').select('actor_id,service_principal').eq('property_id',fixture.property).eq('action','market.brief.completed')).data).toEqual([{actor_id:null,service_principal:'marketvision.brief'}]);
 await p.getByLabel('Reason for report review or download').fill('Check current terms before changing any prices');await lose(page,'brief/review');await p.getByRole('button',{name:'Mark for consideration'}).first().click();await expect(p.getByRole('alert')).toContainText('Failed to fetch');await p.getByRole('button',{name:'Mark for consideration'}).first().click();await expect(p).toContainText('Review: Marked for consideration');await page.unroute('**/api/marketvision/brief/review');expect((await fixture.db.from('marketvision_decisions').select('id').eq('property_id',fixture.property).eq('kind','brief.reviewed')).data).toHaveLength(1)
 await p.getByLabel('Reason for report review or download').fill('Download exact saved report for local review');await lose(page,'brief/export');await p.getByRole('button',{name:'Download readable report'}).click();await expect(p.getByRole('alert')).toContainText('Failed to fetch');const waiting=page.waitForEvent('download');await p.getByRole('button',{name:'Download readable report'}).click();const download=await waiting,path=info.outputPath('saved-market-brief.md');await download.saveAs(path);await expect(p).toContainText('File receipt is not confirmed');await page.unroute('**/api/marketvision/brief/export');const saved=(await fixture.db.from('marketvision_brief_exports').select('content,content_hash').eq('property_id',fixture.property).single()).data!;expect(saved.content_hash).toBe(createHash('sha256').update(saved.content).digest('hex'));expect(saved.content).toContain(r.id);expect(saved.content).toContain('historical report');
 await page.reload();await expect(panel(page).getByRole('heading',{name:'Saved brief details',exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});await panel(page).getByRole('heading',{name:'Saved brief details',exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('market-brief-mobile.png')})
})

test('prepared reports complete their original snapshot after source changes and preserve prior decisions',async({page,fixture})=>{
 await seedBrief(fixture);const briefId=randomUUID(),begin=await fixture.db.rpc('begin_marketvision_brief',{p_id:briefId,p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{windowDays:30,reason:'Prepared report interrupted before calculation'}});expect(begin.error).toBeNull();expect((await fixture.db.from('competitor_units').update({rent_min:9000}).eq('competitor_id',fixture.competitor)).error).toBeNull();await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),fixture.property);await page.goto('/dashboard/marketvision');const p=panel(page);await expect(p.getByRole('heading',{name:'Saved evidence awaits completion'})).toBeVisible();await expect(p.getByRole('alert')).toContainText('Source records or the reporting window changed');await p.getByLabel('Reason for report review or download').fill('Complete the original historical snapshot');await p.getByRole('button',{name:'Complete saved brief'}).click();await expect(p.getByRole('heading',{name:'Saved brief details',exact:true})).toBeVisible();expect((await latest(fixture)).result.positions[0].competitorMean).toBe(1500)
 await p.getByLabel('Reason for report review or download').fill('Review historical evidence for the meeting');await expect(p.getByRole('button',{name:'Mark for consideration'}).first()).toBeDisabled();await p.getByRole('checkbox',{name:/I understand this review refers to historical evidence/}).check();await p.getByRole('button',{name:'Mark for consideration'}).first().click();await expect(p).toContainText('Review: Marked for consideration');await p.getByLabel('Reason for report review or download').fill('Dismiss this historical prompt after review');await p.getByRole('button',{name:'Dismiss prompt'}).first().click();await expect(p).toContainText('Review: Dismissed');expect((await fixture.db.from('marketvision_decisions').select('id').eq('property_id',fixture.property).eq('kind','brief.reviewed')).data).toHaveLength(2);expect((await page.request.get(`/api/marketvision/brief?propertyId=${fixture.otherProperty}&requestId=${briefId}`)).status()).toBe(404)
})

test('failed history is visible, pagination reaches all reports and legacy narratives remain readable',async({page,fixture})=>{
 await seedBrief(fixture);for(let i=0;i<22;i++){const r=await fixture.db.rpc('begin_marketvision_brief',{p_id:randomUUID(),p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{windowDays:7,reason:`Saved history report ${i}`}});expect(r.error).toBeNull()}
 expect((await fixture.db.from('market_insights').insert({property_id:fixture.property,insight_type:'market_brief',data:{insights:[{headline:'Original historical headline',detail:'Retained prior narrative'}]}})).error).toBeNull()
 await page.route('**/api/marketvision/brief?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved report history unavailable'})}));await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),fixture.property);await page.goto('/dashboard/marketvision');const p=panel(page);await expect(p.getByRole('alert')).toContainText('Saved report history unavailable');await expect(p).not.toContainText('No saved-source briefs yet.');await expect(p.getByRole('button',{name:'Save new brief',exact:true})).toBeDisabled();await page.unroute('**/api/marketvision/brief?*');await p.getByRole('button',{name:'Reload saved briefs'}).click();await expect(p.getByRole('button',{name:/Needs local completion/})).toHaveCount(20);await p.getByRole('button',{name:'Older briefs',exact:true}).click();await expect(p.getByRole('button',{name:/Needs local completion/})).toHaveCount(22);await p.getByText('Earlier briefs (1)',{exact:true}).click();await p.getByRole('button',{name:'Load earlier reports'}).click();await p.getByRole('button',{name:/Open historical report/}).click();await expect(p).toContainText('Original historical headline');await expect(p).toContainText('Unverified historical narrative');expect((await page.request.post('/api/marketvision/report',{data:{propertyId:fixture.property,insightType:'market_brief',data:{fake:true}}})).status()).toBe(410)
})
