import {expect,test as base,type Page,type Locator} from '@playwright/test'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {execFileSync} from 'node:child_process'
const org='22222222-2222-2222-2222-222222222222',actor='11111111-1111-1111-1111-111111111111',dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||'',client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={db:ReturnType<typeof client>;property:string;other:string}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),other=randomUUID()
 try{expect((await db.from('properties').insert([{id:property,org_id:org,name:'Floor-plan browser fixture'},{id:other,org_id:org,name:'Other floor-plan browser fixture'}])).error).toBeNull();expect((await db.from('property_chatbot_contexts').insert({property_id:property,status:'current',requires_review:false,context_markdown:'Earlier context',last_generated_at:new Date().toISOString()})).error).toBeNull();await provide({db,property,other})}
 finally{for(const id of[property,other]){
  execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;CREATE TEMP TABLE fixture_contexts AS SELECT id FROM public.shared_context_snapshots WHERE property_id='${id}';CREATE TEMP TABLE fixture_jobs AS SELECT id FROM public.shared_jobs WHERE property_id='${id}';SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${id}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${id}';SET LOCAL session_replication_role=origin;DELETE FROM public.properties WHERE id='${id}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);DELETE FROM public.shared_context_snapshots WHERE id IN(SELECT id FROM fixture_contexts);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of['property_units','property_unit_workspaces','property_unit_versions','property_unit_decisions','assistant_fact_versions','documents','shared_action_events'])expect((await db.from(table).select('*',{count:'exact',head:true}).eq('property_id',id)).count).toBe(0)
 }}
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})
test.setTimeout(180000)
async function open(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/community');await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();const w=page.getByRole('region',{name:'Reviewed floor plans'});await expect(w).toContainText('0 total');return w}
async function reason(w:Locator){await w.getByLabel('Reason for this floor-plan decision',{exact:true}).fill('Review synthetic exact source facts')}
async function fill(w:Locator){for(const[label,value]of[['Floor-plan name','Exact studio'],['Stable floor-plan identifier','studio-zero'],['Bedrooms (0 for studio)','0'],['Minimum monthly rent (usd)','0'],['Deposit (USD)','0'],['Available units','0'],['Reported source','Staff confirmation'],['Private source evidence','Private exact staff quote 🏡']])await w.getByLabel(label,{exact:true}).fill(value);await reason(w)}
async function add(w:Locator){await w.getByRole('button',{name:'Add floor-plan draft'}).click();await fill(w);await w.getByRole('button',{name:'Save private floor-plan draft'}).click();await expect(w.getByLabel('Selected floor-plan review')).toBeVisible()}
async function approve(w:Locator){await reason(w);await w.getByRole('checkbox').check();await w.getByRole('button',{name:'Approve exact floor-plan facts'}).click();await expect(w).toContainText('This exact version supplies the current shared facts.')}
async function rows(f:Fixture){const result=await f.db.from('property_units').select('*').eq('property_id',f.property);expect(result.error).toBeNull();return result.data!}
async function serving(f:Fixture){const r=await f.db.rpc('read_serving_assistant_facts',{p_property_id:f.property});expect(r.error).toBeNull();return r.data}
async function publishFacts(page:Page){const f=page.getByRole('region',{name:'Reviewed assistant facts'});await f.getByRole('button',{name:'Reload current facts'}).click();await f.getByLabel('Reason for this facts decision',{exact:true}).fill('Review complete approved floor-plan facts');await f.getByRole('button',{name:'Prepare complete facts draft'}).click();await expect(f.getByLabel('Exact retained facts')).toBeVisible();await f.getByLabel('Reason for this facts decision',{exact:true}).fill('Publish exact reviewed floor-plan facts');await f.getByRole('checkbox').check();await f.getByRole('button',{name:'Publish reviewed facts',exact:true}).click();await expect(f).toContainText('Reviewed facts available to Luma')}

test('reviewed floor-plan lifecycle keeps zero and unknown distinct and invalidates adopted assistant facts only after approval',async({page,fixture},info)=>{
 const w=await open(page,fixture);await add(w);expect(await rows(fixture)).toHaveLength(0);await expect(w).toContainText('Studio');await expect(w).toContainText('Unknown');await approve(w);expect(await rows(fixture)).toMatchObject([{bedrooms:0,rent_min:0,rent_max:null,available_count:0,bathrooms:null}]);await publishFacts(page);expect((await serving(fixture)).contextMarkdown).toContain('Exact studio');expect((await serving(fixture)).contextMarkdown).not.toContain('Private exact staff quote');const unit=(await rows(fixture))[0],first=(await fixture.db.from('property_unit_workspaces').select('*').eq('id',unit.id).single()).data!.applied_version_id
 await w.getByRole('button',{name:'Create a new draft from these facts'}).click();await w.getByLabel('Minimum monthly rent (usd)',{exact:true}).fill('25');await reason(w);await w.getByRole('button',{name:'Save private floor-plan draft'}).click();await expect(w).toContainText('Latest private draft');expect((await rows(fixture))[0].rent_min).toBe(0);expect((await serving(fixture)).state).toBe('ready');await reason(w);await w.getByRole('checkbox').check();await w.getByRole('button',{name:'Reject this draft'}).click();await expect(w).toContainText('This draft was rejected.');expect((await serving(fixture)).state).toBe('ready');await expect(w.getByRole('button',{name:'Approve exact floor-plan facts'})).toHaveCount(0)
 await w.getByRole('button',{name:'Read approved version'}).click();await expect(w).toContainText('This exact version supplies');await w.getByRole('button',{name:'Create a new draft from these facts'}).click();await w.getByLabel('Minimum monthly rent (usd)',{exact:true}).fill('30');await reason(w);await w.getByRole('button',{name:'Save private floor-plan draft'}).click();await expect(w).toContainText('Latest private draft');await approve(w);expect((await rows(fixture))[0].rent_min).toBe(30);expect((await serving(fixture)).state).toBe('withheld');const versions=await fixture.db.from('property_unit_versions').select('*').eq('unit_id',unit.id).order('version_sequence');expect(versions.data).toHaveLength(3);expect(versions.data![2]).toMatchObject({copied_from_version_id:first,parent_version_id:versions.data![1].id})
 const sourceTime=(await rows(fixture))[0].source_updated_at;await reason(w);await w.getByRole('checkbox').check();await w.getByRole('button',{name:'Retire current floor plan'}).click();await expect(w.getByRole('button',{name:'Restore reviewed floor plan'})).toBeVisible();expect((await rows(fixture))[0].active).toBe(false);await reason(w);await w.getByRole('checkbox').check();await w.getByRole('button',{name:'Restore reviewed floor plan'}).click();await expect(w.getByRole('button',{name:'Retire current floor plan'})).toBeVisible();expect((await rows(fixture))[0]).toMatchObject({active:true,source_updated_at:sourceTime})
 await w.getByRole('button',{name:'Floor-plan version history'}).click();await expect(w).toContainText('Showing 3 of 3.');await w.getByRole('button',{name:'Read floor-plan version'}).last().click();await expect(w).toContainText('Historical version');await expect(page).toHaveURL(new RegExp('unitVersion='+first));await page.reload();await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await expect(w).toContainText('Historical version');await w.getByRole('button',{name:'Floor-plan decision history'}).click();await expect(w).toContainText('Showing 8 of 8.')
 await page.setViewportSize({width:390,height:844});await w.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('reviewed-units-mobile.png')});const events=await fixture.db.from('shared_action_events').select('request,result,training_eligible').eq('property_id',fixture.property);expect(events.data!.every(e=>!e.training_eligible)).toBe(true);expect(JSON.stringify(events.data)).not.toContain('Private exact staff quote');expect((await fixture.db.from('shared_jobs').select('*',{count:'exact',head:true}).eq('property_id',fixture.property)).count).toBe(0)
})
test('lost save reply recovers one exact private draft and cancellation fences unused delayed writes',async({page,fixture})=>{
 const w=await open(page,fixture);let lost=false;await page.route('**/api/property-units',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='save'&&!lost){lost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await w.getByRole('button',{name:'Add floor-plan draft'}).click();await fill(w);await w.getByRole('button',{name:'Save private floor-plan draft'}).click();await expect(w).toContainText('A previous save floor-plan decision is unconfirmed.');expect(await page.evaluate(id=>sessionStorage.getItem('p11.units.pending.v1:'+id),fixture.property)).not.toContain('Private exact staff quote');await page.reload();await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await w.getByRole('button',{name:'Check saved floor-plan decision'}).click();await expect(w.getByLabel('Selected floor-plan review')).toBeVisible();expect((await fixture.db.from('property_unit_versions').select('*',{count:'exact',head:true}).eq('property_id',fixture.property)).count).toBe(1);await page.unroute('**/api/property-units')
 let delayed:Record<string,unknown>|null=null;await page.route('**/api/property-units',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().operation==='save'&&!delayed){delayed=route.request().postDataJSON();await route.abort('failed')}else await route.continue()});await w.getByRole('button',{name:'Create a new draft from these facts'}).click();await reason(w);await w.getByRole('button',{name:'Save private floor-plan draft'}).click();await expect(w).toContainText('A previous save floor-plan decision is unconfirmed.');await w.getByRole('button',{name:'Cancel unused floor-plan decision'}).click();await expect(w).toContainText('Unused floor-plan decision cancelled.');const copy=delayed as unknown as Record<string,unknown>,input={...copy};delete input.requestId;delete input.propertyId;delete input.operation;expect((await fixture.db.rpc('save_property_unit_draft',{p_id:copy.requestId,p_property_id:fixture.property,p_actor_id:actor,p_input:input})).data.state).toBe('decision_cancelled');expect(await rows(fixture)).toHaveLength(0)
})
test('legacy unit change during review is held and a refreshed draft explicitly adopts the current record',async({page,fixture})=>{
 const w=await open(page,fixture),id=randomUUID();expect((await fixture.db.from('property_units').insert({id,property_id:fixture.property,org_id:org,canonical_key:'legacy','unit_type':'Legacy studio',bedrooms:0,rent_min:100})).error).toBeNull();await w.getByRole('button',{name:'Reload floor plans'}).click();await w.getByRole('button',{name:/^Legacy studio/}).click();await expect(w).toContainText('Earlier inventory record.');await w.getByRole('button',{name:'Review earlier floor-plan facts'}).click();await w.getByLabel('Reported source',{exact:true}).fill('Fresh staff confirmation');await w.getByLabel('Private source evidence',{exact:true}).fill('Confirmed updated exact price');await w.getByLabel('Source confirmed at',{exact:true}).fill('2026-09-01T10:00');await reason(w);await w.getByRole('button',{name:'Save private floor-plan draft'}).click();await expect(w).toContainText('Latest private draft');expect((await fixture.db.from('property_units').update({rent_min:200}).eq('id',id)).error).toBeNull();await reason(w);await w.getByRole('checkbox').check();await w.getByRole('button',{name:'Approve exact floor-plan facts'}).click();await expect(w.getByRole('alert')).toContainText('current floor-plan facts changed');expect((await rows(fixture))[0].rent_min).toBe(200);await w.getByRole('button',{name:'Reload floor plans'}).click();await expect(w.getByRole('button',{name:'Approve exact floor-plan facts'})).toBeDisabled();await w.getByRole('button',{name:'Create a new draft from these facts'}).click();await w.getByLabel('Minimum monthly rent (usd)',{exact:true}).fill('200');await reason(w);await w.getByRole('button',{name:'Save private floor-plan draft'}).click();await expect(w.getByRole('button',{name:'Approve exact floor-plan facts'})).toBeVisible();await approve(w);expect((await fixture.db.from('property_units').update({rent_min:300}).eq('id',id)).error).not.toBeNull();expect((await rows(fixture))[0]).toMatchObject({rent_min:200,source_identity:'console-review'})
})
test('complete inventory paging, unavailable reads and property switching preserve current scope',async({page,fixture})=>{
 const w=await open(page,fixture);expect((await fixture.db.from('property_units').insert(Array.from({length:24},(_,i)=>({id:randomUUID(),property_id:fixture.property,org_id:org,canonical_key:'unit-'+i,unit_type:'Inventory unit '+i,bedrooms:1})))).error).toBeNull();await w.getByRole('button',{name:'Reload floor plans'}).click();await expect(w).toContainText('Showing 20 of 24 matching floor plans.');await w.getByRole('button',{name:'Load more floor plans'}).click();await expect(w).toContainText('Showing 24 of 24 matching floor plans.');await w.getByRole('button',{name:/^Inventory unit 0/}).click();await expect(w.getByLabel('Selected floor-plan review')).toBeVisible();await page.route('**/api/property-units?*',route=>route.fulfill({status:503,json:{error:'Fixture unit reads unavailable'}}));await w.getByRole('button',{name:'Reload floor plans'}).click();await expect(w.getByRole('alert')).toContainText('unavailable');await expect(w.getByLabel('Selected floor-plan review')).toHaveCount(0);await page.unroute('**/api/property-units?*');await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.other);await page.getByRole('button',{name:'Knowledge Base',exact:true}).click();await expect(w).toContainText('0 total');await expect(w.getByLabel('Selected floor-plan review')).toHaveCount(0)
})
