import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow cases browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other cases browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['reviews','reviewflow_analysis_requests','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Case browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})
async function openReview(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analysis fixture reviewer',{exact:true}).click();await expect(page.getByRole('region',{name:'Case decisions'})).toBeVisible();await expect(page.getByText('Loading saved case…')).toHaveCount(0)}
async function dropReply(page:Page,method:string){let dropped=false;await page.route('**/api/reviewflow/cases',async route=>{if(route.request().method()===method&&!dropped){dropped=true;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort('failed')}else await route.continue()})}


test('staff case and ticket lifecycle survives lost replies and preserves actual resolution history',async({page,fixture},info)=>{
 await openReview(page,fixture);const panel=page.getByRole('region',{name:'Case decisions'});await panel.getByLabel('Reason for case decision',{exact:true}).fill('Staff reviewed the source review');await dropReply(page,'PATCH');await panel.getByRole('button',{name:'Open case',exact:true}).click();await panel.getByRole('button',{name:'Retry same case decision'}).click();await expect(panel.getByText('Case: open',{exact:false})).toBeVisible();await page.unroute('**/api/reviewflow/cases')
 await panel.getByText('Assignment, priority and follow-up',{exact:true}).click();await panel.getByLabel('Reason for case decision',{exact:true}).fill('Assign follow-up responsibility');await panel.getByLabel('Case priority',{exact:true}).selectOption('high');await panel.getByLabel('Case owner').selectOption(fixture.actor);await panel.getByRole('button',{name:'Save case details'}).click();await expect(panel.getByText('case updated',{exact:true})).toBeVisible()
 await panel.getByLabel('Reason for case decision',{exact:true}).fill('Create the staff follow-up task');await panel.getByText('Create staff ticket',{exact:true}).click();await panel.getByLabel('Ticket title',{exact:true}).fill('Inspect pool maintenance');await panel.getByLabel('Ticket details',{exact:true}).fill('Staff will inspect the saved source issue.');await panel.getByRole('button',{name:'Save staff ticket'}).click();const ticket=panel.getByRole('article',{name:'Staff ticket Inspect pool maintenance',exact:true});await expect(ticket).toBeVisible()
 await panel.getByLabel('Reason for case decision',{exact:true}).fill('Attempt closure before work is done');await panel.getByLabel('Resolution or dismissal evidence').fill('This should remain blocked while staff work is open.');await panel.getByRole('button',{name:'Resolve case',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('remaining tickets');await panel.getByRole('button',{name:'Reload case',exact:true}).click();await expect(panel.getByRole('alert')).toHaveCount(0)
 await ticket.getByText('Review ticket',{exact:true}).click();await ticket.getByLabel('Reason for ticket decision').fill('Staff inspected the pool');await ticket.getByLabel('Ticket status',{exact:true}).selectOption('resolved');await ticket.getByLabel('Ticket resolution evidence').fill('Inspection completed and condition verified by staff.');await ticket.getByRole('button',{name:'Save ticket decision'}).click();await expect(ticket).toContainText('Inspection completed and condition verified by staff.')
 await panel.getByLabel('Reason for case decision',{exact:true}).fill('Review completed staff work');await panel.getByLabel('Resolution or dismissal evidence').fill('Staff confirmed the maintenance outcome.');await panel.getByRole('button',{name:'Resolve case',exact:true}).click();await expect(panel.getByRole('button',{name:'Reopen case',exact:true})).toBeVisible();await ticket.getByText('Review ticket',{exact:true}).click();await expect(ticket.getByRole('button',{name:'Reopen ticket',exact:true})).toBeDisabled()
 await panel.getByLabel('Reason for case decision',{exact:true}).fill('A new follow-up needs staff review');await panel.getByRole('button',{name:'Reopen case',exact:true}).click();await expect(panel).toContainText('Reopened 1 time(s)');await ticket.getByText('Review ticket',{exact:true}).click();await ticket.getByLabel('Reason for ticket decision').fill('Reinspect after new resident information');await ticket.getByRole('button',{name:'Reopen ticket',exact:true}).click();await expect(ticket).toContainText('Inspect pool maintenance · open')
 const cases=await fixture.db.from('reputation_cases').select('status,reopened_count').eq('review_id',fixture.review);expect(cases.data).toEqual([{status:'triaged',reopened_count:1}]);const events=await fixture.db.from('shared_action_events').select('action').eq('property_id',fixture.property).like('action','review.%');expect(events.data).toHaveLength(7);const prior=await fixture.db.from('reputation_case_events').select('payload').eq('property_id',fixture.property).eq('event_type','case.reopened').single();expect(prior.data?.payload.previousResolution).toBe('Staff confirmed the maintenance outcome.');expect((await fixture.db.from('review_responses').select('id').eq('review_id',fixture.review)).data).toHaveLength(0)
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await panel.getByRole('heading',{name:'Case and staff work',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('case-mobile.png')})
})

test('ticket list exposes real staff work, recovers read errors and opens its working case controls',async({page,fixture})=>{
 const create=await page.request.patch('/api/reviewflow/cases',{data:{propertyId:fixture.property,requestId:randomUUID(),reviewId:fixture.review,sourceVersion:1,action:'create',reason:'Open staff case fixture'}});expect(create.ok()).toBe(true);const c=(await create.json()).result
 const ticket=await page.request.patch('/api/reviewflow/cases',{data:{propertyId:fixture.property,requestId:randomUUID(),reviewId:fixture.review,sourceVersion:1,caseId:c.caseId,expectedVersion:c.caseVersion,action:'ticket.create',reason:'Create staff work fixture',title:'Inspection from saved case',description:'Verify staff follow-up',priority:'high',ownerId:fixture.actor}});expect(ticket.ok()).toBe(true)
 await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),fixture.property);await page.route('**/api/reviewflow/tickets?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Staff tickets temporarily unavailable'})}));await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Tickets',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Staff tickets temporarily unavailable'})).toBeVisible();await expect(page.getByText('No saved tickets match these filters.')).toHaveCount(0);await page.unroute('**/api/reviewflow/tickets?*');await page.getByRole('button',{name:'Reload tickets'}).click();await expect(page.getByRole('heading',{name:'Inspection from saved case'})).toBeVisible();await page.getByRole('button',{name:'Review case and ticket'}).click();await expect(page.getByRole('dialog',{name:'Ticket case workspace'})).toBeVisible();await expect(page.getByRole('region',{name:'Case decisions'}).getByRole('article',{name:'Staff ticket Inspection from saved case'})).toBeVisible();await page.getByRole('button',{name:'Close ticket workspace'}).click();await page.getByLabel('Filter ticket status').selectOption('resolved');await expect(page.getByText('No saved tickets match these filters.')).toBeVisible()
})

test('case history pages retain notes and reject cursors from another property',async({page,fixture})=>{
 let saved=await page.request.patch('/api/reviewflow/cases',{data:{propertyId:fixture.property,requestId:randomUUID(),reviewId:fixture.review,sourceVersion:1,action:'create',reason:'Create paginated case'}});expect(saved.ok()).toBe(true);let c=(await saved.json()).result;let cursor=''
 for(let i=0;i<31;i++){cursor=randomUUID();saved=await page.request.patch('/api/reviewflow/cases',{data:{propertyId:fixture.property,requestId:cursor,reviewId:fixture.review,sourceVersion:1,caseId:c.caseId,expectedVersion:c.caseVersion,action:'note',reason:'Record follow-up evidence',note:`Follow-up note ${i+1}`}});expect(saved.ok()).toBe(true);c=(await saved.json()).result}
 await openReview(page,fixture);const panel=page.getByRole('region',{name:'Case decisions'});await expect(panel.getByText('Follow-up note 1',{exact:true})).toHaveCount(0);await panel.getByRole('button',{name:'Load more case history'}).click();await expect(panel.getByText('Follow-up note 1',{exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:'Load more case history'})).toHaveCount(0)
 const wrong=await page.request.get(`/api/reviewflow/cases?propertyId=${fixture.otherProperty}&reviewId=${fixture.review}&cursor=${cursor}`);expect(wrong.status()).toBe(404)
})


test('a delayed drawer refresh cannot erase a newer case validation error',async({page,fixture})=>{
 const created=await page.request.patch('/api/reviewflow/cases',{data:{propertyId:fixture.property,requestId:randomUUID(),reviewId:fixture.review,sourceVersion:1,action:'create',reason:'Prepare delayed refresh fixture'}});expect(created.ok()).toBe(true);await openReview(page,fixture);const panel=page.getByRole('region',{name:'Case decisions'});await expect(panel.getByText('Case: open',{exact:false})).toBeVisible()
 let release!:()=>void,started!:()=>void;const released=new Promise<void>(resolve=>{release=resolve}),seen=new Promise<void>(resolve=>{started=resolve});let held=false
 await page.route('**/api/reviewflow/reviews?*',async route=>{if(route.request().url().includes(`reviewId=${fixture.review}`)&&!held){held=true;const reply=await route.fetch();const body=await reply.json();body.reviews[0].reviewer_name='Refreshed fixture reviewer';started();await released;await route.fulfill({response:reply,json:body})}else await route.continue()})
 try{
  await panel.getByLabel('Reason for case decision',{exact:true}).fill('Create a ticket before the delayed refresh');await panel.getByText('Create staff ticket',{exact:true}).click();await panel.getByLabel('Ticket title',{exact:true}).fill('Unfinished staff work');await panel.getByRole('button',{name:'Save staff ticket'}).click();await expect(panel.getByRole('article',{name:'Staff ticket Unfinished staff work'})).toBeVisible();await seen
  await panel.getByLabel('Reason for case decision',{exact:true}).fill('Attempt closure with unfinished staff work');await panel.getByLabel('Resolution or dismissal evidence').fill('Closure must remain blocked until the work is complete.');await panel.getByRole('button',{name:'Resolve case',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('remaining tickets')
  const completed=page.waitForResponse(r=>r.url().includes('/api/reviewflow/reviews?')&&r.url().includes(`reviewId=${fixture.review}`));release();await completed;await expect(page.getByRole('heading',{name:'Review from Refreshed fixture reviewer'})).toBeVisible();await expect(panel.getByRole('alert')).toContainText('remaining tickets');await expect(panel.getByRole('button',{name:'Retry same case decision'})).toBeVisible();await panel.getByRole('button',{name:'Reload case',exact:true}).click();await expect(panel.getByRole('alert')).toHaveCount(0)
 }finally{release();await page.unroute('**/api/reviewflow/reviews?*')}
})
