import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow overview browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other overview browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['reviews','reviewflow_insight_reports','reviewflow_analysis_batches','reviewflow_analysis_batch_items','reviewflow_analysis_requests','reviewflow_response_generation_requests','reviewflow_publications','reviewflow_intake_requests','reviewflow_intake_observations','reviewflow_configuration_revisions','reviewflow_connection_revisions','review_responses','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})

async function workspace(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');const p=page.getByRole('region',{name:'Review work queue'});await expect(p.getByRole('status')).toHaveCount(0);return p}
async function check(p:PromiseLike<{error:unknown}>){expect((await p).error).toBeNull()}
async function intake(page:Page,f:Fixture,n:number){const r=await page.request.post('/api/reviewflow/intake',{data:{propertyId:f.property,requestId:randomUUID(),action:'save',kind:'manual',reason:'Reviewed isolated source',content:JSON.stringify({platform:'other',platformReviewId:`saved-preview-${n}`,reviewerName:`Recovery source ${n}`,reviewText:`Exact saved import ${n}`})}});expect(r.ok(),await r.text()).toBe(true);return(await r.json()).result}

test('Today preserves open staff work, pages the full queue and opens full review evidence',async({page,fixture},info)=>{
 await check(fixture.db.from('reviews').update({rating:null,created_at:'2024-01-01T00:00:00Z',review_text:'An older urgent review with complete saved evidence.'}).eq('id',fixture.review));const version=await fixture.db.from('reviews').select('source_version').eq('id',fixture.review).single();await check(fixture.db.from('review_analyses').insert({review_id:fixture.review,property_id:fixture.property,source_version:version.data!.source_version,analysis_version:1,taxonomy_version:'multifamily-v1',model:'isolated-fixture',prompt_version:'analysis-v3',status:'completed',sentiment:'negative',is_urgent:true}))
 const rows=Array.from({length:25},(_,i)=>({id:randomUUID(),property_id:fixture.property,platform:'other',platform_review_id:`overview-${i}`,reviewer_name:`Queue fixture ${i}`,review_text:`Queue source ${i}`}));await check(fixture.db.from('reviews').insert(rows));await check(fixture.db.from('reputation_cases').insert({review_id:rows[0].id,property_id:fixture.property,status:'open',priority:'medium'}));await check(fixture.db.from('reviews').update({response_status:'posted'}).eq('id',rows[0].id));const p=await workspace(page,fixture)
 await expect(p).toContainText('26 reviews need attention across 26 saved reviews.');await expect(p.getByText('High risk and urgent (1)',{exact:true})).toBeVisible();await expect(p.getByText('Open staff cases (1)',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Review statistics'})).toContainText('No rated reviews');const needs=p.locator('details').filter({hasText:'Needs a response (24)'});await expect(needs.getByRole('button')).toHaveCount(11);await needs.getByRole('button',{name:'Load more needs a response'}).click();await expect(needs.getByRole('button')).toHaveCount(21);await needs.getByRole('button',{name:'Load more needs a response'}).click();await expect(needs.getByRole('button')).toHaveCount(24)
 await page.setViewportSize({width:390,height:844});await p.getByRole('heading',{name:'Current review workload'}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('overview-mobile.png')});await p.getByRole('button',{name:/Analysis fixture reviewer/}).click();await expect(page.getByRole('heading',{name:'Review from Analysis fixture reviewer'})).toBeVisible();await expect(page.getByRole('paragraph').filter({hasText:/^An older urgent review with complete saved evidence\.$/})).toBeVisible()
})

test('failed overview reads never look like empty success, and changed queue paging requires reload',async({page,fixture})=>{
 await page.route('**/api/reviewflow/recovery?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved work temporarily unavailable'})}));await page.route('**/api/reviewflow/stats?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Statistics temporarily unavailable'})}));const p=await workspace(page,fixture);await expect(p.getByRole('alert')).toContainText('temporarily unavailable');await expect(p.getByText('No saved review or recovery work currently needs attention.')).toHaveCount(0);await expect(page.getByRole('button',{name:'Retry review statistics'})).toBeVisible();await page.unroute('**/api/reviewflow/recovery?*');await page.unroute('**/api/reviewflow/stats?*');await p.getByRole('button',{name:'Reload review queues'}).click();await page.getByRole('button',{name:'Retry review statistics'}).click();await expect(p).toContainText('1 reviews need attention across 1 saved reviews.');await expect(page.getByRole('region',{name:'Review statistics'})).toBeVisible()
 await check(fixture.db.from('reviews').insert(Array.from({length:15},(_,i)=>({property_id:fixture.property,platform:'other',platform_review_id:`page-${i}`,review_text:`Paged source ${i}`}))));await p.getByRole('button',{name:'Reload review queues'}).click();await expect(p).toContainText('16 saved reviews.');await check(fixture.db.from('reviews').update({review_text:'Changed source after the first queue page'}).eq('id',fixture.review));await p.getByRole('button',{name:'Load more needs a response'}).click();await expect(p.getByRole('alert')).toContainText('workload changed');await p.getByRole('button',{name:'Reload review queues'}).click();await expect(p.getByRole('alert')).toHaveCount(0);await p.getByRole('button',{name:'Load more needs a response'}).click();await expect(p.getByRole('button',{name:'Load more needs a response'})).toHaveCount(0)
 await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);await expect(p).toContainText('0 saved reviews.');await expect(p).toContainText('No saved review or recovery work currently needs attention.');await expect(page.getByRole('region',{name:'Review statistics'})).toContainText('No eligible reviews');await expect(p).not.toContainText('Changed source after the first queue page')
})

test('saved-work recovery pages all pending imports and opens the exact import and analysis selection',async({page,fixture})=>{
 for(let i=1;i<=21;i++)await intake(page,fixture,i);const b=await page.request.post('/api/reviewflow/analyze-batch',{data:{propertyId:fixture.property,requestId:randomUUID(),action:'prepare',scope:'unanalyzed_current',reason:'Reviewed saved full selection'}});expect(b.ok(),await b.text()).toBe(true);const p=await workspace(page,fixture),r=p.getByRole('article',{name:'Saved work needing review'});await expect(r).toContainText('Saved work needing review (22)');await expect(r.getByRole('button',{name:'Open saved import',exact:true})).toHaveCount(20);await r.getByRole('button',{name:'Load more saved work'}).click();await expect(r.getByRole('button',{name:'Open saved import',exact:true})).toHaveCount(21);await expect(r.getByRole('button',{name:'Load more saved work'})).toHaveCount(0)
 await r.getByRole('button',{name:'Open saved import',exact:true}).last().click();await expect(page.getByRole('article',{name:'Saved import preview'})).toContainText('Exact saved import 21');await page.getByRole('button',{name:'Today',exact:true}).click();await r.getByRole('button',{name:'Load more saved work'}).click();await r.getByRole('button',{name:'Open saved analysis queue'}).click();await expect(page.getByRole('article',{name:'Saved analysis selection'})).toContainText('1 exact review versions selected');expect((await fixture.db.from('reviewflow_analysis_requests').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
})
