import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow insights browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other insights browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['reviews','reviewflow_insight_reports','reviewflow_analysis_batches','reviewflow_analysis_batch_items','reviewflow_analysis_requests','reviewflow_response_generation_requests','reviewflow_publications','reviewflow_intake_requests','reviewflow_intake_observations','reviewflow_configuration_revisions','reviewflow_connection_revisions','review_responses','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})

async function workspace(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Insights',exact:true}).click();const panel=page.getByRole('region',{name:'Review insights'});await expect(panel.getByText('Loading review evidence…')).toHaveCount(0);return panel}
async function analysis(f:Fixture){const r=await f.db.from('review_analyses').insert({review_id:f.review,property_id:f.property,source_version:1,analysis_version:1,taxonomy_version:'multifamily-v1',model:'isolated-fixture',prompt_version:'analysis-v3',status:'completed',sentiment:'positive',issue_domains:['amenities']});expect(r.error).toBeNull()}
async function drop(page:Page){let dropped=false;await page.route('**/api/reviewflow/insights',async r=>{if(r.request().method()==='POST'&&!dropped){dropped=true;const response=await r.fetch();expect(response.ok()).toBe(true);await r.abort('failed')}else await r.continue()})}

test('insight reports recover a lost save and retain exact prior evidence after a review changes',async({page,fixture},info)=>{
 await analysis(fixture);const p=await workspace(page,fixture);await expect(p).toContainText('1 of 1 stored reviews have current analysis');await expect(p).toContainText('1 reviews use import date');await p.getByLabel('Reason for saving this report').fill('Monthly source review');await drop(page);await p.getByRole('button',{name:'Save exact insight report'}).click();await p.getByRole('button',{name:'Retry same report save'}).click();await expect(p).toContainText('Saved report from');await page.unroute('**/api/reviewflow/insights');const reports=await fixture.db.from('reviewflow_insight_reports').select('id').eq('property_id',fixture.property);expect(reports.data).toHaveLength(1);expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','review.insights.saved')).data).toHaveLength(1)
 expect((await fixture.db.from('reviews').update({review_text:'The pool is currently closed.'}).eq('id',fixture.review)).error).toBeNull();await p.getByRole('button',{name:'Refresh current insights'}).click();await expect(p).toContainText('0 of 1 stored reviews have current analysis');await p.getByText('Saved insight reports',{exact:true}).click();await p.getByRole('button',{name:/90-day report.*Monthly source review/}).click();await expect(p).toContainText('1 of 1 stored reviews have current analysis');await expect(p).toContainText('The pool was clean.');expect((await page.request.get(`/api/reviewflow/insights?propertyId=${fixture.otherProperty}&reportId=${reports.data![0].id}`)).status()).toBe(404)
 await page.reload();await page.getByRole('button',{name:'Insights',exact:true}).click();await p.getByText('Saved insight reports',{exact:true}).click();await p.getByRole('button',{name:/90-day report.*Monthly source review/}).click();await expect(p).toContainText('The pool was clean.');await page.setViewportSize({width:390,height:844});await p.getByRole('heading',{name:'Review evidence and trends'}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('insights-mobile.png')})
 await p.getByRole('button',{name:'Open amenities evidence 1'}).click();await expect(page.getByRole('heading',{name:'Review from Analysis fixture reviewer'})).toBeVisible()
})

test('a changed preview requires refresh before saving and failed history reads remain visible',async({page,fixture})=>{
 const p=await workspace(page,fixture);await p.getByLabel('Reason for saving this report').fill('Review current source');expect((await fixture.db.from('reviews').update({review_text:'A correction after preview'}).eq('id',fixture.review)).error).toBeNull();await p.getByRole('button',{name:'Save exact insight report'}).click();await expect(p.getByRole('alert')).toContainText('report source changed');expect((await fixture.db.from('reviewflow_insight_reports').select('id').eq('property_id',fixture.property)).data).toHaveLength(0);await p.getByRole('button',{name:'Refresh current insights'}).click();await expect(p.getByRole('alert')).toHaveCount(0);await p.getByRole('button',{name:'Save exact insight report'}).click();await expect(p).toContainText('Saved report from')
 await p.getByText('Saved insight reports',{exact:true}).click();await page.route('**/api/reviewflow/insights?*history=true*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved report history unavailable'})}));await p.getByRole('button',{name:'Reload report history'}).click();await expect(p.getByRole('alert')).toContainText('history unavailable');await page.unroute('**/api/reviewflow/insights?*history=true*');await p.getByRole('button',{name:'Reload report history'}).click();await expect(p.getByRole('alert')).toHaveCount(0)
 await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);await page.getByRole('button',{name:'Insights',exact:true}).click();await expect(p).toContainText('0 of 0 stored reviews');await expect(p).not.toContainText('A correction after preview')
})

test('review search reaches beyond the loaded page, preserves literal punctuation and recovers failed reads',async({page,fixture})=>{
 const literal='Literal 100% _ * commas, "quotes" back\\slash';expect((await fixture.db.from('reviews').update({review_text:literal,created_at:'2026-01-01T00:00:00Z'}).eq('id',fixture.review)).error).toBeNull();expect((await fixture.db.from('reviews').insert(Array.from({length:35},(_,i)=>({property_id:fixture.property,platform:'other',platform_review_id:`search-${i}`,review_text:`Another fixture review ${i}`,reviewer_name:`Other fixture ${i}`})))).error).toBeNull();await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),fixture.property);await page.goto('/dashboard/reviewflow');await page.route('**/api/reviewflow/reviews?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Reviews temporarily unavailable'})}));await page.getByRole('button',{name:'Reviews',exact:true}).click();await expect(page.getByRole('region',{name:'Property reviews'}).getByRole('alert')).toContainText('temporarily unavailable');await expect(page.getByText('No reviews found',{exact:true})).toHaveCount(0);await page.unroute('**/api/reviewflow/reviews?*');await page.getByRole('button',{name:'Retry review list'}).click();await expect(page.getByText('36 matching reviews across this property.')).toBeVisible();await expect(page.getByText(literal,{exact:true})).toHaveCount(0)
 await page.getByRole('textbox',{name:'Search all review text and names'}).fill('100% _ * commas, "quotes"');await expect(page.getByText('1 matching reviews across this property.')).toBeVisible();await expect(page.getByText(literal,{exact:true})).toBeVisible();await page.getByRole('textbox',{name:'Search all review text and names'}).fill('no-such-fixture-source');await expect(page.getByText('0 matching reviews across this property.')).toBeVisible();await expect(page.getByText('No reviews found',{exact:true})).toBeVisible();await page.getByRole('textbox',{name:'Search all review text and names'}).fill('Another fixture review');await expect(page.getByText('35 matching reviews across this property.')).toBeVisible();await page.getByRole('button',{name:/Load more/}).click();await expect(page.getByText('35 matching reviews across this property.')).toBeVisible();await expect(page.getByRole('button',{name:/Load more/})).toHaveCount(0)
})
