import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow analysis browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['reviews','reviewflow_analysis_requests','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})
async function openReview(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analysis fixture reviewer',{exact:true}).click();await expect(page.getByRole('region',{name:'Saved review analysis'})).toBeVisible();await expect(page.getByText('Loading saved analysis…')).toHaveCount(0)}
async function request(page:Page,f:Fixture){const id=randomUUID(),r=await page.request.post('/api/reviewflow/analyze',{data:{propertyId:f.property,requestId:id,reviewId:f.review,sourceVersion:1}});expect(r.status()).toBe(202);return id}
async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const r=await f.db.rpc(name,args);if(r.error)throw r.error;return r.data}
const classification={sentiment:'positive',sentimentScore:0.8,topics:['amenities'],journeyStage:'residency',issueDomains:['amenities'],severity:'low',riskClass:'routine',policyClass:'standard',isUrgent:false,confidence:0.95,summary:'The reviewer liked the clean pool.',recommendedAction:'Thank the reviewer.',evidence:[{claim:'Clean pool',quote:'The pool was clean.'}]}
async function saveResult(f:Fixture,id:string,claim?:string){const c=claim||((await rpc(f,'claim_reviewflow_analysis',{p_id:id})).claimToken as string);return rpc(f,'record_reviewflow_analysis_result',{p_id:id,p_claim_token:c,p_result:{status:'received',providerId:'isolated-fixture-result',content:JSON.stringify(classification)}})}
async function dropReply(page:Page,method:string){let dropped=false;await page.route('**/api/reviewflow/analyze',async route=>{if(route.request().method()===method&&!dropped){dropped=true;const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort('failed')}else await route.continue()})}

test('lost request and stop replies replay one saved decision, and stopped work retains late proof',async({page,fixture},info)=>{
 await openReview(page,fixture);const panel=page.getByRole('region',{name:'Saved review analysis'});await expect(panel).toContainText('Model execution is paused');await dropReply(page,'POST');await panel.getByRole('button',{name:'Save analysis request',exact:true}).click();await panel.getByRole('button',{name:'Retry same analysis decision'}).click();await expect(panel).toContainText('Saved; waiting to start');const requests=await fixture.db.from('reviewflow_analysis_requests').select('id,claim_token').eq('property_id',fixture.property);expect(requests.data).toHaveLength(1);expect(requests.data![0].claim_token).toBeNull();const id=requests.data![0].id,c=await rpc(fixture,'claim_reviewflow_analysis',{p_id:id});await panel.getByRole('button',{name:'Reload analysis'}).click();await expect(panel).toContainText('Started; result not yet confirmed');await page.unroute('**/api/reviewflow/analyze');await dropReply(page,'PATCH');await panel.getByLabel('Reason for analysis decision').fill('Stop saved fixture request');await panel.getByRole('button',{name:'Stop analysis',exact:true}).click();await panel.getByRole('button',{name:'Retry same analysis decision'}).click();await expect(panel.getByText('Stopped',{exact:true})).toBeVisible();await saveResult(fixture,id,c.claimToken);await panel.getByRole('button',{name:'Reload analysis'}).click();await expect(panel.getByText('Stopped',{exact:true})).toBeVisible();expect((await fixture.db.from('review_analyses').select('id').eq('property_id',fixture.property)).data).toHaveLength(0);expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','review.analysis.stopped')).data).toHaveLength(1)
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await panel.screenshot({path:info.outputPath('analysis-mobile.png')})
})

test('saved results recover during a pause after a lost reply with matching case and activity evidence',async({page,fixture})=>{
 const id=await request(page,fixture);await saveResult(fixture,id);await openReview(page,fixture);const panel=page.getByRole('region',{name:'Saved review analysis'});await expect(panel).toContainText('Result saved; ready to recover');await dropReply(page,'PATCH');await panel.getByLabel('Reason for analysis decision').fill('Recover saved source analysis');await panel.getByRole('button',{name:'Recover saved analysis',exact:true}).click();await panel.getByRole('button',{name:'Retry same analysis decision'}).click();await expect(panel.getByText('Analysis saved',{exact:true})).toBeVisible();await expect(page.getByText('The reviewer liked the clean pool.',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analysis fixture reviewer',{exact:true}).click();await expect(panel.getByText('Analysis saved',{exact:true})).toBeVisible();expect((await fixture.db.from('review_analyses').select('id,source_version').eq('property_id',fixture.property)).data).toEqual([{id,source_version:1}]);expect((await fixture.db.from('reputation_cases').select('status').eq('review_id',fixture.review)).data).toEqual([{status:'triaged'}]);expect((await fixture.db.from('shared_action_events').select('action').eq('property_id',fixture.property).in('action',['review.analysis.recovered','review.analysis.completed'])).data).toHaveLength(2);const safe=await page.request.get(`/api/reviewflow/analyze?propertyId=${fixture.property}&reviewId=${fixture.review}`);expect(await safe.text()).not.toMatch(/claim_token|model_input|raw_result|The pool was clean/)
})

test('a changed review holds an old result and new analysis uses the new source',async({page,fixture})=>{
 const id=await request(page,fixture);await saveResult(fixture,id);const edit=await fixture.db.from('reviews').update({review_text:'The pool has closed.'}).eq('id',fixture.review);if(edit.error)throw edit.error;const recover=await page.request.patch('/api/reviewflow/analyze',{data:{propertyId:fixture.property,requestId:randomUUID(),analysisRequestId:id,expectedVersion:3,action:'recover',reason:'Inspect changed source fixture'}});expect(recover.status()).toBe(200);expect((await recover.json()).request.state).toBe('held');await openReview(page,fixture);const panel=page.getByRole('region',{name:'Saved review analysis'});await expect(panel).toContainText('Based on an earlier version of this review');await expect(panel).toContainText('The review changed before this result could be applied');await panel.getByRole('button',{name:'Save analysis request',exact:true}).click();await expect(panel).toContainText('Saved; waiting to start');expect((await fixture.db.from('reviewflow_analysis_requests').select('source_version').eq('property_id',fixture.property).eq('state','queued')).data).toEqual([{source_version:2}]);expect((await fixture.db.from('review_analyses').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
})

test('history errors remain visible and changing properties closes the prior review workspace',async({page,fixture})=>{
 const id=await request(page,fixture);await page.route('**/api/reviewflow/analyze?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved analysis history unavailable'})}));await openReview(page,fixture);const panel=page.getByRole('region',{name:'Saved review analysis'});await expect(panel.getByRole('alert')).toContainText('Saved analysis history unavailable');await expect(panel.getByRole('button',{name:'Analyze current review',exact:true})).toBeDisabled();await page.unroute('**/api/reviewflow/analyze?*');await panel.getByRole('button',{name:'Reload analysis'}).click();await expect(panel).toContainText('Saved; waiting to start');const bad=await page.request.get(`/api/reviewflow/analyze?propertyId=${fixture.otherProperty}&cursor=${id}`);expect(bad.status()).toBe(409);await page.getByRole('button',{name:'Close review details'}).click();await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);await expect(page.getByRole('region',{name:'Saved review analysis'})).toHaveCount(0);await expect(page.getByText('Analysis fixture reviewer',{exact:true})).toHaveCount(0)
})
