import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow rights browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other rights browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['review_testimonial_approvals','reviews','reviewflow_insight_reports','reviewflow_analysis_batches','reviewflow_analysis_batch_items','reviewflow_analysis_requests','reviewflow_response_generation_requests','reviewflow_publications','reviewflow_intake_requests','reviewflow_intake_observations','reviewflow_configuration_revisions','reviewflow_connection_revisions','review_responses','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})

async function openReview(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analysis fixture reviewer',{exact:true}).click();const p=page.getByRole('region',{name:'Testimonial permissions'});await expect(p.getByText('Loading testimonial permissions…')).toHaveCount(0);return p}
async function fillPermission(page:Page){const p=page.getByRole('region',{name:'Testimonial permissions'});await p.getByLabel('Retained rights evidence').fill('Reviewed retained consent for this exact testimonial');await p.getByLabel('Reason for permission decision').fill('Manager checked source and rights scope');await p.getByRole('checkbox',{name:/I reviewed permission to reuse/}).check();return p}
async function drop(page:Page,method:string){let dropped=false;await page.route('**/api/reviewflow/testimonials/*',async r=>{if(r.request().method()===method&&!dropped){dropped=true;const reply=await r.fetch();expect(reply.ok(),await reply.text()).toBe(true);await r.abort('failed')}else await r.continue()})}

test('exact permissions recover lost saves, stop reuse after source changes and preserve revoked evidence',async({page,fixture},info)=>{
 const p=await openReview(page,fixture);await expect(page.getByRole('region',{name:'Property reviews'}).getByText('Not classified',{exact:true})).toBeVisible();await fillPermission(page);await drop(page,'POST');await p.getByRole('button',{name:'Save exact testimonial permission'}).click();await p.getByRole('button',{name:'Retry same permission decision'}).click();await expect(p.getByRole('article',{name:'Current testimonial permission'})).toContainText('Current permission recorded');await page.unroute('**/api/reviewflow/testimonials/*');expect((await fixture.db.from('review_testimonial_approvals').select('id').eq('property_id',fixture.property)).data).toHaveLength(1);expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','review.testimonial.approved')).data).toHaveLength(1)
 expect((await fixture.db.rpc('eligible_reviewflow_testimonials',{p_property_id:fixture.property,p_channel:'website'})).data).toHaveLength(1);expect((await fixture.db.rpc('eligible_reviewflow_testimonials',{p_property_id:fixture.property,p_channel:'social'})).data).toHaveLength(0);expect((await fixture.db.from('reviews').update({review_text:'A corrected current testimonial source.'}).eq('id',fixture.review)).error).toBeNull();await p.getByRole('button',{name:'Reload testimonial permissions'}).click();await expect(p.getByRole('article',{name:'Current testimonial permission'})).toContainText('Review source changed');await expect(p.getByRole('article',{name:'Current testimonial permission'})).toContainText('The pool was clean.');expect((await fixture.db.rpc('eligible_reviewflow_testimonials',{p_property_id:fixture.property,p_channel:'website'})).data).toHaveLength(0)
 await p.getByLabel('Reason for revoking permission').fill('Source corrected; review any previously published content');await drop(page,'DELETE');await p.getByRole('button',{name:'Revoke saved permission'}).click();await p.getByRole('button',{name:'Retry same permission decision'}).click();await expect(p.getByRole('status')).toContainText('Previously published content still requires a separate review');await page.unroute('**/api/reviewflow/testimonials/*');await expect(p.getByRole('article',{name:'Exact testimonial source'})).toContainText('A corrected current testimonial source.');expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','review.testimonial.revoked')).data).toHaveLength(1)
 await fillPermission(page);await p.getByRole('checkbox',{name:'Social marketing content'}).check();await p.getByLabel('Permission expiry').fill('2050-12-31');await p.getByRole('button',{name:'Save exact testimonial permission'}).click();await expect(p.getByRole('article',{name:'Current testimonial permission'})).toContainText('Allowed uses: website, social.');expect((await fixture.db.from('review_testimonial_approvals').select('id').eq('property_id',fixture.property)).data).toHaveLength(2);await p.getByText('Saved permission history',{exact:true}).click();await expect(p.locator('details')).toContainText('Revoked permission');await expect(p.locator('details')).toContainText('The pool was clean.')
 await page.setViewportSize({width:390,height:844});await p.getByRole('heading',{name:'Testimonial reuse permissions'}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('rights-mobile.png')})
})

test('failed rights reads remain visible and approving a changed source requires a fresh explicit review',async({page,fixture})=>{
 await page.route('**/api/reviewflow/testimonials/*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Permission history temporarily unavailable'})}));const p=await openReview(page,fixture);await expect(p.getByRole('alert')).toContainText('temporarily unavailable');await expect(p.getByText('No saved testimonial permissions.')).toHaveCount(0);await page.unroute('**/api/reviewflow/testimonials/*');await p.getByRole('button',{name:'Reload testimonial permissions'}).click();await fillPermission(page);expect((await fixture.db.from('reviews').update({review_text:'Updated source before approval'}).eq('id',fixture.review)).error).toBeNull();await p.getByRole('button',{name:'Save exact testimonial permission'}).click();await expect(p.getByRole('alert')).toContainText('review changed');expect((await fixture.db.from('review_testimonial_approvals').select('id').eq('property_id',fixture.property)).data).toHaveLength(0);await p.getByRole('button',{name:'Reload testimonial permissions'}).click();await expect(p.getByRole('article',{name:'Exact testimonial source'})).toContainText('Updated source before approval');await expect(p.getByRole('checkbox',{name:/I reviewed permission to reuse/})).not.toBeChecked();await p.getByRole('checkbox',{name:/I reviewed permission to reuse/}).check();await p.getByRole('button',{name:'Save exact testimonial permission'}).click();await expect(p.getByRole('article',{name:'Current testimonial permission'})).toContainText('Current permission recorded');expect((await page.request.get(`/api/reviewflow/testimonials/${fixture.review}?propertyId=${fixture.otherProperty}`)).status()).toBe(404)
})

test('permission history remains complete beyond its first page and survives reload',async({page,fixture})=>{
 const source=await fixture.db.rpc('read_reviewflow_testimonial_source',{p_property_id:fixture.property,p_actor_id:fixture.actor,p_review_id:fixture.review});expect(source.error).toBeNull();const context=source.data as {source:{sourceVersion:number};sourceHash:string}
 for(let n=0;n<21;n++){const id=randomUUID();const approved=await fixture.db.rpc('decide_reviewflow_testimonial',{p_id:id,p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{action:'approve',reviewId:fixture.review,sourceVersion:context.source.sourceVersion,sourceHash:context.sourceHash,attributionApproved:true,rightsBasis:'direct_consent',evidenceNote:`Retained approval evidence ${n}`,usageScope:['website'],expiresAt:null,reason:`Reviewed fixture permission ${n}`}});expect(approved.error).toBeNull();expect((approved.data as {state:string}).state).toBe('saved');if(n<20){const r=await fixture.db.rpc('decide_reviewflow_testimonial',{p_id:randomUUID(),p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{action:'revoke',reviewId:fixture.review,approvalId:id,expectedVersion:1,reason:`Revoke fixture permission ${n}`}});expect(r.error).toBeNull()}}
 const p=await openReview(page,fixture);await p.getByText('Saved permission history',{exact:true}).click();const h=p.locator('details');await expect(h.getByRole('article')).toHaveCount(20);await h.getByRole('button',{name:'Load more permission history'}).click();await expect(h.getByRole('article')).toHaveCount(21);await expect(h).toContainText('Retained approval evidence 0');await page.reload();await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analysis fixture reviewer',{exact:true}).click();await expect(p.getByRole('article',{name:'Current testimonial permission'})).toContainText('Retained approval evidence 20');expect((await fixture.db.from('review_testimonial_approvals').select('id').eq('property_id',fixture.property)).data).toHaveLength(21)
})
