import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow responses browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other responses browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['reviews','reviewflow_analysis_requests','reviewflow_response_generation_requests','reviewflow_publications','review_responses','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})

async function openReview(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analysis fixture reviewer',{exact:true}).click();await expect(page.getByRole('region',{name:'Saved review responses'})).toBeVisible();await expect(page.getByText('Loading saved responses…')).toHaveCount(0)}
async function workspace(page:Page,f:Fixture){const r=await page.request.get(`/api/reviewflow/respond?propertyId=${f.property}&reviewId=${f.review}`);expect(r.ok()).toBe(true);return r.json()}
async function saveDraft(page:Page,f:Fixture,text='Thank you for sharing your experience with our community.') {const w=await workspace(page,f);const r=await page.request.post('/api/reviewflow/respond',{data:{propertyId:f.property,requestId:randomUUID(),reviewId:f.review,sourceVersion:w.sourceVersion,contextHash:w.contextHash,responseSetHash:w.responseSetHash,replacePending:true,tone:'professional',reason:'Reviewed saved source facts',action:'draft',responseText:text}});expect(r.ok(),await r.text()).toBe(true);return (await r.json()).result}


async function approve(page:Page,f:Fixture){const saved=await saveDraft(page,f);const w=await workspace(page,f),row=w.responses.find((r:{id:string})=>r.id===saved.responseId);const response=await page.request.post('/api/reviewflow/respond',{data:{propertyId:f.property,requestId:randomUUID(),action:'approve',responseId:row.id,expectedVersion:row.version,sourceVersion:row.source_version,contextHash:row.context_hash,contentHash:row.content_hash,reason:'Manager checked exact approved response'}});expect(response.ok(),await response.text()).toBe(true);return row.id}
async function dropPublication(page:Page,action:string){let dropped=false;await page.route('**/api/reviewflow/publications',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON()?.action===action&&!dropped){dropped=true;const reply=await route.fetch();expect(reply.ok(),await reply.text()).toBe(true);await route.abort('failed')}else await route.continue()})}
async function prepareManual(page:Page){const panel=page.getByRole('region',{name:'Review publication evidence'});await panel.getByLabel('Public review destination URL',{exact:true}).fill('https://example.invalid/review/fixture');await panel.getByLabel('Reason for publication',{exact:true}).fill('Publish the exact reviewed response manually');await panel.getByRole('button',{name:'Prepare manual publication',exact:true}).click();return panel}

test('manual publication recovers lost decisions and preserves honest evidence without resolving the case',async({page,fixture},info)=>{
 const responseId=await approve(page,fixture);await openReview(page,fixture);await dropPublication(page,'prepare_manual');const panel=await prepareManual(page);await panel.getByRole('button',{name:'Retry same publication decision'}).click();await expect(panel.getByText('Awaiting publication outcome',{exact:true})).toBeVisible();await page.unroute('**/api/reviewflow/publications');expect((await fixture.db.from('reviewflow_publications').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
 await panel.getByLabel('Reason for publication outcome',{exact:true}).fill('Staff checked exact text at the public review');await panel.getByText('Record a publication outcome',{exact:true}).click();await panel.getByRole('checkbox',{name:'I checked the destination and confirm the published response exactly matches the approved text above.'}).check();await dropPublication(page,'report_manual');await panel.getByRole('button',{name:'Save staff publication report'}).click();await panel.getByRole('button',{name:'Retry same publication decision'}).click();await expect(panel.getByText('Publication reported by staff',{exact:true})).toBeVisible();await expect(panel.getByText('Staff-reported evidence; not independently verified by the provider.',{exact:true})).toBeVisible();await page.unroute('**/api/reviewflow/publications')
 const response=await fixture.db.from('review_responses').select('status,posting_mode').eq('id',responseId).single();expect(response.data).toEqual({status:'posted',posting_mode:'manual_confirmed'});expect((await fixture.db.from('reputation_cases').select('status,resolved_at').eq('review_id',fixture.review).single()).data).toEqual({status:'triaged',resolved_at:null});expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','review.publication.reported')).data).toHaveLength(1)
 await expect(page.getByText('Posted',{exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:'Reload publications'})).toBeEnabled();await page.setViewportSize({width:390,height:844});await panel.getByRole('heading',{name:'Publication and evidence',exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('publication-mobile.png')})
})

test('uncertain handoff blocks replacement until staff records a reviewed outcome',async({page,fixture})=>{
 await approve(page,fixture);await openReview(page,fixture);const panel=await prepareManual(page);await expect(panel.getByText('Awaiting publication outcome',{exact:true})).toBeVisible();await panel.getByLabel('Reason for publication outcome',{exact:true}).fill('The destination did not show a confirmed outcome');await panel.getByRole('button',{name:'Mark outcome uncertain'}).click();await expect(panel.getByText('Publication outcome uncertain',{exact:true})).toBeVisible()
 const w=await workspace(page,fixture);const blocked=await page.request.post('/api/reviewflow/respond',{data:{propertyId:fixture.property,requestId:randomUUID(),reviewId:fixture.review,sourceVersion:w.sourceVersion,contextHash:w.contextHash,responseSetHash:w.responseSetHash,replacePending:true,tone:'professional',reason:'Must reconcile the uncertain publication',action:'draft',responseText:'This new draft must not bypass the uncertain public response.'}});expect(blocked.status()).toBe(409)
 await panel.getByLabel('Reason for publication outcome',{exact:true}).fill('Staff inspected the page and confirmed no reply');await panel.getByText('Response was not published',{exact:true}).click();await panel.getByRole('checkbox',{name:'I checked the destination and confirm this prepared response was not published.'}).check();await dropPublication(page,'cancel_manual');await panel.getByRole('button',{name:'Confirm not published'}).click();await panel.getByRole('button',{name:'Retry same publication decision'}).click();await expect(panel.getByText('Staff confirmed not published',{exact:true})).toBeVisible();await page.unroute('**/api/reviewflow/publications');await saveDraft(page,fixture,'Staff can now prepare a revised response after checking the destination.')
})

test('read errors recover and an actual report remains attributed to its earlier source',async({page,fixture})=>{
 await approve(page,fixture);await page.route('**/api/reviewflow/publications?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Publication history temporarily unavailable'})}));await openReview(page,fixture);const panel=page.getByRole('region',{name:'Review publication evidence'});await expect(panel.getByRole('alert')).toContainText('temporarily unavailable');await expect(panel.getByText('No publication attempts have been saved.')).toHaveCount(0);await page.unroute('**/api/reviewflow/publications?*');await panel.getByRole('button',{name:'Reload publications'}).click();await prepareManual(page);await expect(panel.getByText('Awaiting publication outcome',{exact:true})).toBeVisible();expect((await fixture.db.from('reviews').update({review_text:'Updated source after the manual handoff.'}).eq('id',fixture.review)).error).toBeNull();await panel.getByRole('button',{name:'Reload publications'}).click();await expect(panel).toContainText('earlier source version');await panel.getByLabel('Reason for publication outcome',{exact:true}).fill('Staff verified the already prepared response was published');await panel.getByText('Record a publication outcome',{exact:true}).click();await panel.getByRole('checkbox',{name:'I checked the destination and confirm the published response exactly matches the approved text above.'}).check();await panel.getByRole('button',{name:'Save staff publication report'}).click();await expect(panel.getByText('Publication reported by staff',{exact:true})).toBeVisible();const saved=await fixture.db.from('reviewflow_publications').select('report').eq('property_id',fixture.property).single();expect(saved.data?.report).toMatchObject({sourceChanged:true,verifiedByProvider:false});expect((await fixture.db.from('reviews').select('response_status').eq('id',fixture.review).single()).data?.response_status).not.toBe('posted')
 const wrong=await page.request.get(`/api/reviewflow/publications?propertyId=${fixture.otherProperty}&reviewId=${fixture.review}`);expect(wrong.status()).toBe(409)
})
