import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow intake browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other intake browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['reviews','reviewflow_analysis_requests','reviewflow_response_generation_requests','reviewflow_publications','reviewflow_intake_requests','reviewflow_intake_observations','reviewflow_configuration_revisions','reviewflow_connection_revisions','review_responses','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})

async function settings(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByRole('region',{name:'Saved review imports'})).toBeVisible();await expect(page.getByRole('button',{name:'Reload imports',exact:true})).toBeEnabled();return page.getByRole('region',{name:'Saved review imports'})}
async function drop(page:Page,endpoint:string,action?:string){let dropped=false;await page.route('**/api/reviewflow/'+endpoint,async r=>{if(r.request().method()==='POST'&&(!action||r.request().postDataJSON()?.action===action)&&!dropped){dropped=true;const response=await r.fetch();expect(response.ok(),await response.text()).toBe(true);await r.abort('failed')}else await r.continue()})}
async function newManual(page:Page,reviewText='Saved import browser review'){const p=page.getByRole('region',{name:'Saved review imports'});await p.getByText('Save a new review import',{exact:true}).click();await p.getByLabel('Manual review platform').selectOption('other');await p.getByLabel('Reviewer name',{exact:true}).fill('Intake browser reviewer');await p.getByLabel('Review text to import').fill(reviewText);await p.getByLabel('Reason for adding this source').fill('Reviewed original review source');return p}
async function intakePost(page:Page,f:Fixture,data:Record<string,unknown>){const r=await page.request.post('/api/reviewflow/intake',{data:{propertyId:f.property,requestId:randomUUID(),reason:'Reviewed fixture source',...data}});expect(r.ok(),await r.text()).toBe(true);return (await r.json()).result}

test('manual source and application recover lost replies once and preserve evidence',async({page,fixture},info)=>{
 const p=await settings(page,fixture);await newManual(page);await drop(page,'intake','save');await p.getByRole('button',{name:'Save source and preview'}).click();await p.getByRole('button',{name:'Retry same import decision'}).click();await expect(p.getByRole('article',{name:'Saved import preview'})).toContainText('Saved import · preview');await page.unroute('**/api/reviewflow/intake');expect((await fixture.db.from('reviewflow_intake_requests').select('id').eq('property_id',fixture.property)).data).toHaveLength(1);expect((await fixture.db.from('reviews').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
 await p.getByLabel('Reason for import decision').fill('Reviewed the complete saved row');await drop(page,'intake','apply');await p.getByRole('button',{name:'Apply 1 reviewed rows'}).click();await p.getByRole('button',{name:'Retry same import decision'}).click();await expect(p.getByRole('article',{name:'Saved import preview'})).toContainText('1 added · 0 updated · 0 unchanged');await page.unroute('**/api/reviewflow/intake');expect((await fixture.db.from('reviews').select('id').eq('property_id',fixture.property)).data).toHaveLength(2);expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','review.intake.applied')).data).toHaveLength(1)
 await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();await p.getByRole('button',{name:/Manual entry · completed/}).click();await expect(p.getByRole('article',{name:'Saved import preview'})).toContainText('Saved import browser review');await page.setViewportSize({width:390,height:844});await p.getByRole('article',{name:'Saved import preview'}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('intake-mobile.png')})
})

test('CSV validation shows saved errors, preserves multiline text and pages all preview rows',async({page,fixture})=>{
 const p=await settings(page,fixture);await p.getByText('Save a new review import',{exact:true}).click();await p.getByLabel('Import method').selectOption('csv');await p.getByLabel('Review CSV').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('platform,review_text,rating\ngoogle,Valid first row,5\ngoogle,Invalid rating,6')});await p.getByLabel('Reason for adding this source').fill('Review all CSV rows');await p.getByRole('button',{name:'Save source and preview'}).click();await expect(p.getByRole('article',{name:'Saved import preview'})).toContainText('Row 2:');await expect(p.getByRole('button',{name:/Apply.*reviewed rows/})).toHaveCount(0);expect((await fixture.db.from('reviews').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
 const content='platform,platform_review_id,review_text,rating\n'+Array.from({length:35},(_,i)=>`other,csv-${i},"First line ${i}, with ""quotes""\nSecond line ${i}",5`).join('\n');await p.getByLabel('Review CSV').setInputFiles({name:'reviews.csv',mimeType:'text/csv',buffer:Buffer.from(content)});await p.getByRole('button',{name:'Save source and preview'}).click();const preview=p.getByRole('article',{name:'Saved import preview'});await expect(preview).toContainText('35 validated rows');await expect(preview).toContainText('First line 0, with "quotes"');await preview.getByRole('button',{name:'Load more preview rows'}).click();await expect(preview).toContainText('Row 35');await expect(preview.getByRole('button',{name:'Load more preview rows'})).toHaveCount(0);await p.getByLabel('Reason for import decision').fill('Reviewed every row of this file');await p.getByRole('button',{name:'Apply 35 reviewed rows'}).click();await expect(preview).toContainText('35 added · 0 updated · 0 unchanged')
 const request=await fixture.db.from('reviewflow_intake_requests').select('id').eq('property_id',fixture.property).eq('state','completed').single();expect((await page.request.get(`/api/reviewflow/intake?propertyId=${fixture.otherProperty}&intakeId=${request.data!.id}`)).status()).toBe(404)
})

test('preferences and source settings recover once, apply default tone and pause source execution',async({page,fixture})=>{
 await settings(page,fixture);const preferences=page.getByRole('region',{name:'Review response preferences'});await preferences.getByLabel('Default response tone').selectOption('friendly');await preferences.getByLabel('Property voice').fill('Warm and clear');await preferences.getByLabel('Reason for preference change').fill('Reviewed property voice');await drop(page,'config');await preferences.getByRole('button',{name:'Save response preferences'}).click();await preferences.getByRole('button',{name:'Retry same preference decision'}).click();await expect(preferences.getByRole('status')).toContainText('are saved');await page.unroute('**/api/reviewflow/config');expect((await fixture.db.from('reviewflow_configuration_revisions').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
 const sources=page.getByRole('region',{name:'Review source connections'});await sources.getByText('Add a review source',{exact:true}).click();await sources.getByLabel('Source business ID').fill('FixturePlace');await sources.getByLabel('Public business page URL').fill('https://www.google.com/maps/place/fixture');await sources.getByLabel('Source check frequency').selectOption('daily');await sources.getByLabel('Reason for source change').fill('Reviewed the correct business identity');await drop(page,'connections');await sources.getByRole('button',{name:'Save review source',exact:true}).click();await sources.getByRole('button',{name:'Retry same source decision'}).click();await expect(sources.getByRole('status')).toContainText('Source settings saved');await page.unroute('**/api/reviewflow/connections');expect((await fixture.db.from('review_platform_connections').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
 await sources.getByRole('button',{name:'Request source preview'}).click();const saved=sources.getByRole('region',{name:'Saved review imports'});await expect(saved.getByRole('article',{name:'Saved import preview'})).toContainText('Saved import · queued');const run=await fixture.db.from('reviewflow_intake_requests').select('id,claim_token').eq('property_id',fixture.property).single();expect(run.data?.claim_token).toBeNull();await saved.getByLabel('Reason for import decision').fill('Stop fixture check while external execution is paused');await saved.getByRole('button',{name:'Stop this import'}).click();await expect(saved.getByRole('article',{name:'Saved import preview'})).toContainText('Saved import · stopped')
 const api=await page.request.get(`/api/reviewflow/respond?propertyId=${fixture.property}&reviewId=${fixture.review}`);expect((await api.json()).source.defaultTone).toBe('friendly');await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analysis fixture reviewer',{exact:true}).click();await expect(page.getByRole('region',{name:'Saved review responses'}).getByLabel('Response tone',{exact:true})).toHaveValue('friendly')
})

test('failed reads stay visible and a changed preview requires saved-source rebuilding',async({page,fixture})=>{
 await page.route('**/api/reviewflow/intake?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved import history temporarily unavailable'})}));const p=await settings(page,fixture);await expect(p.getByRole('alert')).toContainText('temporarily unavailable');await expect(p.getByText('No saved imports yet.')).toHaveCount(0);await page.unroute('**/api/reviewflow/intake?*');await p.getByRole('button',{name:'Reload imports'}).click();await expect(p.getByText('No saved imports yet.')).toBeVisible()
 const source=await fixture.db.from('reviews').select('platform_review_id').eq('id',fixture.review).single(),saved=await intakePost(page,fixture,{action:'save',kind:'manual',content:JSON.stringify({platform:'other',platformReviewId:source.data!.platform_review_id,reviewerName:'Analysis fixture reviewer',reviewText:'Reviewed correction from saved source',rating:5})});await p.getByRole('button',{name:'Reload imports'}).click();await p.getByRole('button',{name:/Manual entry · preview/}).click();expect((await fixture.db.from('reviews').update({review_text:'A newer source arrived'}).eq('id',fixture.review)).error).toBeNull();await p.getByLabel('Reason for import decision').fill('Reviewed preview before application');await p.getByRole('button',{name:'Apply 1 reviewed rows'}).click();await expect(p.getByRole('article',{name:'Saved import preview'})).toContainText('A review changed after this preview');await p.getByLabel('Reason for import decision').fill('Rebuild against the current review');await p.getByRole('button',{name:'Rebuild from saved source'}).click();await expect(p.getByRole('article',{name:'Saved import preview'})).toContainText('This preview reuses a previously saved receipt');await p.getByLabel('Reason for import decision').fill('Approve the rebuilt source correction');await p.getByRole('button',{name:'Apply 1 reviewed rows'}).click();await expect(p.getByRole('article',{name:'Saved import preview'})).toContainText('0 added · 1 updated · 0 unchanged');expect((await fixture.db.from('reviewflow_intake_requests').select('state').eq('id',saved.requestId).single()).data?.state).toBe('stopped')
 await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(p.getByText('No saved imports yet.')).toBeVisible();await expect(p.getByText('Reviewed correction from saved source',{exact:true})).toHaveCount(0)
})
