import { expect, test as base, type Page } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||''
const client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;review:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),review=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 const check=async(p:PromiseLike<{error:unknown}>)=>{const r=await p;if(r.error)throw r.error}
 try{
  await check(db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow batch browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'ReviewFlow other batch browser fixture'}]))
  await check(db.from('reviews').insert({id:review,property_id:property,platform:'other',platform_review_id:randomUUID(),review_text:'The pool was clean.',reviewer_name:'Analysis fixture reviewer',rating:5,response_status:'pending'}))
  await provide({property,otherProperty,review,actor,db})
 }finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;CREATE TEMP TABLE fixture_jobs ON COMMIT DROP AS SELECT id FROM public.shared_jobs WHERE property_id='${p}';DELETE FROM public.properties WHERE id='${p}';DELETE FROM public.shared_jobs WHERE id IN(SELECT id FROM fixture_jobs);COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['reviews','reviewflow_analysis_batches','reviewflow_analysis_batch_items','reviewflow_analysis_requests','reviewflow_response_generation_requests','reviewflow_publications','reviewflow_intake_requests','reviewflow_intake_observations','reviewflow_configuration_revisions','reviewflow_connection_revisions','review_responses','reviewflow_commands','review_analyses','reputation_case_events','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{page.on('pageerror',error=>console.error('Response browser page error:',error.message));await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/)})

async function workspace(page:Page,f:Fixture){await page.addInitScript(p=>localStorage.setItem('p11_selected_property_id',p),f.property);await page.goto('/dashboard/reviewflow');await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analyze all unanalysed reviews',{exact:true}).click();const panel=page.getByRole('region',{name:'Property review analysis'});await expect(panel.getByRole('button',{name:'Reload analysis queues'})).toBeEnabled();return panel}
async function drop(page:Page,action:string){let dropped=false;await page.route('**/api/reviewflow/analyze-batch',async r=>{if(r.request().method()==='POST'&&r.request().postDataJSON()?.action===action&&!dropped){dropped=true;const response=await r.fetch();expect(response.ok()).toBe(true);await r.abort('failed')}else await r.continue()})}
async function post(page:Page,f:Fixture,data:Record<string,unknown>){const r=await page.request.post('/api/reviewflow/analyze-batch',{data:{propertyId:f.property,requestId:randomUUID(),reason:'Reviewed browser fixture scope',...data}});expect(r.ok()).toBe(true);const body=await r.json();expect(body.modelExecutionPaused).toBe(true);return body.result}
async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const r=await f.db.rpc(name,args);if(r.error)throw r.error;return r.data}
const classification={sentiment:'positive',sentimentScore:0.8,topics:['amenities'],journeyStage:'residency',issueDomains:['amenities'],severity:'low',riskClass:'routine',policyClass:'standard',isUrgent:false,confidence:0.95,summary:'The reviewer liked the clean pool.',recommendedAction:'Thank the reviewer.',evidence:[{claim:'Clean pool',quote:'The pool was clean.'}]}

test('full selection pages beyond100 and recovers lost prepare, approval and stop replies once',async({page,fixture},info)=>{
 const added=await fixture.db.from('reviews').insert(Array.from({length:104},(_,i)=>({property_id:fixture.property,platform:'other',platform_review_id:`batch-browser-${i}`,review_text:`Other saved review ${i}`,reviewer_name:`Batch reviewer ${i}`,rating:4,response_status:'pending'})));expect(added.error).toBeNull()
 const p=await workspace(page,fixture);await expect(p).toContainText('Model execution is paused');await p.getByLabel('Reason for this analysis selection').fill('Review all current sources');await drop(page,'prepare');await p.getByRole('button',{name:'Save full review selection'}).click();await p.getByRole('button',{name:'Retry same queue decision'}).click();await page.unroute('**/api/reviewflow/analyze-batch');const detail=p.getByRole('article',{name:'Saved analysis selection'});await expect(detail).toContainText('105 exact review versions selected');for(let i=0;i<3;i++)await detail.getByRole('button',{name:'Load more selected reviews'}).click();await expect(detail).toContainText('Review 105 ·');await expect(detail.getByRole('button',{name:'Load more selected reviews'})).toHaveCount(0);expect((await fixture.db.from('reviewflow_analysis_batches').select('id').eq('property_id',fixture.property)).data).toHaveLength(1)
 await p.getByLabel('Reason for queue decision').fill('Approve the exact saved scope');await p.getByRole('checkbox').check();await drop(page,'approve');await p.getByRole('button',{name:'Approve saved analysis scope'}).click();await p.getByRole('button',{name:'Retry same queue decision'}).click();await expect(detail).toContainText('Approved; waiting to start');await page.unroute('**/api/reviewflow/analyze-batch');expect((await fixture.db.from('reviewflow_analysis_requests').select('id').eq('property_id',fixture.property)).data).toHaveLength(0)
 await p.getByLabel('Reason for queue decision').fill('Stop this fixture queue');await drop(page,'stop');await p.getByRole('button',{name:'Stop analysis queue'}).click();await p.getByRole('button',{name:'Retry same queue decision'}).click();await expect(detail).toContainText('0 waiting · 0 held · 105 stopped');await page.unroute('**/api/reviewflow/analyze-batch');for(const action of ['prepared','approved','stopped'])expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action',`review.batch.${action}`)).data).toHaveLength(1)
 await page.reload();await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analyze all unanalysed reviews',{exact:true}).click();await p.getByRole('button',{name:/Queue stopped · 105 reviews/}).click();await expect(detail).toContainText('105 stopped');await page.setViewportSize({width:390,height:844});await detail.scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('batch-mobile.png')})
})

test('saved result recovery completes the queue while models stay paused and opens its exact review',async({page,fixture})=>{
 const saved=await post(page,fixture,{action:'prepare',scope:'unanalyzed_current'});await post(page,fixture,{action:'approve',batchId:saved.batchId,expectedVersion:saved.version,maxModelCalls:1});const item=await fixture.db.from('reviewflow_analysis_batch_items').select('id').eq('batch_id',saved.batchId).single();expect(item.error).toBeNull();await rpc(fixture,'prepare_reviewflow_batch_item',{p_batch_id:saved.batchId,p_item_id:item.data!.id});const claim=await rpc(fixture,'claim_reviewflow_analysis',{p_id:item.data!.id});expect(claim.state).toBe('invoke_once');await rpc(fixture,'record_reviewflow_analysis_result',{p_id:item.data!.id,p_claim_token:claim.claimToken,p_result:{status:'received',providerId:'isolated-batch-fixture',content:JSON.stringify(classification)}})
 const p=await workspace(page,fixture);await p.getByRole('button',{name:/Analysis in progress · 1 reviews/}).click();await p.getByLabel('Reason for queue decision').fill('Recover the saved model output');await drop(page,'recover');await p.getByRole('button',{name:'Recover analysis queue'}).click();await p.getByRole('button',{name:'Retry same queue decision'}).click();const detail=p.getByRole('article',{name:'Saved analysis selection'});await expect(detail).toContainText('Selection analyzed');await expect(detail).toContainText('1 analyzed · 0 need staff review · 0 waiting');expect((await fixture.db.from('reviewflow_analysis_requests').select('id,state').eq('property_id',fixture.property)).data).toEqual([{id:item.data!.id,state:'completed'}]);expect((await fixture.db.from('shared_action_events').select('actor_id,service_principal').eq('property_id',fixture.property).eq('action','review.analysis.completed')).data).toEqual([{actor_id:null,service_principal:'reviewflow.analysis'}]);await detail.getByRole('button',{name:'Open review 1',exact:true}).click();await expect(page.getByRole('region',{name:'Saved review analysis'})).toContainText('Analysis saved')
})

test('failed queue reads are visible and switching property clears the earlier selection',async({page,fixture})=>{
 const saved=await post(page,fixture,{action:'prepare',scope:'unanalyzed_current'});await page.route('**/api/reviewflow/analyze-batch?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Saved queue history unavailable'})}));const p=await workspace(page,fixture);await expect(p.getByRole('alert')).toContainText('history unavailable');await expect(p.getByText('No saved analysis queues.')).toHaveCount(0);await page.unroute('**/api/reviewflow/analyze-batch?*');await p.getByRole('button',{name:'Reload analysis queues'}).click();await p.getByRole('button',{name:/Selection saved; approval required · 1 reviews/}).click();await expect(p.getByRole('article',{name:'Saved analysis selection'})).toContainText('The pool was clean.');expect((await page.request.get(`/api/reviewflow/analyze-batch?propertyId=${fixture.otherProperty}&batchId=${saved.batchId}`)).status()).toBe(404)
 await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.getByText('Analyze all unanalysed reviews',{exact:true}).click();await expect(p.getByText('No saved analysis queues.')).toBeVisible();await expect(p.getByRole('article',{name:'Saved analysis selection'})).toHaveCount(0)
})
