import {expect,test as base,type Page}from '@playwright/test'
import {createClient}from '@supabase/supabase-js'
import {randomUUID}from 'node:crypto'
import {execFileSync}from 'node:child_process'
import {readFile}from 'node:fs/promises'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||'',client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 try{const r=await db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'Codex brief browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'Other Codex brief browser fixture'}]);expect(r.error).toBeNull();await provide({property,otherProperty,actor,db})}finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;DELETE FROM public.properties WHERE id='${p}';COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['siteforge_codex_briefs','siteforge_brief_exports','siteforge_brief_export_reports','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})
const panel=(page:Page)=>page.getByRole('region',{name:'Saved Codex briefs',exact:true})
async function open(page:Page,f:Fixture){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto('/dashboard/siteforge');await expect(panel(page).getByRole('button',{name:'Reload saved briefs'})).toBeEnabled()}
async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const r=await f.db.rpc(name,args);expect(r.error).toBeNull();return r.data}
test('lost save and export replies reuse one exact snapshot and retain revision ancestry after reload',async({page,context,fixture},info)=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await open(page,fixture);await page.getByLabel('What would you like to build or change?').fill('Replace the gallery with approved images');await page.getByLabel('References and source notes').fill('Use private-client-source.pdf');await page.getByText('Preview the brief',{exact:true}).click();const exact=await page.getByLabel('Prepared Codex brief').inputValue();let dropSave=true,dropExport=true;
 await page.route('**/api/siteforge/codex-briefs',async r=>{if(r.request().method()==='POST'&&dropSave){dropSave=false;const response=await r.fetch();expect(response.ok(),await response.text()).toBe(true);await r.abort('failed')}else await r.continue()});await page.route('**/api/siteforge/codex-briefs/export',async r=>{if(r.request().postDataJSON().action==='prepare'&&dropExport){dropExport=false;const response=await r.fetch();expect(response.ok(),await response.text()).toBe(true);await r.abort('failed')}else await r.continue()});
 await page.getByRole('button',{name:'Copy brief for Codex',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Failed to fetch'})).toBeVisible();await page.getByRole('button',{name:'Copy brief for Codex',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Failed to fetch'})).toBeVisible();await page.getByRole('button',{name:'Copy brief for Codex',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Brief copied.'})).toBeVisible();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(exact)
 let rows=(await fixture.db.from('siteforge_codex_briefs').select('id,document,parent_id').eq('property_id',fixture.property)).data!;expect(rows).toHaveLength(1);const original=rows[0].id;expect(rows[0].document).toBe(exact);expect((await fixture.db.from('siteforge_brief_exports').select('id').eq('property_id',fixture.property)).data).toHaveLength(1);await expect(panel(page)).toContainText('Browser reported: copied to clipboard');expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).like('action','site.brief.%')).data).toHaveLength(3)
 await page.getByLabel('What would you like to build or change?').fill('Revise only the gallery captions');await page.getByRole('button',{name:'Save brief',exact:true}).click();await expect(panel(page)).toContainText('2 saved brief snapshots');rows=(await fixture.db.from('siteforge_codex_briefs').select('id,document,parent_id').eq('property_id',fixture.property)).data!;expect(rows.find(r=>r.id!==original)?.parent_id).toBe(original);await page.reload();await expect(panel(page).getByLabel('Exact saved Codex brief')).toHaveValue(rows.find(r=>r.id!==original)!.document);await panel(page).getByRole('link',{name:'Open parent brief'}).click();await expect(panel(page).getByLabel('Exact saved Codex brief')).toHaveValue(exact)
 await panel(page).getByRole('button',{name:'Use this brief as a revision'}).click();await expect(page.getByLabel('What would you like to build or change?')).toHaveValue('Replace the gallery with approved images');const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download brief',exact:true}).click();const download=await downloadEvent;expect(await readFile((await download.path())!,'utf8')).toBe(exact);await expect(panel(page)).toContainText('download started; file receipt unconfirmed');expect((await fixture.db.from('siteforge_codex_briefs').select('id').eq('property_id',fixture.property)).data).toHaveLength(2)
 await page.setViewportSize({width:390,height:844});await panel(page).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('codex-brief-history-mobile.png')})
})
test('clipboard failure and a lost browser-report reply remain truthful and recover without rewriting the result',async({page,fixture})=>{
 await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw new Error('Denied')}}}));await open(page,fixture);await page.getByLabel('What would you like to build or change?').fill('Prepare an editable property website');let dropped=false;await page.route('**/api/siteforge/codex-briefs/export',async r=>{if(r.request().postDataJSON().action==='report'&&!dropped){dropped=true;const response=await r.fetch();expect(response.ok(),await response.text()).toBe(true);await r.abort('failed')}else await r.continue()});await page.getByRole('button',{name:'Copy brief for Codex',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Clipboard access is unavailable.'})).toContainText('report is pending');await expect(page.getByLabel('Prepared Codex brief')).toBeVisible();await page.reload();await expect(panel(page)).toContainText('Browser reported: clipboard unavailable');await expect.poll(()=>page.evaluate(()=>Object.keys(sessionStorage).filter(k=>k.startsWith('p11.codex-brief.report.')).length)).toBe(0);expect((await fixture.db.from('siteforge_brief_export_reports').select('result').eq('property_id',fixture.property)).data).toEqual([{result:'clipboard_failed'}]);expect((await fixture.db.from('shared_action_events').select('id').eq('property_id',fixture.property).eq('action','site.brief.export_reported')).data).toHaveLength(1)
})
test('complete saved history, visible failures and a delayed export remain isolated across property changes',async({page,fixture})=>{
 for(let i=0;i<25;i++)await rpc(fixture,'save_siteforge_codex_brief',{p_id:randomUUID(),p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{property:{id:fixture.property,name:'Codex brief browser fixture',city:null},draft:{request:`Saved fixture brief ${i+1}`,references:'',target:'existing',revision:{keepUnchanged:'',parentVersion:''},delivery:{projectLocation:'',contentOwnership:'',inquiryDestination:''}},parentId:null,templateVersion:'codex-brief-v1'},p_document:`Fixture brief ${i+1}`})
 await page.route('**/api/siteforge/codex-briefs?*',r=>r.fulfill({status:503,json:{error:'Saved history temporarily unavailable'}}));await open(page,fixture);await expect(panel(page).getByRole('alert')).toContainText('temporarily unavailable');await expect(panel(page)).not.toContainText('No brief snapshots');await page.unroute('**/api/siteforge/codex-briefs?*');await panel(page).getByRole('button',{name:'Reload saved briefs'}).click();await expect(panel(page)).toContainText('25 saved brief snapshots');await expect(panel(page).getByRole('link',{name:/Saved fixture brief/})).toHaveCount(20);await panel(page).getByRole('button',{name:'Older brief snapshots'}).click();await expect(panel(page).getByRole('link',{name:/Saved fixture brief/})).toHaveCount(25)
 await page.getByLabel('What would you like to build or change?').fill('Private pending handoff');let release:()=>void=()=>{},start:()=>void=()=>{};const held=new Promise<void>(r=>{release=r}),started=new Promise<void>(r=>{start=r});await page.route('**/api/siteforge/codex-briefs/export',async r=>{if(r.request().postDataJSON().action==='prepare'){const response=await r.fetch();start();await held;await r.fulfill({response}).catch(()=>{})}else await r.continue()});await page.getByRole('button',{name:'Copy brief for Codex',exact:true}).click();await started;await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);release();await expect(panel(page)).toContainText('0 saved brief snapshots');await expect(page.getByLabel('What would you like to build or change?')).toHaveValue('');expect((await fixture.db.from('siteforge_brief_export_reports').select('id').eq('property_id',fixture.property)).data).toHaveLength(0);await expect(panel(page)).not.toContainText('Private pending handoff')
})
