import {expect,test as base,type Page}from '@playwright/test'
import {createClient}from '@supabase/supabase-js'
import {randomUUID}from 'node:crypto'
import {execFileSync}from 'node:child_process'
import {blankDeliveryChecks}from '@/utils/siteforge/delivery-record-contracts'
const dbURL=process.env.NEXT_PUBLIC_SUPABASE_URL||'',client=()=>createClient(dbURL,process.env.SUPABASE_SERVICE_ROLE_KEY!)
type Fixture={property:string;otherProperty:string;actor:string;db:ReturnType<typeof client>}
const test=base.extend<{fixture:Fixture}>({fixture:async({},provide)=>{
 if(!['localhost','127.0.0.1'].includes(new URL(dbURL).hostname)||!['localhost','127.0.0.1'].includes(new URL(process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:9430').hostname))throw new Error('Local isolated fixture required')
 const db=client(),property=randomUUID(),otherProperty=randomUUID(),actor='11111111-1111-1111-1111-111111111111'
 try{expect((await db.from('properties').insert([{id:property,org_id:'22222222-2222-2222-2222-222222222222',name:'Delivery evidence browser fixture'},{id:otherProperty,org_id:'22222222-2222-2222-2222-222222222222',name:'Other delivery evidence browser fixture'}])).error).toBeNull();await provide({property,otherProperty,actor,db})}finally{
  for(const p of [property,otherProperty])execFileSync('docker',['exec','-i','supabase_db_p11-platform','psql','-U','postgres','-d','postgres','-X','-v','ON_ERROR_STOP=1'],{input:`BEGIN;SET LOCAL session_replication_role=replica;UPDATE public.properties SET current_vertical_profile_version_id=NULL WHERE id='${p}';DELETE FROM public.property_vertical_profile_versions WHERE property_id='${p}';SET LOCAL session_replication_role=origin;DELETE FROM public.properties WHERE id='${p}';COMMIT;`,stdio:['pipe','pipe','pipe']})
  for(const table of ['siteforge_delivery_records','siteforge_delivery_reviews','siteforge_codex_briefs','shared_action_events'])expect((await db.from(table).select('id').eq('property_id',property)).data).toHaveLength(0)
 }
}})
test.beforeEach(async({page})=>{await page.goto('/auth/login');await page.getByLabel('Email address').fill('local-admin@p11.test');await page.getByLabel('Password',{exact:true}).fill('local-dev-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/auth\/login/,{timeout:30000})})
const panel=(page:Page)=>page.getByRole('region',{name:'SiteForge delivery evidence',exact:true}),review=(page:Page)=>panel(page).getByRole('form',{name:'Review delivery evidence',exact:true})
const source={sourceName:'delivery-record.md',sourceFormat:'markdown',sourceOrigin:'client_project_report',sourceText:'# Local delivery record\nOriginal reported evidence with untested checks.\n<script>window.deliveryExecuted=true</script>',targetLabel:'Synthetic WordPress review',targetPurpose:'review',sourceRevision:'source-v1',observedAt:null,contentSource:'Client project',editorOwner:'',briefId:null,parentId:null}
async function rpc(f:Fixture,name:string,args:Record<string,unknown>){const r=await f.db.rpc(name,args);expect(r.error).toBeNull();return r.data}
async function seed(f:Fixture,input=source){const id=randomUUID();const r=await rpc(f,'record_siteforge_delivery',{p_id:id,p_property_id:f.property,p_actor_id:f.actor,p_input:input});expect(r.state).toBe('saved');return{id,sourceHash:r.sourceHash}}
async function open(page:Page,f:Fixture,id?:string){await page.addInitScript(id=>localStorage.setItem('p11_selected_property_id',id),f.property);await page.goto(`/dashboard/siteforge${id?`?deliveryRecordId=${id}&deliveryPropertyId=${f.property}`:''}`);await expect(panel(page).getByRole('button',{name:'Reload delivery records'})).toBeEnabled()}
test('exact file intake, linked brief, lost replies, withdrawal and revised sources retain original evidence',async({page,fixture},info)=>{
 const briefId=randomUUID();await rpc(fixture,'save_siteforge_codex_brief',{p_id:briefId,p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{property:{id:fixture.property,name:'Delivery evidence browser fixture',city:null},draft:{request:'Synthetic client website brief',references:'',target:'wordpress',revision:{keepUnchanged:'',parentVersion:''},delivery:{projectLocation:'',contentOwnership:'',inquiryDestination:''}},parentId:null,templateVersion:'codex-brief-v1'},p_document:'Synthetic related client project brief'});await open(page,fixture);await page.getByRole('region',{name:'Saved Codex briefs',exact:true}).getByRole('link',{name:'Synthetic client website brief',exact:true}).click();await panel(page).getByText('Add or revise a delivery record',{exact:true}).click();const intake=panel(page).getByRole('form',{name:'Retain delivery record',exact:true});await intake.getByLabel('Delivery record file',{exact:true}).setInputFiles({name:'delivery-record.md',mimeType:'text/markdown',buffer:Buffer.from(source.sourceText)});await expect(intake.getByLabel('Original record text',{exact:true})).toHaveValue(source.sourceText);await intake.getByLabel('Target being reviewed',{exact:true}).fill(source.targetLabel);await intake.getByLabel('Reported target purpose',{exact:true}).selectOption('review');await intake.getByLabel('Tested source version or package',{exact:true}).fill('source-v1');await intake.getByText('Source ownership and related brief',{exact:true}).click();await intake.getByRole('button',{name:'Attach selected saved brief'}).click();await expect(intake).toContainText('Linked brief: Synthetic client website brief');let dropRecord=true,dropReview=true;await page.route('**/api/siteforge/delivery-records',async r=>{const action=r.request().postDataJSON().action;if((action==='record'&&dropRecord)||(action==='review'&&dropReview)){if(action==='record')dropRecord=false;else dropReview=false;const response=await r.fetch();expect(response.ok(),await response.text()).toBe(true);await r.abort('failed')}else await r.continue()});await intake.getByRole('button',{name:'Retain delivery record',exact:true}).click();await expect(intake.getByRole('alert')).toContainText('Failed to fetch');await intake.getByRole('button',{name:'Retain delivery record',exact:true}).click();await expect(review(page)).toBeVisible();let records=(await fixture.db.from('siteforge_delivery_records').select('id,input,parent_id,brief_id').eq('property_id',fixture.property)).data!;expect(records).toHaveLength(1);const id=records[0].id;expect(records[0].brief_id).toBe(briefId);expect(records[0].input.sourceText).toBe(source.sourceText);expect(await page.evaluate(()=>Object.hasOwn(window,'deliveryExecuted'))).toBe(false)
 await review(page).locator('summary').filter({hasText:'Design and routes'}).click();await review(page).getByLabel('Design and routes status',{exact:true}).selectOption('passed');await review(page).getByLabel('Design and routes evidence',{exact:true}).fill('checks/routes-review.txt');await review(page).getByLabel('Design and routes observation date',{exact:true}).fill('2026-09-20');await review(page).getByLabel('Reason for this evidence decision',{exact:true}).fill('Review the supplied local route evidence');await review(page).getByRole('button',{name:'Save evidence review',exact:true}).click();await expect(review(page).getByRole('alert')).toContainText('Failed to fetch');await review(page).getByRole('button',{name:'Save evidence review',exact:true}).click();await expect(panel(page)).toContainText('Evidence review recorded as an operator report');expect((await fixture.db.from('siteforge_delivery_reviews').select('id').eq('record_id',id)).data).toHaveLength(1)
 await page.reload();await expect(review(page)).toBeVisible();await review(page).getByLabel('Reason for this evidence decision',{exact:true}).fill('Withdraw pending a fuller route comparison');await review(page).getByRole('button',{name:'Withdraw current review'}).click();await expect(panel(page)).toContainText('Earlier reported passes remain historical');const history=panel(page).getByRole('region',{name:'Delivery review history'});await expect(history.locator('details')).toHaveCount(2);await history.locator('summary').filter({hasText:'Reported evidence reviewed'}).click();await expect(history).toContainText('Design and routes · Reported passed');await expect(history).toContainText('checks/routes-review.txt');await panel(page).getByText('Exact retained source',{exact:true}).click();await expect(panel(page).getByLabel('Exact retained delivery source')).toHaveValue(source.sourceText)
 await panel(page).getByRole('button',{name:'Create revised source record'}).click();await intake.getByLabel('Record name',{exact:true}).fill('delivery-record-v2.md');await intake.getByLabel('Tested source version or package',{exact:true}).fill('source-v2');await intake.getByLabel('Original record text',{exact:true}).fill(source.sourceText+'\nCorrected report: route comparison remains open.');await intake.getByRole('button',{name:'Retain delivery record',exact:true}).click();await expect(panel(page)).toContainText('2 retained delivery records');records=(await fixture.db.from('siteforge_delivery_records').select('id,input,parent_id,brief_id').eq('property_id',fixture.property)).data!;expect(records.find(r=>r.id!==id)?.parent_id).toBe(id);expect(records.find(r=>r.id===id)?.input.sourceText).toBe(source.sourceText);await expect(panel(page).getByRole('region',{name:'Delivery review history'})).toContainText('No review decision has been saved');await page.setViewportSize({width:390,height:844});await panel(page).getByRole('region',{name:'Selected delivery evidence'}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('delivery-record-mobile.png')})
})
test('stale review keeps the attempted decision visible and unknown source versions cannot become reported passes',async({page,fixture})=>{
 const saved=await seed(fixture,{...source,sourceRevision:''});await open(page,fixture,saved.id);await panel(page).getByText('Add or revise a delivery record',{exact:true}).click();const intake=panel(page).getByRole('form',{name:'Retain delivery record',exact:true});await intake.getByLabel('Original record text',{exact:true}).fill('Existing unsaved source report');await intake.getByLabel('Delivery record file',{exact:true}).setInputFiles({name:'bad.md',mimeType:'text/markdown',buffer:Buffer.from([0xc3,0x28])});await expect(intake.getByRole('alert')).toContainText('not valid UTF-8');await expect(intake.getByLabel('Original record text',{exact:true})).toHaveValue('Existing unsaved source report');await review(page).locator('summary').filter({hasText:'Design and routes'}).click();await review(page).getByLabel('Design and routes status',{exact:true}).selectOption('passed');await review(page).getByLabel('Design and routes evidence',{exact:true}).fill('checks/unqualified.txt');await review(page).getByLabel('Design and routes observation date',{exact:true}).fill('2026-09-20');await review(page).getByLabel('Reason for this evidence decision',{exact:true}).fill('Attempt a reported pass');await review(page).getByRole('button',{name:'Save evidence review'}).click();await expect(review(page).getByRole('alert')).toContainText('naming the tested source version');expect((await fixture.db.from('siteforge_delivery_reviews').select('id').eq('record_id',saved.id)).data).toHaveLength(0);await review(page).getByLabel('Design and routes status',{exact:true}).selectOption('not_run');await rpc(fixture,'review_siteforge_delivery',{p_id:randomUUID(),p_property_id:fixture.property,p_actor_id:fixture.actor,p_input:{recordId:saved.id,sourceHash:saved.sourceHash,expectedReviewId:null,action:'review',checks:blankDeliveryChecks(),reason:'Concurrent review keeps all checks untested'}});await review(page).getByRole('button',{name:'Save evidence review'}).click();await expect(review(page).getByRole('alert')).toContainText('Another review was saved');await expect(review(page).getByLabel('Reason for this evidence decision',{exact:true})).toHaveValue('Attempt a reported pass');await panel(page).getByRole('button',{name:'Reload delivery records'}).click();await expect(panel(page).getByRole('region',{name:'Delivery review history'}).locator('details')).toHaveCount(1)
})
test('record paging and failed or delayed reads never turn another property into a source of evidence',async({page,fixture})=>{
 for(let i=0;i<25;i++)await seed(fixture,{...source,sourceName:`Report fixture ${i+1}`});await page.route('**/api/siteforge/delivery-records?*',r=>r.fulfill({status:503,json:{error:'Delivery history temporarily unavailable'}}));await open(page,fixture);await expect(panel(page).getByRole('alert')).toContainText('temporarily unavailable');await expect(panel(page)).not.toContainText('No delivery records');await page.unroute('**/api/siteforge/delivery-records?*');await panel(page).getByRole('button',{name:'Reload delivery records'}).click();await expect(panel(page)).toContainText('25 retained delivery records');await expect(panel(page).getByRole('link',{name:/Report fixture/})).toHaveCount(20);await panel(page).getByRole('button',{name:'Older delivery records'}).click();await expect(panel(page).getByRole('link',{name:/Report fixture/})).toHaveCount(25);let release:()=>void=()=>{},start:()=>void=()=>{};const held=new Promise<void>(r=>{release=r}),started=new Promise<void>(r=>{start=r});await page.route('**/api/siteforge/delivery-records?*',async r=>{if(new URL(r.request().url()).searchParams.get('propertyId')===fixture.property){const response=await r.fetch();start();await held;await r.fulfill({response}).catch(()=>{})}else await r.continue()});await panel(page).getByRole('button',{name:'Reload delivery records'}).click();await started;await page.getByRole('combobox',{name:'Property',exact:true}).selectOption(fixture.otherProperty);release();await expect(panel(page)).toContainText('0 retained delivery records');await expect(panel(page).getByRole('link',{name:/Report fixture/})).toHaveCount(0)
})
