export const PRODUCT_LABELS={platform:'Console',siteforge:'SiteForge',lumaleasing:'LumaLeasing',propertyaudit:'PropertyAudit',brandforge:'BrandForge',tourspark:'TourSpark',leadpulse:'LeadPulse',crm:'CRM Sync',forgestudio:'ForgeStudio',reviewflow:'ReviewFlow',marketvision:'MarketVision',bi:'MultiChannel BI',knowledge:'Knowledge Base',property:'Property setup',integrations:'Integrations',reports:'Reports',pipelines:'Pipelines',settings:'Settings',team:'Team',agency:'Agency controls'} as const
export type ProductKey=keyof typeof PRODUCT_LABELS
const routes:Record<string,ProductKey>={siteforge:'siteforge',lumaleasing:'lumaleasing',propertyaudit:'propertyaudit',brandforge:'brandforge',leads:'tourspark',leadpulse:'leadpulse',crm:'crm',forgestudio:'forgestudio',reviewflow:'reviewflow',marketvision:'marketvision',bi:'bi',knowledge:'knowledge',community:'property',properties:'property','floor-plans':'property',integrations:'integrations',reports:'reports',pipelines:'pipelines',settings:'settings',team:'team',agency:'agency',substrate:'agency',luma:'agency',activity:'platform',delivery:'platform',intelligence:'platform'}
export function pageObservation(pathname:string):{product:ProductKey;path:string}|null {
 // Record the registered page family, never URL query text or resource identifiers.
 const parts=pathname.split('/').filter(Boolean)
 if(parts[0]!=='dashboard')return null
 if(parts.length===1)return {product:'platform',path:'/dashboard'}
 const product=routes[parts[1]]
 return product?{product,path:`/dashboard/${parts[1]}`}:null
}
export const ACTION_LABELS:Record<string,string>={
 'intelligence.fact.save':'Saved a draft of property fact',
 'intelligence.fact.approve':'Approved property fact',
 'intelligence.fact.withdraw':'Withdrew property fact',
 'intelligence.fact.lock':'Locked property fact',
 'intelligence.fact.unlock':'Unlocked property fact',
 'intelligence.fact.implement':'Recorded implementation of property fact',
 'intelligence.fact.measure':'Recorded measurements for property fact',
 'intelligence.fact.dismiss':'Dismissed property fact',
 'intelligence.creative.save':'Saved a draft of creative direction',
 'intelligence.creative.approve':'Approved creative direction',
 'intelligence.creative.withdraw':'Withdrew creative direction',
 'intelligence.creative.lock':'Locked creative direction',
 'intelligence.creative.unlock':'Unlocked creative direction',
 'intelligence.creative.implement':'Recorded implementation of creative direction',
 'intelligence.creative.measure':'Recorded measurements for creative direction',
 'intelligence.creative.dismiss':'Dismissed creative direction',
 'intelligence.batch.save':'Saved a draft of observation import',
 'intelligence.batch.approve':'Approved observation import',
 'intelligence.batch.withdraw':'Withdrew observation import',
 'intelligence.batch.lock':'Locked observation import',
 'intelligence.batch.unlock':'Unlocked observation import',
 'intelligence.batch.implement':'Recorded implementation of observation import',
 'intelligence.batch.measure':'Recorded measurements for observation import',
 'intelligence.batch.dismiss':'Dismissed observation import',
 'intelligence.recommendation.save':'Saved a draft of recommendation',
 'intelligence.recommendation.approve':'Approved recommendation',
 'intelligence.recommendation.withdraw':'Withdrew recommendation',
 'intelligence.recommendation.lock':'Locked recommendation',
 'intelligence.recommendation.unlock':'Unlocked recommendation',
 'intelligence.recommendation.implement':'Recorded implementation of recommendation',
 'intelligence.recommendation.measure':'Recorded measurements for recommendation',
 'intelligence.recommendation.dismiss':'Dismissed recommendation',
 'intelligence.experiment.save':'Saved a draft of experiment',
 'intelligence.experiment.approve':'Approved experiment',
 'intelligence.experiment.withdraw':'Withdrew experiment',
 'intelligence.experiment.lock':'Locked experiment',
 'intelligence.experiment.unlock':'Unlocked experiment',
 'intelligence.experiment.implement':'Recorded implementation of experiment',
 'intelligence.experiment.measure':'Recorded measurements for experiment',
 'intelligence.experiment.dismiss':'Dismissed experiment',
 'site.package.queued':'Requested an Astra website build',
 'site.package.preparing':'Preparing saved website information',
 'site.package.starting':'Preparing the Astra generation request',
 'site.package.generating':'Started website generation',
 'site.package.packaging':'Preparing the generated website package',
 'site.package.ready':'Retained the website package for review',
 'site.package.failed':'Website build needs attention',
 'site.package.uncertain':'Website build needs provider confirmation',
 'site.package.download_prepared':'Prepared a website package download',
'delivery.outcomes':'Recorded reviewed leasing outcomes','delivery.outcome_withdraw':'Withdrew a reported leasing outcome','delivery.work_save':'Saved a property work proposal','delivery.work_transition':'Recorded the next delivery step','delivery.quality_review':'Saved a work quality assessment','delivery.report_draft':'Prepared a client report draft','delivery.report_edit':'Revised the client report narrative','delivery.report_refresh':'Refreshed captured client report results','delivery.report_transition':'Recorded a client report publication decision','delivery.report_policy':'Updated monthly draft preparation','delivery.cancel_request':'Closed an unused delivery request',

 'agency.execution.prepared':'Prepared local agency rehearsal','agency.execution.authorized':'Recorded rehearsal authorization check','agency.execution.advanced':'Recorded rehearsal progress','agency.execution.paused':'Paused agency rehearsal','agency.execution.resumed':'Resumed agency rehearsal','agency.execution.stopped':'Stopped agency rehearsal','agency.execution.reversed':'Recorded rehearsal undo','agency.execution.cancelled':'Closed unused rehearsal command',
 'agency.plan.drafted':'Saved agency plan draft','agency.plan.reviewed':'Reviewed agency plan','agency.plan.withdrawn':'Withdrew agency plan','agency.plan.cancelled':'Closed unused agency plan request',
 'agency.observation.reviewed':'Reviewed agency recommendation','agency.observation.cancelled':'Closed unused agency review',
"audit.analysis.applied":"Applied saved analysis",
"audit.analysis.cancelled":"Cancelled analysis request",
"audit.analysis.discarded":"Discarded saved analysis",
"audit.analysis.requested":"Requested analysis",
"audit.analysis.resumed":"Resumed analysis",
"audit.analysis.retried":"Retried analysis",
"audit.analysis.stopped":"Stopped analysis",
"audit.crawl_retry_requested":"Requested crawl retry",
"audit.crawl_stopped":"Stopped crawl",
"audit.evaluation.applied":"Applied saved evaluation",
"audit.evaluation.cancelled":"Cancelled evaluation request",
"audit.evaluation.discarded":"Discarded saved evaluation",
"audit.evaluation.requested":"Requested evaluation",
"audit.finding_reviewed":"Reviewed finding",
"audit.queries_archived":"Archived measurement queries",
"audit.queries_created":"Created measurement queries",
"audit.queries_restored":"Restored measurement queries",
"audit.query_edited":"Edited measurement query",
"audit.recommendation_reviewed":"Reviewed recommendation",
"audit.report.cancelled":"Cancelled report request",
"audit.report.download_prepared":"Prepared report download",
"audit.report.prepared":"Prepared saved report",
"audit.report.reported":"Recorded report delivery evidence",
"audit.report.requested":"Requested report",
"audit.request_cancelled":"Cancelled audit request",
"audit.run_archived":"Archived audit run",
"audit.run_restored":"Restored audit run",
"audit.run_retry_requested":"Requested audit retry",
"audit.run_reviewed":"Reviewed audit run",
"audit.run_stopped":"Stopped audit run",
"audit.runs_requested":"Requested audit runs",
"bi.alert.dismissed":"Dismissed metric alert",
"bi.alert.request_cancelled":"Cancelled alert request",
"bi.alert.restored":"Restored metric alert",
"bi.alert.review_prepared":"Prepared alert review",
"bi.alert.reviewed":"Reviewed metric alert",
"bi.delivery.reported":"Recorded report delivery evidence",
"bi.delivery.started":"Started report delivery attempt",
"bi.goal.archived":"Archived metric goal",
"bi.goal.request_cancelled":"Cancelled goal request",
"bi.goal.restored":"Restored metric goal",
"bi.goal.saved":"Saved metric goal",
"bi.query.executed":"Executed reviewed query",
"bi.query.interpretation_held":"Held query interpretation for review",
"bi.query.interpretation_recorded":"Saved query interpretation",
"bi.query.interpretation_started":"Started query interpretation",
"bi.query.plan_revised":"Revised query plan",
"bi.query.request_cancelled":"Cancelled query request",
"bi.query.requested":"Requested saved query",
"bi.query.stopped":"Stopped query",
"bi.schedule.cancelled":"Cancelled report schedule",
"bi.schedule.claimed":"Claimed scheduled report",
"bi.schedule.created":"Created report schedule",
"bi.schedule.edited":"Edited report schedule",
"bi.schedule.empty":"Recorded empty scheduled report",
"bi.schedule.finished":"Finished scheduled report run",
"bi.schedule.held":"Held scheduled report for review",
"bi.schedule.paused":"Paused report schedule",
"bi.schedule.request_cancelled":"Cancelled schedule request",
"bi.schedule.resumed":"Resumed report schedule",
"bi.schedule.run_closed":"Closed scheduled report run",
"lead.record.created":"Created lead",
"lead.record.crm_prepared":"Prepared lead CRM handoff",
"lead.record.edited":"Edited lead",
"lead.record.followup_started":"Started lead follow-up",
"lead.record.request_cancelled":"Cancelled lead request",
"lead.record.status_changed":"Changed lead status",
"pipeline.import.account_progress":"Recorded account import progress",
"pipeline.import.finished":"Finished import",
"pipeline.import.progress":"Recorded import progress",
"pipeline.import.progress_reviewed":"Reviewed import progress",
"pipeline.import.queued":"Queued import",
"pipeline.import.report_saved":"Saved import source report",
"pipeline.import.request_cancelled":"Cancelled import request",
"pipeline.import.requested":"Requested import",
"pipeline.import.retry_requested":"Requested import retry",
"pipeline.import.started":"Started import",
"pipeline.import.stopped":"Stopped import",
'integration.credentials.renewal_started':'Reserved a connection access renewal','integration.credentials.renewal_updated':'Recorded connection renewal state','luma.request.accepted':'Saved original visitor request','luma.request.response_retained':'Retained actual request response','luma.request.model_started':'Reserved one recorded model invocation','luma.request.model_received':'Retained actual model response','luma.request.model_unknown':'Recorded an unconfirmed model response','luma.request.retain_hold':'Saved request investigation note','luma.request.release_saved_response':'Released exact saved request response','luma.request.cancel':'Cancelled unused request review','console.search.saved':'Saved a console search','console.search.result_selected':'Selected a saved search result','console.search.navigation_prepared':'Prepared navigation from a search result','console.search.request_cancelled':'Closed an unused search request','luma.conversation.taken_over':'Took over a conversation','luma.conversation.released':'Returned a conversation to the assistant','luma.conversation.replied':'Saved a staff reply','luma.conversation.archived':'Archived a conversation from the inbox','luma.conversation.restored':'Restored an inbox conversation','luma.conversation.reviewed':'Saved an exact transcript review','luma.conversation.export_prepared':'Prepared a saved transcript download','luma.conversation.export_reported':'Reported transcript download outcome','luma.conversation.request_cancelled':'Closed an unused conversation request','luma.conversation.message_saved':'Retained a conversation message','luma.conversation.inbox_reopened':'Returned a conversation with a new visitor message to the inbox','luma.conversation.reply_held':'Held an obsolete assistant reply','luma.widget.key_rotated':'Replaced widget installation key','luma.widget.logo_selected':'Selected reviewed widget logo','luma.widget.logo_cleared':'Removed widget logo','luma.widget.installation_prepared':'Prepared exact widget installation','luma.widget.installation_reported':'Reported widget handoff outcome','luma.widget.request_cancelled':'Closed unused widget request','bi.data.review_saved':'Saved exact data review','bi.data.row_excluded':'Excluded reviewed data row','bi.data.row_restored':'Restored reviewed data row','bi.data.export_prepared':'Prepared saved data review download','bi.data.export_reported':'Reported data review download outcome','bi.data.request_cancelled':'Closed unused data review request','bi.csv.preview_saved':'Saved CSV import preview','bi.csv.applied':'Applied reviewed CSV import','bi.csv.discarded':'Discarded CSV import preview','bi.csv.request_cancelled':'Closed unused CSV request','bi.report.saved':'Saved exact marketing report','bi.report.cancelled':'Cancelled unused report save','bi.export.prepared':'Prepared saved report export','bi.export.reported':'Browser reported export outcome','settings.organization_saved':'Organization settings saved','settings.profile_saved':'Console display name saved','settings.preferences_saved':'Console appearance saved','settings.cancelled':'Unused settings request cancelled','team.role_changed':'Team role changed','team.member_removed':'Organization access removed','team.invitation_created':'Team invitation created','team.invitation_rotated':'Team invitation link replaced','team.invitation_revoked':'Team invitation revoked','team.invitation_accepted':'Team invitation accepted','team.invitation_declined':'Team invitation declined','team.invitation_copy_reported':'Invitation copy reported by browser','team.join_cancelled':'Unused invitation decision cancelled','team.cancelled':'Unused team request cancelled','readiness.built':'Readiness check built', 'readiness.approved':'Readiness check approved', 'readiness.rejected':'Readiness check rejected', 'readiness.withdrawn':'Readiness approval withdrawn', 'readiness.cancelled':'Unused readiness request cancelled',
 'neighborhood.saved':'Neighborhood draft saved', 'neighborhood.approved':'Neighborhood source approved', 'neighborhood.rejected':'Neighborhood draft rejected', 'neighborhood.withdrawn':'Neighborhood approval withdrawn', 'neighborhood.archived':'Neighborhood source archived', 'neighborhood.restored':'Neighborhood source restored', 'neighborhood.cancelled':'Unused neighborhood request cancelled',
 'legal.saved':'Legal draft version saved','legal.approved':'Exact legal version approved','legal.rejected':'Legal draft rejected','legal.withdrawn':'Property legal approval withdrawn','legal.cancelled':'Unused legal decision cancelled','checklist.created':'Checklist task created','checklist.saved':'Checklist progress reported','checklist.archived':'Checklist task archived','checklist.restored':'Checklist task restored','checklist.setup_completed':'Property details task completed during setup','checklist.initialized':'Default checklist task initialized','checklist.cancelled':'Unused checklist decision cancelled','knowledge.file.upload_requested':'Original file requested',
  'knowledge.file.upload_stopped':'Unfinished upload stopped',
  'knowledge.file.recovered':'Original upload recovery requested',
  'knowledge.file.uploaded':'Private original retained',
  'knowledge.file.extraction_requested':'File text extraction requested',
  'knowledge.file.extraction_started':'File text extraction started',
  'knowledge.file.extraction_received':'File text receipt retained',
  'knowledge.file.extraction_recovered':'File extraction recovery requested',
  'knowledge.file.extraction_stopped':'File extraction stopped',
  'knowledge.file.reviewed':'File text reviewed and saved',
  'knowledge.file.download_prepared':'Private original download prepared',
  'knowledge.facts.prepared':'Prepared complete assistant facts','knowledge.facts.edited':'Saved an assistant facts correction','knowledge.facts.published':'Published exact reviewed assistant facts','knowledge.facts.withdrawn':'Withdrew published assistant facts','knowledge.decision.cancelled':'Cancelled an unused knowledge decision','knowledge.source.saved':'Saved a retained knowledge version','knowledge.search.requested':'Requested search preparation','knowledge.search.stopped':'Stopped search preparation','knowledge.search.recovered':'Checked retained search preparation','knowledge.source.published':'Published reviewed knowledge','knowledge.source.withdrawn':'Withdrew published knowledge','knowledge.search.started':'Started one search preparation','knowledge.search.result_received':'Retained search preparation receipt','knowledge.search.prepared':'Prepared search data for review','knowledge.search.held':'Held search preparation for review',  'organization.setup.completed':'Organization and first property setup completed',
  'knowledge.web.policy_saved':'Website monitoring policy reviewed',
  'knowledge.web.scheduled':'Private website capture scheduled',
  'knowledge.web.requested': 'Website capture requested',
  'knowledge.web.recovered': 'Website capture recovery checked',
  'knowledge.web.stopped': 'Website capture stopped',
  'knowledge.web.reviewed': 'Website text reviewed',
  'knowledge.web.download_prepared': 'Website original download prepared',
  'knowledge.web.started': 'Website fetch started',
  'knowledge.web.received': 'Website capture receipt retained',
'property.unit.draft_saved':'Saved floor-plan draft','property.unit.approved':'Approved exact floor-plan facts','property.unit.draft_rejected':'Rejected floor-plan draft','property.unit.retired':'Retired floor-plan facts','property.unit.restored':'Restored reviewed floor-plan facts','property.created':'Created a property from reviewed setup','property.onboarding.completed':'Completed property setup details','property.setup.saved':'Saved property details and contacts','site.delivery.recorded':'Retained website delivery record','site.delivery.reviewed':'Reviewed reported delivery evidence','site.delivery.withdrawn':'Withdrew delivery evidence review','site.brief.saved':'Saved Codex brief','site.brief.export_prepared':'Prepared brief handoff','site.brief.export_reported':'Reported browser handoff outcome','lead.note.created':'Added an internal lead note','lead.note.corrected':'Corrected a lead note with retained history','lead.note.withdrawn':'Withdrew an internal lead note','lead.note.restored':'Restored a withdrawn lead note','market.brand_search.saved':'Saved a search of reviewed brand evidence','market.brand.requested':'Requested saved brand analysis','market.brand.stopped':'Stopped saved brand analysis','market.brand.recovered':'Recovered retained brand analysis','market.brand.published':'Saved reviewed brand statements','market.brand.withdrawn':'Withdrew reviewed brand statements','market.brand.started':'Started saved brand analysis','market.brand.result_received':'Retained brand model result','market.brand.previewed':'Prepared source-backed brand preview','market.brand.held':'Held brand analysis for review','market.alert.created':'Reported a market alert','market.alert.read':'Reviewed displayed market alerts','market.alert.dismissed':'Dismissed reviewed market alerts','market.alert.restored':'Restored dismissed market alerts','market.intake.prepared':'Saved competitor intake preview','market.intake.applied':'Applied reviewed competitor identities','market.intake.stopped':'Stopped saved competitor intake','market.handoff.prepared':'Prepared exact ForgeStudio draft handoff','market.handoff.decided':'Reviewed ForgeStudio draft handoff','market.brief.requested':'Requested saved market brief','market.brief.recovered':'Recovered saved market brief','market.brief.completed':'Completed exact market brief','market.brief.reviewed':'Reviewed market recommendation','market.brief.exported':'Prepared market brief download','market.source.requested':'Requested retained market source','market.source.stopped':'Stopped market source acquisition','market.source.recovered':'Recovered saved market source','market.source.started':'Started public page acquisition','market.source.result_received':'Retained public source receipt','market.source.held':'Held market source acquisition','market.listing.saved':'Saved competitor listing','market.listing.removed':'Removed competitor listing','market.extraction.requested':'Requested source pricing extraction','market.extraction.stopped':'Stopped pricing extraction','market.extraction.recovered':'Recovered saved pricing extraction','market.extraction.rebased':'Refreshed the pricing review baseline','market.extraction.applied':'Applied exact reviewed pricing candidates','market.extraction.started':'Started saved source extraction','market.extraction.result_received':'Retained extraction model receipt','market.extraction.previewed':'Prepared saved pricing candidates','market.extraction.held':'Held source extraction for review','market.competitor.saved':'Saved competitor details','market.competitor.archived':'Archived a competitor','market.competitor.restored':'Restored a competitor','market.unit.saved':'Saved competitor unit values','market.unit.removed':'Removed a competitor unit with retained history','market.configuration.saved':'Saved market monitoring settings','review.testimonial.approved':'Approved exact testimonial permissions','review.testimonial.revoked':'Revoked testimonial permissions','review.connection.saved':'Saved review source settings','review.connection.disconnected':'Disconnected a review source locally','review.insights.saved':'Saved exact review insights report','review.batch.prepared':'Review analysis selection saved',
 'review.batch.approved':'Review analysis scope approved',
 'review.batch.stopped':'Review analysis queue stopped',
 'review.batch.recovered':'Review analysis queue recovery requested',
 'review.batch.progressed':'Review analysis queue progressed',
 'review.intake.requested':'Review import requested',
 'review.intake.scheduled':'Review source check scheduled',
 'review.intake.started':'Review source check started',
 'review.intake.result_received':'Review source result saved',
 'review.intake.previewed':'Review import preview saved',
 'review.intake.held':'Review import held for review',
 'review.intake.applied':'Review import applied',
 'review.intake.stopped':'Review import stopped',
 'review.intake.recovered':'Review import recovery requested',
 'review.intake.rebased':'Review import preview rebuilt',
 'review.configuration.saved':'Saved review response preferences','review.publication.prepared':'Prepared an approved review response for publication','review.publication.reported':'Reported manual review response publication','review.publication.cancelled':'Confirmed a review response was not published','review.publication.uncertain':'Recorded an uncertain review publication','review.response.draft_saved':'Saved a review response draft','review.response.approved':'Approved an exact review response','review.response.rejected':'Rejected a review response','review.response.generation_requested':'Requested a response draft','review.response.generation_started':'Started saved response generation','review.response.generation_result_received':'Recorded response model result','review.response.generation_completed':'Saved generated response draft','review.response.generation_stopped':'Stopped response generation','review.response.generation_recovered':'Requested saved response recovery','review.case.created':'Opened a review case','review.case.updated':'Updated review case details','review.case.resolved':'Recorded review case resolution','review.case.dismissed':'Dismissed a review case','review.case.reopened':'Reopened a review case','review.case.note_added':'Added a review case note','review.ticket.created':'Created review staff work','review.ticket.updated':'Updated review staff work','review.ticket.reopened':'Reopened review staff work','review.analysis.started':'Started saved review analysis','review.analysis.result_received':'Recorded review model result','review.analysis.requested':'Requested review analysis','review.analysis.completed':'Saved review analysis','review.analysis.stopped':'Stopped review analysis','review.analysis.recovered':'Requested saved analysis recovery','studio.credentials.renewal_requested':'Requested social access renewal','studio.credentials.renewal_completed':'Saved social access renewal result','studio.app_configuration.save':'Saved social app setup','studio.app_configuration.disable':'Disabled social app setup','studio.connection.disconnected':'Disconnected a social account','studio.authorization.started':'Started social authorization','studio.authorization.cancelled':'Cancelled social authorization','studio.authorization.applied':'Reviewed and connected social accounts','studio.configuration.saved':'Saved studio preferences','studio.metrics.requested':'Requested publication metrics','studio.metrics.reported':'Reported sourced campaign metrics','studio.metrics.reviewed':'Reviewed campaign measurement evidence','studio.attribution.reviewed':'Reviewed attributed outcome evidence','studio.media.requested':'Requested media generation','studio.media.stopped':'Stopped media generation','studio.media.recovered':'Recovered a generated file','studio.media.completed':'Saved generated media','studio.asset.saved':'Saved asset details','studio.asset.reviewed':'Reviewed asset usage','studio.asset.archived':'Archived an asset','studio.asset.restored':'Restored an asset','studio.asset.upload.requested':'Requested asset upload','studio.asset.uploaded':'Saved an uploaded asset','studio.asset.replaced':'Replaced an asset file','studio.asset.upload.recovered':'Recovered a stored upload','studio.sources.refreshed':'Refreshed campaign source evidence','studio.generation.requested':'Requested campaign generation','studio.generation.stopped':'Stopped campaign generation','studio.generation.recovered':'Recovered saved campaign generation','studio.publications.scheduled':'Scheduled campaign publications','studio.publication.recovery_reviewed':'Reviewed publication recovery',
  'studio.publication.cancel':'Cancelled campaign publication','studio.publication.reschedule':'Rescheduled campaign publication','studio.brief.saved':'Saved campaign brief','studio.package.created':'Saved campaign draft','studio.revision.saved':'Saved campaign revision','studio.revision.reviewed':'Reviewed campaign revision','crm.qualification.prepared':'Prepared CRM provider test','crm.qualification.approved':'Approved CRM provider test','crm.qualification.recovered':'Requested CRM test recovery','crm.qualification.activated':'Activated verified CRM lead delivery','crm.qualification.stopped':'Stopped CRM provider test','crm.qualification.completed':'Saved CRM provider test result','crm.bulk.prepared':'Saved CRM batch selection','crm.bulk.approved':'Approved CRM batch','crm.bulk.stopped':'Stopped remaining CRM batch transfers','crm.delivery.recovery_requested':'Requested CRM destination check','crm.delivery.recovery_checked':'Saved CRM destination evidence','crm.delivery.approved':'Approved CRM delivery','crm.delivery.requested':'Requested CRM delivery','crm.delivery.completed':'Saved CRM delivery result','crm.delivery.cancelled':'Stopped CRM delivery','crm.delivery.reconciled':'Reconciled CRM delivery','crm.mapping.saved':'Saved CRM mapping','crm.mapping.previewed':'Previewed CRM transfer values','crm.mapping.approved':'Approved CRM field mapping','crm.operation.requested':'Requested CRM setup check','crm.operation.completed':'Saved CRM setup check result','crm.operation.stopped':'Stopped CRM setup check','lead.score.reviewed':'Reviewed lead priority','lead.engagement.recorded':'Recorded reported engagement','lead.engagement.corrected':'Withdrew reported engagement','lead.score.recalculated':'Recalculated lead score','lead.scoring.started':'Started scoring run','lead.scoring.completed':'Finished scoring run','lead.scoring.cancelled':'Stopped scoring run','brand.research.requested':'Started competitor research','brand.research.completed':'Saved competitor research result','brand.research.cancelled':'Stopped competitor research','brand.source.saved':'Saved brand review source','brand.asset.upload.requested':'Started brand asset upload','brand.asset.uploaded':'Saved brand asset','brand.asset.reviewed':'Reviewed brand asset rights','brand.import.previewed':'Prepared brand import preview','brand.revision.started':'Started brand revision','brand.visuals.generated':'Generated visual candidates','brand.knowledge.published':'Published brand knowledge','brand.operation.requested':'Started brand request','brand.operation.cancelled':'Stopped brand request','brand.brief.saved':'Saved brand brief','brand.section.generated':'Generated brand section','brand.section.regenerated':'Regenerated brand section','brand.section.edited':'Edited brand section','brand.section.approved':'Approved brand section','brand.contract.generated':'Prepared brand for review','brand.contract.imported':'Approved imported brand','brand.export.created':'Created brand export','tour.calendar_event.bound':'Linked existing calendar event','integration.authorization.started':'Started connection request','integration.authorization.cancelled':'Cancelled connection request','integration.authorization.failed':'Connection request stopped','integration.replacement.requested': 'Requested account replacement',
 'integration.account.replaced': 'Replaced connected account',
 'integration.invite.created':'Created authorization link','integration.invite.revoked':'Revoked authorization link','integration.authorization.completed':'Authorized integration','email.disconnected':'Disconnected email','calendar.disconnected':'Disconnected calendar','tour.calendar_change.reviewed':'Reviewed external calendar change','luma.configuration.created':'Initialized leasing assistant','luma.configuration.saved':'Saved leasing assistant settings','tour.schedule_delivery.reviewed':'Reviewed tour change delivery','tour.timezone.set':'Set tour timezone','tour.booked':'Booked tour','tour.outcome.recorded':'Recorded tour outcome','tour.no_show.corrected':'Corrected no-show','tour.rescheduled':'Rescheduled tour','tour.cancelled':'Cancelled tour','tour.reminder.reviewed':'Reviewed tour reminder','console.page.viewed':'Opened page','workflow.pause':'Paused follow-up','workflow.resume':'Resumed follow-up','workflow.stop':'Stopped follow-up','workflow.delivery.reviewed':'Reviewed follow-up delivery'}
