"use client"
import {useCallback,useEffect,useRef,useState} from 'react'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog'
import type {DataReviewPage,DataReviewRow} from '@/utils/analytics/data-review-contracts'

type Props={propertyId:string;startDate:string;endDate:string}
type SavedResult={id:string;reviewId:string|null;status:string;artifact?:unknown;artifactHash?:string}
type HistoryRow={id:string;created_at:string;actor_id:string;start_date?:string;end_date?:string;row_count?:number;input?:Record<string,unknown>;before_state?:unknown;after_state?:unknown;result?:unknown}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-40',field='w-full rounded-lg border p-2 bg-transparent'
async function json(response:Response){const body=await response.json();if(!response.ok)throw Object.assign(new Error(body.error||'The saved result could not be confirmed.'),{status:response.status});return body}
export function MarketingDataReview(props:Props){const[open,setOpen]=useState(false);return <><button type="button" className={button} onClick={()=>setOpen(true)}>Review data</button><Dialog open={open} onOpenChange={setOpen}>{open&&<Workspace key={`${props.propertyId}:${props.startDate}:${props.endDate}`} {...props} close={()=>setOpen(false)}/>}</Dialog></>}
function Workspace({propertyId,startDate,endDate,close}:Props&{close:()=>void}){
 const[data,setData]=useState<DataReviewPage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState<string|null>(null),[selected,setSelected]=useState<DataReviewRow|null>(null),[reason,setReason]=useState(''),[prepared,setPrepared]=useState<SavedResult|null>(null)
 const generation=useRef(0),actor=useRef(''),storage=useRef(''),mounted=useRef(true)
 const load=useCallback(async(kind='current',reviewId:string|null=null,offset=0,hash?:string)=>{
  const ticket=++generation.current;setBusy(true);setError('');setSelected(null);setReason('')
  try{const params=new URLSearchParams({propertyId,startDate,endDate,kind,offset:String(offset),...(reviewId?{reviewId}:{}),...(hash?{hash}:{})});const body=await json(await fetch(`/api/analytics/reconciliation?${params}`));if(!mounted.current||ticket!==generation.current)return;if(body.complete!==true||!Array.isArray(body.items))throw new Error('The complete review could not be confirmed.');actor.current=body.actorId;storage.current=`p11.data-review.v1:${body.actorId}:${propertyId}`;setData(body);const saved=sessionStorage.getItem(storage.current);setPending(saved&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(saved)?saved:null)
  }catch(e){if(mounted.current&&ticket===generation.current)setError(e instanceof Error?e.message:'The review is unavailable.')}finally{if(mounted.current&&ticket===generation.current)setBusy(false)}
 },[propertyId,startDate,endDate])
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false}},[load])
 const clear=()=>{sessionStorage.removeItem(storage.current);setPending(null)}
 async function accept(result:SavedResult){clear();setMessage(result.status==='cancelled'?'Unused request closed.':result.status==='export_prepared'?'Exact download prepared.':result.status==='reported'?'Browser download outcome recorded.':'Decision saved.');if(result.artifact){setPrepared(result);return}setPrepared(null);if(result.reviewId)await load('rows',result.reviewId);else await load()}
 async function send(input:Record<string,unknown>,existing?:string){if(!actor.current)return;const id=existing||crypto.randomUUID();sessionStorage.setItem(storage.current,id);setPending(id);setBusy(true);setError('');setMessage('');try{await accept(await json(await fetch('/api/analytics/reconciliation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,propertyId,expectedActorId:actor.current,...input})})))}catch(e){if((e as{status?:number}).status===400)clear();setError(e instanceof Error?e.message:'Check the saved request before continuing.')}finally{setBusy(false)}}
 async function recover(){if(!pending)return;setBusy(true);setError('');try{await accept(await json(await fetch(`/api/analytics/reconciliation?${new URLSearchParams({propertyId,commandId:pending})}`)))}catch(e){setError(e instanceof Error?e.message:'The request is unavailable.')}finally{setBusy(false)}}
 async function download(){if(!prepared?.artifact||!prepared.reviewId)return;let outcome='initiated';let url:string|undefined;try{url=URL.createObjectURL(new Blob([JSON.stringify(prepared.artifact,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`marketing-data-review-${prepared.reviewId}.json`;document.body.appendChild(link);link.click();link.remove()}catch{outcome='failed'}finally{if(url)URL.revokeObjectURL(url)}await send({operation:'report',reviewId:prepared.reviewId,exportId:prepared.id,artifactHash:prepared.artifactHash,outcome})}
 const rows=data?.kind==='current'||data?.kind==='rows',locked=busy||!!pending
 return <DialogContent aria-labelledby="marketing-review-title" className="max-w-4xl max-h-[92vh] flex flex-col min-w-0">
  <DialogHeader><DialogTitle id="marketing-review-title">Marketing data review</DialogTitle><DialogDescription>{startDate} to {endDate}. Originals are retained. Review source details before excluding overlaps or replacing values with a reviewed provider CSV.</DialogDescription></DialogHeader>
  <div className="p-4 sm:p-6 overflow-auto min-w-0 space-y-4 text-sm">
   <div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void load()}>Refresh current data</button><button className={button} disabled={busy} onClick={()=>void load('history')}>Saved data reviews</button><button className={button} disabled={busy} onClick={()=>void load('decisions')}>Data decision history</button></div>
   {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p>Loading saved data…</p>}
   {pending&&<div className="rounded-lg border border-amber-300 p-3 space-y-2"><p>An earlier request needs confirmation. Its identity is retained in this browser session; source data and notes are kept privately on the server.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void recover()}>Check saved data request</button><button className={button} disabled={busy} onClick={()=>void send({operation:'cancel'},pending)}>Cancel unused data request</button></div></div>}
   {prepared&&<div className="space-y-2"><p>The exact saved review is ready. A browser download report confirms that the download was initiated, not that it reached a destination.</p><button className={button} disabled={locked} onClick={()=>void download()}>Download prepared data review</button></div>}
   {data&&<section aria-label="Data review results" className="space-y-3">
    <h3 className="font-semibold">{data.kind==='history'?'Saved data reviews':data.kind==='decisions'?'Data decision history':data.reviewId?'Saved data snapshot':'Current source data'}</h3>
    <p>{data.count} {rows?'source rows':data.kind==='history'?'saved reviews':'decisions'} · {data.count===0?'No records':`${data.offset+1}–${Math.min(data.count,data.offset+25)} shown`}. {data.reviewId&&'This is a historical snapshot; refresh and save a new review after each change.'}</p>
    {rows&&<div className="flex flex-wrap gap-2">{!data.reviewId?<button className={button} disabled={locked} onClick={()=>void send({operation:'save',startDate,endDate,sourceHash:data.hash})}>Save exact data review</button>:<button className={button} disabled={locked} onClick={()=>void send({operation:'export',reviewId:data.reviewId})}>Prepare data review download</button>}</div>}
    {rows?<ul className="divide-y">{data.items.map(row=><li key={`${row.kind}:${row.id}`} className="py-3 space-y-1"><button className="font-medium text-indigo-600 text-left break-words" onClick={()=>{setSelected(row);setReason('')}}>{String(row.source.campaign_name||row.source.campaign_id||'Unidentified campaign')} · {String(row.source.date||row.source.dimension_value||'Unknown period')}</button><p>{row.kind==='daily'?'Daily totals':'Dimension totals'} · {String(row.source.channel_id||'Unknown channel')} · {row.source.source_account_id?`Account ${row.source.source_account_id}`:'Account needs review'} · {row.excluded?'Excluded from reporting':'Included in reporting'}</p><p>{row.reasons.length?row.reasons.join('; '):'No missing source details detected. Confirm totals against the provider export.'}</p></li>)}</ul>:<ul className="divide-y">{(data.items as unknown as HistoryRow[]).map(item=><li key={item.id} className="py-3 space-y-2"><p>{new Date(item.created_at).toLocaleString()} · Team member {item.actor_id}</p>{data.kind==='history'?<button className={button} disabled={busy} onClick={()=>void load('rows',item.id)}>{item.start_date} to {item.end_date} · {item.row_count} rows</button>:<details><summary>{String(item.input?.operation)} · {String((item.result as{status?:string})?.status||'saved')}</summary><pre className="whitespace-pre-wrap break-all max-h-80 overflow-auto">{JSON.stringify({input:item.input,before:item.before_state,after:item.after_state,result:item.result},null,2)}</pre></details>}</li>)}</ul>}
    <div className="flex gap-2"><button className={button} disabled={busy||data.offset===0} onClick={()=>void load(data.kind,data.reviewId,Math.max(0,data.offset-25),data.hash)}>Previous data page</button><button className={button} disabled={busy||data.offset+25>=data.count} onClick={()=>void load(data.kind,data.reviewId,data.offset+25,data.hash)}>Next data page</button></div>
   </section>}
   {selected&&<section aria-label="Exact source row" className="rounded-lg border p-3 space-y-3"><h3 className="font-semibold">Exact source row</h3><pre className="whitespace-pre-wrap break-all max-h-64 overflow-auto">{JSON.stringify(selected.source,null,2)}</pre><p>Exclusion preserves this original and removes it from current reporting. To correct values, use the CSV import preview with the actual source account. Restore an excluded known-account row before replacing its values. These are staff decisions, not independent provider verification.</p>{data?.reviewId&&data.canManage?<><label className="block">Data decision reason<textarea className={field} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className={button} disabled={locked||!reason.trim()} onClick={()=>void send({operation:selected.excluded?'restore':'exclude',reviewId:data.reviewId,rowId:selected.id,kind:selected.kind,reason:reason.trim()})}>{selected.excluded?'Restore reviewed row':'Exclude reviewed row'}</button></>:<p>{data?.canManage?'Save an exact review before deciding on a row.':'Only a property manager or administrator can change reporting inclusion.'}</p>}</section>}
  </div><DialogFooter><button className={button} onClick={close}>Close data review</button></DialogFooter>
 </DialogContent>
}
