import {expect,it} from 'vitest'
import {unitData,unitCommand,unitQuery,formatUnitNumber,unitEligibility,type PublishedUnit} from './contracts'
const id='11111111-1111-1111-1111-111111111111'
const data={canonicalKey:'studio',name:'Studio',bedrooms:0,bathrooms:null,sqftMin:500,sqftMax:null,priceMin:0,priceMax:null,deposit:0,available:0,specials:'',sourceLabel:'Staff confirmation',sourceUrl:'',sourceNote:'Exact confirmation 🏡',observedAt:'2026-09-01T00:00:00Z',effectiveAt:null,expiresAt:null}
it('preserves zero, unknown and literal source evidence',()=>{expect(unitData.parse(data)).toEqual(data);expect(formatUnitNumber(0,'money')).toBe('$0.00');expect(formatUnitNumber(null)).toBe('Unknown');expect(formatUnitNumber(undefined)).toBe('Unknown')})
it.each([{bedrooms:null},{priceMin:2,priceMax:1},{sqftMin:0},{available:-1},{bathrooms:1.11},{priceMin:1.001},{sourceUrl:'javascript:alert(1)'},{sourceUrl:'https://user:pass@example.test'},{sourceNote:'x'.repeat(32769)},{sourceNote:'\ud800xx'},{sourceNote:'a\0b'},{expiresAt:'2026-08-01T00:00:00Z',effectiveAt:'2026-09-01T00:00:00Z'},{provider:'openai'}])('holds invalid or unsupported data %j',change=>expect(unitData.safeParse({...data,...change}).success).toBe(false))
it('retains literal CRLF and non-ASCII source text',()=>expect(unitData.parse({...data,sourceNote:'  Exact\r\n🏡  '}).sourceNote).toBe('  Exact\r\n🏡  '))
it('requires complete decision ancestry and exact approval',()=>{const save={requestId:id,propertyId:id,operation:'save',unitId:null,expectedDraftId:null,expectedDecisionId:null,expectedUnitHash:'a'.repeat(64),copiedFromVersionId:null,data,reason:'Confirm facts'};expect(unitCommand.safeParse(save).success).toBe(true);expect(unitCommand.safeParse({...save,copiedFromVersionId:undefined}).success).toBe(false);expect(unitCommand.safeParse({...save,operation:'approve',confirmed:false}).success).toBe(false)})
it('accepts local non-RFC UUIDs and exact scoped query shapes',()=>{expect(unitQuery.safeParse({propertyId:id}).success).toBe(true);expect(unitQuery.safeParse({propertyId:id,kind:'unit'}).success).toBe(false);expect(unitQuery.safeParse({propertyId:id,kind:'versions',unitId:id,versionId:id}).success).toBe(false);expect(unitQuery.safeParse({propertyId:id,kind:'unit',unitId:id,versionId:id}).success).toBe(true)})
it('does not describe expired, future, unreviewed or retired rows as usable',()=>{const unit={active:true,review_status:'approved',effective_at:null,expires_at:null}as PublishedUnit;expect(unitEligibility(null)).toBe('Private draft');expect(unitEligibility({...unit,active:false})).toBe('Retired');expect(unitEligibility({...unit,review_status:'pending'})).toBe('Awaiting review');expect(unitEligibility({...unit,effective_at:'2100-01-01T00:00:00Z'})).toBe('Not yet effective');expect(unitEligibility({...unit,expires_at:'2000-01-01T00:00:00Z'})).toBe('Expired');expect(unitEligibility(unit)).toBe('Eligible for reviewed assistant facts')})
