import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({actor:vi.fn(),read:vi.fn(),decide:vi.fn()}))
vi.mock('@/utils/knowledge/material-store',()=>({materialActor:d.actor,readMaterials:d.read,decideMaterial:d.decide,knowledgeExecutionStatus:()=>({paused:true,configured:true}),MaterialError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {GET,POST} from './route'
import {MaterialError} from '@/utils/knowledge/material-store'
const property='33333333-3333-3333-3333-333333333333',id='11111111-1111-1111-1111-111111111111',value={requestId:id,propertyId:property,operation:'save',materialId:null,previousVersionId:null,title:'Policy',content:'Exact\r\ntext',reason:'Reviewed original'}
beforeEach(()=>{vi.clearAllMocks();d.actor.mockResolvedValue('actor');d.decide.mockResolvedValue({state:'saved',materialId:id,versionId:id,published:false});d.read.mockResolvedValue({state:'ready',propertyId:property,items:[]})})
it('authenticates before accepting source text',async()=>{d.actor.mockRejectedValue(new MaterialError('Unauthorized',401));expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(value)}))).status).toBe(401);expect(d.decide).not.toHaveBeenCalled()})
it('rejects unknown fields and the old immediate import shape',async()=>{for(const input of[{...value,metadata:{}},{propertyId:property,title:'Policy',content:'old import'}])expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(input)}))).status).toBe(400);expect(d.decide).not.toHaveBeenCalled()})
it('preserves exact text and actor while returning a private receipt',async()=>{const response=await POST(new Request('http://local',{method:'POST',body:JSON.stringify(value)}));expect(response.status).toBe(200);expect(response.headers.get('Cache-Control')).toBe('private, no-store');expect(d.decide).toHaveBeenCalledWith('actor',value)})
it('checks request size and invalid JSON before mutations',async()=>{expect((await POST(new Request('http://local',{method:'POST',headers:{'content-length':'1048577'},body:'{}'}))).status).toBe(413);expect((await POST(new Request('http://local',{method:'POST',body:'{'}))).status).toBe(400);expect(d.decide).not.toHaveBeenCalled()})
it('reads never start model preparation and native denials remain denials',async()=>{const response=await GET(new Request(`http://local?propertyId=${property}`));expect(response.status).toBe(200);expect(d.decide).not.toHaveBeenCalled();d.read.mockRejectedValue(new MaterialError('Forbidden',403));expect((await GET(new Request(`http://local?propertyId=${property}`))).status).toBe(403)})
it('validates history addressing and never turns unavailable reads into empty success',async()=>{expect((await GET(new Request(`http://local?propertyId=${property}&kind=version`))).status).toBe(400);d.read.mockRejectedValue(new Error('database details'));const response=await GET(new Request(`http://local?propertyId=${property}`));expect(response.status).toBe(503);expect(await response.json()).toEqual({error:'Saved knowledge is unavailable.'})})
