import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
const {from,rpc,prepare,execute,parse}=vi.hoisted(()=>({from:vi.fn(),rpc:vi.fn(),prepare:vi.fn(),execute:vi.fn(),parse:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({from,rpc})}))
vi.mock('./ai',()=>({prepareReviewAnalysis:prepare,executeSavedReviewAnalysis:execute,parseSavedReviewAnalysis:parse}))
import {requestReviewAnalysis,runSavedReviewAnalysis,recoverReviewAnalysis,automaticAnalysisId} from './analysis-store'
const input={propertyId:'property',requestId:'request',reviewId:'review',sourceVersion:2},receipt={status:'received',content:'saved raw output'},classification={summary:'Parsed fixture'}
function chain(data:unknown,error:unknown=null){const q={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data,error})};q.select.mockReturnValue(q);q.eq.mockReturnValue(q);return q}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');prepare.mockReturnValue({model:'fixture-model',source:{}});parse.mockReturnValue(classification);execute.mockResolvedValue(receipt);from.mockImplementation((name:string)=>chain(name==='reviews'?{id:'review',source_version:2,review_text:'Saved review',rating:5,platform:'other',reviewer_name:'Fixture'}:null));rpc.mockImplementation(async(name:string)=>({data:name==='begin_reviewflow_analysis'?{state:'queued',requestId:'request'}:name==='claim_reviewflow_analysis'?{state:'invoke_once',claimToken:'one-claim',modelInput:{model:'fixture-model'},propertyId:'property',actorId:'actor'}:name==='record_reviewflow_analysis_result'?{state:'saved',requestState:'result_ready'}:{state:'saved',analysisId:'request'},error:null}))})
afterEach(()=>vi.unstubAllEnvs())
describe('durable review analysis service',()=>{
 it('saves a request while paused without a model call',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect(await requestReviewAnalysis(input,'actor')).toMatchObject({state:'queued'});expect(prepare).toHaveBeenCalledWith({reviewText:'Saved review',rating:5,platform:'other',reviewerName:'Fixture'});expect(execute).not.toHaveBeenCalled()})
 it('replays an existing decision without rebuilding its model context',async()=>{from.mockReturnValue(chain({id:'request'}));await requestReviewAnalysis(input,'actor');expect(prepare).not.toHaveBeenCalled();expect(rpc.mock.calls[0][1]).toMatchObject({p_input:{reviewId:'review',sourceVersion:2},p_model_input:{}})})
 it('does not claim a queued request while model execution is paused',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect(await runSavedReviewAnalysis('request')).toEqual({state:'paused'});expect(rpc).not.toHaveBeenCalled();expect(execute).not.toHaveBeenCalled()})
 it('never invokes the model if its claim acknowledgement is missing',async()=>{rpc.mockResolvedValue({data:null,error:{message:'lost reply'}});await expect(runSavedReviewAnalysis('request')).rejects.toThrow('could not be confirmed');expect(execute).not.toHaveBeenCalled();expect(rpc).toHaveBeenCalledTimes(1)})
 it('never restarts an already claimed model request',async()=>{rpc.mockResolvedValue({data:{state:'running'},error:null});expect(await runSavedReviewAnalysis('request')).toEqual({state:'running'});expect(execute).not.toHaveBeenCalled()})
 it('retries only the identical saved result after a lost persistence reply',async()=>{let attempts=0;const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,...args:unknown[])=>name==='record_reviewflow_analysis_result'&&attempts++===0?{data:null,error:{message:'lost reply'}}:original(name,...args));from.mockReturnValue(chain({state:'result_ready',model_input:{},raw_result:receipt,result_hash:'saved-hash'}));expect(await runSavedReviewAnalysis('request')).toMatchObject({analysisId:'request'});expect(execute).toHaveBeenCalledTimes(1);const calls=rpc.mock.calls.filter(c=>c[0]==='record_reviewflow_analysis_result');expect(calls).toHaveLength(2);expect(calls[0][1]).toEqual(calls[1][1]);expect(rpc).toHaveBeenCalledWith('apply_reviewflow_analysis',expect.objectContaining({p_result:{resultHash:'saved-hash',analysis:classification}}))})
 it('retains an uncertain provider outcome without retrying the model',async()=>{execute.mockRejectedValue(new Error('timeout'));const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,...args:unknown[])=>name==='record_reviewflow_analysis_result'?{data:{state:'saved',requestState:'held'},error:null}:original(name,...args));expect(await runSavedReviewAnalysis('request')).toMatchObject({requestState:'held'});expect(execute).toHaveBeenCalledTimes(1);expect(rpc).toHaveBeenCalledWith('record_reviewflow_analysis_result',expect.objectContaining({p_result:{status:'uncertain',errorCode:'model_uncertain'}}));expect(parse).not.toHaveBeenCalled()})
 it('never applies a stopped late result',async()=>{const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,...args:unknown[])=>name==='record_reviewflow_analysis_result'?{data:{state:'saved',requestState:'stopped'},error:null}:original(name,...args));await runSavedReviewAnalysis('request');expect(parse).not.toHaveBeenCalled();expect(from).not.toHaveBeenCalled()})
 it('recovers only the saved raw result and records a validation hold without another model',async()=>{from.mockReturnValue(chain({state:'result_ready',model_input:{},raw_result:receipt,result_hash:'saved-hash'}));parse.mockImplementation(()=>{throw new Error('invalid quotes')});await recoverReviewAnalysis('request','property','actor');expect(execute).not.toHaveBeenCalled();expect(rpc).toHaveBeenCalledWith('apply_reviewflow_analysis',expect.objectContaining({p_result:{resultHash:'saved-hash',errorCode:'invalid_output'}}))})
 it('uses stable but source- and operator-specific automatic request identities',()=>{const first=automaticAnalysisId('review',1,'actor');expect(first).toMatch(/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-8[a-f0-9]{3}-[a-f0-9]{12}$/);expect(first).toBe(automaticAnalysisId('review',1,'actor'));expect(first).not.toBe(automaticAnalysisId('review',2,'actor'));expect(first).not.toBe(automaticAnalysisId('review',1,'other'))})
})
