import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
const {completion}=vi.hoisted(()=>({completion:vi.fn()}))
vi.mock('openai',()=>({default:class{chat={completions:{create:completion}}}}))
import {prepareReviewAnalysis,executeSavedReviewAnalysis,parseSavedReviewAnalysis,resetReviewAiClientForTests} from './ai'
const source={reviewText:'The pool was clean.',rating:5,platform:'other',reviewerName:'Fixture'}
const output={sentiment:'positive',sentimentScore:0.8,topics:['amenities'],journeyStage:'residency',issueDomains:['amenities'],severity:'low',riskClass:'routine',policyClass:'standard',isUrgent:false,confidence:0.9,summary:'A clean pool.',recommendedAction:'Thank the reviewer.',evidence:[{claim:'Clean pool',quote:source.reviewText}]}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');resetReviewAiClientForTests();completion.mockResolvedValue({id:'saved-completion',choices:[{message:{content:JSON.stringify(output)}}],usage:{prompt_tokens:25,completion_tokens:35}})})
afterEach(()=>vi.unstubAllEnvs())
describe('saved review analysis contract',()=>{
 it('freezes exact source, prompts, model and policy versions before execution',()=>{const input=prepareReviewAnalysis(source);expect(input.source).toEqual(source);expect(input.userPrompt).toContain(source.reviewText);expect(input.promptVersion).toBe('analysis-v3');expect(input.policyVersion).toBe('reviewflow-policy-v1')})
 it('saves raw provider text and usage after one bounded model request without SDK retries',async()=>{const input=prepareReviewAnalysis(source),receipt=await executeSavedReviewAnalysis(input);expect(receipt).toMatchObject({status:'received',content:JSON.stringify(output),providerId:'saved-completion',usage:{promptTokens:25,completionTokens:35}});expect(completion).toHaveBeenCalledTimes(1);expect(completion.mock.calls[0][0]).toMatchObject({model:input.model,messages:[{role:'system',content:input.systemPrompt},{role:'user',content:input.userPrompt}]});expect(completion.mock.calls[0][1]).toEqual({maxRetries:0,timeout:90_000})})
 it('does not invoke a provider while paused',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');await expect(executeSavedReviewAnalysis(prepareReviewAnalysis(source))).rejects.toThrow('paused');expect(completion).not.toHaveBeenCalled()})
 it('does not send the saved review to a changed provider configuration',async()=>{const input=prepareReviewAnalysis(source);vi.stubEnv('REVIEWFLOW_AI_BASE_URL','https://different.example.invalid/v1');await expect(executeSavedReviewAnalysis(input)).rejects.toThrow('configuration changed');expect(completion).not.toHaveBeenCalled()})
 it('retains malformed raw output for local validation instead of making another model call',async()=>{completion.mockResolvedValue({id:'bad',choices:[{message:{content:'not JSON'}}]});const input=prepareReviewAnalysis(source),receipt=await executeSavedReviewAnalysis(input);expect(receipt.content).toBe('not JSON');expect(()=>parseSavedReviewAnalysis(input,receipt)).toThrow('not valid JSON');expect(completion).toHaveBeenCalledTimes(1)})
 it('rejects invented quotations in a saved result',()=>{expect(()=>parseSavedReviewAnalysis(prepareReviewAnalysis(source),{status:'received',content:JSON.stringify({...output,evidence:[{claim:'Claim',quote:'Not in the source.'}]})})).toThrow('quotations')})
 it('retains deterministic sensitive-topic policy despite a routine model classification',()=>{const input=prepareReviewAnalysis({...source,reviewText:'There was a gas leak.'});const result=parseSavedReviewAnalysis(input,{status:'received',content:JSON.stringify({...output,evidence:[{claim:'Reported safety issue',quote:input.source.reviewText}]})});expect(result.policy.requiresHumanReview).toBe(true);expect(result.policy.autoActionEligible).toBe(false);expect(result.policyClass).not.toBe('standard')})
 it('does not silently reinterpret a saved result using a different policy contract',()=>{expect(()=>parseSavedReviewAnalysis({...prepareReviewAnalysis(source),policyVersion:'older-contract'},{status:'received',content:JSON.stringify(output)})).toThrow('original parser')})
})
