import {describe,expect,it} from 'vitest'
import {publicationWriteSchema,safePublicationUrl} from './publication-contracts'
const id='11111111-1111-1111-1111-111111111111',hash='a'.repeat(64),base={propertyId:id,requestId:id,publicationId:id,expectedVersion:1,reason:'Reviewed destination evidence'}
describe('review publication evidence contracts',()=>{
 it('accepts public HTTPS evidence without credential or local-network links',()=>{expect(safePublicationUrl('https://example.invalid/review/123')).toBe(true);for(const value of ['javascript:alert(1)','http://example.com','https://user:password@example.com/','https://localhost/review','https://127.0.0.1/','https://[::1]/','https://example.internal/','https://example.com:54321/'])expect(safePublicationUrl(value)).toBe(false)})
 it('requires exact text confirmation, a real timestamp and public evidence',()=>{const valid={...base,action:'report_manual',confirmedExactText:true,publishedAt:'2026-09-18T12:00:00Z',evidenceUrl:'https://example.invalid/response'};expect(publicationWriteSchema.safeParse(valid).success).toBe(true);for(const change of [{confirmedExactText:false},{publishedAt:'yesterday'},{evidenceUrl:'http://127.0.0.1'},{verifiedByProvider:true}])expect(publicationWriteSchema.safeParse({...valid,...change}).success).toBe(false)})
 it('requires an explicit not-published confirmation and rejects implicit provider execution',()=>{expect(publicationWriteSchema.safeParse({...base,action:'cancel_manual',confirmedNotPublished:true}).success).toBe(true);expect(publicationWriteSchema.safeParse({...base,action:'cancel_manual'}).success).toBe(false);expect(publicationWriteSchema.safeParse({...base,action:'post'}).success).toBe(false)})
 it('normalizes the exact selected destination before saving its command identity',()=>{const parsed=publicationWriteSchema.parse({propertyId:id,requestId:id,action:'prepare_manual',responseId:id,expectedVersion:2,sourceVersion:1,contextHash:hash,contentHash:hash,targetHash:hash,destinationUrl:'https://EXAMPLE.invalid',replacePublished:false,reason:'Reviewed exact text'});expect(parsed).toMatchObject({destinationUrl:'https://example.invalid/'})})
})
