import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
const {completion}=vi.hoisted(()=>({completion:vi.fn()}))
vi.mock('openai',()=>({default:class{chat={completions:{create:completion}}}}))
import {prepareSavedReviewResponse,executeSavedReviewResponse,parseSavedReviewResponse,resetReviewAiClientForTests,type ReviewResponseInput} from './ai'
const source:ReviewResponseInput={reviewText:'The pool was clean.',rating:5,sentiment:'positive',topics:['amenities'],tone:'professional',reviewerName:'Fixture',grounding:{propertyName:'Fixture community',brandVoice:'Warm and clear',targetAudience:null,propertyPersonality:null,sourceLimitations:[],citedFacts:[{source:'properties.name',fact:'Community name: Fixture community'}]}}
const output={responseText:'Thank you for sharing your experience with our community.',usedFacts:['Community name: Fixture community'],refusalReason:null}
const receipt=(value:unknown)=>({status:'received' as const,content:JSON.stringify(value)})
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');resetReviewAiClientForTests();completion.mockResolvedValue({id:'response-fixture',choices:[{message:{content:JSON.stringify(output)}}],usage:{prompt_tokens:25,completion_tokens:35}})})
afterEach(()=>vi.unstubAllEnvs())
describe('saved response model contract',()=>{
 it('freezes exact source, grounded facts, prompt and model contract',()=>{const saved=prepareSavedReviewResponse(source);expect(saved.source).toEqual(source);expect(saved.userPrompt).toContain(source.reviewText);expect(saved.systemPrompt).toContain(source.grounding.citedFacts[0].fact);expect(saved).toMatchObject({promptVersion:'response-v3',policyVersion:'reviewflow-policy-v1',taxonomyVersion:'multifamily-v1'})})
 it('executes once without SDK retries and preserves the raw receipt',async()=>{const input=prepareSavedReviewResponse(source),saved=await executeSavedReviewResponse(input);expect(saved).toMatchObject({...receipt(output),providerId:'response-fixture',usage:{promptTokens:25,completionTokens:35}});expect(completion).toHaveBeenCalledTimes(1);expect(completion.mock.calls[0][0]).toMatchObject({model:input.model,messages:[{role:'system',content:input.systemPrompt},{role:'user',content:input.userPrompt}]});expect(completion.mock.calls[0][1]).toEqual({maxRetries:0,timeout:90_000})})
 it('does not invoke a paused or changed provider',async()=>{const input=prepareSavedReviewResponse(source);vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');await expect(executeSavedReviewResponse(input)).rejects.toThrow('paused');vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');vi.stubEnv('REVIEWFLOW_AI_BASE_URL','https://different.example.invalid/v1');await expect(executeSavedReviewResponse(input)).rejects.toThrow('configuration changed');expect(completion).not.toHaveBeenCalled()})
 it('never repairs malformed output with another model call',async()=>{completion.mockResolvedValue({id:'invalid',choices:[{message:{content:'not JSON'}}]});const input=prepareSavedReviewResponse(source),raw=await executeSavedReviewResponse(input);expect(raw.content).toBe('not JSON');expect(()=>parseSavedReviewResponse(input,raw)).toThrow('not valid JSON');expect(completion).toHaveBeenCalledTimes(1)})
 it('accepts only exact cited facts and the saved parser contract',()=>{const input=prepareSavedReviewResponse(source);expect(parseSavedReviewResponse(input,receipt(output))).toMatchObject({responseText:output.responseText,usedFacts:output.usedFacts,policyCheck:{passed:true}});expect(()=>parseSavedReviewResponse(input,receipt({...output,usedFacts:['24-hour pool']}))).toThrow('saved property facts');expect(()=>parseSavedReviewResponse({...input,promptVersion:'older'},receipt(output))).toThrow('original parser')})
 it('holds refusal, unknown fields and unsafe promises without creating a draft',()=>{const input=prepareSavedReviewResponse(source);for(const value of [{...output,refusalReason:'Insufficient facts'},{...output,automaticApproval:true},{...output,responseText:'We will refund all of your money and waive the fees.'}])expect(()=>parseSavedReviewResponse(input,receipt(value))).toThrow();expect(completion).not.toHaveBeenCalled()})
 it('does not parse an uncertain or oversized result as a usable response',async()=>{const input=prepareSavedReviewResponse(source);expect(()=>parseSavedReviewResponse(input,{status:'uncertain',errorCode:'timeout'})).toThrow('No confirmed');completion.mockResolvedValue({id:'large',choices:[{message:{content:'x'.repeat(200001)}}]});await expect(executeSavedReviewResponse(input)).rejects.toThrow('limit')})
})
