import {createServiceClient} from '@/utils/supabase/admin'
import {ReviewStoreError,reviewRpc} from './analysis-store'
import {prepareSavedReviewResponse,executeSavedReviewResponse,parseSavedReviewResponse,type SavedResponseInput,type SavedAnalysisReceipt,type ResponseTone} from './ai'
import {checkResponseText,evaluateReviewPolicy,POLICY_ENGINE_VERSION} from './policy'
import type {PolicyClass,RiskClass} from './taxonomy'
export type ResponseContext={review:{id:string;sourceVersion:number;reviewText:string;rating:number|null;reviewerName:string|null;platform:string;sentiment:string|null;topics:unknown;isUrgent:boolean};property:{id:string;orgId:string;name:string;brandVoice:string|null;targetAudience:string|null;websiteUrl:string|null};configuration:{propertyPersonality:string|null;defaultTone:string|null}|null;analysis:{id:string;sourceVersion:number;policyClass:PolicyClass;riskClass:RiskClass;confidence:number;isUrgent:boolean}|null}
export type ContextReceipt={state:'ready';context:ResponseContext;contextHash:string;responseSetHash:string;pendingResponses:Array<{id:string;version:number;status:string;contentHash:string;legacy:boolean}>}
export type DraftInput={reviewId:string;sourceVersion:number;contextHash:string;responseSetHash:string;replacePending:boolean;tone:ResponseTone;reason:string;responseText?:string}
const messages:Record<string,string>={stale_connection:'This source changed. Reload its current settings before saving.',source_identity_changed:'A saved source cannot change platforms. Add the other platform separately.',source_exists:'This platform already has a saved source. Reload and review that source.',already_disconnected:'This source is already disconnected. Reload its current status.',stale_configuration:'These preferences changed. Reload the current version before saving.',stale_publication:'This publication changed. Reload its current evidence.',publication_closed:'This publication already has a final outcome.',stale_destination:'The saved destination or prior publication changed. Reload before preparing.',approval_required:'A current manager approval is required before preparing publication.',busy:'Another publication needs an outcome before starting a new one.',stale_context:'The review or property facts changed. Reload and save a new draft before approval.',stale_responses:'The response list changed. Reload before replacing pending drafts.',replacement_review_required:'Review and confirm replacement of the pending drafts and approvals.',stale_response:'This response changed or was superseded. Reload its current version.',manager_required:'A manager or admin must review this response.',legacy_review_required:'This older response has no verified source version. Save a reviewed new draft first.',publication_review_required:'A publication attempt needs reconciliation before this response can change.',response_closed:'This response is no longer available for that decision.',stale_request:'The saved generation request changed. Reload its status.',request_conflict:'This request differs from its saved decision.',not_found:'This response or request is unavailable.',forbidden:'Your current access does not allow this decision.'}
export async function responseRpc(name:string,args:Record<string,unknown>,allowed=['saved','replayed']){const result=await reviewRpc(name,args);if(!allowed.includes(String(result.state)))throw new ReviewStoreError(messages[String(result.state)]||'This saved response needs review.',['forbidden','manager_required'].includes(String(result.state))?403:409);return result}
export async function responseContext(propertyId:string,actorId:string,reviewId:string){return await responseRpc('reviewflow_response_context',{p_property_id:propertyId,p_actor_id:actorId,p_review_id:reviewId},['ready']) as unknown as ContextReceipt}
export function responsePolicy(context:ResponseContext,text:string){return{origin:'console',policyVersion:POLICY_ENGINE_VERSION,policy:evaluateReviewPolicy({reviewText:context.review.reviewText,modelPolicyClass:context.analysis?.policyClass,modelConfidence:context.analysis?.confidence,riskClass:context.analysis?.riskClass}),textPolicy:checkResponseText(text)}}
export function responseModelInput(context:ResponseContext,tone:ResponseTone){const policy=responsePolicy(context,'').policy;const facts:Array<{source:string;fact:string}>=[];if(context.property.name)facts.push({source:'properties.name',fact:`Community name: ${context.property.name}`});if(context.property.websiteUrl)facts.push({source:'properties.website_url',fact:`Community website: ${context.property.websiteUrl}`});return{...prepareSavedReviewResponse({reviewText:context.review.reviewText,rating:context.review.rating,sentiment:context.review.sentiment,topics:Array.isArray(context.review.topics)?context.review.topics.filter((t):t is string=>typeof t==='string'):[],tone,reviewerName:context.review.reviewerName,grounding:{propertyName:context.property.name,brandVoice:context.property.brandVoice,targetAudience:context.property.targetAudience,propertyPersonality:context.configuration?.propertyPersonality??null,citedFacts:facts,sourceLimitations:[]},policyClass:policy.policyClass,isUrgent:context.review.isUrgent||context.analysis?.isUrgent}),context}}
export async function requestResponseGeneration(propertyId:string,actorId:string,requestId:string,input:DraftInput){const db=createServiceClient();const prior=await db.from('reviewflow_response_generation_requests').select('id').eq('id',requestId).eq('property_id',propertyId).maybeSingle();if(prior.error)throw new ReviewStoreError('Saved generation history is unavailable.');let modelInput:Record<string,unknown>={};if(!prior.data){const receipt=await responseContext(propertyId,actorId,input.reviewId);if(receipt.contextHash!==input.contextHash||receipt.responseSetHash!==input.responseSetHash)throw new ReviewStoreError('The saved review context changed. Reload before generating.',409);modelInput=responseModelInput(receipt.context,input.tone)}return responseRpc('begin_reviewflow_response_generation',{p_id:requestId,p_property_id:propertyId,p_actor_id:actorId,p_input:input,p_model_input:modelInput},['queued','busy','running','result_ready','completed','held','stopped'])}
export async function recoverResponseGeneration(id:string,propertyId:string,actorId:string){const {data:run,error}=await createServiceClient().from('reviewflow_response_generation_requests').select('*').eq('id',id).eq('property_id',propertyId).maybeSingle();if(error)throw new ReviewStoreError('Saved response result could not be loaded.');if(!run)throw new ReviewStoreError('Saved response request unavailable.',404);if(run.state==='completed')return{state:'replayed',responseId:run.response_id};if(run.state!=='result_ready')return{state:run.state};let result:Record<string,unknown>;try{const response=parseSavedReviewResponse(run.model_input as unknown as SavedResponseInput,run.raw_result as unknown as SavedAnalysisReceipt);result={resultHash:run.result_hash,response,policy:responsePolicy(run.source_snapshot as unknown as ResponseContext,response.responseText)}}catch{result={resultHash:run.result_hash,errorCode:'invalid_output'}}return responseRpc('apply_reviewflow_response_generation',{p_id:id,p_property_id:propertyId,p_actor_id:actorId,p_result:result},['saved','replayed','held','stopped'])}
export async function runResponseGeneration(id:string){if(process.env.OUTBOUND_DELIVERY_PAUSED==='true')return{state:'paused'};const claim=await reviewRpc('claim_reviewflow_response_generation',{p_id:id});if(claim.state!=='invoke_once')return claim;let receipt:SavedAnalysisReceipt;try{receipt=await executeSavedReviewResponse(claim.modelInput as SavedResponseInput)}catch{receipt={status:'uncertain',errorCode:'model_uncertain'}}const args={p_id:id,p_claim_token:claim.claimToken,p_result:receipt};let saved:Record<string,unknown>;try{saved=await responseRpc('record_reviewflow_response_generation_result',args)}catch{saved=await responseRpc('record_reviewflow_response_generation_result',args)}if(saved.requestState!=='result_ready')return saved;return recoverResponseGeneration(id,String(claim.propertyId),String(claim.actorId))}
