import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
const {from,rpc,prepare,execute,parse}=vi.hoisted(()=>({from:vi.fn(),rpc:vi.fn(),prepare:vi.fn(),execute:vi.fn(),parse:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({from,rpc})}))
vi.mock('./ai',async()=>({...await vi.importActual('./ai'),prepareSavedReviewResponse:prepare,executeSavedReviewResponse:execute,parseSavedReviewResponse:parse}))
import {requestResponseGeneration,runResponseGeneration,recoverResponseGeneration,responseModelInput,type ResponseContext} from './response-store'
const context:ResponseContext={review:{id:'review',sourceVersion:2,reviewText:'A clean pool.',rating:5,reviewerName:'Fixture',platform:'other',sentiment:'positive',topics:['amenities'],isUrgent:false},property:{id:'property',orgId:'org',name:'Fixture community',brandVoice:'Warm',targetAudience:null,websiteUrl:'https://example.invalid'},configuration:null,analysis:null}
const input={reviewId:'review',sourceVersion:2,contextHash:'context-hash',responseSetHash:'set-hash',tone:'professional' as const,replacePending:false,reason:'Reviewed source facts'},receipt={status:'received',content:'raw fixture'},response={responseText:'Thank you for sharing your experience.'}
function chain(data:unknown,error:unknown=null){const q={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data,error})};q.select.mockReturnValue(q);q.eq.mockReturnValue(q);return q}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');prepare.mockReturnValue({model:'fixture-model'});parse.mockReturnValue(response);execute.mockResolvedValue(receipt);from.mockReturnValue(chain(null));rpc.mockImplementation(async(name:string)=>({data:name==='reviewflow_response_context'?{state:'ready',context,contextHash:input.contextHash,responseSetHash:input.responseSetHash}:name==='begin_reviewflow_response_generation'?{state:'queued',requestId:'request'}:name==='claim_reviewflow_response_generation'?{state:'invoke_once',claimToken:'one-claim',modelInput:{model:'fixture-model'},propertyId:'property',actorId:'actor'}:name==='record_reviewflow_response_generation_result'?{state:'saved',requestState:'result_ready'}:{state:'saved',responseId:'draft'},error:null}))})
afterEach(()=>vi.unstubAllEnvs())
const savedRun=()=>chain({state:'result_ready',model_input:{},source_snapshot:context,raw_result:receipt,result_hash:'saved-hash'})
describe('durable response generation',()=>{
 it('saves frozen source and facts while paused without invoking a model',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect(await requestResponseGeneration('property','actor','request',input)).toMatchObject({state:'queued'});expect(prepare).toHaveBeenCalledWith(expect.objectContaining({reviewText:context.review.reviewText,grounding:expect.objectContaining({citedFacts:[{source:'properties.name',fact:'Community name: Fixture community'},{source:'properties.website_url',fact:'Community website: https://example.invalid'}]})}));expect(execute).not.toHaveBeenCalled()})
 it('replays a saved decision without rebuilding context',async()=>{from.mockReturnValue(chain({id:'request'}));await requestResponseGeneration('property','actor','request',input);expect(prepare).not.toHaveBeenCalled();expect(rpc).toHaveBeenCalledExactlyOnceWith('begin_reviewflow_response_generation',expect.objectContaining({p_model_input:{}}))})
 it('holds changed property facts or pending drafts before saving a model request',async()=>{await expect(requestResponseGeneration('property','actor','request',{...input,responseSetHash:'changed'})).rejects.toThrow('context changed');expect(prepare).not.toHaveBeenCalled();expect(rpc).toHaveBeenCalledTimes(1)})
 it('does not claim while paused or invoke after a lost claim reply',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect(await runResponseGeneration('request')).toEqual({state:'paused'});expect(rpc).not.toHaveBeenCalled();vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');rpc.mockResolvedValue({data:null,error:{message:'lost reply'}});await expect(runResponseGeneration('request')).rejects.toThrow('could not be confirmed');expect(execute).not.toHaveBeenCalled()})
 it('does not restart a running or stopped invocation',async()=>{for(const state of ['running','stopped']){rpc.mockResolvedValue({data:{state},error:null});expect(await runResponseGeneration('request')).toEqual({state})}expect(execute).not.toHaveBeenCalled()})
 it('retries only identical receipt persistence, then recovers the saved result',async()=>{let attempts=0;const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,...args:unknown[])=>name==='record_reviewflow_response_generation_result'&&attempts++===0?{data:null,error:{message:'lost reply'}}:original(name,...args));from.mockReturnValue(savedRun());expect(await runResponseGeneration('request')).toMatchObject({responseId:'draft'});expect(execute).toHaveBeenCalledTimes(1);const calls=rpc.mock.calls.filter(c=>c[0]==='record_reviewflow_response_generation_result');expect(calls).toHaveLength(2);expect(calls[0][1]).toEqual(calls[1][1]);expect(rpc).toHaveBeenCalledWith('apply_reviewflow_response_generation',expect.objectContaining({p_result:expect.objectContaining({resultHash:'saved-hash',response})}))})
 it('retains ambiguous execution or stopped late results without applying drafts',async()=>{execute.mockRejectedValue(new Error('timeout'));const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,...args:unknown[])=>name==='record_reviewflow_response_generation_result'?{data:{state:'saved',requestState:'held'},error:null}:original(name,...args));await runResponseGeneration('request');expect(execute).toHaveBeenCalledTimes(1);expect(rpc).toHaveBeenCalledWith('record_reviewflow_response_generation_result',expect.objectContaining({p_result:{status:'uncertain',errorCode:'model_uncertain'}}));expect(parse).not.toHaveBeenCalled();expect(from).not.toHaveBeenCalled()})
 it('recovers stored output while paused and holds invalid output without another model',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');from.mockReturnValue(savedRun());parse.mockImplementation(()=>{throw new Error('unsupported fact')});await recoverResponseGeneration('request','property','actor');expect(rpc).toHaveBeenCalledWith('apply_reviewflow_response_generation',expect.objectContaining({p_result:{resultHash:'saved-hash',errorCode:'invalid_output'}}));expect(execute).not.toHaveBeenCalled()})
 it('escalates source policy when preparing the frozen model input',()=>{responseModelInput({...context,review:{...context.review,reviewText:'There was a gas leak.'}},'empathetic');expect(prepare).toHaveBeenCalledWith(expect.objectContaining({policyClass:'safety',tone:'empathetic'}))})
})
