import {describe,expect,it,vi} from 'vitest'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Database} from '@/types/supabase'
import {assertSiteForgeTestimonialPermissions} from './testimonial-reuse'
const id='11111111-1111-1111-1111-111111111111',property='33333333-3333-3333-3333-333333333333',source={id,reviewer_name:'Resident',review_text:'Exact approved review',rating:5,platform:'other',review_date:'2026-09-18T00:00:00Z'},permission={id,reviewer_name_snapshot:source.reviewer_name,review_text_snapshot:source.review_text,rating_snapshot:5,platform_snapshot:'other',review_date_snapshot:'2026-09-18T00:00:00.000+00:00'}
const artifact=(reviews:unknown[]=[source])=>({pages:[{sections:[{acfBlock:'acf/testimonials',content:{source:'reviewflow',reviews}}]}]})
function client(data:unknown[],error:unknown=null){const q={in:vi.fn().mockResolvedValue({data,error})},rpc=vi.fn().mockReturnValue(q);return{db:{rpc} as unknown as SupabaseClient<Database>,rpc,q}}
describe('saved website release testimonial permission fence',()=>{
 it('leaves artifacts without managed testimonials untouched',async()=>{const f=client([]);await assertSiteForgeTestimonialPermissions(f.db,property,{pages:[]});expect(f.rpc).not.toHaveBeenCalled()})
 it('checks website-scoped eligibility and all exact approved fields',async()=>{const f=client([permission]);await assertSiteForgeTestimonialPermissions(f.db,property,artifact());expect(f.rpc).toHaveBeenCalledWith('eligible_reviewflow_testimonials',{p_property_id:property,p_channel:'website'});expect(f.q.in).toHaveBeenCalledWith('id',[id])})
 it('holds a saved artifact after revocation, expiry, source changes or absent consent',async()=>{await expect(assertSiteForgeTestimonialPermissions(client([]).db,property,artifact())).rejects.toThrow('permission expired')})
 it('rejects edited text, attribution, rating, platform and date even with a valid permission ID',async()=>{for(const change of [{review_text:'Edited excerpt'},{reviewer_name:'Different resident'},{rating:4},{platform:'google'},{review_date:'2026-09-17T00:00:00Z'},{review_date:'invalid'}])await expect(assertSiteForgeTestimonialPermissions(client([permission]).db,property,artifact([{...source,...change}]))).rejects.toThrow('exact content')})
 it('surfaces failed permission reads instead of approving a partial result',async()=>{await expect(assertSiteForgeTestimonialPermissions(client([],{message:'private database detail'}).db,property,artifact())).rejects.toThrow('could not be confirmed')})
 it('checks every use, including modified duplicate IDs and unqualified source metadata',async()=>{await expect(assertSiteForgeTestimonialPermissions(client([permission]).db,property,artifact([source,{...source,review_text:'Changed repeated use'}]))).rejects.toThrow('exact content');await expect(assertSiteForgeTestimonialPermissions(client([permission]).db,property,artifact([{...source,id:'bad'}]))).rejects.toThrow('permission identity');await expect(assertSiteForgeTestimonialPermissions(client([permission]).db,property,{pages:[{sections:[{acfBlock:'acf/testimonials',content:{reviews:[source]}}]}]})).rejects.toThrow('missing its saved')})
})
