import {beforeEach,describe,expect,it,vi} from 'vitest'
import type {NextRequest} from 'next/server'
const auth=vi.fn(),access=vi.fn(),from=vi.fn(),rpc=vi.fn(),upload=vi.fn(),recover=vi.fn(),form=vi.fn()
vi.mock('@/utils/supabase/server',()=>({createClient:async()=>({auth:{getUser:auth}})}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({from})}))
vi.mock('@/utils/services/auth-guard',()=>({validatePropertyAccess:access}))
vi.mock('@/utils/forgestudio/asset-library-store',()=>({assetLibraryRpc:rpc,uploadLibraryAsset:upload,recoverLibraryUpload:recover,boundedAssetForm:form}))
const property='11111111-1111-4111-8111-111111111111',asset='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333'
let rows:unknown[],error:unknown,chain:Record<string,ReturnType<typeof vi.fn>>
const request=(body:unknown,method='PATCH')=>new Request('http://localhost/api/forgestudio/assets',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}) as NextRequest
const patch={requestId,propertyId:property,assetId:asset,revision:2,action:'save',patch:{folder:'Community',is_favorite:true}}
beforeEach(()=>{vi.clearAllMocks();rows=[];error=null;chain={};for(const key of ['select','eq','is','not','order','limit','or','lt','ilike'])chain[key]=vi.fn(()=>chain);chain.then=vi.fn((resolve:(r:unknown)=>unknown)=>resolve({data:rows,error}));from.mockReturnValue(chain);auth.mockResolvedValue({data:{user:{id:'actual-user'}},error:null});access.mockResolvedValue({authorized:true});rpc.mockResolvedValue({state:'saved',asset:{id:asset}});upload.mockResolvedValue({state:'saved',asset:{id:asset}});recover.mockResolvedValue({state:'saved',asset:{id:asset}});const f=new FormData();f.set('propertyId',property);form.mockResolvedValue(f)})
describe('asset library API',()=>{
 it('requires sign-in before library reads or writes',async()=>{auth.mockResolvedValue({data:{user:null},error:null});const r=await import('./route');expect((await r.GET(new Request('http://localhost/api/forgestudio/assets?propertyId='+property) as NextRequest)).status).toBe(401);expect((await r.PATCH(request(patch))).status).toBe(401);expect(from).not.toHaveBeenCalled();expect(rpc).not.toHaveBeenCalled()})
 it('forbids writes outside the actual property',async()=>{access.mockResolvedValue({authorized:false});expect((await(await import('./route')).PATCH(request(patch))).status).toBe(403);expect(rpc).not.toHaveBeenCalled()})
 it('saves real folder and favorite values under the actual actor and exact revision',async()=>{expect((await(await import('./route')).PATCH(request(patch))).status).toBe(200);expect(rpc).toHaveBeenCalledWith('manage_forgestudio_asset',{p_id:requestId,p_property_id:property,p_actor_id:'actual-user',p_payload:{assetId:asset,revision:2,action:'save',patch:patch.patch}})})
 it.each([{...patch,revision:undefined},{...patch,requestId:undefined},{...patch,patch:{file_url:'https://malicious.invalid'}},{...patch,actorId:'forged'}])('rejects missing identity and unsupported direct mutation %j',async body=>{expect((await(await import('./route')).PATCH(request(body))).status).toBe(400);expect(rpc).not.toHaveBeenCalled()})
 it('uses server pagination and filters across the library',async()=>{rows=Array.from({length:31},(_,i)=>({id:`11111111-1111-4111-8111-${String(i).padStart(12,'0')}`,created_at:'2026-09-17T00:00:00Z'}));const response=await(await import('./route')).GET(new Request(`http://localhost/api/forgestudio/assets?propertyId=${property}&folder=Community&favorites=true&usable=true`) as NextRequest);const data=await response.json();expect(response.status).toBe(200);expect(data.assets).toHaveLength(30);expect(data.nextCursor).toBeTruthy();expect(chain.eq).toHaveBeenCalledWith('folder','Community');expect(chain.eq).toHaveBeenCalledWith('is_favorite',true);expect(chain.eq).toHaveBeenCalledWith('approval_status','approved');expect(chain.is).toHaveBeenCalledWith('archived_at',null)})
 it('rejects an invalid page cursor instead of hiding older assets',async()=>{expect((await(await import('./route')).GET(new Request(`http://localhost/api/forgestudio/assets?propertyId=${property}&cursor=invalid`) as NextRequest)).status).toBe(400)})
 it('read failure is distinct from an empty library',async()=>{error={message:'unavailable'};expect((await(await import('./route')).GET(new Request(`http://localhost/api/forgestudio/assets?propertyId=${property}`) as NextRequest)).status).toBe(503)})
 it('does not retain the old arbitrary URL registration or hard-delete bypass',async()=>{const r=await import('./route');expect((await r.POST(request({propertyId:property,fileUrl:'https://example.invalid/x'},'POST'))).status).toBe(400);expect((await r.DELETE()).status).toBe(409);expect(upload).not.toHaveBeenCalled()})
 it('requires property authorization before storing multipart bytes',async()=>{access.mockResolvedValue({authorized:false});const r=await(await import('./route')).POST(new Request('http://localhost/api/forgestudio/assets',{method:'POST',headers:{'Content-Type':'multipart/form-data; boundary=fixture'},body:'fixture'}) as NextRequest);expect(r.status).toBe(403);expect(upload).not.toHaveBeenCalled()})
 it('recovers stored bytes with an attributed explicit decision',async()=>{const body={requestId,propertyId:property,uploadId:asset,action:'keep_separate',reason:'Keep the stored file and review the original separately'};expect((await(await import('./route')).PATCH(request(body))).status).toBe(200);expect(recover).toHaveBeenCalledWith({...body,actorId:'actual-user'})})
 it('pending uploads are scoped to the requesting operator',async()=>{await(await import('./route')).GET(new Request(`http://localhost/api/forgestudio/assets?mode=uploads&propertyId=${property}`) as NextRequest);expect(chain.eq).toHaveBeenCalledWith('actor_id','actual-user');expect(chain.eq).toHaveBeenCalledWith('state','prepared')})
})
