BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create temp table st(k text primary key,v jsonb);
insert into public.organizations(id,name)values('ee660000-0000-4000-8000-000000000001','Account recovery SQL fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at,encrypted_password,raw_user_meta_data)select ('ee660000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','recovery-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp(),'SYNTHETIC-ORIGINAL-PROVIDER-HASH','{"private":"PRIVATE-AUTH-FIXTURE"}'from generate_series(101,108)n;
insert into public.profiles(id,org_id,role)select ('ee660000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,case when n=108 then null else'ee660000-0000-4000-8000-000000000001'::uuid end,case when n=102 then'admin'else'viewer'end from generate_series(101,108)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into auth.sessions(id,user_id,created_at,updated_at,aal)select ('ee660000-0000-4000-8000-'||lpad((n+100)::text,12,'0'))::uuid,('ee660000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,clock_timestamp(),clock_timestamp(),'aal1'from generate_series(101,108)n;
create function pg_temp.actor(n int default 101)returns uuid language sql as $$select('ee660000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.read_credentials(b jsonb default'{}',n int default 101)returns jsonb language sql as $$select public.read_account_credentials(pg_temp.actor(n),pg_temp.actor(n+100),'aal1',b)$$;
create function pg_temp.claim(i int,n int default 101)returns jsonb language sql as $$select public.claim_account_credential(pg_temp.actor(i),pg_temp.actor(n),pg_temp.actor(n+100),'aal1',pg_temp.read_credentials('{}',n)->>'sourceHash')$$;
create function pg_temp.advance(i int,claim uuid,n int default 101,verified boolean default true,cleanup text default'confirmed')returns jsonb language sql as $$select public.advance_account_credential(pg_temp.actor(i),pg_temp.actor(n),claim,'aal1',verified,cleanup)$$;
create function pg_temp.review(i int,op text default'check',n int default 101)returns jsonb language sql as $$select public.review_account_credential(pg_temp.actor(i),pg_temp.actor(n),pg_temp.actor(n+100),op)$$;

create function pg_temp.reset(i int,n int default 101,aal text default 'aal1')returns jsonb language sql as $$select public.claim_account_recovery(pg_temp.actor(i),pg_temp.actor(n),pg_temp.actor(n+100),aal,pg_temp.read_credentials('{}',n)->>'sourceHash')$$;
select pg_temp.check_it(pg_temp.reset(301)->>'state'='recovery_required','ordinary session is not a recovery grant');
update auth.users set raw_user_meta_data=raw_user_meta_data||'{"recovery":true,"amr":[{"method":"recovery"}]}'where id=pg_temp.actor();
select pg_temp.check_it(pg_temp.reset(301)->>'state'='recovery_required','user metadata cannot create recovery authority');
insert into auth.mfa_amr_claims(id,session_id,authentication_method,created_at,updated_at)select gen_random_uuid(),pg_temp.actor(n+100),'recovery',statement_timestamp()-interval'1 minute',statement_timestamp()from generate_series(101,108)n;
select pg_temp.check_it(pg_temp.read_credentials()->'canRecover'='true','actual recovery authentication exposes controls');
select pg_temp.check_it(public.account_recovery_grant(pg_temp.actor(102),pg_temp.actor(201))is null,'grant belongs to actual session owner');
insert into st values('hash',to_jsonb(pg_temp.read_credentials()->>'sourceHash')),('claim',pg_temp.reset(301));
select pg_temp.check_it((select v->>'state'='claimed'and v->>'claimId'is not null from st where k='claim'),'one saved reset claim');
select pg_temp.check_it((select purpose='recovery'and state='changing'and cleanup_outcome is null from public.account_credential_requests where id=pg_temp.actor(301)),'reset purpose retained without invented current-password verification');
select pg_temp.check_it(not(public.claim_account_recovery(pg_temp.actor(301),pg_temp.actor(),pg_temp.actor(201),'aal1',(select v#>>'{}'from st where k='hash'))?'claimId'),'replay does not return execution capability');
select pg_temp.check_it(pg_temp.reset(302)->>'state'='pending_request','another reset cannot run concurrently');
set constraints auth.recorded_account_credential_commit immediate;
update auth.users set encrypted_password='SYNTHETIC-RESET-HASH',raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='claim'))where id=pg_temp.actor();
select pg_temp.check_it(pg_temp.review(301)->>'status'='confirmed','real Auth password write and reset evidence commit atomically');
select pg_temp.check_it(pg_temp.reset(302)->>'state'='recovery_consumed','one successful reset per recovery session');
select pg_temp.check_it(pg_temp.read_credentials()->'canRecover'='false','used session no longer presents reset controls');
select pg_temp.check_it(public.finish_account_credential(pg_temp.actor(301),pg_temp.actor(),(select(v->>'claimId')::uuid from st where k='claim'),'uncertain')->>'status'='confirmed','lost reply recovers confirmed native reset');
select pg_temp.check_it(pg_temp.review(301,'check',102)->>'state'='not_found','another owner cannot read reset receipt');
insert into st values('expired',pg_temp.reset(303,102));
update auth.mfa_amr_claims set created_at=statement_timestamp()-interval'16 minutes'where session_id=pg_temp.actor(202);
select pg_temp.throws($q$update auth.users set encrypted_password='SYNTHETIC-EXPIRED',raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='expired'))where id=pg_temp.actor(102)$q$,'grant expiry before actual provider commit rolls back password');
select pg_temp.check_it((select encrypted_password='SYNTHETIC-ORIGINAL-PROVIDER-HASH'from auth.users where id=pg_temp.actor(102)),'expired attempt leaves original credential intact');
select pg_temp.check_it(pg_temp.review(303,'cancel',102)->>'status'='cancelled','expired pending reset remains cancellable');
select pg_temp.check_it(pg_temp.reset(304,102)->>'state'='recovery_required','expired grant cannot claim again');
insert into st values('cancelled',pg_temp.reset(305,103));
select pg_temp.check_it(pg_temp.review(305,'cancel',103)->>'status'='cancelled','explicit cancellation saved');
select pg_temp.throws($q$update auth.users set encrypted_password='SYNTHETIC-LATE',raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='cancelled'))where id=pg_temp.actor(103)$q$,'late cancelled reset cannot commit');
insert into st values('revoked',pg_temp.reset(306,104));
delete from auth.sessions where id=pg_temp.actor(204);
select pg_temp.throws($q$update auth.users set encrypted_password='SYNTHETIC-REVOKED',raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='revoked'))where id=pg_temp.actor(104)$q$,'revoked recovery session cannot commit');
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at)values(pg_temp.actor(801),pg_temp.actor(105),'totp','verified',clock_timestamp(),clock_timestamp());
select pg_temp.check_it(pg_temp.reset(307,105)->>'state'='mfa_required','email recovery cannot bypass second factor');
select pg_temp.check_it(pg_temp.reset(307,105,'aal2')->>'state'='claimed','verified second factor permits recovery claim');
select pg_temp.check_it(not has_function_privilege('authenticated','public.account_recovery_grant(uuid,uuid)','EXECUTE')and not has_function_privilege('anon','public.claim_account_recovery(uuid,uuid,uuid,text,text)','EXECUTE'),'browser cannot forge native recovery context');
select pg_temp.check_it(not has_table_privilege('service_role','auth.mfa_amr_claims','SELECT'),'no broad grant to private authentication methods');
grant select,insert,update on assertion_count,st to service_role;
set local role service_role;
select pg_temp.check_it(pg_temp.reset(308,106)->>'state'='claimed','service uses narrow recovery projection');
reset role;
select pg_temp.throws($q$update public.account_credential_requests set purpose='change'where id=pg_temp.actor(308)$q$,'saved request purpose cannot change');
select pg_temp.check_it(not exists(select 1 from public.shared_action_events where org_id='ee660000-0000-4000-8000-000000000001'and(training_eligible or result::text like'%SYNTHETIC%')),'reset history excludes secrets and remains training ineligible');
select n as passed_assertions from assertion_count;
ROLLBACK;
