BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create temp table st(k text primary key,v jsonb);
insert into public.organizations(id,name)values('ee650000-0000-4000-8000-000000000001','Account credential SQL fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at,encrypted_password,raw_user_meta_data)select ('ee650000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','credential-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp(),'SYNTHETIC-ORIGINAL-PROVIDER-HASH','{"private":"PRIVATE-AUTH-FIXTURE"}'from generate_series(101,108)n;
insert into public.profiles(id,org_id,role)select ('ee650000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,case when n=108 then null else'ee650000-0000-4000-8000-000000000001'::uuid end,case when n=102 then'admin'else'viewer'end from generate_series(101,108)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into auth.sessions(id,user_id,created_at,updated_at,aal)select ('ee650000-0000-4000-8000-'||lpad((n+100)::text,12,'0'))::uuid,('ee650000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,clock_timestamp(),clock_timestamp(),'aal1'from generate_series(101,108)n;
create function pg_temp.actor(n int default 101)returns uuid language sql as $$select('ee650000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.read_credentials(b jsonb default'{}',n int default 101)returns jsonb language sql as $$select public.read_account_credentials(pg_temp.actor(n),pg_temp.actor(n+100),'aal1',b)$$;
create function pg_temp.claim(i int,n int default 101)returns jsonb language sql as $$select public.claim_account_credential(pg_temp.actor(i),pg_temp.actor(n),pg_temp.actor(n+100),'aal1',pg_temp.read_credentials('{}',n)->>'sourceHash')$$;
create function pg_temp.advance(i int,claim uuid,n int default 101,verified boolean default true,cleanup text default'confirmed')returns jsonb language sql as $$select public.advance_account_credential(pg_temp.actor(i),pg_temp.actor(n),claim,'aal1',verified,cleanup)$$;
create function pg_temp.review(i int,op text default'check',n int default 101)returns jsonb language sql as $$select public.review_account_credential(pg_temp.actor(i),pg_temp.actor(n),pg_temp.actor(n+100),op)$$;
select pg_temp.check_it(pg_temp.read_credentials()->>'state'='ready','current account can read safe credential source');
select pg_temp.check_it(pg_temp.read_credentials('{}',108)->>'state'='ready','unassigned account owns credential history');
select pg_temp.check_it(pg_temp.read_credentials()::text not like'%PRIVATE%'and pg_temp.read_credentials()::text not like'%PROVIDER-HASH%','safe source excludes credential and auth private content');
insert into st values('hash',to_jsonb(pg_temp.read_credentials()->>'sourceHash')),('claim',pg_temp.claim(301));
select pg_temp.check_it((select v->>'state'='claimed'and v->>'claimId'is not null from st where k='claim'),'one private verification claim');
select pg_temp.check_it(public.claim_account_credential(pg_temp.actor(301),pg_temp.actor(),pg_temp.actor(201),'aal1',(select v#>>'{}'from st where k='hash'))->>'state'='replayed','same safe request replays without passwords');
select pg_temp.check_it(not(public.claim_account_credential(pg_temp.actor(301),pg_temp.actor(),pg_temp.actor(201),'aal1',(select v#>>'{}'from st where k='hash'))?'claimId'),'replay never discloses private execution claim');
select pg_temp.check_it(pg_temp.claim(302)->>'state'='pending_request','concurrent password changes held');
select pg_temp.check_it(pg_temp.advance(301,gen_random_uuid())->>'state'='not_found','wrong claim cannot advance');
select pg_temp.check_it(pg_temp.advance(301,(select(v->>'claimId')::uuid from st where k='claim'))->>'state'='execute','verified password and confirmed temporary-session cleanup permit one update');
-- Metadata alone, even the exact private marker in this privileged fixture, cannot confirm.
update auth.users set raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='claim'))where id=pg_temp.actor();
set constraints auth.recorded_account_credential_commit immediate;
select pg_temp.check_it(pg_temp.review(301)->>'status'='changing','a user-editable marker alone never proves a password changed');
update auth.users set raw_user_meta_data=raw_user_meta_data-'p11_credential_request'where id=pg_temp.actor();
set constraints auth.recorded_account_credential_commit deferred;
update auth.users set encrypted_password='SYNTHETIC-CHANGED-PROVIDER-HASH'where id=pg_temp.actor();
select pg_temp.check_it(pg_temp.review(301)->>'status'='changing','password storage remains unconfirmed before the Auth transaction finishes');
update auth.users set raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='claim'))where id=pg_temp.actor();
set constraints auth.recorded_account_credential_commit immediate;
select pg_temp.check_it(pg_temp.review(301)->>'status'='confirmed','separate password and marker writes confirm atomically at Auth commit');
select pg_temp.check_it(public.finish_account_credential(pg_temp.actor(301),pg_temp.actor(),(select(v->>'claimId')::uuid from st where k='claim'),'uncertain')->>'status'='confirmed','lost provider response cannot erase committed proof');
select pg_temp.check_it(pg_temp.review(301,'cancel')->>'status'='confirmed','cancel after commit recovers instead of undoing a password');
select pg_temp.check_it(pg_temp.read_credentials(jsonb_build_object('kind','detail','requestId',pg_temp.actor(301)),102)->>'state'='not_found','organization administrator cannot read another account credential receipt');
select pg_temp.check_it(pg_temp.review(305,'cancel')->>'status'='cancelled'and pg_temp.claim(305)->>'status'='cancelled','unused cancellation fences delayed initial verification');
insert into st values('cancelClaim',pg_temp.claim(306,103));
select pg_temp.check_it(pg_temp.advance(306,(select(v->>'claimId')::uuid from st where k='cancelClaim'),103)->>'state'='execute','second fixture reaches provider boundary');
select pg_temp.throws($q$update auth.users set encrypted_password='SYNTHETIC-UNCORRELATED-HASH'where id=pg_temp.actor(103)$q$,'uncorrelated provider write is held while recorded execution is outstanding');
select pg_temp.check_it(pg_temp.review(306,'cancel',103)->>'status'='cancelled','uncommitted execution is explicitly cancelled');
select pg_temp.throws($q$update auth.users set encrypted_password='SYNTHETIC-LATE-HASH',raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='cancelClaim'))where id=pg_temp.actor(103)$q$,'late provider password commit rolls back after cancellation');
select pg_temp.check_it((select encrypted_password='SYNTHETIC-ORIGINAL-PROVIDER-HASH'from auth.users where id=pg_temp.actor(103)),'late cancellation leaves original credential intact');
insert into st values('failClaim',pg_temp.claim(307,104));
select pg_temp.check_it(pg_temp.advance(307,(select(v->>'claimId')::uuid from st where k='failClaim'),104)->>'state'='execute','recording rollback fixture reaches provider boundary');
create function pg_temp.fail_event()returns trigger language plpgsql as $$begin if new.actor_id=pg_temp.actor(104)and new.kind='confirmed'then raise exception 'Synthetic credential recording failure';end if;return new;end$$;
create trigger credential_fixture_evidence before insert on public.account_credential_events for each row execute function pg_temp.fail_event();
select pg_temp.throws($q$update auth.users set encrypted_password='SYNTHETIC-UNRECORDED-HASH',raw_user_meta_data=raw_user_meta_data||jsonb_build_object('p11_credential_request',(select v->>'claimId'from st where k='failClaim'))where id=pg_temp.actor(104)$q$,'failed evidence rolls back provider credential change');
drop trigger credential_fixture_evidence on public.account_credential_events;
select pg_temp.check_it((select encrypted_password='SYNTHETIC-ORIGINAL-PROVIDER-HASH'from auth.users where id=pg_temp.actor(104))and pg_temp.review(307,'check',104)->>'status'='changing','no partial credential or success after failed recording');
insert into st values('wrongClaim',pg_temp.claim(308,105));
select pg_temp.check_it(pg_temp.advance(308,(select(v->>'claimId')::uuid from st where k='wrongClaim'),105,false,'not_created')->>'status'='verification_failed','wrong current password never reaches mutation');
insert into st values('cleanupClaim',pg_temp.claim(309,105));
select pg_temp.check_it(pg_temp.advance(309,(select(v->>'claimId')::uuid from st where k='cleanupClaim'),105,true,'unconfirmed')->>'status'='verification_failed','unconfirmed verification-session cleanup prevents credential mutation');
insert into st values('revokedClaim',pg_temp.claim(310,106));
delete from auth.sessions where id=pg_temp.actor(206);
select pg_temp.check_it(pg_temp.advance(310,(select(v->>'claimId')::uuid from st where k='revokedClaim'),106)->>'status'='rejected','revoked original session cannot advance after password verification');
update auth.users set encrypted_password='SYNTHETIC-OUTSIDE-RECORD',raw_user_meta_data=raw_user_meta_data||'{"p11_credential_request":"------------------------------------"}'where id=pg_temp.actor(107);
select pg_temp.check_it(exists(select 1 from public.account_credential_events where actor_id=pg_temp.actor(107)and request_id is null and kind='provider_record_changed'),'outside credential record change is an observation with no invented actor intent');
select pg_temp.throws($q$delete from public.account_credential_events where actor_id=pg_temp.actor()$q$,'credential evidence is immutable');
select pg_temp.check_it(not exists(select 1 from public.account_credential_events where actor_id=pg_temp.actor()and kind like'%SYNTHETIC%')and not exists(select 1 from public.shared_action_events where org_id='ee650000-0000-4000-8000-000000000001'and(training_eligible or request::text like'%claimId%'or result::text like'%PRIVATE%'or result::text like'%PASSWORD%')),'history excludes password bytes hashes claim markers and private provider payloads');
select pg_temp.check_it(not has_table_privilege('authenticated','public.account_credential_requests','SELECT')and not has_function_privilege('authenticated','public.claim_account_credential(uuid,uuid,uuid,text,text)','EXECUTE'),'private credentials cannot be accessed directly by browser roles');
select pg_temp.check_it(not has_table_privilege('service_role','auth.users','SELECT'),'no broad auth access granted to service role');
grant select,insert,update on assertion_count,st to service_role;
set local role service_role;
select pg_temp.check_it(pg_temp.read_credentials()->>'state'='ready','application role reads safe credential projection');
select pg_temp.check_it(pg_temp.review(311,'cancel')->>'state'='saved','application role can cancel its own unused request');
reset role;
update public.profiles set org_id=null where id=pg_temp.actor();
select pg_temp.check_it(pg_temp.read_credentials(jsonb_build_object('kind','detail','requestId',pg_temp.actor(301)))->>'status'='confirmed','credential receipt survives organization removal');
do $$declare n int;begin for n in 1001..2025 loop perform pg_temp.review(n,'cancel');end loop;end$$;
insert into st values('history',pg_temp.read_credentials('{"kind":"history"}'));
select pg_temp.check_it((select(v->>'total')::int>1000 from st where k='history'),'native credential event history exceeds REST row limit');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_credentials(jsonb_build_object('kind','history','offset',1020,'expectedHash',(select v->>'pageHash'from st where k='history')))->'items')>0,'last credential history page is reachable');
select pg_temp.check_it(pg_temp.review(3001,'cancel')->>'state'='saved','another history event appends');
select pg_temp.check_it(pg_temp.read_credentials(jsonb_build_object('kind','history','offset',20,'expectedHash',(select v->>'pageHash'from st where k='history')))->>'state'='history_changed','new event holds stale history pagination');
insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at)values(pg_temp.actor(801),pg_temp.actor(108),'totp','verified',clock_timestamp(),clock_timestamp());
select pg_temp.check_it(pg_temp.read_credentials('{}',108)->'canChange'='false','verified second factor holds low assurance password controls');
select pg_temp.check_it(pg_temp.claim(4001,108)->>'state'='mfa_required','native credential claim requires current second factor assurance');
delete from auth.mfa_factors where id=pg_temp.actor(801);
insert into st values('cancelVerify',pg_temp.claim(4001,108));
select pg_temp.check_it(pg_temp.review(4001,'cancel',108)->>'status'='cancelled','verification in progress can be cancelled');
select pg_temp.check_it(pg_temp.advance(4001,(select(v->>'claimId')::uuid from st where k='cancelVerify'),108)->>'status'='cancelled','late verification cannot start a cancelled password update');
do $$declare i int;c jsonb;begin for i in 4002..4005 loop c:=pg_temp.claim(i,108);perform pg_temp.check_it(c->>'state'='claimed','bounded verification attempt acquired');perform pg_temp.advance(i,(c->>'claimId')::uuid,108,false,'not_created');end loop;end$$;
select pg_temp.check_it(pg_temp.claim(4006,108)->>'state'='rate_limited','repeated verification attempts have a native per-account limit');
select n as passed_assertions from assertion_count;
ROLLBACK;
