BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee720000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'BI alert SQL fixture'),(pg_temp.i(2),'BI alert other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','bi-alert-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,104)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,104)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'BI alert SQL property'),(pg_temp.i(202),pg_temp.i(2),'BI alert other property');
insert into public.fact_marketing_performance(property_id,date,channel_id,source_account_id,currency_code,campaign_id,impressions,clicks,spend,conversions)select pg_temp.i(201),'2026-09-01'::date+n,'google_ads','1111111111','USD','fixture',100,10,1.01,0.125 from generate_series(0,29)n;
create function pg_temp.filters()returns jsonb language sql immutable as $$select'{"startDate":"2026-09-01","endDate":"2026-09-30","channel":null,"account":null,"compare":false}'::jsonb$$;
create function pg_temp.hash()returns text language sql as $$select public.bi_report_source(pg_temp.i(101),pg_temp.i(201),pg_temp.filters())->>'sourceHash'$$;
create function pg_temp.input()returns jsonb language sql as $$select jsonb_build_object('operation','prepare','filters',pg_temp.filters(),'sourceHash',pg_temp.hash())$$;
create function pg_temp.payload()returns jsonb language sql as $$select jsonb_build_object('definitionVersion','bi-alert-v1','sourceHash',pg_temp.hash(),'definitions','{"thresholds":{"spend":50,"clicks":40,"impressions":40,"conversions":60},"minimumDailyDates":7}'::jsonb,'coverage','{"dailyEligible":true,"periodEligible":false,"currentDays":30,"requestedDays":30,"priorDays":0,"currencyKnown":true}'::jsonb,'alerts',(select jsonb_agg(jsonb_build_object('key','daily:clicks:'||('2026-09-01'::date+n)::text,'metric','clicks','kind','daily','date','2026-09-01'::date+n,'value',10,'baseline',5,'percent',100,'threshold',40))from generate_series(0,29)n))$$;
create function pg_temp.command(n int,input jsonb,a int default 101,payload jsonb default null)returns jsonb language sql as $$select public.decide_bi_alert(pg_temp.i(n),pg_temp.i(a),pg_temp.i(201),input,payload)$$;
create function pg_temp.mark(n int,op text,items jsonb,note text default'Fixture explanation',s int default 301)returns jsonb language sql as $$select pg_temp.command(n,jsonb_build_object('operation',op,'setId',pg_temp.i(s),'items',items,'note',note))$$;
create function pg_temp.read_it(kind text default'list',n int default null,a int default 101,offset_n int default 0,bucket text default'all')returns jsonb language sql as $$select public.read_bi_alerts(pg_temp.i(a),pg_temp.i(201),jsonb_build_object('kind',kind,'id',pg_temp.i(n),'offset',offset_n,'bucket',bucket))$$;
set local role service_role;
select pg_temp.check_it(public.bi_alert_payload_valid(pg_temp.payload()),'bounded fixed-rule fixture valid');
select pg_temp.check_it(not public.bi_alert_payload_valid(jsonb_set(pg_temp.payload(),'{alerts,0,percent}','99')),'incorrect percentage rejected');
select pg_temp.check_it(not public.bi_alert_payload_valid(jsonb_set(pg_temp.payload(),'{alerts,0,baseline}','0')),'zero denominator rejected');
select pg_temp.check_it(not public.bi_alert_payload_valid(jsonb_set(pg_temp.payload(),'{alerts,0,threshold}','20')),'different rule threshold rejected');
select pg_temp.check_it(not public.bi_alert_payload_valid(jsonb_set(pg_temp.payload(),'{alerts,0,date}','"2026-02-30"')),'invalid catalog date rejected');
select pg_temp.check_it(not public.bi_alert_payload_valid(jsonb_set(pg_temp.payload(),'{coverage,dailyEligible}','false')),'ineligible daily rule cannot claim findings');
select pg_temp.check_it(not public.bi_alert_payload_valid(jsonb_set(pg_temp.payload(),'{alerts,1}',pg_temp.payload()#>'{alerts,0}')),'duplicate catalog key rejected');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input())->>'state'='needs_derivation','preparation requests server derivation without a phantom result');
select pg_temp.check_it(pg_temp.read_it()->>'count'='0','probe did not create a review');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input(),101,pg_temp.payload())->>'status'='ready','review retains derived evidence');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input())->>'state'='replayed','lost preparation does not need recapture');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input()||'{"sourceHash":"changed"}')->>'state'='request_conflict','request content immutable');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input(),104)->>'state'='not_found','another admin cannot claim request');
select pg_temp.check_it(pg_temp.command(302,pg_temp.input(),104)->>'setId'=pg_temp.i(301)::text,'another manager opens the same retained source');
select pg_temp.check_it(pg_temp.read_it()->>'count'='1','same source never duplicates alert catalog');
select pg_temp.check_it(pg_temp.command(303,pg_temp.input(),102)->>'state'='forbidden','viewer cannot change reviews');
select pg_temp.check_it(pg_temp.command(303,pg_temp.input(),103)->>'state'='forbidden','other org cannot prepare');
select pg_temp.check_it(pg_temp.read_it('items',301,102)->>'count'='30','viewer can inspect retained review');
select pg_temp.check_it(pg_temp.read_it('items',301,103)->>'state'='forbidden','other org cannot inspect');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it('items',301)->'items')=20,'first alert page bounded');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it('items',301,101,20)->'items')=10,'last alert page reachable');
select pg_temp.check_it(not(pg_temp.read_it('items',301)->'set'?'source'),'private raw fact source omitted from read');
select pg_temp.check_it(pg_temp.mark(303,'review','[{"key":"daily:clicks:2026-09-01","revision":1},{"key":"daily:clicks:2026-09-02","revision":9}]')->>'state'='alert_changed','stale selection held atomically');
select pg_temp.check_it(pg_temp.read_it('items',301)#>>'{counts,reviewed}'='0','no partial review after stale second item');
select pg_temp.check_it(pg_temp.mark(303,'review','[{"key":"daily:clicks:2026-09-01","revision":1},{"key":"daily:clicks:2026-09-02","revision":1}]')->>'count'='2','exact selection reviewed');
select pg_temp.check_it(pg_temp.mark(303,'review','[{"key":"daily:clicks:2026-09-01","revision":1},{"key":"daily:clicks:2026-09-02","revision":1}]')->>'state'='replayed','lost decision never repeats updates');
select pg_temp.check_it(pg_temp.read_it('items',301,101,0,'reviewed')->>'count'='2','review bucket complete');
select pg_temp.check_it(pg_temp.read_it('history',301)#>>'{items,0,before_state,0,state}'='open','prior state retained');
select pg_temp.check_it(pg_temp.read_it('history',301)#>>'{items,0,after_state,0,note}'='Fixture explanation','review explanation retained');
select pg_temp.check_it(pg_temp.mark(304,'dismiss','[{"key":"daily:clicks:2026-09-01","revision":2}]','Planned campaign')->>'status'='dismissed','dismissal separate from review');
select pg_temp.check_it(pg_temp.mark(305,'restore','[{"key":"daily:clicks:2026-09-01","revision":3}]','Needs another look')->>'status'='open','restoration retains earlier decisions');
select pg_temp.check_it(pg_temp.read_it('items',301,101,0,'open')#>>'{items,0,revision}'='4','item revision increments across lifecycle');
select pg_temp.check_it(pg_temp.mark(306,'review','[{"key":"daily:clicks:2026-09-03","revision":1},{"key":"daily:clicks:2026-09-03","revision":1}]')->>'state'='invalid_input','duplicate selection rejected');
select pg_temp.check_it(pg_temp.mark(306,'review','[]')->>'state'='invalid_input','empty selection rejected');
select pg_temp.check_it(pg_temp.mark(306,'review','[{"key":"unknown","revision":1}]')->>'state'='not_found','unknown evidence cannot be reviewed');
select pg_temp.check_it(pg_temp.command(306,'{"operation":"cancel_request"}')->>'status'='cancelled_request','unused request tombstone saved');
select pg_temp.check_it(pg_temp.mark(306,'review','[{"key":"daily:clicks:2026-09-03","revision":1}]')->>'status'='cancelled_request','late review fenced');
select pg_temp.check_it(pg_temp.command(303,'{"operation":"cancel_request"}')->>'status'='reviewed','cancel cannot erase a completed review');
select pg_temp.check_it(pg_temp.read_it('command',303,104)->>'state'='not_found','request recovery actor scoped');
insert into st values('items',pg_temp.read_it('items',301)),('source',(select source from public.bi_alert_sets where id=pg_temp.i(301)));
select pg_temp.mark(307,'dismiss','[{"key":"daily:clicks:2026-09-03","revision":1}]');
select pg_temp.check_it(public.read_bi_alerts(pg_temp.i(101),pg_temp.i(201),jsonb_build_object('kind','items','id',pg_temp.i(301),'expectedHash',(select v->>'hash'from st where k='items')))->>'state'='history_changed','item page detects another decision');
update public.fact_marketing_performance set spend=99 where property_id=pg_temp.i(201);
select pg_temp.check_it((select source=(select v from st where k='source')from public.bi_alert_sets where id=pg_temp.i(301)),'later import never rewrites alert source');
select pg_temp.check_it(pg_temp.command(308,pg_temp.input(),101,pg_temp.payload())->>'setId'=pg_temp.i(308)::text,'changed source starts an independent review');
select pg_temp.check_it(pg_temp.read_it('items',308)#>>'{counts,open}'='30','dismissals never carry to another source revision');
select pg_temp.check_it((select count(*)from public.bi_alert_commands where property_id=pg_temp.i(201))=(select count(*)from public.shared_action_events where property_id=pg_temp.i(201)and action like'bi.alert.%'),'one atomic shared action per native decision');
select pg_temp.check_it((select bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)),'review decisions are not training rewards');
select set_config('p11.bi_alert_scope','',true);
select pg_temp.throws(format('update public.bi_alert_items set state=%L where set_id=%L','reviewed',pg_temp.i(301)),'service cannot bypass decision history');
select pg_temp.throws(format('delete from public.bi_alert_sets where id=%L',pg_temp.i(301)),'live source retention cannot be bypassed');
select set_config('p11.bi_alert_scope',pg_temp.i(201)::text,true);
select pg_temp.throws(format('update public.bi_alert_sets set derived=%L where id=%L','{}',pg_temp.i(301)),'retained detection immutable');
select pg_temp.throws(format('update public.bi_alert_commands set result=%L where id=%L','{}',pg_temp.i(301)),'review commands immutable');
reset role;
select pg_temp.check_it(not has_table_privilege('authenticated','public.bi_alert_sets','SELECT'),'private evidence service-only');
select pg_temp.check_it(not has_function_privilege('authenticated','public.decide_bi_alert(uuid,uuid,uuid,jsonb,jsonb)','EXECUTE'),'native decisions service-only');
select set_config('p11.team_scope',pg_temp.i(1)::text,true);update public.profiles set role=null where id=pg_temp.i(101);
select pg_temp.check_it(pg_temp.command(301,(select input from public.bi_alert_sets where id=pg_temp.i(301)))->>'state'='forbidden','missing role does not authorize replay');
update public.profiles set org_id=null,role='viewer'where id=pg_temp.i(101);
select pg_temp.check_it(pg_temp.read_it('items',301)->>'state'='forbidden','removed member cannot inspect saved evidence');
select n as assertions_passed from assertion_count;
ROLLBACK;
