BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee820000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role,authenticated;
insert into public.organizations(id,name)values(pg_temp.i(1),'BI data SQL fixture'),(pg_temp.i(2),'BI data other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','bi-data-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,103)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,103)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'BI data SQL property'),(pg_temp.i(202),pg_temp.i(2),'BI data other property');
insert into public.fact_marketing_performance(id,date,property_id,channel_id,source_account_id,currency_code,campaign_id,campaign_name,impressions,clicks,spend,conversions,raw_source)select pg_temp.i(500+n),'2026-09-01',pg_temp.i(201),'google_ads','1234567890','USD','campaign-'||n,'Private original campaign '||n,100,10,12.5,0.125,'original-provider'from generate_series(1,31)n;
insert into public.fact_marketing_extended(id,property_id,channel_id,campaign_name,report_type,dimension_key,dimension_value,metrics,raw_source,date_range_start,date_range_end)values(pg_temp.i(601),pg_temp.i(201),'google_ads','Historical dimension','devices','device','Mobile','{"spend":8}','legacy-original','2026-09-01','2026-09-30');
create function pg_temp.read_it(r int default null,k text default'current',off int default 0,actor int default 101,h text default null)returns jsonb language sql as $$select public.read_bi_data_review(pg_temp.i(actor),pg_temp.i(201),'2026-09-01','2026-09-30',pg_temp.i(r),null,k,off,h)$$;
create function pg_temp.save_it(n int,actor int default 101)returns jsonb language plpgsql as $$declare h text;begin h:=pg_temp.read_it(null,'current',0,actor)->>'hash';return public.decide_bi_data_review(pg_temp.i(n),pg_temp.i(actor),pg_temp.i(201),jsonb_build_object('operation','save','startDate','2026-09-01','endDate','2026-09-30','sourceHash',h));end$$;
create function pg_temp.decide(n int,r int,row_n int,op text default'exclude',actor int default 101,k text default'daily')returns jsonb language sql as $$select public.decide_bi_data_review(pg_temp.i(n),pg_temp.i(actor),pg_temp.i(201),jsonb_build_object('operation',op,'reviewId',pg_temp.i(r),'rowId',pg_temp.i(row_n),'kind',k,'reason','Private exact source review reason'))$$;
set local role service_role;
select pg_temp.check_it(pg_temp.read_it()->>'count'='32','complete daily plus undated dimension inventory');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it()->'items')=25,'first page bounded');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it(null,'current',25)->'items')=7,'all source rows reachable');
select pg_temp.check_it(pg_temp.read_it(null,'current',0,103)->>'state'='forbidden','cross tenant source denied');
select pg_temp.check_it(pg_temp.save_it(301)->>'status'='saved_review','exact review retained');
select pg_temp.check_it(pg_temp.save_it(301)->>'status'='saved_review','same save identity recovered');
select pg_temp.check_it((select count(*)=1 from public.bi_data_reviews where property_id=pg_temp.i(201)),'replayed save stays single');
select pg_temp.check_it(pg_temp.decide(401,301,501,'exclude',102)->>'state'='forbidden','viewer cannot exclude');
select pg_temp.check_it(pg_temp.decide(401,301,501)->>'status'='excluded','manager exclusion saved');
select pg_temp.check_it((select spend=12.5 and raw_source='original-provider'from public.fact_marketing_performance where id=pg_temp.i(501)),'original values retained unchanged');
select pg_temp.check_it(public.read_marketing_facts(pg_temp.i(201),'2026-09-01','2026-09-30')->>'row_count'='30','report reader omits excluded row');
select pg_temp.check_it(pg_temp.decide(401,301,501)->>'status'='excluded','lost exclusion reply replays exactly');
select pg_temp.check_it(pg_temp.decide(402,301,501,'restore')->>'state'='source_changed','historical row state cannot restore without refresh');
select pg_temp.check_it(pg_temp.save_it(302)->>'status'='saved_review','new review captures exclusion');
select pg_temp.check_it(pg_temp.read_it(301,'rows')->'items'->0->>'excluded'='false','historical source remains unchanged');
select pg_temp.throws(format('update public.fact_marketing_performance set spend=99 where id=%L',pg_temp.i(501)),'worker cannot silently overwrite excluded source');
select pg_temp.throws(format('delete from public.fact_marketing_performance where id=%L',pg_temp.i(501)),'excluded original cannot be deleted');
select pg_temp.check_it(pg_temp.decide(403,302,501,'restore')->>'status'='restored','explicit restoration retains source');
select pg_temp.check_it(public.read_marketing_facts(pg_temp.i(201),'2026-09-01','2026-09-30')->>'row_count'='31','restoration returns row to reporting');
update public.fact_marketing_performance set spend=14 where id=pg_temp.i(502);
select pg_temp.check_it(pg_temp.decide(404,301,502)->>'state'='source_changed','changed provider values fence old decision');
select pg_temp.check_it(public.decide_bi_data_review(pg_temp.i(405),pg_temp.i(101),pg_temp.i(201),'{"operation":"cancel"}')->>'status'='cancelled','unused request closed');
select pg_temp.check_it(pg_temp.decide(405,301,503)->>'status'='cancelled','late mutation cannot pass cancellation');
select pg_temp.check_it(pg_temp.decide(406,301,601,'exclude',101,'dimension')->>'status'='excluded','legacy dimension excluded without rewriting unknown account identity');
-- Exact original download and truthful browser observation.
insert into st values('export',public.decide_bi_data_review(pg_temp.i(407),pg_temp.i(101),pg_temp.i(201),jsonb_build_object('operation','export','reviewId',pg_temp.i(301))));
select pg_temp.check_it((select v->'artifact'->'source'->>'count'='32'from st where k='export'),'download includes complete retained snapshot');
select pg_temp.check_it(public.decide_bi_data_review(pg_temp.i(408),pg_temp.i(101),pg_temp.i(201),jsonb_build_object('operation','report','reviewId',pg_temp.i(301),'exportId',pg_temp.i(407),'artifactHash',(select v->>'artifactHash'from st where k='export'),'outcome','initiated'))->>'status'='reported','browser download outcome retained separately');
select pg_temp.check_it((select evidence='browser_observed'and phase='observed'from public.shared_action_events where id=pg_temp.i(408)),'browser result never claimed as destination receipt');
select pg_temp.check_it(public.read_bi_data_review(pg_temp.i(102),pg_temp.i(201),p_command_id=>pg_temp.i(407))->>'state'='not_found','other actor cannot recover private in-flight download');
select pg_temp.check_it((select bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)),'all history training ineligible');
select pg_temp.check_it(not exists(select 1 from public.shared_action_events where property_id=pg_temp.i(201)and(request::text||coalesce(before_state::text,'')||coalesce(after_state::text,'')||result::text)like'%Private%'),'shared history excludes originals and private reasons');
-- Failure to record means no exclusion commits.
reset role;
create function pg_temp.fail_data_action()returns trigger language plpgsql as $$begin if new.id=pg_temp.i(409)then raise exception 'injected action recording failure';end if;return new;end$$;
create trigger injected_data_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_data_action();
set local role service_role;
select pg_temp.throws('select pg_temp.decide(409,301,504)','action failure rolls back exclusion');
select pg_temp.check_it(not exists(select 1 from public.bi_data_row_state where row_id=pg_temp.i(504)),'row inclusion unchanged after action failure');
select pg_temp.check_it(not exists(select 1 from public.bi_data_commands where id=pg_temp.i(409)),'failed command not falsely successful');
select set_config('p11.bi_data_scope','',true);
select pg_temp.throws(format('update public.bi_data_row_state set excluded=true where row_id=%L',pg_temp.i(501)),'unrecorded exclusion rejected');
select set_config('p11.bi_data_scope',pg_temp.i(201)::text,true);
select pg_temp.throws(format('update public.bi_data_reviews set source=%L where id=%L','{}',pg_temp.i(301)),'review source immutable even in active scope');
select pg_temp.throws(format('update public.bi_data_commands set input=%L where id=%L','{}',pg_temp.i(401)),'decision reason immutable');
select pg_temp.throws(format('delete from public.bi_data_reviews where id=%L',pg_temp.i(301)),'private source cannot be deleted while property exists');
-- Authenticated report paths and access policies read the same exclusion state.
select set_config('request.jwt.claim.sub',pg_temp.i(101)::text,true);
set local role authenticated;
select pg_temp.check_it(jsonb_array_length(public.query_marketing_analytics(pg_temp.i(201),'2026-09-01','2026-09-30'))=1,'authenticated aggregate reader still works');
select pg_temp.check_it((select count(*)=2 from public.bi_data_row_state where property_id=pg_temp.i(201)),'scoped row decisions visible to member');
select pg_temp.throws('select * from public.bi_data_reviews','private snapshot not directly readable');
select pg_temp.throws(format('select public.decide_bi_data_review(%L,%L,%L,%L)',pg_temp.i(999),pg_temp.i(101),pg_temp.i(201),'{"operation":"cancel"}'),'authenticated cannot impersonate native actor');
select set_config('request.jwt.claim.sub',pg_temp.i(103)::text,true);
select pg_temp.check_it((select count(*)=0 from public.bi_data_row_state where property_id=pg_temp.i(201)),'other tenant cannot see exclusion states');
set local role service_role;
select pg_temp.save_it(700+n)from generate_series(1,28)n;
select pg_temp.check_it(pg_temp.read_it(null,'history',25)->>'count'='30','full saved review history');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it(null,'history',25)->'items')=5,'historical continuation complete');
select pg_temp.check_it(pg_temp.read_it(null,'current',25,101,repeat('0',64))->>'state'='source_changed','stale continuation cannot mix source versions');
select pg_temp.check_it(public.decide_bi_data_review(pg_temp.i(800),pg_temp.i(101),pg_temp.i(201),jsonb_build_object('operation','save','startDate','2026-09-01','endDate','2026-09-30','sourceHash',repeat('0',64)))->>'state'='source_changed','stale review capture held');

select pg_temp.check_it(pg_temp.read_it(null,'decisions')->>'count'='36','complete private decision history');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it(null,'decisions',25)->'items')=11,'every decision history page reachable');
select pg_temp.check_it(not exists(select 1 from jsonb_array_elements(pg_temp.read_it(null,'decisions')->'items')x where x->'result'?'artifact'),'history summaries do not duplicate large exact artifacts');
-- Native replacement integration: retain unknown history; explicitly exclude before a verified import.
reset role;
insert into public.properties(id,org_id,name)values(pg_temp.i(203),pg_temp.i(1),'BI data replacement fixture');
do $$declare definition text;begin
 select pg_get_constraintdef(oid)into definition from pg_constraint where conrelid='public.fact_marketing_performance'::regclass and conname='fact_marketing_verified_identity';
 alter table public.fact_marketing_performance drop constraint fact_marketing_verified_identity;
 insert into public.fact_marketing_performance(id,date,property_id,channel_id,campaign_id,campaign_name,impressions,clicks,spend,conversions,raw_source)values(pg_temp.i(901),'2026-09-01',pg_temp.i(203),'google','legacy-id','Unowned original',100,10,12,0.125,'mcp');
 execute 'alter table public.fact_marketing_performance add constraint fact_marketing_verified_identity '||definition;
end$$;
set local role service_role;
insert into st values('legacy',public.read_bi_data_review(pg_temp.i(101),pg_temp.i(203),'2026-09-01','2026-09-30'));
select pg_temp.check_it(public.decide_bi_data_review(pg_temp.i(902),pg_temp.i(101),pg_temp.i(203),jsonb_build_object('operation','save','startDate','2026-09-01','endDate','2026-09-30','sourceHash',(select v->>'hash'from st where k='legacy')))->>'status'='saved_review','unknown original saved without invented identity');
select pg_temp.check_it(public.decide_bi_data_review(pg_temp.i(903),pg_temp.i(101),pg_temp.i(203),jsonb_build_object('operation','exclude','reviewId',pg_temp.i(902),'rowId',pg_temp.i(901),'kind','daily','reason','Historical unknown account replaced by exact provider CSV'))->>'status'='excluded','old invalid row excluded without rewriting constraints or original');
insert into st values('daily-preview',jsonb_build_object('kind','daily','platform','google_ads','sourceAccountId','1234567890','currencyCode','USD','reportType','time_series','parserVersion','native-fixture-v1','dateRange',jsonb_build_object('start','2026-09-01','end','2026-09-01'),'rows',jsonb_build_array(jsonb_build_object('date','2026-09-01','campaign_id','legacy-id','campaign_name','Verified campaign','impressions',100,'clicks',10,'spend',20,'conversions',0.125))));
select pg_temp.check_it(public.prepare_bi_csv(pg_temp.i(904),pg_temp.i(101),pg_temp.i(203),'{"filename":"original.csv","csvContent":"exact original","platform":"google_ads","sourceAccountId":"1234567890","currencyCode":"USD","campaignName":"Verified campaign"}',(select v from st where k='daily-preview'))->>'status'='preview','reviewed replacement preview includes excluded original');
select pg_temp.check_it(public.decide_bi_csv(pg_temp.i(905),pg_temp.i(101),pg_temp.i(203),pg_temp.i(904),(select jsonb_build_object('operation','apply','previewHash',preview_hash,'targetHash',target_hash,'reason','Confirmed actual provider identity')from public.bi_csv_imports where id=pg_temp.i(904)))->>'status'='applied','excluded unowned legacy no longer blocks real account import');
select pg_temp.check_it(public.read_marketing_facts(pg_temp.i(203),'2026-09-01','2026-09-30')->>'row_count'='1','only replacement totals are reported');
select pg_temp.check_it((select source_account_id is null and spend=12 and raw_source='mcp'from public.fact_marketing_performance where id=pg_temp.i(901)),'unowned original never attributed or overwritten');
insert into st values('replaced',public.read_bi_data_review(pg_temp.i(101),pg_temp.i(203),'2026-09-01','2026-09-30'));
select public.decide_bi_data_review(pg_temp.i(906),pg_temp.i(101),pg_temp.i(203),jsonb_build_object('operation','save','startDate','2026-09-01','endDate','2026-09-30','sourceHash',(select v->>'hash'from st where k='replaced')));
select pg_temp.check_it(public.decide_bi_data_review(pg_temp.i(907),pg_temp.i(101),pg_temp.i(203),jsonb_build_object('operation','restore','reviewId',pg_temp.i(906),'rowId',pg_temp.i(901),'kind','daily','reason','Attempting to restore old overlapping export'))->>'state'='overlap_requires_review','restoring overlapping old data cannot double count replacement');
-- Excluded known account identities must first be restored, never silently reactivated by imports.
select pg_temp.check_it(public.decide_bi_data_review(pg_temp.i(908),pg_temp.i(101),pg_temp.i(203),jsonb_build_object('operation','exclude','reviewId',pg_temp.i(906),'rowId',(select id from public.fact_marketing_performance where property_id=pg_temp.i(203)and source_account_id='1234567890'),'kind','daily','reason','Verified row excluded for review'))->>'status'='excluded','known account excluded explicitly');
select public.prepare_bi_csv(pg_temp.i(909),pg_temp.i(101),pg_temp.i(203),'{"filename":"original.csv","csvContent":"exact original","platform":"google_ads","sourceAccountId":"1234567890","currencyCode":"USD","campaignName":"Verified campaign"}',(select v from st where k='daily-preview'));
select pg_temp.check_it(public.decide_bi_csv(pg_temp.i(910),pg_temp.i(101),pg_temp.i(203),pg_temp.i(909),(select jsonb_build_object('operation','apply','previewHash',preview_hash,'targetHash',target_hash,'reason','Try to overwrite excluded known source')from public.bi_csv_imports where id=pg_temp.i(909)))->>'state'='excluded_review_required','CSV exact excluded identity held');

set constraints all immediate;
select n as assertions from assertion_count;
ROLLBACK;
