BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee700000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'BI goals SQL fixture'),(pg_temp.i(2),'BI goals other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','bi-goal-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,104)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,104)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'BI goals SQL property'),(pg_temp.i(202),pg_temp.i(2),'BI goals other property');
create function pg_temp.input(g int default 401)returns jsonb language sql immutable as $$select jsonb_build_object('operation','save','goalId',pg_temp.i(g),'expectedRevision',0,'metric','conversions','period','quarterly','target',100.125,'direction','at_least','threshold',80)$$;
create function pg_temp.command(n int,input jsonb,a int default 101)returns jsonb language sql as $$select public.decide_bi_goal(pg_temp.i(n),pg_temp.i(a),pg_temp.i(201),input)$$;
create function pg_temp.read_it(kind text default'goals',n int default null,a int default 101,offset_n int default 0)returns jsonb language sql as $$select public.read_bi_goals(pg_temp.i(a),pg_temp.i(201),jsonb_build_object('kind',kind,'id',pg_temp.i(n),'offset',offset_n))$$;
set local role service_role;
select pg_temp.check_it(pg_temp.command(301,pg_temp.input())->>'status'='active','quarterly goal retained');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input())->>'state'='replayed','exact lost reply replay');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input()||'{"target":200}')->>'state'='request_conflict','changed input cannot reuse request');
select pg_temp.check_it(pg_temp.command(301,pg_temp.input(),104)->>'state'='not_found','other admin cannot claim request');
select pg_temp.check_it(pg_temp.command(302,pg_temp.input(402),102)->>'state'='forbidden','viewer cannot save');
select pg_temp.check_it(pg_temp.command(302,pg_temp.input(402),103)->>'state'='forbidden','cross org cannot save');
select pg_temp.check_it(pg_temp.read_it('goals',null,102)->>'count'='1','viewer reads scoped goals');
select pg_temp.check_it(pg_temp.read_it('history',null,103)->>'state'='forbidden','cross org history denied');
select pg_temp.check_it(pg_temp.read_it('command',301,104)->>'state'='not_found','request recovery actor scoped');
select pg_temp.check_it(pg_temp.command(302,pg_temp.input(402))->>'state'='duplicate_goal','same metric period never silently overwrites');
select pg_temp.check_it(pg_temp.command(302,pg_temp.input()||'{"target":200}')->>'state'='goal_changed','stale revision denied');
select pg_temp.check_it(pg_temp.command(302,pg_temp.input()||'{"target":200,"expectedRevision":1}')->>'revision'='2','reviewed edit increments');
select pg_temp.check_it((select before_state->>'target_value'='100.125'and after_state->>'target_value'='200'from public.bi_control_commands where id=pg_temp.i(302)),'full before and after retained');
select pg_temp.check_it(pg_temp.command(303,jsonb_build_object('operation','archive','goalId',pg_temp.i(401),'expectedRevision',2))->>'status'='archived','archive retains goal');
select pg_temp.check_it(pg_temp.command(304,pg_temp.input()||'{"expectedRevision":3}')->>'state'='archived_goal','archived goal requires restore');
select pg_temp.check_it(pg_temp.command(304,pg_temp.input(402))->>'state'='duplicate_goal','archived duplicate remains discoverable');
select pg_temp.check_it(pg_temp.command(304,jsonb_build_object('operation','restore','goalId',pg_temp.i(401),'expectedRevision',3))->>'revision'='4','restore increments revision');
select pg_temp.check_it(pg_temp.command(305,'{"operation":"cancel_request"}')->>'status'='cancelled_request','unused request tombstone');
select pg_temp.check_it(pg_temp.command(305,pg_temp.input(402)||'{"period":"yearly"}')->>'status'='cancelled_request','late save fenced');
select pg_temp.check_it(pg_temp.command(301,'{"operation":"cancel_request"}')->>'status'='active','cancel cannot erase completed save');
select pg_temp.check_it(pg_temp.command(306,pg_temp.input(402)||'{"period":"yearly"}')->>'status'='active','yearly supported');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","target":0}')->>'state'='invalid_input','zero target denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","target":-1}')->>'state'='invalid_input','negative target denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","target":"1"}')->>'state'='invalid_input','string target denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","metric":"clicks","target":1.5}')->>'state'='invalid_input','fractional clicks denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","metric":"ctr","target":101}')->>'state'='invalid_input','CTR over 100 denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","direction":null}')->>'state'='invalid_input','null direction denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","threshold":80.5}')->>'state'='invalid_input','fractional threshold denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","unexpected":true}')->>'state'='invalid_input','extra fields denied');
select pg_temp.check_it(pg_temp.command(307,pg_temp.input(403)||'{"period":"daily","direction":"at_most"}')->>'status'='active','daily explicit inverse supported');
insert into st values('page',pg_temp.read_it());
select pg_temp.check_it(pg_temp.command(308,pg_temp.input(404)||'{"period":"weekly"}')->>'status'='active','weekly supported');
select pg_temp.check_it(public.read_bi_goals(pg_temp.i(101),pg_temp.i(201),jsonb_build_object('expectedHash',(select v->>'hash'from st where k='page')))->>'state'='history_changed','changed page fence');
select pg_temp.check_it(pg_temp.command(309,pg_temp.input(405)||'{"period":"monthly"}')->>'status'='active','monthly supported');
select pg_temp.check_it((select count(*)=9 from public.bi_control_commands where property_id=pg_temp.i(201)),'exact native decision count');
select pg_temp.check_it((select count(*)=9 and bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)and action like'bi.goal.%'),'one immutable training-ineligible action per decision');
select set_config('p11.bi_control_scope','',true);
select pg_temp.throws(format('update public.metric_goals set target_value=4 where id=%L',pg_temp.i(401)),'service cannot silently edit');
select pg_temp.throws(format('delete from public.metric_goals where id=%L',pg_temp.i(401)),'service cannot erase live goals');
select set_config('p11.bi_control_scope',pg_temp.i(201)::text,true);
select pg_temp.throws(format('update public.bi_control_commands set result=%L where id=%L','{}',pg_temp.i(301)),'history remains immutable');
reset role;
select pg_temp.check_it(not has_table_privilege('authenticated','public.metric_goals','INSERT,UPDATE,DELETE'),'legacy authenticated mutations closed');
select pg_temp.check_it(not has_table_privilege('authenticated','public.bi_control_commands','SELECT'),'private command table not exposed');
select pg_temp.check_it(not has_function_privilege('authenticated','public.decide_bi_goal(uuid,uuid,uuid,jsonb)','EXECUTE'),'service-only decisions');
select set_config('p11.team_scope',pg_temp.i(1)::text,true);update public.profiles set role='viewer'where id=pg_temp.i(101);
select pg_temp.check_it(pg_temp.command(301,pg_temp.input())->>'state'='forbidden','role revoked before replay');
select pg_temp.check_it(pg_temp.read_it('command',301)->>'status'='active','revoked manager still reads own historical result');
select n as assertions_passed from assertion_count;
ROLLBACK;
