BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee690000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'BI schedule SQL fixture'),(pg_temp.i(2),'BI schedule other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','bi-schedule-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,104)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,104)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'BI schedule SQL property'),(pg_temp.i(202),pg_temp.i(2),'BI schedule other property');
insert into public.fact_marketing_performance(property_id,date,channel_id,source_account_id,currency_code,campaign_id,impressions,clicks,spend,conversions)values(pg_temp.i(201),(clock_timestamp()at time zone'UTC')::date-1,'google_ads','1111111111','USD','daily',100,10,1.01,0.125);
create function pg_temp.config()returns jsonb language sql immutable as $$select '{"name":"Daily fixture","frequency":"daily","weekday":null,"monthday":null,"hour":9,"window":"last_7_days","comparison":true,"campaigns":true,"recipients":["one@fixture.invalid","two@fixture.invalid"]}'::jsonb$$;
create function pg_temp.command(n int,input jsonb,a int default 101)returns jsonb language sql as $$select public.decide_bi_schedule(pg_temp.i(n),pg_temp.i(a),pg_temp.i(201),input)$$;
create function pg_temp.create_it(n int,a int default 101)returns jsonb language sql as $$select pg_temp.command(n,jsonb_build_object('operation','create','config',pg_temp.config()),a)$$;
create function pg_temp.change_it(n int,s int,op text,rev int)returns jsonb language sql as $$select pg_temp.command(n,jsonb_build_object('operation',op,'scheduleId',pg_temp.i(s),'expectedRevision',rev))$$;
create function pg_temp.read_it(kind text default'list',n int default null,a int default 101,offset_n int default 0)returns jsonb language sql as $$select public.read_bi_schedules(pg_temp.i(a),pg_temp.i(201),jsonb_build_object('kind',kind,'id',pg_temp.i(n),'offset',offset_n))$$;
create function pg_temp.due(n int)returns void language plpgsql as $$begin perform set_config('p11.bi_schedule_scope',pg_temp.i(201)::text,true);update public.bi_schedules set next_run_at=clock_timestamp()-interval'1 minute'where id=pg_temp.i(n);end$$;
create function pg_temp.delivery(n int,idx int default 0)returns uuid language sql stable as $$select id from public.bi_schedule_deliveries where run_id=pg_temp.i(n)order by recipient offset idx limit 1$$;
set local role service_role;
select pg_temp.check_it(public.bi_schedule_config(pg_temp.config()),'valid config');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"frequency":null}'),'null frequency rejected');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"recipients":[null]}'),'null recipient rejected');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"recipients":["UPPER@fixture.invalid"]}'),'non-normalized recipient rejected');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"recipients":["one@fixture.invalid","one@fixture.invalid"]}'),'duplicate recipients rejected');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"hour":"9"}'),'string hour rejected');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"weekday":2}'),'unused weekday rejected');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"name":"line\nbreak"}'),'header injection rejected');
select pg_temp.check_it(not public.bi_schedule_config(pg_temp.config()||'{"report_type":"leads"}'),'unsupported report kind rejected');
select pg_temp.check_it(public.bi_schedule_next(pg_temp.config(),'2026-02-28T09:00:00Z')='2026-03-01T09:00:00Z','daily strictly future UTC');
select pg_temp.check_it(public.bi_schedule_next(pg_temp.config()||'{"frequency":"weekly","weekday":1}','2026-09-21T09:00:00Z')='2026-09-28T09:00:00Z','weekly equal instant advances full week');
select pg_temp.check_it(public.bi_schedule_next(pg_temp.config()||'{"frequency":"monthly","monthday":28}','2026-01-29T09:00:00Z')='2026-02-28T09:00:00Z','monthly shortest month respected');
select pg_temp.check_it(public.bi_schedule_filters(pg_temp.config(),'2026-03-01T00:00:00Z')->>'startDate'='2026-02-22','seven completed dates at UTC midnight');
select pg_temp.check_it(public.bi_schedule_filters(pg_temp.config()||'{"frequency":"weekly","weekday":1,"window":"previous_period"}','2026-09-23T09:00:00Z')->>'startDate'='2026-09-14','weekly previous full Monday to Sunday');
select pg_temp.check_it(public.bi_schedule_filters(pg_temp.config()||'{"frequency":"monthly","monthday":1,"window":"previous_period"}','2024-03-01T09:00:00Z')->>'endDate'='2024-02-29','leap year month period');
select pg_temp.check_it(public.bi_schedule_filters(pg_temp.config()||'{"window":"month_to_date"}','2026-03-01T09:00:00Z')is null,'first of month has no completed dates');
select pg_temp.check_it(pg_temp.create_it(301)->>'status'='paused','create starts paused');
select pg_temp.check_it(pg_temp.create_it(301)->>'state'='replayed','lost response exact replay');
select pg_temp.check_it(pg_temp.command(301,jsonb_build_object('operation','create','config',pg_temp.config()||'{"name":"Changed"}'))->>'state'='request_conflict','same request cannot change content');
select pg_temp.check_it(pg_temp.create_it(301,104)->>'state'='not_found','second admin cannot take over request');
select pg_temp.check_it(pg_temp.create_it(302,102)->>'state'='forbidden','viewer cannot create');
select pg_temp.check_it(pg_temp.create_it(302,103)->>'state'='forbidden','cross-org cannot create');
select pg_temp.check_it(pg_temp.read_it('list',null,102)->>'count'='1','viewer can inspect schedules');
select pg_temp.check_it(pg_temp.read_it('list',null,103)->>'state'='forbidden','cross-org reads denied');
select pg_temp.check_it(pg_temp.command(302,'{"operation":"cancel_request"}')->>'status'='cancelled_request','unused request tombstone retained');
select pg_temp.check_it(pg_temp.create_it(302)->>'status'='cancelled_request','late creation fenced');
select pg_temp.check_it(pg_temp.command(301,'{"operation":"cancel_request"}')->>'status'='paused','cancel request cannot erase completed schedule');
select pg_temp.check_it(pg_temp.change_it(303,301,'resume',9)->>'state'='schedule_changed','stale revision denied');
select pg_temp.check_it(pg_temp.change_it(303,301,'resume',1)->>'status'='active','resume requires current review');
select pg_temp.check_it(public.claim_bi_schedule(pg_temp.i(401),pg_temp.i(301))->>'state'='not_due','future run never claimed early');
select pg_temp.due(301);
insert into st values('claim',public.claim_bi_schedule(pg_temp.i(401),pg_temp.i(301)));
select pg_temp.check_it((select v->>'state'='claimed'from st where k='claim'),'due occurrence claimed');
select pg_temp.check_it((select jsonb_array_length(v#>'{source,currentRows}')=1 from st where k='claim'),'source retained atomically');
select pg_temp.check_it(public.claim_bi_schedule(pg_temp.i(401),pg_temp.i(301))->>'state'='already_claimed','replayed claim never authorizes resend');
select pg_temp.check_it(public.claim_bi_schedule(pg_temp.i(402),pg_temp.i(301))->>'state'='not_due','second worker cannot claim held schedule');
select pg_temp.check_it(pg_temp.change_it(304,301,'resume',3)->>'state'='open_run','unresolved occurrence blocks future resume');
select pg_temp.check_it(public.prepare_bi_schedule_run(pg_temp.i(401),'{"from":"reports@fixture.invalid","subject":"Fixture","html":"<p>complete snapshot</p>"}')->>'state'='prepared','payload recorded before send');
select pg_temp.check_it(public.prepare_bi_schedule_run(pg_temp.i(401),'{"from":"reports@fixture.invalid","subject":"Changed","html":"<p>changed</p>"}')->>'state'='request_conflict','payload cannot change');
select pg_temp.check_it(public.start_bi_schedule_delivery(pg_temp.delivery(401),pg_temp.i(501))->>'state'='started','first recipient starts once');
select pg_temp.check_it(public.start_bi_schedule_delivery(pg_temp.delivery(401),pg_temp.i(501))->>'state'='not_started','lost start response never grants repeated send');
select pg_temp.check_it(public.finish_bi_schedule_delivery(pg_temp.delivery(401),pg_temp.i(599),'provider-fixture-1')->>'state'='claim_conflict','wrong attempt token denied');
select pg_temp.check_it(public.finish_bi_schedule_delivery(pg_temp.delivery(401),pg_temp.i(501),'provider-fixture-1')->>'status'='accepted','provider acceptance recorded');
select pg_temp.check_it(public.finish_bi_schedule_delivery(pg_temp.delivery(401),pg_temp.i(501),'provider-fixture-1')->>'state'='replayed','acknowledgement replay exact');
select pg_temp.check_it(public.finish_bi_schedule_delivery(pg_temp.delivery(401),pg_temp.i(501),'different')->>'state'='request_conflict','provider identity immutable');
select pg_temp.check_it(public.start_bi_schedule_delivery(pg_temp.delivery(401,1),pg_temp.i(502))->>'state'='started','second recipient independent');
select pg_temp.check_it(public.finish_bi_schedule_delivery(pg_temp.delivery(401,1),pg_temp.i(502),null)->>'status'='unknown','uncertain provider response never claims failure or delivery');
select pg_temp.check_it(public.finish_bi_schedule_run(pg_temp.i(401),null)->>'status'='held','partial provider acceptance held');
select pg_temp.check_it((select state='held'and last_accepted_at is null from public.bi_schedules where id=pg_temp.i(301)),'partial run never advances schedule');
select pg_temp.check_it(public.start_bi_schedule_delivery(pg_temp.delivery(401,1),pg_temp.i(503))->>'state'='not_started','unknown destination never automatically resent');
select pg_temp.check_it(pg_temp.change_it(305,301,'close_run',4)->>'status'='paused','operator closes unresolved run');
select pg_temp.check_it(public.finish_bi_schedule_delivery(pg_temp.delivery(401,1),pg_temp.i(502),'late-provider-reference')->>'status'='accepted','late provider acceptance retained after operator closes');
select pg_temp.check_it((select state='paused'from public.bi_schedules where id=pg_temp.i(301)),'late callback never reactivates closed schedule');
select pg_temp.check_it(pg_temp.change_it(306,301,'resume',5)->>'status'='active','future resume skips closed occurrence');
select pg_temp.due(301);
select pg_temp.check_it(public.claim_bi_schedule(pg_temp.i(403),pg_temp.i(301))->>'state'='claimed','new occurrence has independent run');
select public.prepare_bi_schedule_run(pg_temp.i(403),'{"from":"reports@fixture.invalid","subject":"Fixture","html":"<p>second occurrence</p>"}');
select public.start_bi_schedule_delivery(pg_temp.delivery(403),pg_temp.i(503));
select public.finish_bi_schedule_delivery(pg_temp.delivery(403),pg_temp.i(503),'provider-second-1');
select public.start_bi_schedule_delivery(pg_temp.delivery(403,1),pg_temp.i(504));
select public.finish_bi_schedule_delivery(pg_temp.delivery(403,1),pg_temp.i(504),'provider-second-2');
select pg_temp.check_it(public.finish_bi_schedule_run(pg_temp.i(403),null)->>'status'='accepted','all recipients accepted completes occurrence');
select pg_temp.check_it((select state='active'and last_accepted_at is not null and next_run_at>clock_timestamp()from public.bi_schedules where id=pg_temp.i(301)),'confirmed acceptance advances future run');
select pg_temp.check_it(pg_temp.read_it('run',403)->'run'->>'source_hash'=(select source_hash from public.bi_schedule_runs where id=pg_temp.i(403)),'run exposes exact retained source');
select pg_temp.check_it(pg_temp.read_it('run',403)::text not like'%claim_token%'and pg_temp.read_it('run',403)::text not like'%second occurrence%','private dispatch token and payload omitted from client history');
select pg_temp.check_it(pg_temp.read_it('events',301)->>'count'='17','human and system schedule history retained');
select pg_temp.check_it((select bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)),'all events training-ineligible');
select pg_temp.check_it((select count(*)>0 and bool_and(actor_id is null)from public.shared_action_events where property_id=pg_temp.i(201)and service_principal='bi.scheduler'),'system results never impersonate schedule author');
select pg_temp.check_it((select count(*)=1 from public.shared_action_events where id=pg_temp.i(301)),'human create recorded exactly once');
select pg_temp.throws($q$update public.bi_schedule_commands set input='{}'where id=pg_temp.i(301)$q$,'command evidence immutable');
select pg_temp.throws($q$update public.bi_schedule_runs set source='{}'where id=pg_temp.i(403)$q$,'retained source immutable');
select pg_temp.throws($q$delete from public.bi_schedules where id=pg_temp.i(301)$q$,'cancel cannot delete history');
select pg_temp.create_it(310);select pg_temp.change_it(311,310,'resume',1);select pg_temp.due(310);select public.claim_bi_schedule(pg_temp.i(410),pg_temp.i(310));select public.prepare_bi_schedule_run(pg_temp.i(410),'{"from":"reports@fixture.invalid","subject":"Fixture","html":"<p>cancel fixture</p>"}');select public.start_bi_schedule_delivery(pg_temp.delivery(410),pg_temp.i(510));
select pg_temp.check_it(pg_temp.change_it(312,310,'cancel',3)->>'status'='cancelled','cancel stops future and pending recipients');
select pg_temp.check_it((select state='unknown'from public.bi_schedule_deliveries where id=pg_temp.delivery(410)),'in-flight cancellation remains unknown');
select pg_temp.check_it((select state='skipped'from public.bi_schedule_deliveries where id=pg_temp.delivery(410,1)),'unstarted recipient skipped');
select pg_temp.check_it(public.start_bi_schedule_delivery(pg_temp.delivery(410,1),pg_temp.i(511))->>'state'='not_started','late second recipient fenced by cancel');
select pg_temp.check_it(public.finish_bi_schedule_delivery(pg_temp.delivery(410),pg_temp.i(510),'late-cancelled')->>'status'='accepted','late acceptance after cancellation preserved');
select pg_temp.check_it(pg_temp.change_it(313,310,'resume',4)->>'state'='closed_schedule','cancelled schedule cannot reactivate');
select pg_temp.create_it(320);select pg_temp.change_it(321,320,'resume',1);select pg_temp.due(320);
reset role;select set_config('p11.team_scope',pg_temp.i(1)::text,true);update public.profiles set role='viewer'where id=pg_temp.i(101);set local role service_role;
select pg_temp.check_it(public.claim_bi_schedule(pg_temp.i(420),pg_temp.i(320))->>'reason'='authorization_changed','author removal holds automatic work');
select pg_temp.check_it(pg_temp.read_it('command',301)->>'status'='paused','read own recorded decision remains possible for property viewer');
reset role;update public.profiles set role='admin'where id=pg_temp.i(101);set local role service_role;
select pg_temp.create_it(330);select pg_temp.change_it(331,330,'resume',1);update public.bi_schedules set next_run_at=clock_timestamp()-interval'25 hours'where id=pg_temp.i(330);
select pg_temp.check_it(public.claim_bi_schedule(pg_temp.i(430),pg_temp.i(330))->>'reason'='missed_run','stale backlog requires review');
select pg_temp.create_it(340);select pg_temp.change_it(341,340,'resume',1);select pg_temp.due(340);select public.claim_bi_schedule(pg_temp.i(440),pg_temp.i(340));select public.prepare_bi_schedule_run(pg_temp.i(440),'{"from":"reports@fixture.invalid","subject":"Fixture","html":"<p>scope</p>"}');
reset role;update public.profiles set role='viewer'where id=pg_temp.i(101);set local role service_role;
select pg_temp.check_it(public.start_bi_schedule_delivery(pg_temp.delivery(440),pg_temp.i(540))->>'state'='forbidden','permission is rechecked before each external effect');
reset role;update public.profiles set role='admin'where id=pg_temp.i(101);update public.fact_marketing_performance set spend=200 where property_id=pg_temp.i(201);set local role service_role;
select pg_temp.check_it(pg_temp.read_it('run',403)#>>'{run,source,currentRows,0,spend}'='1.01','later imports do not alter prior report');
select pg_temp.check_it(not has_function_privilege('authenticated','public.claim_bi_schedule(uuid,uuid)','EXECUTE'),'browser cannot claim');
select pg_temp.check_it(not has_function_privilege('anon','public.decide_bi_schedule(uuid,uuid,uuid,jsonb)','EXECUTE'),'anonymous cannot decide');
select pg_temp.check_it(not has_table_privilege('authenticated','public.bi_schedules','UPDATE'),'direct schedule edits unavailable');
select pg_temp.check_it(not has_table_privilege('authenticated','public.scheduled_reports','UPDATE'),'legacy writer cannot bypass replacement protocol');
select pg_temp.create_it(4000+n)from generate_series(1,22)n;
insert into st values('list',pg_temp.read_it());
select pg_temp.check_it((select jsonb_array_length(v->'items')=20 and(v->>'count')::int>20 from st where k='list'),'schedule history paginated with complete count');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it('list',null,101,20)->'items')>0,'subsequent schedules accessible');
select pg_temp.create_it(4050);
select pg_temp.check_it(public.read_bi_schedules(pg_temp.i(101),pg_temp.i(201),jsonb_build_object('kind','list','offset',20,'expectedHash',(select v->>'hash'from st where k='list')))->>'state'='history_changed','concurrent history changes stop page drift');
reset role;
create function pg_temp.fail_evidence()returns trigger language plpgsql as $$begin if new.id=pg_temp.i(4999)then raise exception 'fixture evidence failure';end if;return new;end$$;
create trigger bi_schedule_fixture_evidence before insert on public.shared_action_events for each row execute function pg_temp.fail_evidence();
set local role service_role;
select pg_temp.throws('select pg_temp.create_it(4999)','action recording failure rolls back schedule');
select pg_temp.check_it(not exists(select 1 from public.bi_schedules where id=pg_temp.i(4999))and not exists(select 1 from public.bi_schedule_commands where id=pg_temp.i(4999)),'no schedule saved without its evidence');
reset role;
select n as passed_assertions from assertion_count;
ROLLBACK;
