BEGIN;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create function pg_temp.fixture() returns jsonb language plpgsql as $$declare p uuid:=gen_random_uuid();b uuid:=gen_random_uuid();actor uuid;begin
 select id into actor from public.profiles where org_id='22222222-2222-2222-2222-222222222222' and role='admin' limit 1;
 insert into public.properties(id,org_id,name)values(p,'22222222-2222-2222-2222-222222222222','Brand revision SQL fixture');
 insert into public.property_brand_assets(id,property_id,generated_by,generation_status,current_step,current_step_name,draft_section,approval_status)values(b,p,actor,'reviewing',1,'introduction','{"step":1,"name":"introduction","data":{"content":"Original draft"},"version":1}','reviewing');
 return jsonb_build_object('p',p,'b',b,'actor',actor);
end$$;
create function pg_temp.begin_op(f jsonb,k text,request_id uuid,rev bigint default 1,input jsonb default '{}') returns jsonb language sql as $$select public.begin_brand_operation((f->>'p')::uuid,(f->>'b')::uuid,(f->>'actor')::uuid,request_id,rev,k,input)$$;
DO $$declare f jsonb;c jsonb;r jsonb;decision uuid;next_id uuid;updates jsonb;b public.property_brand_assets;before_count int;imp uuid;at timestamptz;
begin
 f:=pg_temp.fixture();decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'edit',decision,1,'{"content":"Changed"}');
 perform pg_temp.check(public.check_brand_operation(decision,(c->>'claimToken')::uuid)->>'state'='active','claimed request may start provider work');
 perform pg_temp.check(c->>'state'='claimed','edit claims the exact saved revision');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where episode_id=decision and action='brand.operation.requested'),'request history is recorded before work');
 perform pg_temp.check(pg_temp.begin_op(f,'edit',decision,1,'{"content":"Changed"}')->>'state'='running','same in-flight request does not repeat execution');
 perform pg_temp.check(pg_temp.begin_op(f,'edit',decision,1,'{"content":"Other"}')->>'state'='request_conflict','request identity cannot change');
 perform pg_temp.check(pg_temp.begin_op(f,'edit',gen_random_uuid())->>'state'='busy','concurrent edits are held');
 updates:='{"draft_section":{"step":1,"name":"introduction","data":{"content":"Changed"},"version":2}}';
 perform pg_temp.check(public.finish_brand_operation(decision,gen_random_uuid(),updates,'{}')->>'state'='claim_conflict','forged claim cannot complete');
 r:=public.finish_brand_operation(decision,(c->>'claimToken')::uuid,updates,'{"data":{"content":"Changed"}}');
 perform pg_temp.check(r->>'state'='applied' and r->>'revision'='2','confirmed edit returns the saved version');
 perform pg_temp.check((select draft_section->'data'->>'content'='Changed' and revision=2 from public.property_brand_assets where id=(f->>'b')::uuid),'edited content saved');
 begin update public.brand_revisions set snapshot='{}' where brand_asset_id=(f->>'b')::uuid;raise exception 'FAIL: mutable history';exception when raise_exception then if SQLERRM<>'Brand revision history is immutable' then raise;end if;end;
 perform pg_temp.check((select snapshot->'draft_section'->'data'->>'content'='Original draft' from public.brand_revisions where brand_asset_id=(f->>'b')::uuid and revision=1),'historical brand content cannot be rewritten');
 perform pg_temp.check((select count(*)=2 from public.brand_revisions where brand_asset_id=(f->>'b')::uuid),'original and changed contents preserved');
 perform pg_temp.check((select before_state->>'revision'='1' and after_state->>'revision'='2' and not training_eligible from public.shared_action_events where id=decision),'history links exact revisions without training opt-in');
 perform pg_temp.check(pg_temp.begin_op(f,'edit',decision,1,'{"content":"Changed"}')->>'state'='replayed','lost response recovers the prior result');
 perform pg_temp.check(public.finish_brand_operation(decision,(c->>'claimToken')::uuid,updates,'{}')->>'state'='replayed','lost completion acknowledgment is idempotent');
 perform pg_temp.check(pg_temp.begin_op(f,'edit',gen_random_uuid())->>'state'='stale','stale browser cannot overwrite');
 perform pg_temp.check(pg_temp.begin_op(f,'export',gen_random_uuid(),2)->>'state'='approval_required','draft cannot be exported');
 perform pg_temp.check(pg_temp.begin_op(f,'generate',gen_random_uuid(),2)->>'state'='draft_exists','reopening cannot regenerate a saved draft');
 next_id:=gen_random_uuid();c:=pg_temp.begin_op(f,'approve',next_id,2);
 r:=public.finish_brand_operation(next_id,(c->>'claimToken')::uuid,'{"section_1_introduction":{"content":"Changed","_meta":{"approval":{"status":"approved"}}},"current_step":2,"current_step_name":"positioning","draft_section":null,"generation_status":"generating","approval_status":"reviewing"}','{"approvedStep":1}');
 perform pg_temp.check(r->>'state'='applied','section approval saved');
 perform pg_temp.check((select current_step=2 and draft_section is null and approved_by is null and approval_status='reviewing' from public.property_brand_assets where id=(f->>'b')::uuid),'one section approval does not approve whole book');
 f:=pg_temp.fixture();decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'regenerate',decision);
 perform pg_temp.check(public.cancel_brand_operation((f->>'p')::uuid,decision,(f->>'actor')::uuid,gen_random_uuid())->>'state'='cancelled','operator can stop an unconfirmed generation');
 perform pg_temp.check(public.check_brand_operation(decision,(c->>'claimToken')::uuid)->>'state'='cancelled','stopped request cannot start another provider step');
 perform pg_temp.check(public.finish_brand_operation(decision,(c->>'claimToken')::uuid,updates,'{}')->>'state'='cancelled','late provider result cannot overwrite after stop');
 perform pg_temp.check((select revision=1 and draft_section->'data'->>'content'='Original draft' from public.property_brand_assets where id=(f->>'b')::uuid),'stop preserves prior draft');
 perform pg_temp.check(pg_temp.begin_op(f,'edit',gen_random_uuid())->>'state'='claimed','stop releases the brand for a new decision');
 f:=pg_temp.fixture();decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'edit',decision);
 update public.property_brand_assets set conversation_summary='{"legacy":"newer"}' where id=(f->>'b')::uuid;
 perform pg_temp.check(public.finish_brand_operation(decision,(c->>'claimToken')::uuid,updates,'{}')->>'code'='stale','older service writers also fence completion');
 perform pg_temp.check((select revision=2 and draft_section->'data'->>'content'='Original draft' from public.property_brand_assets where id=(f->>'b')::uuid),'stale save preserves newer content');
 f:=pg_temp.fixture();decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'edit',decision);
 begin perform public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{"property_id":"33333333-3333-3333-3333-333333333333"}','{}');raise exception 'FAIL: unsafe field accepted';exception when raise_exception then if SQLERRM<>'Unexpected brand fields' then raise;end if;end;
 perform pg_temp.check((select revision=1 from public.property_brand_assets where id=(f->>'b')::uuid),'forbidden fields cannot change brand');
 r:=public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{}','{}','save_failed');
 perform pg_temp.check(r->>'code'='save_failed','failure can be durably recorded');
 perform pg_temp.check((select phase='failed' from public.shared_action_events where id=decision),'failure is distinguished from saved content');
 perform pg_temp.check(pg_temp.begin_op(jsonb_set(f,'{actor}',to_jsonb(gen_random_uuid())),'edit',gen_random_uuid())->>'state'='forbidden','unknown actor rejected');
 perform pg_temp.check(pg_temp.begin_op(jsonb_set(f,'{p}',to_jsonb(gen_random_uuid())),'edit',gen_random_uuid())->>'state'='forbidden','cross-property actor rejected');
 perform pg_temp.check(not has_function_privilege('authenticated','public.begin_brand_operation(uuid,uuid,uuid,uuid,bigint,text,jsonb)','execute'),'commands are service only');
 perform pg_temp.check(not has_table_privilege('authenticated','public.brand_operations','select'),'browser cannot read private claims or prompt inputs');
 perform pg_temp.check(not has_table_privilege('authenticated','public.property_brand_assets','update'),'browser cannot bypass atomic brand saves');
 f:=pg_temp.fixture();update public.property_brand_assets set draft_section=null,approval_status='approved',approved_by=(f->>'actor')::uuid,approved_at=now(),generation_status='complete' where id=(f->>'b')::uuid;
 decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'export',decision,2);
 r:=public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{"brand_book_pdf_url":"https://fixture.invalid/book.pdf","pdf_generated_at":"2026-09-16T00:00:00Z"}','{"pdfUrl":"https://fixture.invalid/book.pdf","exportedRevision":2}');
 perform pg_temp.check(r->>'state'='applied','approved revision can attach export');
 perform pg_temp.check((select brand_book_pdf_url is not null and revision=3 from public.property_brand_assets where id=(f->>'b')::uuid),'export points to saved revision');
 update public.property_brand_assets set section_1_introduction='{"content":"New content"}' where id=(f->>'b')::uuid;
 perform pg_temp.check((select brand_book_pdf_url is null and pdf_generated_at is null from public.property_brand_assets where id=(f->>'b')::uuid),'content change invalidates old export');
 f:=pg_temp.fixture();imp:=gen_random_uuid();
 insert into public.property_brand_imports(id,org_id,property_id,status,source_type,source_identity,idempotency_key,created_by)values(imp,'22222222-2222-2222-2222-222222222222',(f->>'p')::uuid,'needs_review','manual','fixture',imp::text,(f->>'actor')::uuid) returning updated_at into at;
 decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'import',decision);
 r:=public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{"approval_status":"approved","generation_status":"complete","draft_section":null,"current_step":12}',jsonb_build_object('contract',jsonb_build_object('identity',jsonb_build_object('name','Approved import')),'contractHash','fixture-hash','importReceipt',jsonb_build_object('id',imp,'updatedAt',at,'assetIds','[]'::jsonb,'conflicts','[]'::jsonb)));
 perform pg_temp.check(r->>'state'='applied' and not r?'importReceipt','private import receipt is not returned');
 perform pg_temp.check((select status='confirmed' and confirmed_by=(f->>'actor')::uuid from public.property_brand_imports where id=imp),'import preview confirmation commits with brand');
 perform pg_temp.check((select approved_by=(f->>'actor')::uuid and approval_status='approved' from public.property_brand_assets where id=(f->>'b')::uuid),'import approval actor is current decision maker');
end$$;
DO $$declare f jsonb;c jsonb;r jsonb;decision uuid;old_doc uuid:=gen_random_uuid();new_doc uuid:=gen_random_uuid();docs jsonb;proposal jsonb;
begin
 f:=pg_temp.fixture();update public.property_brand_assets set draft_section=null,approval_status='approved',approved_by=(f->>'actor')::uuid,approved_at=now(),generation_status='complete' where id=(f->>'b')::uuid;
 insert into public.documents(id,property_id,content,metadata)values(old_doc,(f->>'p')::uuid,'Old approved knowledge','{"type":"brand_book"}');
 docs:=jsonb_build_array(jsonb_build_object('id',new_doc,'content','New approved knowledge','metadata','{}'::jsonb,'embedding',to_jsonb(array_fill(0.01::float8,array[1536]))));
 decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'publish',decision,2);
 r:=public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{}',jsonb_build_object('embeddedChunks',1,'totalChunks',1,'knowledgeReceipt',jsonb_build_object('documents',docs,'sourceName','Brand fixture')));
 perform pg_temp.check(r->>'state'='applied' and not r?'knowledgeReceipt' and r->>'sourceId' is not null,'knowledge publication returns a persisted source receipt');
 perform pg_temp.check(not exists(select 1 from public.documents where id=old_doc) and exists(select 1 from public.documents where id=new_doc and property_id=(f->>'p')::uuid and metadata->>'brand_revision'='2'),'complete replacement swaps documents with revision lineage');
 perform pg_temp.check((select documents_created=1 and status='completed' from public.knowledge_sources where id=(r->>'sourceId')::uuid),'source count is the actual committed count');
 perform pg_temp.check((select result->>'documentCount'='1' and result->>'sourceId'=r->>'sourceId' and result->>'contextRefresh'='pending' from public.shared_action_events where id=decision),'publication history links actual source and pending downstream refresh');
 perform pg_temp.check((select revision=2 from public.property_brand_assets where id=(f->>'b')::uuid),'knowledge publication does not invent a content revision');
 perform pg_temp.check(pg_temp.begin_op(f,'publish',decision,2)->>'state'='replayed','publication replay does not repeat provider work or replace documents twice');
 decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'publish',decision,2);
 begin perform public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{}',jsonb_build_object('knowledgeReceipt',jsonb_build_object('documents',jsonb_set(docs,'{0,embedding}','[0.1]'),'sourceName','Invalid')));raise exception 'FAIL: partial vector accepted';exception when raise_exception then if SQLERRM<>'Invalid knowledge document' then raise;end if;end;
 perform pg_temp.check(exists(select 1 from public.documents where id=new_doc),'incomplete replacement preserves published knowledge');
 perform public.cancel_brand_operation((f->>'p')::uuid,decision,(f->>'actor')::uuid,gen_random_uuid());
 decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'revise',decision,2);
 proposal:=jsonb_build_object('proposed_sections',jsonb_build_object('section_1_introduction',jsonb_build_object('content','New revision')),'current_step',1,'current_step_name','introduction','draft_section',jsonb_build_object('step',1,'name','introduction','version',1,'data',jsonb_build_object('content','New revision')),'approval_status','reviewing','generation_status','reviewing','approved_by',null,'approved_at',null,'contract_hash',null,'section_1_introduction',null);
 r:=public.finish_brand_operation(decision,(c->>'claimToken')::uuid,proposal,'{"readyForReview":true}');
 perform pg_temp.check(r->>'state'='applied','approved brand can enter a new versioned review');
 perform pg_temp.check((select approval_status='reviewing' and approved_by is null and draft_section->'data'->>'content'='New revision' from public.property_brand_assets where id=(f->>'b')::uuid),'new revision clears inherited approval');
 perform pg_temp.check(pg_temp.begin_op(f,'publish',gen_random_uuid(),3)->>'state'='approval_required','unapproved revision cannot replace currently published knowledge');
 perform pg_temp.check(exists(select 1 from public.documents where id=new_doc),'starting revision preserves the last approved knowledge publication');
end$$;
create function pg_temp.reject_brand_event() returns trigger language plpgsql as $$begin raise exception 'Fixture brand history failure';end$$;
create trigger fixture_reject_brand before insert on public.shared_action_events for each row when(new.action in ('brand.section.edited','brand.contract.imported','brand.knowledge.published')) execute function pg_temp.reject_brand_event();
DO $$declare f jsonb;decision uuid;c jsonb;begin
 f:=pg_temp.fixture();decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'edit',decision);
 begin perform public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{"draft_section":{"step":1,"name":"introduction","data":{"content":"Unsaved"},"version":2}}','{}');raise exception 'FAIL: missing history ignored';exception when raise_exception then if SQLERRM<>'Fixture brand history failure' then raise;end if;end;
 perform pg_temp.check((select revision=1 and draft_section->'data'->>'content'='Original draft' from public.property_brand_assets where id=(f->>'b')::uuid),'history failure rolls back edited content');
 perform pg_temp.check((select state='running' from public.brand_operations where id=decision),'history failure leaves request unconfirmed for review');
 perform pg_temp.check((select count(*)=1 from public.brand_revisions where brand_asset_id=(f->>'b')::uuid),'rolled-back edit creates no phantom revision');
end$$;
DO $$declare f jsonb;decision uuid;c jsonb;old_doc uuid:=gen_random_uuid();docs jsonb;begin
 f:=pg_temp.fixture();update public.property_brand_assets set draft_section=null,approval_status='approved',approved_by=(f->>'actor')::uuid,approved_at=now(),generation_status='complete' where id=(f->>'b')::uuid;
 insert into public.documents(id,property_id,content,metadata)values(old_doc,(f->>'p')::uuid,'Previous approved knowledge','{"type":"brand_book"}');
 docs:=jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'content','Replacement','metadata','{}'::jsonb,'embedding',to_jsonb(array_fill(0.01::float8,array[1536]))));
 decision:=gen_random_uuid();c:=pg_temp.begin_op(f,'publish',decision,2);
 begin perform public.finish_brand_operation(decision,(c->>'claimToken')::uuid,'{}',jsonb_build_object('knowledgeReceipt',jsonb_build_object('documents',docs,'sourceName','Brand fixture')));raise exception 'FAIL: publication without history';exception when raise_exception then if SQLERRM<>'Fixture brand history failure' then raise;end if;end;
 perform pg_temp.check(exists(select 1 from public.documents where id=old_doc),'publication history failure restores old knowledge');
 perform pg_temp.check(not exists(select 1 from public.knowledge_sources where property_id=(f->>'p')::uuid),'failed transaction leaves no false completed source');
end$$;
drop trigger fixture_reject_brand on public.shared_action_events;
DO $$declare f jsonb;begin f:=pg_temp.fixture();delete from public.property_brand_assets where id=(f->>'b')::uuid;perform pg_temp.check(not exists(select 1 from public.brand_revisions where brand_asset_id=(f->>'b')::uuid),'property-owned cleanup can cascade immutable revisions');end$$;
select count(*) as passed from checks;
ROLLBACK;
