BEGIN;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixtures(property_id uuid,actor_id uuid);
insert into fixtures select gen_random_uuid(),id from public.profiles where org_id='22222222-2222-2222-2222-222222222222' and role='admin' limit 1;
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','Brand sources SQL fixture' from fixtures;
DO $$declare p uuid;actor uuid;q uuid:=gen_random_uuid();input jsonb;payload jsonb;r jsonb;a uuid;rev bigint;review jsonb;rid uuid;source uuid:=gen_random_uuid();preview jsonb;key text:=gen_random_uuid()::text;before_count int;
begin
 select property_id,actor_id into p,actor from fixtures;
 input:=jsonb_build_object('contentHash',repeat('a',64),'role','primary_logo','size',40,'metadataHash',repeat('b',64));
 payload:='{"name":"Logo","asset_type":"image","asset_role":"primary_logo","file_url":"https://fixture.invalid/logo.svg","file_size_bytes":40,"format":"svg","storage_bucket":"property-assets","storage_path":"fixture/logo.svg","rights_status":"owned","rights_metadata":{"license":"Private license evidence"}}';
 perform pg_temp.check(public.begin_brand_asset_upload(p,actor,q,input)->>'state'='prepared','upload request saved before storage');
 perform pg_temp.check(public.begin_brand_asset_upload(p,actor,q,input)->>'state'='prepared','unconfirmed upload can safely retry');
 perform pg_temp.check(public.begin_brand_asset_upload(p,actor,q,jsonb_set(input,'{size}','41'))->>'state'='request_conflict','same request cannot change input');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where episode_id=q),'repeated preparation creates one event');
 perform pg_temp.check(public.finish_brand_asset_upload(p,actor,q,input,null,'upload_failed')->>'state'='upload_failed','upload failure recorded');
 r:=public.finish_brand_asset_upload(p,actor,q,input,payload);a:=(r->>'assetId')::uuid;
 perform pg_temp.check(r->>'state'='applied' and r->>'revision'='1','asset saves pending review at version one');
 perform pg_temp.check((select approval_status='pending' and approved_by is null from public.content_assets where id=a),'upload does not approve rights');
 perform pg_temp.check(public.finish_brand_asset_upload(p,actor,q,input,payload)->>'state'='replayed','lost upload reply recovers one result');
 perform pg_temp.check((select count(*)=1 from public.content_assets where property_id=p),'one upload has one asset');
 perform pg_temp.check((select count(*)=3 from public.shared_action_events where episode_id=q),'request failure and success remain distinct');
 perform pg_temp.check((select not exists(select 1 from public.shared_action_events where property_id=p and (training_eligible or request::text like '%Private license%'))),'private evidence stays outside learning history');
 perform pg_temp.check(public.finish_brand_asset_upload(p,actor,gen_random_uuid(),input,payload)->>'duplicate'='true','same bytes reuse existing asset');
 perform pg_temp.check(public.finish_brand_asset_upload(p,actor,gen_random_uuid(),jsonb_set(input,'{role}','"secondary_logo"'),payload)->>'state'='role_conflict','same bytes cannot silently change role');
 perform pg_temp.check(public.begin_brand_asset_upload(p,gen_random_uuid(),gen_random_uuid(),input)->>'state'='forbidden','unknown actor cannot prepare upload');
 review:='{"approvalStatus":"approved","rightsStatus":"owned"}';rid:=gen_random_uuid();
 perform pg_temp.check(public.review_brand_asset(p,a,actor,rid,1,review)->>'revision'='2','review increments version');
 perform pg_temp.check((select approval_status='approved' and curation_status='approved' and approved_by=actor and rights_metadata->>'license'='Private license evidence' from public.content_assets where id=a),'review saves decision and retains omitted license evidence');
 perform pg_temp.check(public.review_brand_asset(p,a,actor,rid,1,review)->>'state'='replayed','lost review response does not approve twice');
 perform pg_temp.check(public.review_brand_asset(p,a,actor,rid,1,jsonb_set(review,'{rightsStatus}','"licensed"'))->>'state'='request_conflict','reused decision cannot change rights');
 perform pg_temp.check(public.review_brand_asset(p,a,actor,gen_random_uuid(),1,review)->>'state'='stale','stale review held');
 perform pg_temp.check((select count(*)=2 from public.brand_asset_revisions where asset_id=a),'before and after rights versions retained');
 update public.content_assets set expires_at=now()-interval '1 day' where id=a returning governance_revision into rev;
 perform pg_temp.check(public.review_brand_asset(p,a,actor,gen_random_uuid(),rev,review)->>'state'='rights_required','omitted expiry cannot approve an expired asset');
 perform pg_temp.check(public.review_brand_asset(p,a,actor,gen_random_uuid(),rev,review||'{"expiresAt":null}')->>'state'='applied','explicit removal of expiry is a recorded review');
 select governance_revision into rev from public.content_assets where id=a;
 perform pg_temp.check(public.review_brand_asset(p,a,actor,gen_random_uuid(),rev,'{"approvalStatus":"rejected","rightsStatus":"restricted"}')->>'state'='applied','rights can be revoked');
 perform pg_temp.check((select approval_status='rejected' and approved_by is null and approved_at is null from public.content_assets where id=a),'revocation clears approval identity');
 perform pg_temp.check(public.review_brand_asset(p,a,actor,gen_random_uuid(),rev+1,'{"approvalStatus":"approved","rightsStatus":"restricted"}')->>'state'='rights_required','restricted rights cannot approve');
 begin update public.brand_asset_revisions set snapshot='{}' where asset_id=a;raise exception 'FAIL mutable snapshot';exception when raise_exception then if SQLERRM<>'Brand revision history is immutable' then raise;end if;end;
 perform pg_temp.check((select snapshot->'rights_metadata'->>'license'='Private license evidence' from public.brand_asset_revisions where asset_id=a and revision=1),'historical license evidence preserved');
 r:=public.save_brand_import_source(p,actor,source,repeat('c',64),repeat('d',64),'Package.txt','text/plain','Client supplied brand text #123456');
 perform pg_temp.check(r->>'state'='applied','private package source saved');
 perform pg_temp.check(public.save_brand_import_source(p,actor,source,repeat('c',64),repeat('d',64),'Package.txt','text/plain','Client supplied brand text #123456')->>'state'='replayed','source retry returns same receipt');
 perform pg_temp.check(public.save_brand_import_source(p,actor,source,repeat('e',64),repeat('d',64),'Package.txt','text/plain','Changed')->>'state'='request_conflict','source request identity fenced');
 perform pg_temp.check(not exists(select 1 from public.documents where property_id=p),'review source is not published knowledge');
 perform pg_temp.check(not exists(select 1 from public.knowledge_sources where property_id=p),'review source does not claim a published source');
 preview:='{"source_type":"package","source_identity":"fixture","source_manifest":[],"extracted_contract":{"identity":{"name":"Client brand"}},"conflicts":[],"extraction_report":{},"content_hash":"preview-hash"}';
 r:=public.save_brand_import_preview(p,actor,key,repeat('f',64),0,preview);
 perform pg_temp.check(r->>'state'='applied' and r->'preview'->'extraction_report'->>'baseRevision'='0','preview and initial brand version saved');
 perform pg_temp.check(public.save_brand_import_preview(p,actor,key,repeat('f',64),0,preview)->>'state'='replayed','preview retry creates no extra import');
 perform pg_temp.check(public.save_brand_import_preview(p,actor,key,repeat('a',64),0,preview)->>'state'='request_conflict','preview identity cannot change');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=p and action='brand.import.previewed'),'one semantic preview record');
 insert into public.property_brand_assets(property_id,generated_by)values(p,actor);
 perform pg_temp.check(public.save_brand_import_preview(p,actor,gen_random_uuid()::text,repeat('f',64),0,preview)->>'state'='stale','preview cannot attach to a changed brand');
 perform pg_temp.check(not has_table_privilege('authenticated','public.brand_import_sources','select'),'browser cannot read private source table');
 perform pg_temp.check(not has_table_privilege('authenticated','public.brand_asset_revisions','select'),'browser cannot read private historical rights evidence');
 perform pg_temp.check(not has_function_privilege('authenticated','public.review_brand_asset(uuid,uuid,uuid,uuid,bigint,jsonb)','execute'),'review service cannot be directly impersonated');
end$$;
-- Actual RLS caller cannot bypass the service to approve an asset.
select set_config('request.jwt.claim.sub',(select actor_id::text from fixtures),true);
select set_config('request.jwt.claims',jsonb_build_object('sub',(select actor_id from fixtures),'role','authenticated')::text,true);
grant select on fixtures to authenticated;
set local role authenticated;
DO $$declare p uuid;a uuid;begin
 select property_id into p from fixtures;
 begin update public.content_assets set approval_status='approved' where property_id=p;raise exception 'FAIL direct approval';exception when raise_exception then if SQLERRM<>'Governed asset changes require the review service' then raise;end if;end;
 insert into public.content_assets(org_id,property_id,name,asset_type,file_url,approval_status)values('22222222-2222-2222-2222-222222222222',p,'Pending compatible upload','image','https://fixture.invalid/new.svg','pending') returning id into a;
 update public.content_assets set name='Renamed pending upload' where id=a;
 begin insert into public.content_assets(org_id,property_id,name,asset_type,file_url,approval_status)values('22222222-2222-2222-2222-222222222222',p,'Bypass','image','https://fixture.invalid/bypass.svg','approved');raise exception 'FAIL direct preapproval';exception when raise_exception then if SQLERRM<>'Governed asset changes require the review service' then raise;end if;end;
end$$;
reset role;
select pg_temp.check((select governance_revision=2 from public.content_assets where name='Renamed pending upload'),'ordinary pending upload remains compatible with new versioning');
-- Any history write failure rolls back the related content change.
create function pg_temp.fail_history() returns trigger language plpgsql as $$begin if new.action in ('brand.asset.reviewed','brand.import.previewed','brand.source.saved') then raise exception 'History unavailable';end if;return new;end$$;
create trigger source_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_history();
DO $$declare p uuid;actor uuid;a uuid;rev bigint;source uuid:=gen_random_uuid();key text:=gen_random_uuid()::text;
begin
 select property_id,actor_id into p,actor from fixtures;
 select id,governance_revision into a,rev from public.content_assets where property_id=p and asset_role='primary_logo';
 begin perform public.review_brand_asset(p,a,actor,gen_random_uuid(),rev,'{"approvalStatus":"approved","rightsStatus":"owned"}');raise exception 'FAIL review without event';exception when raise_exception then if SQLERRM<>'History unavailable' then raise;end if;end;
 perform pg_temp.check((select governance_revision=rev and approval_status='rejected' from public.content_assets where id=a),'history failure rolls back rights approval');
 begin perform public.save_brand_import_source(p,actor,source,repeat('c',64),repeat('d',64),'Package.txt','text/plain','Text');raise exception 'FAIL source without event';exception when raise_exception then if SQLERRM<>'History unavailable' then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.brand_import_sources where id=source),'history failure rolls back private source');
 begin perform public.save_brand_import_preview(p,actor,key,repeat('f',64),1,'{"source_type":"manual","source_identity":"fixture","source_manifest":[],"extracted_contract":{},"conflicts":[],"content_hash":"hash"}');raise exception 'FAIL preview without event';exception when raise_exception then if SQLERRM<>'History unavailable' then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.property_brand_imports where property_id=p and idempotency_key=key),'history failure rolls back preview');
end$$;
select count(*) as passed from checks;
ROLLBACK;
