BEGIN;
SET LOCAL jit=off;
create temp table checks(label text);
create function pg_temp.check(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
do $$declare p uuid:=gen_random_uuid();p2 uuid:=gen_random_uuid();c uuid:=gen_random_uuid();c2 uuid:=gen_random_uuid();retired uuid:=gen_random_uuid();replacement uuid:=gen_random_uuid();l uuid:=gen_random_uuid();actor uuid;b uuid;r jsonb;before_events bigint;begin
 select id into actor from public.profiles where org_id='22222222-2222-2222-2222-222222222222'order by id limit 1;
 insert into public.properties(id,name,org_id)values(p,'Calendar summary SQL fixture','22222222-2222-2222-2222-222222222222'),(p2,'Calendar summary SQL fixture','22222222-2222-2222-2222-222222222222');
 insert into public.leads(id,property_id,first_name,status)values(l,p,'Summary fixture','tour_booked');
 insert into public.agent_calendars(id,property_id,profile_id,provider,account_email,calendar_id)values(c,p,actor,'google','fixture@example.invalid','fixture'),(c2,p2,actor,'google','fixture@example.invalid','other');
 insert into public.integration_replacements(id,property_id,actor_id,capability,provider,account_email,revision,review)values(replacement,p,actor,'calendar','google','fixture@example.invalid','fixture','{}');
 insert into public.agent_calendars(id,property_id,profile_id,provider,account_email,calendar_id,retired_at,replacement_id,sync_enabled,token_status)values(retired,p,actor,'google','fixture@example.invalid','retired',clock_timestamp(),replacement,false,'disconnected');
 perform pg_temp.check(public.read_calendar_sync_summary(p,retired,actor)->>'state'='not_found','retired connection rejected');
 r:=public.read_calendar_sync_summary(p,c,actor);perform pg_temp.check(r#>>'{summary,total_events}'='0'and r#>>'{summary,degraded}'='false','empty connected scope has actual zero counts');
 insert into public.tour_bookings(property_id,lead_id,scheduled_date,scheduled_time,status)select p,l,current_date+n*5,'10:00',case when n=1106 then 'cancelled'when n=1107 then 'completed'else 'confirmed'end from generate_series(1,1107)n;
 insert into public.calendar_events(agent_calendar_id,google_event_id,provider_event_id,sync_status)select c,'fixture-'||n,'fixture-'||n,case when n<=1100 then 'synced'when n=1101 then 'failed'when n=1102 then 'external_drift'when n=1103 then 'external_missing'when n=1104 then 'external_cancelled'else 'pending'end from generate_series(1,1105)n;
 select id into b from public.tour_bookings where property_id=p and status='confirmed'order by id limit 1;
 update public.calendar_events set tour_booking_id=b where agent_calendar_id=c and provider_event_id='fixture-1';
 insert into public.calendar_events(agent_calendar_id,google_event_id,provider_event_id,sync_status)values(c2,'unrelated','unrelated','failed');
 select count(*)into before_events from public.shared_action_events where property_id=p;
 r:=public.read_calendar_sync_summary(p,c,actor);
 perform pg_temp.check(r->>'state'='ready','current property member can read');
 perform pg_temp.check(r#>>'{summary,total_events}'='1105','complete event total beyond REST cap');
 perform pg_temp.check(r#>>'{summary,synced_events}'='1100','complete healthy count beyond REST cap');
 perform pg_temp.check(r#>>'{summary,failed_events}'='1','failure beyond first page included');
 perform pg_temp.check(r#>>'{summary,external_drift_events}'='1','drift counted');
 perform pg_temp.check(r#>>'{summary,external_missing_events}'='1','missing event counted');
 perform pg_temp.check(r#>>'{summary,external_cancelled_events}'='1','external cancellation counted');
 perform pg_temp.check(r#>>'{summary,other_events}'='1','unknown status not counted as synced');
 perform pg_temp.check(r#>>'{summary,missing_event_bookings}'='1104','complete active booking count excludes closed and linked bookings');
 perform pg_temp.check(r#>>'{summary,degraded}'='true','actual failures mark degraded');
 perform pg_temp.check((select count(*)=before_events from public.shared_action_events where property_id=p),'summary read does not create decision history');
 perform pg_temp.check(public.read_calendar_sync_summary(p,c,gen_random_uuid())->>'state'='forbidden','unknown actor cannot read');
 perform pg_temp.check(public.read_calendar_sync_summary(p,c2,actor)->>'state'='not_found','other property calendar rejected');
 perform pg_temp.check(public.read_calendar_sync_summary(gen_random_uuid(),c,actor)->>'state'='forbidden','outside actor scope rejected');
 perform pg_temp.check(not has_function_privilege('authenticated','public.read_calendar_sync_summary(uuid,uuid,uuid)','EXECUTE')and not has_function_privilege('anon','public.read_calendar_sync_summary(uuid,uuid,uuid)','EXECUTE'),'browser and anonymous roles cannot impersonate actors');
end$$;
select count(*)as passed_assertions from checks;
ROLLBACK;
