begin;
create temp table assertions(n int);insert into assertions values(0);
create function pg_temp.ok(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertions set n=n+1;end$$;
create function pg_temp.denied(statement text,label text)returns void language plpgsql as $$declare rejected boolean:=false;begin begin execute statement;exception when insufficient_privilege then rejected:=true;end;perform pg_temp.ok(rejected,label);end$$;
create function pg_temp.uid(n int)returns uuid language sql as $$select ('ec930000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into public.organizations(id,name)values(pg_temp.uid(1),'Portal fixture'),(pg_temp.uid(2),'Other portal fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.uid(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','portal-'||n||'@fixture.invalid',now(),now(),now()from generate_series(101,106)n;
insert into public.profiles(id,org_id,role,full_name)select pg_temp.uid(n),case when n<=102 then pg_temp.uid(1)when n=106 then pg_temp.uid(2)end,case when n in(101,106)then'admin'else'viewer'end,'Portal fixture '||n from generate_series(101,106)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name,address)values(pg_temp.uid(11),pg_temp.uid(1),'Assigned property','{"city":"Portland"}'),(pg_temp.uid(12),pg_temp.uid(1),'Unassigned property','{}'),(pg_temp.uid(13),pg_temp.uid(2),'Other organization property','{}');
create function pg_temp.invite(p uuid default pg_temp.uid(11),email text default'portal-103@fixture.invalid')returns jsonb language sql as $$select jsonb_build_object('operation','invite','name','Client fixture','email',email,'propertyIds',jsonb_build_array(p))$$;
grant select,update on assertions to service_role,authenticated,anon;
set local role service_role;
select pg_temp.ok(not has_table_privilege('service_role','auth.users','SELECT'),'service access to auth users stays restricted');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(201),pg_temp.uid(102),pg_temp.invite(),repeat('a',64))->>'state'='forbidden','viewer cannot invite');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(201),pg_temp.uid(101),pg_temp.invite(pg_temp.uid(13)),repeat('a',64))->>'state'='invalid_properties','cross organization property rejected');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(201),pg_temp.uid(101),pg_temp.invite(),repeat('a',64))->>'state'='saved','admin invite succeeds through application role');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(201),pg_temp.uid(101),pg_temp.invite(),repeat('b',64))->>'state'='replayed','lost response does not make a second invitation');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(201),pg_temp.uid(101),pg_temp.invite(pg_temp.uid(12)),repeat('a',64))->>'state'='request_conflict','same request cannot alter properties');
select pg_temp.ok(public.read_client_access(pg_temp.uid(101))::text not like'%aaaaaaaaaaaaaaaa%','roster contains no invitation secrets');
select pg_temp.ok(jsonb_array_length(public.read_client_access(pg_temp.uid(106))->'invitations')=0,'other organization sees none of these invitations');
select pg_temp.ok(public.join_client_portal(pg_temp.uid(202),pg_temp.uid(104),repeat('a',64),true)->>'state'='recipient_required','wrong signed in recipient rejected');
select pg_temp.ok(public.join_client_portal(pg_temp.uid(202),pg_temp.uid(103),repeat('a',64),false)->>'state'='ready','recipient reviews without joining');
select pg_temp.ok(not exists(select 1 from public.client_portal_accounts where user_id=pg_temp.uid(103)),'review does not grant access');
select pg_temp.ok(public.join_client_portal(pg_temp.uid(202),pg_temp.uid(103),repeat('a',64),true)->>'state'='joined','recipient accepts');
select pg_temp.ok(public.join_client_portal(pg_temp.uid(203),pg_temp.uid(103),repeat('a',64),true)->>'state'='joined','repeat acceptance is safe');
select pg_temp.ok((select org_id is null and role='viewer'from public.profiles where id=pg_temp.uid(103)),'client gets no internal membership');
select pg_temp.ok(jsonb_array_length(public.read_client_portal_scope(pg_temp.uid(103))->'properties')=1,'client sees assigned property only');
select pg_temp.ok(public.read_client_portal_scope(pg_temp.uid(103))->'properties'->0->>'id'=pg_temp.uid(11)::text,'exact assignment retained');
select pg_temp.ok(public.read_client_access(pg_temp.uid(103))->>'state'='forbidden','client cannot read staff directory');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(204),pg_temp.uid(103),pg_temp.invite(),repeat('b',64))->>'state'='forbidden','client cannot grant access');
select pg_temp.denied($q$update public.profiles set org_id=pg_temp.uid(1),role='admin'where id=pg_temp.uid(103)$q$,'even privileged onboarding cannot elevate a client');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(205),pg_temp.uid(101),jsonb_build_object('operation','update','targetId',pg_temp.uid(103),'revision',1,'propertyIds',jsonb_build_array(pg_temp.uid(12))))->>'state'='saved','admin changes assignment');
select pg_temp.ok(public.read_client_portal_scope(pg_temp.uid(103))->'properties'->0->>'id'=pg_temp.uid(12)::text,'old assignment removed immediately');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(206),pg_temp.uid(101),jsonb_build_object('operation','revoke','targetId',pg_temp.uid(103),'revision',1))->>'state'='changed','stale revision cannot revoke');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(206),pg_temp.uid(101),jsonb_build_object('operation','revoke','targetId',pg_temp.uid(103),'revision',2))->>'state'='saved','current revision revokes');
select pg_temp.ok(public.read_client_portal_scope(pg_temp.uid(103))->>'state'='forbidden','revocation fences existing account immediately');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(207),pg_temp.uid(101),jsonb_build_object('operation','update','targetId',pg_temp.uid(103),'revision',3,'propertyIds',jsonb_build_array(pg_temp.uid(11))))->>'state'='saved','explicit staff decision restores client access');
select pg_temp.ok((select count(*)=5 from public.client_portal_access_events where org_id=pg_temp.uid(1)),'exact committed access decisions recorded once');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.uid(103)::text,true);
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid(103),'role','authenticated')::text,true);
set local role authenticated;
select pg_temp.ok(public.client_portal_identity()->>'kind'='client','signed in client identifies own role');
select pg_temp.ok((select count(*)=1 from public.client_portal_accounts),'identity table hides all other client accounts');
select pg_temp.ok((select count(*)=0 from public.properties where id in(pg_temp.uid(11),pg_temp.uid(12),pg_temp.uid(13))),'client cannot read internal properties directly');
select pg_temp.denied('select *from public.client_portal_property_access','client cannot query private grant table');
select pg_temp.denied('select *from public.client_portal_invitations','client cannot read invitations');
select pg_temp.denied('select *from public.client_portal_access_events','client cannot read internal access history');
select pg_temp.denied('select public.read_client_portal_scope(pg_temp.uid(104))','direct RPC cannot impersonate another client');
select pg_temp.denied('select public.decide_client_access(pg_temp.uid(208),pg_temp.uid(101),pg_temp.invite(),repeat(''b'',64))','direct RPC cannot impersonate admin');
select pg_temp.denied('update public.profiles set org_id=pg_temp.uid(1),role=''admin''where id=pg_temp.uid(103)','browser cannot elevate profile');
reset role;
update auth.users set email_confirmed_at=null where id=pg_temp.uid(104);
select pg_temp.ok(public.decide_client_access(pg_temp.uid(209),pg_temp.uid(101),pg_temp.invite(pg_temp.uid(11),'portal-104@fixture.invalid'),repeat('b',64))->>'state'='saved','prepare unverified recipient');
select pg_temp.ok(public.join_client_portal(pg_temp.uid(210),pg_temp.uid(104),repeat('b',64),true)->>'state'='recipient_required','unverified recipient cannot join');
update auth.users set email_confirmed_at=now()where id=pg_temp.uid(104);
update auth.users set banned_until=now()+interval'1 day'where id=pg_temp.uid(101);
select pg_temp.ok(public.join_client_portal(pg_temp.uid(210),pg_temp.uid(104),repeat('b',64),true)->>'state'='unavailable','banned issuer invitation rejected');
update auth.users set banned_until=null where id=pg_temp.uid(101);
update public.client_portal_invitations set expires_at=now()-interval'1 day'where id=pg_temp.uid(209);
select pg_temp.ok(public.join_client_portal(pg_temp.uid(210),pg_temp.uid(104),repeat('b',64),true)->>'state'='unavailable','expired invitation rejected');
update auth.users set banned_until=now()+interval'1 day'where id=pg_temp.uid(103);
select pg_temp.ok(public.read_client_portal_scope(pg_temp.uid(103))->>'state'='forbidden','banned client session rejected');
set local role anon;
select pg_temp.denied('select public.client_portal_identity()','anonymous identity reads denied');
select pg_temp.denied('select *from public.client_portal_accounts','anonymous directory denied');
reset role;
select n as passed_assertions from assertions;
rollback;
