begin;
create temp table checks(n int);insert into checks values(0);
create temp table stash(k text primary key,v jsonb);
create function pg_temp.ok(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update checks set n=n+1;end$$;
create function pg_temp.uid(n int)returns uuid language sql as $$select('ed610001-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.denied(statement text,label text)returns void language plpgsql as $$declare rejected boolean:=false;begin begin execute statement;exception when insufficient_privilege then rejected:=true;end;perform pg_temp.ok(rejected,label);end$$;
insert into public.organizations(id,name)values(pg_temp.uid(1),'Delivery fixture'),(pg_temp.uid(2),'Other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.uid(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','delivery-'||n||'@fixture.invalid',now(),now(),now()from generate_series(101,105)n;
insert into public.profiles(id,org_id,role,full_name)select pg_temp.uid(n),case when n=105 then null when n=104 then pg_temp.uid(2)else pg_temp.uid(1)end,case when n in(103,105)then'viewer'else'admin'end,'Delivery fixture '||n from generate_series(101,105)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name,address)values(pg_temp.uid(11),pg_temp.uid(1),'Delivery property','{}'),(pg_temp.uid(12),pg_temp.uid(1),'Unassigned property','{}'),(pg_temp.uid(13),pg_temp.uid(2),'Other property','{}');
insert into public.leads(id,org_id,property_id,first_name,last_name,email,source,created_at)values(pg_temp.uid(21),pg_temp.uid(1),pg_temp.uid(11),'Taylor','Fixture','delivery-lead@fixture.invalid','organic',now()-interval'10 days'),(pg_temp.uid(22),pg_temp.uid(2),pg_temp.uid(13),'Other','Fixture','other@fixture.invalid','paid',now()-interval'10 days');
insert into public.tours(id,lead_id,property_id,tour_date,tour_time,status)values(pg_temp.uid(31),pg_temp.uid(21),pg_temp.uid(11),current_date-1,'12:00','completed');
insert into public.tour_bookings(id,lead_id,property_id,scheduled_date,scheduled_time,status)values(pg_temp.uid(32),pg_temp.uid(21),pg_temp.uid(11),current_date-1,'12:00','completed');
create function pg_temp.command(n int,input jsonb,a int default 101,p int default 11)returns jsonb language sql as $$select public.decide_delivery(pg_temp.uid(n),pg_temp.uid(a),pg_temp.uid(p),input)$$;
create function pg_temp.outcome(stage text default'lease',revision int default null,reference text default'Leasing report reviewed',lead int default 21)returns jsonb language sql as $$select jsonb_build_object('operation','outcomes','rows',jsonb_build_array(jsonb_build_object('leadId',pg_temp.uid(lead),'stage',stage,'occurredOn',current_date-1,'source','staff_reported','reference',reference,'revision',revision,'reason',case when revision is not null then'Corrected after source review'else''end)))$$;
create function pg_temp.work()returns jsonb language sql as $$select jsonb_build_object('operation','work_save','targetId',null,'revision',null,'title','Improve property discovery','product','siteforge','playbook','website_improvement','ownerId',pg_temp.uid(101),'dueOn',current_date+7,'nextStep','Prepare a reviewed website brief','proposal','Correct the location page and measure visibility after release','clientSummary','Improved local property information','baselineEvent',pg_temp.uid(41))$$;
create function pg_temp.event(n int,product text,action text,property_n int default 11)returns void language plpgsql as $$begin
 insert into public.shared_action_episodes(id,org_id,property_id,actor_id,origin)values(pg_temp.uid(n),pg_temp.uid(case when property_n=13 then 2 else 1 end),pg_temp.uid(property_n),pg_temp.uid(101),'console');
 insert into public.shared_action_events(id,episode_id,org_id,property_id,actor_id,product,action,evidence,phase,request,result,created_at)values(pg_temp.uid(n),pg_temp.uid(n),pg_temp.uid(case when property_n=13 then 2 else 1 end),pg_temp.uid(property_n),pg_temp.uid(101),product,action,'server_confirmed','succeeded','{}','{}',clock_timestamp());end$$;
create function pg_temp.transition(n int,status text,rev int,e int default null)returns jsonb language sql as $$select pg_temp.command(n,jsonb_build_object('operation','work_transition','targetId',pg_temp.uid(301),'revision',rev,'status',status,'nextStep','Review the retained evidence and next observation','evidenceId',pg_temp.uid(e)))$$;
grant all on checks,stash to service_role,authenticated,anon;
set local role service_role;
select pg_temp.ok(public.read_delivery_workspace(pg_temp.uid(104),pg_temp.uid(11))->>'state'='forbidden','cross tenant board denied');
select pg_temp.ok(public.read_delivery_workspace(pg_temp.uid(103),pg_temp.uid(11))->>'state'='ready','internal viewer can read');
select pg_temp.ok(pg_temp.command(201,pg_temp.outcome(),103)->>'state'='forbidden','viewer cannot change outcomes');
select pg_temp.ok(pg_temp.command(201,pg_temp.outcome(),104)->>'state'='forbidden','cross tenant write denied');
select pg_temp.ok(pg_temp.command(201,pg_temp.outcome())->>'state'='saved','record outcome');
select pg_temp.ok(pg_temp.command(201,pg_temp.outcome())->>'state'='replayed','lost reply replay is stable');
select pg_temp.ok(pg_temp.command(201,pg_temp.outcome('application'))->>'state'='request_conflict','request cannot change meaning');
select pg_temp.ok(pg_temp.command(202,pg_temp.outcome())->>'state'='saved','exact duplicate is harmless');
select pg_temp.ok((select count(*)=1 from public.delivery_outcomes where property_id=pg_temp.uid(11)),'one canonical outcome');
select pg_temp.ok(pg_temp.command(203,pg_temp.outcome('lease',null,'Another report'))->>'state'='duplicate_outcome','conflicting duplicate held');
select pg_temp.ok(pg_temp.command(203,pg_temp.outcome('lease',2,'Another report'))->>'state'='changed','stale correction held');
select pg_temp.ok(pg_temp.command(203,pg_temp.outcome('lease',1,'Corrected report'))->>'state'='saved','current correction retained');
select pg_temp.ok(public.read_delivery_receipt(pg_temp.uid(102),pg_temp.uid(11),pg_temp.uid(201))->>'state'='not_recorded','receipt actor scoped');
select pg_temp.ok(public.read_delivery_receipt(pg_temp.uid(101),pg_temp.uid(11),pg_temp.uid(201))->>'state'='replayed','owner can recover');
select pg_temp.ok(private.delivery_funnel(pg_temp.uid(11),current_date-29,current_date)->>'booked'='1','two native tour sources count once');
select pg_temp.ok(private.delivery_funnel(pg_temp.uid(11),current_date-29,current_date)->>'attended'='1','attended deduplicates');
select pg_temp.ok(private.delivery_funnel(pg_temp.uid(11),current_date-29,current_date)->>'leases'='1','reported lease counted');
select pg_temp.ok(private.delivery_funnel(pg_temp.uid(11),current_date-29,current_date)->>'applications'='0','earlier stages not inferred');
select pg_temp.ok(pg_temp.command(204,jsonb_build_object('operation','outcomes','rows',(pg_temp.outcome('application')->'rows')||(pg_temp.outcome('booked',null,'Other record',22)->'rows')))->>'state'='invalid_lead','invalid batch refused');
select pg_temp.ok(not exists(select 1 from public.delivery_outcomes where property_id=pg_temp.uid(11)and stage='application'),'invalid batch atomic');
select pg_temp.ok(pg_temp.command(205,jsonb_build_object('operation','outcome_withdraw','targetId',(select id from public.delivery_outcomes where property_id=pg_temp.uid(11)),'revision',2,'reason','Lease report was withdrawn'))->>'state'='saved','withdraw keeps history');
select pg_temp.ok(private.delivery_funnel(pg_temp.uid(11),current_date-29,current_date)->>'leases'='0','withdrawal excludes reported lease');
select pg_temp.ok(pg_temp.command(206,'{"operation":"cancel_request"}')->>'status'='cancelled','unused request closes');
select pg_temp.ok(pg_temp.command(206,pg_temp.outcome('application'))->>'status'='cancelled','late command fenced after closure');
select pg_temp.ok(pg_temp.command(201,'{"operation":"cancel_request"}')->>'state'='replayed','closing cannot erase prior save');
select pg_temp.event(41,'propertyaudit','audit.evaluation.applied');
select pg_temp.ok(pg_temp.command(301,pg_temp.work()||'{"baselineEvent":null}')->>'state'='baseline_required','website work requires audit baseline');
select pg_temp.ok(pg_temp.command(301,pg_temp.work())->>'state'='saved','create owned website work');
select pg_temp.ok(pg_temp.transition(302,'approved',1)->>'state'='invalid_transition','cannot skip review');
select pg_temp.ok(pg_temp.transition(302,'review',1)->>'state'='saved','proposal goes to review');
select pg_temp.ok(pg_temp.transition(303,'approved',1)->>'state'='changed','stale work review held');
select pg_temp.ok(pg_temp.transition(303,'approved',2)->>'state'='saved','approve current version');
select pg_temp.ok(pg_temp.transition(304,'released',3,41)->>'state'='invalid_evidence','audit cannot impersonate release');
select pg_temp.event(42,'siteforge','site.delivery.reviewed');
select pg_temp.ok(pg_temp.transition(304,'released',3,42)->>'state'='saved','release links reviewed SiteForge evidence');
select pg_temp.ok(pg_temp.transition(305,'measured',4,41)->>'state'='invalid_evidence','old baseline cannot count as remeasurement');
select pg_temp.event(43,'propertyaudit','audit.evaluation.applied');
select pg_temp.ok(pg_temp.transition(305,'measured',4,43)->>'state'='saved','new measurement closes loop');
select pg_temp.ok(pg_temp.command(306,pg_temp.work()||jsonb_build_object('targetId',pg_temp.uid(301),'revision',5))->>'state'='closed_work','completed evidence cannot be rewritten');
insert into stash values('assessment','{"model":"Existing model fixture","factual":true,"brand":false,"complete":true,"score":3,"corrections":"Brand tone needed correction","baselineMinutes":60,"deliveryMinutes":20,"reviewMinutes":10,"correctionMinutes":5,"costUsd":null}');
select pg_temp.ok(pg_temp.command(307,jsonb_build_object('operation','quality_review','targetId',pg_temp.uid(301),'revision',5,'evidenceId',pg_temp.uid(42),'assessment',(select v from stash where k='assessment')))->>'state'='saved','quality tied to actual saved product evidence');
select pg_temp.ok(pg_temp.command(308,jsonb_build_object('operation','quality_review','targetId',pg_temp.uid(301),'revision',4,'evidenceId',pg_temp.uid(42),'assessment',(select v from stash where k='assessment')))->>'state'='changed','stale artifact assessment rejected');
select pg_temp.ok(pg_temp.command(401,jsonb_build_object('operation','report_draft','month',to_char(current_date,'YYYY-MM')))->>'state'='incomplete_month','partial month cannot be monthly report');
insert into stash values('draft',pg_temp.command(401,jsonb_build_object('operation','report_draft','month',to_char(current_date-interval'1 month','YYYY-MM'))));
select pg_temp.ok((select v->>'state'='saved'from stash where k='draft'),'monthly draft saved');
select pg_temp.ok(pg_temp.command(402,jsonb_build_object('operation','report_draft','month',to_char(current_date-interval'1 month','YYYY-MM')))->>'existing'='true','one draft per month');
select pg_temp.ok((select count(*)=1 from public.delivery_reports where property_id=pg_temp.uid(11)),'monthly retries do not duplicate');
select pg_temp.ok(public.decide_client_access(pg_temp.uid(501),pg_temp.uid(101),jsonb_build_object('operation','invite','name','Client fixture','email','delivery-105@fixture.invalid','propertyIds',jsonb_build_array(pg_temp.uid(11))),repeat('b',64))->>'state'='saved','client invitation');
select pg_temp.ok(public.join_client_portal(pg_temp.uid(502),pg_temp.uid(105),repeat('b',64),true)->>'state'='joined','client accepts');
select pg_temp.ok(jsonb_array_length(public.read_published_delivery_reports(pg_temp.uid(105))->'reports')=0,'draft invisible to client');
select pg_temp.ok(public.read_client_delivery(pg_temp.uid(105),pg_temp.uid(12),current_date-29,current_date)->>'state'='forbidden','client unassigned property denied');
select pg_temp.ok(public.read_client_delivery(pg_temp.uid(105),pg_temp.uid(11),current_date-29,current_date)->>'state'='ready','assigned client receives safe aggregate');
select pg_temp.ok(public.read_delivery_workspace(pg_temp.uid(105),pg_temp.uid(11))->>'state'='forbidden','client cannot inspect staff workspace');
select pg_temp.ok(public.read_delivery_report(pg_temp.uid(105),pg_temp.uid(11),(select(v->>'targetId')::uuid from stash where k='draft'))->>'state'='forbidden','client cannot read unpublished snapshot');
select pg_temp.ok(pg_temp.command(403,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',1,'status','approved'))->>'state'='summary_required','blank report cannot be approved');
select pg_temp.ok(pg_temp.command(403,jsonb_build_object('operation','report_edit','targetId',(select v->>'targetId'from stash where k='draft'),'revision',1,'summary','This is the reviewed monthly summary.','nextSteps','Review campaign and leasing evidence.'))->>'state'='saved','narrative saves');
select pg_temp.ok(pg_temp.command(404,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',2,'status','published'))->>'state'='invalid_transition','publication requires prior approval');
select pg_temp.ok(pg_temp.command(404,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',2,'status','approved'))->>'state'='saved','approve narrative and frozen snapshot');
select pg_temp.ok(pg_temp.command(405,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',2,'status','published'))->>'state'='changed','stale publication held');
select pg_temp.ok(pg_temp.command(405,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',3,'status','published'))->>'state'='saved','publish approved version');
select pg_temp.ok(jsonb_array_length(public.read_published_delivery_reports(pg_temp.uid(105))->'reports')=1,'only published report visible');
select pg_temp.ok(public.read_published_delivery_reports(pg_temp.uid(105))#>>'{reports,0,summary}'='This is the reviewed monthly summary.','client sees reviewed narrative');
select pg_temp.ok(public.read_published_delivery_reports(pg_temp.uid(105))::text not like'%delivery-lead@fixture.invalid%','client reports contain no lead contact details');
select pg_temp.ok(pg_temp.command(406,jsonb_build_object('operation','report_refresh','targetId',(select v->>'targetId'from stash where k='draft'),'revision',4))->>'state'='published_report','cannot refresh a live report silently');
select pg_temp.ok(pg_temp.command(406,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',4,'status','withdrawn'))->>'state'='saved','withdraw published report');
select pg_temp.ok(jsonb_array_length(public.read_published_delivery_reports(pg_temp.uid(105))->'reports')=0,'withdrawal removes client visibility');
select pg_temp.ok(pg_temp.command(407,jsonb_build_object('operation','report_refresh','targetId',(select v->>'targetId'from stash where k='draft'),'revision',5))->>'state'='saved','refresh retains a new immutable BI snapshot');
select pg_temp.ok((select count(*)=2 from public.bi_reports where property_id=pg_temp.uid(11)),'original and refreshed snapshots retained');
select pg_temp.ok((select state='draft'and approved_by is null and revision=6 from public.delivery_reports where property_id=pg_temp.uid(11)),'refresh clears prior approval');
select pg_temp.ok(pg_temp.command(408,'{"operation":"report_policy","revision":null,"enabled":true}')->>'state'='saved','enable draft policy');
select pg_temp.ok(jsonb_array_length(public.draft_due_client_reports()->'results')=0,'worker skips existing month');
select pg_temp.ok(pg_temp.command(409,'{"operation":"report_policy","revision":null,"enabled":false}')->>'state'='changed','stale policy update held');
select pg_temp.ok((select count(*)from public.delivery_commands where property_id=pg_temp.uid(11))=(select count(*)from public.shared_action_events where property_id=pg_temp.uid(11)and action like'delivery.%'),'every successful command has one atomic action event');
select pg_temp.ok((select bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.uid(11)),'records are not training exports');

select pg_temp.ok(pg_temp.command(410,'{"operation":"report_policy","revision":null,"enabled":true}',101,12)->>'state'='saved','second property enables scheduled drafting');
select pg_temp.ok(jsonb_array_length(public.draft_due_client_reports()->'results')=1,'worker prepares only missing opted-in month');
select pg_temp.ok((select count(*)=1 from public.delivery_reports where property_id=pg_temp.uid(12)and state='draft'),'worker never publishes');
select pg_temp.ok((select count(*)=1 from public.shared_action_events where property_id=pg_temp.uid(12)and action='delivery.report_draft'and actor_id is null and service_principal='client-report-drafts'),'scheduled action is attributed to background service');
select pg_temp.ok(jsonb_array_length(public.draft_due_client_reports()->'results')=0,'worker rerun remains idempotent');
select pg_temp.ok(pg_temp.command(411,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',6,'status','approved'),102)->>'state'='saved','second manager approves current report');
reset role;
update auth.users set banned_until=now()+interval'1 day'where id=pg_temp.uid(102);
set local role service_role;
select pg_temp.ok(pg_temp.command(412,jsonb_build_object('operation','report_transition','targetId',(select v->>'targetId'from stash where k='draft'),'revision',7,'status','published'))->>'state'='approval_expired','approval loses authority when reviewer is banned');
select pg_temp.ok(public.read_client_delivery(pg_temp.uid(105),pg_temp.uid(11),current_date,current_date-1)->>'state'='invalid_input','invalid aggregate periods rejected');
select pg_temp.ok(public.read_published_delivery_reports(pg_temp.uid(105),pg_temp.uid(12))->>'state'='forbidden','global report pagination cannot request unassigned property');
select pg_temp.ok(public.read_delivery_workspace(pg_temp.uid(101),pg_temp.uid(11),'{"search":"%_"}')#>>'{leads}'='[]','search wildcard is literal');
reset role;
update auth.users set banned_until=now()+interval'1 day'where id=pg_temp.uid(101);
set local role service_role;
select pg_temp.ok(public.read_delivery_workspace(pg_temp.uid(101),pg_temp.uid(11))->>'state'='forbidden','banned current session cannot read');
select pg_temp.ok(pg_temp.command(201,pg_temp.outcome())->>'state'='forbidden','replay rechecks access');
select pg_temp.ok(public.read_delivery_receipt(pg_temp.uid(101),pg_temp.uid(11),pg_temp.uid(201))->>'state'='forbidden','recovery rechecks access');
reset role;
set local role authenticated;
select pg_temp.denied('select *from public.delivery_outcomes','browser cannot directly read outcomes');
select pg_temp.denied('select *from public.delivery_reports','browser cannot bypass publication');
select pg_temp.denied('select public.decide_delivery(pg_temp.uid(201),pg_temp.uid(101),pg_temp.uid(11),pg_temp.outcome())','browser cannot impersonate actor');
select pg_temp.denied('select public.read_client_delivery(pg_temp.uid(105),pg_temp.uid(11),current_date-29,current_date)','client cannot impersonate another client');
reset role;
select n as passed_assertions from checks;
rollback;
