BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee860000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'Console search SQL fixture'),(pg_temp.i(2),'Console search other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','console-search-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,103)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,103)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'Console search SQL property'),(pg_temp.i(202),pg_temp.i(2),'Console search other property');
insert into public.leads(id,property_id,first_name,last_name,email,source,status)select pg_temp.i(1000+n),pg_temp.i(201),'Needle',n::text,'private-'||n||'@fixture.invalid','fixture','new'from generate_series(1,1005)n;
insert into public.leads(id,property_id,first_name,last_name,source,status)values(pg_temp.i(301),pg_temp.i(201),'Literal%_,','(Original)','fixture','new'),(pg_temp.i(302),pg_temp.i(202),'Needle','Other tenant','fixture','new');
insert into public.documents(id,property_id,content,metadata)select pg_temp.i(3000+n),pg_temp.i(201),'Retained text '||n,jsonb_build_object('title','Retained document '||n)from generate_series(1,65)n;
insert into public.documents(id,property_id,content,metadata)values(pg_temp.i(3070),pg_temp.i(201),'Exact unmatched earlier text with Needle at the end.','{"title":"Late stored source"}');
insert into public.conversations(id,property_id,lead_id,channel)values(pg_temp.i(401),pg_temp.i(201),pg_temp.i(301),'widget'),(pg_temp.i(402),pg_temp.i(202),pg_temp.i(302),'widget');
insert into public.messages(conversation_id,role,content)values(pg_temp.i(401),'user','Needle in this original conversation'),(pg_temp.i(402),'user','Needle other tenant');
create function pg_temp.decide(n int,input jsonb,actor int default 101)returns jsonb language sql as $$select public.decide_console_search(pg_temp.i(n),pg_temp.i(actor),pg_temp.i(201),input)$$;
set local role service_role;
select pg_temp.check_it(pg_temp.decide(501,'{"operation":"search","query":"Needle","filter":"all"}',103)->>'state'='forbidden','other tenant cannot search');
select pg_temp.check_it(pg_temp.decide(501,'{"operation":"search","query":"N","filter":"all"}')->>'state'='invalid_input','short query rejected');
select pg_temp.check_it(pg_temp.decide(501,'{"operation":"search","query":"Needle","filter":"all","extra":true}')->>'state'='invalid_input','unknown fields rejected');
select public.save_knowledge_material(pg_temp.i(450),pg_temp.i(201),pg_temp.i(101),'{"materialId":null,"previousVersionId":null,"title":"Reviewed Needle","content":"Private retained knowledge original.","reason":"Synthetic source"}');
insert into st values('search',pg_temp.decide(501,'{"operation":"search","query":"Needle","filter":"all"}'));
select pg_temp.check_it((select v->>'status'='searched'and(v->>'count')::int=1008 from st where k='search'),'full scoped source search exceeds REST and former sample limits');
select pg_temp.check_it((select jsonb_array_length(sources)=1008 from public.console_search_commands where id=pg_temp.i(501)),'complete exact matching originals retained');
select pg_temp.check_it(pg_temp.decide(501,'{"operation":"search","query":"Needle","filter":"all"}')=(select v from st where k='search'),'lost search response replays exact result');
select pg_temp.check_it(pg_temp.decide(501,'{"operation":"search","query":"different","filter":"all"}')->>'state'='request_conflict','identity cannot change query');
select pg_temp.check_it((select count(*)=1 from public.shared_action_events where id=pg_temp.i(501)),'replay has one shared action');
select pg_temp.check_it((select request::text not like'%Needle%'and result::text not like'%private%'and not training_eligible from public.shared_action_events where id=pg_temp.i(501)),'shared event has no query or source and no training permission');
insert into st values('page',public.read_console_search(pg_temp.i(101),pg_temp.i(201),'results',pg_temp.i(501)));
select pg_temp.check_it((select jsonb_array_length(v->'items')=20 and(v->>'total')::int=1008 from st where k='page'),'bounded page exposes full count');
select pg_temp.check_it((select not((v->'items'->0)?'source')from st where k='page'),'list excludes full private originals');
select pg_temp.check_it(public.read_console_search(pg_temp.i(102),pg_temp.i(201),'results',pg_temp.i(501))->>'state'='not_found','colleague cannot read personal query history');
select pg_temp.check_it(pg_temp.decide(502,'{"operation":"search","query":"Literal%_, (Original)","filter":"lead"}',102)->>'count'='1','viewer can search literal punctuation without wildcard/filter injection');
select pg_temp.check_it(pg_temp.decide(503,'{"operation":"search","query":"Needle","filter":"knowledge"}')->>'count'='2','knowledge filter includes later stored document and reviewed material');
select pg_temp.check_it(pg_temp.decide(504,jsonb_build_object('operation','select','searchId',pg_temp.i(503),'key','document:'||pg_temp.i(3070)))->>'current'='true','selected saved source matches current original');
update public.documents set content='Corrected current body'where id=pg_temp.i(3070);
select pg_temp.check_it(pg_temp.decide(505,jsonb_build_object('operation','select','searchId',pg_temp.i(503),'key','document:'||pg_temp.i(3070)))->>'current'='false','current change labeled explicitly');
select pg_temp.check_it(public.read_console_search(pg_temp.i(101),pg_temp.i(201),'command',pg_temp.i(505))->'source'->'source'->>'content'='Exact unmatched earlier text with Needle at the end.','historical exact source unchanged');
select pg_temp.check_it(pg_temp.decide(506,jsonb_build_object('operation','navigate','searchId',pg_temp.i(503),'key','document:'||pg_temp.i(3070)))->>'url'like'/dashboard/community?knowledgeGroup=%','stored source link names real knowledge group');
select pg_temp.check_it(pg_temp.decide(507,jsonb_build_object('operation','navigate','searchId',pg_temp.i(503),'key','material:'||pg_temp.i(450)))->>'url'like'%knowledgeVersion='||pg_temp.i(450),'reviewed source link pins original version');
select pg_temp.check_it(pg_temp.decide(508,jsonb_build_object('operation','navigate','searchId',pg_temp.i(501),'key','lead:'||pg_temp.i(1001)))->>'url'='/dashboard/leads?lead='||pg_temp.i(1001),'lead destination carries exact identity');
select pg_temp.check_it(pg_temp.decide(509,jsonb_build_object('operation','navigate','searchId',pg_temp.i(501),'key','conversation:'||pg_temp.i(401)))->>'url'='/dashboard/lumaleasing?tab=conversations&conversation='||pg_temp.i(401),'conversation destination uses actual inbox');
select pg_temp.check_it(pg_temp.decide(510,jsonb_build_object('operation','select','searchId',pg_temp.i(501),'key','lead:'||pg_temp.i(302)))->>'state'='not_found','unmatched foreign result cannot be selected');
select pg_temp.check_it(pg_temp.decide(511,'{"operation":"cancel"}')->>'status'='cancelled','unused request cancelled');
select pg_temp.check_it(pg_temp.decide(511,'{"operation":"search","query":"Needle","filter":"all"}')->>'status'='cancelled','cancellation fences delayed query');
select pg_temp.check_it(pg_temp.decide(501,'{"operation":"cancel"}')->>'status'='searched','cancel cannot erase completed evidence');
select pg_temp.throws('UPDATE public.console_search_commands SET input=''{}''WHERE id='''||pg_temp.i(501)||'''','original query immutable');
select pg_temp.throws('DELETE FROM public.console_search_commands WHERE id='''||pg_temp.i(501)||'''','original query cannot be deleted directly');
select pg_temp.check_it(not has_table_privilege('authenticated','public.console_search_commands','SELECT'),'private search ledger has no direct viewer grant');
select pg_temp.check_it(not has_function_privilege('authenticated','public.decide_console_search(uuid,uuid,uuid,jsonb)','EXECUTE'),'mutations native service only');
select pg_temp.check_it(public.read_console_search(pg_temp.i(101),pg_temp.i(201),'results',pg_temp.i(501),1000,(select v->>'hash'from st where k='page'))->>'total'='1008','last page reachable beyond REST cap');
insert into public.leads(property_id,first_name,last_name,source,status)select pg_temp.i(201),'Needle','Extra '||n,'fixture','new'from generate_series(1,1000)n;
select pg_temp.check_it(pg_temp.decide(512,'{"operation":"search","query":"Needle","filter":"all"}')->>'status'='narrow_query','broad search is explicitly held rather than truncated');
select pg_temp.check_it(public.read_console_search(pg_temp.i(101),pg_temp.i(201),'results',pg_temp.i(501),0,(select v->>'hash'from st where k='page'))->>'total'='1008','later inserts cannot alter saved result pages');
do $$begin for n in 600..624 loop perform pg_temp.decide(n,'{"operation":"cancel"}');end loop;end$$;
insert into st values('history',public.read_console_search(pg_temp.i(101),pg_temp.i(201),'history'));
select pg_temp.check_it((select(v->>'total')::int>20 and jsonb_array_length(v->'items')=20 from st where k='history'),'complete history count and first page');
select pg_temp.check_it(jsonb_array_length(public.read_console_search(pg_temp.i(101),pg_temp.i(201),'history',null,20,(select v->>'hash'from st where k='history'))->'items')>0,'later history pages reachable');
create function pg_temp.reject_action()returns trigger language plpgsql as $$begin if new.id=pg_temp.i(530)then raise exception 'Fixture action failure';end if;return new;end$$;
reset role;create trigger search_fixture_reject before insert on public.shared_action_events for each row execute function pg_temp.reject_action();set local role service_role;
select pg_temp.throws('select pg_temp.decide(530,''{"operation":"search","query":"Unique no result","filter":"all"}'')','action failure rolls back search');
select pg_temp.check_it(not exists(select 1 from public.console_search_commands where id=pg_temp.i(530)),'failed action leaves no orphan query');
reset role;drop trigger search_fixture_reject on public.shared_action_events;
set local role service_role;
reset role;
select 'Assertions passed: '||n from assertion_count;
ROLLBACK;
