begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,lead_ids uuid[],batch_id uuid,approval_id uuid,stop_id uuid);
insert into fixture select gen_random_uuid(),id,array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()],gen_random_uuid(),gen_random_uuid(),gen_random_uuid() from public.profiles where org_id='22222222-2222-2222-2222-222222222222' and role='admin' limit 1;
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','CRM bulk rollback fixture' from fixture;
insert into public.leads(id,property_id,first_name,email)select x.id,f.property_id,'Bulk lead '||x.n,case when x.n<4 then 'bulk-private-'||x.n||'@fixture.invalid' else null end from fixture f cross join lateral unnest(f.lead_ids) with ordinality x(id,n);
do $$declare f fixture;c public.integration_credentials;preview uuid:=gen_random_uuid();receipt uuid:=gen_random_uuid();r jsonb;begin
 select * into f from fixture;
 perform public.save_crm_mapping_review(f.property_id,f.actor_id,gen_random_uuid(),'lasso',0,'{"api_key":"local-bulk-secret"}','{"first_name":"first_name","email":"email"}');
 select * into c from public.integration_credentials where property_id=f.property_id;
 perform public.preview_crm_mapping(f.property_id,f.actor_id,preview,c.id,c.crm_revision);perform public.approve_crm_mapping(f.property_id,f.actor_id,gen_random_uuid(),preview);
 insert into public.crm_validation_receipts(id,property_id,integration_id,revision,credentials_hash,mapping_hash,provider_identity,capabilities,evidence,state)values(receipt,f.property_id,c.id,c.crm_revision,public.crm_configuration_hash(c.credentials),public.crm_configuration_hash(c.field_mapping),'{"fixture":true}','{"fixture":true,"leadSearch":true,"leadRead":true,"leadWrite":true}','{"simulated":true}','verified');
 update public.integration_credentials set crm_validation_receipt_id=receipt,mapping_validated=true,status='connected' where id=c.id;
 perform pg_temp.check(public.prepare_crm_bulk(f.property_id,gen_random_uuid(),f.batch_id,f.lead_ids)->>'state'='forbidden','current actor required');
 perform pg_temp.check(public.prepare_crm_bulk(f.property_id,f.actor_id,f.batch_id,array[f.lead_ids[1],gen_random_uuid()])->>'state'='selection_changed','entire selection scope validated first');
 perform pg_temp.check(not exists(select 1 from public.crm_handoffs where property_id=f.property_id),'bad selection creates no partial handoffs');
 begin perform public.prepare_crm_bulk(f.property_id,f.actor_id,f.batch_id,array[f.lead_ids[1],f.lead_ids[1]]);raise exception 'FAIL accepted duplicates';exception when raise_exception then if SQLERRM<>'Duplicate lead selection' then raise;end if;end;
 perform pg_temp.check(public.prepare_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.lead_ids)->>'state'='saved','saves selection and exact child transfers');
 perform pg_temp.check(public.prepare_crm_bulk(f.property_id,f.actor_id,f.batch_id,array[f.lead_ids[4],f.lead_ids[2],f.lead_ids[1],f.lead_ids[3]])->>'state'='replayed','selection order cannot duplicate request');
 perform pg_temp.check(public.prepare_crm_bulk(f.property_id,f.actor_id,f.batch_id,array[f.lead_ids[1]])->>'state'='request_conflict','saved identity cannot change selected leads');
 perform pg_temp.check((select count(*)=3 from public.crm_handoffs where property_id=f.property_id),'missing contact excluded without executable transfer');
 perform pg_temp.check(public.read_crm_bulk(f.property_id,f.actor_id,f.batch_id)->'counts'='{"queued":3,"contact_required":1}'::jsonb,'batch has honest prepared and excluded counts');
 perform pg_temp.check(public.read_crm_bulk(f.property_id,f.actor_id)->>'total'='1','reload recovers saved batch');
 perform pg_temp.check(public.read_crm_bulk(f.property_id,gen_random_uuid(),f.batch_id)->>'state'='forbidden','batch values require current property membership');
 perform pg_temp.check(public.read_crm_bulk(gen_random_uuid(),f.actor_id,f.batch_id)->>'state'='forbidden','cross-property batch read denied');
 perform pg_temp.check(public.search_crm_bulk_leads(f.property_id,f.actor_id,'bulk-private')->>'total'='3','property search searches actual contact');
 perform pg_temp.check(public.search_crm_bulk_leads(f.property_id,f.actor_id,',email.neq.null')->>'total'='0','search punctuation remains literal');
 perform pg_temp.check(public.search_crm_bulk_leads(f.property_id,gen_random_uuid())->>'state'='forbidden','search requires current membership');
 perform pg_temp.check(not has_table_privilege('authenticated','public.crm_bulk_batches','select') and not has_table_privilege('anon','public.crm_bulk_commands','insert'),'private batch values denied to raw browser roles');
 perform pg_temp.check(not has_function_privilege('authenticated','public.command_crm_bulk(uuid,uuid,uuid,uuid,text,text)','execute') and not has_function_privilege('anon','public.crm_bulk_snapshot(uuid,boolean)','execute'),'internal operations not browser callable');
 perform pg_temp.check((select bool_and(relrowsecurity) from pg_class where oid in('public.crm_bulk_batches'::regclass,'public.crm_bulk_commands'::regclass)),'private tables have RLS');
 perform pg_temp.check((select bool_and(not training_eligible) and bool_and(request::text not like '%bulk-private%' and result::text not like '%bulk-private%') from public.shared_action_events where property_id=f.property_id and action like 'crm.bulk.%'),'bulk semantic history excludes contact and is not training eligible');
 begin update public.crm_bulk_batches set manifest='[]' where id=f.batch_id;raise exception 'FAIL mutable manifest';exception when sqlstate '55000' then null;end;
 perform pg_temp.check((select jsonb_array_length(manifest)=4 from public.crm_bulk_batches where id=f.batch_id),'selection and saved authority immutable');
end$$;
-- Approval failure must roll back all child approvals and shared projections.
create function pg_temp.fail_bulk_history() returns trigger language plpgsql as $$begin if new.action='crm.bulk.approved' then raise exception 'Fixture bulk history failure';end if;return new;end$$;
create trigger crm_bulk_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_bulk_history();
do $$declare f fixture;hash text;begin
 select * into f from fixture;select manifest_hash into hash from public.crm_bulk_batches where id=f.batch_id;
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.approval_id,'approve','wrong')->>'state'='preview_conflict','approval is bound to manifest hash');
 update public.leads set first_name='Changed after review' where id=f.lead_ids[2];
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.approval_id,'approve',hash)->>'state'='stale_source','changed lead holds the entire unapproved batch');
 perform pg_temp.check(not exists(select 1 from public.crm_handoff_approvals where property_id=f.property_id),'stale batch leaves no partial approval');
 perform pg_temp.check(exists(select 1 from jsonb_array_elements(public.read_crm_bulk(f.property_id,f.actor_id,f.batch_id)->'items') i where i->'stale'='true'),'reload exposes stale prepared values');
 update public.leads set first_name='Bulk lead 2' where id=f.lead_ids[2];
 begin perform public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.approval_id,'approve',hash);raise exception 'FAIL history failure ignored';exception when raise_exception then if SQLERRM<>'Fixture bulk history failure' then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.crm_handoff_approvals where property_id=f.property_id),'history failure rolls back every child approval');
 perform pg_temp.check(not exists(select 1 from public.crm_bulk_commands where batch_id=f.batch_id),'history failure rolls back batch command');
 perform pg_temp.check((select bool_and(execution_approved_at is null) from public.crm_handoffs where property_id=f.property_id),'history failure leaves queue unapproved');
end$$;
drop trigger crm_bulk_fixture_failure on public.shared_action_events;
do $$declare f fixture;hash text;r jsonb;h uuid;claim uuid;begin
 select * into f from fixture;select manifest_hash into hash from public.crm_bulk_batches where id=f.batch_id;
 update public.profiles set role='viewer' where id=f.actor_id;
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.approval_id,'approve',hash)->>'state'='forbidden','role loss blocks approval');
 update public.profiles set role='admin' where id=f.actor_id;
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.approval_id,'approve',hash)->>'state'='applied','exact saved batch approves prepared children atomically');
 perform pg_temp.check((select count(*)=3 from public.crm_handoff_approvals where property_id=f.property_id),'approval covers exactly prepared children');
 perform pg_temp.check((select count(*)=3 from public.shared_approvals where property_id=f.property_id and decision_payload ? 'handoffId'),'each child retains shared approval projection');
 perform pg_temp.check(not exists(select 1 from public.crm_handoff_receipts where property_id=f.property_id),'approval alone never implies provider work');
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.approval_id,'approve',hash)->>'state'='replayed','lost approval reply is recovered without approving again');
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.approval_id,'stop',hash)->>'state'='request_conflict','approval request cannot be repurposed as stop');
 select id into h from public.crm_handoffs where lead_id=f.lead_ids[1];r:=public.claim_crm_handoff(h);claim:=(r->>'claimId')::uuid;
 perform public.record_crm_handoff_search(h,claim,true,'bulk-linked-record','email');perform public.finish_crm_handoff(h,claim,'linked','bulk-linked-record');
 select id into h from public.crm_handoffs where lead_id=f.lead_ids[2];r:=public.claim_crm_handoff(h);claim:=(r->>'claimId')::uuid;
 perform public.record_crm_handoff_search(h,claim,false);perform public.mark_crm_handoff_write(h,claim);perform public.finish_crm_handoff(h,claim,'needs_reconciliation');
 perform pg_temp.check(public.read_crm_bulk(f.property_id,f.actor_id,f.batch_id)->'counts'='{"queued":1,"confirmed":1,"needs_reconciliation":1,"contact_required":1}'::jsonb,'partial results derive from actual child outcomes');
 r:=public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.stop_id,'stop',hash);
 perform pg_temp.check(r->'result'->>'processed'='1' and r->'result'->>'uncertain'='1','stop distinguishes untouched and uncertain transfers');
 perform pg_temp.check(public.read_crm_bulk(f.property_id,f.actor_id,f.batch_id)->'counts'='{"cancelled":1,"confirmed":1,"needs_reconciliation":1,"contact_required":1}'::jsonb,'stop preserves confirmed and uncertain state');
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,f.stop_id,'stop',hash)->>'state'='replayed','lost stop response recovers stable result');
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,f.batch_id,gen_random_uuid(),'stop',hash)->>'state'='already_recorded','another stop does not duplicate history');
 perform pg_temp.check((select count(*)=2 from public.crm_bulk_commands where batch_id=f.batch_id),'one approval and one stop receipt');
 perform pg_temp.check((select state='needs_reconciliation' from public.crm_handoffs where id=h),'bulk stop cannot cancel away an uncertain write');
 perform pg_temp.check(public.mark_crm_handoff_write(h,claim)->>'state'='needs_reconciliation','recovery never releases another write');
 r:=public.prepare_crm_bulk(f.property_id,f.actor_id,gen_random_uuid(),array[f.lead_ids[1],f.lead_ids[2],f.lead_ids[4]]);
 perform pg_temp.check(public.read_crm_bulk(f.property_id,f.actor_id,(r->>'batchId')::uuid)->'counts'='{"already_linked":1,"handoff_in_progress":1,"contact_required":1}'::jsonb,'later selection truthfully excludes linked and unfinished work');
 perform pg_temp.check(public.command_crm_bulk(f.property_id,f.actor_id,(r->>'batchId')::uuid,gen_random_uuid(),'approve',public.read_crm_bulk(f.property_id,f.actor_id,(r->>'batchId')::uuid)->>'manifestHash')->>'state'='nothing_to_approve','all excluded batch cannot acquire delivery authority');
end$$;
do $$declare f fixture;r jsonb;begin
 select * into f from fixture;
 perform pg_temp.check(public.read_crm_monitor(f.property_id,gen_random_uuid())->>'state'='forbidden','overview enforces current property access');
 perform pg_temp.check(not has_function_privilege('authenticated','public.read_crm_monitor(uuid,uuid)','execute'),'browser cannot bypass overview scope');
 r:=public.read_crm_monitor(f.property_id,f.actor_id);
 perform pg_temp.check(r->'counts'->>'confirmed'='1' and r->'counts'->>'needs_reconciliation'='1','overview distinguishes one confirmed and one uncertain transfer');
 perform pg_temp.check(r->'confirmedOutcomes'='{"linked":1}'::jsonb,'overview reports verified link without inventing creation');
 insert into public.leads(property_id,first_name,external_crm_id,crm_sync_status)values(f.property_id,'Legacy fixture','old-unverified-id','created');
 r:=public.read_crm_monitor(f.property_id,f.actor_id);
 perform pg_temp.check(r->>'legacyLeads'='1' and r->'confirmedOutcomes'='{"linked":1}'::jsonb,'older status does not inflate receipt-backed outcomes');
 perform pg_temp.check(r::text not like '%local-bulk-secret%' and r::text not like '%bulk-private-%','overview omits credentials and contact values');
end$$;
select count(*) as assertions from checks;
rollback;
