begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,operation_id uuid,integration_id uuid,claim_id uuid);
insert into fixture select gen_random_uuid(),id,gen_random_uuid(),null,null from public.profiles where org_id='22222222-2222-2222-2222-222222222222' and role='admin' limit 1;
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','CRM qualification rollback fixture' from fixture;
do $$declare f fixture;c public.integration_credentials;preview uuid:=gen_random_uuid();r jsonb;hash text;begin
 select * into f from fixture;
 perform public.save_crm_mapping_review(f.property_id,f.actor_id,gen_random_uuid(),'hubspot',0,'{"api_key":"qualification-private-token"}','{"first_name":"firstname","last_name":"lastname","email":"email","property_name":"company"}');
 select * into c from public.integration_credentials where property_id=f.property_id;update fixture set integration_id=c.id;
 perform pg_temp.check(public.prepare_crm_qualification(f.property_id,f.actor_id,f.operation_id,c.id,c.crm_revision)->>'state'='mapping_approval_required','test requires approved mapping');
 perform public.preview_crm_mapping(f.property_id,f.actor_id,preview,c.id,c.crm_revision);perform public.approve_crm_mapping(f.property_id,f.actor_id,gen_random_uuid(),preview);
 perform pg_temp.check(public.prepare_crm_qualification(f.property_id,gen_random_uuid(),f.operation_id,c.id,c.crm_revision)->>'state'='forbidden','test requires current manager');
 perform pg_temp.check(public.prepare_crm_qualification(f.property_id,f.actor_id,f.operation_id,c.id,c.crm_revision)->>'state'='saved','exact synthetic test prepared');
 perform pg_temp.check(public.prepare_crm_qualification(f.property_id,f.actor_id,f.operation_id,c.id,c.crm_revision)->>'state'='replayed','lost preparation response replays');
 perform pg_temp.check(public.prepare_crm_qualification(f.property_id,f.actor_id,f.operation_id,c.id,c.crm_revision+1)->>'state'='request_conflict','request cannot change revision');
 perform pg_temp.check(public.prepare_crm_qualification(f.property_id,f.actor_id,gen_random_uuid(),c.id,c.crm_revision)->>'state'='operation_in_progress','second test cannot overlap unfinished operation');
 perform pg_temp.check((select payload->>'company'='CRM qualification rollback fixture' and payload->>'email' like 'p11-qualification-%@example.invalid' from public.crm_qualifications where id=f.operation_id),'company and unique synthetic contact are explicit saved values');
 select payload_hash into hash from public.crm_qualifications where id=f.operation_id;
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,gen_random_uuid(),'activate',hash)->>'state'='verification_required','mapping cannot activate delivery without test evidence');
 perform pg_temp.check(public.claim_crm_qualification(f.operation_id)->>'state'='prepared','unapproved test cannot be claimed');
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,gen_random_uuid(),'run','wrong')->>'state'='preview_conflict','run requires exact saved test values');
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,gen_random_uuid(),'run',hash)->>'state'='applied','explicit operator approves test and cleanup');
 r:=public.claim_crm_qualification(f.operation_id);update fixture set claim_id=(r->>'claimId')::uuid;
 perform pg_temp.check(r->>'state'='claimed' and r->'credentials'->>'api_key'='qualification-private-token','one private worker claim receives bound credentials');
 perform pg_temp.check(public.claim_crm_qualification(f.operation_id)->>'state'='running','second worker cannot claim');
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,gen_random_uuid(),'recover',hash)->>'state'='worker_pending','recovery respects original worker confirmation window');
 perform pg_temp.check(public.read_crm_qualifications(f.property_id,gen_random_uuid())->>'state'='forbidden','private test history requires current membership');
 perform pg_temp.check(public.read_crm_qualifications(f.property_id,f.actor_id)::text not like '%qualification-private-token%','test UI never exposes credentials');
 perform pg_temp.check(not has_table_privilege('authenticated','public.crm_qualifications','select') and not has_function_privilege('authenticated','public.claim_crm_qualification(uuid)','execute'),'browser cannot read private tables or claim writes');
end$$;
do $$declare f fixture;r jsonb;hash text;begin
 select * into f from fixture;select payload_hash into hash from public.crm_qualifications where id=f.operation_id;
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'create_intent','{}')->>'state'='preflight_required','create requires provider account and mapping evidence');
 perform public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'preflight','{"identity":{"id":"local-fixture-account","type":"simulated"},"contractVersion":"crm-exact-v1"}');
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'create_intent','{}')->>'state'='proceed_once','first durable creation intent permits one attempt');
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'create_intent','{}')->>'state'='replayed','lost intent reply never permits second attempt');
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,gen_random_uuid(),'stop',hash)->>'state'='cleanup_required','stop cannot erase uncertain test creation');
 begin update public.integration_credentials set credentials='{"api_key":"replacement"}' where id=f.integration_id;raise exception 'FAIL replacement allowed';exception when raise_exception then if SQLERRM<>'Resolve the unfinished CRM test record before replacing its connection' then raise;end if;end;
 perform pg_temp.check((select credentials->>'api_key'='qualification-private-token' from public.integration_credentials where id=f.integration_id),'uncertain test retains original credentials');
 r:=public.finish_crm_qualification(f.operation_id,f.claim_id);
 perform pg_temp.check(r->>'qualificationState'='needs_reconciliation','missing create acknowledgement remains held');
 perform pg_temp.check(not exists(select 1 from public.crm_validation_receipts where id=f.operation_id),'uncertain test cannot produce verified receipt');
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,gen_random_uuid(),'recover',hash)->>'state'='applied','explicit recovery requests saved test');
 r:=public.claim_crm_qualification(f.operation_id);update fixture set claim_id=(r->>'claimId')::uuid;
 perform pg_temp.check(r->'receipts' ? 'create_intent','recovery retains earlier one-write intent');
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'created','{"externalId":"fixture-record","confirmed":true}')->>'state'='claim_conflict','late previous worker is fenced');
end$$;
do $$declare f fixture;begin
 select * into f from fixture;
 perform public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'created','{"externalId":"fixture-record","confirmed":true}');
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'cleanup_intent','{"externalId":"fixture-record"}')->>'state'='exact_test_record_required','cleanup requires readback of exact saved test');
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'readback','{"externalId":"wrong-record","matches":true}')->>'state'='destination_conflict','cannot substitute destination during cleanup');
 perform public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'readback','{"externalId":"fixture-record","matches":true}');
 perform public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'search','{"externalId":"fixture-record","matches":true}');
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'cleanup_intent','{"externalId":"fixture-record"}')->>'state'='proceed_once','one cleanup attempt authorized only for original test');
 perform pg_temp.check(public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'cleanup_intent','{"externalId":"fixture-record"}')->>'state'='replayed','lost cleanup intent never issues repeated delete');
 perform public.checkpoint_crm_qualification(f.operation_id,f.claim_id,'cleanup','{"externalId":"fixture-record","absent":true}');
 perform pg_temp.check(public.finish_crm_qualification(f.operation_id,f.claim_id)->>'qualificationState'='verified','complete provider and cleanup evidence verifies lead capability');
 perform pg_temp.check((select not mapping_validated and crm_validation_receipt_id is null from public.integration_credentials where id=f.integration_id),'verified test does not automatically activate delivery');
 perform pg_temp.check((select capabilities->'noteWrite'='false' and capabilities->'leadWrite'='true' from public.crm_validation_receipts where id=f.operation_id),'lead evidence does not invent note capability');
end$$;
create function pg_temp.fail_qualification_activation() returns trigger language plpgsql as $$begin if new.action='crm.qualification.activated' then raise exception 'Fixture activation history failure';end if;return new;end$$;
create trigger crm_qualification_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_qualification_activation();
do $$declare f fixture;hash text;begin
 select * into f from fixture;select payload_hash into hash from public.crm_qualifications where id=f.operation_id;
 begin perform public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,gen_random_uuid(),'activate',hash);raise exception 'FAIL partial activation';exception when raise_exception then if SQLERRM<>'Fixture activation history failure' then raise;end if;end;
 perform pg_temp.check((select not mapping_validated and crm_validation_receipt_id is null from public.integration_credentials where id=f.integration_id),'activation history failure rolls back connection change');
end$$;
drop trigger crm_qualification_fixture_failure on public.shared_action_events;
do $$declare f fixture;hash text;command uuid:=gen_random_uuid();begin
 select * into f from fixture;select payload_hash into hash from public.crm_qualifications where id=f.operation_id;
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,command,'activate',hash)->>'state'='applied','reviewed fresh evidence activates exact connection');
 perform pg_temp.check(public.command_crm_qualification(f.property_id,f.actor_id,f.operation_id,command,'activate',hash)->>'state'='replayed','lost activation acknowledgement is replayed');
 perform pg_temp.check((select public.crm_handoff_configuration_ready(c.id,c.crm_revision,c.crm_approved_review_id,c.crm_validation_receipt_id,public.crm_configuration_hash(c.credentials)) from public.integration_credentials c where c.id=f.integration_id),'activation supplies the real saved delivery gate');
 perform pg_temp.check((select bool_and(not training_eligible) and bool_and(request::text not like '%qualification-private%' and result::text not like '%qualification-private%') from public.shared_action_events where property_id=f.property_id and action like 'crm.qualification.%'),'qualification actions exclude secrets and training eligibility');
end$$;
select count(*) as assertions from checks;
rollback;
