begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid);
insert into fixture select gen_random_uuid(),id from public.profiles where org_id='22222222-2222-2222-2222-222222222222' and role='admin' limit 1;
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','CRM foundation SQL fixture' from fixture;
DO $$declare p uuid;actor uuid;request_id uuid:=gen_random_uuid();r jsonb;connection uuid;version bigint;mapping jsonb:='{"first_name":"FirstName","last_name":"LastName","email":"Email"}';creds jsonb:='{"api_key":"local-only-secret-fixture"}';
begin
 select property_id,actor_id into p,actor from fixture;
 r:=public.save_crm_mapping_review(p,actor,request_id,'salesforce',0,creds,mapping);
 perform pg_temp.check(r->>'state'='applied' and r->>'providerVerified'='false','local mapping save cannot claim provider validation');
 connection:=(r->>'integrationId')::uuid;version:=(r->>'revision')::bigint;
 perform pg_temp.check((select status='pending' and mapping_validated=false from public.integration_credentials where id=connection),'saved mapping stays pending');
 perform pg_temp.check(public.save_crm_mapping_review(p,actor,request_id,'salesforce',0,creds,mapping)->>'state'='replayed','lost save response replays exact result');
 perform pg_temp.check(public.save_crm_mapping_review(p,actor,request_id,'salesforce',0,creds,'{"email":"Other"}')->>'state'='request_conflict','same save identity cannot change mapping');
 perform pg_temp.check(public.save_crm_mapping_review(p,actor,gen_random_uuid(),'salesforce',0,creds,mapping)->>'state'='stale','stale configuration held');
 perform pg_temp.check(public.save_crm_mapping_review(p,gen_random_uuid(),gen_random_uuid(),'salesforce',version,creds,mapping)->>'state'='forbidden','unknown actor cannot save credentials');
 perform pg_temp.check(public.save_crm_mapping_review(p,actor,gen_random_uuid(),'hubspot',0,creds,mapping)->>'state'='provider_change_requires_review','provider replacement is explicit hold');
 perform pg_temp.check(public.save_crm_mapping_review(p,actor,gen_random_uuid(),'salesforce',version,creds,'{"email":"Contact","phone":"Contact"}')->>'state'='duplicate_targets','two source fields cannot silently overwrite same target');
 r:=public.read_crm_workspace(p,actor);
 perform pg_temp.check(r::text not like '%local-only-secret-fixture%' and r::text not like '%api_key%' and r->'integrations'->0->>'hasCredentials'='true','status DTO reveals presence, not credentials');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=p and action='crm.mapping.saved' and not training_eligible),'one saved decision excluded from training');
 perform pg_temp.check((select request::text not like '%local-only-secret-fixture%' and result::text not like '%local-only-secret-fixture%' from public.shared_action_events where id=request_id),'shared history excludes secret values');
 begin update public.integration_credentials set mapping_validated=true,status='connected' where id=connection;raise exception 'FAIL forged readiness';exception when raise_exception then if SQLERRM<>'CRM activation requires current saved provider evidence' then raise;end if;end;
 perform pg_temp.check((select mapping_validated=false from public.integration_credentials where id=connection),'direct provider-ready boolean rejected');
 r:=public.save_crm_mapping_review(p,actor,gen_random_uuid(),'salesforce',version,null,'{"email":"PrimaryEmail"}');
 perform pg_temp.check((r->>'revision')::bigint=version+1,'mapping change increments saved revision');
 perform pg_temp.check((select credentials=creds from public.integration_credentials where id=connection),'omitted credentials preserve saved secret on server');
 perform pg_temp.check(not has_table_privilege('authenticated','public.crm_mapping_reviews','select'),'review snapshots are private');
 perform pg_temp.check(not has_function_privilege('authenticated','public.save_crm_mapping_review(uuid,uuid,uuid,text,bigint,jsonb,jsonb)','execute'),'review writes require server scope');
end$$;
grant insert,select on checks to authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select actor_id from fixture),'role','authenticated')::text,true);
set local role authenticated;
select pg_temp.check(not exists(select 1 from public.integration_credentials where platform='salesforce' and credentials->>'api_key'='local-only-secret-fixture'),'browser cannot read CRM credential row');
reset role;
select count(*) as passed from checks;

DO $$declare p uuid;actor uuid;c public.integration_credentials;r jsonb;preview uuid:=gen_random_uuid();decision uuid:=gen_random_uuid();lead uuid:=gen_random_uuid();
begin
 select property_id,actor_id into p,actor from fixture;
 select * into c from public.integration_credentials where property_id=p and platform='salesforce';
 r:=public.preview_crm_mapping(p,actor,preview,c.id,c.crm_revision);
 perform pg_temp.check(r->>'state'='applied' and r->'preview'->>'exampleOnly'='true','example preview is explicitly synthetic');
 perform pg_temp.check(r->'preview'->'mapped'->>'PrimaryEmail'='example@example.invalid','preview applies the exact saved mapping');
 perform pg_temp.check(public.preview_crm_mapping(p,actor,preview,c.id,c.crm_revision)->>'state'='replayed','preview response retry recovers snapshot');
 r:=public.approve_crm_mapping(p,actor,decision,preview);
 perform pg_temp.check(r->>'state'='applied' and r->>'providerVerified'='false','human approval remains distinct from provider acceptance');
 perform pg_temp.check((select crm_approved_review_id=decision and status='pending' and mapping_validated=false from public.integration_credentials where id=c.id),'approval cannot activate delivery');
 perform pg_temp.check(public.approve_crm_mapping(p,actor,decision,preview)->>'state'='replayed','lost approval acknowledgment replays once');
 insert into public.leads(id,property_id,first_name,email)values(lead,p,'Private fixture','crm-private@example.invalid');
 preview:=gen_random_uuid();r:=public.preview_crm_mapping(p,actor,preview,c.id,c.crm_revision,lead);
 perform pg_temp.check(r->'preview'->'mapped'->>'PrimaryEmail'='crm-private@example.invalid','actual lead preview is property scoped');
 perform pg_temp.check((select request::text not like '%crm-private%' and result::text not like '%crm-private%' from public.shared_action_events where id=preview),'shared preview record excludes lead contact values');
 update public.leads set email='crm-changed@example.invalid' where id=lead;
 perform pg_temp.check(public.approve_crm_mapping(p,actor,gen_random_uuid(),preview)->>'state'='stale_preview','changed source values require a fresh preview');
 perform pg_temp.check(public.preview_crm_mapping(p,actor,gen_random_uuid(),c.id,c.crm_revision,gen_random_uuid())->>'state'='not_found','unscoped lead cannot be previewed');
 r:=public.save_crm_mapping_review(p,actor,gen_random_uuid(),'salesforce',c.crm_revision,'{"api_key":"rotated-fixture"}',c.field_mapping);
 perform pg_temp.check((select crm_approved_review_id is null and crm_validation_receipt_id is null and crm_revision=c.crm_revision+1 from public.integration_credentials where id=c.id),'credential change invalidates previous mapping approval and provider evidence');
 perform pg_temp.check(public.approve_crm_mapping(p,actor,gen_random_uuid(),preview)->>'state'='stale','old preview cannot approve changed credentials');
end$$;

DO $$declare p uuid;actor uuid;c public.integration_credentials;op uuid:=gen_random_uuid();claim uuid;r jsonb;result jsonb:='{"status":"limited","messageCode":"read_check_only","connection":{"success":true,"evidenceSource":"local_structure"}}';stopped uuid;
begin
 select property_id,actor_id into p,actor from fixture;select * into c from public.integration_credentials where property_id=p;
 r:=public.request_crm_setup_operation(p,actor,op,c.id,c.crm_revision,'schema');
 perform pg_temp.check(r->>'state'='applied' and r->'operation'->>'state'='queued','setup request saved before provider work');
 perform pg_temp.check(public.request_crm_setup_operation(p,actor,op,c.id,c.crm_revision,'schema')->>'state'='replayed','unknown setup acknowledgment recovers same operation');
 perform pg_temp.check(public.request_crm_setup_operation(p,actor,op,c.id,c.crm_revision,'connection')->>'state'='request_conflict','saved check cannot change kind');
 perform pg_temp.check(public.request_crm_setup_operation(p,actor,gen_random_uuid(),c.id,c.crm_revision,'schema')->>'state'='operation_in_progress','overlapping checks held');
 r:=public.claim_crm_setup_operation(op);claim:=(r->>'claimId')::uuid;
 perform pg_temp.check(r->>'state'='claimed' and r->'credentials'->>'api_key'='rotated-fixture','private claim uses saved credentials');
 perform pg_temp.check(public.claim_crm_setup_operation(op)->>'state'='running','second worker does not repeat provider read');
 perform pg_temp.check(public.finish_crm_setup_operation(op,gen_random_uuid(),result)->>'state'='claim_conflict','wrong worker result held');
 r:=public.finish_crm_setup_operation(op,claim,result);
 perform pg_temp.check(r->>'state'='saved' and r->>'accepted'='true','single provider result saved');
 perform pg_temp.check(public.finish_crm_setup_operation(op,claim,result)->>'state'='replayed','completion reply can be replayed');
 perform pg_temp.check(public.finish_crm_setup_operation(op,claim,'{"status":"checked"}')->>'state'='request_conflict','receipt cannot be overwritten');
 perform pg_temp.check((select not mapping_validated and crm_validation_receipt_id is null from public.integration_credentials where id=c.id),'read-only check cannot activate delivery');
 r:=public.read_crm_setup_operations(p,actor);
 perform pg_temp.check(r::text not like '%rotated-fixture%' and r::text not like '%credentials%' and r->'operations'->0->>'state'='completed','readable setup history excludes credentials');
 perform pg_temp.check((select count(*)=2 from public.shared_action_events where episode_id=op and not training_eligible),'request and actual result have distinct untrained evidence');
 op:=gen_random_uuid();perform public.request_crm_setup_operation(p,actor,op,c.id,c.crm_revision,'connection');claim:=(public.claim_crm_setup_operation(op)->>'claimId')::uuid;
 r:=public.stop_crm_setup_operation(p,actor,op,gen_random_uuid());perform pg_temp.check(r->>'state'='applied','in-flight read can be stopped');
 r:=public.finish_crm_setup_operation(op,claim,result);perform pg_temp.check(r->>'accepted'='false','late stopped result is not accepted');
 perform pg_temp.check((select state='stopped' from public.crm_setup_operations where id=op) and exists(select 1 from public.crm_setup_receipts where operation_id=op),'late actual receipt retained without resuming stopped work');
 op:=gen_random_uuid();perform public.request_crm_setup_operation(p,actor,op,c.id,c.crm_revision,'connection');claim:=(public.claim_crm_setup_operation(op)->>'claimId')::uuid;
 perform public.save_crm_mapping_review(p,actor,gen_random_uuid(),'salesforce',c.crm_revision,'{"api_key":"changed-during-check"}',c.field_mapping);
 r:=public.finish_crm_setup_operation(op,claim,result);perform pg_temp.check(r->>'accepted'='false','credential rotation fences a claimed result');
 perform pg_temp.check((select not current_configuration from public.crm_setup_receipts where operation_id=op),'old account check stays bound to original configuration');
 perform pg_temp.check(public.read_crm_setup_operations(p,gen_random_uuid())->>'state'='forbidden','setup receipts cannot cross membership boundary');
 perform pg_temp.check(not has_function_privilege('authenticated','public.claim_crm_setup_operation(uuid)','execute'),'browser cannot claim credentials or finish checks');
 perform pg_temp.check(not has_table_privilege('authenticated','public.crm_setup_receipts','select'),'provider receipt table is private');
 begin update public.crm_setup_receipts set result='{}' where operation_id=op;raise exception 'FAIL mutable receipt';exception when others then if SQLERRM<>'Action history is immutable' then raise;end if;end;
 perform pg_temp.check((select r.result->>'status'='limited' from public.crm_setup_receipts r where operation_id=op),'receipt history rejects updates');
end$$;

DO $$declare p uuid;actor uuid;peer uuid:=gen_random_uuid();c public.integration_credentials;r jsonb;op uuid:=gen_random_uuid();
begin
 select property_id,actor_id into p,actor from fixture;select * into c from public.integration_credentials where property_id=p;
 perform set_config('p11.team_scope','22222222-2222-2222-2222-222222222222',true);insert into auth.users(id,email)values(peer,peer::text||'@fixture.invalid');update public.profiles set org_id='22222222-2222-2222-2222-222222222222' where id=peer;
 perform pg_temp.check(public.read_crm_workspace(p,peer)->>'state'='saved','member may review sanitized setup');
 perform pg_temp.check(public.save_crm_mapping_review(p,peer,gen_random_uuid(),c.platform,c.crm_revision,null,c.field_mapping)->>'state'='forbidden','member cannot replace credentials');
 perform pg_temp.check(public.request_crm_setup_operation(p,peer,op,c.id,c.crm_revision,'connection')->>'state'='forbidden','member cannot initiate provider calls');
 perform public.request_crm_setup_operation(p,actor,op,c.id,c.crm_revision,'connection');
 update public.integration_credentials set credentials='{"api_key":"changed-before-claim"}' where id=c.id;
 perform pg_temp.check(public.claim_crm_setup_operation(op)->>'state'='stale','changed queued setup is stopped before exposing credentials');
 begin update public.integration_credentials set platform='pms' where id=c.id;raise exception 'FAIL changed identity';exception when raise_exception then if SQLERRM<>'CRM connection identity cannot change' then raise;end if;end;
 perform pg_temp.check((select platform=c.platform from public.integration_credentials where id=c.id),'CRM row cannot bypass private policy by changing provider kind');
end$$;
create function pg_temp.fail_crm_history() returns trigger language plpgsql as $$begin if new.action like 'crm.%' then raise exception 'Fixture CRM history failure';end if;return new;end$$;
create trigger crm_fixture_history_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_crm_history();
DO $$declare p uuid;actor uuid;c public.integration_credentials;request uuid:=gen_random_uuid();
begin
 select property_id,actor_id into p,actor from fixture;select * into c from public.integration_credentials where property_id=p;
 begin perform public.save_crm_mapping_review(p,actor,request,c.platform,c.crm_revision,'{"api_key":"should-not-save"}',c.field_mapping);raise exception 'FAIL partial save';exception when raise_exception then if SQLERRM<>'Fixture CRM history failure' then raise;end if;end;
 perform pg_temp.check((select credentials=c.credentials and crm_revision=c.crm_revision from public.integration_credentials where id=c.id),'history failure rolls back credential and version change');
 perform pg_temp.check(not exists(select 1 from public.crm_mapping_reviews where id=request),'history failure rolls back review receipt');
 begin perform public.request_crm_setup_operation(p,actor,request,c.id,c.crm_revision,'connection');raise exception 'FAIL partial request';exception when raise_exception then if SQLERRM<>'Fixture CRM history failure' then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.crm_setup_operations where id=request),'history failure rolls back provider request');
end$$;
drop trigger crm_fixture_history_failure on public.shared_action_events;

select count(*) as total_passed from checks;
rollback;