begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,revision_id uuid,connection_id uuid,publication_id uuid,tracking_token uuid,request_id uuid,claim_token uuid,review_id uuid,result jsonb);
insert into fixture select gen_random_uuid(),id,gen_random_uuid(),gen_random_uuid(),null,null,gen_random_uuid(),null,gen_random_uuid(),jsonb_build_object('status','observed','metrics',public.validate_forgestudio_metrics('{"impressions":100,"clicks":0,"reactions":10}'::jsonb),'definition','provider_reported_snapshot.v1','observedAt',clock_timestamp(),'providerPayload','{"private":"provider-evidence"}'::jsonb) from public.profiles where id='11111111-1111-1111-1111-111111111111';
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','ForgeStudio outcomes rollback fixture' from fixture;
do $$declare f fixture;r jsonb;variant uuid;hash text;begin select * into f from fixture;
 r:=public.save_forgestudio_revision(f.revision_id,f.property_id,f.actor_id,'{"content":{"contractVersion":"forgestudio.social.v1","conceptSummary":"Measured campaign","variants":[{"variantKey":"primary","sequenceIndex":0,"platform":"facebook","caption":"Explore our community.","hashtags":[],"assetIds":[],"mediaUrls":[],"contentFormat":"text","linkUrl":"https://example.invalid/community"}],"claims":[]},"authorKind":"user","validation":[[]]}'::jsonb);
 hash:=r->'revision'->>'content_hash';select id into variant from public.social_content_variants where revision_id=f.revision_id;
 perform public.review_forgestudio_revision(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('revisionId',f.revision_id,'contentHash',hash,'decision','approved','note','Reviewed exact campaign copy'));
 insert into public.social_connections(id,property_id,platform,account_id,is_active,access_token)values(f.connection_id,f.property_id,'facebook','fixture-account',true,'fixture-token');
 r:=public.schedule_forgestudio_publications(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('revisionId',f.revision_id,'contentHash',hash,'destinations',jsonb_build_array(jsonb_build_object('connectionId',f.connection_id,'variantId',variant,'scheduledFor',clock_timestamp()+interval '1 day','timezone','America/Los_Angeles'))));
 update fixture set publication_id=(r->'publications'->0->>'id')::uuid;
 update public.social_publications set status='published',remote_post_id='fixture-post',published_at=clock_timestamp()-interval '1 day' where id=(r->'publications'->0->>'id')::uuid;
 update fixture set tracking_token=(select p.tracking_token from public.social_publications p where p.id=(r->'publications'->0->>'id')::uuid);
 perform pg_temp.check((select publication_id is not null from fixture),'published fixture retains its exact approved revision and destination');
end$$;
do $$declare f fixture;r jsonb;again uuid:=gen_random_uuid();begin select * into f from fixture;
 perform pg_temp.check(not has_function_privilege('authenticated','public.begin_forgestudio_measurement(uuid,uuid,uuid,uuid)','execute') and not has_table_privilege('authenticated','public.forgestudio_measurements','select') and not has_table_privilege('authenticated','public.social_attribution_events','select'),'private measurement and subject evidence stays behind authorized APIs');
 perform pg_temp.check(public.begin_forgestudio_measurement(f.request_id,f.property_id,gen_random_uuid(),f.publication_id)->>'state'='forbidden','measurement request needs current property access');
 perform pg_temp.check(public.begin_forgestudio_measurement(f.request_id,f.property_id,f.actor_id,f.publication_id)->>'state'='saved','request and action evidence save atomically');
 perform pg_temp.check(public.begin_forgestudio_measurement(f.request_id,f.property_id,f.actor_id,f.publication_id)->>'state'='replayed','lost request acknowledgement returns the saved measurement');
 perform pg_temp.check(public.begin_forgestudio_measurement(again,f.property_id,f.actor_id,f.publication_id)->>'measurementId'=f.request_id::text and(select count(*)=1 from public.forgestudio_measurements where property_id=f.property_id),'another check request reuses the active read without duplicating provider work');
 r:=public.claim_forgestudio_measurement(f.request_id);update fixture set claim_token=(r->'measurement'->>'claim_token')::uuid;
 perform pg_temp.check(r->>'state'='claimed' and r->'measurement'->'snapshot'->'publication'->>'revisionId'=f.revision_id::text,'provider read is tied to exact published revision');
 perform pg_temp.check(public.claim_forgestudio_measurement(f.request_id)->>'state'='empty','active read has one worker');
 perform pg_temp.check(public.validate_forgestudio_metrics('{"impressions":0}'::jsonb)->'clicks'='null'::jsonb,'missing count stays unknown while an explicit zero stays zero');
 begin perform public.validate_forgestudio_metrics('{"clicks":-1}');raise exception 'FAIL negative count';exception when raise_exception then if SQLERRM<>'Measurements must be whole nonnegative counts or unavailable' then raise;end if;end;
 perform pg_temp.check(true,'negative counts are rejected');
end$$;
do $$declare f fixture;r jsonb;payload jsonb;begin select * into f from fixture;
 perform pg_temp.check(public.finish_forgestudio_measurement(f.request_id,gen_random_uuid(),f.result)->>'state'='claim_mismatch','a different worker cannot submit measurement evidence');
 r:=public.finish_forgestudio_measurement(f.request_id,f.claim_token,f.result);perform pg_temp.check(r->>'state'='saved' and r->>'measurementState'='completed','exact provider observation is retained');
 perform pg_temp.check(public.finish_forgestudio_measurement(f.request_id,f.claim_token,f.result)->>'state'='replayed','lost result acknowledgement repeats only the same evidence');
 perform pg_temp.check(public.finish_forgestudio_measurement(f.request_id,f.claim_token,f.result||'{"extra":true}')->>'state'='result_conflict','different result cannot replace a saved observation');
 perform pg_temp.check(not exists(select 1 from public.shared_experiment_outcomes where property_id=f.property_id),'observed counts never become an automatic reward');
 payload:=jsonb_build_object('measurementId',f.request_id,'expectedVersion',1,'decision','included','reason','Checked the exact provider observation source');
 perform pg_temp.check(public.review_forgestudio_measurement(f.review_id,f.property_id,f.actor_id,payload)->>'state'='saved','measurement inclusion records a versioned reason');
 perform pg_temp.check(public.review_forgestudio_measurement(f.review_id,f.property_id,f.actor_id,payload)->>'state'='replayed','lost evidence review reply records the decision once');
 perform pg_temp.check(public.review_forgestudio_measurement(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"decision":"excluded"}')->>'state'='stale_measurement','an older review cannot overwrite a newer decision');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='studio.metrics.reviewed'),'one shared semantic review event after replay');
 perform pg_temp.check((select result->'metrics'->'clicks'='0'::jsonb and result->'metrics'->'reach'='null'::jsonb from public.forgestudio_measurements where id=f.request_id),'stored evidence preserves absent and zero values distinctly');
end$$;
create function pg_temp.fail_outcome_history() returns trigger language plpgsql as $$begin if new.action='studio.metrics.reviewed' then raise exception 'Fixture outcome history failure';end if;return new;end$$;
create trigger outcome_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_outcome_history();
do $$declare f fixture;begin select * into f from fixture;
 begin perform public.review_forgestudio_measurement(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('measurementId',f.request_id,'expectedVersion',2,'decision','excluded','reason','Withdraw the reviewed measurement'));raise exception 'FAIL partial review';exception when raise_exception then if SQLERRM<>'Fixture outcome history failure' then raise;end if;end;
 perform pg_temp.check((select review_status='included' and review_version=2 from public.forgestudio_measurements where id=f.request_id),'failed action history rolls back evidence review');
end$$;
drop trigger outcome_fixture_failure on public.shared_action_events;
do $$declare f fixture;measurement_uuid uuid:=gen_random_uuid();r jsonb;token uuid;old_token uuid;begin select * into f from fixture;
 perform public.begin_forgestudio_measurement(measurement_uuid,f.property_id,f.actor_id,f.publication_id);r:=public.claim_forgestudio_measurement(measurement_uuid);old_token:=(r->'measurement'->>'claim_token')::uuid;
 update public.forgestudio_measurements m set lease_expires_at=clock_timestamp()-interval '1 minute' where m.id=measurement_uuid;
 r:=public.claim_forgestudio_measurement(measurement_uuid);token:=(r->'measurement'->>'claim_token')::uuid;
 perform pg_temp.check(token<>old_token and public.finish_forgestudio_measurement(measurement_uuid,old_token,f.result)->>'state'='claim_mismatch','expired read can be repeated safely while the older worker is fenced');
 update public.social_connections set access_token='rotated-fixture-token' where id=f.connection_id;
 r:=public.finish_forgestudio_measurement(measurement_uuid,token,f.result);
 perform pg_temp.check(r->>'measurementState'='held' and(select result=f.result from public.forgestudio_measurements m where m.id=measurement_uuid),'late result after credential change is retained but held');
 perform pg_temp.check(public.review_forgestudio_measurement(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('measurementId',measurement_uuid,'expectedVersion',1,'decision','included','reason','Attempt to accept a changed-source result'))->>'state'='observation_required','held observations cannot be included as valid evidence');
 perform pg_temp.check(not exists(select 1 from public.due_forgestudio_measurements(20,f.property_id) p where p.id=f.publication_id),'recent attempt prevents daily scanning from repeatedly checking the same publication');
end$$;
do $$declare f fixture;measurement_uuid uuid:=gen_random_uuid();payload jsonb;r jsonb;begin select * into f from fixture;
 payload:=jsonb_build_object('publicationId',f.publication_id,'observedAt',clock_timestamp(),'metrics','{"impressions":240,"clicks":12}'::jsonb,'source','Provider export reviewed by operator','reason','Record the exported cumulative totals');
 r:=public.report_forgestudio_metrics(measurement_uuid,f.property_id,f.actor_id,payload);
 perform pg_temp.check(r->>'state'='saved' and(select origin='operator_report' and review_status='unreviewed' from public.forgestudio_measurements m where m.id=measurement_uuid),'operator report retains source and awaits separate review');
 perform pg_temp.check(public.report_forgestudio_metrics(measurement_uuid,f.property_id,f.actor_id,payload)->>'state'='replayed','lost report reply cannot duplicate a cumulative snapshot');
 perform pg_temp.check((select result->'metrics'->'reach'='null'::jsonb from public.forgestudio_measurements m where m.id=measurement_uuid),'partial report does not invent unreported values');
 begin perform public.report_forgestudio_metrics(gen_random_uuid(),f.property_id,f.actor_id,payload||jsonb_build_object('observedAt',clock_timestamp()-interval '2 days'));raise exception 'FAIL early report';exception when raise_exception then if SQLERRM<>'Explain the source, time and at least one reported measurement' then raise;end if;end;
 perform pg_temp.check(true,'operator report cannot predate the published post');
end$$;
do $$declare f fixture;r jsonb;event_id uuid;decision uuid:=gen_random_uuid();at_time timestamptz:=clock_timestamp()-interval '1 hour';payload jsonb;begin select * into f from fixture;
 perform pg_temp.check(public.record_forgestudio_attribution(f.tracking_token,'lead',repeat('a',64),clock_timestamp()-interval '2 days','fixture-crm',repeat('b',64))->>'state'='outside_measurement_window','business event cannot predate publication');
 perform pg_temp.check(public.record_forgestudio_attribution(f.tracking_token,'lead',repeat('a',64),clock_timestamp()+interval '1 day','fixture-crm',repeat('b',64))->>'state'='outside_measurement_window','future business event is rejected');
 r:=public.record_forgestudio_attribution(f.tracking_token,'lead',repeat('a',64),at_time,'fixture-crm',repeat('b',64));event_id:=(r->>'eventId')::uuid;
 perform pg_temp.check(r->>'state'='saved' and r->>'evidenceKind'='system_report','business outcome remains a source report, not verified impact');
 perform pg_temp.check(public.record_forgestudio_attribution(f.tracking_token,'lead',repeat('a',64),at_time,'fixture-crm',repeat('b',64))->>'state'='replayed','same source business event cannot count again after a retry');
 perform pg_temp.check(public.record_forgestudio_attribution(f.tracking_token,'lead',repeat('a',64),at_time+interval '2 hours','fixture-crm',repeat('b',64))->>'state'='source_event_conflict','changing retry time cannot turn the same business event into another conversion');
 perform pg_temp.check(public.record_forgestudio_attribution(f.tracking_token,'lease',repeat('a',64),at_time,'fixture-crm',repeat('b',64))->>'state'='source_event_conflict','a source event cannot be silently relabeled as another outcome');
 payload:=jsonb_build_object('eventId',event_id,'expectedVersion',1,'decision','excluded','reason','Source report was incorrect');
 perform pg_temp.check(public.review_forgestudio_attribution(decision,f.property_id,f.actor_id,payload)->>'state'='saved','incorrect attribution can be excluded with a recorded reason');
 perform pg_temp.check(public.review_forgestudio_attribution(decision,f.property_id,f.actor_id,payload)->>'state'='replayed','lost exclusion response retains one decision');
 perform pg_temp.check(public.record_forgestudio_attribution(f.tracking_token,'lead',repeat('a',64),at_time,'fixture-crm',repeat('b',64))->>'eventState'='excluded','source replay cannot reactivate excluded evidence');
 perform pg_temp.check(public.review_forgestudio_attribution(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"decision":"active"}')->>'state'='stale_attribution','older attribution review cannot overwrite exclusion');
 perform pg_temp.check(public.review_forgestudio_attribution(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"decision":"active","expectedVersion":2}')->>'state'='saved','explicit current review can restore the original reported evidence');
 perform pg_temp.check(not exists(select 1 from public.shared_experiment_outcomes where property_id=f.property_id),'reported leads do not create positive training rewards');
end$$;
select count(*) as passed_assertions from checks;
rollback;
