begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,request_id uuid,settings jsonb);
insert into fixture values(gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),'{"brand_voice":"Warm and clear","target_audience":"Outdoor spaces","key_amenities":["Pool","Roof deck"],"include_hashtags":false,"include_cta":false,"max_caption_length":180}');
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','ForgeStudio configuration rollback fixture' from fixture;
do $$declare f fixture;result jsonb;before_source jsonb;begin select * into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.forgestudio_config','insert') and not has_table_privilege('authenticated','public.forgestudio_config','update') and not has_function_privilege('authenticated','public.save_forgestudio_configuration(uuid,uuid,uuid,jsonb)','execute'),'browser roles cannot bypass the versioned save');
 before_source:=public.read_forgestudio_source_record(f.property_id,'config',f.property_id,'{"absent":true}');
 perform pg_temp.check(before_source='{"absent":true}'::jsonb and not exists(select 1 from public.forgestudio_config where property_id=f.property_id),'absent preferences are explicit read-only source evidence');
 perform pg_temp.check(public.save_forgestudio_configuration(f.request_id,f.property_id,gen_random_uuid(),jsonb_build_object('expectedVersion',0,'config',f.settings))->>'state'='forbidden','unscoped actor cannot save settings');
 result:=public.save_forgestudio_configuration(f.request_id,f.property_id,f.actor_id,jsonb_build_object('expectedVersion',0,'config',f.settings));
 perform pg_temp.check(result->>'state'='saved' and result->>'version'='1' and result->'config'=f.settings,'supported settings save with first version');
 perform pg_temp.check(public.save_forgestudio_configuration(f.request_id,f.property_id,f.actor_id,jsonb_build_object('expectedVersion',0,'config',f.settings))->>'state'='replayed','lost reply replays one saved decision');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='studio.configuration.saved'),'only one semantic settings event is recorded');
 perform pg_temp.check((select before_state->>'version'='0' and after_state->'config'=f.settings and shared_action_events.result->'trainingEligible'='false'::jsonb from public.shared_action_events where id=f.request_id),'history retains exact before and after preferences and training exclusion');
 perform pg_temp.check(public.save_forgestudio_configuration(f.request_id,f.property_id,f.actor_id,jsonb_build_object('expectedVersion',0,'config',f.settings||'{"brand_voice":"Changed"}'))->>'state'='request_conflict','request identity cannot be reused for different preferences');
 perform pg_temp.check(public.save_forgestudio_configuration(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('expectedVersion',0,'config',f.settings))->>'state'='stale_configuration','another stale initial form cannot overwrite saved preferences');
 begin perform public.read_forgestudio_source_record(f.property_id,'config',f.property_id,before_source);raise exception 'FAIL missed changed absent source';exception when raise_exception then if SQLERRM not like 'A source changed%' then raise;end if;end;
 perform pg_temp.check(true,'new settings invalidate a source snapshot that recorded their absence');
 before_source:=public.read_forgestudio_source_record(f.property_id,'config',f.property_id);
 result:=public.save_forgestudio_configuration(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('expectedVersion',1,'config',f.settings||'{"max_caption_length":140}'));
 perform pg_temp.check(result->>'version'='2' and result->'config'->>'max_caption_length'='140','subsequent save increments exact settings version');
 begin perform public.read_forgestudio_source_record(f.property_id,'config',f.property_id,before_source);raise exception 'FAIL missed changed saved source';exception when raise_exception then if SQLERRM not like 'A source changed%' then raise;end if;end;
 perform pg_temp.check(true,'changed settings invalidate the original source evidence');
 begin perform public.save_forgestudio_configuration(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('expectedVersion',2,'config',f.settings||'{"property_id":"33333333-3333-3333-3333-333333333333"}'));raise exception 'FAIL unexpected setting';exception when raise_exception then if SQLERRM<>'Invalid studio configuration' then raise;end if;end;
 perform pg_temp.check(true,'identity and unsupported fields cannot be smuggled into settings');
 begin perform public.save_forgestudio_configuration(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('expectedVersion',2,'config',f.settings||'{"max_caption_length":12}'));raise exception 'FAIL invalid caption limit';exception when raise_exception then if SQLERRM<>'Invalid studio configuration' then raise;end if;end;
 perform pg_temp.check(true,'caption limits are validated in the database');
 begin perform public.save_forgestudio_configuration(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('expectedVersion',2,'config',f.settings||'{"key_amenities":[42]}'));raise exception 'FAIL invalid amenities';exception when raise_exception then if SQLERRM<>'Invalid studio amenities' then raise;end if;end;
 perform pg_temp.check(true,'amenities must be bounded meaningful text');
 begin update public.forgestudio_config set property_id='33333333-3333-3333-3333-333333333333' where property_id=f.property_id;raise exception 'FAIL moved configuration';exception when raise_exception then if SQLERRM<>'Configuration identity cannot change' then raise;end if;end;
 perform pg_temp.check(true,'existing config identity cannot move to another property');
end$$;
create function pg_temp.fail_settings_history() returns trigger language plpgsql as $$begin if new.action='studio.configuration.saved' then raise exception 'Fixture settings history failure';end if;return new;end$$;
create trigger settings_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_settings_history();
do $$declare f fixture;command_id uuid:=gen_random_uuid();begin select * into f from fixture;
 begin perform public.save_forgestudio_configuration(command_id,f.property_id,f.actor_id,jsonb_build_object('expectedVersion',2,'config',f.settings));raise exception 'FAIL missing history';exception when raise_exception then if SQLERRM<>'Fixture settings history failure' then raise;end if;end;
 perform pg_temp.check((select configuration_version=2 and max_caption_length=140 from public.forgestudio_config where property_id=f.property_id) and not exists(select 1 from public.forgestudio_commands where forgestudio_commands.id=command_id),'settings and version roll back when action evidence fails');
end$$;
drop trigger settings_fixture_failure on public.shared_action_events;
select count(*) as passed_assertions from checks;
rollback;
