begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,brief_id uuid,revision_id uuid,package_id uuid,edited_id uuid,content jsonb,payload jsonb);
insert into fixture select gen_random_uuid(),id,gen_random_uuid(),gen_random_uuid(),null,gen_random_uuid(),'{"contractVersion":"forgestudio.social.v1","conceptSummary":"A factual campaign","variants":[{"variantKey":"primary","sequenceIndex":0,"platform":"facebook","caption":"Welcome to the community.","hashtags":[],"assetIds":[],"mediaUrls":[],"contentFormat":"text","linkUrl":"https://example.invalid/community"}],"claims":[]}',null from public.profiles where org_id='22222222-2222-2222-2222-222222222222' and role='admin' limit 1;
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','ForgeStudio scheduling rollback fixture' from fixture;
do $$declare f fixture;r jsonb;input jsonb:='{"title":"Operator brief","objective":"Explain the community","channels":["facebook"],"formatPlan":[{"platform":"facebook","contentFormat":"text","quantity":1}],"sourceFacts":[{"text":"Private reviewed source","source":"operator"}]}';begin
 select * into f from fixture;
 perform pg_temp.check(public.save_forgestudio_brief(f.brief_id,f.property_id,gen_random_uuid(),input)->>'state'='forbidden','brief requires current property access');
 r:=public.save_forgestudio_brief(f.brief_id,f.property_id,f.actor_id,input);
 perform pg_temp.check(r->>'state'='saved' and r->'brief'->>'id'=f.brief_id::text,'brief and decision saved together');
 perform pg_temp.check(public.save_forgestudio_brief(f.brief_id,f.property_id,f.actor_id,input)->>'state'='replayed','lost brief reply recovers same saved brief');
 perform pg_temp.check(public.save_forgestudio_brief(f.brief_id,f.property_id,f.actor_id,input||'{"title":"Changed"}')->>'state'='request_conflict','request cannot change brief values');
 perform pg_temp.check(public.save_forgestudio_brief(gen_random_uuid(),f.property_id,f.actor_id,input||jsonb_build_object('assetIds',jsonb_build_array(gen_random_uuid())))->>'state'='asset_unavailable','foreign or missing assets cannot enter a brief');
 perform pg_temp.check(public.save_forgestudio_brief(gen_random_uuid(),f.property_id,f.actor_id,input||jsonb_build_object('connectionIds',jsonb_build_array(gen_random_uuid())))->>'state'='connection_unavailable','foreign or missing accounts cannot enter a brief');
 perform pg_temp.check((select count(*)=1 from public.social_content_briefs where property_id=f.property_id),'invalid/replayed requests do not leave extra briefs');
 perform pg_temp.check(not has_table_privilege('authenticated','public.forgestudio_commands','select') and not has_function_privilege('authenticated','public.save_forgestudio_brief(uuid,uuid,uuid,jsonb)','execute'),'browser cannot read private decisions or bypass attributed transaction');
 input:=jsonb_build_object('content',f.content,'authorKind','llm','briefId',f.brief_id,'validation','[[]]'::jsonb);
 update fixture set payload=input;
 r:=public.save_forgestudio_revision(f.revision_id,f.property_id,f.actor_id,input);
 perform pg_temp.check(r->>'state'='saved','package and initial revision save atomically');
 update fixture set package_id=(r->>'packageId')::uuid;
 perform pg_temp.check((select count(*)=1 and bool_and(link_url='https://example.invalid/community') from public.social_content_variants where revision_id=f.revision_id),'channel payload preserves reviewed link');
 perform pg_temp.check((select status='generated' from public.social_content_briefs where id=f.brief_id),'brief completion commits with package');
 perform pg_temp.check(public.save_forgestudio_revision(f.revision_id,f.property_id,f.actor_id,input)->>'state'='replayed','lost package save recovers original package and revision');
 perform pg_temp.check((select count(*)=1 from public.social_content_packages where property_id=f.property_id),'package replay cannot duplicate draft');
 perform pg_temp.check((select authored_by_kind='llm' and authored_by is null from public.social_content_revisions where id=f.revision_id),'machine-authored content does not impersonate operator');
end$$;
do $$declare f fixture;r jsonb;input jsonb;hash text;decision uuid:=gen_random_uuid();begin
 select * into f from fixture;select content_hash into hash from public.social_content_revisions where id=f.revision_id;
 input:=jsonb_build_object('revisionId',f.revision_id,'contentHash',hash,'decision','approved','note','Exact reviewed content');
 perform pg_temp.check(public.review_forgestudio_revision(decision,f.property_id,f.actor_id,input||'{"contentHash":"wrong"}')->>'state'='stale_revision','approval requires exact content hash');
 r:=public.review_forgestudio_revision(decision,f.property_id,f.actor_id,input);
 perform pg_temp.check(r->'revision'->>'approval_status'='approved','review and governance commit together');
 perform pg_temp.check(public.review_forgestudio_revision(decision,f.property_id,f.actor_id,input)->>'state'='replayed','lost approval reply recovers original decision');
 perform pg_temp.check(public.review_forgestudio_revision(gen_random_uuid(),f.property_id,f.actor_id,input||'{"decision":"denied"}')->>'state'='stale_revision','another reviewer cannot overwrite completed decision');
 perform pg_temp.check((select count(*)=1 from public.shared_approvals where property_id=f.property_id),'one approval governance record after replay');
 begin update public.social_content_revisions set content='{}' where id=f.revision_id;raise exception 'FAIL changed revision';exception when raise_exception then if SQLERRM<>'Create a new revision to edit saved content' then raise;end if;end;
 begin update public.social_content_variants set caption='Rewritten after approval' where revision_id=f.revision_id;raise exception 'FAIL changed variant';exception when others then if SQLERRM<>'Action history is immutable' then raise;end if;end;
 perform pg_temp.check((select content_hash=hash and approval_status='approved' from public.social_content_revisions where id=f.revision_id),'approved content and variants remain immutable');
 input:=jsonb_build_object('packageId',f.package_id,'expectedRevisionId',gen_random_uuid(),'content',f.content,'authorKind','user','reason','Improve explanation','validation','[[]]'::jsonb);
 perform pg_temp.check(public.save_forgestudio_revision(f.edited_id,f.property_id,f.actor_id,input)->>'state'='stale_revision','edit from old loaded version is rejected');
 update fixture set payload=input||jsonb_build_object('expectedRevisionId',f.revision_id);
end$$;
do $$declare f fixture;input jsonb;hash text;command_id uuid:=gen_random_uuid();bad uuid:=gen_random_uuid();first_connection uuid:=gen_random_uuid();second_connection uuid:=gen_random_uuid();variant uuid;r jsonb;pub uuid;stamp timestamptz;request uuid;begin
 select * into f from fixture;select content_hash into hash from public.social_content_revisions where id=f.revision_id;select id into variant from public.social_content_variants where revision_id=f.revision_id limit 1;
 insert into public.social_connections(id,property_id,platform,account_id,is_active)values(first_connection,f.property_id,'facebook','fixture-account-one',true),(second_connection,f.property_id,'facebook','fixture-account-two',true);
 update public.social_connections set access_token='encv1:fixture',page_access_token='encv1:page',page_id=account_id,scopes=array['pages_show_list','pages_read_engagement','pages_manage_posts'],token_expires_at=clock_timestamp()+interval '60 days',permission_evidence='{"source":"provider_response","expiryKnown":true}' where property_id=f.property_id and access_token is null;
 input:=jsonb_build_object('revisionId',f.revision_id,'contentHash',hash,'destinations',jsonb_build_array(jsonb_build_object('connectionId',first_connection,'variantId',variant,'scheduledFor',clock_timestamp()+interval '1 day','timezone','America/Los_Angeles'),jsonb_build_object('connectionId',second_connection,'variantId',variant,'scheduledFor',clock_timestamp()+interval '2 days','timezone','America/Los_Angeles')));
 perform pg_temp.check(public.schedule_forgestudio_publications(command_id,f.property_id,gen_random_uuid(),input)->>'state'='forbidden','schedule needs current property access');
 perform pg_temp.check(public.schedule_forgestudio_publications(command_id,f.property_id,f.actor_id,input||'{"contentHash":"wrong"}')->>'state'='stale_revision','scheduling requires the reviewed exact revision');
 perform pg_temp.check(public.schedule_forgestudio_publications(command_id,f.property_id,f.actor_id,jsonb_set(input,'{destinations,1,connectionId}',to_jsonb(bad)))->>'state'='connection_unavailable','invalid second account holds the entire selection');
 perform pg_temp.check(not exists(select 1 from public.social_publications where property_id=f.property_id) and not exists(select 1 from public.shared_jobs where property_id=f.property_id and domain='forgestudio.publication'),'invalid second destination leaves no first publication or job');
 perform pg_temp.check(public.schedule_forgestudio_publications(command_id,f.property_id,f.actor_id,jsonb_set(input,'{destinations,1}',input->'destinations'->0))->>'state'='duplicate_destination','duplicate target cannot be scheduled twice');
 perform pg_temp.check(public.schedule_forgestudio_publications(command_id,f.property_id,f.actor_id,jsonb_set(input,'{destinations,0,timezone}','"Wrong/Zone"'))->>'state'='timezone_required','unknown timezone cannot be guessed');
 perform pg_temp.check(public.schedule_forgestudio_publications(command_id,f.property_id,f.actor_id,jsonb_set(input,'{destinations,0,scheduledFor}',to_jsonb(clock_timestamp()-interval '1 day')))->>'state'='schedule_time_required','past schedule cannot silently enter backlog');
 r:=public.schedule_forgestudio_publications(command_id,f.property_id,f.actor_id,input);
 perform pg_temp.check(r->>'state'='saved' and jsonb_array_length(r->'publications')=2,'two valid destinations save together');
 perform pg_temp.check(public.schedule_forgestudio_publications(command_id,f.property_id,f.actor_id,input)->>'state'='replayed','lost scheduling reply recovers the exact two publications');
 perform pg_temp.check((select count(*)=2 from public.social_publications where property_id=f.property_id) and (select count(*)=2 from public.shared_jobs where property_id=f.property_id and domain='forgestudio.publication'),'repeated scheduling does not create extra jobs');
 perform pg_temp.check(public.schedule_forgestudio_publications(gen_random_uuid(),f.property_id,f.actor_id,input)->>'state'='already_scheduled','new request cannot duplicate a live target');
 perform pg_temp.check((select bool_and(delivery_snapshot->>'contentHash'=hash and delivery_snapshot->>'accountId' in('fixture-account-one','fixture-account-two')) from public.social_publications where property_id=f.property_id),'schedule freezes actual approved content and destination identity');
 select p.id,p.updated_at into pub,stamp from public.social_publications p where p.connection_id=first_connection;
 request:=gen_random_uuid();input:=jsonb_build_object('action','reschedule','publicationId',pub,'expectedUpdatedAt',stamp,'scheduledFor',clock_timestamp()+interval '3 days');
 perform pg_temp.check(public.control_forgestudio_publication(request,f.property_id,f.actor_id,input||jsonb_build_object('expectedUpdatedAt',clock_timestamp()-interval '1 day'))->>'state'='stale_publication','changed schedule cannot be overwritten from a stale calendar');
 r:=public.control_forgestudio_publication(request,f.property_id,f.actor_id,input);
 perform pg_temp.check(r->>'state'='saved','future schedule change recorded');
 perform pg_temp.check(public.control_forgestudio_publication(request,f.property_id,f.actor_id,input)->>'state'='replayed','lost reschedule reply recovers the saved change');
 perform pg_temp.check((select p.scheduled_for=j.available_at and (a.execution_payload->>'scheduledFor')=(to_jsonb(p.scheduled_for)#>>'{}') from public.social_publications p join public.shared_jobs j on j.id=p.shared_job_id join public.shared_action_attempts a on a.id=p.shared_action_attempt_id where p.id=pub),'schedule, job due time and action payload change together');
 select updated_at into stamp from public.social_publications where id=pub;
 update public.shared_jobs set lease_owner='fixture-worker',lease_expires_at=clock_timestamp()+interval '5 minutes' where id=(select shared_job_id from public.social_publications where id=pub);
 input:=jsonb_build_object('action','cancel','publicationId',pub,'expectedUpdatedAt',stamp);request:=gen_random_uuid();
 perform pg_temp.check(public.control_forgestudio_publication(request,f.property_id,f.actor_id,input)->>'state'='publication_in_progress','claimed work cannot be cancelled as unattempted');
 update public.shared_jobs set lease_owner=null,lease_expires_at=null where id=(select shared_job_id from public.social_publications where id=pub);
 perform pg_temp.check(public.control_forgestudio_publication(request,f.property_id,f.actor_id,input)->>'state'='saved','unclaimed publication can be stopped');
 perform pg_temp.check(public.control_forgestudio_publication(request,f.property_id,f.actor_id,input)->>'state'='replayed','lost cancellation reply recovers original stop');
 perform pg_temp.check((select p.status='cancelled' and j.lifecycle_status='cancelled' and a.execution_status='cancelled' from public.social_publications p join public.shared_jobs j on j.id=p.shared_job_id join public.shared_action_attempts a on a.id=p.shared_action_attempt_id where p.id=pub),'cancellation updates publication, job and attempt together');
 update fixture set payload=jsonb_build_object('action','cancel','publicationId',(select id from public.social_publications where connection_id=second_connection),'expectedUpdatedAt',(select updated_at from public.social_publications where connection_id=second_connection));
end$$;
create function pg_temp.fail_publication_history() returns trigger language plpgsql as $$begin if new.action='studio.publication.cancel' then raise exception 'Fixture publication history failure';end if;return new;end$$;
create trigger publication_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_publication_history();
do $$declare f fixture;begin
 select * into f from fixture;
 begin perform public.control_forgestudio_publication(gen_random_uuid(),f.property_id,f.actor_id,f.payload);raise exception 'FAIL partial cancel';exception when raise_exception then if SQLERRM<>'Fixture publication history failure' then raise;end if;end;
 perform pg_temp.check((select p.status='scheduled' and j.lifecycle_status='queued' and a.execution_status='approved_pending_execution' from public.social_publications p join public.shared_jobs j on j.id=p.shared_job_id join public.shared_action_attempts a on a.id=p.shared_action_attempt_id where p.id=(f.payload->>'publicationId')::uuid),'history failure rolls back every cancellation projection');
end$$;
drop trigger publication_fixture_failure on public.shared_action_events;
do $$declare f fixture;pub public.social_publications;job public.shared_jobs;claim uuid:=gen_random_uuid();prepared jsonb;r jsonb;original_account text;begin
 select * into f from fixture;
 select * into pub from public.social_publications where property_id=f.property_id and status='scheduled';
 select * into job from public.shared_jobs where id=pub.shared_job_id;
 perform pg_temp.check(public.prepare_forgestudio_publication_write(job.id,'worker-one',claim)->>'state'='lease_lost','unclaimed work cannot acquire provider write permission');
 update public.shared_jobs set lifecycle_status='running',lease_owner='worker-one',lease_expires_at=clock_timestamp()+interval '5 minutes',attempt_count=1 where id=job.id;
 prepared:=public.prepare_forgestudio_publication_write(job.id,'worker-one',claim);
 perform pg_temp.check(prepared->>'state'='prepared','claimed exact approved destination prepares');
 perform pg_temp.check(not exists(select 1 from public.forgestudio_publication_receipts where publication_id=pub.id),'preflight creates no write permission');
 begin update public.social_connections set account_id='different-account' where id=pub.connection_id;raise exception 'FAIL changed identity';exception when raise_exception then if SQLERRM<>'Social destination identity cannot change' then raise;end if;end;
 perform pg_temp.check(true,'existing destination identity cannot be silently changed');
 update public.social_connections set access_token='encv1:changed-encrypted-credential' where id=pub.connection_id;
 perform pg_temp.check(public.prepare_forgestudio_publication_write(job.id,'worker-one',claim,prepared->>'fingerprint')->>'state'='destination_changed','credential change between validation and intent is held');
 update public.social_connections set access_token='encv1:fixture' where id=pub.connection_id;
 update public.social_connections set token_expires_at=clock_timestamp()-interval '1 day' where id=pub.connection_id;
 perform pg_temp.check(public.prepare_forgestudio_publication_write(job.id,'worker-one',claim)->>'state'='reconnect_required','expired credentials cannot be refreshed unsafely inside publication');
 update public.social_connections set token_expires_at=clock_timestamp()+interval '60 days' where id=pub.connection_id;
 perform pg_temp.check(public.prepare_forgestudio_publication_write(job.id,'other-worker',claim,prepared->>'fingerprint')->>'state'='lease_lost','another worker cannot write under the original lease');
 perform pg_temp.check(public.prepare_forgestudio_publication_write(job.id,'worker-one',claim,prepared->>'fingerprint')->>'state'='destination_changed','credential history cannot be reset by restoring earlier token bytes');
 prepared:=public.prepare_forgestudio_publication_write(job.id,'worker-one',claim);
 r:=public.prepare_forgestudio_publication_write(job.id,'worker-one',claim,prepared->>'fingerprint');
 perform pg_temp.check(r->>'state'='proceed_once','first exact intent grants one provider invocation');
 perform pg_temp.check(public.prepare_forgestudio_publication_write(job.id,'worker-one',claim,prepared->>'fingerprint')->>'state'='write_already_recorded','lost intent reply cannot grant another send');
 perform pg_temp.check((select count(*)=1 from public.forgestudio_publication_receipts where publication_id=pub.id and kind='write_intent') and (select count(*)=1 from public.social_publication_attempts where publication_id=pub.id),'intent and public attempt save together once');
 perform pg_temp.check(public.finish_forgestudio_publication_write(job.id,'other-worker',claim,'{"kind":"provider_acknowledged","providerPostId":"wrong"}')->>'state'='claim_mismatch','foreign worker cannot finish the intent');
 r:=public.finish_forgestudio_publication_write(job.id,'worker-one',claim,'{"kind":"provider_uncertain","reason":"Timed out after send"}');
 perform pg_temp.check(r->>'state'='saved' and r->>'status'='reconciling','uncertain provider result saves review hold');
 perform pg_temp.check(public.finish_forgestudio_publication_write(job.id,'worker-one',claim,'{"kind":"provider_uncertain","reason":"Timed out after send"}')->>'state'='replayed','lost uncertainty reply returns the same result');
 perform pg_temp.check((select lifecycle_status='failed' and lease_owner is null from public.shared_jobs where id=job.id),'uncertain write is never queued for automatic retry');
 select * into pub from public.social_publications where id=pub.id;
 r:=public.review_forgestudio_publication_recovery(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('publicationId',pub.id,'expectedUpdatedAt',pub.updated_at,'action','resume_before_send','reason','Reviewed the saved request and result'));
 perform pg_temp.check(r->>'state'='write_review_required','operator resume cannot resend an uncertain write');
 update fixture set payload=jsonb_build_object('publicationId',pub.id,'expectedUpdatedAt',pub.updated_at,'action','record_existing_post','reason','I checked the exact account and content at the destination','providerPostId','fixture-existing-post','providerPostUrl','https://example.invalid/post/fixture'),edited_id=gen_random_uuid();
 begin update public.forgestudio_publication_receipts set evidence='{}' where publication_id=pub.id;raise exception 'FAIL mutable receipt';exception when raise_exception then if SQLERRM<>'Publication evidence is immutable' then raise;end if;end;
 perform pg_temp.check(true,'system write and outcome evidence is immutable');
end$$;
do $$declare f fixture;r jsonb;begin
 select * into f from fixture;
 r:=public.review_forgestudio_publication_recovery(f.edited_id,f.property_id,f.actor_id,f.payload);
 perform pg_temp.check(r->>'state'='saved','operator can record a checked existing post without resending');
 perform pg_temp.check(public.review_forgestudio_publication_recovery(f.edited_id,f.property_id,f.actor_id,f.payload)->>'state'='replayed','lost operator review response recovers exact decision');
 perform pg_temp.check((select status='published' and remote_post_id='fixture-existing-post' from public.social_publications where id=(f.payload->>'publicationId')::uuid),'manual destination evidence records the provided post identity');
 perform pg_temp.check(exists(select 1 from public.forgestudio_publication_receipts where publication_id=(f.payload->>'publicationId')::uuid and kind='operator_attestation' and evidence->>'automaticallyVerified'='false' and evidence->>'actorId'=f.actor_id::text),'manual evidence explicitly differs from provider confirmation');
 perform pg_temp.check(exists(select 1 from public.shared_action_events where id=f.edited_id and action='studio.publication.recovery_reviewed'),'review and semantic action commit together');
end$$;

-- Reusing a cancelled destination creates a new request, without a dedupe collision.
do $$declare f fixture;prior public.social_publications;r jsonb;begin
 select * into f from fixture;select * into prior from public.social_publications where property_id=f.property_id and status='cancelled';
 update fixture set payload=jsonb_build_object('revisionId',f.revision_id,'contentHash',prior.delivery_snapshot->>'contentHash','destinations',jsonb_build_array(jsonb_build_object('connectionId',prior.connection_id,'variantId',prior.variant_id,'scheduledFor',clock_timestamp()+interval '4 days','timezone','UTC'))),edited_id=gen_random_uuid();
end$$;
create function pg_temp.fail_scheduling_history() returns trigger language plpgsql as $$begin if new.action='studio.publications.scheduled' then raise exception 'Fixture scheduling history failure';end if;return new;end$$;
create trigger publication_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_scheduling_history();
do $$declare f fixture;before_jobs int;begin
 select * into f from fixture;select count(*) into before_jobs from public.shared_jobs where property_id=f.property_id;
 begin perform public.schedule_forgestudio_publications(f.edited_id,f.property_id,f.actor_id,f.payload);raise exception 'FAIL partial schedule';exception when raise_exception then if SQLERRM<>'Fixture scheduling history failure' then raise;end if;end;
 perform pg_temp.check((select count(*)=before_jobs from public.shared_jobs where property_id=f.property_id) and not exists(select 1 from public.social_publications where property_id=f.property_id and status='scheduled'),'history failure rolls back complete new schedule graph');
end$$;
drop trigger publication_fixture_failure on public.shared_action_events;
do $$declare f fixture;r jsonb;pub public.social_publications;claim uuid:=gen_random_uuid();args jsonb;begin
 select * into f from fixture;r:=public.schedule_forgestudio_publications(f.edited_id,f.property_id,f.actor_id,f.payload);
 perform pg_temp.check(r->>'state'='saved','cancelled destination can be scheduled under a fresh request');
 select * into pub from public.social_publications where id=(r->'publications'->0->>'id')::uuid;
 begin update public.social_publications set delivery_snapshot='{}' where id=pub.id;raise exception 'FAIL mutable snapshot';exception when raise_exception then if SQLERRM<>'Create a new publication to change its approved content or destination' then raise;end if;end;
 perform pg_temp.check(true,'approved publication identity and destination snapshot cannot be rewritten');
 update public.shared_jobs set lifecycle_status='running',lease_owner='before-send-worker',lease_expires_at=clock_timestamp()+interval '1 minute',attempt_count=1 where id=pub.shared_job_id;
 r:=public.finish_forgestudio_publication_write(pub.shared_job_id,'before-send-worker',claim,'{"kind":"blocked_before_send","reason":"Missing local credentials"}');
 perform pg_temp.check(r->>'state'='saved' and r->>'status'='failed','before-send block records a non-provider failure');
 perform pg_temp.check(public.finish_forgestudio_publication_write(pub.shared_job_id,'before-send-worker',claim,'{"kind":"blocked_before_send","reason":"Missing local credentials"}')->>'state'='replayed','before-send result replays after its lease has closed');
 select * into pub from public.social_publications where id=pub.id;
 args:=jsonb_build_object('publicationId',pub.id,'expectedUpdatedAt',pub.updated_at,'action','resume_before_send','reason','Restored destination credentials and reviewed no-write evidence');
 r:=public.review_forgestudio_publication_recovery(gen_random_uuid(),f.property_id,f.actor_id,args);
 perform pg_temp.check(r->>'state'='saved','manager can resume a proven before-send failure');
 perform pg_temp.check((select lifecycle_status='queued' and max_attempts=2 and attempt_count=1 from public.shared_jobs where id=pub.shared_job_id),'resume grants one new claim without deleting earlier evidence');
 update public.shared_jobs set lifecycle_status='running',lease_owner='new-claim-worker',lease_expires_at=clock_timestamp()+interval '5 minutes',attempt_count=2 where id=pub.shared_job_id;
 update fixture set edited_id=gen_random_uuid(),payload=jsonb_build_object('publicationId',pub.id,'jobId',pub.shared_job_id);
end$$;
create function pg_temp.fail_write_intent() returns trigger language plpgsql as $$begin if new.kind='write_intent' then raise exception 'Fixture intent save failure';end if;return new;end$$;
create trigger publication_fixture_failure before insert on public.forgestudio_publication_receipts for each row execute function pg_temp.fail_write_intent();
do $$declare f fixture;r jsonb;begin
 select * into f from fixture;r:=public.prepare_forgestudio_publication_write((f.payload->>'jobId')::uuid,'new-claim-worker',f.edited_id);
 begin perform public.prepare_forgestudio_publication_write((f.payload->>'jobId')::uuid,'new-claim-worker',f.edited_id,r->>'fingerprint');raise exception 'FAIL partial intent';exception when raise_exception then if SQLERRM<>'Fixture intent save failure' then raise;end if;end;
 perform pg_temp.check((select status='queued' from public.social_publications where id=(f.payload->>'publicationId')::uuid) and not exists(select 1 from public.social_publication_attempts where publication_id=(f.payload->>'publicationId')::uuid),'failed intent persistence leaves publication and attempts unchanged');
end$$;
drop trigger publication_fixture_failure on public.forgestudio_publication_receipts;
do $$declare f fixture;r jsonb;begin
 select * into f from fixture;r:=public.prepare_forgestudio_publication_write((f.payload->>'jobId')::uuid,'new-claim-worker',f.edited_id);
 perform pg_temp.check(public.prepare_forgestudio_publication_write((f.payload->>'jobId')::uuid,'new-claim-worker',f.edited_id,r->>'fingerprint')->>'state'='proceed_once','intent succeeds after a proven rollback');
 r:=public.finish_forgestudio_publication_write((f.payload->>'jobId')::uuid,'new-claim-worker',f.edited_id,'{"kind":"provider_acknowledged","providerPostId":"fixture-acknowledged","providerPostUrl":"https://example.invalid/acknowledged"}');
 perform pg_temp.check(r->>'state'='saved' and r->>'status'='published','provider acknowledgement and all projections save together');
 perform pg_temp.check(public.finish_forgestudio_publication_write((f.payload->>'jobId')::uuid,'new-claim-worker',f.edited_id,'{"kind":"provider_acknowledged","providerPostId":"fixture-acknowledged","providerPostUrl":"https://example.invalid/acknowledged"}')->>'state'='replayed','acknowledged result recovers its lost response after the lease closes');
 perform pg_temp.check(public.finish_forgestudio_publication_write((f.payload->>'jobId')::uuid,'new-claim-worker',f.edited_id,'{"kind":"provider_uncertain","reason":"different result"}')->>'state'='result_conflict','saved acknowledgement cannot be replaced by an uncertain result');
 perform pg_temp.check((select p.status='published' and j.lifecycle_status='succeeded' and a.execution_status='executed' from public.social_publications p join public.shared_jobs j on j.id=p.shared_job_id join public.shared_action_attempts a on a.id=p.shared_action_attempt_id where p.id=(f.payload->>'publicationId')::uuid),'published state, job, and execution result agree');
 perform pg_temp.check(not has_table_privilege('authenticated','public.forgestudio_publication_receipts','select') and not has_function_privilege('authenticated','public.prepare_forgestudio_publication_write(uuid,text,uuid,text)','execute'),'browser cannot read private worker receipts or authorize provider writes directly');
end$$;

do $$declare f fixture;connection uuid:=gen_random_uuid();variant uuid;hash text;r jsonb;pub public.social_publications;claim uuid:=gen_random_uuid();begin
 select * into f from fixture;select id into variant from public.social_content_variants where revision_id=f.revision_id limit 1;select content_hash into hash from public.social_content_revisions where id=f.revision_id;
 insert into public.social_connections(id,property_id,platform,account_id,is_active) values(connection,f.property_id,'facebook','late-result-fixture',true);
 update public.social_connections set access_token='encv1:fixture',page_access_token='encv1:page',page_id=account_id,scopes=array['pages_show_list','pages_read_engagement','pages_manage_posts'],token_expires_at=clock_timestamp()+interval '60 days',permission_evidence='{"source":"provider_response","expiryKnown":true}' where property_id=f.property_id and access_token is null;
 r:=public.schedule_forgestudio_publications(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('revisionId',f.revision_id,'contentHash',hash,'destinations',jsonb_build_array(jsonb_build_object('connectionId',connection,'variantId',variant,'scheduledFor',clock_timestamp()+interval '1 day','timezone','UTC'))));
 select * into pub from public.social_publications where id=(r->'publications'->0->>'id')::uuid;
 update public.shared_jobs set lifecycle_status='running',lease_owner='late-worker',lease_expires_at=clock_timestamp()+interval '5 minutes',attempt_count=1 where id=pub.shared_job_id;
 r:=public.prepare_forgestudio_publication_write(pub.shared_job_id,'late-worker',claim);
 perform pg_temp.check(public.prepare_forgestudio_publication_write(pub.shared_job_id,'late-worker',claim,r->>'fingerprint')->>'state'='proceed_once','late-result fixture has exactly one saved provider intent');
 update fixture set edited_id=claim,payload=jsonb_build_object('jobId',pub.shared_job_id,'publicationId',pub.id);
end$$;
create function pg_temp.fail_result_receipt() returns trigger language plpgsql as $$begin if new.kind='provider_acknowledged' then raise exception 'Fixture result save failure';end if;return new;end$$;
create trigger publication_fixture_failure before insert on public.forgestudio_publication_receipts for each row execute function pg_temp.fail_result_receipt();
do $$declare f fixture;begin
 select * into f from fixture;
 begin perform public.finish_forgestudio_publication_write((f.payload->>'jobId')::uuid,'late-worker',f.edited_id,'{"kind":"provider_acknowledged","providerPostId":"actual-provider-post","providerPostUrl":"https://example.invalid/actual-provider-post"}');raise exception 'FAIL partial result';exception when raise_exception then if SQLERRM<>'Fixture result save failure' then raise;end if;end;
 perform pg_temp.check((select p.status='publishing' and j.lifecycle_status='running' from public.social_publications p join public.shared_jobs j on j.id=p.shared_job_id where p.id=(f.payload->>'publicationId')::uuid),'failed result persistence leaves the pending intent intact without a false success');
end$$;
drop trigger publication_fixture_failure on public.forgestudio_publication_receipts;
do $$declare f fixture;pub public.social_publications;r jsonb;begin
 select * into f from fixture;select * into pub from public.social_publications where id=(f.payload->>'publicationId')::uuid;
 update public.shared_jobs set lease_expires_at=clock_timestamp()-interval '1 minute' where id=pub.shared_job_id;
 r:=public.review_forgestudio_publication_recovery(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('publicationId',pub.id,'expectedUpdatedAt',pub.updated_at,'action','record_existing_post','reason','Manager reviewed what appeared to be the existing post','providerPostId','operator-recorded-post','providerPostUrl','https://example.invalid/operator-recorded-post'));
 perform pg_temp.check(r->>'state'='saved','expired worker intent can be reviewed without another send');
 r:=public.finish_forgestudio_publication_write(pub.shared_job_id,'late-worker',f.edited_id,'{"kind":"provider_acknowledged","providerPostId":"actual-provider-post","providerPostUrl":"https://example.invalid/actual-provider-post"}');
 perform pg_temp.check(r->>'state'='saved' and r->>'status'='reconciling','conflicting late acknowledgement creates an explicit review hold');
 perform pg_temp.check((select status='in_review' from public.social_content_packages where id=pub.package_id),'conflicting provider evidence removes the false published campaign badge');
 perform pg_temp.check((select count(*)=3 from public.forgestudio_publication_receipts where publication_id=pub.id),'late provider and prior manager evidence both remain immutable');
 perform pg_temp.check((select p.status='reconciling' and p.remote_post_id='operator-recorded-post' and j.lifecycle_status='failed' and j.status_reason='provider_review_conflict' from public.social_publications p join public.shared_jobs j on j.id=p.shared_job_id where p.id=pub.id),'conflict preserves the reviewed identity and never queues a resend');
end$$;

select count(*) as assertions from checks;
rollback;
