begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,authorization_id uuid,connection_id uuid,claim_token uuid,payload jsonb,result jsonb,queued_id uuid,published_id uuid);
insert into fixture values(gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),null,jsonb_build_object('platform','facebook','credentialFingerprint',repeat('a',64),'redirectUri','http://localhost/api/forgestudio/social/callback/facebook','scopes',array['pages_show_list','pages_read_engagement','pages_manage_posts']),null,null,null);
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','ForgeStudio connection rollback fixture' from fixture;
create function pg_temp.account_result(account_id text) returns jsonb language sql as $$select jsonb_build_object('status','observed','observedAt',clock_timestamp(),'accounts',jsonb_build_array(jsonb_build_object('accountId',account_id,'accountName','Reviewed account','platform','facebook','accessTokenEncrypted','encv1:private-token','pageAccessTokenEncrypted','encv1:private-page','pageId',account_id,'scopes',array['pages_show_list','pages_read_engagement','pages_manage_posts'],'expiresAt',clock_timestamp()+interval '60 days','permissionEvidence',jsonb_build_object('source','provider_response','expiryKnown',true))));$$;
do $$declare f fixture;r jsonb;begin select * into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.social_connections','select') and not has_table_privilege('authenticated','public.social_auth_configs','select') and not has_table_privilege('authenticated','public.forgestudio_authorizations','select'),'browser roles cannot read private provider/app credentials');
 perform pg_temp.check(not has_function_privilege('authenticated','public.apply_forgestudio_authorization(uuid,uuid,uuid,jsonb)','execute'),'browser cannot bypass the reviewed API');
 perform pg_temp.check(public.begin_forgestudio_authorization(f.authorization_id,f.property_id,gen_random_uuid(),f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:secret"}')->>'state'='forbidden','unscoped actor cannot authorize');
 r:=public.begin_forgestudio_authorization(f.authorization_id,f.property_id,f.actor_id,f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:secret","codeVerifierEncrypted":"encv1:original"}');
 perform pg_temp.check(r->>'state'='pending','authorization saves before provider exchange');
 r:=public.begin_forgestudio_authorization(f.authorization_id,f.property_id,f.actor_id,f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:new-random-iv","codeVerifierEncrypted":"encv1:new"}');
 perform pg_temp.check(r->'credentials'->>'codeVerifierEncrypted'='encv1:original','retried start uses the exact saved PKCE verifier');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='studio.authorization.started'),'start has exactly one semantic decision');
 perform pg_temp.check(public.claim_forgestudio_authorization(f.authorization_id,f.property_id,f.actor_id,'linkedin',repeat('b',64),repeat('a',64))->>'state'='not_found','signed request cannot cross provider callbacks');
 r:=public.claim_forgestudio_authorization(f.authorization_id,f.property_id,f.actor_id,'facebook',repeat('b',64),repeat('a',64));update fixture set claim_token=(r->>'claimToken')::uuid,result=pg_temp.account_result('fixture-one');
 perform pg_temp.check(r->>'state'='exchange_once','first callback obtains one exchange intent');
 perform pg_temp.check(public.claim_forgestudio_authorization(f.authorization_id,f.property_id,f.actor_id,'facebook',repeat('b',64),repeat('a',64))->>'state'='exchanging','concurrent or interrupted callback never repeats code exchange');
end$$;
do $$declare f fixture;r jsonb;review uuid:=gen_random_uuid();payload jsonb;begin select * into f from fixture;
 perform pg_temp.check(public.finish_forgestudio_authorization(f.authorization_id,gen_random_uuid(),f.result)->>'state'='claim_mismatch','another callback cannot save a result');
 r:=public.finish_forgestudio_authorization(f.authorization_id,f.claim_token,f.result);perform pg_temp.check(r->>'authorizationState'='review_required' and not exists(select 1 from public.social_connections where property_id=f.property_id),'saved grant requires explicit account review before activation');
 perform pg_temp.check(public.finish_forgestudio_authorization(f.authorization_id,f.claim_token,f.result)->>'state'='replayed','lost grant-save response reuses identical saved evidence');
 perform pg_temp.check(public.finish_forgestudio_authorization(f.authorization_id,f.claim_token,f.result||'{"reason":"different"}')->>'state'='result_conflict','grant evidence cannot be changed on retry');
 payload:=jsonb_build_object('authorizationId',f.authorization_id,'expectedVersion',2,'accountIds',array['fixture-one'],'reason','Reviewed this exact property account');
 perform pg_temp.check(public.apply_forgestudio_authorization(review,f.property_id,gen_random_uuid(),payload)->>'state'='forbidden','account selection requires a current property manager');
 perform pg_temp.check(public.apply_forgestudio_authorization(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"accountIds":["unrelated"]}')->>'state'='grant_review_required','unobserved accounts cannot be selected');
 r:=public.apply_forgestudio_authorization(review,f.property_id,f.actor_id,payload);update fixture set connection_id=(r->'connectionIds'->>0)::uuid;
 perform pg_temp.check(r->>'state'='saved' and r->>'publicationStarted'='false','review connects only the selected account and does not publish');
 perform pg_temp.check(public.apply_forgestudio_authorization(review,f.property_id,f.actor_id,payload)->>'state'='replayed','lost account-review response recovers one decision');
 perform pg_temp.check((select raw_profile='{}'::jsonb and permission_evidence->>'source'='provider_response' and security_version=1 and public.forgestudio_social_grant_ready(c) from public.social_connections c where property_id=f.property_id),'saved active grant is encrypted, evidenced and versioned');
 perform pg_temp.check(not exists(select 1 from public.shared_action_events where property_id=f.property_id and (result::text||coalesce(before_state::text,'')||coalesce(after_state::text,'')) like '%encv1:%'),'shared history contains no encrypted or plaintext credentials');
end$$;
do $$declare f fixture;a uuid:=gen_random_uuid();r jsonb;proof jsonb;payload jsonb;claim uuid;before_count integer;begin select * into f from fixture;
 select count(*) into before_count from public.social_connections where property_id=f.property_id;
 perform public.begin_forgestudio_authorization(a,f.property_id,f.actor_id,f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:secret"}');r:=public.claim_forgestudio_authorization(a,f.property_id,f.actor_id,'facebook',repeat('b',64),repeat('a',64));claim:=(r->>'claimToken')::uuid;
 proof:=pg_temp.account_result('candidate-good');proof:=jsonb_set(proof,'{accounts}',proof->'accounts'||jsonb_build_array((pg_temp.account_result('candidate-bad')->'accounts'->0)||'{"scopes":[]}'::jsonb));perform public.finish_forgestudio_authorization(a,claim,proof);
 payload:=jsonb_build_object('authorizationId',a,'expectedVersion',2,'accountIds',array['candidate-good','candidate-bad'],'reason','Review both candidate accounts');
 perform pg_temp.check(public.apply_forgestudio_authorization(gen_random_uuid(),f.property_id,f.actor_id,payload)->>'state'='grant_review_required' and(select count(*)=before_count from public.social_connections where property_id=f.property_id),'one incomplete grant prevents partial activation of a selected group');
 begin perform public.apply_forgestudio_authorization(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"accountIds":[null]}');raise exception 'FAIL null account';exception when raise_exception then if SQLERRM<>'An account may only be selected once' then raise;end if;end;
 perform pg_temp.check(true,'null account selection cannot bypass grant validation');
 perform pg_temp.check(public.cancel_forgestudio_authorization(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('authorizationId',a,'expectedVersion',1,'reason','Cancel old view'))->>'state'='stale_authorization','cancellation requires the current authorization version');
 r:=public.cancel_forgestudio_authorization(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('authorizationId',a,'expectedVersion',2,'reason','Cancel the incomplete provider grant'));
 perform pg_temp.check(r->>'state'='saved' and(select state='cancelled' from public.forgestudio_authorizations where id=a),'explicit review cancellation closes the saved grant');
 a:=gen_random_uuid();perform public.begin_forgestudio_authorization(a,f.property_id,f.actor_id,f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:secret"}');
 perform pg_temp.check(public.claim_forgestudio_authorization(a,f.property_id,f.actor_id,'facebook',repeat('b',64),repeat('c',64))->>'state'='held','changed app credentials fence a pending callback');
end$$;
-- Create both an unstarted publication and a published one on the same destination.
do $$declare f fixture;r jsonb;revision uuid;variant uuid;hash text;begin select * into f from fixture;
 for i in 1..2 loop
  revision:=gen_random_uuid();r:=public.save_forgestudio_revision(revision,f.property_id,f.actor_id,jsonb_build_object('content',jsonb_build_object('contractVersion','forgestudio.social.v1','conceptSummary','Account continuity','variants',jsonb_build_array(jsonb_build_object('variantKey','primary','sequenceIndex',0,'platform','facebook','caption','Explore our community.','hashtags','[]'::jsonb,'assetIds','[]'::jsonb,'mediaUrls','[]'::jsonb,'contentFormat','text')),'claims','[]'::jsonb),'authorKind','user','validation','[[]]'::jsonb));
  hash:=r->'revision'->>'content_hash';select id into variant from public.social_content_variants where revision_id=revision;
  perform public.review_forgestudio_revision(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('revisionId',revision,'contentHash',hash,'decision','approved','note','Reviewed exact campaign copy'));
  r:=public.schedule_forgestudio_publications(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('revisionId',revision,'contentHash',hash,'destinations',jsonb_build_array(jsonb_build_object('connectionId',f.connection_id,'variantId',variant,'scheduledFor',clock_timestamp()+interval '1 day','timezone','America/Los_Angeles'))));
  if i=1 then update fixture set queued_id=(r->'publications'->0->>'id')::uuid;else update fixture set published_id=(r->'publications'->0->>'id')::uuid;update public.social_publications set status='published',remote_post_id='prior-published-post',published_at=clock_timestamp()-interval '1 day' where id=(r->'publications'->0->>'id')::uuid;end if;
 end loop;
end$$;
do $$declare f fixture;r jsonb;decision uuid:=gen_random_uuid();a uuid:=gen_random_uuid();claim uuid;proof jsonb;payload jsonb;begin select * into f from fixture;
 perform public.begin_forgestudio_authorization(a,f.property_id,f.actor_id,f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:secret"}');r:=public.claim_forgestudio_authorization(a,f.property_id,f.actor_id,'facebook',repeat('b',64),repeat('a',64));claim:=(r->>'claimToken')::uuid;
 payload:=jsonb_build_object('connectionId',f.connection_id,'expectedVersion',1,'reason','Retire local access for this account');
 perform pg_temp.check(public.disconnect_forgestudio_connection(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"expectedVersion":9}')->>'state'='stale_connection','stale disconnect cannot retire newer credentials');
 r:=public.disconnect_forgestudio_connection(decision,f.property_id,f.actor_id,payload);
 perform pg_temp.check(r->>'state'='saved' and r->>'cancelledCount'='1','disconnect cancels the unstarted publication');
 perform pg_temp.check(public.disconnect_forgestudio_connection(decision,f.property_id,f.actor_id,payload)->>'state'='replayed','lost disconnect response replays one decision');
 perform pg_temp.check((select status='cancelled' from public.social_publications where id=f.queued_id) and (select lifecycle_status='cancelled' from public.shared_jobs where id=(select shared_job_id from public.social_publications where id=f.queued_id)),'publication and shared work stop together');
 perform pg_temp.check((select status='published' and remote_post_id='prior-published-post' from public.social_publications where id=f.published_id),'published history and remote identity survive disconnect');
 perform pg_temp.check((select not is_active and access_token is null and page_access_token is null and security_version=2 and disconnected_at is not null and not public.forgestudio_social_grant_ready(c) from public.social_connections c where id=f.connection_id),'local credentials clear without deleting destination identity');
 proof:=pg_temp.account_result('fixture-one');r:=public.finish_forgestudio_authorization(a,claim,proof);
 perform pg_temp.check(r->>'authorizationState'='held' and (select result=proof from public.forgestudio_authorizations where id=a),'late callback is retained privately but cannot restore disconnected access');
 perform pg_temp.check(public.apply_forgestudio_authorization(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('authorizationId',a,'expectedVersion',3,'accountIds',array['fixture-one'],'reason','Try stale consent'))->>'state'='authorization_closed','operator cannot apply held late consent');
 begin delete from public.social_connections where id=f.connection_id;raise exception 'FAIL deleted history';exception when raise_exception then if SQLERRM<>'Disconnect the account while retaining publication history' then raise;end if;end;
 perform pg_temp.check(true,'even direct destination deletion cannot cascade publication history');
end$$;
do $$declare f fixture;r jsonb;a uuid:=gen_random_uuid();review uuid:=gen_random_uuid();payload jsonb;begin select * into f from fixture;
 r:=public.begin_forgestudio_authorization(a,f.property_id,f.actor_id,f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:secret"}');r:=public.claim_forgestudio_authorization(a,f.property_id,f.actor_id,'facebook',repeat('b',64),repeat('a',64));perform public.finish_forgestudio_authorization(a,(r->>'claimToken')::uuid,pg_temp.account_result('fixture-one'));
 payload:=jsonb_build_object('authorizationId',a,'expectedVersion',2,'accountIds',array['fixture-one'],'reason','Renew consent for the same reviewed account');r:=public.apply_forgestudio_authorization(review,f.property_id,f.actor_id,payload);
 perform pg_temp.check(r->'connectionIds'->>0=f.connection_id::text and(select security_version=3 and is_active from public.social_connections where id=f.connection_id),'fresh reviewed consent renews the exact existing destination');
 perform pg_temp.check((select status='cancelled' from public.social_publications where id=f.queued_id),'renewal never silently resumes cancelled publications');
 a:=gen_random_uuid();perform public.begin_forgestudio_authorization(a,f.property_id,f.actor_id,f.payload,'{"appId":"test-app","appSecretEncrypted":"encv1:secret"}');
 payload:=jsonb_build_object('action','save','platform','meta','expectedVersion',0,'appId','new-app','secretFingerprint',repeat('c',64));review:=gen_random_uuid();r:=public.save_forgestudio_social_config(review,f.property_id,f.actor_id,payload,'encv1:private-app');
 perform pg_temp.check(r->>'state'='saved' and r->>'version'='1','app credentials save with an exact initial version');
 perform pg_temp.check(public.save_forgestudio_social_config(review,f.property_id,f.actor_id,payload,'encv1:new-random-iv')->>'state'='replayed','encrypted random IV does not change app decision identity');
 perform pg_temp.check((select state='held' from public.forgestudio_authorizations where id=a),'app rotation closes unfinished authorizations');
 perform pg_temp.check(public.save_forgestudio_social_config(gen_random_uuid(),f.property_id,f.actor_id,payload,'encv1:another')->>'state'='stale_configuration','older app form cannot replace new credentials');
 r:=public.save_forgestudio_social_config(gen_random_uuid(),f.property_id,f.actor_id,'{"action":"disable","platform":"meta","expectedVersion":1}');
 perform pg_temp.check(r->>'version'='2' and (select not is_configured and app_secret_encrypted='' from public.social_auth_configs where property_id=f.property_id),'disabled app retains a versioned tombstone and clears its secret');
end$$;
create function pg_temp.fail_connection_history() returns trigger language plpgsql as $$begin if new.action='studio.connection.disconnected' then raise exception 'Fixture connection history failure';end if;return new;end$$;
create trigger connection_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_connection_history();
do $$declare f fixture;begin select * into f from fixture;
 begin perform public.disconnect_forgestudio_connection(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('connectionId',f.connection_id,'expectedVersion',3,'reason','History failure test'));raise exception 'FAIL missing event';exception when raise_exception then if SQLERRM<>'Fixture connection history failure' then raise;end if;end;
 perform pg_temp.check((select is_active and security_version=3 from public.social_connections where id=f.connection_id),'connection mutation rolls back when semantic evidence fails');
end$$;
drop trigger connection_fixture_failure on public.shared_action_events;
select count(*) as passed_assertions from checks;
rollback;
