begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,brief_id uuid,generation_id uuid,token uuid,input jsonb,raw jsonb,content jsonb,recovery_id uuid);
insert into fixture select gen_random_uuid(),id,gen_random_uuid(),gen_random_uuid(),null,null,null,'{"contractVersion":"forgestudio.social.v1","conceptSummary":"Saved generation fixture","variants":[{"variantKey":"facebook:text:1","sequenceIndex":0,"platform":"facebook","caption":"Welcome to this community.","hashtags":[],"assetIds":[],"mediaUrls":[],"contentFormat":"text"}],"claims":[]}',gen_random_uuid() from public.profiles where org_id='22222222-2222-2222-2222-222222222222' and role='admin' limit 1;
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','ForgeStudio generation rollback fixture' from fixture;
do $$declare f fixture;r jsonb;begin
 select * into f from fixture;
 r:=public.save_forgestudio_brief(f.brief_id,f.property_id,f.actor_id,'{"title":"Saved generation fixture","objective":"Explain the community","channels":["facebook"],"formatPlan":[{"platform":"facebook","contentFormat":"text","quantity":1}]}');
 perform pg_temp.check(r->>'state'='saved','generation starts from a real saved brief');
 perform pg_temp.check(public.begin_forgestudio_generation(f.generation_id,f.property_id,gen_random_uuid(),f.brief_id)->>'state'='forbidden','request requires current property access');
 r:=public.begin_forgestudio_generation(f.generation_id,f.property_id,f.actor_id,f.brief_id);
 perform pg_temp.check(r->>'state'='claimed' and r->>'claimToken' is not null,'first request receives a unique generation claim');
 update fixture set token=(r->>'claimToken')::uuid,input=jsonb_build_object('bundle',jsonb_build_object('propertyId',f.property_id,'contextHash','fixture-context-hash','sources','[]'::jsonb,'assets','[]'::jsonb),'objective','Explain the community','channels','["facebook"]'::jsonb,'formatPlan','[{"platform":"facebook","contentFormat":"text","quantity":1}]'::jsonb),raw=jsonb_build_object('output',f.content,'metadata',jsonb_build_object('model','fixture-model','promptVersion','forgestudio.generation.v1','contractVersion','forgestudio.social.v1','usage',jsonb_build_object('inputTokens',10,'outputTokens',15)));
 r:=public.begin_forgestudio_generation(f.generation_id,f.property_id,f.actor_id,f.brief_id);
 perform pg_temp.check(r->>'state'='preparing' and not(r?'claimToken'),'lost start reply returns status without another execution claim');
 perform pg_temp.check(public.begin_forgestudio_generation(gen_random_uuid(),f.property_id,f.actor_id,f.brief_id)->>'state'='busy','a second request cannot start against an active brief');
 perform pg_temp.check((select count(*)=1 from public.forgestudio_generations where brief_id=f.brief_id),'one active generation exists');
 perform pg_temp.check(exists(select 1 from public.shared_action_events where id=f.generation_id and action='studio.generation.requested'),'request and attributed decision commit together');
 perform pg_temp.check(not has_table_privilege('authenticated','public.forgestudio_generations','select') and not has_function_privilege('authenticated','public.advance_forgestudio_generation(uuid,uuid,text,jsonb)','execute'),'browser cannot read raw model context or invoke worker transitions');
end$$;
do $$declare f fixture;r jsonb;begin
 select * into f from fixture;
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,gen_random_uuid(),'context',f.input)->>'state'='claim_mismatch','another worker cannot save the context');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'model_intent','{}')->>'state'='context_required','model cannot run before context is durably saved');
 r:=public.advance_forgestudio_generation(f.generation_id,f.token,'context',f.input);
 perform pg_temp.check(r->>'state'='saved' and r->>'contextId' is not null,'input, context snapshot and receipt save together');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'context',f.input)->>'state'='replayed','lost context reply recovers the same saved snapshot');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'context',f.input||'{"objective":"different"}')->>'state'='input_conflict','saved model input cannot drift');
 perform pg_temp.check((select count(*)=1 from public.shared_context_snapshots where property_id=f.property_id),'context replay does not create another snapshot');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'raw_result',f.raw)->>'state'='model_intent_required','unsolicited output cannot create a generation result');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'model_intent','{}')->>'state'='proceed_once','first saved model intent grants one invocation');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'model_intent','{}')->>'state'='model_already_started','a repeated intent can never invoke the model again');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'raw_result',f.raw)->>'state'='saved','raw model result is retained before materialization');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'raw_result',f.raw)->>'state'='replayed','lost raw-result reply recovers exact evidence');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'raw_result',f.raw||'{"output":{"changed":true}}')->>'state'='result_conflict','another model result cannot replace the saved output');
 perform pg_temp.check(public.advance_forgestudio_generation(f.generation_id,f.token,'failure','{"code":"model_uncertain"}')->>'state'='result_ready','a saved result is not erased by a late generic failure');
 perform pg_temp.check(public.finish_forgestudio_generation(f.generation_id,f.property_id,f.actor_id,jsonb_build_object('resultHash','wrong','content',f.content,'validation','[[]]'::jsonb))->>'state'='result_conflict','materialization binds the exact raw result');
 begin update public.forgestudio_generations set raw_result='{}' where id=f.generation_id;raise exception 'FAIL mutable raw';exception when raise_exception then if SQLERRM<>'Generation inputs and results are immutable' then raise;end if;end;
 perform pg_temp.check(true,'raw result is immutable');
end$$;
create function pg_temp.fail_generation_history() returns trigger language plpgsql as $$begin if new.action='studio.package.created' then raise exception 'Fixture generation history failure';end if;return new;end$$;
create trigger generation_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_generation_history();
do $$declare f fixture;begin
 select * into f from fixture;
 begin perform public.finish_forgestudio_generation(f.generation_id,f.property_id,f.actor_id,jsonb_build_object('resultHash',public.crm_configuration_hash(f.raw),'content',f.content,'validation','[[]]'::jsonb));raise exception 'FAIL partial generated package';exception when raise_exception then if SQLERRM<>'Fixture generation history failure' then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.social_content_packages where property_id=f.property_id) and (select state='result_ready' and raw_result=f.raw from public.forgestudio_generations where id=f.generation_id),'failed package transaction preserves recoverable raw result without partial package');
end$$;
drop trigger generation_fixture_failure on public.shared_action_events;
do $$declare f fixture;r jsonb;payload jsonb;begin
 select * into f from fixture;payload:=jsonb_build_object('generationId',f.generation_id,'resultHash',public.crm_configuration_hash(f.raw),'content',f.content,'validation','[[]]'::jsonb);
 r:=public.recover_forgestudio_generation(f.recovery_id,f.property_id,f.actor_id,payload);
 perform pg_temp.check(r->>'state'='saved' and r->>'packageId' is not null,'operator recovery materializes the saved result without a model call');
 perform pg_temp.check(public.recover_forgestudio_generation(f.recovery_id,f.property_id,f.actor_id,payload)->>'state'='replayed','lost recovery reply returns the same generated package');
 perform pg_temp.check((select count(*)=1 from public.social_content_packages where brief_id=f.brief_id) and (select count(*)=1 from public.social_content_revisions where property_id=f.property_id),'recovery creates exactly one package and revision');
 perform pg_temp.check((select g.state='completed' and b.status='generated' and r.context_snapshot_id=g.context_id and r.authored_by_kind='llm' from public.forgestudio_generations g join public.social_content_briefs b on b.id=g.brief_id join public.social_content_revisions r on r.id=g.revision_id where g.id=f.generation_id),'generation state, brief, authored kind and exact context stay consistent');
 perform pg_temp.check(exists(select 1 from public.shared_action_events where id=f.recovery_id and action='studio.generation.recovered'),'human recovery decision is recorded atomically');
 perform pg_temp.check(public.begin_forgestudio_generation(gen_random_uuid(),f.property_id,f.actor_id,f.brief_id)->>'state'='draft_exists','completed brief cannot accidentally generate another package');
end$$;
-- A stopped in-flight request may retain a late result, but cannot apply it.
do $$declare f fixture;brief uuid:=gen_random_uuid();generation uuid:=gen_random_uuid();token uuid;stop uuid:=gen_random_uuid();r jsonb;payload jsonb;stamp timestamptz;begin
 select * into f from fixture;perform public.save_forgestudio_brief(brief,f.property_id,f.actor_id,'{"title":"Stop fixture","objective":"Explain the community","channels":["facebook"],"formatPlan":[{"platform":"facebook","contentFormat":"text","quantity":1}]}');
 r:=public.begin_forgestudio_generation(generation,f.property_id,f.actor_id,brief);token:=(r->>'claimToken')::uuid;
 perform public.advance_forgestudio_generation(generation,token,'context',f.input);perform public.advance_forgestudio_generation(generation,token,'model_intent','{}');
 perform public.advance_forgestudio_generation(generation,token,'failure','{"code":"model_uncertain"}');
 perform pg_temp.check(public.begin_forgestudio_generation(gen_random_uuid(),f.property_id,f.actor_id,brief)->>'state'='busy','uncertain model result holds new automatic work on its brief');
 select updated_at into stamp from public.forgestudio_generations where id=generation;
 payload:=jsonb_build_object('generationId',generation,'expectedUpdatedAt',stamp,'reason','Stop this uncertain request and retain its evidence');
 perform pg_temp.check(public.stop_forgestudio_generation(stop,f.property_id,f.actor_id,payload||jsonb_build_object('expectedUpdatedAt',clock_timestamp()-interval '1 day'))->>'state'='stale_generation','stop requires the opened generation version');
 perform pg_temp.check(public.stop_forgestudio_generation(stop,f.property_id,f.actor_id,payload)->>'state'='saved','operator can stop uncertain work explicitly');
 perform pg_temp.check(public.stop_forgestudio_generation(stop,f.property_id,f.actor_id,payload)->>'state'='replayed','lost stop response recovers the original decision');
 r:=public.advance_forgestudio_generation(generation,token,'raw_result',f.raw);
 perform pg_temp.check(r->>'state'='saved' and r->>'generationState'='stopped','late output is retained without reversing the stop');
 perform pg_temp.check(public.finish_forgestudio_generation(generation,f.property_id,f.actor_id,jsonb_build_object('resultHash',public.crm_configuration_hash(f.raw),'content',f.content,'validation','[[]]'::jsonb))->>'state'='stopped','stopped output cannot silently create a campaign');
 perform pg_temp.check(not exists(select 1 from public.social_content_packages where brief_id=brief),'no package exists for a stopped generation');
 perform pg_temp.check(exists(select 1 from public.forgestudio_generation_receipts where generation_id=generation and kind='stopped' and evidence->>'providerCancellationConfirmed'='false'),'stop does not claim remote cancellation or refunded model cost');
end$$;
select count(*) as assertions from checks;
rollback;
