begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,connection_id uuid,renewal_id uuid,claim_token uuid,result jsonb);
insert into fixture values(gen_random_uuid(),'11111111-1111-1111-1111-111111111111',null,gen_random_uuid(),null,null);
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','ForgeStudio renewal rollback fixture' from fixture;
create function pg_temp.proof(account_id text,platform text default 'x') returns jsonb language sql as $$select jsonb_build_object('status','observed','observedAt',clock_timestamp(),'accounts',jsonb_build_array(jsonb_build_object('platform',platform,'accountId',account_id,'accountName','Renewal fixture','accessTokenEncrypted','encv1:access','refreshTokenEncrypted','encv1:refresh','pageAccessTokenEncrypted',case when platform='facebook' then 'encv1:page' end,'pageId',case when platform='facebook' then account_id end,'expiresAt',clock_timestamp()+interval '1 day','refreshExpiresAt',clock_timestamp()+interval '30 days','scopes',case when platform='facebook' then array['pages_show_list','pages_read_engagement','pages_manage_posts'] else array['tweet.read','tweet.write','users.read'] end,'permissionEvidence',jsonb_build_object('source','provider_response','expiryKnown',true))));$$;
create function pg_temp.connect(account_id text,platform text default 'x') returns uuid language plpgsql as $$declare f fixture;a uuid:=gen_random_uuid();r jsonb;begin
 select * into f from fixture;
 perform public.begin_forgestudio_authorization(a,f.property_id,f.actor_id,jsonb_build_object('platform',platform,'credentialFingerprint',repeat('a',64),'redirectUri','http://localhost/callback','scopes',case when platform='facebook' then array['pages_show_list','pages_read_engagement','pages_manage_posts'] else array['tweet.read','tweet.write','users.read'] end),'{"appId":"fixture-app","appSecretEncrypted":"encv1:secret"}');
 r:=public.claim_forgestudio_authorization(a,f.property_id,f.actor_id,platform,repeat('b',64),repeat('a',64));perform public.finish_forgestudio_authorization(a,(r->>'claimToken')::uuid,pg_temp.proof(account_id,platform));
 r:=public.apply_forgestudio_authorization(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('authorizationId',a,'expectedVersion',2,'accountIds',array[account_id],'reason','Reviewed exact renewal fixture'));
 if r->>'state'<>'saved' then raise exception 'Fixture connect failed %',r;end if;return (r->'connectionIds'->>0)::uuid;
end$$;
create function pg_temp.start_renewal(connection_id uuid,request_id uuid default gen_random_uuid()) returns jsonb language plpgsql as $$declare f fixture;v integer;begin select * into f from fixture;select security_version into v from public.social_connections where id=connection_id;
 return public.begin_forgestudio_renewal(request_id,f.property_id,f.actor_id,jsonb_build_object('connectionId',connection_id,'expectedVersion',v,'reason','Renew saved access'),repeat('a',64),'{"appId":"fixture-app","appSecretEncrypted":"encv1:secret","redirectUri":"http://localhost/callback"}');end$$;
update fixture set connection_id=pg_temp.connect('original');
do $$declare f fixture;r jsonb;begin select * into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.forgestudio_renewals','select') and not has_table_privilege('anon','public.forgestudio_renewals','select'),'private rotation receipts are not browser-readable');
 perform pg_temp.check(not has_function_privilege('authenticated','public.begin_forgestudio_renewal(uuid,uuid,uuid,jsonb,text,jsonb)','execute'),'browser cannot bypass renewal API');
 perform pg_temp.check((select refresh_token_expires_at>clock_timestamp()+interval '29 days' from public.social_connections where id=f.connection_id),'authorization retains provider refresh expiry');
 perform pg_temp.check(public.begin_forgestudio_renewal(f.renewal_id,f.property_id,gen_random_uuid(),'{}',repeat('a',64),'{}')->>'state'='forbidden','unscoped actor cannot start renewal');
 perform pg_temp.check(public.begin_forgestudio_renewal(f.renewal_id,f.property_id,f.actor_id,jsonb_build_object('connectionId',f.connection_id,'expectedVersion',9,'reason','Old account view'),repeat('a',64),'{}')->>'state'='stale_connection','stale connection version cannot begin an exchange');
 perform pg_temp.check(public.begin_forgestudio_renewal(f.renewal_id,f.property_id,f.actor_id,jsonb_build_object('connectionId',f.connection_id,'expectedVersion',1,'reason','Wrong app key'),repeat('c',64),'{}')->>'state'='app_authorization_changed','renewal app identity must match original consent');
 r:=pg_temp.start_renewal(f.connection_id,f.renewal_id);update fixture set claim_token=(r->>'claimToken')::uuid,result=pg_temp.proof('original');
 perform pg_temp.check(r->>'state'='exchange_once' and r->'credentials'->>'refreshTokenEncrypted'='encv1:refresh','first intent returns saved encrypted grant once');
 perform pg_temp.check(not (pg_temp.start_renewal(f.connection_id,f.renewal_id)?'claimToken') and pg_temp.start_renewal(f.connection_id)->>'state'='exchanging','same or new request cannot repeat a current-version exchange');
 perform pg_temp.check((select count(*)=1 from public.forgestudio_renewals where connection_id=f.connection_id),'one private renewal intent per connection version');
 perform pg_temp.check((select not public.forgestudio_social_grant_ready(c) from public.social_connections c where id=f.connection_id),'potentially rotated credentials cannot start publication while result unknown');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='studio.credentials.renewal_requested'),'request and semantic decision commit once');
end$$;
do $$declare f fixture;r jsonb;begin select * into f from fixture;
 perform pg_temp.check(public.finish_forgestudio_renewal(f.renewal_id,gen_random_uuid(),f.result)->>'state'='claim_mismatch','wrong claim cannot finish renewal');
 r:=public.finish_forgestudio_renewal(f.renewal_id,f.claim_token,f.result);
 perform pg_temp.check(r->>'renewalState'='completed','complete provider proof finalizes renewal');
 perform pg_temp.check((select security_version=2 and public.forgestudio_social_grant_ready(c) and permission_evidence->>'renewalId'=f.renewal_id::text from public.social_connections c where id=f.connection_id),'rotated credentials and new revision become usable together');
 perform pg_temp.check(public.finish_forgestudio_renewal(f.renewal_id,f.claim_token,f.result)->>'state'='replayed','lost completion reply safely replays');
 perform pg_temp.check(public.finish_forgestudio_renewal(f.renewal_id,f.claim_token,f.result||'{"reason":"changed"}')->>'state'='result_conflict','immutable rotation result cannot be rewritten');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='studio.credentials.renewal_completed'),'completion has one semantic outcome');
 perform pg_temp.check(not exists(select 1 from public.shared_action_events where property_id=f.property_id and row_to_json(shared_action_events)::text like '%encv1:%'),'shared history contains no provider credentials');
 perform pg_temp.check(not exists(select 1 from public.social_publications where property_id=f.property_id),'credential renewal never creates publications');
end$$;
-- Every invalid/partial grant is retained but must leave the earlier credentials held.
do $$declare f fixture;c uuid;r jsonb;proof jsonb;request_id uuid;begin select * into f from fixture;
 for i in 1..8 loop
  c:=pg_temp.connect('invalid-'||i);request_id:=gen_random_uuid();r:=pg_temp.start_renewal(c,request_id);proof:=pg_temp.proof('invalid-'||i);
  if i=1 then proof:=jsonb_set(proof,'{accounts,0,accountId}','"other"');
  elsif i=2 then proof:=jsonb_set(proof,'{accounts,0,scopes}','[]');
  elsif i=3 then proof:=jsonb_set(proof,'{accounts,0,expiresAt}','null');
  elsif i=4 then proof:=jsonb_set(proof,'{accounts,0,expiresAt}','"infinity"');
  elsif i=5 then proof:=jsonb_set(proof,'{accounts,0,refreshExpiresAt}','"not-a-date"');
  elsif i=6 then proof:=jsonb_set(proof,'{accounts,0,refreshTokenEncrypted}','"plain-secret"');
  elsif i=7 then proof:=jsonb_set(proof,'{accounts,0,unknown}','"field"');
  else proof:=jsonb_build_object('status','uncertain','observedAt',clock_timestamp(),'accounts','[]'::jsonb);end if;
  perform pg_temp.check(public.finish_forgestudio_renewal(request_id,(r->>'claimToken')::uuid,proof)->>'renewalState'='held','invalid grant retained as hold '||i);
  perform pg_temp.check((select security_version=1 and not public.forgestudio_social_grant_ready(s) from public.social_connections s where id=c),'invalid grant cannot activate credentials '||i);
 end loop;
end$$;
do $$declare f fixture;c uuid;r jsonb;request_id uuid;begin select * into f from fixture;
 c:=pg_temp.connect('expired-refresh');update public.social_connections set refresh_token_expires_at=clock_timestamp()-interval '1 minute' where id=c;
 perform pg_temp.check(pg_temp.start_renewal(c)->>'state'='reauthorization_required','known expired refresh token cannot be exchanged');
 c:=pg_temp.connect('expired-meta','facebook');update public.social_connections set token_expires_at=null where id=c;
 perform pg_temp.check(pg_temp.start_renewal(c)->>'state'='reauthorization_required','unknown Meta user access expiry cannot be extended');
 c:=pg_temp.connect('disconnect');request_id:=gen_random_uuid();r:=pg_temp.start_renewal(c,request_id);
 perform public.disconnect_forgestudio_connection(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('connectionId',c,'expectedVersion',1,'reason','Retire while renewal runs'));
 perform pg_temp.check(public.finish_forgestudio_renewal(request_id,(r->>'claimToken')::uuid,pg_temp.proof('disconnect'))->>'renewalState'='held','late renewal cannot undo disconnect');
 perform pg_temp.check((select not is_active and access_token is null and security_version=2 from public.social_connections where id=c),'disconnected credentials remain cleared');
 c:=pg_temp.connect('new-consent');request_id:=gen_random_uuid();r:=pg_temp.start_renewal(c,request_id);perform pg_temp.connect('new-consent');
 perform pg_temp.check(public.finish_forgestudio_renewal(request_id,(r->>'claimToken')::uuid,pg_temp.proof('new-consent'))->>'renewalState'='held','new consent fences earlier refresh result');
 perform pg_temp.check((select security_version=2 and public.forgestudio_social_grant_ready(s) from public.social_connections s where id=c),'new consent remains usable after old renewal is held');
 c:=pg_temp.connect('app-change');request_id:=gen_random_uuid();r:=pg_temp.start_renewal(c,request_id);
 perform public.save_forgestudio_social_config(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('action','save','platform','x','expectedVersion',0,'appId','changed','secretFingerprint',repeat('d',64)),'encv1:new-secret');
 perform pg_temp.check(public.finish_forgestudio_renewal(request_id,(r->>'claimToken')::uuid,pg_temp.proof('app-change'))->>'renewalState'='held','app change fences saved renewal');
end$$;
create function pg_temp.fail_renewal_history() returns trigger language plpgsql as $$begin if new.action='studio.credentials.renewal_completed' then raise exception 'Fixture renewal history failure';end if;return new;end$$;
create trigger renewal_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_renewal_history();
do $$declare f fixture;c uuid;r jsonb;request_id uuid:=gen_random_uuid();begin select * into f from fixture;c:=pg_temp.connect('atomic');r:=pg_temp.start_renewal(c,request_id);
 begin perform public.finish_forgestudio_renewal(request_id,(r->>'claimToken')::uuid,pg_temp.proof('atomic'));raise exception 'FAIL missing action';exception when raise_exception then if SQLERRM<>'Fixture renewal history failure' then raise;end if;end;
 perform pg_temp.check((select security_version=1 from public.social_connections where id=c) and(select state='exchanging' and result is null from public.forgestudio_renewals where id=request_id),'credential rotation rolls back with failed outcome recording');
end$$;
drop trigger renewal_fixture_failure on public.shared_action_events;
do $$declare f fixture;actor uuid:=gen_random_uuid();c uuid;r jsonb;request_id uuid:=gen_random_uuid();begin
 select*into f from fixture;
 insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)values(actor,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','renewal-leaver-'||actor||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp());
 perform set_config('p11.team_scope','22222222-2222-2222-2222-222222222222',true);
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222',role='admin'where id=actor;
 update fixture set actor_id=actor;c:=pg_temp.connect('departed-requester');r:=pg_temp.start_renewal(c,request_id);
 update public.profiles set org_id=null,role='viewer'where id=actor;
 perform pg_temp.check(public.finish_forgestudio_renewal(request_id,(r->>'claimToken')::uuid,pg_temp.proof('departed-requester'))->>'renewalState'='held','departed operator cannot activate renewed access');
 perform pg_temp.check((select result is not null from public.forgestudio_renewals where id=request_id),'actual late provider receipt survives operator departure');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where request->>'renewalId'=request_id::text and action='studio.credentials.renewal_completed'and actor_id is null and service_principal='forgestudio.credential_service'and phase='failed'and not training_eligible),'held result still has actual service attribution');
 perform pg_temp.check((select security_version=1 from public.social_connections where id=c),'departure preserves earlier credentials and holds new grant');
 update fixture set actor_id=f.actor_id;
end$$;
do $$declare f fixture;begin select * into f from fixture;
 set local session_replication_role=replica;update public.properties set current_vertical_profile_version_id=null where id=f.property_id;delete from public.property_vertical_profile_versions where property_id=f.property_id;set local session_replication_role=origin;delete from public.properties where id=f.property_id;
 perform pg_temp.check(not exists(select 1 from public.forgestudio_renewals where property_id=f.property_id) and not exists(select 1 from public.social_connections where property_id=f.property_id),'property cleanup cascades private renewal receipts without orphans');
end$$;
select count(*) as passed_assertions from checks;
rollback;
