BEGIN;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is not true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
DO $$begin
 perform pg_temp.check(public.integration_permission_state('google','calendar',array['https://www.googleapis.com/auth/calendar'],null)='permissions_unconfirmed','legacy requested scopes are not a verified grant');
 perform pg_temp.check(public.integration_permission_state('google','calendar',array['https://www.googleapis.com/auth/calendar'],'microsoft_request_contract')='permissions_unconfirmed','Microsoft omission contract cannot verify Google');
 perform pg_temp.check(public.integration_permission_state('google','calendar',array['https://www.googleapis.com/auth/calendar.readonly'],'provider_response')='permissions_incomplete','read-only grant cannot mutate calendar');
 perform pg_temp.check(public.integration_permission_state('microsoft','email',array['User.Read','Mail.Read'],'provider_response')='permissions_incomplete','read-only mail cannot send');
 perform pg_temp.check(public.integration_permission_state('microsoft','calendar',array['https%3A%2F%2Fgraph.microsoft.com%2FUser.Read','Calendars.ReadWrite'],'provider_response')='confirmed','Graph URL-encoded scopes accepted');
 perform pg_temp.check(public.integration_permission_state('microsoft','calendar',array['User.Read','Calendars.ReadWrite','%ZZ'],'provider_response')='permissions_unconfirmed','malformed encoded scope unconfirmed');
 perform pg_temp.check(public.integration_permission_state('microsoft','calendar',array['User.Read','Calendars.ReadWrite',null],'provider_response')='permissions_unconfirmed','null scope unconfirmed');
 perform pg_temp.check(not has_function_privilege('anon','public.integration_permission_state(text,text,text[],text)','EXECUTE'),'permission policy service-only');
end$$;
DO $$declare p uuid:=gen_random_uuid();c uuid:=gen_random_uuid();actor uuid;identity jsonb;r jsonb;req uuid;version bigint;tokens jsonb;
begin
 select id into actor from public.profiles where org_id='22222222-2222-2222-2222-222222222222' order by id limit 1;
 insert into public.properties(id,name,org_id)values(p,'Permission policy fixture','22222222-2222-2222-2222-222222222222');
 insert into public.agent_calendars(id,property_id,profile_id,provider,google_email,account_email,access_token,refresh_token,token_expires_at,sync_enabled,token_status,scopes,provider_metadata)
 values(c,p,actor,'microsoft','fixture@example.invalid','fixture@example.invalid','old-access','old-refresh',now()+interval '2 hours',true,'healthy',array['User.Read','Calendars.ReadWrite','Mail.Send','Mail.Read'],'{}');
 select public.calendar_credential_identity(ac),credential_version into identity,version from public.agent_calendars ac where id=c;
 r:=public.claim_calendar_token_refresh(p,c,version,identity,gen_random_uuid(),false);
 perform pg_temp.check(r->>'state'='permissions_unconfirmed' and not r ? 'accessToken','calendar unexpired legacy grant held');
 perform pg_temp.check(not exists(select 1 from public.calendar_token_refreshes where agent_calendar_id=c),'calendar unconfirmed grant cannot start provider work');
 update public.agent_calendars set provider_metadata='{"scopeEvidence":"provider_response","preserve":"yes"}' where id=c returning credential_version into version;
 perform pg_temp.check(version=2,'calendar evidence change increments version');
 r:=public.claim_calendar_token_refresh(p,c,version,identity,gen_random_uuid(),false);
 perform pg_temp.check(r->>'state'='ready' and r->>'permissionState'='confirmed','calendar verified fresh grant reusable');
 req:=gen_random_uuid();r:=public.claim_calendar_token_refresh(p,c,version,identity,req,true);
 perform pg_temp.check(r->>'state'='claimed','calendar verified renewal claim');
 tokens:=jsonb_build_object('accessToken','new-access','refreshToken','new-refresh','expiresAt',now()+interval '1 hour');
 r:=public.finish_calendar_token_refresh(p,c,req,'success',tokens);
 perform pg_temp.check(r->>'state'='saved' and r->>'permissionState'='confirmed','calendar omitted renewal scope inherits verified grant');
 perform pg_temp.check((select provider_metadata->>'scopeEvidence'='refresh_inherited' and provider_metadata->>'preserve'='yes' from public.agent_calendars where id=c),'calendar inheritance provenance preserved without clobbering provider metadata');
 select credential_version into version from public.agent_calendars where id=c;
 req:=gen_random_uuid();perform public.claim_calendar_token_refresh(p,c,version,identity,req,true);
 tokens:=tokens||'{"scope":"User.Read","refreshToken":"narrowed-rotation"}';
 r:=public.finish_calendar_token_refresh(p,c,req,'success',tokens);
 perform pg_temp.check(r->>'state'='permissions_incomplete' and not r ? 'accessToken','calendar narrower refreshed grant returns no usable credential');
 perform pg_temp.check((select refresh_token='narrowed-rotation' and token_status='permissions_incomplete' and scopes=array['User.Read'] and credential_version=version+1 from public.agent_calendars where id=c),'calendar rotation and permission hold saved atomically');
 perform pg_temp.check((select refresh_status='permissions_incomplete' and completed_version=version+1 from public.calendar_token_refreshes where request_id=req),'calendar renewal ledger reflects hold');
 perform pg_temp.check(public.finish_calendar_token_refresh(p,c,req,'success',tokens)=r,'calendar lost hold response replays exact saved outcome');
 r:=public.claim_calendar_token_refresh(p,c,version,identity,gen_random_uuid(),false);
 perform pg_temp.check(r->>'state'='permissions_incomplete' and not r ? 'accessToken','calendar stale config cannot bypass reduced permissions');
 update public.agent_calendars set scopes=array['User.Read','Calendars.ReadWrite','Mail.Read','Mail.Send'],provider_metadata='{"scopeEvidence":"provider_response"}',token_status='healthy' where id=c returning credential_version into version;
 req:=gen_random_uuid();perform public.claim_calendar_token_refresh(p,c,version,identity,req,true);
 r:=public.finish_calendar_token_refresh(p,c,req,'success',tokens||'{"scope":null}');
 perform pg_temp.check(r->>'state'='permissions_unconfirmed','calendar explicit null scope cannot inherit earlier grant');
 update public.agent_calendars set scopes=array['User.Read','Calendars.ReadWrite','Mail.Read','Mail.Send'],provider_metadata='{"scopeEvidence":"provider_response"}',token_status='healthy' where id=c returning credential_version into version;
 req:=gen_random_uuid();perform public.claim_calendar_token_refresh(p,c,version,identity,req,true);
 update public.agent_calendars set scopes=array['User.Read'] where id=c;
 r:=public.finish_calendar_token_refresh(p,c,req,'success',tokens);
 perform pg_temp.check(r->>'state'='connection_changed','calendar permission edits fence in-flight renewal');
 perform pg_temp.check((select scopes=array['User.Read'] from public.agent_calendars where id=c),'calendar stale completion cannot restore removed permissions');
end$$;
DO $$declare p uuid:=gen_random_uuid();c uuid:=gen_random_uuid();actor uuid;identity jsonb;r jsonb;req uuid;version bigint;tokens jsonb;
begin
 select id into actor from public.profiles where org_id='22222222-2222-2222-2222-222222222222' order by id limit 1;
 insert into public.properties(id,name,org_id)values(p,'Permission policy fixture','22222222-2222-2222-2222-222222222222');
 insert into public.email_configurations(id,property_id,profile_id,provider,google_email,account_email,access_token,refresh_token,token_expires_at,sync_enabled,token_status,scopes,provider_metadata)
 values(c,p,actor,'microsoft','fixture@example.invalid','fixture@example.invalid','old-access','old-refresh',now()+interval '2 hours',true,'healthy',array['User.Read','Calendars.ReadWrite','Mail.Send','Mail.Read'],'{}');
 select public.email_credential_identity(ac),credential_version into identity,version from public.email_configurations ac where id=c;
 r:=public.claim_email_token_refresh(p,c,version,identity,gen_random_uuid(),false);
 perform pg_temp.check(r->>'state'='permissions_unconfirmed' and not r ? 'accessToken','email unexpired legacy grant held');
 perform pg_temp.check(not exists(select 1 from public.email_token_refreshes where email_configuration_id=c),'email unconfirmed grant cannot start provider work');
 update public.email_configurations set provider_metadata='{"scopeEvidence":"provider_response","preserve":"yes"}' where id=c returning credential_version into version;
 perform pg_temp.check(version=2,'email evidence change increments version');
 r:=public.claim_email_token_refresh(p,c,version,identity,gen_random_uuid(),false);
 perform pg_temp.check(r->>'state'='ready' and r->>'permissionState'='confirmed','email verified fresh grant reusable');
 req:=gen_random_uuid();r:=public.claim_email_token_refresh(p,c,version,identity,req,true);
 perform pg_temp.check(r->>'state'='claimed','email verified renewal claim');
 tokens:=jsonb_build_object('accessToken','new-access','refreshToken','new-refresh','expiresAt',now()+interval '1 hour');
 r:=public.finish_email_token_refresh(p,c,req,'success',tokens);
 perform pg_temp.check(r->>'state'='saved' and r->>'permissionState'='confirmed','email omitted renewal scope inherits verified grant');
 perform pg_temp.check((select provider_metadata->>'scopeEvidence'='refresh_inherited' and provider_metadata->>'preserve'='yes' from public.email_configurations where id=c),'email inheritance provenance preserved without clobbering provider metadata');
 select credential_version into version from public.email_configurations where id=c;
 req:=gen_random_uuid();perform public.claim_email_token_refresh(p,c,version,identity,req,true);
 tokens:=tokens||'{"scope":"User.Read","refreshToken":"narrowed-rotation"}';
 r:=public.finish_email_token_refresh(p,c,req,'success',tokens);
 perform pg_temp.check(r->>'state'='permissions_incomplete' and not r ? 'accessToken','email narrower refreshed grant returns no usable credential');
 perform pg_temp.check((select refresh_token='narrowed-rotation' and token_status='permissions_incomplete' and scopes=array['User.Read'] and credential_version=version+1 from public.email_configurations where id=c),'email rotation and permission hold saved atomically');
 perform pg_temp.check((select refresh_status='permissions_incomplete' and completed_version=version+1 from public.email_token_refreshes where request_id=req),'email renewal ledger reflects hold');
 perform pg_temp.check(public.finish_email_token_refresh(p,c,req,'success',tokens)=r,'email lost hold response replays exact saved outcome');
 r:=public.claim_email_token_refresh(p,c,version,identity,gen_random_uuid(),false);
 perform pg_temp.check(r->>'state'='permissions_incomplete' and not r ? 'accessToken','email stale config cannot bypass reduced permissions');
 update public.email_configurations set scopes=array['User.Read','Calendars.ReadWrite','Mail.Read','Mail.Send'],provider_metadata='{"scopeEvidence":"provider_response"}',token_status='healthy' where id=c returning credential_version into version;
 req:=gen_random_uuid();perform public.claim_email_token_refresh(p,c,version,identity,req,true);
 r:=public.finish_email_token_refresh(p,c,req,'success',tokens||'{"scope":null}');
 perform pg_temp.check(r->>'state'='permissions_unconfirmed','email explicit null scope cannot inherit earlier grant');
 update public.email_configurations set scopes=array['User.Read','Calendars.ReadWrite','Mail.Read','Mail.Send'],provider_metadata='{"scopeEvidence":"provider_response"}',token_status='healthy' where id=c returning credential_version into version;
 req:=gen_random_uuid();perform public.claim_email_token_refresh(p,c,version,identity,req,true);
 update public.email_configurations set scopes=array['User.Read'] where id=c;
 r:=public.finish_email_token_refresh(p,c,req,'success',tokens);
 perform pg_temp.check(r->>'state'='connection_changed','email permission edits fence in-flight renewal');
 perform pg_temp.check((select scopes=array['User.Read'] from public.email_configurations where id=c),'email stale completion cannot restore removed permissions');
end$$;
select count(*) as passed from checks; ROLLBACK;
