BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'Failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee740000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'Lead record SQL fixture'),(pg_temp.i(2),'Lead record other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','lead-record-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,104)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,104)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'Lead record SQL property'),(pg_temp.i(202),pg_temp.i(2),'Lead record other property');
insert into public.workflow_definitions(id,property_id,name,is_active,trigger_on,steps)values(pg_temp.i(401),pg_temp.i(201),'Explicit follow-up fixture',true,'lead_created','[{"action":"wait","delay_hours":1}]');
create function pg_temp.fields()returns jsonb language sql immutable as $$select'{"firstName":"Taylor","lastName":"Fixture","email":"taylor@fixture.invalid","phone":"+1 (415) 555-0188","source":"manual","bedrooms":"studio","moveInDate":"2026-10-01","notes":"Private initial preference"}'::jsonb$$;
create function pg_temp.command(n int,input jsonb,a int default 101)returns jsonb language plpgsql as $$declare r jsonb;begin r:=public.decide_lead_record(pg_temp.i(n),pg_temp.i(a),pg_temp.i(201),input);perform set_config('p11.lead_record_scope','',true);return r;end$$;
create function pg_temp.creation(fields jsonb default pg_temp.fields(),workflows jsonb default'[]')returns jsonb language sql as $$select jsonb_build_object('operation','create','fields',fields,'duplicateReason','','workflowIds',workflows,'workflowHash',public.lead_followup_context(pg_temp.i(201))->>'hash','prepareCrm',false)$$;
create function pg_temp.read_it(kind text default'list',n int default null,a int default 101,offset_n int default 0)returns jsonb language sql as $$select public.read_lead_records(pg_temp.i(a),pg_temp.i(201),jsonb_build_object('kind',kind,'id',pg_temp.i(n),'offset',offset_n))$$;
create function pg_temp.change(n int,op text,j int,extra jsonb default'{}',revision int default null)returns jsonb language sql as $$select pg_temp.command(n,jsonb_build_object('operation',op,'leadId',pg_temp.i(j),'revision',coalesce(revision,(select record_revision from public.leads where id=pg_temp.i(j))))||extra)$$;
set local role service_role;
select pg_temp.check_it(public.lead_record_fields_valid(pg_temp.fields()),'valid contact and preference fields');
select pg_temp.check_it(not public.lead_record_fields_valid(pg_temp.fields()||'{"email":"bad","phone":""}'),'invalid email held');
select pg_temp.check_it(not public.lead_record_fields_valid(pg_temp.fields()||'{"email":"","phone":""}'),'contact required');
select pg_temp.check_it(not public.lead_record_fields_valid(pg_temp.fields()||'{"moveInDate":"2026-02-30"}'),'invalid calendar date held');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation(),102)->>'state'='forbidden','viewer cannot create');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation(),103)->>'state'='forbidden','other organization cannot create');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation())->>'leadId'=pg_temp.i(301)::text,'stable identity creates one lead');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation())->>'state'='replayed','lost create reply cannot duplicate lead');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation(),104)->>'state'='not_found','another manager cannot take over request');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation(pg_temp.fields()||'{"firstName":"Other"}'))->>'state'='request_conflict','recorded input immutable');
select pg_temp.check_it(pg_temp.read_it('lead',301)#>>'{lead,bedrooms}'='studio','textual preferences preserved');
select pg_temp.check_it((select count(*)=0 from public.lead_workflows where lead_id=pg_temp.i(301)),'create does not activate a default workflow');
select pg_temp.check_it(pg_temp.read_it('lead',301,102)->>'state'='ready','viewer reads current lead');
select pg_temp.check_it(pg_temp.read_it('lead',301,103)->>'state'='forbidden','cross tenant read denied');
select pg_temp.check_it(pg_temp.read_it('command',301,104)->>'state'='not_found','request recovery owner scoped');
select pg_temp.check_it(pg_temp.command(302,pg_temp.creation(pg_temp.fields()||'{"firstName":"Another","email":" TAYLOR@fixture.invalid "}'))->>'state'='contact_conflict','matching contact never silently overwrites original');
select pg_temp.check_it(pg_temp.read_it('lead',301)#>>'{lead,first_name}'='Taylor','original contact retained');
insert into st values('matches',public.lead_contact_matches(pg_temp.i(201),null,pg_temp.fields()));
select pg_temp.check_it(pg_temp.command(302,pg_temp.creation()||jsonb_build_object('duplicateHash',(select v->>'hash'from st where k='matches'),'duplicateReason','Separate household member')) ->>'status'='saved','explicit shared-contact decision can create separate lead');
select pg_temp.check_it(pg_temp.read_it('history',302)#>>'{items,0,input,duplicateReason}'='Separate household member','shared-contact explanation retained');
select pg_temp.check_it(pg_temp.change(303,'edit',301,jsonb_build_object('fields',pg_temp.fields()||'{"firstName":"Changed"}','duplicateReason',''))->>'state'='contact_conflict','edit conflict also needs explicit review');
select pg_temp.check_it(pg_temp.change(303,'edit',301,jsonb_build_object('fields',pg_temp.fields()||'{"firstName":"Changed","email":"new@fixture.invalid","phone":""}','duplicateReason',''))->>'status'='saved','exact contact edit retained');
select pg_temp.check_it(pg_temp.read_it('history',301)#>>'{items,0,before_state,first_name}'='Taylor','before edit is immutable private evidence');
select pg_temp.check_it(pg_temp.read_it('history',301)#>>'{items,0,after_state,lead,first_name}'='Changed','after edit retained');
select pg_temp.check_it(pg_temp.change(304,'status',301,'{"status":"contacted","reason":"Phone conversation reported"}',1)->>'state'='lead_changed','stale status held');
select pg_temp.check_it(pg_temp.change(304,'status',301,'{"status":"contacted","reason":"Phone conversation reported"}')->>'status'='saved','operator reported status recorded');
select pg_temp.check_it(pg_temp.read_it('lead',301)#>>'{lead,last_contacted_at}'is not null,'reported contact time retained');
select pg_temp.check_it(pg_temp.change(305,'start_followup',301,jsonb_build_object('workflowIds',jsonb_build_array(pg_temp.i(401)),'workflowHash',repeat('a',64)))->>'state'='followup_changed','changed follow-up definition held');
select pg_temp.check_it(pg_temp.change(305,'start_followup',301,jsonb_build_object('workflowIds',jsonb_build_array(pg_temp.i(401)),'workflowHash',public.lead_followup_context(pg_temp.i(201))->>'hash'))->>'startedFollowups'='1','reviewed active follow-up enrolled');
select pg_temp.check_it(pg_temp.change(306,'start_followup',301,jsonb_build_object('workflowIds',jsonb_build_array(pg_temp.i(401)),'workflowHash',public.lead_followup_context(pg_temp.i(201))->>'hash'))->>'state'='followup_open','cannot duplicate active follow-up');
select pg_temp.check_it(pg_temp.change(307,'status',301,'{"status":"leased","reason":"Operator reported lease; document review separate"}')->>'stoppedFollowups'='1','closure atomically stops active follow-up');
select pg_temp.check_it((select bool_and(status='stopped')from public.lead_workflows where lead_id=pg_temp.i(301)),'follow-up actually stopped');
select pg_temp.check_it(pg_temp.change(308,'status',301,'{"status":"new","reason":"Corrected report"}')->>'status'='saved','status can be corrected');
select pg_temp.check_it((select bool_and(status='stopped')from public.lead_workflows where lead_id=pg_temp.i(301)),'correction does not restart follow-up');
select pg_temp.check_it(pg_temp.change(309,'prepare_crm',301)#>>'{crmPreparation,state}'='configuration_required','CRM setup gap retained without claiming delivery');
select pg_temp.check_it(pg_temp.command(310,'{"operation":"cancel_request"}')->>'status'='cancelled_request','unused request cancelled');
select pg_temp.check_it(pg_temp.command(310,pg_temp.creation())->>'status'='cancelled_request','late original create fenced');
select pg_temp.check_it(pg_temp.command(301,'{"operation":"cancel_request"}')->>'leadId'=pg_temp.i(301)::text,'cancel cannot erase saved lead');
-- Existing automated/source writes change revision without forging a human author.
insert into st values('lead',pg_temp.read_it('lead',301));
update public.leads set phone='+14155550100'where id=pg_temp.i(301);
select pg_temp.check_it((pg_temp.read_it('lead',301)#>>'{lead,record_revision}')::integer=(select(v#>>'{lead,record_revision}')::integer+1 from st where k='lead'),'external source change advances displayed revision');
select pg_temp.check_it(pg_temp.change(311,'status',301,'{"status":"lost","reason":"Old view"}',(select(v#>>'{lead,record_revision}')::integer from st where k='lead'))->>'state'='lead_changed','concurrent source cannot be overwritten');
select pg_temp.check_it((select count(*)from public.lead_record_commands where property_id=pg_temp.i(201))=(select count(*)from public.shared_action_events where property_id=pg_temp.i(201)and action like'lead.record.%'),'all human mutations have one atomic shared event');
select pg_temp.check_it((select bool_and(not training_eligible and request::text not like'%fixture.invalid%'and result::text not like'%Private%')from public.shared_action_events where property_id=pg_temp.i(201)),'private contact data excluded and training ineligible');
-- More than the Data API row cap: summaries/search use the complete property scope.
insert into public.leads(property_id,first_name,last_name,email,source,status)select pg_temp.i(201),'Bulk',n::text,'bulk-'||n||'@fixture.invalid','fixture-bulk','lost'from generate_series(1,1205)n;
insert into public.leads(property_id,first_name,last_name,email,source,status)values(pg_temp.i(201),'Literal%_','Comma, Person','literal@fixture.invalid','unique-source','new');
select pg_temp.check_it(pg_temp.read_it()#>>'{pagination,total}'='1208','full property count exceeds row cap');
select pg_temp.check_it(pg_temp.read_it()#>>'{statusSummary,lost}'='1205','complete status summary');
select pg_temp.check_it(public.read_lead_records(pg_temp.i(101),pg_temp.i(201),'{"search":"%_"}')#>>'{pagination,total}'='1','search is literal, not a query expression');
select pg_temp.check_it(public.read_lead_records(pg_temp.i(101),pg_temp.i(201),'{"page":13,"limit":100}')#>>'{pagination,totalPages}'='13','last list page reachable');
select pg_temp.check_it(jsonb_array_length(public.read_lead_records(pg_temp.i(101),pg_temp.i(201),'{"page":13,"limit":100}')->'leads')=8,'last page complete');
select pg_temp.check_it(public.read_lead_records(pg_temp.i(101),pg_temp.i(201),'{"page":0}')->>'state'='invalid_input','invalid pagination held');
do $$begin for n in 5000..5021 loop perform pg_temp.change(n,'status',301,'{"status":"new","reason":"Fixture history decision"}');end loop;end$$;
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it('history',301)->'items')=20,'first decision page bounded');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it('history',301,101,20)->'items')>0,'remaining decision history reachable');
select set_config('p11.lead_record_scope','',true);
select pg_temp.throws(format('update public.lead_record_commands set input=%L where id=%L','{}',pg_temp.i(301)),'decision input cannot be rewritten');
select pg_temp.throws(format('delete from public.lead_record_commands where id=%L',pg_temp.i(301)),'live history cannot be removed');
reset role;
select pg_temp.check_it(not has_function_privilege('authenticated','public.decide_lead_record(uuid,uuid,uuid,jsonb)','EXECUTE'),'native mutation service-only');
select pg_temp.check_it(not has_table_privilege('authenticated','public.lead_record_commands','SELECT'),'private commands service-only');
-- A history failure must roll back both the reported status and its follow-up effects.
select pg_temp.check_it(pg_temp.change(5998,'start_followup',301,jsonb_build_object('workflowIds',jsonb_build_array(pg_temp.i(401)),'workflowHash',public.lead_followup_context(pg_temp.i(201))->>'hash'))->>'status'='saved','atomic rollback fixture has active follow-up');
create function pg_temp.reject_lead_action()returns trigger language plpgsql as $$begin if new.id=pg_temp.i(6000)then raise exception 'Synthetic history failure';end if;return new;end$$;
create trigger fixture_lead_action_failure before insert on public.shared_action_events for each row execute function pg_temp.reject_lead_action();
select pg_temp.throws(format('select pg_temp.change(6000,%L,301,%L)','status','{"status":"lost","reason":"Must roll back"}'),'history failure aborts the whole change');
select pg_temp.check_it(pg_temp.read_it('lead',301)#>>'{lead,status}'='new','failed history keeps previous reported status');
select pg_temp.check_it((select count(*)=1 from public.lead_workflows where lead_id=pg_temp.i(301)and status='active'),'failed history also restores future follow-up');
select pg_temp.check_it(not exists(select 1 from public.lead_record_commands where id=pg_temp.i(6000)),'failed history leaves no saved command');
drop trigger fixture_lead_action_failure on public.shared_action_events;
select set_config('p11.team_scope',pg_temp.i(1)::text,true);update public.profiles set role='viewer'where id=pg_temp.i(101);
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation())->>'state'='forbidden','role withdrawal denies saved-request replay');
select n as assertions_passed from assertion_count;ROLLBACK;
