begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,lead_id uuid,other_lead uuid,actor_id uuid,note_id uuid,legacy_id uuid,untracked_id uuid);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'Lead activity rollback fixture'from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'Lead activity other rollback fixture'from fixture;
insert into public.leads(id,property_id,first_name,last_name,status)select lead_id,property_id,'Note','Fixture','new'from fixture union all select other_lead,other_property,'Other','Fixture','new'from fixture;
create function pg_temp.note_input(nid uuid,verb text,new_content text default null)returns jsonb language sql as $$select jsonb_build_object('action',verb,'noteId',a.id,'expectedVersion',coalesce(n.version,0),'sourceHash',public.crm_configuration_hash(to_jsonb(a)),'reason','Review exact isolated note decision')||case when verb='correct'then jsonb_build_object('content',new_content)else '{}'::jsonb end from public.lead_activities a left join public.lead_note_records n on n.id=a.id where a.id=nid$$;
create function pg_temp.reject_note_history()returns trigger language plpgsql as $$begin if new.action like 'lead.note.%'then raise exception 'Synthetic note history failure';end if;return new;end$$;
do $$declare f fixture;r jsonb;v_input jsonb;v_stale jsonb;v_id uuid:=gen_random_uuid();original_at timestamptz;begin select *into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.lead_activities','select')and not has_table_privilege('authenticated','public.lead_activities','insert')and not has_function_privilege('anon','public.save_lead_note(uuid,uuid,uuid,uuid,jsonb)','execute'),'raw activity access and system event fabrication stay server private');
 v_input:='{"action":"add","content":"Client asked about a garden home.","reason":"Save operator note"}';
 perform pg_temp.check(public.save_lead_note(f.note_id,f.property_id,f.lead_id,gen_random_uuid(),v_input)->>'state'='forbidden','note mutation needs current property access');
 perform pg_temp.check(public.save_lead_note(f.note_id,f.other_property,f.lead_id,f.actor_id,v_input)->>'state'='not_found','note target must belong to the explicitly selected property');
 begin perform public.save_lead_note(f.note_id,f.property_id,f.lead_id,f.actor_id,'{"action":"email_sent","content":"Fake email success","reason":"Try old generic activity"}');raise exception 'expected rejected system outcome';exception when others then if sqlerrm='expected rejected system outcome'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.lead_activities where id=f.note_id),'human note commands cannot fabricate provider success');
 r:=public.save_lead_note(f.note_id,f.property_id,f.lead_id,f.actor_id,v_input);perform pg_temp.check(r->>'state'='saved'and r->'externalDelivery'='false'::jsonb,'internal note and its actor history save together without delivery');
 select created_at into original_at from public.lead_activities where id=f.note_id;
 perform pg_temp.check(public.save_lead_note(f.note_id,f.property_id,f.lead_id,f.actor_id,v_input)->>'state'='replayed'and(select count(*)=1 from public.lead_activities where id=f.note_id),'lost note response does not duplicate activity');
 perform pg_temp.check(public.save_lead_note(f.note_id,f.property_id,f.lead_id,f.actor_id,v_input||'{"content":"changed"}')->>'state'='request_conflict','request identity cannot replace saved content');
 r:=public.read_lead_activity(f.property_id,f.lead_id,f.actor_id);
 perform pg_temp.check(r->'activities'->0->>'sourceHash'=public.crm_configuration_hash((select to_jsonb(a)from public.lead_activities a where a.id=f.note_id))and not(r->'activities'->0?'metadata'),'displayed source hash matches canonical activity and hides internal metadata');
 perform pg_temp.check((select request->>'noteId'=f.note_id::text and not(request?'content')and not(result?'content')from public.shared_action_events where id=f.note_id),'shared action history uses note identity without private body');
 v_input:=pg_temp.note_input(f.note_id,'correct','Client asked about a ground-floor garden home.');v_stale:=v_input;
 r:=public.save_lead_note(v_id,f.property_id,f.lead_id,f.actor_id,v_input);perform pg_temp.check(r->>'state'='saved'and r->>'version'='2','exact source correction advances the retained note version');
 perform pg_temp.check(public.save_lead_note(v_id,f.property_id,f.lead_id,f.actor_id,v_input)->>'state'='replayed','lost correction reply reopens the same decision');
 perform pg_temp.check(public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,v_stale||'{"content":"older overwrite"}')->>'state'='stale_note','older displayed versions cannot overwrite a correction');
 perform pg_temp.check((select created_at=original_at and created_by=f.actor_id from public.lead_activities where id=f.note_id)and(select original_activity->>'description'='Client asked about a garden home.'from public.lead_note_records where id=f.note_id),'correction preserves original content, author and creation time');
 create trigger reject_note_history before insert on public.shared_action_events for each row execute function pg_temp.reject_note_history();
 v_id:=gen_random_uuid();v_input:=pg_temp.note_input(f.note_id,'correct','A change that must roll back');
 begin perform public.save_lead_note(v_id,f.property_id,f.lead_id,f.actor_id,v_input);raise exception 'expected failed action recording';exception when others then if sqlerrm='expected failed action recording'then raise;end if;end;
 drop trigger reject_note_history on public.shared_action_events;
 perform pg_temp.check((select version=2 and content='Client asked about a ground-floor garden home.'from public.lead_note_records where id=f.note_id)and not exists(select 1 from public.lead_note_decisions where id=v_id),'history failure rolls back canonical note and private revision together');
 perform public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.note_id,'withdraw'));
 perform pg_temp.check((select description='Note withdrawn'from public.lead_activities where id=f.note_id)and(select state='withdrawn'and content='Client asked about a ground-floor garden home.'from public.lead_note_records where id=f.note_id),'withdrawal hides active content while retaining it privately');
 perform pg_temp.check(public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.note_id,'correct','Cannot edit withdrawn note'))->>'state'='state_changed','withdrawn notes require explicit restoration before correction');
 perform public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.note_id,'restore'));
 perform pg_temp.check((select description='Client asked about a ground-floor garden home.'from public.lead_activities where id=f.note_id)and(select version=4 from public.lead_note_records where id=f.note_id),'restoration reuses original retained content with a new decision');
 begin update public.lead_activities set description='Unrecorded change'where id=f.note_id;raise exception 'expected native note workflow';exception when others then if sqlerrm='expected native note workflow'then raise;end if;end;
 begin delete from public.lead_activities where id=f.note_id;raise exception 'expected retained history';exception when others then if sqlerrm='expected retained history'then raise;end if;end;
 perform pg_temp.check((select version=4 from public.lead_note_records where id=f.note_id),'generic changes and deletion cannot bypass native note history');
 insert into public.lead_activities(id,lead_id,type,description,created_at,metadata)values(f.legacy_id,f.lead_id,'note','Earlier note needing correction',null,'{"privateReceipt":"DO_NOT_EXPOSE"}'),(f.untracked_id,f.lead_id,'email_sent','Earlier record says an email was sent',null,'{"privateReceipt":"DO_NOT_EXPOSE"}');
 perform pg_temp.check(public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.untracked_id,'correct','not a note'))->>'state'='note_required','real system activity producers are preserved but their records cannot be edited as notes');
 perform pg_temp.check(public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.legacy_id,'restore'))->>'state'='state_changed'and not exists(select 1 from public.lead_note_records where id=f.legacy_id),'invalid legacy restoration cannot adopt an unrecorded note as a side effect');
 update public.profiles set role='agent'where id=f.actor_id;
 perform pg_temp.check(public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.legacy_id,'correct','Unauthorized correction'))->>'state'='author_required','unknown-author earlier notes require a current manager');
 perform pg_temp.check(public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.note_id,'correct','Author corrected their own note'))->>'state'='saved','a current note author can correct their own record without manager role');
 update public.profiles set role='admin'where id=f.actor_id;
 perform public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.legacy_id,'correct','Reviewed earlier note correction'));
 perform pg_temp.check((select source_type='legacy'and original_activity->>'description'='Earlier note needing correction'from public.lead_note_records where id=f.legacy_id)and(select created_at is null and created_by is null from public.lead_activities where id=f.legacy_id),'legacy correction preserves unknown original author/time and full original evidence');
 r:=public.read_lead_activity(f.property_id,f.lead_id,f.actor_id);perform pg_temp.check(position('DO_NOT_EXPOSE'in r::text)=0,'arbitrary provider metadata never enters the timeline');
 update public.leads set property_id=f.other_property where id=f.lead_id;
 r:=public.read_lead_activity(f.other_property,f.lead_id,f.actor_id);perform pg_temp.check(exists(select 1 from jsonb_array_elements(r->'activities')a where a->>'id'=f.note_id::text and a->'description'='null'::jsonb and a->'canEdit'='false'::jsonb and a->>'provenance'='earlier_property'),'moving a lead does not expose an earlier property private note');
 perform pg_temp.check(public.read_lead_activity(f.property_id,f.lead_id,f.actor_id,null,f.note_id)->>'state'='not_found'and public.save_lead_note(gen_random_uuid(),f.other_property,f.lead_id,f.actor_id,pg_temp.note_input(f.note_id,'withdraw'))->>'state'='source_property_changed','moved lead cannot mutate or retrieve old property note revisions');
 update public.leads set property_id=f.property_id where id=f.lead_id;
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.read_lead_activity(f.property_id,f.lead_id,f.actor_id)->>'state'='forbidden'and public.save_lead_note(f.note_id,f.property_id,f.lead_id,f.actor_id,'{"action":"add","content":"Client asked about a garden home.","reason":"Save operator note"}')->>'state'='forbidden','reads and lost replies recheck the actor’s current organization');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
end$$;
do $$declare f fixture;r jsonb;seen uuid[]:='{}';cursor_id uuid;expected bigint;i integer;begin select *into f from fixture;
 perform pg_temp.check(public.record_lead_return_note(f.property_id,f.lead_id,f.actor_id,'Returned via console')->>'state'='saved'and public.record_lead_return_note(f.property_id,f.lead_id,f.actor_id,'Returned via console')->>'state'='replayed','console returning-lead notes keep the duplicate window through scoped native recording');
 perform pg_temp.check(public.record_lead_return_note(f.other_property,f.lead_id,f.actor_id,'Returned via console')->>'state'='not_found','return-note compatibility cannot cross the lead property');
 insert into public.lead_activities(lead_id,type,description,created_at)select f.lead_id,'system_fixture','Retained activity '||g.n,case when g.n%2=0 then null else '2020-01-01T00:00:00Z'::timestamptz end from generate_series(1,1005)g(n);
 select count(*)into expected from public.lead_activities where lead_id=f.lead_id;
 loop r:=public.read_lead_activity(f.property_id,f.lead_id,f.actor_id,cursor_id);select seen||array_agg((v->>'id')::uuid)into seen from jsonb_array_elements(r->'activities')v;cursor_id:=(r->>'nextCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(cardinality(seen)=expected and(select count(distinct id)=expected from unnest(seen)id),'paged timeline preserves all records beyond 1000 including null and tied dates');
 perform pg_temp.check(public.read_lead_activity(f.property_id,f.lead_id,f.actor_id,gen_random_uuid())->>'state'='cursor_changed','foreign timeline cursors rejected');
 for i in 1..24 loop perform public.save_lead_note(gen_random_uuid(),f.property_id,f.lead_id,f.actor_id,pg_temp.note_input(f.note_id,'correct','Recorded correction '||i));end loop;
 seen:='{}';cursor_id:=null;select count(*)into expected from public.lead_note_decisions where note_id=f.note_id;
 loop r:=public.read_lead_activity(f.property_id,f.lead_id,f.actor_id,cursor_id,f.note_id);select seen||array_agg((v->>'id')::uuid)into seen from jsonb_array_elements(r->'history')v;cursor_id:=(r->>'nextCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(cardinality(seen)=expected and cardinality(seen)>20,'note history pages every recorded correction, withdrawal and restoration');
end$$;
select count(*)as passed_assertions from checks;
rollback;
