BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee840000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'Luma conversation SQL fixture'),(pg_temp.i(2),'Luma conversation other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','luma-conversation-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,103)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,103)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'Luma conversation SQL property'),(pg_temp.i(202),pg_temp.i(2),'Luma conversation other property');
insert into public.conversations(id,property_id,channel)values(pg_temp.i(301),pg_temp.i(201),'widget'),(pg_temp.i(302),pg_temp.i(202),'widget');
create function pg_temp.read_it(kind text default'messages',offset_n int default 0,hash text default null,actor int default 101)returns jsonb language sql as $$select public.read_luma_conversations(pg_temp.i(actor),pg_temp.i(201),case when kind='list'then null else pg_temp.i(301)end,kind,null,offset_n,hash)$$;
create function pg_temp.command(n int,op text,extra jsonb default'{}',actor int default 101)returns jsonb language plpgsql as $$declare hash text;begin hash:=pg_temp.read_it()->>'hash';return public.decide_luma_conversation(pg_temp.i(n),pg_temp.i(actor),pg_temp.i(201),jsonb_build_object('operation',op,'conversationId',pg_temp.i(301),'sourceHash',hash,'reason','Private staff reason')||extra);end$$;
set local role service_role;
select pg_temp.check_it(pg_temp.read_it()->>'state'='ready','current complete transcript read');
select pg_temp.check_it(pg_temp.read_it('messages',0,null,102)->>'canManage'='false','viewer read only');
select pg_temp.check_it(pg_temp.read_it('messages',0,null,103)->>'state'='forbidden','other organization read denied');
select pg_temp.check_it(pg_temp.command(401,'takeover','{}',102)->>'state'='forbidden','viewer takeover denied');
select pg_temp.check_it(pg_temp.command(401,'reply','{"content":"Unauthorized staff reply"}',102)->>'state'='forbidden','viewer reply denied');
select pg_temp.check_it(public.save_luma_message_at_revision(pg_temp.i(201),pg_temp.i(301),'user','Private visitor original',null)->>'saved'='true','visitor message saved');
select pg_temp.check_it((select count(*)=1 from public.luma_conversation_service_events where property_id=pg_temp.i(201)and kind='message_saved'),'actual visitor storage has separate service evidence');
select pg_temp.check_it((select count(*)=1 from public.shared_action_events where property_id=pg_temp.i(201)and service_principal='lumaleasing.message_store'and actor_id is null),'system event never impersonates a human');
select pg_temp.check_it(pg_temp.command(402,'reply','{"content":"Reply while AI owns chat"}')->>'state'='mode_changed','reply before takeover held');
insert into st values('before-takeover',pg_temp.read_it());
select pg_temp.check_it(pg_temp.command(403,'takeover')->>'status'='taken_over','manager takes over');
select pg_temp.check_it((select is_human_mode and mode_revision=1 from public.conversations where id=pg_temp.i(301)),'takeover changes exact mode version');
select pg_temp.check_it((select count(*)=1 from public.messages where conversation_id=pg_temp.i(301)and role='system'),'takeover notice saved once');
select pg_temp.check_it(public.decide_luma_conversation(pg_temp.i(403),pg_temp.i(101),pg_temp.i(201),(select input from public.luma_conversation_commands where id=pg_temp.i(403)))->>'status'='taken_over','lost takeover reply replays');
select pg_temp.check_it((select count(*)=1 from public.messages where conversation_id=pg_temp.i(301)and role='system'),'replay cannot duplicate visible notice');
select pg_temp.check_it(pg_temp.command(403,'release')->>'state'='request_conflict','stable identity cannot become a different decision');
select pg_temp.check_it(public.decide_luma_conversation(pg_temp.i(404),pg_temp.i(101),pg_temp.i(201),jsonb_build_object('operation','release','conversationId',pg_temp.i(301),'sourceHash',(select v->>'hash'from st where k='before-takeover'),'reason','Stale release'))->>'state'='source_changed','old transcript cannot release current control');
select pg_temp.check_it(pg_temp.command(405,'reply','{"content":"Private exact staff reply"}')->>'status'='reply_saved','manager reply saved atomically');
select pg_temp.check_it((select count(*)=1 from public.messages where conversation_id=pg_temp.i(301)and content='Private exact staff reply'),'one staff reply exists');
select pg_temp.check_it(public.decide_luma_conversation(pg_temp.i(405),pg_temp.i(101),pg_temp.i(201),(select input from public.luma_conversation_commands where id=pg_temp.i(405)))->>'status'='reply_saved','lost reply replay returns saved message');
select pg_temp.check_it((select count(*)=1 from public.messages where conversation_id=pg_temp.i(301)and content='Private exact staff reply'),'lost reply cannot send twice');
select pg_temp.check_it((select count(*)=1 from public.luma_conversation_service_events where property_id=pg_temp.i(201)and kind='message_saved'),'staff command is not falsely re-attributed to a worker');
select pg_temp.check_it(public.save_luma_message_at_revision(pg_temp.i(201),pg_temp.i(301),'assistant','Private obsolete AI reply',0)->>'stale'='true','in-flight assistant response held during human control');
select pg_temp.check_it(pg_temp.command(406,'release')->>'status'='released','manager returns conversation to assistant');
select pg_temp.check_it(public.save_luma_message_at_revision(pg_temp.i(201),pg_temp.i(301),'assistant','Private older AI reply after release',0)->>'stale'='true','takeover and release cannot revive older in-flight response');
select pg_temp.check_it(not exists(select 1 from public.messages where conversation_id=pg_temp.i(301)and content like'Private older AI%'),'held response never reaches visitor transcript');
select pg_temp.check_it((select count(*)=2 from public.luma_conversation_service_events where property_id=pg_temp.i(201)and kind='reply_held'),'actual held responses retained privately');
select pg_temp.check_it(public.save_luma_message_at_revision(pg_temp.i(201),pg_temp.i(301),'assistant','Private current AI response',2)->>'saved'='true','response from current mode can be saved');
select pg_temp.check_it(pg_temp.command(407,'review')->>'status'='review_saved','exact transcript review retained');
insert into st values('review',(select source from public.luma_conversation_commands where id=pg_temp.i(407)));
select public.save_luma_message_at_revision(pg_temp.i(201),pg_temp.i(301),'user','Private new visitor message after review',null);
select pg_temp.check_it(pg_temp.command(408,'export',jsonb_build_object('reviewId',pg_temp.i(407)))->>'status'='export_prepared','exact historical transcript prepared');
select pg_temp.check_it((select result->>'artifact'not like'%Private new visitor message after review%'from public.luma_conversation_commands where id=pg_temp.i(408)),'download original does not absorb later messages');
select pg_temp.check_it((select source=(select v from st where k='review')from public.luma_conversation_commands where id=pg_temp.i(408)),'retained download uses exact source review');
select pg_temp.check_it(public.decide_luma_conversation(pg_temp.i(409),pg_temp.i(101),pg_temp.i(201),jsonb_build_object('operation','report','preparationId',pg_temp.i(408),'artifactHash',(select result->>'artifactHash'from public.luma_conversation_commands where id=pg_temp.i(408)),'outcome','download_initiated'))->>'status'='reported','actual browser outcome recorded separately');
select pg_temp.check_it((select evidence='browser_observed'and phase='observed'from public.shared_action_events where id=pg_temp.i(409)),'download observation never claims recipient receipt');
select pg_temp.check_it(pg_temp.command(410,'archive')->>'status'='archived','conversation archived with transcript retained');
select pg_temp.check_it(pg_temp.read_it('list')->>'count'='0','archived conversation omitted from active inbox');
select pg_temp.check_it(public.read_luma_conversations(pg_temp.i(101),pg_temp.i(201),null,'list',null,0,null,true)->>'count'='1','archived conversation remains reachable');
select pg_temp.check_it(pg_temp.command(411,'restore')->>'status'='restored','explicit archive restoration recorded');
select pg_temp.command(412,'archive');
select public.save_luma_message_at_revision(pg_temp.i(201),pg_temp.i(301),'user','Private new visitor message reopens inbox',null);
select pg_temp.check_it(pg_temp.read_it('list')->>'count'='1','new visitor message returns archived chat to active inbox');
select pg_temp.check_it((select count(*)=1 from public.luma_conversation_service_events where property_id=pg_temp.i(201)and kind='inbox_reopened'),'automatic reopening has actual system receipt');
select pg_temp.check_it(public.decide_luma_conversation(pg_temp.i(413),pg_temp.i(101),pg_temp.i(201),'{"operation":"cancel"}')->>'status'='cancelled','unused request cancelled');
select pg_temp.check_it(pg_temp.command(413,'takeover')->>'status'='cancelled','late cancelled takeover cannot execute');
select set_config('p11.luma_conversation_scope','',true);
select pg_temp.throws(format('update public.conversations set is_human_mode=true where id=%L',pg_temp.i(301)),'direct legacy takeover blocked');
select pg_temp.throws(format('update public.luma_conversation_commands set input=%L where id=%L','{}',pg_temp.i(403)),'private exact source cannot be rewritten');
select pg_temp.throws(format('delete from public.luma_conversation_commands where id=%L',pg_temp.i(403)),'private decisions cannot be erased');
select pg_temp.check_it(not exists(select 1 from public.shared_action_events where property_id=pg_temp.i(201)and(request::text||result::text||coalesce(before_state::text,'')||coalesce(after_state::text,''))like'%Private%'),'shared history excludes messages and staff reasons');
select pg_temp.check_it((select bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)),'human and system events excluded from training');
select pg_temp.check_it(not has_table_privilege('authenticated','public.luma_conversation_commands','select')and not has_function_privilege('authenticated','public.decide_luma_conversation(uuid,uuid,uuid,jsonb)','execute'),'private source and native mutation grants denied to clients');
-- Recording failure must roll back both mode and its visible notice.
reset role;
create function pg_temp.fail_conversation_action()returns trigger language plpgsql as $$begin if new.id=pg_temp.i(414)then raise exception 'Injected conversation action failure';end if;return new;end$$;
create trigger injected_conversation_action before insert on public.shared_action_events for each row execute function pg_temp.fail_conversation_action();
set local role service_role;
insert into st values('before-failure',public.luma_conversation_source(pg_temp.i(201),pg_temp.i(301)));
select pg_temp.throws($sql$select pg_temp.command(414,'takeover')$sql$,'history failure aborts takeover');
select pg_temp.check_it(public.luma_conversation_source(pg_temp.i(201),pg_temp.i(301))=(select v from st where k='before-failure'),'failed action preserves mode and messages exactly');
select pg_temp.check_it(not exists(select 1 from public.luma_conversation_commands where id=pg_temp.i(414)),'failed command does not claim success');
do $$begin for i in 501..531 loop perform public.decide_luma_conversation(pg_temp.i(i),pg_temp.i(101),pg_temp.i(201),'{"operation":"cancel"}');end loop;end$$;
select pg_temp.check_it(jsonb_array_length(public.read_luma_conversations(pg_temp.i(101),pg_temp.i(201),null,'history')->'items')=25,'history paged completely');
select pg_temp.check_it(jsonb_array_length(public.read_luma_conversations(pg_temp.i(101),pg_temp.i(201),null,'history',null,25)->'items')>0,'older history reachable');
insert into st values('history',public.read_luma_conversations(pg_temp.i(101),pg_temp.i(201),null,'history'));
select pg_temp.command(532,'review');
select pg_temp.check_it(public.read_luma_conversations(pg_temp.i(101),pg_temp.i(201),null,'history',null,25,(select v->>'hash'from st where k='history'))->>'state'='source_changed','changed history cannot silently skip records');
select pg_temp.check_it(public.read_luma_conversations(pg_temp.i(102),pg_temp.i(201),null,'command',pg_temp.i(407))->'command'->'source'=(select v from st where k='review'),'authorized member can read exact historical source');
select pg_temp.check_it(public.read_luma_conversations(pg_temp.i(103),pg_temp.i(201),null,'command',pg_temp.i(407))->>'state'='forbidden','other tenant cannot recover private messages');
select n as passed_assertions from assertion_count;
ROLLBACK;
