BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee830000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'Luma widget SQL fixture'),(pg_temp.i(2),'Luma widget other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','luma-widget-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,103)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,103)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'Luma widget SQL property'),(pg_temp.i(202),pg_temp.i(2),'Luma widget other property');
insert into public.lumaleasing_config(property_id,api_key,is_active)values(pg_temp.i(201),'luma_private_fixture_original',true);
create function pg_temp.read_it(actor int default 101,offset_n int default 0,hash text default null)returns jsonb language sql as $$select public.read_luma_widget_operations(pg_temp.i(actor),pg_temp.i(201),null,offset_n,hash)$$;
create function pg_temp.decide(n int,input jsonb,actor int default 101)returns jsonb language sql as $$select public.decide_luma_widget_operation(pg_temp.i(n),pg_temp.i(actor),pg_temp.i(201),input)$$;
create function pg_temp.rotate(n int,actor int default 101)returns jsonb language plpgsql as $$declare v text;begin v:=pg_temp.read_it(actor)->>'keyVersion';return pg_temp.decide(n,jsonb_build_object('operation','rotate','keyVersion',v,'replaceInstalledKey',true,'reason','Replace exact widget installation key'),actor);end$$;
create function pg_temp.prepare(n int,kind text default'embed')returns jsonb language plpgsql as $$declare v text;begin v:=pg_temp.read_it()->>'keyVersion';return pg_temp.decide(n,jsonb_build_object('operation','prepare','kind',kind,'keyVersion',v,'origin','http://127.0.0.1:9430'));end$$;
create function pg_temp.logo(n int,asset_n int default 501,actor int default 101)returns jsonb language plpgsql as $$declare rev text;a public.content_assets;begin rev:=pg_temp.read_it(actor)->>'configurationRevision';select*into a from public.content_assets where id=pg_temp.i(asset_n);return pg_temp.decide(n,jsonb_build_object('operation','logo','configurationRevision',rev,'assetId',a.id,'assetRevision',a.governance_revision,'contentHash',a.content_hash,'reason','Reviewed exact original logo'),actor);end$$;
set local role service_role;
select pg_temp.check_it(pg_temp.read_it()->>'state'='ready','property widget state read');
select pg_temp.check_it(pg_temp.read_it(102)->>'canManage'='false','viewer sees read-only controls');
select pg_temp.check_it(pg_temp.read_it(103)->>'state'='forbidden','other property member denied');
select pg_temp.check_it(pg_temp.rotate(301,102)->>'state'='forbidden','viewer cannot rotate public widget identity');
select pg_temp.check_it(public.save_recorded_luma_configuration(pg_temp.i(201),pg_temp.i(102),pg_temp.i(302),'save','{"widget_name":"Unauthorized"}',pg_temp.read_it()->>'configurationRevision')->>'state'='forbidden','viewer cannot bypass controls through settings');
insert into st values('installation',pg_temp.prepare(303));
select pg_temp.check_it((select v->>'artifact'like'%luma_private_fixture_original%'and v->>'artifact'like'%http://127.0.0.1:9430/lumaleasing.js%'from st where k='installation'),'exact scoped installation artifact retained');
select pg_temp.check_it(pg_temp.prepare(303)=(select v from st where k='installation'),'lost preparation reply replays exactly');
select pg_temp.check_it(pg_temp.decide(303,'{"operation":"cancel"}')=(select v from st where k='installation'),'cancel acknowledges already-saved preparation');
insert into st values('old-state',pg_temp.read_it());
select pg_temp.check_it(pg_temp.rotate(304)->>'status'='key_replaced','manager replaces current widget key');
select pg_temp.check_it((select api_key<>'luma_private_fixture_original'and length(api_key)=69 from public.lumaleasing_config where property_id=pg_temp.i(201)),'replacement key has new random identity');
select pg_temp.check_it(public.read_luma_widget_operations(pg_temp.i(101),pg_temp.i(201),pg_temp.i(303))->>'isCurrent'='false','historical handoff identifies replaced key');
select pg_temp.check_it(pg_temp.decide(303,(select input from public.luma_widget_commands where id=pg_temp.i(303)))->>'isCurrent'='false','replayed preparation cannot claim a replaced key remains current');
select pg_temp.check_it(pg_temp.decide(304,(select input from public.luma_widget_commands where id=pg_temp.i(304)))->>'status'='key_replaced','lost rotation reply replays original decision');
select pg_temp.check_it((select count(*)=1 from public.shared_action_events where property_id=pg_temp.i(201)and action='luma.widget.key_rotated'),'rotation recovery cannot replace another key');
select pg_temp.check_it(pg_temp.decide(305,jsonb_build_object('operation','rotate','keyVersion',(select v->>'keyVersion'from st where k='old-state'),'replaceInstalledKey',true,'reason','Stale rotation'))->>'state'='source_changed','stale installation key cannot rotate a newer key');
select pg_temp.check_it(pg_temp.decide(306,'{"operation":"cancel"}')->>'status'='cancelled','unused widget request closed');
select pg_temp.check_it(pg_temp.rotate(306)->>'status'='cancelled','late key rotation fenced');
select set_config('p11.luma_widget_scope','',true);
select pg_temp.throws(format('update public.lumaleasing_config set api_key=%L where property_id=%L','silent-replacement',pg_temp.i(201)),'old direct key writer rejected');
-- Exact current artifact can have separate actual browser outcomes; stable IDs deduplicate each outcome.
insert into st values('current-installation',pg_temp.prepare(307));
select pg_temp.check_it(pg_temp.decide(308,jsonb_build_object('operation','report','preparationId',pg_temp.i(307),'artifactHash',(select v->>'artifactHash'from st where k='current-installation'),'outcome','copied'))->>'status'='reported','browser copy report saved');
select pg_temp.check_it(pg_temp.decide(309,jsonb_build_object('operation','report','preparationId',pg_temp.i(307),'artifactHash',(select v->>'artifactHash'from st where k='current-installation'),'outcome','download_initiated'))->>'status'='reported','separate later download reports its own observation');
select pg_temp.check_it((select bool_and(evidence='browser_observed'and phase='observed')from public.shared_action_events where id in(pg_temp.i(308),pg_temp.i(309))),'handoff observations never claim installation or destination receipt');
select pg_temp.check_it(public.read_luma_widget_operations(pg_temp.i(102),pg_temp.i(201),pg_temp.i(307))->>'state'='not_found','another actor cannot recover private handoff');
select pg_temp.check_it(pg_temp.decide(310,jsonb_build_object('operation','report','preparationId',pg_temp.i(307),'artifactHash',repeat('0',64),'outcome','copied'))->>'state'='invalid_input','wrong artifact cannot report an outcome');
-- Reuse the actual managed upload/review lifecycle for logos.
insert into st values('upload',public.begin_forgestudio_asset_upload(pg_temp.i(501),pg_temp.i(201),pg_temp.i(101),jsonb_build_object('contentHash',repeat('a',64),'size',100,'mimeType','image/png','extension','png','metadata','{"name":"Private original logo","description":"Retained source","asset_type":"image","rights_status":"unknown","rights_metadata":{"license":"Private license note"},"tags":[]}'::jsonb)));
select public.finish_forgestudio_asset_upload(pg_temp.i(501),pg_temp.i(201),pg_temp.i(101),jsonb_build_object('contentHash',repeat('a',64),'storagePath',(select v->>'storagePath'from st where k='upload'),'storageBucket','property-assets','storageVerified',true,'fileUrl','https://example.invalid/retained-logo.png'));
select pg_temp.check_it(pg_temp.logo(311)->>'state'='asset_changed','unapproved logo is held');
select public.manage_forgestudio_asset(pg_temp.i(502),pg_temp.i(201),pg_temp.i(101),(select jsonb_build_object('assetId',id,'revision',governance_revision,'action','review','reason','Review exact logo usage','review',jsonb_build_object('approval_status','approved','rights_status','owned'))from public.content_assets where id=pg_temp.i(501)));
select pg_temp.check_it(pg_temp.logo(312,501,102)->>'state'='forbidden','viewer cannot select a logo');
select pg_temp.check_it(pg_temp.logo(312)->>'status'='logo_selected','reviewed logo applied with evidence');
select pg_temp.check_it(public.luma_widget_logo(pg_temp.i(201))->>'url'='https://example.invalid/retained-logo.png','public config uses approved retained file');
select pg_temp.check_it((select after_state->'asset'->>'name'='Private original logo'from public.luma_widget_commands where id=pg_temp.i(312)),'exact asset version retained privately');
select pg_temp.check_it(public.luma_configuration_snapshot(pg_temp.i(201))->'managedLogo'->>'assetId'=pg_temp.i(501)::text,'configuration revision includes selected source');
insert into st values('before-archive',pg_temp.read_it());
select public.manage_forgestudio_asset(pg_temp.i(503),pg_temp.i(201),pg_temp.i(101),(select jsonb_build_object('assetId',id,'revision',governance_revision,'action','archive','reason','Stop using the original logo')from public.content_assets where id=pg_temp.i(501)));
select pg_temp.check_it(public.luma_widget_logo(pg_temp.i(201))->>'url'is null,'archived logo is omitted from public configuration');
select pg_temp.check_it(pg_temp.read_it()->>'configurationRevision'is distinct from(select v->>'configurationRevision'from st where k='before-archive'),'source withdrawal changes saved configuration review');
select pg_temp.check_it(pg_temp.logo(313)->>'state'='asset_changed','archived logo cannot be reselected');
select pg_temp.check_it(pg_temp.decide(314,jsonb_build_object('operation','clear_logo','configurationRevision',pg_temp.read_it()->>'configurationRevision','reason','Remove withdrawn original'))->>'status'='logo_cleared','explicit removal recorded');
select pg_temp.check_it(not exists(select 1 from public.luma_widget_assets where property_id=pg_temp.i(201)),'current binding cleared while decision originals remain');
-- Recording failure rolls back the key mutation.
reset role;
create function pg_temp.fail_widget_action()returns trigger language plpgsql as $$begin if new.id=pg_temp.i(315)then raise exception 'injected widget action failure';end if;return new;end$$;
create trigger injected_widget_action before insert on public.shared_action_events for each row execute function pg_temp.fail_widget_action();
set local role service_role;
insert into st values('before-failure',pg_temp.read_it());
select pg_temp.throws('select pg_temp.rotate(315)','history failure aborts key replacement');
select pg_temp.check_it(pg_temp.read_it()->>'keyVersion'=(select v->>'keyVersion'from st where k='before-failure'),'old key remains valid when recording fails');
select pg_temp.check_it(not exists(select 1 from public.luma_widget_commands where id=pg_temp.i(315)),'failed key command is not claimed successful');
select set_config('p11.luma_widget_scope',pg_temp.i(201)::text,true);
select pg_temp.throws(format('update public.luma_widget_commands set input=%L where id=%L','{}',pg_temp.i(304)),'exact decision cannot be rewritten');
select pg_temp.throws(format('delete from public.luma_widget_commands where id=%L',pg_temp.i(304)),'saved decision cannot be erased');
select pg_temp.check_it(not exists(select 1 from public.shared_action_events where property_id=pg_temp.i(201)and action like'luma.widget.%'and(request::text||coalesce(before_state::text,'')||coalesce(after_state::text,'')||result::text)like'%Private%'),'shared history excludes private original notes');
select pg_temp.check_it(not exists(select 1 from public.shared_action_events where property_id=pg_temp.i(201)and action like'luma.widget.%'and(request::text||coalesce(before_state::text,'')||coalesce(after_state::text,'')||result::text)like'%luma_private_fixture%'),'shared history excludes installation keys');
select pg_temp.check_it((select bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)and action like'luma.widget.%'),'all widget evidence training ineligible');
insert into st values('old-history',pg_temp.read_it());
select pg_temp.decide(700+n,'{"operation":"cancel"}')from generate_series(1,28)n;
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it(101,25)->'items')>0,'complete next history page');
select pg_temp.check_it(pg_temp.read_it(101,25,(select v->>'hash'from st where k='old-history'))->>'state'='history_changed','history continuation rejects changed version');
select pg_temp.check_it(not exists(select 1 from jsonb_array_elements(pg_temp.read_it()->'items')x where x->'result'?'artifact'),'history summaries do not expose private installation artifacts');
reset role;
select pg_temp.check_it(not has_table_privilege('authenticated','public.luma_widget_commands','select'),'browser role cannot read private handoffs directly');
select pg_temp.check_it(not has_function_privilege('authenticated','public.decide_luma_widget_operation(uuid,uuid,uuid,jsonb)','execute'),'browser role cannot impersonate staff decisions');
set constraints all immediate;
select n as assertions from assertion_count;
ROLLBACK;
