BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee850000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'Luma reads SQL fixture'),(pg_temp.i(2),'Luma reads other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','luma-read-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,103)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,103)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'Luma reads SQL property'),(pg_temp.i(202),pg_temp.i(2),'Luma reads other property');
insert into public.conversations(id,property_id,channel)values(pg_temp.i(301),pg_temp.i(201),'widget'),(pg_temp.i(302),pg_temp.i(202),'widget');
set local role service_role;
insert into st values('empty',public.read_luma_overview(pg_temp.i(101),pg_temp.i(201)));
select pg_temp.check_it((select v->>'state'='ready'from st where k='empty'),'authorized overview');
select pg_temp.check_it((select(v->>'totalSessions')::int=0 and v->'conversionRate'='null'::jsonb and v->'tourBookingRate'='null'::jsonb from st where k='empty'),'empty denominators are unknown rather than zero percent');
select pg_temp.check_it((select v->'avgResponseTime'='null'::jsonb from st where k='empty'),'unmeasured latency is unknown');
select pg_temp.check_it(public.read_luma_overview(pg_temp.i(102),pg_temp.i(201))->>'state'='ready','viewer can read');
select pg_temp.check_it(public.read_luma_overview(pg_temp.i(103),pg_temp.i(201))->>'state'='forbidden','other tenant denied');
insert into public.widget_sessions(property_id,visitor_id)select pg_temp.i(201),'luma-fixture-'||n from generate_series(1,1005)n;
insert into public.conversations(property_id,channel)select pg_temp.i(201),'widget'from generate_series(1,55);
insert into st values('full',public.read_luma_overview(pg_temp.i(101),pg_temp.i(201)));
select pg_temp.check_it((select(v->>'totalSessions')::int=1005 from st where k='full'),'count exceeds API row limit');
select pg_temp.check_it((select(v->>'totalConversations')::int=56 from st where k='full'),'count exceeds previous 50 conversation sample');
select pg_temp.check_it((select jsonb_array_length(v->'conversations')=5 from st where k='full'),'recent preview explicitly five');
insert into public.leads(id,property_id,first_name,last_name,source,status)values(pg_temp.i(401),pg_temp.i(201),'One','Lead','widget','new'),(pg_temp.i(402),pg_temp.i(201),'Two','Lead','widget','new');
insert into public.widget_sessions(property_id,lead_id,visitor_id)values(pg_temp.i(201),pg_temp.i(401),'lead-fixture-a'),(pg_temp.i(201),pg_temp.i(401),'lead-fixture-b'),(pg_temp.i(201),pg_temp.i(402),'lead-fixture-c');
insert into public.tour_bookings(property_id,lead_id,source,status,scheduled_date,scheduled_time)values(pg_temp.i(201),pg_temp.i(401),'lumaleasing','scheduled','2030-01-01','10:00'),(pg_temp.i(201),pg_temp.i(401),'lumaleasing','completed','2030-01-02','10:00'),(pg_temp.i(201),pg_temp.i(402),'lumaleasing','cancelled','2030-01-03','10:00');
insert into st values('rates',public.read_luma_overview(pg_temp.i(101),pg_temp.i(201)));
select pg_temp.check_it((select(v->>'totalSessions')::int=1008 and(v->>'linkedSessions')::int=3 and(v->>'uniqueLeads')::int=2 from st where k='rates'),'repeat sessions count separately from unique leads');
select pg_temp.check_it((select(v->>'tourBookingRate')::numeric=50 and(v->>'tourLeads')::int=1 and(v->>'toursBooked')::int=3 from st where k='rates'),'repeated bookings cannot inflate distinct lead conversion and cancelled tours do not qualify');
update public.conversations set lead_id=pg_temp.i(401)where id=pg_temp.i(301);
select pg_temp.check_it(public.read_luma_conversations(pg_temp.i(101),pg_temp.i(201),null,'list',null,0,null,false,pg_temp.i(401))->>'count'='1','lead inbox scoped to its linked conversation');
select pg_temp.check_it(public.read_luma_conversations(pg_temp.i(101),pg_temp.i(201),pg_temp.i(301),'messages',null,0,null,false,pg_temp.i(402))->>'state'='not_found','lead transcript cannot silently show another lead');
insert into public.messages(id,conversation_id,role,content,created_at)select pg_temp.i(1000+n),pg_temp.i(301),'assistant','message '||n,'2026-01-01'::timestamptz from generate_series(1,405)n;
insert into public.messages(id,conversation_id,role,content,created_at)values(pg_temp.i(1500),pg_temp.i(301),'user','unknown time',null),(pg_temp.i(1501),pg_temp.i(301),'system','Private system notice',now()),(pg_temp.i(1502),pg_temp.i(302),'user','Other tenant message',now()),(pg_temp.i(1503),pg_temp.i(301),'user','',now());
insert into st values('one',public.read_luma_visitor_messages(pg_temp.i(201),pg_temp.i(301)));
select pg_temp.check_it((select jsonb_array_length(v->'messages')=200 and(v->>'hasEarlierMessages')::boolean from st where k='one'),'first bounded page advertises more');
select pg_temp.check_it((select v->'messages'->0->>'content'='message 206'from st where k='one'),'tied timestamps page deterministically');
insert into st values('two',public.read_luma_visitor_messages(pg_temp.i(201),pg_temp.i(301),(select(v->>'nextBeforeId')::uuid from st where k='one')));
insert into public.messages(id,conversation_id,role,content)values(pg_temp.i(1600),pg_temp.i(301),'assistant','New message during paging');
insert into st values('three',public.read_luma_visitor_messages(pg_temp.i(201),pg_temp.i(301),(select(v->>'nextBeforeId')::uuid from st where k='two')));
select pg_temp.check_it((select jsonb_array_length(v->'messages')=200 from st where k='two'),'second full page');
select pg_temp.check_it((select jsonb_array_length(v->'messages')=6 and not(v->>'hasEarlierMessages')::boolean and v->'nextBeforeId'='null'::jsonb from st where k='three'),'last page complete including null timestamp');
select pg_temp.check_it((select v->'messages'->0->>'content'='unknown time'from st where k='three'),'null timestamps reachable');
select pg_temp.check_it((select count(distinct m->>'id')=406 from st cross join lateral jsonb_array_elements(v->'messages')m where k in('one','two','three')),'all original messages exactly once while inserts continue');
select pg_temp.check_it((select string_agg(v::text,'')not like'%Private system%'and string_agg(v::text,'')not like'%Other tenant%'from st),'public pages exclude private and other tenant data');
select pg_temp.check_it(public.read_luma_visitor_messages(pg_temp.i(202),pg_temp.i(301))->>'state'='not_found','property scoped transcript');
select pg_temp.check_it(public.read_luma_visitor_messages(pg_temp.i(201),pg_temp.i(301),pg_temp.i(1502))->>'state'='source_changed','other conversation cursor rejected');
select pg_temp.check_it(public.read_luma_visitor_messages(pg_temp.i(201),pg_temp.i(301),pg_temp.i(1501))->>'state'='source_changed','private notice cursor rejected');
select pg_temp.check_it(not has_function_privilege('authenticated','public.read_luma_overview(uuid,uuid)','EXECUTE'),'overview native service only');
select pg_temp.check_it(not has_function_privilege('anon','public.read_luma_visitor_messages(uuid,uuid,uuid)','EXECUTE'),'public transcript native service only');
reset role;
select 'Assertions passed: '||n from assertion_count;
ROLLBACK;
