begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,competitor_id uuid,report_id uuid,recommendation_id uuid);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision brief rollback fixture'from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision other brief rollback fixture'from fixture;
insert into public.competitors(id,property_id,name,is_active)select competitor_id,property_id,'Saved brief competitor',true from fixture;
insert into public.competitor_units(competitor_id,unit_type,bedrooms,rent_min)select competitor_id,'One bedroom',1,1200 from fixture;
insert into public.property_units(org_id,property_id,unit_type,canonical_key,bedrooms,rent_min,active,review_status,expires_at)select '22222222-2222-2222-2222-222222222222'::uuid,f.property_id,n,n,1,1800,true,case when n='pending'then 'pending'else 'approved'end,case when n='expired'then statement_timestamp()-interval '1 day'else null end from fixture f cross join unnest(array['approved','pending','expired'])n;
create function pg_temp.result_for(report_id uuid,rec uuid)returns jsonb language sql as $$select jsonb_build_object('schemaVersion','market-brief-v2','reportId',r.id,'propertyId',r.property_id,'sourceHash',r.source_hash,'snapshotAt',r.source_snapshot->>'snapshotAt','analysis','{}'::jsonb,'recommendations',jsonb_build_array(jsonb_build_object('id',rec,'title','Review exact sources','kind','source_review','priority','review','rationale','Dates are unknown','evidence','[]'::jsonb,'subjectIds','[]'::jsonb,'limitations','[]'::jsonb)))from public.marketvision_briefs r where r.id=report_id;$$;
do $$declare f fixture;r jsonb;b public.marketvision_briefs;payload jsonb:='{"windowDays":30,"reason":"Reviewed exact report scope"}';review_input jsonb;command uuid:=gen_random_uuid();export_id uuid:=gen_random_uuid();last_id uuid;old_source jsonb;begin select * into f from fixture;
 perform pg_temp.check(not has_function_privilege('authenticated','public.begin_marketvision_brief(uuid,uuid,uuid,jsonb)','execute')and not has_table_privilege('authenticated','public.marketvision_briefs','select'),'clients cannot forge report sources or read private snapshots directly');
 perform pg_temp.check(not has_table_privilege('authenticated','public.market_insights','insert'),'legacy arbitrary insight insertion is closed');
 perform pg_temp.check(public.begin_marketvision_brief(f.report_id,f.property_id,gen_random_uuid(),payload)->>'state'='forbidden','report requests require current property access');
 r:=public.begin_marketvision_brief(f.report_id,f.property_id,f.actor_id,payload);perform pg_temp.check(r->>'state'='prepared'and r->>'version'='1','exact report source saved before local computation');
 select * into b from public.marketvision_briefs where id=f.report_id;old_source:=b.source_snapshot;
 perform pg_temp.check(jsonb_array_length(b.source_snapshot->'subjectUnits')=1 and b.source_snapshot->'subjectUnits'->0->>'unit_type'='approved','only current approved subject inventory is compared');
 perform pg_temp.check((select context_payload=b.source_snapshot and context_hash=b.source_hash from public.shared_context_snapshots where id=b.context_id),'shared context and private source are identical');
 perform pg_temp.check((select actor_id=f.actor_id and shared_job_ref=f.report_id and context_snapshot_ref=b.context_id from public.shared_action_events where id=f.report_id),'request action links actual operator, job and exact context');
 perform pg_temp.check(public.begin_marketvision_brief(f.report_id,f.property_id,f.actor_id,payload)->>'state'='prepared'and(select count(*)=1 from public.marketvision_briefs where id=f.report_id),'interrupted requests resume one saved brief');
 perform pg_temp.check(public.begin_marketvision_brief(f.report_id,f.property_id,f.actor_id,payload||'{"windowDays":7}')->>'state'='request_conflict','request identity cannot select new report input');
 perform pg_temp.check(public.read_marketvision_briefs(f.other_property,f.actor_id,f.report_id)->>'state'='not_found','report details do not cross property boundaries');
 perform pg_temp.check(public.read_marketvision_briefs(f.property_id,f.actor_id,f.report_id)->>'sourceChanged'='false','an immediate current check does not fabricate a changed snapshot');
 update public.competitor_units set rent_min=1300 where competitor_id=f.competitor_id;
 perform pg_temp.check(public.read_marketvision_briefs(f.property_id,f.actor_id,f.report_id)->>'sourceChanged'='true'and(select source_snapshot=old_source from public.marketvision_briefs where id=f.report_id),'source changes are explicit and original evidence is immutable');
 perform pg_temp.check(public.complete_marketvision_brief(f.report_id,f.other_property,f.actor_id,b.source_hash,pg_temp.result_for(f.report_id,f.recommendation_id))->>'state'='not_found','completion cannot cross properties');
 perform pg_temp.check(public.complete_marketvision_brief(f.report_id,f.property_id,f.actor_id,'different',pg_temp.result_for(f.report_id,f.recommendation_id))->>'state'='request_conflict','completion requires original source hash');
 r:=public.complete_marketvision_brief(f.report_id,f.property_id,f.actor_id,b.source_hash,pg_temp.result_for(f.report_id,f.recommendation_id));perform pg_temp.check(r->>'state'='ready'and r->>'version'='2','retained historical evidence can finish without substituting live sources');
 perform pg_temp.check((select actor_id is null and service_principal='marketvision.brief'and shared_job_ref=f.report_id from public.shared_action_events where action='market.brief.completed'and property_id=f.property_id),'actual local report calculation has a separate service identity');
 perform pg_temp.check(public.complete_marketvision_brief(f.report_id,f.property_id,f.actor_id,b.source_hash,pg_temp.result_for(f.report_id,f.recommendation_id))->>'state'='ready'and(select count(*)=1 from public.shared_action_events where action='market.brief.completed'and property_id=f.property_id),'lost completion response preserves one result');
 perform pg_temp.check(public.complete_marketvision_brief(f.report_id,f.property_id,f.actor_id,b.source_hash,pg_temp.result_for(f.report_id,f.recommendation_id)||'{"changed":true}')->>'state'='request_conflict','completed report cannot be rewritten');
 review_input:=jsonb_build_object('briefId',f.report_id,'expectedVersion',2,'recommendationId',f.recommendation_id,'decision','consider','expectedReviewId',null,'acknowledgedSourceChange',false,'reason','Reviewed exact historical recommendation');
 perform pg_temp.check(public.review_marketvision_brief(command,f.property_id,f.actor_id,review_input)->>'state'='source_changed','changed sources require explicit historical acknowledgment');
 review_input:=review_input||'{"acknowledgedSourceChange":true}';r:=public.review_marketvision_brief(command,f.property_id,f.actor_id,review_input);
 perform pg_temp.check(r->>'state'='saved'and r->>'executionStarted'='false'and r->>'businessOutcome'='unknown','review decision does not claim execution or business success');
 perform pg_temp.check(public.review_marketvision_brief(command,f.property_id,f.actor_id,review_input)->>'state'='replayed','lost review response recovers one decision');
 perform pg_temp.check(public.review_marketvision_brief(gen_random_uuid(),f.property_id,f.actor_id,review_input||'{"decision":"dismiss"}')->>'state'='stale_review','an old review cannot silently overwrite another operator decision');
 r:=public.review_marketvision_brief(gen_random_uuid(),f.property_id,f.actor_id,review_input||jsonb_build_object('decision','dismiss','expectedReviewId',command));perform pg_temp.check(r->>'state'='saved','reviewed correction retains the earlier consideration decision');
 review_input:=jsonb_build_object('briefId',f.report_id,'expectedVersion',2,'format','markdown','reason','Prepare exact historical report download');
 r:=public.export_marketvision_brief(export_id,f.property_id,f.actor_id,review_input,'# Exact saved report bytes');
 perform pg_temp.check(r->>'state'='saved'and r->>'contentHash'=encode(extensions.digest(convert_to('# Exact saved report bytes','UTF8'),'sha256'),'hex'),'download artifact retains exact bytes and hash');
 perform pg_temp.check(public.export_marketvision_brief(export_id,f.property_id,f.actor_id,review_input,'different renderer bytes')->>'content'='# Exact saved report bytes','lost artifact response returns original bytes even if renderer changed');
 perform pg_temp.check((select result->>'downloadConfirmed'='false'and result->>'externalDelivery'='false'from public.marketvision_decisions where id=export_id),'prepared file never claims confirmed delivery');
 begin update public.marketvision_briefs set source_snapshot='{}'where id=f.report_id;raise exception 'expected source guard';exception when others then if sqlerrm='expected source guard'then raise;end if;end;
 begin update public.marketvision_brief_exports set content='changed'where id=export_id;raise exception 'expected artifact guard';exception when others then if sqlerrm='expected artifact guard'then raise;end if;end;
 perform pg_temp.check(true,'original snapshots and report artifacts are immutable');
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.read_marketvision_briefs(f.property_id,f.actor_id,f.report_id)->>'state'='forbidden'and public.export_marketvision_brief(export_id,f.property_id,f.actor_id,review_input,'unused')->>'state'='forbidden','access revocation blocks history and export replay');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
end$$;
-- More than one page; no report disappears behind the first 20 rows.
do $$declare f fixture;i integer;r jsonb;next_page jsonb;begin select * into f from fixture;for i in 1..22 loop perform public.begin_marketvision_brief(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('windowDays',7,'reason','History fixture report '||i));end loop;r:=public.read_marketvision_briefs(f.property_id,f.actor_id);next_page:=public.read_marketvision_briefs(f.property_id,f.actor_id,null,(r->>'nextCursor')::uuid);
 perform pg_temp.check(jsonb_array_length(r->'reports')=20 and jsonb_array_length(next_page->'reports')=3 and next_page->>'nextCursor'is null,'report history pages every saved request');
 perform pg_temp.check(public.read_marketvision_briefs(f.other_property,f.actor_id,null,(r->>'nextCursor')::uuid)->>'state'='cursor_changed','history cursors are scoped');
 insert into public.market_insights(property_id,insight_type,data)values(f.property_id,'market_brief','{"historical":"retained"}');
 r:=public.read_marketvision_legacy_briefs(f.property_id,f.actor_id);perform pg_temp.check(jsonb_array_length(r->'legacyReports')=1 and public.read_marketvision_legacy_briefs(f.property_id,f.actor_id,(r->'legacyReports'->0->>'id')::uuid)->'legacyReport'->'data'='{"historical":"retained"}'::jsonb,'legacy reports remain readable without being requalified');
end$$;
-- Result and artifact events are part of the same transaction as their state changes.
create function pg_temp.reject_brief_result()returns trigger language plpgsql as $$begin if new.action in('market.brief.completed','market.brief.exported')then raise exception 'isolated result event failure';end if;return new;end$$;
create trigger test_brief_result_failure before insert on public.shared_action_events for each row execute function pg_temp.reject_brief_result();
do $$declare f fixture;request uuid:=gen_random_uuid();download uuid:=gen_random_uuid();r public.marketvision_briefs;recovery uuid:=gen_random_uuid();payload jsonb;begin select * into f from fixture;
 perform public.begin_marketvision_brief(request,f.property_id,f.actor_id,'{"windowDays":7,"reason":"Completion rollback source"}');select * into r from public.marketvision_briefs where id=request;
 begin perform public.complete_marketvision_brief(request,f.property_id,f.actor_id,r.source_hash,pg_temp.result_for(request,f.recommendation_id));raise exception 'expected result failure';exception when others then if sqlerrm='expected result failure'then raise;end if;end;
 perform pg_temp.check((select state='prepared'and result is null and version=1 from public.marketvision_briefs where id=request)and(select lifecycle_status='queued'from public.shared_jobs where id=request),'result-event failure rolls back report completion and job success');
 begin perform public.export_marketvision_brief(download,f.property_id,f.actor_id,jsonb_build_object('briefId',f.report_id,'expectedVersion',2,'format','json','reason','Atomic artifact fixture'),'Exact artifact content');raise exception 'expected export failure';exception when others then if sqlerrm='expected export failure'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.marketvision_brief_exports where id=download)and not exists(select 1 from public.marketvision_decisions where id=download),'artifact-event failure leaves no artifact or successful decision');
 payload:=jsonb_build_object('briefId',request,'expectedVersion',1,'reason','Recover exact saved report');
 perform pg_temp.check(public.recover_marketvision_brief(recovery,f.property_id,f.actor_id,payload||'{"expectedVersion":2}')->>'state'='stale_report','recovery requires the reviewed report version');
 perform pg_temp.check(public.recover_marketvision_brief(recovery,f.property_id,f.actor_id,payload)->>'state'='saved'and public.recover_marketvision_brief(recovery,f.property_id,f.actor_id,payload)->>'state'='replayed','explicit recovery is recorded once');
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.complete_marketvision_brief(request,f.property_id,f.actor_id,r.source_hash,pg_temp.result_for(request,f.recommendation_id))->>'state'='forbidden','revoked access cannot finish a queued report');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
end$$;
drop trigger test_brief_result_failure on public.shared_action_events;
-- Action failure must roll back the report, context and job in the same transaction.
create function pg_temp.reject_brief_event()returns trigger language plpgsql as $$begin if new.action='market.brief.requested'then raise exception 'isolated action failure';end if;return new;end$$;
create trigger test_brief_event_failure before insert on public.shared_action_events for each row execute function pg_temp.reject_brief_event();
do $$declare f fixture;request uuid:=gen_random_uuid();begin select * into f from fixture;begin perform public.begin_marketvision_brief(request,f.property_id,f.actor_id,'{"windowDays":7,"reason":"Atomic brief request fixture"}');raise exception 'expected event failure';exception when others then if sqlerrm='expected event failure'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.marketvision_briefs where id=request)and not exists(select 1 from public.shared_jobs where id=request)and not exists(select 1 from public.shared_context_snapshots where source_ref=request::text),'action failure rolls back report, context and job');
end$$;
select count(*)as passed_assertions from checks;
rollback;
