begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create function pg_temp.reject_brand_history()returns trigger language plpgsql as $$begin if new.action='market.brand.published'then raise exception 'Synthetic history failure';end if;return new;end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,competitor_id uuid,source_id uuid,request_id uuid,input jsonb,model jsonb,preview jsonb);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,'{"claims":[{"category":"positioning","kind":"source_claim","statement":"The website describes garden living.","quote":"Garden living beside the park"},{"category":"voice","kind":"interpretation","statement":"Inviting language.","quote":"Welcome home"}],"notes":"One captured page only"}');
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision brand rollback fixture'from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision other brand rollback fixture'from fixture;
insert into public.competitors(id,property_id,name,property_type,website_url)select competitor_id,property_id,'Brand fixture competitor','multifamily','https://example.com/brand/'from fixture;
do $$declare f fixture;claim jsonb;body text:='<p>Garden living beside the park. Welcome home to our community. Ask the team about current availability and offers.</p>';content text:='Garden living beside the park. Welcome home to our community. Ask the team about current availability and offers.';begin select *into f from fixture;
 perform public.begin_marketvision_source(f.source_id,f.property_id,f.actor_id,jsonb_build_object('competitorId',f.competitor_id,'expectedVersion',1,'source','website','reason','Review isolated brand source'));
 claim:=public.claim_marketvision_source(f.source_id);
 perform public.record_marketvision_source_result(f.source_id,(claim->>'claimToken')::uuid,jsonb_build_object('status','received','transport','public_http_v1','parserVersion','public-html-v1','requestedUrl','https://example.com/brand/','finalUrl','https://example.com/brand/','statusCode',200,'contentType','text/html','fetchedAt',clock_timestamp(),'body',body,'bodyHash',encode(sha256(convert_to(body,'UTF8')),'hex'),'text',content,'textTruncated',false));
 update fixture set input=jsonb_build_object('competitorId',f.competitor_id,'sourceId',f.source_id,'sourceVersion',(select version from public.marketvision_source_requests where id=f.source_id),'confirmedSourceScope',true,'reason','Review exact page for brand claims'),model=jsonb_build_object('model','gpt-4o-mini','promptVersion','brand-evidence-v1','maxTokens',8000,'systemPrompt','Isolated model recipe','userPrompt',content,'source',jsonb_build_object('content',content,'sourceUrl','https://example.com/brand/','competitorName','Brand fixture competitor'));
end$$;
create function pg_temp.prepare_brand(rid uuid)returns void language plpgsql as $$declare f fixture;claim jsonb;receipt jsonb;begin select *into f from fixture;perform public.begin_marketvision_brand(rid,f.property_id,f.actor_id,f.input,f.model);claim:=public.claim_marketvision_brand(rid);receipt:=jsonb_build_object('status','received','content',f.preview::text,'finishReason','stop','usage',jsonb_build_object('inputTokens',100,'outputTokens',20));perform public.record_marketvision_brand_result(rid,(claim->>'claimToken')::uuid,receipt);perform public.prepare_marketvision_brand_preview(rid,public.crm_configuration_hash(receipt),f.preview);end$$;
create function pg_temp.review_input(rid uuid,previous uuid)returns jsonb language sql as $$select jsonb_build_object('brandRequestId',r.id,'expectedVersion',r.version,'previewHash',r.preview_hash,'expectedReviewId',previous,'action','publish','acknowledgeInterpretation',true,'acknowledgeReplacement',true,'selection',jsonb_build_array(jsonb_build_object('sourceIndex',0,'action','include','claim',r.preview->'claims'->0),jsonb_build_object('sourceIndex',1,'action','skip')),'reason','Review quoted statement and skip interpretation')from public.marketvision_brand_requests r where r.id=rid$$;

create function pg_temp.search_input(q text,mode text default 'all')returns jsonb language sql as $$select jsonb_build_object('query',q,'mode',mode,'category','all','kind','all','competitorId',null,'reason','Search reviewed evidence in isolated fixture')$$;
create temp table saved_search(id uuid,payload jsonb);
insert into saved_search values(gen_random_uuid(),pg_temp.search_input('GARDEN park'));
do $$declare f fixture;v_id uuid;v_payload jsonb;r jsonb;review_id uuid:=gen_random_uuid();withdraw_id uuid:=gen_random_uuid();begin select *into f from fixture;select id,payload into v_id,v_payload from saved_search;
 perform pg_temp.prepare_brand(f.request_id);
 insert into public.competitor_brand_intelligence(competitor_id,positioning_statement)values(f.competitor_id,'Garden living is an unqualified legacy analysis');
 perform pg_temp.check(public.save_marketvision_brand_search(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.search_input('garden'))->>'matches'='0','unreviewed generation and legacy analysis are excluded from new search');
 perform public.review_marketvision_brand(review_id,f.property_id,f.actor_id,pg_temp.review_input(f.request_id,null));
 perform pg_temp.check(not has_table_privilege('authenticated','public.marketvision_brand_searches','select')and not has_function_privilege('anon','public.save_marketvision_brand_search(uuid,uuid,uuid,jsonb)','execute'),'saved query context and search execution stay server private');
 perform pg_temp.check(public.save_marketvision_brand_search(v_id,f.property_id,gen_random_uuid(),v_payload)->>'state'='forbidden','search requires current property access');
 perform pg_temp.check(public.save_marketvision_brand_search(v_id,f.property_id,f.actor_id,v_payload||jsonb_build_object('competitorId',gen_random_uuid()))->>'state'='not_found','search cannot select a foreign competitor');
 r:=public.save_marketvision_brand_search(v_id,f.property_id,f.actor_id,v_payload);perform pg_temp.check(r->>'state'='saved'and r->>'matches'='1'and r->'modelInvoked'='false'::jsonb and r->'embeddingInvoked'='false'::jsonb,'case-insensitive all-word search saves exact matches without a model');
 perform pg_temp.check(public.save_marketvision_brand_search(v_id,f.property_id,f.actor_id,v_payload)->>'state'='replayed','lost response reopens original search instead of new execution');
 perform pg_temp.check(public.save_marketvision_brand_search(v_id,f.property_id,f.actor_id,pg_temp.search_input('different'))->>'state'='request_conflict','search identity cannot replace saved terms');
 r:=public.read_marketvision_brand_searches(f.property_id,f.actor_id,v_id);
 perform pg_temp.check(r->'items'->0->'claim'->>'quote'='Garden living beside the park'and r->'items'->0->>'reviewId'=review_id::text and r->'items'->0->'stillCurrent'='true'::jsonb,'results retain exact quotation and current review identity');
 perform pg_temp.check(not(r->'search'?'context')and not(r->'search'?'actor_id')and r->'search'->'coverage'->>'reviewedCompetitors'='1','read projection exposes coverage without full private context');
 perform pg_temp.check((select not(request?'query')and result->>'matches'='1'from public.shared_action_events where id=v_id),'shared action history records confirmed counts without raw query text');
 perform pg_temp.check(not public.marketvision_brand_search_matches('{"statement":"garden","quote":"park"}',array['garden','missing'],'all')and public.marketvision_brand_search_matches('{"statement":"garden","quote":"park"}',array['garden','missing'],'any'),'all and any matching have explicit different semantics');
 perform pg_temp.check(not public.marketvision_brand_search_matches('{"statement":"garden beside park","quote":"garden"}',array['garden park'],'phrase'),'phrase mode does not fabricate adjacent words');
 perform pg_temp.check(not public.marketvision_brand_search_matches('{"statement":"garden","quote":"park"}',array['%'],'phrase'),'percent and wildcard text are literal rather than SQL patterns');
 perform pg_temp.check(public.save_marketvision_brand_search(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.search_input('garden')||'{"category":"amenity"}')->>'matches'='0','category filters do not include unrelated positioning claims');
 perform pg_temp.check(public.save_marketvision_brand_search(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.search_input('garden')||'{"kind":"interpretation"}')->>'matches'='0','claim and interpretation filters retain the reviewed classification');
 begin update public.marketvision_brand_searches set results='[]'where id=v_id;raise exception 'expected immutable snapshot';exception when others then if sqlerrm='expected immutable snapshot'then raise;end if;end;
 perform pg_temp.check((select jsonb_array_length(results)=1 from public.marketvision_brand_searches where id=v_id),'saved matching results cannot be rewritten');
 perform public.review_marketvision_brand(withdraw_id,f.property_id,f.actor_id,jsonb_build_object('brandRequestId',f.request_id,'expectedVersion',(select version from public.marketvision_brand_requests where id=f.request_id),'expectedReviewId',review_id,'action','withdraw','reason','Withdraw evidence after saved search'));
 r:=public.read_marketvision_brand_searches(f.property_id,f.actor_id,v_id);
 perform pg_temp.check(jsonb_array_length(r->'items')=1 and r->'items'->0->'stillCurrent'='false'::jsonb,'withdrawn evidence remains in an old search with an explicit historical status');
 perform pg_temp.check(public.save_marketvision_brand_search(gen_random_uuid(),f.property_id,f.actor_id,v_payload)->>'matches'='0','new searches exclude withdrawal rather than reusing an older approved review');
 perform public.review_marketvision_brand(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.review_input(f.request_id,withdraw_id));
 update public.competitors set name='Changed search source'where id=f.competitor_id;
 perform pg_temp.check(public.save_marketvision_brand_search(gen_random_uuid(),f.property_id,f.actor_id,v_payload)->>'matches'='0','new searches exclude changed competitor baselines');
 perform pg_temp.check(public.read_marketvision_brand_searches(f.other_property,f.actor_id,v_id)->>'state'='not_found','saved search details cannot cross properties');
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.read_marketvision_brand_searches(f.property_id,f.actor_id,v_id)->>'state'='forbidden'and public.save_marketvision_brand_search(v_id,f.property_id,f.actor_id,v_payload)->>'state'='forbidden','saved reads and lost replies recheck current access');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
 alter table public.competitors disable trigger user;update public.competitors set name='Brand fixture competitor',version=1 where id=f.competitor_id;alter table public.competitors enable trigger user;
end$$;
create function pg_temp.reject_search_history()returns trigger language plpgsql as $$begin if new.action='market.brand_search.saved'then raise exception 'Synthetic history failure';end if;return new;end$$;
do $$declare f fixture;rid uuid:=gen_random_uuid();begin select *into f from fixture;
 create trigger reject_search_history before insert on public.shared_action_events for each row execute function pg_temp.reject_search_history();
 begin perform public.save_marketvision_brand_search(rid,f.property_id,f.actor_id,pg_temp.search_input('garden'));raise exception 'expected missing history';exception when others then if sqlerrm='expected missing history'then raise;end if;end;
 drop trigger reject_search_history on public.shared_action_events;
 perform pg_temp.check(not exists(select 1 from public.marketvision_brand_searches where id=rid)and not exists(select 1 from public.marketvision_decisions where id=rid),'failed actor recording rolls back the complete search snapshot');
end$$;
-- The immutable saved-result reader must retain every row beyond the REST limit.
do $$declare f fixture;seed public.marketvision_brand_searches;rid uuid:=gen_random_uuid();rows jsonb;r jsonb;offset_value integer:=0;seen integer:=0;i integer;cursor_id uuid;begin select *into f from fixture;select *into seed from public.marketvision_brand_searches where id=(select id from saved_search);
 select jsonb_agg((seed.results->0)||jsonb_build_object('ordinal',g.n)order by g.n)into rows from generate_series(1,1005)g(n);
 insert into public.marketvision_brand_searches(id,property_id,org_id,actor_id,input,input_hash,algorithm,terms,context,context_hash,results,result_hash,coverage)values(rid,seed.property_id,seed.org_id,seed.actor_id,seed.input,seed.input_hash,seed.algorithm,seed.terms,seed.context,seed.context_hash,rows,public.crm_configuration_hash(rows),seed.coverage||'{"matchedStatements":1005}');
 loop r:=public.read_marketvision_brand_searches(f.property_id,f.actor_id,rid,null,offset_value);seen:=seen+jsonb_array_length(r->'items');offset_value:=(r->>'nextOffset')::integer;exit when offset_value is null;end loop;
 perform pg_temp.check(seen=1005,'retained result paging includes every row beyond 1000');
 perform pg_temp.check(public.read_marketvision_brand_searches(f.property_id,f.actor_id,rid,null,1020)->>'state'='cursor_changed','out-of-snapshot result offset is rejected');
 for i in 1..22 loop perform public.save_marketvision_brand_search(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.search_input('garden'));end loop;
 seen:=0;loop r:=public.read_marketvision_brand_searches(f.property_id,f.actor_id,null,cursor_id);seen:=seen+jsonb_array_length(r->'items');cursor_id:=(r->>'nextCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(seen=29,'saved search history pages every original snapshot');
 perform pg_temp.check(public.read_marketvision_brand_searches(f.property_id,f.actor_id,null,gen_random_uuid())->>'state'='cursor_changed','foreign history cursors are rejected');
end$$;
select count(*)as passed_assertions from checks;
rollback;
