
begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,competitor_id uuid,source_id uuid,brief_id uuid,missing_id uuid);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision monitoring rollback fixture'from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision other monitoring rollback fixture'from fixture;
insert into public.competitors(id,property_id,name,property_type,website_url)select competitor_id,property_id,'Monitoring source competitor','multifamily','https://example.com/floorplans/'from fixture;
create temp table seen(id uuid primary key);
do $$declare f fixture;page jsonb;row jsonb;cursor uuid;count_rows integer:=0;b public.marketvision_briefs;begin select *into f from fixture;
 perform pg_temp.check(not has_function_privilege('authenticated','public.read_marketvision_monitoring(uuid,uuid,text,uuid,uuid)','execute')and not has_function_privilege('anon','public.marketvision_monitoring_rows(uuid,uuid)','execute'),'read RPCs stay service-only with their own access validation');
 perform pg_temp.check(public.read_marketvision_monitoring(f.property_id,gen_random_uuid())->>'state'='forbidden','current actor access required');
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id);perform pg_temp.check(page->'counts'->>'all'='0'and page->'runs'='[]','genuine empty property is explicit');
 perform public.begin_marketvision_source(f.source_id,f.property_id,f.actor_id,jsonb_build_object('competitorId',f.competitor_id,'expectedVersion',1,'source','website','reason','Saved monitoring fixture source'));
 perform public.begin_marketvision_brief(f.brief_id,f.property_id,f.actor_id,'{"windowDays":30,"reason":"Saved monitoring report"}');
 insert into public.shared_jobs(id,org_id,property_id,domain,subject_type,subject_id,lifecycle_status,payload)values(f.missing_id,'22222222-2222-2222-2222-222222222222',f.property_id,'marketvision.extraction','competitor',f.competitor_id::text,'succeeded','{"content":"SENSITIVE_PRIVATE_SOURCE"}');
 insert into public.shared_jobs(org_id,property_id,domain,subject_type,subject_id,lifecycle_status,payload,error_message)select '22222222-2222-2222-2222-222222222222',f.property_id,'marketvision.ingestion','observation_refresh',f.property_id::text,'succeeded','{"providerResponse":"SENSITIVE_PROVIDER_RECEIPT"}','SENSITIVE_ERROR_BODY'from generate_series(1,1005);
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id);perform pg_temp.check((page->'counts'->>'all')::integer=1008 and(page->'counts'->>'legacy')::integer=1005,'counts include the full property beyond REST row limits');
 perform pg_temp.check((page->'counts'->>'active')::integer=1 and(page->'counts'->>'attention')::integer=2,'qualified request state determines active and attention counts');
 perform pg_temp.check(jsonb_array_length(page->'runs')=20 and page->>'nextCursor'is not null,'bounded first page exposes a cursor');
 loop
  for row in select value from jsonb_array_elements(page->'runs')loop insert into seen values((row->>'id')::uuid);count_rows:=count_rows+1;end loop;
  cursor:=(page->>'nextCursor')::uuid;exit when cursor is null;page:=public.read_marketvision_monitoring(f.property_id,f.actor_id,'all',null,cursor);
 end loop;
 perform pg_temp.check(count_rows=1008 and(select count(*)=1008 from seen),'keyset pagination reaches every row once even with tied timestamps');
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id,'attention');perform pg_temp.check(jsonb_array_length(page->'runs')=2 and page->>'nextCursor'is null,'attention filter preserves complete global counts with a scoped page');
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id,'all',f.missing_id);perform pg_temp.check(page->'run'->>'request_state'='missing_record'and page->'run'->>'category'='attention','a successful ledger row without a qualified receipt is not successful work');
 perform pg_temp.check(public.read_marketvision_monitoring(f.other_property,f.actor_id,'all',f.source_id)->>'state'='not_found','direct links cannot cross properties');
 perform pg_temp.check(public.read_marketvision_monitoring(f.other_property,f.actor_id,'all',null,f.source_id)->>'state'='cursor_changed','cursors cannot cross properties');
 perform pg_temp.check(public.read_marketvision_monitoring(f.property_id,f.actor_id,'complete',null,f.source_id)->>'state'='cursor_changed','cursor from another filter requires a fresh view');
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id,'all',f.source_id);perform pg_temp.check(page->'run'->>'kind'='source'and(page->'run'->>'competitor_id')::uuid=f.competitor_id,'source recovery targets the original competitor and request');
 perform pg_temp.check(not(page->'run'?'claim_token')and not(page->'run'?'input')and not(page->'run'?'receipt')and not(page->'run'?'payload'),'monitoring does not expose private raw sources or claim tokens');
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id,'legacy');perform pg_temp.check(page::text not like '%SENSITIVE%'and page->'runs'->0->>'category'='legacy','earlier job states retain labels without returning raw payloads or treating effects as verified');
 select *into b from public.marketvision_briefs where id=f.brief_id;
 perform public.complete_marketvision_brief(f.brief_id,f.property_id,f.actor_id,b.source_hash,jsonb_build_object('schemaVersion','market-brief-v2','reportId',b.id,'propertyId',f.property_id,'sourceHash',b.source_hash,'snapshotAt',b.source_snapshot->>'snapshotAt','analysis','{}'::jsonb,'recommendations','[]'::jsonb));
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id,'complete');perform pg_temp.check(page->'counts'->>'complete'='1'and(page->'runs'->0->>'brief_id')::uuid=f.brief_id,'completed saved report is separately counted and directly recoverable');
 perform public.control_marketvision_source(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('sourceId',f.source_id,'expectedVersion',1,'action','stop','reason','Stop isolated queued work'));
 page:=public.read_marketvision_monitoring(f.property_id,f.actor_id,'closed');perform pg_temp.check(page->'counts'->>'closed'='1'and page->'counts'->>'active'='0'and page->'runs'->0->>'request_state'='stopped','stopped requests retain their own closed state');
 perform pg_temp.check(jsonb_array_length(page->'workers')=2 and not(page->'workers'->0?'summary')and not(page->'workers'->0?'error'),'shared worker timestamps exclude other-property outcomes and provider errors');
 begin perform public.read_marketvision_monitoring(f.property_id,f.actor_id,'anything');raise exception 'MISSING invalid filter';exception when others then if sqlerrm like 'MISSING%'then raise;end if;perform pg_temp.check(sqlerrm='Choose a valid saved-work view','unknown filters cannot broaden queries');end;
end$$;
select count(*)as passed_assertions from checks;
rollback;
