begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,competitor_id uuid,source_id uuid,extraction_id uuid,input jsonb,receipt jsonb,preview jsonb);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,'{"pricingBasis":"monthly_rent_usd","units":[{"unit_type":"A1","bedrooms":1,"bathrooms":null,"sqft_min":null,"sqft_max":null,"rent_min":1200,"rent_max":null,"deposit":null,"available_count":null,"move_in_specials":null,"evidence":[{"field":"unit_type","quote":"A1"},{"field":"bedrooms","quote":"1 bedroom"},{"field":"rent_min","quote":"$1200 monthly rent in USD"}]}],"notes":null}');
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision acquisition rollback fixture'from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision other acquisition rollback fixture'from fixture;
insert into public.competitors(id,property_id,name,property_type,website_url)select competitor_id,property_id,'Acquisition fixture competitor','multifamily','https://example.com/floorplans/'from fixture;
insert into public.competitor_units(competitor_id,unit_type,bedrooms,rent_min)select competitor_id,'Unselected type',2,1500 from fixture;
update fixture set input=jsonb_build_object('competitorId',competitor_id,'expectedVersion',1,'source','website','reason','Reviewed the saved public pricing source');
update fixture set receipt=jsonb_build_object('status','received','transport','public_http_v1','parserVersion','public-html-v1','requestedUrl','https://example.com/floorplans/','finalUrl','https://example.com/current-plans/','statusCode',200,'contentType','text/html','fetchedAt',clock_timestamp(),'body','<p>A1 has 1 bedroom. Starting at $1200 monthly rent in USD. Contact the property to confirm availability.</p>','bodyHash',encode(sha256(convert_to('<p>A1 has 1 bedroom. Starting at $1200 monthly rent in USD. Contact the property to confirm availability.</p>','UTF8')),'hex'),'text','A1 has 1 bedroom. Starting at $1200 monthly rent in USD. Contact the property to confirm availability.','textTruncated',false);
do $$declare f fixture;r jsonb;claim jsonb;source_input jsonb;model jsonb;model_claim jsonb;model_receipt jsonb;payload jsonb;begin select * into f from fixture;
 perform pg_temp.check(not has_function_privilege('authenticated','public.begin_marketvision_source(uuid,uuid,uuid,jsonb)','execute')and not has_table_privilege('authenticated','public.marketvision_source_requests','select'),'source receipts and write claims stay private');
 perform pg_temp.check(public.begin_marketvision_source(f.source_id,f.property_id,gen_random_uuid(),f.input)->>'state'='forbidden','source requests require current property access');
 perform pg_temp.check(public.begin_marketvision_source(f.source_id,f.other_property,f.actor_id,f.input)->>'state'='not_found','source request cannot cross properties');
 perform pg_temp.check(public.begin_marketvision_source(f.source_id,f.property_id,f.actor_id,f.input)->>'state'='queued','source URL and request are retained before fetching');
 perform pg_temp.check((select claim_token is null and source_snapshot->>'sourceUrl'='https://example.com/floorplans/'from public.marketvision_source_requests where id=f.source_id),'saved requests do not pretend a fetch started');
 perform pg_temp.check(public.begin_marketvision_source(f.source_id,f.property_id,f.actor_id,f.input)->>'state'='queued'and(select count(*)=1 from public.shared_jobs where id=f.source_id),'lost source acknowledgements recover the original job');
 perform pg_temp.check(public.begin_marketvision_source(f.source_id,f.property_id,f.actor_id,f.input||'{"reason":"Different request"}')->>'state'='request_conflict','request IDs cannot replace source intent');
 perform pg_temp.check(public.begin_marketvision_source(gen_random_uuid(),f.property_id,f.actor_id,f.input)->>'state'='busy','one open fetch per competitor source avoids duplicate dispatch');
 perform pg_temp.check((select shared_job_ref=f.source_id from public.shared_action_events where id=f.source_id),'operator request links its retained job context');
 claim:=public.claim_marketvision_source(f.source_id);
 perform pg_temp.check(claim->>'state'='fetch_once'and public.claim_marketvision_source(f.source_id)->>'state'='running','one worker claim permits one fetch');
 perform pg_temp.check((select actor_id is null and service_principal='marketvision.source'and before_state->>'state'='queued'from public.shared_action_events where shared_job_ref=f.source_id and action='market.source.started'),'actual nonhuman fetching principal is recorded');
 perform pg_temp.check(public.record_marketvision_source_result(f.source_id,gen_random_uuid(),f.receipt)->>'state'='claim_mismatch','wrong receipt claims cannot alter source state');
 begin perform public.record_marketvision_source_result(f.source_id,(claim->>'claimToken')::uuid,f.receipt||'{"bodyHash":"wrong"}');raise exception 'expected invalid source hash';exception when others then if sqlerrm='expected invalid source hash'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.market_source_captures where id=f.source_id),'invalid receipts cannot fabricate source lineage');
 perform pg_temp.check(public.record_marketvision_source_result(f.source_id,(claim->>'claimToken')::uuid,f.receipt)->>'requestState'='received','page receipt and source capture persist together');
 perform pg_temp.check(public.record_marketvision_source_result(f.source_id,(claim->>'claimToken')::uuid,f.receipt)->>'state'='replayed'and(select count(*)=1 from public.market_source_captures where id=f.source_id),'lost receipt acknowledgements do not duplicate captures');
 perform pg_temp.check(public.record_marketvision_source_result(f.source_id,(claim->>'claimToken')::uuid,f.receipt||'{"text":"Changed source evidence"}')->>'state'='result_conflict','late results cannot replace the retained page');
 perform pg_temp.check((select count(*)=1 from public.competitor_units where competitor_id=f.competitor_id)and(select last_scraped_at is null and version=1 from public.competitors where id=f.competitor_id),'fetching a page does not change business values or legacy price freshness');
 perform pg_temp.check((select source_type='website'and source_url=f.receipt->>'finalUrl'and captured_at=(f.receipt->>'fetchedAt')::timestamptz and effective_at is null and content_hash=f.receipt->>'bodyHash'from public.market_source_captures where id=f.source_id),'source provenance keeps final URL, actual retrieval time, hash and unknown price date');
 r:=public.read_marketvision_sources(f.property_id,f.actor_id,f.competitor_id,f.source_id);
 perform pg_temp.check(not(r->'request'?'claim_token')and not(r->'request'->'receipt'?'body')and r->'request'->'receipt'->>'text'=f.receipt->>'text','source reads show review text without raw HTML or worker claims');
 perform pg_temp.check(public.read_marketvision_sources(f.other_property,f.actor_id,f.competitor_id,f.source_id)->>'state'='not_found','private source receipt reads are property scoped');
 begin update public.market_source_captures set content_hash='changed'where id=f.source_id;raise exception 'expected immutable capture';exception when others then if sqlerrm='expected immutable capture'then raise;end if;end;
 perform pg_temp.check((select content_hash=f.receipt->>'bodyHash'from public.market_source_captures where id=f.source_id),'retained source captures cannot be relabeled');
 source_input:=jsonb_build_object('competitorId',f.competitor_id,'sourceVersion',1,'sourceRequestId',f.source_id,'confirmedSourceScope',true,'content',f.receipt->>'text','sourceUrl',f.receipt->>'finalUrl','effectiveAt',null,'reason','Reviewed retained page for pricing candidates');
 model:=jsonb_build_object('model','gpt-4o-mini','promptVersion','pricing-v2','source',jsonb_build_object('content',f.receipt->>'text','propertyType','multifamily'),'systemPrompt','Isolated extraction contract','userPrompt',f.receipt->>'text','maxTokens',8000);
 begin perform public.begin_marketvision_extraction(f.extraction_id,f.property_id,f.actor_id,source_input||'{"content":"Spoofed source text that is not the actual retained page evidence at all."}',model);raise exception 'expected exact retained source';exception when others then if sqlerrm='expected exact retained source'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.marketvision_extraction_requests where id=f.extraction_id),'operator text cannot claim fetched provenance');
 perform pg_temp.check(public.begin_marketvision_extraction(f.extraction_id,f.property_id,f.actor_id,source_input,model)->>'state'='queued','exact retained source can request separate reviewed extraction');
 model_claim:=public.claim_marketvision_extraction(f.extraction_id);model_receipt:=jsonb_build_object('status','received','content',f.preview::text,'finishReason','stop');perform public.record_marketvision_extraction_result(f.extraction_id,(model_claim->>'claimToken')::uuid,model_receipt);perform public.prepare_marketvision_extraction_preview(f.extraction_id,public.crm_configuration_hash(model_receipt),f.preview);
 select jsonb_build_object('extractionId',id,'expectedVersion',x.version,'previewHash',x.preview_hash,'confirmedMonthlyRentUsd',true,'selection',jsonb_build_array(jsonb_build_object('sourceIndex',0,'values',(f.preview->'units'->0)-'evidence')),'reason','Reviewed exact page-backed candidate values')into payload from public.marketvision_extraction_requests x where id=f.extraction_id;
 r:=public.apply_marketvision_extraction(gen_random_uuid(),f.property_id,f.actor_id,payload);
 perform pg_temp.check(r->>'state'='saved'and r->>'captureId'=f.source_id::text and r->'sourceFetched'='true'::jsonb,'approved extraction reuses exact fetched source capture');
 perform pg_temp.check((select count(*)=1 from public.market_source_captures where property_id=f.property_id)and(select capture_id=f.source_id and rent_min=1200 from public.competitor_units where competitor_id=f.competitor_id and unit_type='A1'),'reviewed prices cannot create a second fake manual capture');
 perform pg_temp.check((select source='reviewed_page_extraction'and capture_id=f.source_id from public.competitor_price_history where capture_id=f.source_id),'price history identifies reviewed fetched-page provenance');
 r:=public.read_marketvision_extractions(f.property_id,f.actor_id,f.competitor_id,f.extraction_id);
 perform pg_temp.check(r->'request'->'sourceProvenance'->>'captureId'=f.source_id::text and not(r->'request'?'claim_token'),'extraction review exposes source identity and hides worker claims');
end$$;
-- Stop and uncertainty retain actual outcomes without usable source application or repeated fetches.
do $$declare f fixture;rid uuid:=gen_random_uuid();claim jsonb;version integer;receipt jsonb;begin select * into f from fixture;
 perform public.begin_marketvision_source(rid,f.property_id,f.actor_id,f.input);claim:=public.claim_marketvision_source(rid);
 select x.version into version from public.marketvision_source_requests x where id=rid;
 perform public.control_marketvision_source(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('sourceId',rid,'expectedVersion',version,'action','stop','reason','Stop source use during isolated fetch'));
 perform public.record_marketvision_source_result(rid,(claim->>'claimToken')::uuid,f.receipt);
 perform pg_temp.check((select state='stopped'and raw_result=f.receipt and capture_id is null from public.marketvision_source_requests where id=rid)and not exists(select 1 from public.market_source_captures where id=rid),'stopped requests retain late pages without creating usable captures');
 perform pg_temp.check(not public.marketvision_capture_current(rid,f.property_id,f.competitor_id),'stopped source cannot back a pricing extraction');
 rid:=gen_random_uuid();perform public.begin_marketvision_source(rid,f.property_id,f.actor_id,f.input);claim:=public.claim_marketvision_source(rid);perform public.record_marketvision_source_result(rid,(claim->>'claimToken')::uuid,'{"status":"uncertain","errorCode":"fetch_unconfirmed"}');
 perform pg_temp.check(public.claim_marketvision_source(rid)->>'state'='held','uncertain source fetch is not dispatched again');
 rid:=gen_random_uuid();perform public.begin_marketvision_source(rid,f.property_id,f.actor_id,f.input);update public.competitors set website_url='https://example.com/changed-source/'where id=f.competitor_id;
 perform pg_temp.check(public.claim_marketvision_source(rid)->>'state'='held','source changes hold queued work before any fetch');
 perform pg_temp.check(not public.marketvision_capture_current(f.source_id,f.property_id,f.competitor_id),'changed competitor sources cannot reuse older page provenance');
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.begin_marketvision_source(f.source_id,f.property_id,f.actor_id,f.input)->>'state'='forbidden'and public.read_marketvision_sources(f.property_id,f.actor_id,f.competitor_id,f.source_id)->>'state'='forbidden','private page reads and request replays recheck current access');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
end$$;
-- Captured provenance cannot be restored through a rebase after the source changes.
do $$declare f fixture;rid uuid:=gen_random_uuid();eid uuid:=gen_random_uuid();claim jsonb;receipt jsonb;source_input jsonb;model jsonb;payload jsonb;r jsonb;cursor_id uuid;i integer;begin select * into f from fixture;
 perform public.begin_marketvision_source(rid,f.property_id,f.actor_id,f.input||'{"expectedVersion":2}');claim:=public.claim_marketvision_source(rid);receipt:=f.receipt||jsonb_build_object('requestedUrl','https://example.com/changed-source/','fetchedAt',clock_timestamp());perform public.record_marketvision_source_result(rid,(claim->>'claimToken')::uuid,receipt);
 source_input:=jsonb_build_object('competitorId',f.competitor_id,'sourceVersion',2,'sourceRequestId',rid,'confirmedSourceScope',true,'content',receipt->>'text','sourceUrl',receipt->>'finalUrl','effectiveAt',null,'reason','Review retained current source for stale comparison test');
 model:=jsonb_build_object('model','gpt-4o-mini','promptVersion','pricing-v2','source',jsonb_build_object('content',receipt->>'text','propertyType','multifamily'),'systemPrompt','Isolated source comparison contract','userPrompt',receipt->>'text','maxTokens',8000);
 perform public.begin_marketvision_extraction(eid,f.property_id,f.actor_id,source_input,model);claim:=public.claim_marketvision_extraction(eid);receipt:=jsonb_build_object('status','received','content',f.preview::text,'finishReason','stop');perform public.record_marketvision_extraction_result(eid,(claim->>'claimToken')::uuid,receipt);perform public.prepare_marketvision_extraction_preview(eid,public.crm_configuration_hash(receipt),f.preview);
 select jsonb_build_object('extractionId',id,'expectedVersion',version,'previewHash',preview_hash,'confirmedMonthlyRentUsd',true,'selection',jsonb_build_array(jsonb_build_object('sourceIndex',0,'values',(f.preview->'units'->0)-'evidence')),'reason','Review stale fetched-page application')into payload from public.marketvision_extraction_requests where id=eid;
 update public.competitors set website_url='https://example.com/new-source/'where id=f.competitor_id;
 perform pg_temp.check(public.apply_marketvision_extraction(gen_random_uuid(),f.property_id,f.actor_id,payload)->>'state'='stale_source','a source change blocks application of an earlier fetched-page preview');
 perform pg_temp.check(public.control_marketvision_extraction(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('action','rebase','extractionId',eid,'expectedVersion',(payload->>'expectedVersion')::integer,'reason','Attempt to reuse an obsolete source'))->>'state'='source_unavailable','rebase cannot relabel an older page as the current source');
 perform pg_temp.check((select state='preview_ready'from public.marketvision_extraction_requests where id=eid)and not exists(select 1 from public.competitor_price_history where capture_id=rid),'a rejected source rebase retains the review and writes no price evidence');
 rid:=gen_random_uuid();perform public.begin_marketvision_source(rid,f.property_id,f.actor_id,f.input||'{"expectedVersion":3}');claim:=public.claim_marketvision_source(rid);
 update public.profiles set org_id=null where id=f.actor_id;
 receipt:=f.receipt||jsonb_build_object('requestedUrl','https://example.com/new-source/','fetchedAt',clock_timestamp());perform public.record_marketvision_source_result(rid,(claim->>'claimToken')::uuid,receipt);
 perform pg_temp.check((select state='held'and error_code='source_or_access_changed'and raw_result=receipt and capture_id is null from public.marketvision_source_requests where id=rid),'lost access after dispatch retains the receipt without a usable capture');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
 for i in 1..22 loop
  rid:=gen_random_uuid();perform public.begin_marketvision_source(rid,f.property_id,f.actor_id,f.input||jsonb_build_object('expectedVersion',3,'reason','Saved source history fixture '||i::text));
  perform public.control_marketvision_source(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('sourceId',rid,'expectedVersion',1,'action','stop','reason','Close isolated history source'));
 end loop;
 r:=public.read_marketvision_sources(f.property_id,f.actor_id,f.competitor_id);cursor_id:=(r->>'nextCursor')::uuid;
 perform pg_temp.check(jsonb_array_length(r->'requests')=20 and cursor_id is not null,'source history continues beyond twenty saved requests');
 perform pg_temp.check(jsonb_array_length(public.read_marketvision_sources(f.property_id,f.actor_id,f.competitor_id,null,cursor_id)->'requests')=8,'history paging retains older source outcomes');
 perform pg_temp.check(public.read_marketvision_sources(f.property_id,f.actor_id,f.competitor_id,null,gen_random_uuid())->>'state'='cursor_changed','history rejects unrelated source cursors');
end$$;
select count(*)as passed_assertions from checks;
rollback;
