begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,competitor_id uuid);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid());
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision listing rollback fixture'from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision other listing rollback fixture'from fixture;
insert into public.competitors(id,property_id,name,property_type,ils_listings)select competitor_id,property_id,'Listing fixture competitor','multifamily','{"rent_com":"https://www.rent.com/retained-source"}'from fixture;
insert into public.scrape_config(property_id,is_enabled,scrape_frequency)select property_id,false,'manual'from fixture;
do $$declare f fixture;command uuid:=gen_random_uuid();payload jsonb;r jsonb;old_state jsonb;bad text;begin select * into f from fixture;
 payload:=jsonb_build_object('action','save','competitorId',f.competitor_id,'expectedVersion',1,'url','https://www.apartments.com/reviewed-community/abc/','reason','Reviewed exact community listing');
 perform pg_temp.check(not has_function_privilege('authenticated','public.save_marketvision_listing(uuid,uuid,uuid,jsonb)','execute'),'clients cannot forge listing decisions');
 perform pg_temp.check(public.save_marketvision_listing(command,f.property_id,gen_random_uuid(),payload)->>'state'='forbidden','listing changes require current property access');
 perform pg_temp.check(public.save_marketvision_listing(command,f.other_property,f.actor_id,payload)->>'state'='not_found','listing changes cannot cross properties');
 r:=public.save_marketvision_listing(command,f.property_id,f.actor_id,payload);perform pg_temp.check(r->>'state'='saved'and r->>'version'='2'and r->'externalExecutionStarted'='false'::jsonb,'reviewed link saves without provider execution');
 perform pg_temp.check((select ils_listings->>'rent_com'='https://www.rent.com/retained-source'and ils_listings->>'apartments_com'=payload->>'url'and last_scraped_at is null from public.competitors where id=f.competitor_id),'other sources and unknown freshness are preserved');
 perform pg_temp.check((select not is_enabled and scrape_frequency='manual'from public.scrape_config where property_id=f.property_id)and not exists(select 1 from public.shared_jobs where property_id=f.property_id)and not exists(select 1 from public.market_source_captures where property_id=f.property_id),'saving a link does not enable monitoring or fabricate capture jobs');
 perform pg_temp.check(public.save_marketvision_listing(command,f.property_id,f.actor_id,payload)->>'state'='replayed'and(select count(*)=1 from public.shared_action_events where id=command),'lost listing responses recover once');
 perform pg_temp.check(public.save_marketvision_listing(command,f.property_id,f.actor_id,payload||'{"url":"https://www.apartments.com/changed/source/"}')->>'state'='request_conflict','a reused request identity cannot change the source');
 perform pg_temp.check((select actor_id=f.actor_id and service_principal is null and evidence='server_confirmed'and request::text not like '%apartments.com%'from public.shared_action_events where id=command),'shared summary identifies the actor without copying raw source URLs');
 perform pg_temp.check((select before_state->'apartments_com'='null'::jsonb and after_state->>'apartments_com'=payload->>'url'from public.marketvision_decisions where id=command),'private evidence retains source before and after');
 perform pg_temp.check(public.save_marketvision_listing(gen_random_uuid(),f.property_id,f.actor_id,payload)->>'state'='stale_competitor','an outdated source form cannot overwrite a current listing');
 foreach bad in array array['https://evil.com/apartments.com/abc','https://apartments.com.evil.com/abc','https://user@apartments.com/abc','https://apartments.com/','http://127.0.0.1/abc','https://apartments.com/abc def']loop
  begin perform public.save_marketvision_listing(gen_random_uuid(),f.property_id,f.actor_id,payload||jsonb_build_object('url',bad,'expectedVersion',2));raise exception 'expected invalid source';exception when others then if sqlerrm='expected invalid source'then raise;end if;end;
 end loop;
 perform pg_temp.check((select version=2 from public.competitors where id=f.competitor_id),'invalid sources leave saved values unchanged');
 r:=public.save_marketvision_listing(gen_random_uuid(),f.property_id,f.actor_id,(payload-'url')||'{"action":"remove","expectedVersion":2}');
 perform pg_temp.check(r->>'state'='saved'and(select ils_listings='{"rent_com":"https://www.rent.com/retained-source"}'::jsonb from public.competitors where id=f.competitor_id),'removal affects only the reviewed listing');
 perform pg_temp.check((select count(*)=2 from public.marketvision_decisions where property_id=f.property_id),'removing a source preserves earlier decisions');
 update public.competitors set is_active=false where id=f.competitor_id;
 perform pg_temp.check(public.save_marketvision_listing(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"expectedVersion":4}')->>'state'='competitor_archived','archived competitor sources cannot change');
 update public.competitors set is_active=true where id=f.competitor_id;
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.save_marketvision_listing(command,f.property_id,f.actor_id,payload)->>'state'='forbidden','replays recheck current access');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
end$$;
-- A failed action append must roll back the listing and private decision as well.
create function pg_temp.reject_listing_event()returns trigger language plpgsql as $$begin if new.action='market.listing.saved'then raise exception 'isolated listing action failure';end if;return new;end$$;
create trigger test_listing_event_failure before insert on public.shared_action_events for each row execute function pg_temp.reject_listing_event();
do $$declare f fixture;command uuid:=gen_random_uuid();before_state jsonb;begin select * into f from fixture;select to_jsonb(c)into before_state from public.competitors c where id=f.competitor_id;
 begin perform public.save_marketvision_listing(command,f.property_id,f.actor_id,jsonb_build_object('action','save','competitorId',f.competitor_id,'expectedVersion',5,'url','https://www.apartments.com/atomic-source/abc/','reason','Atomic source decision qualification'));raise exception 'expected action failure';exception when others then if sqlerrm='expected action failure'then raise;end if;end;
 perform pg_temp.check((select to_jsonb(c)=before_state from public.competitors c where id=f.competitor_id)and not exists(select 1 from public.marketvision_decisions where id=command),'action failure rolls back listing and private evidence');
end$$;
select count(*)as passed_assertions from checks;
rollback;
