begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create function pg_temp.reject_brand_history()returns trigger language plpgsql as $$begin if new.action='market.brand.published'then raise exception 'Synthetic history failure';end if;return new;end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,competitor_id uuid,source_id uuid,request_id uuid,input jsonb,model jsonb,preview jsonb);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null,'{"claims":[{"category":"positioning","kind":"source_claim","statement":"The website describes garden living.","quote":"Garden living beside the park"},{"category":"voice","kind":"interpretation","statement":"Inviting language.","quote":"Welcome home"}],"notes":"One captured page only"}');
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision brand rollback fixture'from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'MarketVision other brand rollback fixture'from fixture;
insert into public.competitors(id,property_id,name,property_type,website_url)select competitor_id,property_id,'Brand fixture competitor','multifamily','https://example.com/brand/'from fixture;
do $$declare f fixture;claim jsonb;body text:='<p>Garden living beside the park. Welcome home to our community. Ask the team about current availability and offers.</p>';content text:='Garden living beside the park. Welcome home to our community. Ask the team about current availability and offers.';begin select *into f from fixture;
 perform public.begin_marketvision_source(f.source_id,f.property_id,f.actor_id,jsonb_build_object('competitorId',f.competitor_id,'expectedVersion',1,'source','website','reason','Review isolated brand source'));
 claim:=public.claim_marketvision_source(f.source_id);
 perform public.record_marketvision_source_result(f.source_id,(claim->>'claimToken')::uuid,jsonb_build_object('status','received','transport','public_http_v1','parserVersion','public-html-v1','requestedUrl','https://example.com/brand/','finalUrl','https://example.com/brand/','statusCode',200,'contentType','text/html','fetchedAt',clock_timestamp(),'body',body,'bodyHash',encode(sha256(convert_to(body,'UTF8')),'hex'),'text',content,'textTruncated',false));
 update fixture set input=jsonb_build_object('competitorId',f.competitor_id,'sourceId',f.source_id,'sourceVersion',(select version from public.marketvision_source_requests where id=f.source_id),'confirmedSourceScope',true,'reason','Review exact page for brand claims'),model=jsonb_build_object('model','gpt-4o-mini','promptVersion','brand-evidence-v1','maxTokens',8000,'systemPrompt','Isolated model recipe','userPrompt',content,'source',jsonb_build_object('content',content,'sourceUrl','https://example.com/brand/','competitorName','Brand fixture competitor'));
end$$;
create function pg_temp.prepare_brand(rid uuid)returns void language plpgsql as $$declare f fixture;claim jsonb;receipt jsonb;begin select *into f from fixture;perform public.begin_marketvision_brand(rid,f.property_id,f.actor_id,f.input,f.model);claim:=public.claim_marketvision_brand(rid);receipt:=jsonb_build_object('status','received','content',f.preview::text,'finishReason','stop','usage',jsonb_build_object('inputTokens',100,'outputTokens',20));perform public.record_marketvision_brand_result(rid,(claim->>'claimToken')::uuid,receipt);perform public.prepare_marketvision_brand_preview(rid,public.crm_configuration_hash(receipt),f.preview);end$$;
create function pg_temp.review_input(rid uuid,previous uuid)returns jsonb language sql as $$select jsonb_build_object('brandRequestId',r.id,'expectedVersion',r.version,'previewHash',r.preview_hash,'expectedReviewId',previous,'action','publish','acknowledgeInterpretation',true,'acknowledgeReplacement',true,'selection',jsonb_build_array(jsonb_build_object('sourceIndex',0,'action','include','claim',r.preview->'claims'->0),jsonb_build_object('sourceIndex',1,'action','skip')),'reason','Review quoted statement and skip interpretation')from public.marketvision_brand_requests r where r.id=rid$$;
do $$declare f fixture;r jsonb;claim jsonb;receipt jsonb;payload jsonb;decision uuid:=gen_random_uuid();rev2 uuid:=gen_random_uuid();withdraw uuid:=gen_random_uuid();begin select *into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.marketvision_brand_requests','select')and not has_table_privilege('anon','public.marketvision_brand_reviews','insert')and not has_function_privilege('authenticated','public.begin_marketvision_brand(uuid,uuid,uuid,jsonb,jsonb)','execute'),'raw brand input and write functions stay private');
 perform pg_temp.check(public.begin_marketvision_brand(f.request_id,f.property_id,gen_random_uuid(),f.input,f.model)->>'state'='forbidden','current actor access required');
 perform pg_temp.check(public.begin_marketvision_brand(f.request_id,f.other_property,f.actor_id,f.input,f.model)->>'state'='not_found','wrong property cannot request this competitor');
 perform pg_temp.check(public.begin_marketvision_brand(f.request_id,f.property_id,f.actor_id,f.input||'{"sourceVersion":99}',f.model)->>'state'='stale_source','exact retained source version is required');
 r:=public.begin_marketvision_brand(f.request_id,f.property_id,f.actor_id,f.input,f.model);perform pg_temp.check(r->>'state'='queued','complete source and recipe saved before invocation');
 perform pg_temp.check(public.begin_marketvision_brand(f.request_id,f.property_id,f.actor_id,f.input,'{}')->>'state'='queued','lost creation response replays original recipe');
 perform pg_temp.check(public.begin_marketvision_brand(f.request_id,f.property_id,f.actor_id,f.input||'{"reason":"different intent"}',f.model)->>'state'='request_conflict','same identity cannot replace source intent');
 perform pg_temp.check(public.begin_marketvision_brand(gen_random_uuid(),f.property_id,f.actor_id,f.input,f.model)->>'state'='busy','one active request per competitor');
 claim:=public.claim_marketvision_brand(f.request_id);perform pg_temp.check(claim->>'state'='invoke_once'and public.claim_marketvision_brand(f.request_id)->>'state'='running','single invocation token prevents repeated model execution');
 perform pg_temp.check((select actor_id is null and service_principal='marketvision.brand'from public.shared_action_events where shared_job_ref=f.request_id and action='market.brand.started'),'actual service principal retained');
 receipt:=jsonb_build_object('status','received','content',f.preview::text,'finishReason','stop','usage',jsonb_build_object('inputTokens',100,'outputTokens',20));
 perform pg_temp.check(public.record_marketvision_brand_result(f.request_id,gen_random_uuid(),receipt)->>'state'='claim_mismatch','wrong worker cannot store model result');
 perform pg_temp.check(public.record_marketvision_brand_result(f.request_id,(claim->>'claimToken')::uuid,receipt)->>'requestState'='result_ready','raw receipt saved before validation');
 perform pg_temp.check(public.record_marketvision_brand_result(f.request_id,(claim->>'claimToken')::uuid,receipt)->>'state'='replayed','exact receipt replay is idempotent');
 perform pg_temp.check(public.record_marketvision_brand_result(f.request_id,(claim->>'claimToken')::uuid,receipt||'{"content":"different"}')->>'state'='result_conflict','receipt cannot be replaced');
 perform pg_temp.check(public.prepare_marketvision_brand_preview(f.request_id,public.crm_configuration_hash(receipt),f.preview)->>'requestState'='preview_ready','complete quoted preview saved');
 r:=public.read_marketvision_brand(f.property_id,f.actor_id,'requests',f.competitor_id,f.request_id);
 perform pg_temp.check(r->'request'->>'content'=f.model->'source'->>'content'and not(r->'request'?'claim_token')and not(r->'request'?'raw_result')and not(r->'request'?'model_input'),'detail exposes review evidence without raw private transport');
 perform pg_temp.check((select count(*)=0 from public.marketvision_current_brand_evidence(f.property_id,'22222222-2222-2222-2222-222222222222')),'unreviewed generation never enters qualified context');
 payload:=pg_temp.review_input(f.request_id,null);
 begin perform public.review_marketvision_brand(decision,f.property_id,f.actor_id,jsonb_set(payload,'{selection,0,claim,quote}','"Fabricated quotation"'));raise exception 'expected quote failure';exception when others then if sqlerrm='expected quote failure'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.marketvision_brand_reviews where id=decision)and not exists(select 1 from public.marketvision_decisions where id=decision),'unsupported quote produces no partial approval history');
 begin perform public.review_marketvision_brand(decision,f.property_id,f.actor_id,jsonb_set(payload,'{selection}',jsonb_build_array(payload->'selection'->0)));raise exception 'expected incomplete selection';exception when others then if sqlerrm='expected incomplete selection'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.marketvision_brand_reviews where id=decision),'every generated candidate needs include or skip decision');
 create trigger reject_brand_history before insert on public.shared_action_events for each row execute function pg_temp.reject_brand_history();
 begin perform public.review_marketvision_brand(decision,f.property_id,f.actor_id,payload);raise exception 'expected history failure';exception when others then if sqlerrm='expected history failure'then raise;end if;end;
 drop trigger reject_brand_history on public.shared_action_events;
 perform pg_temp.check(not exists(select 1 from public.marketvision_brand_reviews where id=decision)and not exists(select 1 from public.marketvision_decisions where id=decision)and(select state='preview_ready'from public.marketvision_brand_requests where id=f.request_id),'failed action history rolls back the review, private decision and completion together');
 r:=public.review_marketvision_brand(decision,f.property_id,f.actor_id,payload);perform pg_temp.check(r->>'state'='saved'and r->>'statementCount'='1'and r->'externalPublication'='false'::jsonb,'review saves selected source statements without downstream publication');
 perform pg_temp.check(public.review_marketvision_brand(decision,f.property_id,f.actor_id,payload)->>'state'='replayed'and(select count(*)=1 from public.marketvision_brand_reviews where request_id=f.request_id),'lost approval response cannot create another revision');
 perform pg_temp.check((select claims->0->>'quote'='Garden living beside the park'and observed_at=(select(raw_result->>'fetchedAt')::timestamptz from public.marketvision_source_requests where id=f.source_id)from public.marketvision_current_brand_evidence(f.property_id,'22222222-2222-2222-2222-222222222222')),'qualified source retains exact quote and actual capture date');
 perform pg_temp.check((select preview=f.preview and raw_result=receipt from public.marketvision_brand_requests where id=f.request_id),'original generated result survives operator selection');
 payload:=pg_temp.review_input(f.request_id,decision);payload:=jsonb_set(payload,'{selection,0,claim,statement}','"The captured page promotes garden living."');
 perform pg_temp.check(public.review_marketvision_brand(rev2,f.property_id,f.actor_id,payload||jsonb_build_object('expectedReviewId',null))->>'state'='stale_review','review replacement requires exact predecessor');
 r:=public.review_marketvision_brand(rev2,f.property_id,f.actor_id,payload);perform pg_temp.check(r->>'state'='saved'and(select count(*)=2 from public.marketvision_brand_reviews where request_id=f.request_id),'corrections append a new revision without model call');
 perform pg_temp.check((select previous_review_id=decision from public.marketvision_brand_reviews where id=rev2),'review corrections retain predecessor identity');
 payload:=jsonb_build_object('brandRequestId',f.request_id,'expectedVersion',(select version from public.marketvision_brand_requests where id=f.request_id),'expectedReviewId',rev2,'action','withdraw','reason','Withdraw reviewed evidence pending another source');
 perform pg_temp.check(public.review_marketvision_brand(withdraw,f.property_id,f.actor_id,payload)->>'state'='saved','current evidence can be withdrawn explicitly');
 perform pg_temp.check((select count(*)=0 from public.marketvision_current_brand_evidence(f.property_id,'22222222-2222-2222-2222-222222222222')),'withdrawal excludes all prior approvals rather than falling back');
 perform pg_temp.check((select count(*)=3 from public.marketvision_brand_reviews where request_id=f.request_id),'withdrawal retains full previous review history');
 perform public.review_marketvision_brand(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.review_input(f.request_id,withdraw));
 update public.competitors set name='Changed source baseline'where id=f.competitor_id;
 perform pg_temp.check((select count(*)=0 from public.marketvision_current_brand_evidence(f.property_id,'22222222-2222-2222-2222-222222222222')),'changed competitor baseline excludes previously approved evidence');
 perform pg_temp.check(public.review_marketvision_brand(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.review_input(f.request_id,(select id from public.marketvision_brand_reviews where competitor_id=f.competitor_id order by review_sequence desc limit 1)))->>'state'='source_unavailable','outdated page cannot be reapproved');
 perform pg_temp.check(public.read_marketvision_brand(f.other_property,f.actor_id,'requests',f.competitor_id,f.request_id)->>'state'='not_found','saved detail remains property scoped');
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.read_marketvision_brand(f.property_id,f.actor_id)->>'state'='forbidden'and public.begin_marketvision_brand(f.request_id,f.property_id,f.actor_id,f.input,f.model)->>'state'='forbidden','reads and lost replies recheck current access');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
 -- Restore a baseline solely inside this rollback fixture for subsequent execution tests.
 alter table public.competitors disable trigger user;update public.competitors set name='Brand fixture competitor',version=1 where id=f.competitor_id;alter table public.competitors enable trigger user;
end$$;
do $$declare f fixture;rid uuid:=gen_random_uuid();claim jsonb;receipt jsonb;v integer;payload jsonb;begin select *into f from fixture;
 perform public.begin_marketvision_brand(rid,f.property_id,f.actor_id,f.input,f.model);claim:=public.claim_marketvision_brand(rid);select version into v from public.marketvision_brand_requests where id=rid;
 perform public.control_marketvision_brand(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('brandRequestId',rid,'expectedVersion',v,'action','stop','reason','Stop this saved analysis'));
 receipt:=jsonb_build_object('status','received','content',f.preview::text,'finishReason','stop');perform public.record_marketvision_brand_result(rid,(claim->>'claimToken')::uuid,receipt);
 perform pg_temp.check((select state='stopped'and raw_result=receipt from public.marketvision_brand_requests where id=rid),'late receipt retained without reopening stopped work');
 perform pg_temp.check(public.prepare_marketvision_brand_preview(rid,public.crm_configuration_hash(receipt),f.preview)->>'state'='stopped','late stopped result cannot create usable preview');
 rid:=gen_random_uuid();perform public.begin_marketvision_brand(rid,f.property_id,f.actor_id,f.input,f.model);claim:=public.claim_marketvision_brand(rid);perform public.record_marketvision_brand_result(rid,(claim->>'claimToken')::uuid,'{"status":"uncertain"}');
 perform pg_temp.check(public.claim_marketvision_brand(rid)->>'state'='held','uncertain invocation cannot automatically repeat');
 rid:=gen_random_uuid();perform public.begin_marketvision_brand(rid,f.property_id,f.actor_id,f.input,f.model);claim:=public.claim_marketvision_brand(rid);receipt:=jsonb_build_object('status','received','content','{broken','finishReason','length');perform public.record_marketvision_brand_result(rid,(claim->>'claimToken')::uuid,receipt);
 perform pg_temp.check(public.prepare_marketvision_brand_preview(rid,public.crm_configuration_hash(receipt),null,'incomplete_output')->>'state'='held','truncated model output is held without partial statements');
 perform pg_temp.check(not exists(select 1 from public.competitor_units where competitor_id=f.competitor_id)and not exists(select 1 from public.competitor_brand_intelligence where competitor_id=f.competitor_id),'brand review does not write prices or legacy intelligence');
 rid:=gen_random_uuid();perform public.begin_marketvision_brand(rid,f.property_id,f.actor_id,f.input,f.model);
 begin update public.shared_jobs set lifecycle_status='cancelled'where id=rid;raise exception 'expected native decision';exception when others then if sqlerrm='expected native decision'then raise;end if;end;
 perform pg_temp.check((select lifecycle_status='queued'from public.shared_jobs where id=rid),'generic cancellation cannot bypass native brand decision');
 begin update public.shared_context_snapshots set context_payload='{}'where id=(select context_id from public.marketvision_brand_requests where id=rid);raise exception 'expected immutable context';exception when others then if sqlerrm='expected immutable context'then raise;end if;end;
 perform pg_temp.check((select context_payload?'modelInput'from public.shared_context_snapshots where id=(select context_id from public.marketvision_brand_requests where id=rid)),'source and model context cannot be overwritten');
 update public.profiles set org_id=null where id=f.actor_id;
 perform pg_temp.check(public.claim_marketvision_brand(rid)->>'state'='held','worker rechecks original actor access before model execution');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor_id;
end$$;
-- Stable pagination reaches beyond the REST row cap; null/tied legacy dates never drop records.
insert into public.competitors(property_id,name,property_type)select f.property_id,'History fixture '||i,'multifamily'from fixture f cross join generate_series(1,1004)i;
do $$declare f fixture;r jsonb;cursor_id uuid;seen_ids uuid[]:='{}';begin select *into f from fixture;
 loop r:=public.read_marketvision_brand(f.property_id,f.actor_id,'current',null,null,cursor_id);select seen_ids||array_agg((v->>'id')::uuid)into seen_ids from jsonb_array_elements(r->'items')v;cursor_id:=(r->>'nextCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(cardinality(seen_ids)=1005 and(select count(distinct id)=1005 from unnest(seen_ids)id),'paged current coverage includes every competitor beyond 1000');
 perform pg_temp.check(public.read_marketvision_brand(f.property_id,f.actor_id,'current',null,null,gen_random_uuid())->>'state'='cursor_changed','foreign pagination anchors rejected');
 perform pg_temp.check((select request_state='completed'and kind='brand'from public.marketvision_monitoring_rows(f.property_id,'22222222-2222-2222-2222-222222222222')where id=f.request_id),'monitoring links exact saved native brand state');
end$$;

do $$declare f fixture;rid uuid;previous uuid;cursor_id uuid;seen integer:=0;r jsonb;i integer;begin select *into f from fixture;
 perform pg_temp.check(not has_function_privilege('authenticated','public.read_marketvision_brand_context(uuid)','execute'),'downstream context cannot bypass server property authorization');
 for i in 1..24 loop
  select id into previous from public.marketvision_brand_reviews where competitor_id=f.competitor_id order by review_sequence desc limit 1;
  perform public.review_marketvision_brand(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.review_input(f.request_id,previous));
 end loop;
 loop r:=public.read_marketvision_brand(f.property_id,f.actor_id,'reviews',f.competitor_id,null,cursor_id);seen:=seen+jsonb_array_length(r->'items');cursor_id:=(r->>'nextCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(seen=28,'review history pages every correction and withdrawal in retained sequence order');
 for i in 1..22 loop
  rid:=gen_random_uuid();perform public.begin_marketvision_brand(rid,f.property_id,f.actor_id,f.input,f.model);
  perform public.control_marketvision_brand(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('brandRequestId',rid,'expectedVersion',1,'action','stop','reason','Close synthetic history request'));
 end loop;
 cursor_id:=null;seen:=0;
 loop r:=public.read_marketvision_brand(f.property_id,f.actor_id,'requests',f.competitor_id,null,cursor_id);seen:=seen+jsonb_array_length(r->'items');cursor_id:=(r->>'nextCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(seen=27,'request history preserves every older stopped and held analysis');
 r:=public.read_marketvision_brand_context(f.property_id);perform pg_temp.check(r->>'activeCompetitors'='1005'and jsonb_array_length(r->'evidence')=1,'downstream snapshot retains complete coverage counts without the REST row cap');
end$$;
select count(*)as passed_assertions from checks;
rollback;
