BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(v boolean,label text)returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Assertion failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee880000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'Product handoff SQL fixture'),(pg_temp.i(2),'Product handoff other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','product-handoff-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,103)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,103)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'Product handoff SQL property'),(pg_temp.i(202),pg_temp.i(2),'Product handoff other property');
insert into public.lumaleasing_config(id,property_id,api_key,is_active)values(pg_temp.i(301),pg_temp.i(201),'handoff-synthetic-key',true);
insert into public.widget_sessions(id,property_id,visitor_id,last_activity_at)values(pg_temp.i(350),pg_temp.i(201),'handoff-fixture-visitor',clock_timestamp());
insert into public.leads(id,property_id,first_name,last_name,email,source,status)values(pg_temp.i(401),pg_temp.i(201),'Exact','Visitor','handoff@fixture.invalid','widget','new'),(pg_temp.i(402),pg_temp.i(201),'Other','Visitor','other-handoff@fixture.invalid','widget','new'),(pg_temp.i(403),pg_temp.i(202),'Alien','Visitor','alien-handoff@fixture.invalid','widget','new');
insert into public.conversations(id,property_id,widget_session_id,channel)values(pg_temp.i(451),pg_temp.i(201),pg_temp.i(350),'widget');
create function pg_temp.link(lead_id int default 401)returns jsonb language sql as $$select public.link_luma_visitor_lead(pg_temp.i(201),pg_temp.i(501),(select(v->>'token')::uuid from st where k='request'),pg_temp.i(350),pg_temp.i(451),pg_temp.i(lead_id))$$;
set local role service_role;
insert into st values('request',public.claim_recorded_luma_request(pg_temp.i(201),pg_temp.i(501),'lead',jsonb_build_object('sessionId',pg_temp.i(350),'email','handoff@fixture.invalid')::text,'fixture',encode(sha256(convert_to('handoff-synthetic-key','UTF8')),'hex')));
select pg_temp.check_it(pg_temp.link()->>'state'='saved','session, conversation and engagement link atomically');
select pg_temp.check_it((select lead_id=pg_temp.i(401)from public.widget_sessions where id=pg_temp.i(350))and(select lead_id=pg_temp.i(401)from public.conversations where id=pg_temp.i(451)),'same contact stored in both sources');
select pg_temp.check_it((select count(*)=1 from public.lead_engagement_events where lead_id=pg_temp.i(401)and event_type='chat_started'),'actual conversation link creates one engagement');
select pg_temp.check_it((select count(*)=1 from public.lead_engagement_receipts where lead_id=pg_temp.i(401)and origin='lumaleasing'),'exact immutable source receipt recorded');
select pg_temp.check_it((select count(*)=1 from public.shared_action_events where property_id=pg_temp.i(201)and action='lead.engagement.recorded'and actor_id is null and service_principal='leadpulse.source_service'and not training_eligible),'actual service action exists without a fabricated human actor');
select pg_temp.check_it((select count(*)>0 from public.lead_scores where lead_id=pg_temp.i(401)),'scoring saved before contact link is acknowledged');
select pg_temp.check_it(pg_temp.link()->>'state'='saved','link recovery safely replays');
select pg_temp.check_it((select count(*)=1 from public.lead_engagement_events where lead_id=pg_temp.i(401)and event_type='chat_started'),'repeated linkage cannot double score engagement');
select pg_temp.check_it(pg_temp.link(402)->>'state'='contact_conflict','existing visitor contact cannot silently change');
select pg_temp.check_it(pg_temp.link(403)->>'state'='not_found','other-property contact rejected');
select pg_temp.check_it(public.link_luma_visitor_lead(pg_temp.i(201),pg_temp.i(501),pg_temp.i(999),pg_temp.i(350),pg_temp.i(451),pg_temp.i(401))->>'state'='authority_changed','wrong request lease cannot change linkage');
insert into public.conversations(id,property_id,lead_id,channel)values(pg_temp.i(452),pg_temp.i(201),pg_temp.i(401),'widget');
select pg_temp.check_it((select count(*)=2 from public.lead_engagement_events where lead_id=pg_temp.i(401)and event_type='chat_started'),'new linked conversation is recorded at source insertion');
insert into public.conversations(id,property_id,lead_id,channel)values(pg_temp.i(453),pg_temp.i(201),pg_temp.i(401),'chat');
select pg_temp.check_it((select count(*)=2 from public.lead_engagement_events where lead_id=pg_temp.i(401)and event_type='chat_started'),'unqualified channel does not fabricate visitor engagement');
select pg_temp.check_it(not has_function_privilege('authenticated','public.link_luma_visitor_lead(uuid,uuid,uuid,uuid,uuid,uuid)','EXECUTE'),'linkage is server-only');
select pg_temp.check_it(public.record_lead_engagement(pg_temp.i(201),pg_temp.i(401),'website_lead_submitted','{"source":"synthetic"}','siteforge-fixture','siteforge',null)->>'state'='applied','existing durable SiteForge source remains supported');
select pg_temp.check_it((select count(*)=1 from public.shared_action_events where property_id=pg_temp.i(201)and service_principal='leadpulse.source_service'and request->>'source'='siteforge'),'SiteForge source receipt has separate service evidence');
create function pg_temp.reject_link_action()returns trigger language plpgsql as $$begin if new.property_id=pg_temp.i(201)and new.action='lead.engagement.recorded'then raise exception 'Fixture source action failure';end if;return new;end$$;
reset role;create trigger handoff_fixture_action before insert on public.shared_action_events for each row execute function pg_temp.reject_link_action();set local role service_role;
select pg_temp.throws('insert into public.conversations(id,property_id,lead_id,channel)values(pg_temp.i(460),pg_temp.i(201),pg_temp.i(401),''widget'')','source transaction fails when action cannot be recorded');
select pg_temp.check_it(not exists(select 1 from public.conversations where id=pg_temp.i(460))and not exists(select 1 from public.lead_engagement_receipts where request_key='luma/chat-started/'||pg_temp.i(460)||'/'||pg_temp.i(401)),'no partial source or scoring receipt after rollback');
reset role;drop trigger handoff_fixture_action on public.shared_action_events;
select 'Assertions passed: '||n from assertion_count;
ROLLBACK;
