BEGIN;
create temp table assertion_count(n int);insert into assertion_count values(0);
create function pg_temp.check_it(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'Failed: %',label;end if;update assertion_count set n=n+1;end$$;
create function pg_temp.throws(statement text,label text)returns void language plpgsql as $$declare failed boolean:=false;begin begin execute statement;exception when others then failed:=true;end;perform pg_temp.check_it(failed,label);end$$;
create function pg_temp.i(n int)returns uuid language sql immutable as $$select('ee750000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create temp table st(k text primary key,v jsonb);grant all on st,assertion_count to service_role;
insert into public.organizations(id,name)values(pg_temp.i(1),'Audit decision SQL fixture'),(pg_temp.i(2),'Audit decision other fixture');
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)select pg_temp.i(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','audit-decision-'||n||'@fixture.invalid',clock_timestamp(),clock_timestamp(),clock_timestamp()from generate_series(101,104)n;
insert into public.profiles(id,org_id,role)select pg_temp.i(n),pg_temp.i(case when n=103 then 2 else 1 end),case when n=102 then'viewer'else'admin'end from generate_series(101,104)n on conflict(id)do update set org_id=excluded.org_id,role=excluded.role;
insert into public.properties(id,org_id,name)values(pg_temp.i(201),pg_temp.i(1),'Audit decision SQL property'),(pg_temp.i(202),pg_temp.i(2),'Audit decision other property');
create function pg_temp.command(n int,input jsonb,a int default 101)returns jsonb language plpgsql as $$declare r jsonb;begin r:=public.decide_geo_operator(pg_temp.i(n),pg_temp.i(a),pg_temp.i(201),input);perform set_config('p11.geo_operator_scope','',true);return r;end$$;
create function pg_temp.query_fields(text_value text default'Where is the fixture property?')returns jsonb language sql as $$select jsonb_build_object('text',text_value,'type','branded','geo','Fixture City','weight',1.2,'runCount',1,'isActive',true)$$;
create function pg_temp.creation()returns jsonb language sql as $$select jsonb_build_object('operation','query_create','queries',jsonb_build_array(pg_temp.query_fields()),'sourceKind','manual','sourceEvidence','{}'::jsonb,'sourceHash',public.geo_operator_context(pg_temp.i(201))->>'hash')$$;
create function pg_temp.read_it(kind text default'context',id_value uuid default null,a int default 101,offset_n int default 0)returns jsonb language sql as $$select public.read_geo_operator(pg_temp.i(a),pg_temp.i(201),jsonb_build_object('kind',kind,'id',id_value,'offset',offset_n))$$;
create function pg_temp.query_change(n int,op text,fields jsonb default null)returns jsonb language sql as $$select pg_temp.command(n,jsonb_build_object('operation',op,'selection',jsonb_build_array(jsonb_build_object('id',v#>>'{queryIds,0}','revision',(select decision_revision from public.geo_queries where id=(v#>>'{queryIds,0}')::uuid))),'reason','Fixture decision')||case when fields is null then'{}'::jsonb else jsonb_build_object('fields',fields)end)from st where k='created'$$;
create function pg_temp.run_request()returns jsonb language sql as $$select jsonb_build_object('operation','run_request','sourceHash',public.geo_operator_context(pg_temp.i(201))->>'hash','surfaces',jsonb_build_array(jsonb_build_object('surface','chatgpt','modelName','local-fixture-model')),'executionCount',1,'measurementMode','local_fixture')$$;
create function pg_temp.run_change(n int,op text,extra jsonb default'{}',which text default'run')returns jsonb language sql as $$select pg_temp.command(n,jsonb_build_object('operation',op,'runId',v#>>'{source,run,id}','revision',(v#>>'{source,run,control_revision}')::integer,'sourceHash',v->>'hash','reason','Reviewed fixture measurement')||extra)from st where k=which$$;
set local role service_role;
select pg_temp.check_it(public.geo_operator_query_valid(pg_temp.query_fields()),'valid query fields');
select pg_temp.check_it(not public.geo_operator_query_valid(pg_temp.query_fields()||'{"weight":0}'),'invalid query weight held');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation(),102)->>'state'='forbidden','viewer cannot configure audit');
select pg_temp.check_it(pg_temp.command(301,pg_temp.creation(),103)->>'state'='forbidden','other tenant cannot configure audit');
insert into st values('input',pg_temp.creation());insert into st values('created',pg_temp.command(301,(select v from st where k='input')));
select pg_temp.check_it((select v->>'count'='1'from st where k='created'),'one reviewed query saved');
select pg_temp.check_it(pg_temp.command(301,(select v from st where k='input'))->>'state'='replayed','saved identity cannot duplicate prompts');
select pg_temp.check_it(pg_temp.command(301,(select v from st where k='input'),104)->>'state'='not_found','request owner scope');
select pg_temp.check_it(pg_temp.command(302,pg_temp.creation())->>'state'='query_conflict','duplicate prompt held rather than silently duplicated');
select pg_temp.check_it(pg_temp.read_it('queries',null,102)->>'count'='1','viewer reads complete queries');
select pg_temp.check_it(pg_temp.read_it('queries',null,103)->>'state'='forbidden','other tenant read held');
select pg_temp.check_it(pg_temp.query_change(303,'query_edit',pg_temp.query_fields('Reviewed revised question')) ->>'state'='saved','query edit retained');
select pg_temp.check_it(pg_temp.read_it('history')#>>'{items,0,before_state,0,text}'='Where is the fixture property?','original query wording retained');
select pg_temp.check_it(pg_temp.query_change(304,'query_archive')->>'state'='saved','query archive saved');
select pg_temp.check_it(public.geo_operator_context(pg_temp.i(201))->>'queryCount'='0','archive excludes future execution');
select pg_temp.check_it(pg_temp.query_change(305,'query_restore')->>'state'='saved','query restore saved');
select pg_temp.check_it(public.geo_operator_context(pg_temp.i(201))->>'queryCount'='0','restore does not silently activate');
select pg_temp.check_it(pg_temp.query_change(306,'query_edit',pg_temp.query_fields('Reviewed revised question'))->>'state'='saved','restored query explicitly enabled');
select pg_temp.check_it(pg_temp.command(307,pg_temp.run_request()||jsonb_build_object('sourceHash',repeat('a',64)))->>'state'='source_changed','run requires current reviewed source');
insert into st values('request',pg_temp.run_request());insert into st values('requested',pg_temp.command(307,(select v from st where k='request')));
select pg_temp.check_it((select v->>'expectedExecutions'='1'from st where k='requested'),'exact run queued');
select pg_temp.check_it(pg_temp.command(307,(select v from st where k='request'))->>'state'='replayed','run request lost reply cannot duplicate calls');
insert into st values('run',pg_temp.read_it('run',(select(v#>>'{runIds,0}')::uuid from st where k='requested')));
select pg_temp.check_it((select v#>>'{items,0,query,text}'='Reviewed revised question'from st where k='run'),'worker receives captured query wording');
select pg_temp.check_it(not exists(select 1 from public.geo_execution_jobs j join public.geo_runs r on r.id=j.run_id where r.property_id=pg_temp.i(201)and r.measurement_mode<>'local_fixture'),'only isolated fixture work exists');
select pg_temp.check_it(pg_temp.run_change(308,'run_archive')->>'state'='run_open','running work cannot be hidden through archive');
select pg_temp.check_it(pg_temp.run_change(308,'run_stop')->>'state'='saved','queued run can stop');
select pg_temp.check_it((select bool_and(state='failed'and lease_token is null)from public.geo_execution_jobs where property_id=pg_temp.i(201)),'stop fences worker lease');
select pg_temp.check_it(pg_temp.run_change(309,'run_retry')->>'state'='run_changed','stale retry cannot proceed');
update st set v=pg_temp.read_it('run',(v#>>'{source,run,id}')::uuid)where k='run';
select pg_temp.check_it(pg_temp.query_change(310,'query_edit',pg_temp.query_fields('A later question')) ->>'state'='saved','current query can change independently of captured run');
select pg_temp.check_it(pg_temp.run_change(311,'run_retry')->>'state'='saved','linked retry saved');
select pg_temp.check_it((select retry_of=(select(v#>>'{source,run,id}')::uuid from st where k='run')from public.geo_runs where id=pg_temp.i(311)),'retry explicitly linked');
select pg_temp.check_it((select query_snapshot->>'text'='Reviewed revised question'from public.geo_execution_items where run_id=pg_temp.i(311)),'retry uses original source not current prompt');
select pg_temp.check_it(pg_temp.run_change(312,'run_review','{"review":"inconclusive"}')->>'state'='saved','incomplete result can be reviewed honestly');
select pg_temp.check_it(pg_temp.read_it('history')#>>'{items,0,after_state,verifiedImprovement}'='false','review is not a verified improvement');
select pg_temp.check_it(pg_temp.run_change(313,'run_archive')->>'state'='saved','terminal run archived with sources retained');
select pg_temp.check_it((select count(*)=1 from public.geo_execution_items where run_id=(select(v#>>'{source,run,id}')::uuid from st where k='run')),'archive retains execution source');
update st set v=pg_temp.read_it('run',(v#>>'{source,run,id}')::uuid)where k='run';
select pg_temp.check_it(pg_temp.run_change(314,'run_restore')->>'state'='saved','archived run restored');
select pg_temp.check_it(pg_temp.command(315,'{"operation":"cancel_request"}')->>'status'='cancelled_request','unused request cancelled');
select pg_temp.check_it(pg_temp.command(315,pg_temp.run_request())->>'status'='cancelled_request','late run request fenced');
insert into public.geo_site_findings(id,property_id,category,description,detector,fingerprint,title,severity)values(pg_temp.i(401),pg_temp.i(201),'technical','Private evidence detail','fixture','fixture-key','Missing title','medium');
insert into public.geo_recommendations(id,property_id,title,type,narrative,status)values(pg_temp.i(402),pg_temp.i(201),'Review title','content','Private draft explanation','todo');
insert into st values('finding',pg_temp.read_it('findings')->'items'->0),('recommendation',pg_temp.read_it('recommendations')->'items'->0);
select pg_temp.check_it(pg_temp.command(316,jsonb_build_object('operation','finding_review','resourceId',pg_temp.i(401),'sourceHash',(select v->>'sourceHash'from st where k='finding'),'status','fixed','owner','web_developer','notes','Staff reports title changed','reason','Review against next actual crawl'))->>'reportedStatus'='fixed','reported fix saved with reason');
select pg_temp.check_it(pg_temp.command(317,jsonb_build_object('operation','finding_review','resourceId',pg_temp.i(401),'sourceHash',(select v->>'sourceHash'from st where k='finding'),'status','todo','owner','','notes','','reason','Old evidence'))->>'state'='source_changed','stale evidence review held');
select pg_temp.check_it(pg_temp.command(318,jsonb_build_object('operation','recommendation_review','resourceId',pg_temp.i(402),'sourceHash',(select v->>'sourceHash'from st where k='recommendation'),'status','in_progress','owner','content','notes','Review copy','reason','Selected for editorial review'))->>'state'='saved','recommendation choice retained');
select pg_temp.check_it((select count(*)from public.geo_operator_commands where property_id=pg_temp.i(201))=(select count(*)from public.shared_action_events where property_id=pg_temp.i(201)and action like'audit.%'),'every human mutation has atomic shared history');
select pg_temp.check_it((select bool_and(not training_eligible and request::text not like'%Private%'and result::text not like'%Private%')from public.shared_action_events where property_id=pg_temp.i(201)),'private evidence excluded and all decisions training ineligible');
select pg_temp.throws(format('delete from public.geo_queries where property_id=%L',pg_temp.i(201)),'query source deletion held');
select pg_temp.throws(format('delete from public.geo_runs where property_id=%L',pg_temp.i(201)),'run source deletion held');
select pg_temp.throws(format('update public.geo_operator_commands set input=%L where id=%L','{}',pg_temp.i(301)),'decision immutable');
-- No provider calls: deterministic local receipts exercise the real persistence boundary.
insert into st values('lease',public.claim_geo_execution(pg_temp.i(311)));
insert into st values('next',public.advance_geo_execution(pg_temp.i(311),(select(v->>'lease_token')::uuid from st where k='lease')));
insert into st values('invocation',public.start_geo_provider_invocation(pg_temp.i(311),(select(v->>'lease_token')::uuid from st where k='lease'),(select(v#>>'{item,id}')::uuid from st where k='next')));
select pg_temp.check_it((select v->>'state'='claimed'from st where k='invocation'),'provider invocation starts once');
select pg_temp.check_it(public.start_geo_provider_invocation(pg_temp.i(311),(select(v->>'lease_token')::uuid from st where k='lease'),(select(v#>>'{item,id}')::uuid from st where k='next'))->>'state'='in_progress','same invocation cannot call provider twice');
insert into st values('provider',jsonb_build_object('answer',jsonb_build_object('run_id',pg_temp.i(311),'query_id',(select v#>>'{item,query_snapshot,id}'from st where k='next'),'presence',false,'flags','[]'::jsonb,'answer_summary','Deterministic local receipt','ordered_entities','[]'::jsonb,'raw_json','{"synthetic":true}'::jsonb,'analysis_method','local_fixture'),'citations','[]'::jsonb,'score','{"presence":false,"score":0}'::jsonb));
select pg_temp.check_it(public.finish_geo_provider_invocation((select(v->>'invocationId')::uuid from st where k='invocation'),(select(v->>'lease_token')::uuid from st where k='lease'),(select v from st where k='provider'))->>'state'='retained','actual response retained before application');
select pg_temp.check_it((select count(*)=0 from public.geo_answers where run_id=pg_temp.i(311)),'retention alone does not claim a scored answer');
select pg_temp.check_it(public.start_geo_provider_invocation(pg_temp.i(311),(select(v->>'lease_token')::uuid from st where k='lease'),(select(v#>>'{item,id}')::uuid from st where k='next'))->>'state'='retained','retained response prevents another provider call');
reset role;
create function pg_temp.fail_geo_application()returns trigger language plpgsql as $$begin if new.kind='response_applied'then raise exception 'Synthetic receipt application failure';end if;return new;end$$;
create trigger fixture_geo_application_failure before insert on public.geo_service_events for each row execute function pg_temp.fail_geo_application();
select pg_temp.throws(format('select public.apply_geo_provider_invocation(%L,%L,%L)',(select v->>'invocationId'from st where k='invocation'),pg_temp.i(311),(select v->>'lease_token'from st where k='lease')),'application history failure rolls back derived answer');
select pg_temp.check_it((select count(*)=0 from public.geo_answers where run_id=pg_temp.i(311)),'failed application leaves no half-saved answer');
select pg_temp.check_it((select state='returned'and not applied from public.geo_provider_invocations where id=(select(v->>'invocationId')::uuid from st where k='invocation')),'failed application retains original actual response');
drop trigger fixture_geo_application_failure on public.geo_service_events;
set local role service_role;
select pg_temp.check_it(public.apply_geo_provider_invocation((select(v->>'invocationId')::uuid from st where k='invocation'),pg_temp.i(311),(select(v->>'lease_token')::uuid from st where k='lease'))->>'ready_to_finish'='true','retained response safely applied without provider replay');
select pg_temp.check_it((select count(*)=1 from public.geo_answers where run_id=pg_temp.i(311)),'exactly one measured answer saved');
select pg_temp.check_it(public.finish_geo_execution(pg_temp.i(311),(select(v->>'lease_token')::uuid from st where k='lease'),'{"overall_score":0,"visibility_pct":0,"breakdown":{"synthetic":true}}')->>'state'='completed','actual fixture completion recorded separately');
select pg_temp.check_it((select bool_and(actor_id is null and service_principal='propertyaudit.worker'and not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)and action like'audit.worker.%'),'worker events never forge human demonstrations');
insert into st values('late_request',pg_temp.command(320,pg_temp.run_request()));
insert into st values('late_lease',public.claim_geo_execution((select(v#>>'{runIds,0}')::uuid from st where k='late_request')));
insert into st values('late_next',public.advance_geo_execution((select(v->>'run_id')::uuid from st where k='late_lease'),(select(v->>'lease_token')::uuid from st where k='late_lease')));
insert into st values('late_invocation',public.start_geo_provider_invocation((select(v->>'run_id')::uuid from st where k='late_lease'),(select(v->>'lease_token')::uuid from st where k='late_lease'),(select(v#>>'{item,id}')::uuid from st where k='late_next')));
insert into st values('late_run',pg_temp.read_it('run',(select(v->>'run_id')::uuid from st where k='late_lease')));
select pg_temp.check_it(pg_temp.run_change(321,'run_stop','{}','late_run')->>'state'='saved','in-flight run stopped through current reviewed state');
select pg_temp.check_it(public.finish_geo_provider_invocation((select(v->>'invocationId')::uuid from st where k='late_invocation'),(select(v->>'lease_token')::uuid from st where k='late_lease'),'{"answer":{"answer_summary":"Late synthetic response"}}')->>'state'='retained','late response survives stopped lease');
select pg_temp.check_it(public.apply_geo_provider_invocation((select(v->>'invocationId')::uuid from st where k='late_invocation'),(select(v->>'run_id')::uuid from st where k='late_lease'),(select(v->>'lease_token')::uuid from st where k='late_lease'))->>'state'='lease_lost','late response cannot resume stopped work');
select pg_temp.check_it((select count(*)=0 from public.geo_answers where run_id=(select(v->>'run_id')::uuid from st where k='late_lease')),'late response cannot create an accepted answer');

insert into st values('withdrawn_request',pg_temp.command(325,pg_temp.run_request()));
insert into st values('withdrawn_lease',public.claim_geo_execution((select(v#>>'{runIds,0}')::uuid from st where k='withdrawn_request')));
insert into st values('withdrawn_next',public.advance_geo_execution((select(v->>'run_id')::uuid from st where k='withdrawn_lease'),(select(v->>'lease_token')::uuid from st where k='withdrawn_lease')));
select set_config('p11.team_scope',pg_temp.i(1)::text,true);update public.profiles set role='viewer'where id=pg_temp.i(101);
select pg_temp.check_it(public.start_geo_provider_invocation((select(v->>'run_id')::uuid from st where k='withdrawn_lease'),(select(v->>'lease_token')::uuid from st where k='withdrawn_lease'),(select(v#>>'{item,id}')::uuid from st where k='withdrawn_next'))->>'state'='authorization_changed','permission is rechecked before the next provider invocation');
select pg_temp.check_it(not exists(select 1 from public.geo_provider_invocations where run_id=(select(v->>'run_id')::uuid from st where k='withdrawn_lease')),'withdrawn authority never starts a provider invocation');
select pg_temp.check_it((select state='failed'and lease_token is null from public.geo_execution_jobs where run_id=(select(v->>'run_id')::uuid from st where k='withdrawn_lease')),'withdrawn authority visibly closes and fences the queued work');
update public.profiles set role='admin'where id=pg_temp.i(101);

-- No network: synthetic website captures exercise native persistence and fencing.
update public.properties set website_url='https://audit-fixture.invalid'where id=pg_temp.i(201);
insert into st values('crawl_requested',pg_temp.command(701,pg_temp.run_request()||'{"includeSiteCrawl":true}'));
select pg_temp.check_it((select v->>'crawlId'=pg_temp.i(701)::text from st where k='crawl_requested'),'reviewed website crawl queued atomically');
select pg_temp.check_it((select seed_url='https://audit-fixture.invalid'and measurement_mode='local_fixture'from public.geo_site_crawls where id=pg_temp.i(701)),'crawl keeps exact reviewed URL and synthetic provenance');
select pg_temp.check_it(public.claim_geo_site_crawl()is null,'background worker never claims synthetic website crawl');
insert into st values('crawl_claim',public.claim_geo_site_crawl(pg_temp.i(701)));
select pg_temp.check_it((select v->>'status'='running'and v->>'lease_token'is not null from st where k='crawl_claim'),'explicit synthetic worker claim fenced');
select pg_temp.check_it(public.claim_geo_site_crawl(pg_temp.i(701))is null,'second crawler cannot share lease');
select pg_temp.check_it(public.save_geo_site_crawl(pg_temp.i(701),pg_temp.i(999),'pages','{"pages":[]}')->>'state'='lease_lost','unknown crawl lease cannot persist pages');
select pg_temp.check_it(public.save_geo_site_crawl(pg_temp.i(701),(select(v->>'lease_token')::uuid from st where k='crawl_claim'),'pages','{"pages":[{"url":"https://audit-fixture.invalid","title":"Captured fixture title","status_code":200,"content_type":"text/html","content":{},"forms":[],"provenance":{}}]}')->>'state'='saved','captured page saved through current lease');
select pg_temp.check_it(public.save_geo_site_crawl(pg_temp.i(701),(select(v->>'lease_token')::uuid from st where k='crawl_claim'),'checkpoint','{"crawl_state":{"frontier":["https://audit-fixture.invalid/next"]},"pages_discovered":2}')->>'state'='saved','checkpoint and worker evidence commit together');
select pg_temp.check_it((select pages_crawled=1 and pages_discovered=2 from public.geo_site_crawls where id=pg_temp.i(701)),'checkpoint uses actual persisted page count');
insert into st values('crawl_review',pg_temp.read_it('crawl',pg_temp.i(701)));
select pg_temp.check_it(pg_temp.command(702,jsonb_build_object('operation','crawl_stop','crawlId',pg_temp.i(701),'sourceHash',(select v->>'hash'from st where k='crawl_review'),'reason','Synthetic stop test'))->>'state'='saved','operator can stop reviewed crawl');
select pg_temp.check_it(public.save_geo_site_crawl(pg_temp.i(701),(select(v->>'lease_token')::uuid from st where k='crawl_claim'),'completed','{"findings":[]}')->>'state'='lease_lost','late crawler cannot publish after stop');
select pg_temp.check_it((select count(*)=1 from public.geo_crawl_pages where crawl_id=pg_temp.i(701)),'stopping keeps captured pages');
update st set v=pg_temp.read_it('crawl',pg_temp.i(701))where k='crawl_review';
select pg_temp.check_it(pg_temp.command(703,jsonb_build_object('operation','crawl_retry','crawlId',pg_temp.i(701),'sourceHash',(select v->>'hash'from st where k='crawl_review'),'reason','Explicit reviewed retry'))->>'state'='saved','crawl retry creates separate retained capture');
select pg_temp.check_it((select retry_of=pg_temp.i(701)and seed_url='https://audit-fixture.invalid'from public.geo_site_crawls where id=pg_temp.i(703)),'retry retains source and original link');
insert into st values('crawl_retry_claim',public.claim_geo_site_crawl(pg_temp.i(703)));
select pg_temp.check_it(public.save_geo_site_crawl(pg_temp.i(703),(select(v->>'lease_token')::uuid from st where k='crawl_retry_claim'),'completed','{"findings":[],"page_cap_reached":true,"robots_summary":{},"sitemap_summary":{},"llms_txt_summary":{},"pages_discovered":0}')->>'state'='saved','completed limited crawl is recorded');
select pg_temp.check_it((select status='completed'and crawl_state->>'page_cap_reached'='true'from public.geo_site_crawls where id=pg_temp.i(703)),'coverage limitation remains explicit');
select pg_temp.check_it((select count(*)=1 from public.geo_service_events where property_id=pg_temp.i(201)and kind='crawl_completed'and detail->>'absenceIsVerifiedFix'='false'),'absence never claimed as verified fix');
select pg_temp.check_it(pg_temp.read_it('crawls')->>'count'='2','complete crawl history remains reachable');
select pg_temp.check_it(pg_temp.read_it('service_history')->>'count'<>'0','worker source history readable separately');
select pg_temp.check_it(pg_temp.read_it('crawl',pg_temp.i(703),103)->>'state'='forbidden','other organization cannot inspect crawl');
select pg_temp.check_it(pg_temp.read_it('crawl',pg_temp.i(703))#>'{source,lease_token}'is null,'crawl read never exposes lease token');
select pg_temp.check_it((select bool_and(not training_eligible)from public.shared_action_events where property_id=pg_temp.i(201)),'worker and human decisions remain training ineligible');

insert into public.geo_queries(property_id,text,type,is_active)select pg_temp.i(201),'Bulk question '||n,'faq',false from generate_series(1,1205)n;
select pg_temp.check_it(pg_temp.read_it('queries')->>'count'='1206','query inventory complete beyond API row cap');
select pg_temp.check_it(jsonb_array_length(pg_temp.read_it('queries',null,101,1200)->'items')=6,'last query page reachable');
select pg_temp.check_it(public.read_geo_operator(pg_temp.i(101),pg_temp.i(201),'{"kind":"queries","search":"%_"}')->>'count'='0','special characters search literally');
reset role;
select pg_temp.check_it(not has_function_privilege('authenticated','public.decide_geo_operator(uuid,uuid,uuid,jsonb)','EXECUTE'),'native decision service-only');
select pg_temp.check_it(not has_table_privilege('authenticated','public.geo_operator_commands','SELECT'),'private snapshots service-only');

reset role;set local role service_role;
create function pg_temp.report_options(fmt text default'html')returns jsonb language sql as $$select jsonb_build_object('format',fmt,'template','comprehensive','sections','["summary","queries"]'::jsonb,'runId',pg_temp.i(311))$$;
create function pg_temp.report_prepare(n int,a int default 101,opts jsonb default null,cancel boolean default false)returns jsonb language sql as $$select public.prepare_geo_report(pg_temp.i(n),pg_temp.i(a),pg_temp.i(201),coalesce(opts,pg_temp.report_options()),cancel)$$;
create function pg_temp.report_read(n int,a int default 101)returns jsonb language sql as $$select public.read_geo_reports(pg_temp.i(a),pg_temp.i(201),pg_temp.i(n))$$;
select pg_temp.check_it(pg_temp.report_prepare(800,103)->>'state'='forbidden','cross tenant report held');
select pg_temp.check_it(pg_temp.report_prepare(800,101,pg_temp.report_options()||'{"secret":true}')->>'state'='invalid_input','unknown export options held');
select pg_temp.check_it(pg_temp.report_prepare(800,101,pg_temp.report_options()||'{"format":"pdf"}')->>'state'='invalid_input','cannot claim generated PDF bytes');
select pg_temp.check_it(pg_temp.report_prepare(800,101,pg_temp.report_options()-'runId')->>'state'='completed_run_required','synthetic measurement excluded from default report');
select pg_temp.check_it(pg_temp.report_prepare(800)->>'status'='prepared','exact report source prepared');
select pg_temp.check_it(pg_temp.report_prepare(800)->>'state'='replayed','missed source reply recovers without recapture');
select pg_temp.check_it(pg_temp.report_prepare(800,104)->>'state'='not_found','another actor cannot finish original request');
select pg_temp.check_it(pg_temp.report_prepare(800,101,pg_temp.report_options('markdown'))->>'state'='request_conflict','changed requested format cannot reuse report identity');
select pg_temp.check_it(pg_temp.report_read(800)#>>'{record,source,runs,0,items,0,query,text}'='Reviewed revised question','report uses captured original question');
select pg_temp.check_it(pg_temp.report_read(800)#>>'{record,source,runs,0,answers,0,answer,answer_summary}'='Deterministic local receipt','actual accepted answer retained');
select pg_temp.check_it(pg_temp.report_read(800,102)->>'state'='ready','viewer reads saved report within property');
select pg_temp.check_it(pg_temp.report_read(800,103)->>'state'='forbidden','other tenant cannot inspect report');
select pg_temp.check_it(pg_temp.report_read(800,104)->>'canResume'='false','other actor can read without original request authority');
insert into st values('report_source',pg_temp.report_read(800)->'record'->'source');
select set_config('p11.geo_operator_scope',pg_temp.i(201)::text,true);update public.geo_queries set text='Changed after report capture'where id=(select(v#>>'{queryIds,0}')::uuid from st where k='created');
select pg_temp.check_it(pg_temp.report_read(800)->'record'->'source'=(select v from st where k='report_source'),'later query edits cannot alter report evidence');
select pg_temp.check_it(public.finish_geo_report(pg_temp.i(800),pg_temp.i(101),pg_temp.i(201),'wrong','fixture artifact')->>'state'='source_changed','mismatched source cannot finish');
select pg_temp.check_it(public.finish_geo_report(pg_temp.i(800),pg_temp.i(104),pg_temp.i(201),pg_temp.report_read(800)#>>'{record,source_hash}','fixture artifact')->>'state'='not_found','other actor cannot render original report');
select pg_temp.check_it(public.finish_geo_report(pg_temp.i(800),pg_temp.i(101),pg_temp.i(201),pg_temp.report_read(800)#>>'{record,source_hash}','fixture artifact')->>'status'='ready','exact artifact saved');
select pg_temp.check_it(public.finish_geo_report(pg_temp.i(800),pg_temp.i(101),pg_temp.i(201),pg_temp.report_read(800)#>>'{record,source_hash}','fixture artifact')->>'state'='replayed','artifact acknowledgment recovery');
select pg_temp.check_it(public.finish_geo_report(pg_temp.i(800),pg_temp.i(101),pg_temp.i(201),pg_temp.report_read(800)#>>'{record,source_hash}','different artifact')->>'state'='request_conflict','finished artifact cannot change');
select pg_temp.check_it(pg_temp.report_read(800)#>>'{record,artifact}'='fixture artifact','retained bytes directly available');
select pg_temp.check_it(public.observe_geo_report(pg_temp.i(820),pg_temp.i(102),pg_temp.i(201),pg_temp.i(800),'prepared')->>'state'='saved','viewer export preparation separately recorded');
select pg_temp.check_it(public.observe_geo_report(pg_temp.i(820),pg_temp.i(102),pg_temp.i(201),pg_temp.i(800),'download_initiated')->>'state'='saved','browser outcome separately recorded');
select pg_temp.check_it(public.observe_geo_report(pg_temp.i(820),pg_temp.i(102),pg_temp.i(201),pg_temp.i(800),'download_initiated')->>'state'='replayed','lost browser observation acknowledgment idempotent');
select pg_temp.check_it(public.observe_geo_report(pg_temp.i(820),pg_temp.i(102),pg_temp.i(201),pg_temp.i(800),'failed')->>'state'='request_conflict','reported outcome immutable');
select pg_temp.check_it(public.observe_geo_report(pg_temp.i(821),pg_temp.i(102),pg_temp.i(201),pg_temp.i(800),'download_initiated')->>'state'='not_found','unprepared download cannot be reported');
select pg_temp.check_it((select evidence='browser_observed'and phase='observed'from public.shared_action_events where episode_id=pg_temp.i(820)and action='audit.report.reported'),'browser initiation never claims verified delivery');
select pg_temp.check_it(pg_temp.report_prepare(802,101,'{}',true)->>'status'='cancelled','unused report request cancellation');
select pg_temp.check_it(pg_temp.report_prepare(802)->>'status'='cancelled','late source capture fenced');
select pg_temp.check_it(pg_temp.report_prepare(803)->>'status'='prepared','second source prepared');
select pg_temp.check_it(pg_temp.report_prepare(803,101,'{}',true)->>'status'='cancelled','pending rendering can cancel');
select pg_temp.check_it(public.finish_geo_report(pg_temp.i(803),pg_temp.i(101),pg_temp.i(201),pg_temp.report_read(803)#>>'{record,source_hash}','late artifact')->>'state'='cancelled','late renderer cannot finish cancelled source');
select pg_temp.check_it(pg_temp.report_read(803)#>>'{record,artifact}'is null,'cancel retains source without claiming artifact');
select pg_temp.throws(format('delete from public.geo_report_records where id=%L',pg_temp.i(800)),'report history retained');
select pg_temp.throws(format('update public.geo_report_records set artifact=%L where id=%L','changed',pg_temp.i(800)),'artifact guard independent of API');
select pg_temp.check_it((select bool_and(not training_eligible and request::text not like'%Deterministic%'and result::text not like'%fixture artifact%')from public.shared_action_events where action like'audit.report.%'and property_id=pg_temp.i(201)),'private report content excluded from shared training-ineligible history');
select pg_temp.check_it((select bool_and(origin='console')from public.shared_action_episodes where id in(pg_temp.i(800),pg_temp.i(820))),'human report actions use console attribution');
select pg_temp.check_it(pg_temp.report_prepare(804,102,pg_temp.report_options('queries_csv'))->>'status'='prepared','viewer may export readable active question inventory');
select set_config('p11.geo_operator_scope',pg_temp.i(201)::text,true);
insert into public.geo_queries(property_id,text,type,is_active)select pg_temp.i(201),'Report complete inventory '||n,'branded',true from generate_series(1,1051)n;
select pg_temp.check_it(pg_temp.report_prepare(805,101,pg_temp.report_options('queries_csv'))->>'status'='prepared','large inventory report saved');
select pg_temp.check_it(jsonb_array_length(pg_temp.report_read(805)#>'{record,source,queries}')>1050,'native report source has no REST thousand-row truncation');
select pg_temp.check_it(pg_temp.report_prepare(806,101,pg_temp.report_options('findings_csv'))->>'status'='prepared','findings CSV saved');
select pg_temp.check_it(jsonb_array_length(pg_temp.report_read(806)#>'{record,source,findings}')>0,'findings include retained private review evidence');
-- A source or artifact cannot commit without its action event.
reset role;
create function pg_temp.fail_report_event()returns trigger language plpgsql as $$begin if new.action='audit.report.prepared'then raise exception 'Synthetic report history failure';end if;return new;end$$;
create trigger fixture_report_event before insert on public.shared_action_events for each row execute function pg_temp.fail_report_event();
set local role service_role;
select pg_temp.throws(format('select public.finish_geo_report(%L,%L,%L,%L,%L)',pg_temp.i(804),pg_temp.i(102),pg_temp.i(201),pg_temp.report_read(804)#>>'{record,source_hash}','atomic fixture'),'artifact evidence failure rolls back completion');
select pg_temp.check_it(pg_temp.report_read(804)#>>'{record,state}'='prepared'and pg_temp.report_read(804)#>>'{record,artifact}'is null,'no half-saved report after evidence failure');
reset role;drop trigger fixture_report_event on public.shared_action_events;
set local role service_role;
select pg_temp.report_prepare(n,101,pg_temp.report_options('queries_csv'))from generate_series(900,930)n;
insert into st values('report_history',public.read_geo_reports(pg_temp.i(101),pg_temp.i(201)));
select pg_temp.check_it((select jsonb_array_length(v->'items')=25 and(v->>'count')::int>30 from st where k='report_history'),'full report history count with bounded first page');
select pg_temp.check_it(jsonb_array_length(public.read_geo_reports(pg_temp.i(101),pg_temp.i(201),null,25,(select v->>'hash'from st where k='report_history'))->'items')>0,'older reports reachable');
select pg_temp.report_prepare(932,101,pg_temp.report_options('queries_csv'));
select pg_temp.check_it(public.read_geo_reports(pg_temp.i(101),pg_temp.i(201),null,25,(select v->>'hash'from st where k='report_history'))->>'state'='history_changed','changed report history cannot mix pagination');
reset role;
select pg_temp.check_it(not has_table_privilege('authenticated','public.geo_report_records','SELECT')and not has_function_privilege('authenticated','public.prepare_geo_report(uuid,uuid,uuid,jsonb,boolean)','EXECUTE'),'native source/operations service-only');
select n as assertions_passed from assertion_count;
ROLLBACK;
