begin;
do $$
declare actor uuid:='11111111-1111-1111-1111-111111111111';org uuid;prop uuid:=gen_random_uuid();foreign_org uuid:=gen_random_uuid();foreign_prop uuid:=gen_random_uuid();request uuid:=gen_random_uuid();r jsonb;input jsonb;count_before integer;release uuid:=gen_random_uuid();
begin
 select org_id into org from public.profiles where id=actor;
 if org is null then raise exception 'Local admin fixture required';end if;
 insert into public.properties(id,org_id,name)values(prop,org,'Intelligence transaction fixture');
 insert into public.organizations(id,name)values(foreign_org,'Intelligence foreign fixture');
 insert into public.properties(id,org_id,name)values(foreign_prop,foreign_org,'Foreign property');
 input:=jsonb_build_object('kind','fact','key','market','expectedRevision',0,'operation','save','reason','SQL qualification','payload',jsonb_build_object('field','market','value','Austin'));
 r:=public.decide_property_intelligence(request,actor,foreign_prop,input);if r->>'state'<>'forbidden'then raise exception 'Cross-org mutation allowed';end if;
 r:=public.decide_property_intelligence(request,actor,prop,input);if r->>'state'<>'saved'then raise exception 'Save failed: %',r;end if;
 r:=public.decide_property_intelligence(request,actor,prop,input);if r->>'state'<>'replayed'then raise exception 'Retry not idempotent';end if;
 r:=public.decide_property_intelligence(request,actor,prop,input||'{"reason":"different"}');if r->>'state'<>'request_conflict'then raise exception 'Request identity conflict lost';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input);if r->>'state'<>'changed'then raise exception 'Stale save allowed';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"approve","expectedRevision":1}');if r->>'state'<>'saved'or r#>>'{document,status}'<>'approved'then raise exception 'Approval failed';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"lock","expectedRevision":2}');if r->>'state'<>'saved'then raise exception 'Lock failed';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"expectedRevision":3}');if r->>'state'<>'locked'then raise exception 'Locked content overwritten';end if;
 select count(*)into count_before from public.shared_action_events where property_id=prop and action like 'intelligence.%';if count_before<>3 then raise exception 'Expected exactly three successful decisions, got %',count_before;end if;
 if has_table_privilege('authenticated','public.property_intelligence_documents','select')or has_table_privilege('anon','public.property_intelligence_documents','select')or has_function_privilege('authenticated','public.decide_property_intelligence(uuid,uuid,uuid,jsonb)','execute')then raise exception 'Direct public access exposed';end if;
 begin update public.property_intelligence_changes set input='{}'where id=request;raise exception 'History update unexpectedly succeeded';exception when sqlstate '55000' then null;end;
 insert into public.shared_action_episodes(id,org_id,property_id,actor_id,origin)values(release,org,prop,actor,'console');
 insert into public.shared_action_events(id,episode_id,org_id,property_id,actor_id,product,action,evidence,phase,request,result)values(release,release,org,prop,actor,'siteforge','site.delivery.recorded','server_confirmed','succeeded','{}','{"qualificationOnly":true}');
 input:=jsonb_build_object('kind','experiment','key','future','expectedRevision',0,'operation','save','reason','SQL qualification','payload',jsonb_build_object('start',current_date+1,'end',current_date+8,'releaseEvent',release));
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input);if r->>'state'<>'saved'then raise exception 'Experiment draft failed';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"approve","expectedRevision":1}');if r->>'state'<>'saved'then raise exception 'Experiment preregistration failed';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"expectedRevision":2}');if r->>'state'<>'frozen'then raise exception 'Approved experiment changed';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"measure","expectedRevision":2,"payload":{"evaluation":{"ready":true}}}');if r->>'state'<>'invalid_evidence'then raise exception 'Open experiment measured';end if;
 input:=input||jsonb_build_object('key','past','payload',jsonb_build_object('start',current_date-1,'end',current_date+8,'releaseEvent',release));
 perform public.decide_property_intelligence(gen_random_uuid(),actor,prop,input);
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"approve","expectedRevision":1}');if r->>'state'<>'preregister_required'then raise exception 'Retrospective experiment registered';end if;
 input:=jsonb_build_object('kind','recommendation','key','untested','expectedRevision',0,'operation','save','reason','SQL qualification','payload','{}'::jsonb);
 perform public.decide_property_intelligence(gen_random_uuid(),actor,prop,input);
 perform public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"approve","expectedRevision":1}');
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"implement","expectedRevision":2}');if r->>'state'<>'invalid_evidence'then raise exception 'Implementation without action evidence allowed';end if;
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"measure","expectedRevision":2}');if r->>'state'<>'invalid_transition'then raise exception 'Unimplemented recommendation measured';end if;
 release:=gen_random_uuid();
 insert into public.shared_action_episodes(id,org_id,property_id,actor_id,origin)values(release,org,prop,actor,'console');
 insert into public.shared_action_events(id,episode_id,org_id,property_id,actor_id,product,action,evidence,phase,request,result)values(release,release,org,prop,actor,'siteforge','site.package.queued','server_confirmed','succeeded','{}','{"qualificationOnly":true}');
 input:=jsonb_build_object('kind','experiment','key','queued-not-delivered','expectedRevision',0,'operation','save','reason','SQL qualification','payload',jsonb_build_object('start',current_date+1,'end',current_date+8,'releaseEvent',release));
 perform public.decide_property_intelligence(gen_random_uuid(),actor,prop,input);
 r:=public.decide_property_intelligence(gen_random_uuid(),actor,prop,input||'{"operation":"approve","expectedRevision":1}');if r->>'state'<>'invalid_evidence'then raise exception 'Queued work mistaken for implementation evidence';end if;
end $$;
rollback;
