
begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is not true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(source_id uuid,foreign_id uuid,foreign_org uuid,target_id uuid,actor uuid);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111');
insert into public.organizations(id,name)select foreign_org,'Property creation foreign fixture'from fixture;
insert into public.properties(id,org_id,name,brand_voice,pet_policy,parking_info,office_hours)select source_id,'22222222-2222-2222-2222-222222222222'::uuid,'Property creation template fixture','Source voice','{"allowed":true}'::jsonb,'{"garage":true}'::jsonb,'{"monday":"9-5"}'::jsonb from fixture union all select foreign_id,foreign_org,'Property creation foreign fixture','Private foreign voice','{}'::jsonb,'{}'::jsonb,'{}'::jsonb from fixture;
insert into public.property_contacts(property_id,contact_type,name,email,is_primary,special_instructions)select source_id,'primary','Template contact','template@example.test',true,'Original contact instruction'from fixture;
insert into public.integration_credentials(property_id,platform,status,account_id,credentials)select source_id,'google_ads','verified','never-copy-account','{"token":"not-a-real-provider-secret"}'::jsonb from fixture;
create function pg_temp.profile()returns jsonb language sql as $$select'{"name":"Property creation target fixture","propertyType":null,"address":{"street":"","city":"City only","state":"","zip":""},"websiteUrl":"https://example.test/target","additionalUrls":[],"unitCount":0,"yearBuilt":null,"amenities":[],"specialFeatures":[],"brandVoice":"","targetAudience":""}'::jsonb$$;
create function pg_temp.reject_creation_task()returns trigger language plpgsql as $$begin if new.property_id=(select target_id from fixture)then raise exception 'Fixture task storage failure';end if;return new;end$$;
do $$declare f fixture;v_preview jsonb;v_input jsonb;v_other jsonb;v_r jsonb;v_id uuid:=gen_random_uuid();v_complete_id uuid:=gen_random_uuid();v_baseline jsonb;v_count bigint;begin select *into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.property_creation_requests','SELECT')and not has_function_privilege('anon','public.create_property_from_setup(uuid,uuid,jsonb)','EXECUTE'),'creation receipts and native functions are private');
 perform pg_temp.check(public.read_property_creation_template(f.foreign_id,f.actor,'{"contacts":true,"connections":true,"guidance":true}')->>'state'='forbidden','template previews cannot cross organizations');
 v_preview:=public.read_property_creation_template(f.source_id,f.actor,'{"contacts":true,"connections":true,"guidance":true}');
 perform pg_temp.check(v_preview->>'state'='ready'and jsonb_array_length(v_preview->'snapshot'->'contacts')=1 and v_preview->'snapshot'->'guidance'->>'brandVoice'='Source voice','exact selected template data is reviewable');
 perform pg_temp.check(position('never-copy-account'in v_preview::text)=0 and position('not-a-real-provider-secret'in v_preview::text)=0 and position('verified'in v_preview::text)=0,'template plans include service intentions without account identity or secrets');
 v_input:=jsonb_build_object('profile',pg_temp.profile(),'template',jsonb_build_object('sourceId',f.source_id,'snapshotHash',v_preview->>'snapshotHash','flags',v_preview->'snapshot'->'flags','guidanceConfirmed',true));
 v_other:=jsonb_set(v_input,'{template,sourceId}',to_jsonb(f.foreign_id));v_r:=public.create_property_from_setup(f.target_id,f.actor,v_other);
 perform pg_temp.check(v_r->>'state'='forbidden'and not exists(select 1 from public.properties where id=f.target_id),'foreign template cannot create a partial target');
 v_other:=jsonb_set(v_input,'{template,guidanceConfirmed}','false');begin perform public.create_property_from_setup(f.target_id,f.actor,v_other);raise exception 'expected guidance review';exception when others then if sqlerrm='expected guidance review'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.properties where id=f.target_id),'copied property-specific guidance requires explicit applicability review');
 update public.properties set brand_voice='Revised source voice'where id=f.source_id;
 perform pg_temp.check(public.create_property_from_setup(f.target_id,f.actor,v_input)->>'state'='template_changed'and not exists(select 1 from public.properties where id=f.target_id),'changed template is held before creating anything');
 v_preview:=public.read_property_creation_template(f.source_id,f.actor,'{"contacts":true,"connections":true,"guidance":true}');v_input:=jsonb_set(v_input,'{template,snapshotHash}',v_preview->'snapshotHash');
 create trigger reject_creation_task before insert on public.onboarding_tasks for each row execute function pg_temp.reject_creation_task();begin perform public.create_property_from_setup(f.target_id,f.actor,v_input);raise exception 'expected task rollback';exception when others then if sqlerrm='expected task rollback'then raise;end if;end;drop trigger reject_creation_task on public.onboarding_tasks;
 perform pg_temp.check(not exists(select 1 from public.properties where id=f.target_id)and not exists(select 1 from public.property_creation_requests where id=f.target_id)and not exists(select 1 from public.shared_action_events where property_id=f.target_id),'task creation failure rolls back property, contacts, receipt and shared history');
 v_r:=public.create_property_from_setup(f.target_id,f.actor,v_input);
 perform pg_temp.check(v_r->>'state'='created'and v_r->>'propertyId'=f.target_id::text and v_r->'snapshot'->'profile'->'unitCount'='0','creation returns the durable target and preserves zero units');
 perform pg_temp.check((select org_id='22222222-2222-2222-2222-222222222222'and address->>'city'='City only'and not(settings?'timezone')and onboarding_completed_at is null and brand_voice='Revised source voice'and pet_policy='{"allowed":true}'from public.properties where id=f.target_id),'created property uses explicit facts, reviewed guidance and no guessed timezone');
 perform pg_temp.check((select count(*)=1 from public.property_contacts where property_id=f.target_id)and not exists(select 1 from public.property_contacts a join public.property_contacts b on a.id=b.id where a.property_id=f.source_id and b.property_id=f.target_id),'copied contacts use new target identities');
 perform pg_temp.check(not exists(select 1 from public.integration_credentials where property_id=f.target_id)and(select connection_requests->0->>'platform'='google_ads'and connection_requests->0->>'accountId'=''from public.property_setup_state where property_id=f.target_id),'creation plans never impersonate a connected provider');
 perform pg_temp.check((select count(*)=9 from public.onboarding_tasks where property_id=f.target_id)and(select count(*)=1 from public.shared_action_events where property_id=f.target_id and action='property.created'),'tasks and one creation action commit together');
 perform pg_temp.check((select position('template@example.test'in request::text)=0 and position('template@example.test'in result::text)=0 from public.shared_action_events where id=f.target_id),'shared creation event does not contain copied contact data');
 update public.properties set brand_voice='Changed after creation'where id=f.source_id;
 v_r:=public.create_property_from_setup(f.target_id,f.actor,v_input);perform pg_temp.check(v_r->>'state'='replayed'and(select count(*)=9 from public.onboarding_tasks where property_id=f.target_id),'lost-reply recovery survives later template edits without duplicate tasks');
 perform pg_temp.check(public.create_property_from_setup(f.target_id,f.actor,jsonb_set(v_input,'{profile,name}','"Different creation"'))->>'state'='request_conflict','a pending identity cannot silently become a second creation');
 perform pg_temp.check(public.read_property_creation(f.target_id,f.actor)->>'propertyId'=f.target_id::text,'pending request can be recovered without retained browser form text');
 v_baseline:=public.read_property_setup(f.target_id,f.actor);v_other:=(v_baseline->'snapshot')||jsonb_build_object('expectedHash',v_baseline->>'snapshotHash','reason','Finish reviewed property setup','completeOnboarding',true);
 v_r:=public.save_property_setup(v_complete_id,f.target_id,f.actor,v_other);
 perform pg_temp.check(v_r->>'state'='saved'and v_r->'setupCompleted'='true'and(select onboarding_completed_at is not null from public.properties where id=f.target_id),'setup completion and the reviewed final values commit together');
 perform pg_temp.check((select count(*)=2 from public.onboarding_tasks where property_id=f.target_id and status='completed')and(select count(*)=7 from public.onboarding_tasks where property_id=f.target_id and status<>'completed'),'completion marks actual facts/contact tasks, never unperformed knowledge or provider work');
 perform pg_temp.check((select action='property.onboarding.completed'from public.shared_action_events where id=v_complete_id)and public.save_property_setup(v_complete_id,f.target_id,f.actor,v_other)->>'state'='replayed','completion is recorded once and exact lost replies recover');
 perform pg_temp.check(public.save_property_setup(gen_random_uuid(),f.target_id,f.actor,v_other)->>'state'='already_completed','new completion attempts cannot rewrite a completed setup');
 v_r:=public.read_property_setup(f.target_id,f.actor,null,f.target_id);perform pg_temp.check(v_r->'selected'->>'kind'='created','creation history is distinguished from an edit to an existing property');
 update public.profiles set role=null where id=f.actor;
 perform pg_temp.check(public.create_property_from_setup(v_id,f.actor,jsonb_build_object('profile',pg_temp.profile(),'template',null))->>'state'='forbidden'and public.read_property_creation(f.target_id,f.actor)->>'state'='forbidden','creation and recovery require a current manager role');
 update public.profiles set role='admin'where id=f.actor;
 v_r:=public.create_property_from_setup(v_id,f.actor,jsonb_build_object('profile',pg_temp.profile()||'{"name":"Independent creation fixture"}','template',null));perform pg_temp.check(v_r->>'state'='created'and not exists(select 1 from public.property_contacts where property_id=v_id),'creation without a template does not fabricate contacts or source facts');
 v_baseline:=public.read_property_setup(v_id,f.actor);v_other:=(v_baseline->'snapshot')||jsonb_build_object('expectedHash',v_baseline->>'snapshotHash','reason','Cannot finish without a primary contact','completeOnboarding',true);
 begin perform public.save_property_setup(gen_random_uuid(),v_id,f.actor,v_other);raise exception 'expected primary contact';exception when others then if sqlerrm='expected primary contact'then raise;end if;end;
 perform pg_temp.check((select onboarding_completed_at is null from public.properties where id=v_id),'incomplete contact setup remains visibly unfinished');
 update public.profiles set org_id=null where id=f.actor;
 perform pg_temp.check(public.read_property_creation(f.target_id,f.actor)->>'state'='forbidden'and public.create_property_from_setup(f.target_id,f.actor,v_input)->>'state'='forbidden','creation replay rechecks current organization');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor;
end$$;
select count(*)as passed_assertions from checks;
rollback;
