begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,review_id uuid,response_id uuid,publication_id uuid);
insert into fixture values(gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),null,gen_random_uuid());
insert into public.properties(id,org_id,name) select property_id,'22222222-2222-2222-2222-222222222222','ReviewFlow publication rollback fixture' from fixture;
insert into public.reviews(id,property_id,platform,review_text,reviewer_name,rating,response_status) select review_id,property_id,'other','The pool was clean.','Publication fixture reviewer',5,'pending' from fixture;
create function pg_temp.approve_draft() returns uuid language plpgsql as $$declare f fixture;context jsonb;d public.review_responses;draft_id uuid:=gen_random_uuid();policy jsonb:='{"origin":"console","policyVersion":"reviewflow-policy-v1","policy":{"policyClass":"standard"},"textPolicy":{"passed":true,"violations":[]}}';result jsonb;begin
 select * into f from fixture;context:=public.reviewflow_response_context(f.property_id,f.actor_id,f.review_id);
 result:=public.commit_reviewflow_response_draft(draft_id,f.property_id,f.actor_id,jsonb_build_object('reviewId',f.review_id,'sourceVersion',context->'context'->'review'->'sourceVersion','contextHash',context->>'contextHash','responseSetHash',context->>'responseSetHash','replacePending',true,'tone','professional','reason','Reviewed exact source before publication','responseText','Thank you for sharing your experience with our community.'),policy);if result->>'state'<>'saved' then raise exception 'Draft fixture: %',result;end if;
 select * into d from public.review_responses where review_responses.id=draft_id;
 result:=public.decide_reviewflow_response(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('responseId',draft_id,'expectedVersion',d.version,'sourceVersion',d.source_version,'contextHash',d.context_hash,'contentHash',d.content_hash,'action','approve','reason','Manager reviewed exact approved text'),policy);if result->>'state'<>'saved' then raise exception 'Approval fixture: %',result;end if;
 update fixture set response_id=draft_id;return draft_id;
end$$;
create function pg_temp.prepare_input() returns jsonb language plpgsql as $$declare f fixture;d public.review_responses;t jsonb;begin select * into f from fixture;select * into d from public.review_responses where id=f.response_id;t:=public.reviewflow_publication_target(f.property_id,f.actor_id,f.review_id);return jsonb_build_object('responseId',d.id,'expectedVersion',d.version,'sourceVersion',d.source_version,'contextHash',d.context_hash,'contentHash',d.content_hash,'targetHash',t->>'targetHash','destinationUrl','https://example.invalid/review/fixture','replacePublished',true,'reason','Reviewed exact text and public destination');end$$;
create function pg_temp.prepare(id uuid default null,extra jsonb default '{}') returns jsonb language plpgsql as $$declare f fixture;begin select * into f from fixture;return public.request_reviewflow_manual_publication(coalesce(prepare.id,f.publication_id),f.property_id,f.actor_id,pg_temp.prepare_input()||extra);end$$;
create function pg_temp.outcome_input(decision text) returns jsonb language plpgsql as $$declare f fixture;run public.reviewflow_publications;begin select * into f from fixture;select * into run from public.reviewflow_publications where id=f.publication_id;return jsonb_build_object('publicationId',run.id,'expectedVersion',run.version,'decision',decision,'reason','Staff inspected exact response at its saved destination')||case decision when 'reported' then jsonb_build_object('confirmedExactText',true,'publishedAt',clock_timestamp(),'evidenceUrl','https://example.invalid/review/fixture#reply') when 'not_published' then '{"confirmedNotPublished":true}'::jsonb else '{}'::jsonb end;end$$;
select pg_temp.approve_draft();
do $$declare f fixture;payload jsonb;r jsonb;command uuid:=gen_random_uuid();begin select * into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.reviewflow_publications','select') and not has_function_privilege('authenticated','public.request_reviewflow_manual_publication(uuid,uuid,uuid,jsonb)','execute'),'publication evidence is private and recorded server-side');
 perform pg_temp.check(public.request_reviewflow_manual_publication(f.publication_id,f.property_id,gen_random_uuid(),pg_temp.prepare_input())->>'state'='manager_required','unknown actor cannot prepare publication');
 perform pg_temp.check(pg_temp.prepare(null,'{"expectedVersion":99}')->>'state'='stale_response','publication requires exact response version');
 perform pg_temp.check(pg_temp.prepare(null,jsonb_build_object('targetHash',repeat('0',64)))->>'state'='stale_destination','publication requires reviewed destination history');
 payload:=pg_temp.prepare_input();r:=public.request_reviewflow_manual_publication(f.publication_id,f.property_id,f.actor_id,payload);
 perform pg_temp.check(r->>'state'='saved' and public.request_reviewflow_manual_publication(f.publication_id,f.property_id,f.actor_id,payload)->>'state'='replayed','lost preparation reply cannot create another handoff');
 perform pg_temp.check(pg_temp.prepare(gen_random_uuid())->>'state'='busy','concurrent publication for the same review is held');
 perform pg_temp.check((select count(*)=1 from public.reviewflow_publications where property_id=f.property_id),'one manual handoff is retained');
 perform pg_temp.check((select status='approved' and posted_at is null from public.review_responses where id=f.response_id),'preparation is not publication');
 perform pg_temp.check((select a.execution_status='executing' from public.reviewflow_publications p join public.shared_action_attempts a on a.id=p.attempt_id where p.id=f.publication_id),'pending manual handoff protects its approved text from replacement');
 begin update public.reviewflow_publications set response_text='Changed text' where id=f.publication_id;raise exception 'FAIL mutable publication';exception when raise_exception then if SQLERRM<>'Publication identity and approved text are immutable' then raise;end if;end;
 perform pg_temp.check(true,'frozen publication text is immutable');
 r:=public.review_reviewflow_manual_publication(command,f.property_id,f.actor_id,pg_temp.outcome_input('uncertain'));
 perform pg_temp.check(r->>'state'='saved' and(select state='held' from public.reviewflow_publications where id=f.publication_id),'uncertain outcome stays open for reconciliation');
 perform pg_temp.check((select a.execution_status='failed' from public.reviewflow_publications p join public.shared_action_attempts a on a.id=p.attempt_id where p.id=f.publication_id),'uncertainty cannot silently enable another write');
 command:=gen_random_uuid();payload:=pg_temp.outcome_input('not_published');
 perform pg_temp.check(public.review_reviewflow_manual_publication(command,f.property_id,f.actor_id,payload)->>'state'='saved' and public.review_reviewflow_manual_publication(command,f.property_id,f.actor_id,payload)->>'state'='replayed','reviewed not-published outcome recovers a lost reply');
 perform pg_temp.check((select state='cancelled' and report->>'kind'='staff_reported_not_published' from public.reviewflow_publications where id=f.publication_id),'cancellation retains the actual staff attestation');
 perform pg_temp.check((select a.execution_status='approved_pending_execution' from public.reviewflow_publications p join public.shared_action_attempts a on a.id=p.attempt_id where p.id=f.publication_id),'confirmed non-publication returns to explicit approval waiting state');
end$$;
update fixture set publication_id=gen_random_uuid();
select pg_temp.prepare();
do $$declare f fixture;payload jsonb;command uuid:=gen_random_uuid();begin select * into f from fixture;
 update public.reviews set review_text='The source changed after the manual handoff.' where id=f.review_id;
 perform pg_temp.check((select source_version=2 and response_status='pending' from public.reviews where id=f.review_id),'a changed source does not retain a current approved or posted status');
 payload:=pg_temp.outcome_input('reported');
 begin perform public.review_reviewflow_manual_publication(command,f.property_id,f.actor_id,payload||'{"confirmedExactText":false}');raise exception 'FAIL missing exact text';exception when raise_exception then if SQLERRM<>'Confirm exact posted text and provide its public evidence link' then raise;end if;end;
 perform pg_temp.check(true,'manual publication requires an explicit exact-text attestation');
 perform pg_temp.check(public.review_reviewflow_manual_publication(command,f.property_id,f.actor_id,payload)->>'state'='saved' and public.review_reviewflow_manual_publication(command,f.property_id,f.actor_id,payload)->>'state'='replayed','staff report and associated response state recover once');
 perform pg_temp.check((select state='reported' and report->'verifiedByProvider'='false'::jsonb and report->'sourceChanged'='true'::jsonb from public.reviewflow_publications where id=f.publication_id),'real reported publication remains attributed to its earlier source without claiming verification');
 perform pg_temp.check((select status='posted' and posting_mode='manual_confirmed' and posted_by=f.actor_id from public.review_responses where id=f.response_id),'response retains staff publication evidence');
 perform pg_temp.check((select response_status='pending' from public.reviews where id=f.review_id),'reporting an earlier-source response does not mark the new source answered');
 perform pg_temp.check((select status='triaged' and resolved_at is null from public.reputation_cases where review_id=f.review_id),'publication does not resolve resident staff work');
 begin update public.reviewflow_publications set report='{}' where id=f.publication_id;raise exception 'FAIL mutable report';exception when raise_exception then if SQLERRM<>'Closed publication evidence is immutable' then raise;end if;end;
 perform pg_temp.check(true,'reported outcome cannot be rewritten');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='review.publication.reported'),'staff report records one semantic outcome');
end$$;
select pg_temp.approve_draft();
update fixture set publication_id=gen_random_uuid();
do $$declare f fixture;r jsonb;begin select * into f from fixture;
 perform pg_temp.check(pg_temp.prepare(null,'{"replacePublished":false}')->>'state'='replacement_review_required','replacing an existing published response requires reviewed intent');
 -- A conflicting activity event forces completion to fail without a global trigger.
 r:=public.append_shared_action_event(f.publication_id,f.publication_id,f.property_id,f.actor_id,'reviewflow','review.publication.prepared','server_confirmed','succeeded','{"fixture":"conflicting receipt"}',null,null,'{}','{}');
 perform pg_temp.check(r->>'state'='recorded','isolated conflicting receipt is saved for rollback verification');
 begin perform pg_temp.prepare();raise exception 'FAIL missing atomic evidence';exception when raise_exception then if SQLERRM<>'Review decision history could not be saved' then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.reviewflow_publications where id=f.publication_id) and not exists(select 1 from public.reviewflow_commands where id=f.publication_id),'failed history rolls back the publication and its command');
 perform pg_temp.check((select a.execution_status='approved_pending_execution' from public.review_responses d join public.shared_action_attempts a on a.id=d.shared_action_attempt_id where d.id=f.response_id),'failed publication history preserves the prior approval');
end$$;
select count(*) as passed_assertions from checks;
rollback;
