begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,review_id uuid,response_id uuid,publication_id uuid);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),null,gen_random_uuid());
insert into public.properties(id,org_id,name) select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'ReviewFlow overview rollback fixture' from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'ReviewFlow other overview rollback fixture' from fixture;
insert into public.reviews(property_id,platform,platform_review_id,review_text,review_date,created_at) select property_id,'other','overview-'||n,'Unrated saved review',now()-interval '2 days',now()-interval '1 day' from fixture cross join generate_series(1,1005)n;
insert into public.reviews(id,property_id,platform,platform_review_id,review_text,created_at) select review_id,property_id,'other','old-urgent','An older urgent source',now()-interval '2 years' from fixture;
insert into public.review_analyses(review_id,property_id,source_version,analysis_version,taxonomy_version,model,prompt_version,status,sentiment,topics,is_urgent) select r.id,r.property_id,r.source_version,1,'multifamily-v1','fixture','analysis-v3','completed','negative','["maintenance","maintenance"]',r.id=f.review_id from public.reviews r join fixture f on f.property_id=r.property_id where r.platform_review_id in('overview-1','overview-2','overview-3','old-urgent');
insert into public.review_analyses(review_id,property_id,source_version,analysis_version,taxonomy_version,model,prompt_version,status,sentiment,topics) select r.id,r.property_id,r.source_version,2,'multifamily-v1','fixture','analysis-v3','manual_review_required','negative','["habitability"]' from public.reviews r join fixture f on f.property_id=r.property_id where r.platform_review_id='overview-2';
update public.reviews set review_text='Changed current source' where platform_review_id='overview-3' and property_id=(select property_id from fixture);
insert into public.reputation_cases(property_id,review_id,status,priority) select r.property_id,r.id,case when platform_review_id='overview-5' then 'resolved' else 'open' end,'medium' from public.reviews r join fixture f on f.property_id=r.property_id where platform_review_id in('overview-4','overview-5');
update public.reviews set response_status='posted' where platform_review_id='overview-4' and property_id=(select property_id from fixture);

do $$declare f fixture;s jsonb;q jsonb;b jsonb;cursor_id uuid;begin select * into f from fixture;
 perform pg_temp.check(not has_function_privilege('authenticated','public.read_reviewflow_statistics(uuid,uuid,integer)','execute') and not has_function_privilege('authenticated','public.reviewflow_recovery_rows(uuid)','execute'),'service read boundaries keep private job evidence out of direct clients');
 perform pg_temp.check(public.read_reviewflow_statistics(f.property_id,gen_random_uuid(),0)->>'state'='forbidden' and public.read_reviewflow_queue(f.property_id,gen_random_uuid())->>'state'='forbidden' and public.read_reviewflow_recovery(f.property_id,gen_random_uuid())->>'state'='forbidden','all overview reads recheck current property membership');
 s:=public.read_reviewflow_statistics(f.property_id,f.actor_id,0)->'stats';
 perform pg_temp.check(s->>'totalReviews'='1006','statistics count all saved reviews beyond REST page caps');
 perform pg_temp.check(s->'avgRating'='null'::jsonb and s->>'ratedReviews'='0','unrated sources never become a fabricated zero average');
 perform pg_temp.check(s->'analysisCoverage'='{"current":2,"staffReview":1,"unclassified":1003}'::jsonb,'analysis coverage excludes stale and superseded completed analyses');
 perform pg_temp.check(s->'sentimentCounts'->>'negative'='2' and s->'topTopics'->0->>'count'='2','sentiment and topics use current classifications and deduplicate each review');
 perform pg_temp.check(s->'responseEvidence'='{"staffReported":0,"legacyUnverified":1,"providerConfirmed":0}'::jsonb,'legacy posted scalars are not provider verification');
 perform pg_temp.check(public.read_reviewflow_statistics(f.property_id,f.actor_id,90)->'stats'->>'totalReviews'='1005','statistics honor review dates and disclosed import-date fallback');
 perform pg_temp.check(public.read_reviewflow_statistics(f.other_property,f.actor_id,0)->'stats'->'responseRate'='null'::jsonb,'an empty property has no invented response rate');
 q:=public.read_reviewflow_queue(f.property_id,f.actor_id);
 perform pg_temp.check(q->>'total'='1006' and q->>'actionable'='1006','full queues include all review and unresolved case work');
 select value into b from jsonb_array_elements(q->'buckets') where value->>'id'='high_risk';
 perform pg_temp.check(b->>'total'='1' and b->'items'->0->>'id'=f.review_id::text,'old urgent work outside the former first200 rows stays visible');
 perform pg_temp.check((select bucket='remediation' from public.reviewflow_queue_members(f.property_id) where review_id=(select id from public.reviews where property_id=f.property_id and platform_review_id='overview-4')),'posting a response does not complete an open staff case');
 perform pg_temp.check((select bucket='needs_attention' from public.reviewflow_queue_members(f.property_id) where review_id=(select id from public.reviews where property_id=f.property_id and platform_review_id='overview-5')),'a resolved case does not answer its pending response');
 select value into b from jsonb_array_elements(q->'buckets') where value->>'id'='needs_attention';cursor_id:=(b->>'nextCursor')::uuid;
 perform pg_temp.check(b->>'total'='1004' and jsonb_array_length(b->'items')=10 and cursor_id is not null,'priority queues expose exact totals with bounded pages');
 s:=public.read_reviewflow_queue(f.property_id,f.actor_id,'needs_attention',cursor_id);
 perform pg_temp.check(s->>'sourceHash'=q->>'sourceHash' and jsonb_array_length(s->'buckets'->0->'items')=10 and not exists(select 1 from jsonb_array_elements(s->'buckets'->0->'items')n join jsonb_array_elements(b->'items')o on n->>'id'=o->>'id'),'unchanged queue pages have a stable workload hash and no overlap');
 perform pg_temp.check(public.read_reviewflow_queue(f.other_property,f.actor_id,'needs_attention',cursor_id)->>'state'='stale_cursor','queue cursors cannot cross properties');
 update public.reviews set response_status='skipped' where id=cursor_id;
 perform pg_temp.check(public.read_reviewflow_queue(f.property_id,f.actor_id,'needs_attention',cursor_id)->>'state'='stale_cursor','closed or moved cursor anchors require a reload');
 perform pg_temp.check(public.read_reviewflow_queue(f.property_id,f.actor_id)->>'sourceHash'<>q->>'sourceHash','changed membership has a new workload hash');
end$$;
create function pg_temp.approve_draft() returns uuid language plpgsql as $$declare f fixture;context jsonb;d public.review_responses;draft_id uuid:=gen_random_uuid();policy jsonb:='{"origin":"console","policyVersion":"reviewflow-policy-v1","policy":{"policyClass":"standard"},"textPolicy":{"passed":true,"violations":[]}}';result jsonb;begin
 select * into f from fixture;context:=public.reviewflow_response_context(f.property_id,f.actor_id,f.review_id);
 result:=public.commit_reviewflow_response_draft(draft_id,f.property_id,f.actor_id,jsonb_build_object('reviewId',f.review_id,'sourceVersion',context->'context'->'review'->'sourceVersion','contextHash',context->>'contextHash','responseSetHash',context->>'responseSetHash','replacePending',true,'tone','professional','reason','Reviewed exact source before publication','responseText','Thank you for sharing your experience with our community.'),policy);if result->>'state'<>'saved' then raise exception 'Draft fixture: %',result;end if;
 select * into d from public.review_responses where review_responses.id=draft_id;
 result:=public.decide_reviewflow_response(gen_random_uuid(),f.property_id,f.actor_id,jsonb_build_object('responseId',draft_id,'expectedVersion',d.version,'sourceVersion',d.source_version,'contextHash',d.context_hash,'contentHash',d.content_hash,'action','approve','reason','Manager reviewed exact approved text'),policy);if result->>'state'<>'saved' then raise exception 'Approval fixture: %',result;end if;
 update fixture set response_id=draft_id;return draft_id;
end$$;
create function pg_temp.prepare_input() returns jsonb language plpgsql as $$declare f fixture;d public.review_responses;t jsonb;begin select * into f from fixture;select * into d from public.review_responses where id=f.response_id;t:=public.reviewflow_publication_target(f.property_id,f.actor_id,f.review_id);return jsonb_build_object('responseId',d.id,'expectedVersion',d.version,'sourceVersion',d.source_version,'contextHash',d.context_hash,'contentHash',d.content_hash,'targetHash',t->>'targetHash','destinationUrl','https://example.invalid/review/fixture','replacePublished',true,'reason','Reviewed exact text and public destination');end$$;
create function pg_temp.prepare(id uuid default null,extra jsonb default '{}') returns jsonb language plpgsql as $$declare f fixture;begin select * into f from fixture;return public.request_reviewflow_manual_publication(coalesce(prepare.id,f.publication_id),f.property_id,f.actor_id,pg_temp.prepare_input()||extra);end$$;
create function pg_temp.outcome_input(decision text) returns jsonb language plpgsql as $$declare f fixture;run public.reviewflow_publications;begin select * into f from fixture;select * into run from public.reviewflow_publications where id=f.publication_id;return jsonb_build_object('publicationId',run.id,'expectedVersion',run.version,'decision',decision,'reason','Staff inspected exact response at its saved destination')||case decision when 'reported' then jsonb_build_object('confirmedExactText',true,'publishedAt',clock_timestamp(),'evidenceUrl','https://example.invalid/review/fixture#reply') when 'not_published' then '{"confirmedNotPublished":true}'::jsonb else '{}'::jsonb end;end$$;
do $$declare f fixture;r jsonb;s jsonb;old_hash text;old_cursor text;begin select * into f from fixture;
 perform pg_temp.approve_draft();perform pg_temp.prepare();
 r:=public.read_reviewflow_recovery(f.property_id,f.actor_id);perform pg_temp.check(r->>'total'='1' and r->'items'->0->>'kind'='manual_handoff' and r->'items'->0->>'reviewId'=f.review_id::text,'manual handoff recovery points to its full review history');
 perform public.review_reviewflow_manual_publication(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.outcome_input('uncertain'));
 r:=public.read_reviewflow_recovery(f.property_id,f.actor_id);perform pg_temp.check(r->>'total'='1' and r->'items'->0->>'kind'='publication_uncertain','uncertain manual publication remains visible without a duplicate legacy failure');
 perform public.review_reviewflow_manual_publication(gen_random_uuid(),f.property_id,f.actor_id,pg_temp.outcome_input('reported'));
 s:=public.read_reviewflow_statistics(f.property_id,f.actor_id,0)->'stats';perform pg_temp.check(s->'responseEvidence'->>'staffReported'='1' and s->'responseEvidence'->>'providerConfirmed'='0','a saved manual publication is attributed to staff without claiming provider readback');
 perform pg_temp.check(public.read_reviewflow_recovery(f.property_id,f.actor_id)->>'total'='0','reported handoff leaves the recovery queue');
 for n in 1..25 loop
  insert into public.reviews(property_id,platform,platform_review_id,review_text)values(f.property_id,'other','legacy-approved-'||n,'A legacy approval waiting for attention')returning id into f.review_id;update fixture set review_id=f.review_id;perform pg_temp.approve_draft();
  update public.review_responses set approved_at=now()-interval '2 days' where id=(select response_id from fixture);
 end loop;
 r:=public.read_reviewflow_recovery(f.property_id,f.actor_id);old_hash:=r->>'sourceHash';old_cursor:=r->>'nextCursor';
 perform pg_temp.check(r->>'total'='25' and jsonb_array_length(r->'items')=20 and old_cursor is not null,'recovery counts the whole workload and pages beyond twenty');
 s:=public.read_reviewflow_recovery(f.property_id,f.actor_id,old_cursor);
 perform pg_temp.check(jsonb_array_length(s->'items')=5 and s->'nextCursor'='null'::jsonb and s->>'sourceHash'=old_hash and not exists(select 1 from jsonb_array_elements(s->'items')n join jsonb_array_elements(r->'items')o on n->>'id'=o->>'id'),'the next recovery page is complete, stable and nonoverlapping');
 perform pg_temp.check(public.read_reviewflow_recovery(f.other_property,f.actor_id,old_cursor)->>'state'='stale_cursor','recovery cursors cannot cross properties');
 -- Keep the cursor fixture approved: generated UUID ordering can otherwise select the same row for both cases.
 update public.review_responses set status='posted',posting_mode='provider_api',posted_at=now(),platform_response_id='unqualified-legacy-id' where id=(select id from public.review_responses where property_id=f.property_id and status='approved' and id<>split_part(old_cursor,':',2)::uuid order by id limit 1);
 r:=public.read_reviewflow_recovery(f.property_id,f.actor_id);
 perform pg_temp.check(r->'counts'->>'legacy_publication'='1' and r->>'sourceHash'<>old_hash,'legacy provider IDs alone do not count as qualified readback');
 update public.review_responses set status='rejected' where id=split_part(old_cursor,':',2)::uuid;
 perform pg_temp.check(public.read_reviewflow_recovery(f.property_id,f.actor_id,old_cursor)->>'state'='stale_cursor','closed recovery anchors require reload');
end$$;
select count(*) as passed_assertions from checks;
rollback;
