begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,actor_id uuid,review_id uuid,as_of timestamptz,report_id uuid,source jsonb,input jsonb,result jsonb);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),date_trunc('milliseconds',now()),gen_random_uuid(),null,null,null);
insert into public.properties(id,org_id,name) select property_id,'22222222-2222-2222-2222-222222222222'::uuid,'ReviewFlow insights rollback fixture' from fixture union all select other_property,'22222222-2222-2222-2222-222222222222'::uuid,'ReviewFlow insights other rollback fixture' from fixture;
insert into public.reviews(property_id,platform,platform_review_id,review_text,review_date,created_at) select property_id,'other','insight-'||n,'Saved fixture review',as_of-interval '2 days',as_of-interval '1 day' from fixture cross join generate_series(1,1005)n;
insert into public.reviews(id,property_id,platform,platform_review_id,review_text,created_at) select review_id,property_id,'other','undated','Undated fixture review',as_of-interval '1 day' from fixture;
insert into public.reviews(property_id,platform,platform_review_id,review_text,review_date,created_at) select property_id,'other','old-import','Old source imported recently',as_of-interval '1 year',as_of-interval '1 day' from fixture union all select property_id,'other','future-review','Future source',as_of+interval '1 day',as_of-interval '1 day' from fixture;
insert into public.review_analyses(review_id,property_id,source_version,analysis_version,taxonomy_version,model,prompt_version,status,sentiment,issue_domains) select r.id,r.property_id,r.source_version,1,'multifamily-v1','fixture','analysis-v3','completed','negative','["maintenance"]' from public.reviews r join fixture f on f.property_id=r.property_id where r.platform_review_id in('insight-1','insight-2','insight-3','undated');
insert into public.review_analyses(review_id,property_id,source_version,analysis_version,taxonomy_version,model,prompt_version,status,sentiment,issue_domains) select r.id,r.property_id,r.source_version,2,'multifamily-v1','fixture','analysis-v3','manual_review_required','negative','["habitability"]' from public.reviews r join fixture f on f.property_id=r.property_id where r.platform_review_id='insight-2';
update public.reviews set review_text='Changed current source' where platform_review_id='insight-3' and property_id=(select property_id from fixture);
insert into public.reputation_cases(property_id,review_id,status,priority,issue_domains,created_at) select property_id,review_id,'open','high','["maintenance"]',as_of-interval '2 years' from fixture;

do $$declare f fixture;s jsonb;begin select * into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.reviewflow_insight_reports','select') and not has_function_privilege('authenticated','public.read_reviewflow_insight_source(uuid,uuid,integer,timestamptz)','execute'),'raw report evidence and source reads are server-private');
 perform pg_temp.check(public.read_reviewflow_insight_source(f.property_id,gen_random_uuid(),90,f.as_of)->>'state'='forbidden','source reads require current property membership');
 s:=public.read_reviewflow_insight_source(f.property_id,f.actor_id,90,f.as_of);
 perform pg_temp.check(s->>'state'='ready' and jsonb_array_length(s->'source'->'reviews')=1006,'full snapshot exceeds the former1000 cap and excludes old imported and future dated reviews');
 perform pg_temp.check(s->'source'->'coverage'->>'dateFallbackReviews'='1','missing review dates use the disclosed import-date fallback');
 perform pg_temp.check(jsonb_array_length(s->'source'->'analyses')=2,'only latest completed analyses of exact current sources are usable');
 perform pg_temp.check(s->'source'->'coverage'->>'staffReviewAnalyses'='1','a newer staff-review result prevents using its older completed analysis');
 perform pg_temp.check(jsonb_array_length(s->'source'->'cases')=1,'long-standing open cases remain visible outside the review-date window');
 perform pg_temp.check(s=public.read_reviewflow_insight_source(f.property_id,f.actor_id,90,f.as_of),'unchanged source snapshot and hash are stable');
 update fixture set source=s,input=jsonb_build_object('windowDays',90,'asOf',f.as_of,'sourceHash',s->>'sourceHash','reason','Reviewed exact window and evidence'),result=jsonb_build_object('insightsVersion','reviewflow-insights-v2','windowDays',90,'totalReviews',1006,'classifiedReviews',2,'clusters','[]'::jsonb);
end$$;

do $$declare f fixture;r jsonb;collision uuid:=gen_random_uuid();begin select * into f from fixture;
 perform public.append_shared_action_event(collision,collision,f.property_id,f.actor_id,'reviewflow','review.analysis.requested','server_confirmed','succeeded','{}',null,null,'{}');
 begin perform public.save_reviewflow_insight_report(collision,f.property_id,f.actor_id,f.input,f.result);raise exception 'Expected action collision';exception when others then if sqlerrm='Expected action collision' then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.reviewflow_insight_reports where id=collision),'failed semantic action saving rolls back the report');
 r:=public.save_reviewflow_insight_report(f.report_id,f.property_id,f.actor_id,f.input,f.result);perform pg_temp.check(r->>'state'='saved','report and exact evidence save atomically');
 perform pg_temp.check(public.save_reviewflow_insight_report(f.report_id,f.property_id,f.actor_id,f.input,'{}')->>'state'='replayed','lost reply reuses the saved report without recomputation');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where id=f.report_id and action='review.insights.saved'),'saved report has one confirmed human decision');
 perform pg_temp.check((select source_snapshot=f.source->'source' and source_hash=f.source->>'sourceHash' from public.reviewflow_insight_reports where id=f.report_id),'full private source evidence is retained');
 begin update public.reviewflow_insight_reports set result='{}' where id=f.report_id;raise exception 'Expected immutable report';exception when others then if sqlerrm='Expected immutable report' then raise;end if;end;
 perform pg_temp.check((select result=f.result from public.reviewflow_insight_reports where id=f.report_id),'prior report cannot be silently rewritten');
 perform pg_temp.check(public.save_reviewflow_insight_report(f.report_id,f.other_property,f.actor_id,f.input,f.result)->>'state'='request_conflict','a stable report identity cannot move to another property');
 update public.reviews set review_text='Source changed after preview' where id=f.review_id;
 perform pg_temp.check(public.save_reviewflow_insight_report(gen_random_uuid(),f.property_id,f.actor_id,f.input,f.result)->>'state'='stale_source','changed source cannot be saved under the reviewed preview hash');
 perform pg_temp.check(public.save_reviewflow_insight_report(f.report_id,f.property_id,f.actor_id,f.input,'{}')->>'state'='replayed','existing report recovery survives later source changes');
end$$;
do $$declare f fixture;begin select * into f from fixture;
 update public.reviews set review_text=$txt$Literal 100% _ * commas, "quotes" back\slash$txt$ where property_id=f.property_id and platform_review_id='insight-4';
 perform pg_temp.check((select bool_and((select count(*) from public.search_reviewflow_reviews(f.property_id,q))=1) from(values('100%'),('_'),('*'),('commas,'),('"quotes"'),(E'back\\slash'))queries(q)),'full-property search treats wildcards, punctuation and backslashes literally');
 perform pg_temp.check((select count(*)=0 from public.search_reviewflow_reviews(f.other_property,'Saved fixture review')),'search never mixes another property into results');
 perform pg_temp.check((select prosecdef=false from pg_proc where oid='public.search_reviewflow_reviews(uuid,text)'::regprocedure),'search retains caller RLS rather than elevating database access');
 perform pg_temp.check(not has_function_privilege('anon','public.search_reviewflow_reviews(uuid,text)','execute') and has_function_privilege('authenticated','public.search_reviewflow_reviews(uuid,text)','execute'),'only signed-in read paths can call review search');
end$$;
select count(*) as passed_assertions from checks;
rollback;
