begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,actor_id uuid,review_id uuid,request_id uuid,claim uuid,model_input jsonb,receipt jsonb,classification jsonb);
insert into fixture values(gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid(),null,null,null,null);
insert into public.properties(id,org_id,name)select property_id,'22222222-2222-2222-2222-222222222222','ReviewFlow analysis rollback fixture' from fixture;
insert into public.reviews(id,property_id,platform,platform_review_id,review_text,reviewer_name,rating,response_status)select review_id,property_id,'other','analysis-fixture','The pool was clean.','Fixture reviewer',5,'pending' from fixture;
update fixture set model_input=jsonb_build_object('source',jsonb_build_object('reviewText','The pool was clean.','rating',5,'platform','other','reviewerName','Fixture reviewer'),'model','fixture-model','systemPrompt','Fixture system prompt','userPrompt','The pool was clean.','promptVersion','analysis-v3','taxonomyVersion','multifamily-v1','policyVersion','reviewflow-policy-v1'),classification=jsonb_build_object('sentiment','positive','sentimentScore',0.8,'topics',array['amenities'],'journeyStage','residency','issueDomains',array['amenities'],'severity','low','riskClass','routine','policyClass','standard','isUrgent',false,'confidence',0.9,'summary','The reviewer liked the clean pool.','recommendedAction','Thank the reviewer.','evidence',jsonb_build_array(jsonb_build_object('claim','Clean pool','quote','The pool was clean.')),'policy',jsonb_build_object('requiresHumanReview',false,'autoActionEligible',true,'flags','[]'::jsonb),'provenance',jsonb_build_object('model','fixture-model','promptVersion','analysis-v3','taxonomyVersion','multifamily-v1','policyVersion','reviewflow-policy-v1'),'usage',jsonb_build_object('model','fixture-model','promptTokens',40,'completionTokens',50));
update fixture set receipt=jsonb_build_object('status','received','providerId','fixture-completion','content',(classification-'policy'-'provenance'-'usage')::text,'usage',classification->'usage');
create function pg_temp.start(id uuid default null,review_id uuid default null) returns jsonb language plpgsql as $$declare f fixture;r public.reviews;input jsonb;begin select * into f from fixture;select * into r from public.reviews source_row where source_row.id=coalesce(start.review_id,f.review_id);input:=jsonb_set(f.model_input,'{source}',jsonb_build_object('reviewText',r.review_text,'rating',r.rating,'platform',r.platform,'reviewerName',r.reviewer_name));return public.begin_reviewflow_analysis(coalesce(start.id,f.request_id),f.property_id,f.actor_id,jsonb_build_object('reviewId',r.id,'sourceVersion',r.source_version),input);end$$;
create function pg_temp.apply(id uuid default null) returns jsonb language plpgsql as $$declare f fixture;run public.reviewflow_analysis_requests;begin select * into f from fixture;select * into run from public.reviewflow_analysis_requests request_row where request_row.id=coalesce(apply.id,f.request_id);return public.apply_reviewflow_analysis(run.id,f.property_id,f.actor_id,jsonb_build_object('resultHash',run.result_hash,'analysis',f.classification));end$$;
do $$declare f fixture;r jsonb;begin select * into f from fixture;
 perform pg_temp.check(not has_table_privilege('authenticated','public.reviewflow_analysis_requests','select') and not has_function_privilege('authenticated','public.claim_reviewflow_analysis(uuid)','execute'),'browser roles cannot read private results or claim model work');
 perform pg_temp.check(public.begin_reviewflow_analysis(f.request_id,f.property_id,gen_random_uuid(),'{}','{}')->>'state'='forbidden','unscoped analysis request is denied');
 perform pg_temp.check(public.begin_reviewflow_analysis(f.request_id,f.property_id,f.actor_id,jsonb_build_object('reviewId',f.review_id,'sourceVersion',2),f.model_input)->>'state'='stale_source','stale source cannot queue analysis');
 r:=pg_temp.start();perform pg_temp.check(r->>'state'='queued','request, context and job save before any model intent');
 perform pg_temp.check(pg_temp.start()->>'state'='queued' and pg_temp.start(gen_random_uuid())->>'state'='busy','lost start reply and competing request cannot create duplicate active work');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='review.analysis.requested'),'one recorded request after retries');
 perform pg_temp.check((select model_input=f.model_input and source_snapshot->>'review_text'='The pool was clean.' from public.reviewflow_analysis_requests where id=f.request_id),'exact review and model contract remain saved');
 r:=public.claim_reviewflow_analysis(f.request_id);update fixture set claim=(r->>'claimToken')::uuid;
 perform pg_temp.check(r->>'state'='invoke_once' and public.claim_reviewflow_analysis(f.request_id)->>'state'='running','model starts once even after a lost claim reply');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='review.analysis.started'),'model intent records truthful worker origin');
end$$;
do $$declare f fixture;r jsonb;begin select * into f from fixture;
 perform pg_temp.check(public.record_reviewflow_analysis_result(f.request_id,gen_random_uuid(),f.receipt)->>'state'='claim_mismatch','unowned result cannot change request');
 r:=public.record_reviewflow_analysis_result(f.request_id,f.claim,f.receipt);perform pg_temp.check(r->>'requestState'='result_ready' and not exists(select 1 from public.review_analyses where review_id=f.review_id),'raw model result persists before classification changes');
 perform pg_temp.check(public.record_reviewflow_analysis_result(f.request_id,f.claim,f.receipt)->>'state'='replayed','lost result-save reply safely replays exact evidence');
 perform pg_temp.check(public.record_reviewflow_analysis_result(f.request_id,f.claim,f.receipt||'{"providerId":"different"}')->>'state'='result_conflict','stored model receipt cannot be rewritten');
 r:=pg_temp.apply();perform pg_temp.check(r->>'state'='saved' and r->>'analysisId'=f.request_id::text,'validated model result applies to saved analysis');
 perform pg_temp.check((select source_version=1 and sentiment='positive' and response_status='pending' from public.reviews where id=f.review_id),'analysis cannot silently enable automatic public responses');
 perform pg_temp.check((select status='triaged' and priority='low' from public.reputation_cases where review_id=f.review_id),'review and triaged case save consistently');
 perform pg_temp.check((select lifecycle_status='succeeded' and progress=100 from public.shared_jobs where id=f.request_id),'job completes only after atomic application');
 perform pg_temp.check(pg_temp.apply()->>'state'='replayed' and(select count(*)=1 from public.review_analyses where review_id=f.review_id),'recovery never duplicates analysis versions');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where property_id=f.property_id and action='review.analysis.completed') and (select count(*)=1 from public.reputation_case_events where property_id=f.property_id and event_type='analysis_recorded'),'case and shared completion evidence are recorded once');
 perform pg_temp.check(not exists(select 1 from public.shared_action_events where property_id=f.property_id and row_to_json(shared_action_events)::text like '%The pool was clean.%'),'raw review text is kept out of the general activity event');
end$$;
do $$declare f fixture;r jsonb;rid uuid:=gen_random_uuid();claim uuid;decision uuid:=gen_random_uuid();payload jsonb;begin select * into f from fixture;
 perform pg_temp.start(rid);r:=public.claim_reviewflow_analysis(rid);claim:=(r->>'claimToken')::uuid;
 payload:=jsonb_build_object('analysisRequestId',rid,'expectedVersion',2,'reason','Stop this simulated work');
 perform pg_temp.check(public.control_reviewflow_analysis(gen_random_uuid(),f.property_id,f.actor_id,payload||'{"expectedVersion":1}')->>'state'='stale_request','stale stop cannot overwrite newer request state');
 perform pg_temp.check(public.control_reviewflow_analysis(decision,f.property_id,f.actor_id,payload)->>'state'='saved','operator can stop started analysis');
 perform pg_temp.check(public.control_reviewflow_analysis(decision,f.property_id,f.actor_id,payload)->>'state'='replayed','lost stop reply recovers exact recorded decision');
 perform pg_temp.check(public.record_reviewflow_analysis_result(rid,claim,f.receipt)->>'requestState'='stopped','late raw result remains private after stop');
 perform pg_temp.check(pg_temp.apply(rid)->>'state'='stopped' and not exists(select 1 from public.review_analyses where id=rid and id<>f.request_id),'stopped request cannot apply its late result');
end$$;
do $$declare f fixture;r jsonb;rid uuid:=gen_random_uuid();claim uuid;begin select * into f from fixture;
 perform pg_temp.start(rid);r:=public.claim_reviewflow_analysis(rid);claim:=(r->>'claimToken')::uuid;perform public.record_reviewflow_analysis_result(rid,claim,f.receipt);
 update public.reviews set review_text='The pool has closed.' where id=f.review_id;
 perform pg_temp.check((select source_version=2 and sentiment is null and response_status='pending' from public.reviews where id=f.review_id),'changed source increments version and clears stale classification');
 perform pg_temp.check(pg_temp.apply(rid)->>'state'='held','late analysis of an earlier source cannot change the current review');
 perform pg_temp.check((select count(*)=1 from public.review_analyses where review_id=f.review_id),'earlier immutable analysis survives a source change');
 rid:=gen_random_uuid();perform pg_temp.start(rid);update public.reviews set review_text='The pool was clean.' where id=f.review_id;
 perform pg_temp.check(public.claim_reviewflow_analysis(rid)->>'state'='held','source changes before claiming prevent any model intent');
end$$;
create function pg_temp.fail_analysis_history() returns trigger language plpgsql as $$begin if new.action='review.analysis.completed' and new.phase='succeeded' then raise exception 'Fixture analysis history failure';end if;return new;end$$;
create trigger analysis_fixture_failure before insert on public.shared_action_events for each row execute function pg_temp.fail_analysis_history();
do $$declare f fixture;r jsonb;rid uuid:=gen_random_uuid();begin select * into f from fixture;perform pg_temp.start(rid);r:=public.claim_reviewflow_analysis(rid);perform public.record_reviewflow_analysis_result(rid,(r->>'claimToken')::uuid,f.receipt);
 begin perform pg_temp.apply(rid);raise exception 'FAIL missing action';exception when raise_exception then if SQLERRM<>'Fixture analysis history failure' then raise;end if;end;
 perform pg_temp.check((select state='result_ready' and raw_result is not null from public.reviewflow_analysis_requests where id=rid) and not exists(select 1 from public.review_analyses where id=rid),'failed atomic application preserves raw result for recovery without another model');
 update fixture set request_id=rid;
end$$;
drop trigger analysis_fixture_failure on public.shared_action_events;
do $$declare f fixture;r jsonb;decision uuid:=gen_random_uuid();payload jsonb;begin select * into f from fixture;
 payload:=jsonb_build_object('analysisRequestId',f.request_id,'expectedVersion',3,'reason','Recover exact saved model result');
 perform pg_temp.check(public.request_reviewflow_analysis_recovery(decision,f.property_id,f.actor_id,payload)->>'state'='saved','saved result recovery has an explicit operator decision');
 perform pg_temp.check(pg_temp.apply()->>'state'='saved','recovery applies retained result after transient action failure');
 perform pg_temp.check(public.request_reviewflow_analysis_recovery(decision,f.property_id,f.actor_id,payload)->>'state'='replayed','lost recovery response replays the same decision');
 begin update public.review_analyses set summary='replacement' where id=f.request_id;raise exception 'FAIL changed analysis';exception when raise_exception then if SQLERRM<>'Review evidence is immutable' then raise;end if;end;
 perform pg_temp.check(true,'saved analysis history cannot be overwritten');
end$$;

-- Escalation and terminal decisions use the same transaction as analysis.
update public.reviews set review_text='Water leaks from the ceiling.' where id=(select review_id from fixture);
update fixture set classification=classification||jsonb_build_object('sentiment','negative','sentimentScore',-0.8,'topics',array['maintenance'],'issueDomains',array['maintenance'],'severity','high','riskClass','operational','isUrgent',true,'summary','The reviewer reports a ceiling leak.','evidence',jsonb_build_array(jsonb_build_object('claim','Ceiling leak','quote','Water leaks from the ceiling.'))),request_id=gen_random_uuid();
update fixture set receipt=jsonb_build_object('status','received','content',(classification-'policy'-'provenance'-'usage')::text);
do $$declare f fixture;r jsonb;ticket_id uuid;rid uuid:=gen_random_uuid();begin select * into f from fixture;
 perform pg_temp.start();r:=public.claim_reviewflow_analysis(f.request_id);perform public.record_reviewflow_analysis_result(f.request_id,(r->>'claimToken')::uuid,f.receipt);perform pg_temp.apply();
 perform pg_temp.check((select priority='urgent' and source_ticket_id is not null from public.reputation_cases where review_id=f.review_id),'urgent analysis links an escalation ticket atomically');
 select id into ticket_id from public.review_tickets where review_id=f.review_id;
 perform pg_temp.check((select status='open' and priority='urgent' from public.review_tickets where id=ticket_id),'negative urgent evidence creates one useful staff ticket');
 update public.review_tickets set status='resolved',resolution_notes='Staff confirmed repair',resolved_at=clock_timestamp() where id=ticket_id;
 update public.reputation_cases set status='resolved' where review_id=f.review_id;
 perform pg_temp.start(rid);r:=public.claim_reviewflow_analysis(rid);perform public.record_reviewflow_analysis_result(rid,(r->>'claimToken')::uuid,f.receipt);perform pg_temp.apply(rid);
 perform pg_temp.check((select status='resolved' from public.reputation_cases where review_id=f.review_id) and(select status='resolved' and resolution_notes='Staff confirmed repair' from public.review_tickets where id=ticket_id),'fresh analysis cannot reopen an operator-resolved case or ticket');
 perform pg_temp.check((select count(*)=1 from public.review_tickets where review_id=f.review_id),'analysis retries cannot create parallel escalation tickets');
end$$;
do $$declare f fixture;r jsonb;rid uuid:=gen_random_uuid();source_id uuid:=gen_random_uuid();begin select * into f from fixture;
 insert into public.reviews(id,property_id,platform,review_text,rating,reviewer_name) values(source_id,f.property_id,'other','Water leaks from the ceiling.',1,'Fixture reviewer');
 insert into public.reputation_cases(property_id,review_id,status,priority) values(f.property_id,source_id,'dismissed','low');
 perform pg_temp.start(rid,source_id);r:=public.claim_reviewflow_analysis(rid);perform public.record_reviewflow_analysis_result(rid,(r->>'claimToken')::uuid,f.receipt);perform pg_temp.apply(rid);
 perform pg_temp.check(not exists(select 1 from public.review_tickets where review_id=source_id),'a dismissed case cannot create a new open ticket through analysis');
end$$;
do $$declare f fixture;r jsonb;rid uuid:=gen_random_uuid();saved_hash text;begin select * into f from fixture;
 perform pg_temp.start(rid);r:=public.claim_reviewflow_analysis(rid);perform public.record_reviewflow_analysis_result(rid,(r->>'claimToken')::uuid,f.receipt);select result_hash into saved_hash from public.reviewflow_analysis_requests where id=rid;
 perform pg_temp.check(public.apply_reviewflow_analysis(rid,f.property_id,f.actor_id,jsonb_build_object('resultHash','different','analysis',f.classification))->>'state'='result_conflict','application must identify the exact saved receipt');
 begin perform public.apply_reviewflow_analysis(rid,f.property_id,f.actor_id,jsonb_build_object('resultHash',saved_hash,'analysis',f.classification||'{"sentiment":"positive"}'));raise exception 'FAIL receipt rewritten';exception when raise_exception then if SQLERRM<>'Analysis differs from its saved model receipt' then raise;end if;end;
 perform pg_temp.check(true,'model classification cannot be replaced while recovering its receipt');
 perform pg_temp.check(public.apply_reviewflow_analysis(rid,f.property_id,f.actor_id,jsonb_build_object('resultHash',saved_hash,'errorCode','invalid_output'))->>'state'='held','invalid saved output can be held without publishing a classification');
 perform pg_temp.check(not exists(select 1 from public.review_analyses where id=rid),'invalid output never writes a completed analysis');
end$$;

select count(*) as passed_assertions from checks;
rollback;
