begin;
create temp table checks(label text);
create function pg_temp.check(ok boolean,label text)returns void language plpgsql as $$begin if ok is not true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
create temp table fixture(property_id uuid,other_property uuid,actor uuid,brief_id uuid,export_id uuid);
insert into fixture values(gen_random_uuid(),gen_random_uuid(),'11111111-1111-1111-1111-111111111111',gen_random_uuid(),gen_random_uuid());
insert into public.properties(id,name,org_id,settings,address)select property_id,'Codex brief SQL fixture','22222222-2222-2222-2222-222222222222'::uuid,'{"city":""}'::jsonb,'{"city":"Should not replace explicit blank"}'::jsonb from fixture union all select other_property,'Other Codex brief SQL fixture','22222222-2222-2222-2222-222222222222'::uuid,'{}'::jsonb,'{}'::jsonb from fixture;
create function pg_temp.brief_input(property_id uuid,parent_id uuid default null)returns jsonb language sql as $$select jsonb_build_object('property',jsonb_build_object('id',p.id,'name',p.name,'city',null),'draft',jsonb_build_object('request','Update the gallery','references','Private source notes','target','wordpress','revision',jsonb_build_object('keepUnchanged','','parentVersion',''),'delivery',jsonb_build_object('projectLocation','','contentOwnership','','inquiryDestination','')),'parentId',parent_id,'templateVersion','codex-brief-v1')from public.properties p where p.id=property_id$$;
create function pg_temp.reject_brief_event()returns trigger language plpgsql as $$begin if new.action='site.brief.saved'then raise exception 'Fixture: history unavailable';end if;return new;end$$;
do $$declare f fixture;r jsonb;r2 jsonb;child uuid:=gen_random_uuid();failed_id uuid:=gen_random_uuid();input jsonb;begin select *into f from fixture;input:=pg_temp.brief_input(f.property_id);
 perform pg_temp.check(not has_table_privilege('authenticated','public.siteforge_codex_briefs','SELECT')and not has_table_privilege('anon','public.siteforge_brief_exports','SELECT')and not has_function_privilege('authenticated','public.save_siteforge_codex_brief(uuid,uuid,uuid,jsonb,text)','EXECUTE'),'private brief tables and operations are service-only');
 perform pg_temp.check(public.save_siteforge_codex_brief(f.brief_id,f.property_id,gen_random_uuid(),input,'Exact private document')->>'state'='forbidden','unknown actor rejected before save');
 perform pg_temp.check(public.save_siteforge_codex_brief(f.brief_id,f.property_id,f.actor,jsonb_set(input,'{property,name}','"Stale property"'),'Exact private document')->>'state'='property_changed','displayed property facts must match current native context');
 r:=public.save_siteforge_codex_brief(f.brief_id,f.property_id,f.actor,input,'Exact private document');perform pg_temp.check(r->>'state'='saved'and r->>'document'='Exact private document','saved brief retains exact document and explicit blank city semantics');
 perform pg_temp.check(public.save_siteforge_codex_brief(f.brief_id,f.property_id,f.actor,input,'Exact private document')->>'state'='replayed','lost save reply reuses one exact snapshot');
 perform pg_temp.check(public.save_siteforge_codex_brief(f.brief_id,f.property_id,f.actor,input,'Changed document')->>'state'='request_conflict','request identity cannot change saved text');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where id=f.brief_id and product='siteforge'and action='site.brief.saved'and position('Private source notes'in request::text)=0 and result->'websiteCreated'='false'),'saved action records scope/hash without raw private notes or fabricated site creation');
 perform pg_temp.check(public.save_siteforge_codex_brief(child,f.other_property,f.actor,pg_temp.brief_input(f.other_property,f.brief_id),'Cross property revision')->>'state'='parent_unavailable','revision parent cannot cross property');
 r:=public.save_siteforge_codex_brief(child,f.property_id,f.actor,pg_temp.brief_input(f.property_id,f.brief_id),'Exact revised document');perform pg_temp.check(r->>'state'='saved'and(select parent_id=f.brief_id from public.siteforge_codex_briefs where id=child),'revision creates a new snapshot with preserved parent');
 create trigger reject_brief_event before insert on public.shared_action_events for each row execute function pg_temp.reject_brief_event();
 begin perform public.save_siteforge_codex_brief(failed_id,f.property_id,f.actor,input,'Must roll back');raise exception 'expected history failure';exception when others then if sqlerrm='expected history failure'then raise;end if;end;
 drop trigger reject_brief_event on public.shared_action_events;
 perform pg_temp.check(not exists(select 1 from public.siteforge_codex_briefs where id=failed_id),'failed action history rolls back the brief atomically');
 begin update public.siteforge_codex_briefs set document='Changed original'where id=f.brief_id;raise exception 'expected immutable snapshot';exception when others then if sqlerrm='expected immutable snapshot'then raise;end if;end;
 begin delete from public.siteforge_codex_briefs where id=child;raise exception 'expected retained snapshot';exception when others then if sqlerrm='expected retained snapshot'then raise;end if;end;
 perform pg_temp.check((select document='Exact private document'from public.siteforge_codex_briefs where id=f.brief_id)and exists(select 1 from public.siteforge_codex_briefs where id=child),'snapshot mutation and deletion cannot overwrite history');
 r:=public.prepare_siteforge_brief_export(f.export_id,f.property_id,f.actor,f.brief_id,'copy');perform pg_temp.check(r->>'state'='prepared'and r->>'document'='Exact private document','handoff preparation returns exactly the retained snapshot');
 perform pg_temp.check(public.prepare_siteforge_brief_export(f.export_id,f.property_id,f.actor,f.brief_id,'copy')->>'state'='replayed'and public.prepare_siteforge_brief_export(f.export_id,f.property_id,f.actor,child,'copy')->>'state'='request_conflict','handoff retries preserve exact brief and mode');
 r:=public.read_siteforge_codex_briefs(f.property_id,f.actor,null,f.brief_id);perform pg_temp.check(r->'exports'->0->'reportedOutcome'='null'::jsonb,'prepared handoff does not imply browser success or file receipt');
 begin perform public.report_siteforge_brief_export(f.property_id,f.actor,f.export_id,'download_started');raise exception 'expected mode mismatch';exception when others then if sqlerrm='expected mode mismatch'then raise;end if;end;
 perform pg_temp.check(not exists(select 1 from public.siteforge_brief_export_reports where id=f.export_id),'incompatible observed outcome rejected without report');
 perform pg_temp.check(public.report_siteforge_brief_export(f.property_id,f.actor,f.export_id,'clipboard_failed')->>'state'='recorded','browser failure is retained as an observed outcome');
 perform pg_temp.check(public.report_siteforge_brief_export(f.property_id,f.actor,f.export_id,'clipboard_failed')->>'state'='replayed'and public.report_siteforge_brief_export(f.property_id,f.actor,f.export_id,'clipboard_succeeded')->>'state'='request_conflict','observed result replay cannot rewrite the original outcome');
 perform pg_temp.check((select count(*)=1 from public.shared_action_events where episode_id=f.export_id and action='site.brief.export_reported'and evidence='browser_observed'and phase='observed'and result->'deliveryConfirmed'='false'),'browser observation is distinct from verified delivery');
 perform pg_temp.check(public.read_siteforge_codex_briefs(f.other_property,f.actor,null,f.brief_id)->>'state'='not_found'and public.prepare_siteforge_brief_export(gen_random_uuid(),f.other_property,f.actor,f.brief_id,'copy')->>'state'='not_found','reads and exports cannot cross property');
 update public.properties set name='Renamed after original snapshot'where id=f.property_id;
 perform pg_temp.check(public.save_siteforge_codex_brief(f.brief_id,f.property_id,f.actor,input,'Exact private document')->>'state'='replayed','old exact request remains recoverable after a property rename');
 r:=public.read_siteforge_codex_briefs(f.property_id,f.actor,null,f.brief_id);perform pg_temp.check(r->'selected'->'input'->'property'->>'name'='Codex brief SQL fixture','historical context is never silently refreshed');
 update public.profiles set org_id=null where id=f.actor;
 perform pg_temp.check(public.read_siteforge_codex_briefs(f.property_id,f.actor)->>'state'='forbidden'and public.prepare_siteforge_brief_export(f.export_id,f.property_id,f.actor,f.brief_id,'copy')->>'state'='forbidden'and public.report_siteforge_brief_export(f.property_id,f.actor,f.export_id,'clipboard_failed')->>'state'='forbidden','read export and observed-result replay recheck current actor access');
 update public.profiles set org_id='22222222-2222-2222-2222-222222222222'where id=f.actor;
end$$;
do $$declare f fixture;i integer;r jsonb;cursor_id uuid;seen uuid[]:='{}';expected bigint;e uuid;begin select *into f from fixture;
 for i in 1..1005 loop perform public.save_siteforge_codex_brief(gen_random_uuid(),f.property_id,f.actor,pg_temp.brief_input(f.property_id),'Complete saved snapshot '||i);end loop;
 select count(*)into expected from public.siteforge_codex_briefs where property_id=f.property_id;
 loop r:=public.read_siteforge_codex_briefs(f.property_id,f.actor,cursor_id);select seen||array_agg((v->>'id')::uuid)into seen from jsonb_array_elements(r->'briefs')v;cursor_id:=(r->>'nextCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(cardinality(seen)=expected and(select count(distinct id)=expected from unnest(seen)id),'brief paging covers more than1000 saved snapshots exactly once');
 for i in 1..24 loop e:=gen_random_uuid();perform public.prepare_siteforge_brief_export(e,f.property_id,f.actor,f.brief_id,'download');if i%2=0 then perform public.report_siteforge_brief_export(f.property_id,f.actor,e,'download_started');end if;end loop;
 seen:='{}';cursor_id:=null;loop r:=public.read_siteforge_codex_briefs(f.property_id,f.actor,null,f.brief_id,cursor_id);select seen||array_agg((v->>'id')::uuid)into seen from jsonb_array_elements(r->'exports')v;cursor_id:=(r->>'nextExportCursor')::uuid;exit when cursor_id is null;end loop;
 perform pg_temp.check(cardinality(seen)=25 and(select count(distinct id)=25 from unnest(seen)id),'handoff history pages both observed and unreported preparations');
 perform pg_temp.check(public.read_siteforge_codex_briefs(f.property_id,f.actor,gen_random_uuid())->>'state'='cursor_changed','unrelated snapshot cursor rejected');
end$$;
select count(*)as passed_assertions from checks;
rollback;
