BEGIN;
-- Keep fixture tour durations within the same day at every test clock time.
create temp table checks(label text);
create function pg_temp.check(passed boolean,label text) returns void language plpgsql as $$begin
 if passed is not true then raise exception 'FAIL: %',label;end if;insert into checks values(label);end$$;
DO $$
declare p uuid:=gen_random_uuid();good_p uuid:=gen_random_uuid();l uuid:=gen_random_uuid();good_l uuid:=gen_random_uuid();
 t uuid:=gen_random_uuid();good_t uuid:=gen_random_uuid();old_t uuid:=gen_random_uuid();stale_t uuid:=gen_random_uuid();old_l uuid:=gen_random_uuid();
 w uuid:=gen_random_uuid();d timestamp:=date_trunc('hour',now() at time zone 'UTC')-interval '3 hours';r jsonb;r2 jsonb;v integer;
begin
 insert into public.properties(id,org_id,name,settings)values(p,'22222222-2222-2222-2222-222222222222','No-show failed fixture','{"timezone":"UTC"}'),(good_p,'22222222-2222-2222-2222-222222222222','No-show healthy fixture','{"timezone":"UTC"}');
 insert into public.leads(id,property_id,first_name,last_name,status)values(l,p,'Retry','Fixture','tour_booked'),(good_l,good_p,'Independent','Fixture','tour_booked'),(old_l,good_p,'Old','Fixture','tour_booked');
 update public.workflow_definitions set is_active=false where property_id in (p,good_p);
 insert into public.workflow_definitions(id,property_id,name,trigger_on,steps,exit_conditions,is_active)values(w,p,'Broken fixture','tour_no_show','[]','[]',true);
 insert into public.tours(id,property_id,lead_id,tour_date,tour_time,status)values(t,p,l,d::date,d::time,'confirmed');
 insert into public.tour_bookings(id,property_id,lead_id,scheduled_date,scheduled_time,status)values(good_t,good_p,good_l,d::date,d::time,'confirmed');
 r:=public.process_tour_noshow_attempt(p,l,'tours',t,1);
 perform pg_temp.check(r->>'state'='backoff' and r->>'attempts'='1','first failure is persisted with delayed retry');
 perform pg_temp.check((select status='confirmed' from public.tours where id=t),'failed outcome rolls back status');
 perform pg_temp.check(not exists(select 1 from public.tour_outcomes where tour_id=t) and not exists(select 1 from public.lead_engagement_events where lead_id=l),'failed outcome rolls back receipt and score');
 perform pg_temp.check((select next_try_at=now()+interval '15 minutes' from public.tour_noshow_attempts where tour_id=t),'first retry waits fifteen minutes');
 r2:=public.process_tour_noshow_attempt(p,l,'tours',t,1);
 perform pg_temp.check(r2->>'state'='backoff' and (select attempts=1 from public.tour_noshow_attempts where tour_id=t),'immediate retry cannot consume another attempt');
 r:=public.list_tour_noshow_candidates(250);
 perform pg_temp.check(not exists(select 1 from jsonb_array_elements(r->'tours') x where x->>'id'=t::text),'backoff excluded before batch limit');
 perform pg_temp.check(exists(select 1 from jsonb_array_elements(r->'tours') x where x->>'id'=good_t::text),'independent widget booking remains eligible');
 r:=public.process_tour_noshow_attempt(good_p,good_l,'tour_bookings',good_t,1);
 perform pg_temp.check(r->>'state'='applied','independent booking succeeds');
 perform pg_temp.check((select state='completed' and attempts=1 from public.tour_noshow_attempts where tour_id=good_t),'successful outcome and attempt checkpoint saved together');
 r2:=public.process_tour_noshow_attempt(good_p,good_l,'tour_bookings',good_t,1);
 perform pg_temp.check(r2->>'state'='replayed' and r2->'outcome'=r->'outcome','lost response returns saved receipt');
 perform pg_temp.check((select count(*)=1 from public.lead_engagement_events where lead_id=good_l),'replay does not duplicate scoring');
 update public.tour_noshow_attempts set next_try_at=now()-interval '1 second' where tour_id=t;
 r:=public.process_tour_noshow_attempt(p,l,'tours',t,1);
 perform pg_temp.check(r->>'state'='backoff' and r->>'attempts'='2','second failure remains bounded');
 perform pg_temp.check((select next_try_at=now()+interval '1 hour' from public.tour_noshow_attempts where tour_id=t),'second retry waits an hour');
 update public.tour_noshow_attempts set next_try_at=now()-interval '1 second' where tour_id=t;
 r:=public.process_tour_noshow_attempt(p,l,'tours',t,1);
 perform pg_temp.check(r->>'state'='review' and r->>'attempts'='3','third failure stops for review');
 r:=public.process_tour_noshow_attempt(p,l,'tours',t,1);
 perform pg_temp.check(r->>'state'='review' and (select attempts=3 and next_try_at is null from public.tour_noshow_attempts where tour_id=t),'review cannot automatically restart');
 perform pg_temp.check(not exists(select 1 from jsonb_array_elements(public.list_tour_noshow_candidates(250)->'tours') x where x->>'id'=t::text),'review excluded from worker batch');
 perform pg_temp.check((select count(*)=1 from public.tour_noshow_queue(p,l)) and (select count(*)=0 from public.tour_noshow_queue(good_p,l)),'review history is property and lead scoped');
 perform pg_temp.check(public.process_tour_noshow_attempt(good_p,l,'tours',t,1)->>'state'='not_found','foreign property rejected');
 perform pg_temp.check(public.process_tour_noshow_attempt(p,good_l,'tours',t,1)->>'state'='not_found','foreign lead rejected');
 perform pg_temp.check(public.process_tour_noshow_attempt(p,l,'tours',t,2)->>'state'='stale','stale schedule version rejected');
 update public.workflow_definitions set steps='[{"action":"wait","delay_hours":1}]' where id=w;
 r:=public.record_tour_outcome(p,l,'tours',t,'completed','Verified by operator');
 perform pg_temp.check(r->>'state'='applied','operator can save verified outcome after automatic failure');
 perform pg_temp.check(public.tour_noshow_state(p,'tours',t) is null,'resolved tour disappears from review');
 insert into public.workflow_definitions(property_id,name,trigger_on,steps,exit_conditions,is_active)values(good_p,'No-show follow-up','tour_no_show','[{"action":"wait","delay_hours":1}]','[]',true);
 d:=date_trunc('hour',now() at time zone 'UTC')-interval '10 days';
 insert into public.tours(id,property_id,lead_id,tour_date,tour_time,status)values(old_t,good_p,old_l,d::date,d::time,'scheduled');
 perform pg_temp.check(public.tour_noshow_state(good_p,'tours',old_t)->'automation'->>'state'='backlog','old active tours visibly require review');
 perform pg_temp.check(public.process_tour_noshow_attempt(good_p,old_l,'tours',old_t,1)->>'state'='backlog','worker cannot replay old backlog');
 perform pg_temp.check(not exists(select 1 from public.tour_noshow_attempts where tour_id=old_t),'backlog does not consume attempts');
 r:=public.record_tour_outcome(good_p,old_l,'tours',old_t,'no_show','Historical attendance confirmed');
 perform pg_temp.check(r->>'state'='applied' and r->'outcome'->>'followup_state'='suppressed','manual historical no-show saves without fresh follow-up');
 perform pg_temp.check(not exists(select 1 from public.lead_workflows where lead_id=old_l),'historical manual decision cannot enqueue campaign');
 d:=date_trunc('hour',now() at time zone 'UTC')-interval '2 days';
 insert into public.tours(id,property_id,lead_id,tour_date,tour_time,status)values(stale_t,good_p,old_l,d::date,d::time,'scheduled');
 r:=public.process_tour_noshow_attempt(good_p,old_l,'tours',stale_t,1);
 perform pg_temp.check(r->>'state'='applied' and r->'outcome'->>'followup_state'='suppressed','late automatic outcome also suppresses stale messaging');
 perform pg_temp.check(not exists(select 1 from public.lead_workflows where lead_id=old_l),'automatic delayed outcome cannot enqueue campaign');
 perform pg_temp.check(not has_table_privilege('authenticated','public.tour_noshow_attempts','SELECT') and (select relrowsecurity from pg_class where oid='public.tour_noshow_attempts'::regclass),'private retry ledger has RLS');
 perform pg_temp.check(not has_function_privilege('anon','public.process_tour_noshow_attempt(uuid,uuid,text,uuid,integer)','EXECUTE') and not has_function_privilege('authenticated','public.tour_noshow_queue(uuid,uuid)','EXECUTE'),'retry and status functions are service-only');
end$$;
select count(*) as passed from checks;
ROLLBACK;
