import {beforeEach,it,expect,vi}from 'vitest'
const d=vi.hoisted(()=>({actor:vi.fn(),read:vi.fn(),decide:vi.fn()}));vi.mock('@/utils/property-setup/organization-store',()=>({organizationActor:d.actor,readOrganizationSetup:d.read,decideOrganizationSetup:d.decide,OrganizationError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {GET,POST}from './route'
import {OrganizationError}from '@/utils/property-setup/organization-store'
const id='11111111-1111-1111-1111-111111111111',body={requestId:id,operation:'complete',expectedRevision:1,draftHash:'a'.repeat(64),confirmed:true,reason:'Review first organization setup'}
beforeEach(()=>{vi.clearAllMocks();d.actor.mockResolvedValue('actor');d.read.mockResolvedValue({state:'ready',actorId:'actor',alreadyMember:false,setup:null,items:[]});d.decide.mockResolvedValue({state:'saved',decisionId:id})})
it('authenticates before parsing input or reading private drafts',async()=>{d.actor.mockRejectedValue(new OrganizationError('Unauthorized',401));expect((await POST(new Request('http://local',{method:'POST',body:'invalid'}))).status).toBe(401);expect((await GET(new Request('http://local'))).status).toBe(401);expect(d.read).not.toHaveBeenCalled();expect(d.decide).not.toHaveBeenCalled()})
it('retires anonymous-id and legacy nontransactional setup bodies',async()=>{for(const input of[{organizationName:'Legacy'},{organization:{name:'Legacy'},property:{name:'Legacy'}},{...body,actorId:id},{...body,confirmed:false}])expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(input)}))).status).toBe(400);expect(d.decide).not.toHaveBeenCalled()})
it('saves only an exact authenticated actor command with private response',async()=>{const result=await POST(new Request('http://local',{method:'POST',body:JSON.stringify(body)}));expect(result.status).toBe(200);expect(result.headers.get('Cache-Control')).toBe('private, no-store');expect(d.decide).toHaveBeenCalledWith('actor',body)})
it('enforces actual streamed as well as declared request limits',async()=>{expect((await POST(new Request('http://local',{method:'POST',headers:{'content-length':'524289'},body:'{}'}))).status).toBe(413);expect((await POST(new Request('http://local',{method:'POST',body:'x'.repeat(524289)}))).status).toBe(413);expect(d.decide).not.toHaveBeenCalled()})
it('distinguishes fresh, existing and completed accounts without writing',async()=>{expect(await(await GET(new Request('http://local'))).json()).toMatchObject({needsOnboarding:true});d.read.mockResolvedValueOnce({alreadyMember:true,setup:null});expect(await(await GET(new Request('http://local'))).json()).toMatchObject({needsOnboarding:false});d.read.mockResolvedValueOnce({alreadyMember:false,setup:{state:'completed'}});expect(await(await GET(new Request('http://local'))).json()).toMatchObject({needsOnboarding:false});expect(d.decide).not.toHaveBeenCalled()})
it('denies arbitrary reads and hides private implementation errors',async()=>{expect((await GET(new Request('http://local?actorId=another'))).status).toBe(400);d.read.mockRejectedValue(new Error('private internals'));const r=await GET(new Request('http://local'));expect(r.status).toBe(503);expect(await r.json()).toEqual({error:'Organization setup is unavailable.'})})
