import {NextRequest,NextResponse} from 'next/server'
import {marketId,unitDecision} from '@/utils/marketvision/decision-contracts'
import {requireMarketOperator,marketRpc,MarketStoreError,marketError} from '@/utils/marketvision/decision-store'
import {formatUnit} from '@/utils/marketvision/records'
export async function GET(req:NextRequest){try{const property=marketId.safeParse(req.nextUrl.searchParams.get('propertyId')),competitor=marketId.safeParse(req.nextUrl.searchParams.get('competitorId'));if(!property.success||!competitor.success)throw new MarketStoreError('Choose a property and competitor.',400);const actor=await requireMarketOperator(property.data),result=await marketRpc('read_marketvision_competitors',{p_property_id:property.data,p_actor_id:actor,p_active_only:false}),record=(result.competitors as Record<string,unknown>[]).find(c=>c.id===competitor.data);if(!record)throw new MarketStoreError('This competitor is unavailable in the selected property.',404);const units=(record.units as Record<string,unknown>[]).map(formatUnit);return NextResponse.json({units,count:units.length,competitorVersion:record.version,isActive:record.is_active})}catch(e){return marketError(e)}}
async function save(req:NextRequest,method:'POST'|'PUT'|'DELETE'){try{const parsed=unitDecision.safeParse(await req.json().catch(()=>null));if(!parsed.success)throw new MarketStoreError('Review the unit values, current version, and a reason before saving.',400);const {requestId,propertyId,...input}=parsed.data;if(input.action!==({POST:'create',PUT:'save',DELETE:'remove'} as const)[method])throw new MarketStoreError('Choose the matching unit decision.',400);const actor=await requireMarketOperator(propertyId),result=await marketRpc('save_marketvision_unit',{p_id:requestId,p_property_id:propertyId,p_actor_id:actor,p_input:input});return NextResponse.json({success:true,result})}catch(e){return marketError(e)}}
export const POST=(req:NextRequest)=>save(req,'POST')
export const PUT=(req:NextRequest)=>save(req,'PUT')
export const DELETE=(req:NextRequest)=>save(req,'DELETE')
