import { describe, it, expect } from 'vitest';
import { buildBiReport, type BiSource, type BiFact } from './report-data';
import { detectBiChanges } from './alert-data';
import { alertCommand, alertRead } from './alert-contracts';
const fact = (day: number, extra: Partial<BiFact> = {}): BiFact => ({ id: crypto.randomUUID(), date: `2026-09-${String(day).padStart(2, '0')}`, channel_id: 'google_ads', source_account_id: 'one', currency_code: 'USD', campaign_id: 'fixture', campaign_name: 'Fixture', impressions: 100, clicks: 10, spend: 1, conversions: .125, ...extra });
const source = (rows: BiFact[], prior: BiFact[] = []): BiSource => ({ version: 'bi-v1', propertyId: '33333333-3333-3333-3333-333333333333', propertyName: 'Fixture', filters: { startDate: '2026-09-01', endDate: '2026-09-07', channel: null, account: null, compare: true }, currentRows: rows, previousRows: prior, previousPeriod: { start: '2026-08-25', end: '2026-08-31' } });
const detect = (s: BiSource) => detectBiChanges(buildBiReport(s), 'a'.repeat(64));
describe('fixed marketing comparison rules', () => {
    it('uses other dates as baseline and retains the exact figures and thresholds', () => { const d = detect(source(Array.from({ length: 7 }, (_, i) => fact(i + 1, { clicks: i === 6 ? 20 : 10 })))); expect(d.alerts).toHaveLength(1); expect(d.alerts[0]).toEqual({ key: 'daily:clicks:2026-09-07', metric: 'clicks', kind: 'daily', date: '2026-09-07', value: 20, baseline: 10, percent: 100, threshold: 40 }); expect(d.coverage).toMatchObject({ dailyEligible: true, periodEligible: false, currentDays: 7, requestedDays: 7 }); });
    it('retains all matching changes beyond the former top five', () => { const d = detect(source(Array.from({ length: 7 }, (_, i) => fact(i + 1, { clicks: i % 2 ? 0 : 100 })))); expect(d.alerts).toHaveLength(7); expect(new Set(d.alerts.map(a => a.key)).size).toBe(7); });
    it('does not call missing data a clean result', () => { const d = detect(source([fact(1)])); expect(d.alerts).toEqual([]); expect(d.coverage.dailyEligible).toBe(false); expect(d.coverage.periodEligible).toBe(false); });
    it('requires seven complete daily dates', () => { const s = source(Array.from({ length: 6 }, (_, i) => fact(i + 1, { clicks: i ? 10 : 100 }))); s.filters.endDate = '2026-09-06'; expect(detect(s).coverage.dailyEligible).toBe(false); });
    it('never creates infinite percentages from zero baselines', () => { const d = detect(source(Array.from({ length: 7 }, (_, i) => fact(i + 1, { clicks: i === 6 ? 1 : 0 })))); expect(d.alerts.some(a => a.key === 'daily:clicks:2026-09-07')).toBe(false); expect(d.alerts.every(a => Number.isFinite(a.percent))).toBe(true); });
    it('keeps fractional conversions and signed decreases', () => { const d = detect(source(Array.from({ length: 7 }, (_, i) => fact(i + 1, { conversions: i === 6 ? 0 : .125 })))); expect(d.alerts.find(a => a.metric === 'conversions')).toMatchObject({ value: 0, baseline: .125, percent: -100, threshold: 60 }); });
    it('withholds unknown money without hiding valid count comparisons', () => { const d = detect(source(Array.from({ length: 7 }, (_, i) => fact(i + 1, { clicks: i === 6 ? 20 : 10, spend: i === 6 ? 100 : 1, currency_code: null })))); expect(d.alerts.some(a => a.metric === 'spend')).toBe(false); expect(d.alerts.some(a => a.metric === 'clicks')).toBe(true); });
    it('compares complete equal periods and excludes partial prior coverage', () => { const rows = Array.from({ length: 7 }, (_, i) => fact(i + 1, { clicks: 20 })), prior = Array.from({ length: 7 }, (_, i) => fact(i + 1, { date: `2026-08-${25 + i}` })); const d = detect(source(rows, prior)); expect(d.alerts.find(a => a.kind === 'period' && a.metric === 'clicks')).toMatchObject({ value: 140, baseline: 70, percent: 100 }); expect(detect(source(rows, prior.slice(1))).coverage.periodEligible).toBe(false); });
    it('cannot retain duplicate selections, extra evidence or unsupported states', () => { const id = source([]).propertyId, c = { id, propertyId: id, expectedActorId: id, operation: 'review', setId: id, items: [{ key: 'daily:clicks:2026-09-01', revision: 1 }], note: 'Planned change' }; expect(alertCommand.safeParse(c).success).toBe(true); expect(alertCommand.safeParse({ ...c, items: [...c.items, ...c.items] }).success).toBe(false); expect(alertCommand.safeParse({ ...c, derived: { forged: true } }).success).toBe(false); expect(alertCommand.safeParse({ ...c, note: 'x'.repeat(2001) }).success).toBe(false); expect(alertRead.safeParse({ propertyId: id, kind: 'items' }).success).toBe(false); });
});
