import { describe, it, expect } from 'vitest';
import { calculateQuery } from './query-data';
import { queryPlan, queryCommand, planFits } from './query-contracts';
import type { BiFact, BiSource } from './report-data';
const fact = (extra: Partial<BiFact> = {}): BiFact => ({ id: crypto.randomUUID(), date: '2026-09-01', channel_id: 'google_ads', source_account_id: 'one', currency_code: 'USD', campaign_id: 'one', campaign_name: 'First', impressions: 100, clicks: 10, spend: 10.01, conversions: .125, ...extra });
const source = (rows: BiFact[]): BiSource => ({ version: 'bi-v1', propertyId: '33333333-3333-3333-3333-333333333333', propertyName: 'Fixture', filters: { startDate: '2026-09-01', endDate: '2026-09-30', compare: true, channel: null, account: null }, currentRows: rows, previousRows: [], previousPeriod: null });
const plan = { groupBy: 'channel' as const, startDate: '2026-09-01', endDate: '2026-09-30', channel: null };
describe('retained query calculations', () => {
    it('shares BI definitions and weighted rates, preserving fractional attribution', () => { const r = calculateQuery(source([fact({ impressions: 10, clicks: 5, spend: .1 }), fact({ impressions: 990, clicks: 5, spend: .2, conversions: .25 })]), plan, 'source', 'plan'); expect(r.totals).toMatchObject({ spend: .3, conversions: .375, ctr: 1 }); expect(r.rows[0].cpa).toBeCloseTo(.8); expect(r.coverage).toMatchObject({ records: 2, observedDays: 1, requestedDays: 30 }); expect(r.sourceHash).toBe('source'); });
    it('retains every campaign beyond the previous 100-row limit', () => { const r = calculateQuery(source(Array.from({ length: 125 }, (_, i) => fact({ campaign_id: String(i) }))), { ...plan, groupBy: 'campaign' }, 's', 'p'); expect(r.rows).toHaveLength(125); expect(r.totals.spend).toBe(1251.25); });
    it('separates campaign identity by channel/account and canonicalizes aliases', () => { const r = calculateQuery(source([fact(), fact({ source_account_id: 'two' }), fact({ channel_id: 'google' }), fact({ channel_id: 'meta_ads' })]), { ...plan, groupBy: 'campaign' }, 's', 'p'); expect(r.rows).toHaveLength(3); expect(r.rows.find(r => r.account === 'one' && r.channel === 'google_ads')?.clicks).toBe(20); });
    it('restricts calculation to reviewed dates and channels', () => { const r = calculateQuery(source([fact(), fact({ date: '2026-09-02' }), fact({ date: '2026-09-02', channel_id: 'meta_ads' })]), { ...plan, startDate: '2026-09-02', channel: 'google_ads' }, 's', 'p'); expect(r.coverage.records).toBe(1); expect(r.totals.clicks).toBe(10); });
    it('cannot widen captured report scope', () => { const s = source([fact()]); s.filters.channel = 'google_ads'; expect(() => calculateQuery(s, { ...plan, channel: 'meta_ads' }, 's', 'p')).toThrow(); expect(() => calculateQuery(s, { ...plan, startDate: '2026-08-01' }, 's', 'p')).toThrow(); expect(planFits(plan, s.filters)).toBe(true); });
    it('never fills absent dates or invents results for no records', () => { expect(calculateQuery(source([]), plan, 's', 'p').rows).toEqual([]); expect(calculateQuery(source([fact()]), { ...plan, groupBy: 'day' }, 's', 'p').rows).toHaveLength(1); });
    it('preserves unavailable currency and zero-denominator rates', () => { expect(calculateQuery(source([fact({ currency_code: null, impressions: 0, clicks: 0, conversions: 0 })]), plan, 's', 'p').rows[0]).toMatchObject({ spend: null, ctr: null, cpc: null, cpa: null }); });
    it('uses UTC Monday weeks even across calendar years', () => { const s = source([fact({ date: '2026-01-01' }), fact({ date: '2026-01-04' })]); s.filters.startDate = '2026-01-01'; s.filters.endDate = '2026-01-04'; const r = calculateQuery(s, { ...plan, startDate: s.filters.startDate, endDate: s.filters.endDate, groupBy: 'week' }, 's', 'p'); expect(r.rows).toHaveLength(1); expect(r.rows[0].label).toBe('Week starting 2025-12-29'); expect(r.coverage.observedDays).toBe(2); });
    it.each([{ groupBy: 'pg_sleep(5)' }, { sql: 'SELECT * FROM profiles' }, { propertyId: 'other' }, { limit: 100 }, { startDate: '2026-02-30' }, { startDate: '2026-01-01', endDate: '2027-01-02' }, { channel: 'x OR true' }, { extra: 1 }])('rejects unsafe, truncated or out-of-bounds plans %j', extra => expect(queryPlan.safeParse({ ...plan, ...extra }).success).toBe(false));
    it('requires stable property, actor and source identity and reviewed manual plan', () => { const s = source([]), id = s.propertyId, c = { operation: 'request', propertyId: id, expectedActorId: id, id, mode: 'manual', question: 'Totals', filters: s.filters, sourceHash: 'a'.repeat(64), plan }; expect(queryCommand.safeParse(c).success).toBe(true); expect(queryCommand.safeParse({ ...c, plan: undefined }).success).toBe(false); expect(queryCommand.safeParse({ ...c, expectedActorId: undefined }).success).toBe(false); expect(queryCommand.safeParse({ ...c, mode: 'assistant' }).success).toBe(false); });
});
