import { buildBiReport, biExportData, metricCurrency, metricPercent, type BiSource } from './report-data';
import { formatConversions } from './marketing-fact';
import { getMarketingChannelLabel } from './channel-identity';
import type { ScheduleConfig } from './schedule-contracts';
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
const table = (labels: string[], rows: unknown[][]) => `<table class="report-table" style="width:100%;table-layout:fixed;border-collapse:collapse;text-align:left;font-size:13px"><thead><tr>${labels.map(x => `<th scope="col" style="padding:8px;background:#f1f5f9;overflow-wrap:anywhere">${escape(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(values => '<tr>' + values.map((value, index) => `<td style="padding:8px;border-bottom:1px solid #e2e8f0;overflow-wrap:anywhere"><span class="mobile-label" style="display:none;font-weight:bold;color:#475569;margin-bottom:4px">${escape(labels[index])}</span>${escape(value)}</td>`).join('') + '</tr>').join('')}</tbody></table>`;
const mobileStyles = `<style>@media(max-width:600px){.mail-body{padding:12px!important}.mail-main{padding:16px!important}.report-table,.report-table tbody,.report-table tr,.report-table td{display:block!important;width:auto!important}.report-table thead{display:none!important}.report-table tr{border:1px solid #e2e8f0;border-radius:8px;margin-bottom:12px}.report-table td{padding:10px!important}.report-table td:last-child{border-bottom:0!important}.mobile-label{display:block!important}}</style>`;
export function scheduledReportEmail(input: {
    id: string;
    source: BiSource;
    sourceHash: string;
    config: ScheduleConfig;
    createdAt: string;
}, from: string) {
    const report = buildBiReport(input.source), data = biExportData(report, { id: input.id, sourceHash: input.sourceHash, savedAt: input.createdAt, label: input.config.name });
    const metrics = data.metrics.map(m => [m.label, m.value, ...(input.config.comparison ? [m.change === null || m.change === undefined ? 'Not available' : m.change.toFixed(2) + '%'] : [])]);
    const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${mobileStyles}</head><body class="mail-body" style="margin:0;padding:24px;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a"><main class="mail-main" style="max-width:960px;margin:auto;background:white;padding:24px;border-radius:12px"><p style="color:#4f46e5">oneClick · Marketing report</p><h1>${escape(input.config.name)}</h1><h2>${escape(input.source.propertyName)}</h2><p>${escape(report.dateRange.start)} to ${escape(report.dateRange.end)} · UTC dates</p><p>${report.coverage.records} stored records across ${report.coverage.observedDays} of ${report.coverage.requestedDays} selected dates. Missing dates are not filled with invented zeroes.</p>${table(['Metric', 'Value', ...(input.config.comparison ? ['Change from prior period'] : [])], metrics)}${report.comparison ? `<p>Prior period: ${escape(report.comparison.previousPeriod?.start)} to ${escape(report.comparison.previousPeriod?.end)} · ${report.coverage.previousRecords} stored records.</p>` : ''}<h2>Sources</h2>${table(['Channel', 'Account', 'Records', 'Observed dates', 'Currency'], (data.sourceCoverage || []).map(s => [s.channel, s.account, s.records, `${s.days} (${s.firstDate} to ${s.lastDate})`, s.currency]))}<h2>Channel totals</h2>${table(['Channel', 'Spend (USD)', 'Impressions', 'Clicks', 'Reported conversions', 'CTR'], report.channels.map(c => [getMarketingChannelLabel(c.channel), metricCurrency(c.spend), c.impressions, c.clicks, formatConversions(c.conversions), metricPercent(c.ctr)]))}${input.config.campaigns ? '<h2>Campaigns</h2>' + table(['Campaign / ID', 'Channel / account', 'Spend (USD)', 'Clicks', 'Reported conversions', 'CTR'], report.campaigns.map(c => [c.campaign_name + ' / ' + c.campaign_id, getMarketingChannelLabel(c.channel) + ' / ' + (c.source_account_id || 'Unattributed account'), metricCurrency(c.spend), c.clicks, formatConversions(c.conversions), metricPercent(c.ctr)])) : ''}<h2>Reading this report</h2><ul>${data.notes?.map(n => '<li>' + escape(n) + '</li>').join('')}</ul><p style="font-size:11px;overflow-wrap:anywhere">Report ${escape(input.id)} · bi-v1<br>Source ${escape(input.sourceHash)}<br>Prepared ${escape(input.createdAt)}</p></main></body></html>`;
    if (new TextEncoder().encode(html).length > 524288)
        throw new Error('The complete report exceeds the email size limit. Turn off campaign details or narrow the scheduled period.');
    return { from, subject: input.config.name + ' — ' + report.dateRange.end, html };
}
