'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {usePropertyContext} from '@/components/layout/PropertyContext'
import {executionBoard,type ExecutionBoard} from '@/utils/agency/execution'
const button='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-800 disabled:opacity-50'
export function AgencyExecution(){
 const{currentProperty,hasLoadedProperties}=usePropertyContext()
 return <div className="mx-auto max-w-5xl p-4 sm:p-0"><Link href="/dashboard/agency" className="text-sm font-medium text-indigo-700 underline">Agency review</Link><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold text-slate-900">Execution pilot</h1><span className="rounded-full bg-amber-50 px-3 py-1 text-sm text-amber-900">Not launched</span></div><p className="mt-2 text-slate-600">Review the next steps toward automatic work for {currentProperty.name}.</p>
 <section aria-label="Launch requirements" className="mt-6 rounded-xl border border-indigo-100 bg-indigo-50 p-5"><h2 className="font-semibold text-indigo-950">Human review comes first</h2><p className="mt-2 text-sm text-indigo-950">Saving or reviewing a plan does not permit automatic action. Execution is available only in a separate, disposable local rehearsal. Real properties need their own acceptance and permission before a pilot can launch.</p><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm text-slate-700"><li><strong>Review a useful plan.</strong> Check its goal, source evidence, proposed steps and unknowns with the client.</li><li><strong>Measure proposal quality.</strong> Compare existing-model suggestions with the baseline and record human corrections. Real model quality is still unmeasured.</li><li><strong>Authorize a bounded pilot.</strong> Define exact targets, time and action limits, success criteria, who can stop it, and how to undo each effect.</li></ol><Link href="/dashboard/agency/plans" className="mt-4 inline-block text-sm font-medium text-indigo-700 underline">Review follow-up plans</Link></section>
 <section className="mt-6 grid gap-4 sm:grid-cols-2" aria-label="Rehearsal scope"><article className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Small internal actions</h2><p className="mt-2 text-sm text-slate-600">The local rehearsal covers adding a lead note and dismissing a market alert, with a maximum of two effects. Each has a recorded undo. A person’s later edits stop conflicting undo attempts.</p></article><article className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Separate measures</h2><p className="mt-2 text-sm text-slate-600">Action receipts, human interventions and reversals are retained separately. This rehearsal makes no provider calls. Completing an action does not prove a client or business outcome.</p></article></section>
 {hasLoadedProperties&&currentProperty.id?<History key={currentProperty.id} propertyId={currentProperty.id}/>:<p className="mt-6 text-sm text-slate-500">Select a property to review its pilot status.</p>}</div>
}
function History({propertyId}:{propertyId:string}){
 const[board,setBoard]=useState<ExecutionBoard|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const alive=useRef(false),loading=useRef(false)
 async function load(before?:string){
  if(loading.current)return;loading.current=true;setBusy(true);setError('')
  try{const query=new URLSearchParams({propertyId,kind:before?'history':'board',...(before?{before}:{})});const response=await fetch('/api/agency/execution?'+query,{cache:'no-store'});if(!response.ok)throw new Error('Execution status could not be loaded. Refresh to try again.');const next=executionBoard.parse(await response.json());if(next.propertyId!==propertyId)throw new Error('The status does not match this property.');if(alive.current)setBoard(previous=>before&&previous?{...next,items:[...previous.items,...next.items]}:next)}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Execution status could not be verified.')}finally{loading.current=false;if(alive.current)setBusy(false)}
 }
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false}
 // A mounted history belongs to one property; discard responses after a switch.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[])
 return <section aria-label="Execution history" className="mt-8 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Property pilot status</h2><button className={button} disabled={busy} onClick={()=>void load()}>Refresh status</button></div>{error&&<p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{error}</p>}{!board&&!error&&<p className="text-sm text-slate-500">Loading execution status…</p>}{board&&<><p role="status" className="text-sm text-slate-600">{board.enabled?'This disposable property has a local rehearsal scope. Commands are controlled by the rehearsal operator.':'Automatic execution is off for this property.'}</p>{board.items.length===0&&<p className="rounded-xl border border-dashed p-5 text-sm text-slate-500">No execution commands have been recorded for this property.</p>}{board.items.map(item=><article key={item.id} className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-medium">{item.result.status?.replaceAll('_',' ')||'Unused request closed'}</h3><p className="mt-1 text-xs text-slate-500">{new Date(item.created_at).toLocaleString()}</p><p className="mt-2 text-sm">{item.result.appliedCount??0} effects · {item.result.reversedCount??0} reversed · {item.result.interventions??0} interventions</p>{item.result.issue&&<p className="mt-2 text-sm text-amber-800">Needs review: {item.result.issue.replaceAll('_',' ')}</p>}<p className="mt-2 text-xs text-slate-500">Business outcome unmeasured. Provider calls: 0.</p></article>)}{board.nextBefore&&<button className={button} disabled={busy} onClick={()=>void load(board.nextBefore!)}>Load older commands</button>}</>}</section>
}
