'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {usePropertyContext} from '@/components/layout/PropertyContext'
import {PRODUCT_LABELS} from '@/utils/actions/catalog'
import {agencyProducts,currentWork,productLinks,type AgencyProduct} from '@/utils/agency/contracts'
import {planActions,planActionLabels,planStates,planBoard,planDocument,suggestedSteps,type PlanBoard,type PlanDocument,type PlanInput,type PlanRecord} from '@/utils/agency/plans'
import {agencyFetch} from '@/utils/agency/client'
import {planUrl,pendingPlan,postPlan,recoverPlan,type PendingPlan} from '@/utils/agency/plan-client'
const button='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-800 disabled:opacity-50'
const field='mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2 text-sm font-normal disabled:bg-slate-50'
const date=(v:string)=>new Date(v).toLocaleString()
export function AgencyPlans(){
 const {currentProperty,hasLoadedProperties}=usePropertyContext(),[product,setProduct]=useState<AgencyProduct>('siteforge')
 return <div className="mx-auto max-w-5xl p-4 sm:p-0"><Link href="/dashboard/agency" className="text-sm text-indigo-700 underline">Back to Agency review</Link><h1 className="mt-3 text-2xl font-semibold">Follow-up plans</h1><p className="mt-2 text-slate-600">Define the goal and review the steps for {currentProperty.name}. Each product has one current plan with retained revisions.</p><p className="my-5 rounded-xl border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-950">Draft and review only. Saving or reviewing a plan does not carry out its steps. Follow-up happens through the product’s existing controls and permissions.</p>
 <label className="block max-w-sm text-sm font-medium">Plan product<select className={field} value={product} onChange={e=>setProduct(e.target.value as AgencyProduct)}>{agencyProducts.map(p=><option key={p} value={p}>{PRODUCT_LABELS[p]}</option>)}</select></label>
 {hasLoadedProperties&&currentProperty.id?<Workbench key={`${currentProperty.id}:${product}`} propertyId={currentProperty.id} product={product}/>:<p className="mt-4">Select a property to prepare a plan.</p>}</div>
}
function Workbench({propertyId,product}:{propertyId:string;product:AgencyProduct}){
 const [board,setBoard]=useState<PlanBoard|null>(null),[history,setHistory]=useState<PlanRecord[]>([]),[next,setNext]=useState<string|null>(null),[pending,setPending]=useState<PendingPlan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const alive=useRef(false),lock=useRef(false),generation=useRef(0)
 async function refresh(){const current=++generation.current;const b=planBoard.parse(await agencyFetch(planUrl(propertyId,product)));if(current!==generation.current||!alive.current)return;if(b.propertyId!==propertyId||b.product!==product||!b.evidence)throw new Error('The plan does not match this property and product.');setBoard(b);setHistory(b.items);setNext(b.nextBefore)}
 useEffect(()=>{alive.current=true;setPending(pendingPlan(propertyId,product));void refresh().catch(()=>{if(alive.current)setError('The plan could not be loaded. Refresh to try again.')});return()=>{alive.current=false}
 // Each mount owns one property/product. Late responses cannot fill the next selection.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[])
 async function run(task:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await task()}catch(e){if(alive.current)setError(e instanceof Error?e.message:'The plan could not be confirmed.')}finally{lock.current=false;if(alive.current){setBusy(false);setPending(pendingPlan(propertyId,product))}}}
 async function save(input:PlanInput){await run(async()=>{const r=await postPlan(input);if(alive.current)setNotice(r.record.status==='reviewed'?'Plan review recorded. Follow-up remains a human decision.':r.record.status==='withdrawn'?'Plan withdrawn. Its history is retained.':'Draft saved. No work has been started.');await refresh()})}
 async function recover(close:boolean){if(!pending)return;await run(async()=>{const r=await recoverPlan(pending,close);if(alive.current)setNotice(r.record.kind==='save'?'Found your saved plan revision.':'Unused plan request closed.');await refresh()})}
 async function more(){if(!next)return;await run(async()=>{const b=planBoard.parse(await agencyFetch(planUrl(propertyId,product,{kind:'history',before:next})));if(b.propertyId!==propertyId||b.product!==product)throw new Error('The history does not match this plan.');if(alive.current){setHistory(old=>[...old,...b.items]);setNext(b.nextBefore)}})}
 return <><div className="my-5 flex flex-wrap items-center gap-3"><button className={button} disabled={busy} onClick={()=>void run(refresh)}>Refresh plan evidence</button><Link href={productLinks[product]} className="text-sm text-indigo-700 underline">Open {PRODUCT_LABELS[product]}</Link></div>
 {error&&<p role="alert" className="mb-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{error}</p>}{notice&&<p role="status" className="mb-4 text-sm text-emerald-800">{notice}</p>}
 {pending&&<section aria-label="Unconfirmed plan" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-medium">Check your earlier plan request</h2><p className="my-2 text-sm">Its reply was interrupted. Check the saved revision, or close the request if it was never saved.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void recover(false)}>Check saved plan</button><button className={button} disabled={busy} onClick={()=>void recover(true)}>Close unused plan request</button></div></section>}
 {!board&&!error&&<p className="text-sm text-slate-500">Loading the plan…</p>}
 {board?.evidence&&<><section aria-label="Plan source evidence" className="mb-5 rounded-xl border border-slate-200 p-4"><h2 className="font-semibold">Evidence for this draft</h2><p className="mt-2 text-sm">{board.evidence.failedCount} recorded failures in the dated action window · {currentWork(board.evidence)?.total||0} unfinished items in checked sources</p><p className="mt-1 text-xs text-slate-500">Captured {date(board.evidence.capturedAt)}. Missing checks and records do not establish readiness or provider health.</p>{!currentWork(board.evidence)?.checkedSources.length&&<p className="mt-2 text-sm text-amber-800">Current-work checks are not yet available for this product.</p>}{board.current?.evidence?.sourceHash!==board.evidence.sourceHash&&board.current&&<p className="mt-2 text-sm text-amber-800">Evidence has changed since the current plan revision. Review the new evidence before recording another decision.</p>}{currentWork(board.evidence)?.coverage&&<p className="mt-2 text-sm text-slate-600">{currentWork(board.evidence)!.coverage!.detail}</p>}<details className="mt-3 text-sm"><summary>Inspect the saved evidence references</summary>{board.evidence.failures.map(f=><p key={f.eventId} className="mt-2 break-all text-xs">Recorded failure: {f.action} · {date(f.recordedAt)} · {f.eventId}</p>)}{currentWork(board.evidence)?.items.map(w=><p key={`${w.source}:${w.id}`} className="mt-2 break-all text-xs">{w.category==='incident'?'Open incident':w.category==='unconfirmed'?'Unconfirmed result':'Held work'} · {w.id}</p>)}<p className="mt-2 text-xs">References are limited to five failures and the five oldest unfinished items; counts and the evidence fingerprint include the full checked set. Open the product for the complete work list.</p></details></section>
 {board.current&&<p className="mb-4 text-sm">Current revision {board.current.revision}: <strong>{planStates[board.current.status!]}</strong></p>}
 {!board.canManage&&<p className="mb-4 text-sm text-slate-500">A manager can save or review plans.</p>}
 <Editor key={board.current?.id||'new'} board={board} propertyId={propertyId} product={product} disabled={busy||!!pending||!board.canManage} save={save}/></>}
 <section aria-label="Plan revision history" className="mt-8 space-y-3"><h2 className="text-lg font-semibold">Plan and correction history</h2><p className="text-sm text-slate-600">Earlier goals, steps, evidence and human reasons remain available. A review is not proof that the goal was achieved.</p>{board&&!history.length&&<p className="text-sm text-slate-500">No plan revisions saved yet.</p>}{history.map(r=><article key={r.id} className="rounded-xl border border-slate-200 p-4"><h3 className="font-medium">{r.kind==='cancel_unused'?'Unused plan request closed':`Revision ${r.revision} · ${planStates[r.status!]}`}</h3><p className="mt-1 text-xs text-slate-500">{date(r.created_at)}</p>{r.plan&&<><p className="mt-3 whitespace-pre-wrap break-words text-sm"><strong>Goal:</strong> {r.plan.goal}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm"><strong>Success criteria:</strong> {r.plan.successMeasure}</p><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm">{r.plan.steps.map((s,i)=><li key={i}><span className="font-medium">{planActionLabels[s.action]}</span><p className="whitespace-pre-wrap break-words text-slate-600">{s.detail}</p></li>)}</ol></>}{r.reason&&<p className="mt-3 whitespace-pre-wrap break-words text-sm"><strong>Reason:</strong> {r.reason}</p>}<details className="mt-3 text-xs text-slate-500"><summary>Revision evidence</summary>{r.evidence&&<><p className="mt-2">Evidence captured {date(r.evidence.capturedAt)} · {r.evidence.failedCount} failures · {currentWork(r.evidence)?.total||0} unfinished items</p><p className="break-all">Source fingerprint: {r.evidence.sourceHash}</p></>}<p className="mt-2 break-all">Revision: {r.id}</p><p className="break-all">Previous revision: {r.previous_id||'First draft'}</p><p className="break-all">Author record: {r.actor_id}</p><p>Follow-up by people only; execution not authorized.</p></details></article>)}{next&&<button className={button} disabled={busy} onClick={()=>void more()}>Load older plan revisions</button>}</section></>
}
function Editor({board,propertyId,product,disabled,save}:{board:PlanBoard;propertyId:string;product:AgencyProduct;disabled:boolean;save:(input:PlanInput)=>Promise<void>}){
 const [plan,setPlan]=useState<PlanDocument>(board.current?.plan||{goal:'',successMeasure:'',steps:suggestedSteps(board.evidence!)}),[reason,setReason]=useState('')
 const valid=planDocument.safeParse(plan).success&&reason.trim().length>=3,same=!!board.current&&JSON.stringify(planDocument.safeParse(plan).success?planDocument.parse(plan):plan)===JSON.stringify(board.current.plan)
 function submit(status:PlanInput['status']){if(!valid||disabled||!board.evidence)return;void save({operation:'save',propertyId,product,previousId:board.current?.id||null,sourceHash:board.evidence.sourceHash,plan,status,reason})}
 return <section aria-label="Plan editor" className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">{board.current?'Revise or review the plan':'Create a draft'}</h2><p className="mt-2 text-sm text-slate-600">Steps are review suggestions you can edit. State the actual goal and how a person will check the result. Save changed content as a draft before recording its review.</p><fieldset disabled={disabled} className="mt-4 space-y-4"><label className="block text-sm font-medium">Goal<textarea className={field} rows={2} maxLength={1000} value={plan.goal} onChange={e=>setPlan({...plan,goal:e.target.value})}/></label><label className="block text-sm font-medium">Success criteria<textarea className={field} rows={2} maxLength={1000} value={plan.successMeasure} onChange={e=>setPlan({...plan,successMeasure:e.target.value})}/></label>
 <div className="space-y-4"><h3 className="text-sm font-semibold">Proposed steps</h3>{plan.steps.map((s,i)=><div key={i} className="rounded-lg border border-slate-200 p-3"><label className="block text-sm font-medium">Step {i+1} action<select className={field} value={s.action} onChange={e=>setPlan({...plan,steps:plan.steps.map((x,j)=>j===i?{...x,action:e.target.value as typeof s.action}:x)})}>{planActions.map(a=><option key={a} value={a}>{planActionLabels[a]}</option>)}</select></label><label className="mt-3 block text-sm font-medium">Step {i+1} details<textarea className={field} rows={2} maxLength={1200} value={s.detail} onChange={e=>setPlan({...plan,steps:plan.steps.map((x,j)=>j===i?{...x,detail:e.target.value}:x)})}/></label><button type="button" className={`${button} mt-2`} disabled={disabled||plan.steps.length===1} onClick={()=>setPlan({...plan,steps:plan.steps.filter((_,j)=>j!==i)})}>Remove step {i+1}</button></div>)}<button type="button" className={button} disabled={disabled||plan.steps.length>=8} onClick={()=>setPlan({...plan,steps:[...plan.steps,{action:'inspect_work',detail:''}]})}>Add step</button></div>
 <label className="block text-sm font-medium">Reason for this version<textarea className={field} rows={2} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={disabled||!valid} onClick={()=>submit('draft')}>Save draft</button><button type="button" className={button} disabled={disabled||!valid||!same||board.current?.status==='withdrawn'} onClick={()=>submit('reviewed')}>Record plan review</button><button type="button" className={button} disabled={disabled||!valid||!same||board.current?.status==='withdrawn'} onClick={()=>submit('withdrawn')}>Withdraw plan</button></div></fieldset></section>
}
