'use client'
import {useCallback,useEffect,useState,useRef} from 'react'
import {pricingFields,type ExtractionPreview} from '@/utils/marketvision/extraction-contracts'
import {sendMarketDecision,marketNumber} from '@/utils/marketvision/decision-client'
type Field=typeof pricingFields[number]
type Draft=Record<Field,string>
interface SavedRequest{id:string;state:string;version:number;preview:ExtractionPreview|null;preview_hash:string|null;input:{content:string;sourceUrl:string;effectiveAt:string|null;reason:string};error_code:string|null;sourceProvenance?:{fetchedAt:string;finalUrl:string;textTruncated:boolean;bodyHash:string}|null;baselineChanged:boolean;model:string;review_context:{units:Array<Record<string,unknown>>}|null}
interface Row{id:string;state:string;reason:string;createdAt:string;candidateCount:number|null}
const labels:Record<Field,string>={unit_type:'Unit type',bedrooms:'Bedrooms',bathrooms:'Bathrooms',sqft_min:'Minimum area (sq ft)',sqft_max:'Maximum area (sq ft)',rent_min:'Minimum monthly rent ($)',rent_max:'Maximum monthly rent ($)',deposit:'Deposit ($)',available_count:'Available units',move_in_specials:'Move-in specials'}
const states:Record<string,string>={queued:'Waiting to start',running:'Extraction in progress',result_ready:'Model result saved',preview_ready:'Ready for review',held:'Needs attention',stopped:'Stopped',completed:'Applied'}
const issues:Record<string,string>={invalid_output:'The model result did not meet the saved extraction contract. Inspect the source and start a new request with clearer content if needed.',incomplete_output:'The model did not return a complete response. The receipt is retained; no unit values were applied.',model_uncertain:'The model outcome is unconfirmed. Recovery will not repeat that invocation.',invocation_unconfirmed:'The started model request has not returned a confirmed result. Check its status or stop application.',source_or_access_changed:'The competitor or requester access changed before execution. Review the current property and save a new request.',unsupported_pricing_basis:'The saved result does not establish the supported monthly rental pricing basis.'}
const toDraft=(u:ExtractionPreview['units'][number])=>Object.fromEntries(pricingFields.map(k=>[k,u[k]===null?'':String(u[k])])) as Draft
const display=(v:unknown)=>v===null||v===undefined?'Unknown':String(v)
export function CompetitorExtractionPanel({propertyId,competitorId,onApplied,openRequestId}:{propertyId:string;competitorId:string;onApplied:()=>void;openRequestId?:string}){
 const [rows,setRows]=useState<Row[]>([]),[cursor,setCursor]=useState<string|null>(null),[version,setVersion]=useState(0),[selected,setSelected]=useState<SavedRequest|null>(null),[execution,setExecution]=useState({paused:true,configured:false}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [content,setContent]=useState(''),[url,setUrl]=useState(''),[effective,setEffective]=useState(''),[requestReason,setRequestReason]=useState(''),[reason,setReason]=useState(''),[drafts,setDrafts]=useState<Draft[]>([]),[chosen,setChosen]=useState<number[]>([]),[confirmed,setConfirmed]=useState(false)
 const generation=useRef(0)
 const invalidate=useCallback(()=>{generation.current++},[])
 const load=useCallback(async(id?:string,after?:string)=>{const current=++generation.current;setBusy(true);setError('');try{const p=new URLSearchParams({propertyId,competitorId,...(id?{requestId:id}:{}),...(after?{cursor:after}:{})}),r=await fetch(`/api/marketvision/extract-pricing?${p}`),d=await r.json();if(!r.ok)throw new Error(d.error||'Saved extractions could not be loaded.');if(current!==generation.current)return;setExecution(d.execution);setLoaded(true);if(id){setSelected(d.request);setDrafts(d.request.preview?.units.map(toDraft)??[]);setChosen([]);setConfirmed(false)}else{setRows(v=>after?[...v,...d.requests]:d.requests);setCursor(d.nextCursor);setVersion(d.competitorVersion)}}catch(e){if(current!==generation.current)return;setLoaded(false);setError(e instanceof Error?e.message:'Saved extractions could not be loaded.')}finally{if(current===generation.current)setBusy(false)}},[propertyId,competitorId])
 useEffect(()=>{void load(openRequestId);return invalidate},[load,openRequestId,invalidate])
 const selectedId=selected?.id,selectedState=selected?.state
 useEffect(()=>{if(!selectedId||!selectedState||!['queued','running','result_ready'].includes(selectedState)||execution.paused)return;const id=selectedId;let polls=0;const timer=setInterval(()=>{polls++;if(polls>12){clearInterval(timer);return}void load(id)},5000);return()=>clearInterval(timer)},[selectedId,selectedState,execution.paused,load])
 const request=async()=>{setBusy(true);setError('');setMessage('');try{const d=await sendMarketDecision('/api/marketvision/extract-pricing','POST',{propertyId,competitorId,sourceVersion:version,content,sourceUrl:url,effectiveAt:effective?new Date(effective).toISOString():null,reason:requestReason},['queued','running','result_ready','preview_ready','held','stopped','completed','busy']);setMessage(d.result.state==='busy'?'An earlier extraction is still open. Review or stop that saved request first.':['held','stopped','completed'].includes(d.result.state)?'This exact request already exists. Inspect its retained outcome; use a new reviewed source or reason for a different request.':'Source request saved.');await load(d.result.requestId)}catch(e){setError(e instanceof Error?e.message:'The source request could not be confirmed.')}finally{setBusy(false)}}
 const control=async(action:'stop'|'recover'|'rebase')=>{if(!selected)return;setBusy(true);setError('');setMessage('');try{await sendMarketDecision('/api/marketvision/extract-pricing','PUT',{propertyId,extractionId:selected.id,expectedVersion:selected.version,action,reason});setReason('');setMessage(action==='rebase'?'Current saved values loaded. Review and select the candidates again.':action==='stop'?'Application stopped. A late model receipt may still be retained.':'Recovery requested from saved state.');await load(selected.id)}catch(e){setError(e instanceof Error?e.message:'The extraction decision could not be confirmed.')}finally{setBusy(false)}}
 const apply=async()=>{if(!selected)return;setBusy(true);setError('');setMessage('');try{const selection=chosen.map(sourceIndex=>({sourceIndex,values:Object.fromEntries(pricingFields.map(k=>[k,k==='unit_type'?drafts[sourceIndex][k].trim():k==='move_in_specials'?drafts[sourceIndex][k].trim()||null:marketNumber(drafts[sourceIndex][k])]))}));const d=await sendMarketDecision('/api/marketvision/extract-pricing','PATCH',{propertyId,extractionId:selected.id,expectedVersion:selected.version,previewHash:selected.preview_hash,confirmedMonthlyRentUsd:confirmed,selection,reason});setMessage(`${d.result.savedUnits} reviewed unit types saved together. Unselected unit types were retained.`);setReason('');await load(selected.id);onApplied()}catch(e){setError(e instanceof Error?e.message:'The reviewed prices could not be confirmed.')}finally{setBusy(false)}}
 const open=selected&&!['completed','stopped'].includes(selected.state)
 return <section aria-label="Saved source extraction" className="rounded-xl border p-4 space-y-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">Extract pricing from a source</h3><button disabled={busy} onClick={()=>load(selected?.id)} className="text-sm underline">Reload extraction status</button></div><p className="text-sm text-gray-500">Keep the source, review its suggested monthly rental values, and choose what to save. A pasted page is operator-supplied evidence; it is not a verified provider fetch.</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-700">{message}</p>}{execution.paused?<p className="text-sm text-amber-700">External execution is paused. Requests can be saved; models will not be called.</p>:!execution.configured?<p className="text-sm text-amber-700">Model access is not configured. Saved requests have not been started.</p>:null}
 {!selected&&<><form aria-label="New source extraction" onSubmit={e=>{e.preventDefault();void request()}} className="space-y-3"><fieldset disabled={busy||!loaded} className="space-y-3 min-w-0"><label className="block text-sm">Pasted floor plan and rental source<textarea required minLength={50} maxLength={50000} rows={6} value={content} onChange={e=>setContent(e.target.value)} className="block w-full rounded border p-2 mt-1" /></label><label className="block text-sm">Public source page (optional)<input type="url" value={url} onChange={e=>setUrl(e.target.value)} className="block w-full rounded border p-2 mt-1" /></label><label className="block text-sm">Source observation time (optional)<input type="datetime-local" value={effective} onChange={e=>setEffective(e.target.value)} className="block w-full rounded border p-2 mt-1" /></label><label className="block text-sm">Reason for extraction<textarea required minLength={3} maxLength={2000} value={requestReason} onChange={e=>setRequestReason(e.target.value)} className="block w-full rounded border p-2 mt-1" /></label><button type="submit" className="border rounded px-3 py-2 text-sm">Save source and request extraction</button></fieldset></form><div className="space-y-2 border-t pt-3"><h4 className="font-medium">Saved extraction requests</h4>{rows.map(r=><button key={r.id} disabled={busy} onClick={()=>load(r.id)} className="block w-full text-left text-sm border rounded p-2"><span className="font-medium">{states[r.state]||r.state}</span> · {new Date(r.createdAt).toLocaleString()}<span className="block">{r.reason}</span></button>)}{loaded&&!error&&!rows.length&&<p className="text-sm text-gray-500">No saved source requests yet.</p>}{cursor&&<button disabled={busy} onClick={()=>load(undefined,cursor)} className="text-sm underline">Load more extraction requests</button>}</div></>}
 {selected&&<article aria-label="Current extraction" className="space-y-3"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium">{states[selected.state]||selected.state}</h4><button disabled={busy} onClick={()=>{setSelected(null);setReason('');void load()}} className="underline text-sm">Back to source requests</button></div>{selected.error_code&&<p className="text-sm text-amber-700">{issues[selected.error_code]||'The saved request needs review.'}</p>}<details className="border rounded p-2 text-sm"><summary>Retained source and provenance</summary><p className="mt-2">{selected.input.reason}</p>{selected.input.sourceUrl&&<a href={selected.input.sourceUrl} target="_blank" rel="noreferrer" className="underline break-all">{selected.sourceProvenance?'Retained fetched page':'Source page reported by operator'}</a>}<p>{selected.input.effectiveAt?`Reported source time: ${new Date(selected.input.effectiveAt).toLocaleString()}`:'Source observation time is unknown.'}</p>{selected.sourceProvenance&&<><p>Page fetched: {new Date(selected.sourceProvenance.fetchedAt).toLocaleString()}. Static page text only; this is separate from the unknown price effective date.</p>{selected.sourceProvenance.textTruncated&&<p>Extraction used the first 50,000 characters of readable page text.</p>}<p className="break-all text-xs">Retained page hash: {selected.sourceProvenance.bodyHash}</p></>}<p>Model: {selected.model}. The original result remains retained after corrections.</p><pre className="whitespace-pre-wrap break-words text-xs mt-2 max-h-72 overflow-auto">{selected.input.content}</pre></details>
 {selected.state==='preview_ready'&&selected.preview&&<><p className="text-sm">{selected.preview.units.length} saved candidates. Selected values replace a matching unit type; other unit types remain unchanged. Empty fields mean unknown and may clear an older value.</p>{selected.preview.pricingBasis==='unconfirmed'&&<p className="text-sm text-amber-700">The model did not establish monthly rent in USD. Confirm the actual source basis before applying any price.</p>}{selected.preview.notes&&<p className="text-sm text-gray-600">Model notes: {selected.preview.notes}</p>}{selected.baselineChanged&&<p role="alert" className="text-sm text-amber-700">Saved competitor or unit values changed. Refresh the comparison below and review the current values before applying.</p>}{drafts.map((draft,index)=>{const prior=selected.review_context?.units.find(u=>u.unit_type===draft.unit_type.trim());return <details key={index} open={index===0} className="border rounded p-3 space-y-2"><summary className="cursor-pointer font-medium">Candidate {index+1}: {selected.preview!.units[index].unit_type}</summary><label className="flex gap-2 items-center text-sm"><input type="checkbox" disabled={busy||selected.baselineChanged} checked={chosen.includes(index)} onChange={e=>{setChosen(v=>e.target.checked?[...v,index]:v.filter(n=>n!==index));setConfirmed(false)}}/>Select candidate {index+1} for application</label><p className="text-xs text-gray-500">{prior?'Updates the existing matching unit type.':'Creates a new unit type.'}</p><fieldset disabled={busy||selected.baselineChanged} className="grid sm:grid-cols-2 gap-3 min-w-0">{pricingFields.map(field=><label key={field} className="text-sm">{labels[field]}<input aria-label={`Candidate ${index+1} ${labels[field]}`} type={['unit_type','move_in_specials'].includes(field)?'text':'number'} min="0" step={['rent_min','rent_max','deposit'].includes(field)?'0.01':field==='bathrooms'?'0.1':'1'} value={draft[field]} onChange={e=>{setDrafts(v=>v.map((d,n)=>n===index?{...d,[field]:e.target.value}:d));setConfirmed(false)}} className="block w-full border rounded p-2 mt-1"/><span className="block text-xs text-gray-500">Saved: {prior?display(prior[field]):'No matching unit'}</span></label>)}</fieldset><details className="text-sm"><summary>Quoted source evidence</summary>{selected.preview!.units[index].evidence.map((e,n)=><blockquote key={n} className="border-l-2 pl-2 my-2"><span className="font-medium">{labels[e.field]}:</span> {e.quote}</blockquote>)}</details></details>})}<label className="flex gap-2 items-start text-sm"><input type="checkbox" disabled={busy||selected.baselineChanged} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I checked the selected values against the source, including unknowns and replacements. Prices represent monthly rent in USD.</span></label></>}
 {open&&<><label className="block text-sm">Reason for extraction decision<textarea minLength={3} maxLength={2000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} className="block w-full border rounded p-2 mt-1" /></label><div className="flex flex-wrap gap-2">{selected.state==='preview_ready'?<><button disabled={busy||!confirmed||!chosen.length||selected.baselineChanged||reason.trim().length<3} onClick={apply} className="border rounded px-3 py-2 text-sm disabled:opacity-50">Apply selected reviewed units</button>{selected.baselineChanged&&<button disabled={busy||reason.trim().length<3} onClick={()=>control('rebase')} className="border rounded px-3 py-2 text-sm">Refresh saved comparison</button>}</>:<button disabled={busy||reason.trim().length<3} onClick={()=>control('recover')} className="border rounded px-3 py-2 text-sm">Recover saved extraction</button>}<button disabled={busy||reason.trim().length<3} onClick={()=>control('stop')} className="border rounded px-3 py-2 text-sm">Stop extraction</button></div></>}{selected.state==='completed'&&<p className="text-sm text-emerald-700">The reviewed values and source evidence were saved together. Saving did not call the model again or mark the competitor as freshly scraped.</p>}</article>}{busy&&<p className="text-sm" role="status">Loading or saving extraction…</p>}</section>
}
