'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {sendMarketDecision} from '@/utils/marketvision/decision-client'
import type {BriefRecommendation} from '@/utils/marketvision/saved-brief'
import type {HandoffDetail,HandoffSummary} from '@/utils/marketvision/handoff-contracts'
import {marketDate} from './MarketEvidence'
interface Props {initialHandoffId?:string;propertyId:string;briefId:string;version:number;sourceCurrent:boolean;recommendations:BriefRecommendation[];reviews:Array<{id:string;kind:string;input:{recommendationId?:string;decision?:string}}>;disabled:boolean}
const states={prepared:'Awaiting manager approval',completed:'Draft created',rejected:'Rejected',withdrawn:'Withdrawn'}
export function MarketHandoffs({propertyId,briefId,version,sourceCurrent,recommendations,reviews,disabled,initialHandoffId}:Props){
 const [items,setItems]=useState<HandoffSummary[]>([]),[cursor,setCursor]=useState<string|null>(null),[detail,setDetail]=useState<HandoffDetail|null>(null)
 const [loading,setLoading]=useState(true),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState('')
 const [recId,setRecId]=useState(''),[title,setTitle]=useState(''),[objective,setObjective]=useState(''),[channel,setChannel]=useState('facebook'),[format,setFormat]=useState('image'),[reason,setReason]=useState(''),[decisionReason,setDecisionReason]=useState('')
 const controller=useRef<AbortController|null>(null)
 const read=useCallback(async(extra:Record<string,string>,signal:AbortSignal)=>{const response=await fetch(`/api/marketvision/handoffs?${new URLSearchParams({propertyId,briefId,...extra})}`,{signal,cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Handoff history could not be loaded.');return data},[propertyId,briefId])
 const load=useCallback(async(id?:string,next?:string)=>{controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);setReady(false);setError(null)
  try{const data=await read(next?{cursor:next}:{},c.signal),selected=id??(!next?data.handoffs[0]?.id:undefined),saved=selected?await read({handoffId:selected},c.signal):null;if(c.signal.aborted)return;setItems(old=>next?[...old,...data.handoffs]:data.handoffs);setCursor(data.nextCursor);if(saved)setDetail(saved);else if(!next)setDetail(null);setReady(true)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Handoff history could not be loaded.')}finally{if(!c.signal.aborted)setLoading(false)}
 },[read])
 useEffect(()=>{void load(initialHandoffId);return()=>controller.current?.abort()},[load,initialHandoffId])
 const open=async(id:string)=>{controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);setReady(false);setError(null);try{const saved=await read({handoffId:id},c.signal);if(!c.signal.aborted){setDetail(saved);setDecisionReason('');setReady(true)}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'The saved handoff could not be loaded.')}finally{if(!c.signal.aborted)setLoading(false)}}
 const lastReview=(id:string)=>reviews.filter(r=>r.kind==='brief.reviewed'&&r.input.recommendationId===id).at(-1)
 const eligible=recommendations.filter(r=>r.kind==='comparison_review'&&lastReview(r.id)?.input.decision==='consider')
 const selected=eligible.find(r=>r.id===recId),locked=disabled||busy||loading||!ready
 const prepare=async()=>{if(!selected)return;setBusy(true);setError(null);setMessage('');try{const result=await sendMarketDecision('/api/marketvision/handoffs','POST',{propertyId,briefId,expectedVersion:version,recommendationId:selected.id,expectedReviewId:lastReview(selected.id)!.id,title,objective,channel,format,reason},['saved','replayed'],true);await load(String(result.result.handoffId));setMessage('Exact draft saved for manager approval. No content generation or delivery has started.')}catch(e){setError(e instanceof Error?e.message:'The handoff could not be confirmed.')}finally{setBusy(false)}}
 const decide=async(decision:'approve'|'reject'|'withdraw')=>{if(!detail)return;setBusy(true);setError(null);setMessage('');try{await sendMarketDecision('/api/marketvision/handoffs','PUT',{propertyId,handoffId:detail.handoff.id,expectedVersion:detail.handoff.version,draftHash:detail.handoff.draft_hash,decision,reason:decisionReason});await load(detail.handoff.id);setMessage(decision==='approve'?'One reviewed draft was created in ForgeStudio. Generation and publishing need their own review.':'The handoff decision was saved.')}catch(e){setError(e instanceof Error?e.message:'The decision could not be confirmed.')}finally{setBusy(false)}}
 const h=detail?.handoff,canDecide=!locked&&decisionReason.trim().length>=3
 return <section aria-label="ForgeStudio handoffs" className="space-y-4 rounded-xl border bg-slate-50 p-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-semibold">ForgeStudio draft handoffs</h4><button disabled={busy||disabled} onClick={()=>void load(h?.id)} className="rounded border bg-white px-3 py-2 text-sm disabled:opacity-50">Reload handoffs</button></div>
  <p className="text-sm text-slate-600">A considered comparison can guide a draft topic. A manager approves the exact draft below. Competitor information remains advisory and does not become an approved claim about your property.</p>
  {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{message&&<p role="status" className="rounded bg-emerald-50 p-3 text-emerald-800">{message}</p>}{loading&&<p role="status">Loading saved handoffs…</p>}
  {!sourceCurrent&&<p className="text-sm text-amber-800">Create and review a current brief before preparing another draft.</p>}
  {sourceCurrent&&eligible.length>0&&<details className="rounded border bg-white p-3"><summary>Prepare a draft for approval</summary><div className="mt-3 space-y-3">
   <label className="block text-sm">Reviewed comparison<select value={recId} disabled={locked} onChange={e=>{setRecId(e.target.value);const r=eligible.find(r=>r.id===e.target.value);if(r)setTitle(r.title)}} className="mt-1 block w-full rounded border p-2"><option value="">Select a considered comparison</option>{eligible.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>
   <label className="block text-sm">Draft title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={300} disabled={locked} className="mt-1 block w-full rounded border p-2"/></label>
   <label className="block text-sm">Draft objective<textarea value={objective} onChange={e=>setObjective(e.target.value)} maxLength={2000} disabled={locked} className="mt-1 block w-full rounded border p-2"/></label>
   <div className="flex flex-wrap gap-3"><label className="text-sm">Draft channel<select value={channel} disabled={locked} onChange={e=>{setChannel(e.target.value);setFormat(e.target.value==='tiktok'?'video':'image')}} className="ml-2 rounded border p-2">{['facebook','instagram','linkedin','tiktok','x'].map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">Draft format<select value={format} disabled={locked} onChange={e=>setFormat(e.target.value)} className="ml-2 rounded border p-2">{(channel==='tiktok'?['video','reel']:channel==='instagram'?['image','video','reel','carousel','story']:['text','image','video','reel','carousel','story']).map(f=><option key={f}>{f}</option>)}</select></label></div>
   <label className="block text-sm">Reason for draft handoff<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} disabled={locked} className="mt-1 block w-full rounded border p-2"/></label>
   <button disabled={locked||!selected||!title.trim()||!objective.trim()||reason.trim().length<3} onClick={()=>void prepare()} className="rounded bg-indigo-700 px-4 py-2 text-white disabled:opacity-50">Save draft for approval</button>
  </div></details>}
  {sourceCurrent&&eligible.length===0&&<p className="text-sm">Mark a pricing comparison for consideration before preparing a draft. Source coverage prompts need verified source records first.</p>}
  {ready&&items.length===0&&<p className="text-sm">No handoffs for this saved brief.</p>}
  {items.length>0&&<ul className="space-y-2">{items.map(i=><li key={i.id}><button onClick={()=>void open(i.id)} disabled={busy||loading||disabled} className="w-full rounded border bg-white p-3 text-left disabled:opacity-50"><span className="block font-medium">{i.title}</span><span className="text-sm">{states[i.state]} · {marketDate(i.createdAt)}</span></button></li>)}</ul>}{cursor&&<button disabled={locked} onClick={()=>void load(h?.id,cursor)} className="text-sm text-indigo-700">Older handoffs</button>}
  {h&&detail&&ready&&<article className="space-y-3 rounded border bg-white p-4"><h5 className="font-semibold">Saved draft for approval</h5><p className="text-sm">{states[h.state]} · prepared {marketDate(h.created_at)}</p><p className="font-medium">{h.draft.title}</p><p className="whitespace-pre-wrap text-sm">{h.draft.objective}</p><p className="text-sm">{h.draft.formatPlan.map(f=>`${f.quantity} ${f.contentFormat} for ${f.platform}`).join(', ')}</p><p className="text-sm">Reason: {h.input.reason}</p>
   <details className="rounded border p-3"><summary>Advisory evidence and draft constraints</summary><ul className="mt-2 list-disc space-y-2 pl-5 text-sm">{[...h.draft.sourceFacts.map(f=>f.text),...h.draft.constraints.mustInclude,...h.draft.constraints.mustAvoid].map(t=><li key={t}>{t}</li>)}</ul></details>
   {(detail.sourceChanged!==false||detail.reviewChanged)&&<p role="alert" className="rounded bg-amber-50 p-3 text-sm">The source check or recommendation review changed. This draft remains saved; prepare a new handoff from a current reviewed brief before approval.</p>}
   {h.state==='prepared'&&<><label className="block text-sm">Reason for handoff decision<textarea value={decisionReason} onChange={e=>setDecisionReason(e.target.value)} disabled={locked} maxLength={2000} className="mt-1 block w-full rounded border p-2"/></label><div className="flex flex-wrap gap-3">{detail.canApprove?<><button disabled={!canDecide||detail.sourceChanged!==false||detail.reviewChanged} onClick={()=>void decide('approve')} className="rounded bg-indigo-700 px-4 py-2 text-white disabled:opacity-50">Approve and create draft</button><button disabled={!canDecide} onClick={()=>void decide('reject')} className="rounded border px-3 py-2 disabled:opacity-50">Reject handoff</button></>:<p className="text-sm">A current property manager must approve this draft.</p>}{detail.canWithdraw&&<button disabled={!canDecide} onClick={()=>void decide('withdraw')} className="rounded border px-3 py-2 disabled:opacity-50">Withdraw handoff</button>}</div></>}
   {h.receipt?.contentBriefId&&<Link href={`/dashboard/forgestudio?tab=campaigns&briefId=${h.receipt.contentBriefId}`} className="inline-block rounded border px-3 py-2 text-indigo-700">Open saved ForgeStudio draft</Link>}
   <p className="text-xs text-slate-600">This approval creates a draft only. It does not generate content, publish, change rents or establish a business outcome.</p>
  </article>}
 </section>
}
