'use client'
import {MarketHandoffs} from './MarketHandoffs'
import {useCallback,useEffect,useRef,useState} from 'react'
import {sendMarketDecision} from '@/utils/marketvision/decision-client'
import type {SavedMarketBrief,BriefRecommendation} from '@/utils/marketvision/saved-brief'
import {MarketEvidence,marketDate,marketMoney} from './MarketEvidence'
interface Item{id:string;state:string;version:number;createdAt:string;windowDays:number;reason:string}
interface Decision{id:string;kind:string;input:{recommendationId?:string;decision?:string;reason:string};result:Record<string,unknown>;createdAt:string}
interface Detail {report:{id:string;state:string;version:number;result:SavedMarketBrief|null;created_at:string;input:{reason:string;windowDays:number}};sourceChanged:boolean|null;currentEvidenceState:string;decisions:Decision[]}
function RecordedChanges({report}:{report:SavedMarketBrief}){
 const [page,setPage]=useState(0),rows=report.analysis.changes
 return <section aria-label="Recorded pricing changes"><h4 className="font-semibold">Recorded pricing changes ({rows.length})</h4>
  {rows.length===0?<p className="mt-2 text-sm text-slate-600">No comparable price changes were saved in this window. This does not establish that live prices stayed unchanged.</p>:<><ul className="mt-3 space-y-3">{rows.slice(page*20,(page+1)*20).map(c=><li key={`${c.unitId}:${c.citations.at(-1)?.historyId}`} className="rounded border p-3"><p className="font-medium">{c.competitorName} · {c.unitType}</p><p className="text-sm">{marketMoney(c.previousValue)} → {marketMoney(c.currentValue)} · saved {marketDate(c.recordedAt)}</p><MarketEvidence evidence={c.citations}/></li>)}</ul>{rows.length>20&&<div className="mt-3 flex flex-wrap gap-3"><button disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous changes</button><span>Page {page+1} of {Math.ceil(rows.length/20)}</span><button disabled={(page+1)*20>=rows.length} onClick={()=>setPage(v=>v+1)}>More changes</button></div>}</>}
  <p className="mt-3 text-sm text-slate-600">Comparable history covers {report.analysis.trendCoverage.matchedPlans} plans across {report.analysis.trendCoverage.matchedCompetitors} competitors. {report.analysis.trendCoverage.netChangePct===null?'Insufficient evidence for a percentage movement.':`Mean saved starting rent changed ${report.analysis.trendCoverage.netChangePct}% within that fixed sample.`}</p>
 </section>
}
function HistoricalBrief({value}:{value:unknown}){
 const saved=value&&typeof value==='object'?value as Record<string,unknown>:{},raw=saved.data&&typeof saved.data==='object'?saved.data as Record<string,unknown>:{},rows=(key:string)=>Array.isArray(raw[key])?raw[key].filter((v):v is Record<string,unknown>=>v!==null&&typeof v==='object'):[]
 const plain=(v:unknown)=>typeof v==='string'||typeof v==='number'?String(v):'Unknown'
 return <article className="mt-3 space-y-3 rounded border p-3 text-sm"><h4 className="font-semibold">Unverified historical narrative</h4><p>Originally generated: {typeof saved.generatedAt==='string'?marketDate(saved.generatedAt):'Unknown'}</p>
  {rows('changes').map((r,i)=><p key={`c${i}`}>{plain(r.competitorName)} · {plain(r.unitType)}: {plain(r.previousValue)} → {plain(r.currentValue)}</p>)}
  {rows('insights').map((r,i)=><div key={`i${i}`}><h5 className="font-medium">{plain(r.headline)}</h5><p>{plain(r.detail)}</p></div>)}
  {rows('recommendations').map((r,i)=><div key={`r${i}`}><h5 className="font-medium">{plain(r.title)}</h5><p>{plain(r.rationale)}</p></div>)}
  <p className="text-slate-600">Original confidence and revenue claims are historical assertions. Create a saved-source brief before acting on them.</p>
 </article>
}
export function MarketBriefView({propertyId,openRequestId,openHandoffId}:{propertyId:string;openRequestId?:string;openHandoffId?:string}){
 const [items,setItems]=useState<Item[]>([]),[cursor,setCursor]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[reason,setReason]=useState(''),[days,setDays]=useState('30'),[reviewReason,setReviewReason]=useState(''),[ack,setAck]=useState(false),[message,setMessage]=useState(''),[legacyCount,setLegacyCount]=useState(0),[legacy,setLegacy]=useState<{id:string;createdAt:string|null}[]>([]),[legacyCursor,setLegacyCursor]=useState<string|null>(null),[legacyData,setLegacyData]=useState<unknown>(null)
 const generation=useRef(0)
 const read=useCallback(async(query:Record<string,string>)=>{const res=await fetch(`/api/marketvision/brief?${new URLSearchParams({propertyId,...query})}`,{cache:'no-store'}),data=await res.json();if(!res.ok)throw new Error(data.error||'Saved briefs could not be loaded.');return data},[propertyId])
 const load=useCallback(async(id?:string,next?:string)=>{const g=++generation.current;setLoading(true);setReady(false);setError(null);try{
   const list=await read(next?{cursor:next}:{})
   if(g!==generation.current)return
   setItems(old=>next?[...old,...list.reports]:list.reports);setCursor(list.nextCursor);setLegacyCount(list.legacyCount)
   const selected=id??list.reports[0]?.id
   const d=selected?await read({requestId:selected}):null
   if(g!==generation.current)return
   setDetail(d);setAck(false);setReviewReason('');setReady(true)
 }catch(e){if(g===generation.current){setDetail(null);setError(e instanceof Error?e.message:'Saved briefs could not be loaded.')}}finally{if(g===generation.current)setLoading(false)}},[read])
 useEffect(()=>{const counter=generation;void load(openRequestId);return()=>{counter.current++}},[load,openRequestId])
 const open=async(id:string)=>{const g=++generation.current;setLoading(true);setReady(false);setError(null);try{const d=await read({requestId:id});if(g!==generation.current)return;setDetail(d);setAck(false);setReviewReason('');setReady(true)}catch(e){if(g===generation.current){setDetail(null);setError(e instanceof Error?e.message:'This brief could not be loaded.')}}finally{if(g===generation.current)setLoading(false)}}
 const generate=async()=>{setBusy(true);setError(null);setMessage('');const g=generation.current;try{const data=await sendMarketDecision('/api/marketvision/brief','POST',{propertyId,windowDays:Number(days),reason},['ready'],true);if(g!==generation.current)return;setReason('');await load(String(data.result.requestId));setMessage('Saved brief completed from its exact retained evidence.')}catch(e){if(g===generation.current)setError(e instanceof Error?e.message:'The brief could not be confirmed.')}finally{setBusy(false)}}
 const recover=async()=>{if(!detail)return;setBusy(true);setError(null);try{await sendMarketDecision('/api/marketvision/brief','PUT',{propertyId,briefId:detail.report.id,expectedVersion:detail.report.version,reason:reviewReason},['ready']);await load(detail.report.id);setMessage('The original saved report was completed without acquiring new sources.')}catch(e){setError(e instanceof Error?e.message:'Recovery could not be confirmed.')}finally{setBusy(false)}}
 const review=async(rec:BriefRecommendation,decision:'consider'|'dismiss')=>{if(!detail)return;setBusy(true);setError(null);try{const last=detail.decisions.filter(d=>d.kind==='brief.reviewed'&&d.input.recommendationId===rec.id).at(-1);await sendMarketDecision('/api/marketvision/brief/review','POST',{propertyId,briefId:detail.report.id,expectedVersion:detail.report.version,recommendationId:rec.id,expectedReviewId:last?.id??null,decision,acknowledgedSourceChange:ack,reason:reviewReason});await open(detail.report.id);setMessage('Recommendation review recorded. No pricing change or downstream work was started.')}catch(e){setError(e instanceof Error?e.message:'Review could not be confirmed.')}finally{setBusy(false)}}
 const download=async(format:'json'|'markdown')=>{if(!detail)return;setBusy(true);setError(null);try{const data=await sendMarketDecision('/api/marketvision/brief/export','POST',{propertyId,briefId:detail.report.id,expectedVersion:detail.report.version,format,reason:reviewReason}),content=String(data.result.content),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content))),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==data.result.contentHash)throw new Error('Download bytes did not match the saved artifact. Retry the same download.');const url=URL.createObjectURL(new Blob([content],{type:format==='json'?'application/json':'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`market-brief-${detail.report.id}.${format==='json'?'json':'md'}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);await open(detail.report.id);setMessage('Exact report file prepared and download requested. File receipt is not confirmed.')}catch(e){setError(e instanceof Error?e.message:'The download could not be prepared.')}finally{setBusy(false)}}
 const loadLegacy=async(next?:string,id?:string)=>{setError(null);setBusy(true);try{const data=await read({view:'legacy',...(next?{cursor:next}:{}),...(id?{requestId:id}:{})});if(id)setLegacyData(data.legacyReport);else{setLegacy(old=>next?[...old,...data.legacyReports]:data.legacyReports);setLegacyCursor(data.nextCursor)}}catch(e){setError(e instanceof Error?e.message:'Historical reports could not be loaded.')}finally{setBusy(false)}}
 const report=detail?.report.result,canDecide=ready&&!busy&&!loading&&reviewReason.trim().length>=3
 return <section aria-label="Saved market briefs" className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Market brief</h2><button disabled={busy||loading} onClick={()=>void load(detail?.report.id)} className="rounded border px-3 py-2 text-sm disabled:opacity-50">Reload saved briefs</button></div>
  <p className="text-sm text-slate-600">Save an exact pricing snapshot to review, revisit or download. Creating a brief uses existing records and does not fetch pages or call a model.</p>
  {error&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-red-700">{error}</p>}{message&&<p role="status" className="rounded bg-emerald-50 p-3 text-emerald-800">{message}</p>}
  <div className="rounded-xl border bg-white p-4"><h3 className="font-semibold">Prepare a new brief</h3><label className="mt-3 block text-sm">Reporting window <select value={days} disabled={busy} onChange={e=>setDays(e.target.value)} className="ml-2 rounded border p-2">{[7,30,60,90].map(d=><option key={d} value={d}>{d} days</option>)}</select></label><label className="mt-3 block text-sm">Reason for this brief<textarea value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} maxLength={2000} className="mt-1 block w-full rounded border p-2"/></label><button disabled={!ready||busy||loading||reason.trim().length<3} onClick={()=>void generate()} className="mt-3 rounded bg-indigo-700 px-4 py-2 text-white disabled:opacity-50">Save new brief</button></div>
  {loading&&<p role="status">Loading saved brief evidence…</p>}
  {ready&&items.length===0&&<p>No saved-source briefs yet.</p>}
  {items.length>0&&<div className="rounded-xl border bg-white p-4"><h3 className="font-semibold">Saved briefs</h3><ul className="mt-3 space-y-2">{items.map(item=><li key={item.id}><button disabled={busy||loading} onClick={()=>void open(item.id)} className="w-full break-words rounded border p-3 text-left disabled:opacity-50">{marketDate(item.createdAt)} · {item.windowDays} days · {item.state==='ready'?'Complete':'Needs local completion'}<span className="mt-1 block text-sm text-slate-600">{item.reason}</span></button></li>)}</ul>{cursor&&<button disabled={busy||loading} onClick={()=>void load(detail?.report.id,cursor)} className="mt-3 text-indigo-700">Older briefs</button>}</div>}
  {detail&&ready&&<div className="space-y-4 rounded-xl border bg-white p-4">
   <h3 className="font-semibold">{detail.report.state==='ready'?'Saved brief details':'Saved evidence awaits completion'}</h3><p className="text-sm text-slate-600">Requested {marketDate(detail.report.created_at)} · {detail.report.input.windowDays} days</p>
   {detail.sourceChanged===true&&<p role="alert" className="rounded bg-amber-50 p-3 text-amber-900">Source records or the reporting window changed since this snapshot. This saved report has not been rewritten. Create a new brief for a current comparison.</p>}
   {detail.sourceChanged===null&&<p role="alert" className="rounded bg-amber-50 p-3">Current evidence could not be checked. This is the retained historical report.</p>}
   <label className="block text-sm">Reason for report review or download<textarea value={reviewReason} onChange={e=>setReviewReason(e.target.value)} disabled={busy} maxLength={2000} className="mt-1 block w-full rounded border p-2"/></label>
   {detail.report.state==='prepared'&&<button onClick={()=>void recover()} disabled={!canDecide} className="rounded bg-indigo-700 px-4 py-2 text-white disabled:opacity-50">Complete saved brief</button>}
   {report&&<>
    <p className="text-sm">Evidence snapshot: {marketDate(report.snapshotAt)}. {report.analysis.summary.pricedPlans} of {report.analysis.summary.totalUnitsTracked} plans have a known starting rent.</p>
    <div className="flex flex-wrap gap-3"><button disabled={!canDecide} onClick={()=>void download('markdown')} className="rounded border px-3 py-2 disabled:opacity-50">Download readable report</button><button disabled={!canDecide} onClick={()=>void download('json')} className="rounded border px-3 py-2 disabled:opacity-50">Download report data</button></div>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="py-3 text-left font-semibold">Subject and competitor starting rents</caption><thead><tr><th className="p-2">Bedrooms</th><th className="p-2">Subject mean</th><th className="p-2">Competitor mean</th><th className="p-2">Priced plans</th></tr></thead><tbody>{report.positions.map(p=><tr key={p.bedrooms} className="border-t"><td className="p-2">{p.bedrooms===0?'Studio':p.bedrooms}</td><td className="p-2">{marketMoney(p.subjectMean)}</td><td className="p-2">{marketMoney(p.competitorMean)}</td><td className="p-2">{p.subjectPlans} subject / {p.competitorPlans} competitor</td></tr>)}</tbody></table></div>
    <details className="rounded border p-3"><summary>Subject property pricing sources ({report.subjectUnits.length})</summary><MarketEvidence evidence={report.subjectUnits.map(u=>({unitId:u.id,unitType:u.unit_type,competitorId:propertyId,competitorName:report.propertyName,historyId:null,recordedAt:u.last_updated_at,captureId:null,sourceType:u.source,sourceUrl:u.source_url,capturedAt:null,fetchedAt:null,effectiveAt:u.effective_at,contentHash:null}))}/></details>
    <RecordedChanges key={report.reportId} report={report}/>
    <h4 className="font-semibold">What needs review</h4>
    {detail.sourceChanged===true&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>I understand this review refers to historical evidence, not the current market.</span></label>}
    {report.recommendations.length===0?<p>No review prompt was produced by the saved comparison rules.</p>:report.recommendations.map(rec=>{const last=detail.decisions.filter(d=>d.kind==='brief.reviewed'&&d.input.recommendationId===rec.id).at(-1);return <article key={rec.id} className="rounded-lg border p-3"><h5 className="font-medium">{rec.title}</h5><p className="mt-2 text-sm">{rec.rationale}</p><p className="mt-2 text-sm text-slate-600">Review: {last?.input.decision==='consider'?'Marked for consideration':last?.input.decision==='dismiss'?'Dismissed':'Not reviewed'}</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={!canDecide||detail.sourceChanged===null||(detail.sourceChanged&&!ack)} onClick={()=>void review(rec,'consider')} className="rounded border px-3 py-2 disabled:opacity-50">Mark for consideration</button><button disabled={!canDecide} onClick={()=>void review(rec,'dismiss')} className="rounded border px-3 py-2 disabled:opacity-50">Dismiss prompt</button></div><p className="mt-2 text-xs text-slate-600">This records your decision; it does not change prices or start another product.</p><MarketEvidence evidence={rec.evidence}/></article>})}
    <MarketHandoffs initialHandoffId={openHandoffId} key={`${propertyId}:${report.reportId}`} propertyId={propertyId} briefId={report.reportId} version={detail.report.version} sourceCurrent={detail.sourceChanged===false} recommendations={report.recommendations} reviews={detail.decisions} disabled={busy||loading}/>
    <details className="rounded border p-3"><summary>Calculation limits</summary><ul className="mt-2 list-disc space-y-2 pl-5 text-sm">{[...report.limitations,...report.analysis.limitations].map(t=><li key={t}>{t}</li>)}</ul></details>
    <MarketEvidence evidence={report.analysis.evidence}/>
   </>}
   <details className="rounded border p-3"><summary>Saved report decisions ({detail.decisions.length})</summary><ul className="mt-3 space-y-3 text-sm">{detail.decisions.map(d=><li key={d.id}><p>{d.kind==='brief.exported'?'Download prepared':d.kind==='brief.recovered'?'Completion requested':'Recommendation reviewed'} · {marketDate(d.createdAt)}</p><p>{d.input.reason}</p></li>)}</ul></details>
  </div>}
  {legacyCount>0&&<details className="rounded border bg-white p-4"><summary>Earlier briefs ({legacyCount})</summary><p className="mt-2 text-sm text-slate-600">Retained historical reports. Their original input snapshots and confidence claims were not qualified by the new saved-source workflow.</p><button disabled={busy} onClick={()=>void loadLegacy()} className="mt-3 text-indigo-700">Load earlier reports</button><ul className="mt-3 space-y-2">{legacy.map(r=><li key={r.id}><button onClick={()=>void loadLegacy(undefined,r.id)} disabled={busy} className="text-indigo-700">Open historical report · {marketDate(r.createdAt)}</button></li>)}</ul>{legacyCursor&&<button onClick={()=>void loadLegacy(legacyCursor)} disabled={busy}>Older historical reports</button>}{legacyData!==null&&<HistoricalBrief value={legacyData}/>}</details>}
 </section>
}
