"use client"
import {useCallback,useEffect,useRef,useState}from 'react'
import {useAccountTimeZone,accountDate}from '@/components/layout/AccountPreferences'
import type {Member,Invitation,Page,MemberDetail,InvitationDetail,Decision}from '@/utils/team/contracts'
import {teamFetch as request,teamUrl as url,pendingTeam,clearPendingTeam,postTeam,type PendingTeam,type TeamWrite}from '@/utils/team/client'
const button='rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:opacity-50',field='mt-1 w-full rounded-md border border-slate-300 bg-white p-2 text-slate-900'
const labels:Record<string,string>={role_changed:'Role changed',member_removed:'Organization access removed',invitation_created:'Invitation created',invitation_rotated:'Invitation link replaced',invitation_revoked:'Invitation revoked',invitation_accepted:'Invitation accepted',invitation_declined:'Invitation declined',invitation_copy_reported:'Browser copy result',join_cancelled:'Unused invitation request cancelled',cancelled:'Unused request cancelled'}
const message=(e:unknown)=>e instanceof Error?e.message:'Team access is unavailable.'
const text=(v:unknown)=>typeof v==='object'?JSON.stringify(v,null,2):String(v??'Not supplied')
function Evidence({value}:{value:unknown}){if(!value||typeof value!=='object')return<p>{text(value)}</p>;return<dl className="space-y-2">{Object.entries(value).map(([k,v])=><div key={k}><dt className="font-medium capitalize">{k.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ')}</dt><dd className="whitespace-pre-wrap break-words text-sm">{v&&typeof v==='object'?<Evidence value={v}/>:text(v)}</dd></div>)}</dl>}
export function TeamAccessWorkbench(){
 const[page,setPage]=useState<Page<Member>|null>(null),[member,setMember]=useState<MemberDetail|null>(null),[invitations,setInvitations]=useState<Page<Invitation>|null>(null),[invitation,setInvitation]=useState<InvitationDetail|null>(null),[history,setHistory]=useState<Page<Decision>|null>(null),[detail,setDetail]=useState<Record<string,unknown>|null>(null),[newInvite,setNewInvite]=useState(false),[role,setRole]=useState<'admin'|'manager'|'viewer'>('viewer'),[email,setEmail]=useState(''),[days,setDays]=useState(7),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<PendingTeam|null>(null),[secret,setSecret]=useState<{token:string;sourceDecisionId:string;invitationId:string}|null>(null)
 const timeZone=useAccountTimeZone()
 const alive=useRef(false),generation=useRef(0),scope=page?`${page.actorId}:${page.orgId}`:''
 const reload=useCallback(async()=>{const g=++generation.current;setBusy(true);setError('');setPage(null);setMember(null);setInvitations(null);setInvitation(null);setHistory(null);setDetail(null);setNewInvite(false);setConfirmed(false);setSecret(null);try{const p=await request('/api/team');if(alive.current&&g===generation.current){setPage(p);setPending(pendingTeam(`${p.actorId}:${p.orgId}`))}}catch(e){if(alive.current&&g===generation.current)setError(message(e))}finally{if(alive.current&&g===generation.current)setBusy(false)}},[])
 useEffect(()=>{alive.current=true;void reload();return()=>{alive.current=false}},[reload])
 function fail(e:unknown){setError(message(e));if(e instanceof Error&&'status'in e&&Number(e.status)===403){setPage(null);setMember(null);setInvitations(null);setInvitation(null);setHistory(null);setDetail(null);setSecret(null)}}
 async function selectMember(id:string){if(!page)return;setBusy(true);setError('');setConfirmed(false);setInvitation(null);setNewInvite(false);setReason('');try{const d=await request(url({orgId:page.orgId,kind:'member',memberId:id}));if(alive.current){setMember(d);setRole(['admin','manager','viewer'].includes(d.member.role)?d.member.role:'viewer')}}catch(e){if(alive.current){fail(e);setMember(null)}}finally{if(alive.current)setBusy(false)}}
 async function selectInvitation(id:string){if(!page)return;setBusy(true);setError('');setConfirmed(false);setMember(null);setNewInvite(false);setReason('');try{const d=await request(url({orgId:page.orgId,kind:'invitation',invitationId:id}));if(alive.current)setInvitation(d)}catch(e){if(alive.current){fail(e);setInvitation(null)}}finally{if(alive.current)setBusy(false)}}
 async function load(kind:'members'|'invitations'|'history',more=false){if(!page)return;const current=kind==='members'?page:kind==='invitations'?invitations:history;setBusy(true);setError('');try{const p=await request(url({orgId:page.orgId,kind,offset:more?current?.nextOffset??0:0,expectedHash:more?current?.pageHash:undefined}));if(alive.current){const next={...p,items:more?[...current!.items,...p.items]:p.items};if(kind==='members')setPage(next);else if(kind==='invitations')setInvitations(next);else setHistory(next)}}catch(e){if(alive.current){fail(e);if(kind==='members'){setPage(null);setMember(null)}else if(kind==='invitations')setInvitations(null);else setHistory(null)}}finally{if(alive.current)setBusy(false)}}
 async function showDecision(id:string){if(!page)return;setBusy(true);setDetail(null);try{const d=await request(url({orgId:page.orgId,kind:'history_detail',decisionId:id}));if(alive.current)setDetail(d.decision)}catch(e){if(alive.current)fail(e)}finally{if(alive.current)setBusy(false)}}
 async function save(command:TeamWrite){if(!page?.canManage||pending||busy)return;setBusy(true);setError('');setNotice('');const savedScope=scope;try{const r=await postTeam(savedScope,command);if(!alive.current)return;await reload();if(!alive.current)return;if(['invitation_created','invitation_rotated'].includes(r.kind)&&typeof r.invitationToken==='string'&&/^[a-f0-9]{64}$/.test(r.invitationToken))setSecret({token:r.invitationToken,sourceDecisionId:r.decisionId,invitationId:r.targetId});setNotice(r.kind==='member_removed'?'Organization access removed. The account and its history remain.':r.kind==='invitation_created'||r.kind==='invitation_rotated'?(r.invitationToken?'Invitation saved. Copy its link to share it with the reviewed recipient. No email has been sent.':'Saved invitation recovered. Review it and replace its link to obtain a new secret. No email has been sent.'):'Team decision saved.');setReason('')}catch(e){if(alive.current){fail(e);setPending(pendingTeam(savedScope));if(e instanceof Error&&'status'in e&&Number(e.status)===409){setMember(null);setInvitation(null);setConfirmed(false);setSecret(null)}}}finally{if(alive.current)setBusy(false)}}
 async function recover(cancel=false){if(!page||!pending)return;setBusy(true);setError('');const savedScope=scope;try{const r=await request(cancel?'/api/team':url({orgId:page.orgId,kind:'decision',decisionId:pending.id}),cancel?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orgId:page.orgId,requestId:pending.id,operation:'cancel_unused',inputHash:pending.hash,reason:'Stop unused team request after checking its saved result'})}:undefined);if(r.orgId!==page.orgId||r.decisionId!==pending.id||!['ready','replayed','saved'].includes(r.state))throw new Error('The saved team result could not be verified.');clearPendingTeam(savedScope,pending.id);if(!alive.current)return;setPending(null);await reload();if(alive.current)setNotice(r.cancelled?'Unused team request cancelled.':r.kind==='invitation_created'||r.kind==='invitation_rotated'?'Saved invitation recovered. Review it and replace its link to obtain a new secret. The earlier link is not revealed.':'Saved team decision recovered.')}catch(e){if(alive.current)fail(e)}finally{if(alive.current)setBusy(false)}}
 async function copyLink(){if(!page||!secret||busy||pending)return;setBusy(true);setError('');let outcome:'copied'|'failed'='copied';try{await navigator.clipboard.writeText(`${window.location.origin}/join/team#token=${secret.token}`)}catch{outcome='failed'}try{const r=await postTeam(scope,{orgId:page.orgId,operation:'report_link_copy',sourceDecisionId:secret.sourceDecisionId,outcome});if(alive.current)setNotice(outcome==='copied'?(r.linkStillCurrent?'Invitation link copied. No email has been sent.':'The copied link has since changed. Review the invitation and replace its link.'):'The browser could not copy the link. You can select and copy the displayed link manually.')}catch(e){if(alive.current){setPending(pendingTeam(scope));fail(e)}}finally{if(alive.current)setBusy(false)}}
 const enabled=!!page?.canManage&&!busy&&!pending,canReview=enabled&&confirmed&&reason.trim().length>=3
 const common=page?{orgId:page.orgId,reason,confirmed:true as const}:null
 return<section aria-label="Recorded team access" className="mx-auto max-w-6xl space-y-5 p-4 text-slate-900 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">Team access</h1><p className="mt-2 text-sm text-slate-600">{page?.organizationName||'Your organization'} · Review member roles, invitation links and access changes.</p></div><button className={button} disabled={busy} onClick={()=>void reload()}>Reload team</button></div>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-3 text-green-800">{notice}</p>}{busy&&<p role="status">Loading or saving team access…</p>}
 {pending&&<div className="space-y-2 rounded-lg border border-amber-300 bg-amber-50 p-3"><p>A team decision is unconfirmed. Check its saved result before another change.</p><button className={button} disabled={busy} onClick={()=>void recover()}>Check saved team decision</button> <button className={button} disabled={busy} onClick={()=>void recover(true)}>Cancel unused team request</button></div>}
 {page&&<><div className="flex flex-wrap gap-3">{page.canManage&&<><button className={button} disabled={!enabled} onClick={()=>{setNewInvite(true);setMember(null);setInvitation(null);setRole('viewer');setEmail('');setDays(7);setConfirmed(false);setReason('')}}>Create invitation</button><button className={button} disabled={busy} onClick={()=>void load('invitations')}>Review invitations</button><button className={button} disabled={busy} onClick={()=>void load('history')}>Team decision history</button></>}{!page.canManage&&<p>View only. A current administrator can change organization access.</p>}</div>
 <ul className="divide-y rounded-xl border bg-white">{page.items.map(m=><li key={m.id}><button className="w-full p-4 text-left disabled:opacity-50" disabled={busy||!!pending} onClick={()=>void selectMember(m.id)}><span className="font-medium">{m.name||m.email||'Team member'}</span><span className="block break-words text-sm">{m.email||'Email unavailable'} · {m.role||'Role unavailable'}{m.accessBlocked?' · Account access blocked':!m.emailConfirmed?' · Email confirmation pending':''}{m.id===page.actorId?' · You':''}</span></button></li>)}</ul><p>Showing {page.items.length} of {page.total} team members.</p>{page.nextOffset!==null&&<button className={button} disabled={busy} onClick={()=>void load('members',true)}>Load more team members</button>}
 {invitations&&<div aria-label="Saved team invitations" className="space-y-3"><h2 className="text-lg font-semibold">Invitations</h2>{invitations.items.map(i=><button key={i.id} className="block w-full rounded-lg border bg-white p-3 text-left" disabled={busy||!!pending} onClick={()=>void selectInvitation(i.id)}>{i.email} · {i.role} · {i.effectiveStatus}<span className="block text-sm">Expires {accountDate(i.expiresAt,timeZone)}{!i.issuerAuthorized?' · Needs a current administrator’s review':''}</span></button>)}<p>Showing {invitations.items.length} of {invitations.total} invitations.</p>{invitations.nextOffset!==null&&<button className={button} disabled={busy} onClick={()=>void load('invitations',true)}>Load more invitations</button>}</div>}
 {(member||invitation||newInvite)&&<div aria-label="Selected team review" className="space-y-4 rounded-xl border bg-white p-5">
 {member&&<><h2 className="text-lg font-semibold">Review {member.member.name||member.member.email||'team member'}</h2><p>{member.member.email} · Current role: {member.member.role}</p><label className="block">Reviewed role<select aria-label="Reviewed member role" className={field} disabled={!enabled} value={role} onChange={e=>{setRole(e.target.value as typeof role);setConfirmed(false)}}><option value="viewer">Viewer</option><option value="manager">Manager</option><option value="admin">Administrator</option></select></label><p className="text-sm">Removing organization access keeps the account and past work. The last available administrator must remain.</p></>}
 {newInvite&&<><h2 className="text-lg font-semibold">Create a reviewed invitation</h2><p className="text-sm">Only the account with this verified email can accept the link. The recipient must review and accept the requested role. Share the link yourself after saving; this does not send an email.</p><label className="block">Recipient email<input aria-label="Invitation recipient email" className={field} type="email" disabled={!enabled} value={email} onChange={e=>{setEmail(e.target.value);setConfirmed(false)}}/></label><label className="block">Invitation role<select aria-label="Invitation role" className={field} disabled={!enabled} value={role} onChange={e=>{setRole(e.target.value as typeof role);setConfirmed(false)}}><option value="viewer">Viewer</option><option value="manager">Manager</option><option value="admin">Administrator</option></select></label></>}
 {invitation&&<><h2 className="text-lg font-semibold">Review invitation for {invitation.invitation.email}</h2><p>{invitation.invitation.role} · {invitation.invitation.effectiveStatus} · Expires {accountDate(invitation.invitation.expiresAt,timeZone)}</p><p className="text-sm">Replacing the link invalidates the old secret and records the current administrator’s review. To change the recipient or role, revoke this invitation and create a new one.</p></>}
 {(newInvite||invitation?.invitation.status==='pending')&&<label className="block">Link expires in days<input aria-label="Invitation lifetime in days" className={field} disabled={!enabled} type="number" min={1} max={14} value={days} onChange={e=>{setDays(Number(e.target.value));setConfirmed(false)}}/></label>}
 <fieldset disabled={!enabled} className="space-y-3"><label className="block">Reason for team decision<textarea aria-label="Reason for team decision" className={field} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex gap-2"><input aria-label="Confirm reviewed team decision" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this exact member or invitation and the intended access change.</label></fieldset>
 <div className="flex flex-wrap gap-3">{member&&common&&<><button className={button} disabled={!canReview||role===member.member.role} onClick={()=>void save({...common,operation:'change_role',memberId:member.member.id,memberHash:member.memberHash,rosterHash:member.rosterHash,role})}>Save reviewed role</button><button className={button} disabled={!canReview||member.member.id===page.actorId} onClick={()=>void save({...common,operation:'remove_member',memberId:member.member.id,memberHash:member.memberHash,rosterHash:member.rosterHash})}>Remove organization access</button></>}{newInvite&&common&&<button className={button} disabled={!canReview||!email.trim()||days<1||days>14||!Number.isInteger(days)} onClick={()=>void save({...common,operation:'create_invitation',email,role,expiresInDays:days})}>Save invitation</button>}{invitation?.invitation.status==='pending'&&common&&<><button className={button} disabled={!canReview||days<1||days>14||!Number.isInteger(days)} onClick={()=>void save({...common,operation:'rotate_invitation',invitationId:invitation.invitation.id,invitationHash:invitation.invitationHash,expiresInDays:days})}>Replace invitation link</button><button className={button} disabled={!canReview} onClick={()=>void save({...common,operation:'revoke_invitation',invitationId:invitation.invitation.id,invitationHash:invitation.invitationHash})}>Revoke invitation</button></>}</div></div>}
 {secret&&<div aria-label="New invitation link" className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Share the invitation link</h2><p className="text-sm">This secret is shown only for the newly saved link. Reloading clears it; you can explicitly replace the link if needed.</p><textarea aria-label="Private invitation link" readOnly className={field} value={typeof window==='undefined'?'':`${window.location.origin}/join/team#token=${secret.token}`}/><button className={button} disabled={!enabled} onClick={()=>void copyLink()}>Copy invitation link</button></div>}
 {history&&<div aria-label="Team decision history" className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Recorded decisions</h2><p>Showing {history.items.length} of {history.total} team decisions · {timeZone}.</p>{history.items.map(d=><button className="block w-full border-b py-3 text-left" key={d.id} disabled={busy} onClick={()=>void showDecision(d.id)}>{labels[d.kind]||d.kind} · {d.reason}<span className="block text-sm">{accountDate(d.createdAt,timeZone)} · {page.items.find(m=>m.id===d.actorId)?.name||'Recorded team member'}</span></button>)}{history.nextOffset!==null&&<button className={button} disabled={busy} onClick={()=>void load('history',true)}>Load more team decisions</button>}{detail&&<div aria-label="Saved team decision details" className="grid gap-5 sm:grid-cols-2"><div><h3 className="font-semibold">Before the decision</h3><Evidence value={detail.before_state}/></div><div><h3 className="font-semibold">After the decision</h3><Evidence value={detail.after_state}/></div></div>}</div>}
 </>}
 </section>
}
