"use client"
import {useCallback,useEffect,useRef,useState}from 'react'
import Link from 'next/link'
import {switchTeamAccount}from '@/app/auth/actions'
import {teamFetch as request,postTeam,pendingTeam,clearPendingTeam,type PendingTeam}from '@/utils/team/client'
import type {JoinContext}from '@/utils/team/contracts'
const button='rounded-lg border border-slate-300 px-4 py-2 text-sm disabled:opacity-50'
export function TeamJoinWorkbench({actorId}:{actorId:string|null}){
 const[context,setContext]=useState<JoinContext|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[pending,setPending]=useState<PendingTeam|null>(null),[result,setResult]=useState<Record<string,unknown>|null>(null),[prepared,setPrepared]=useState(false)
 const alive=useRef(false),initial=useRef<Promise<void>|null>(null),initialToken=useRef<string|null>(null),generation=useRef(0),scope=actorId?`join:${actorId}`:''
 const load=useCallback(async()=>{const g=++generation.current,current=()=>alive.current&&generation.current===g;setBusy(true);setError('');setContext(null);setResult(null);setConfirmed(false);setReason('');try{
  const token=new URLSearchParams(window.location.hash.slice(1)).get('token')
  if(token&&token!==initialToken.current){initial.current=null;initialToken.current=token}
  if(!initial.current)initial.current=(async()=>{if(token){await request('/api/team/join/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});window.history.replaceState(null,'','/join/team')}})()
  await initial.current;if(!current())return;setPrepared(true)
  if(!actorId)return;const p=pendingTeam(scope);setPending(p);if(p)return
  const value=await request('/api/team/join');if(current())setContext(value)
 }catch(e){if(current()){setError(e instanceof Error?e.message:'This invitation is unavailable.');initial.current=null}}finally{if(current())setBusy(false)}},[actorId,scope])
 useEffect(()=>{alive.current=true;const changed=()=>{initial.current=null;void load()};void load();window.addEventListener('hashchange',changed);return()=>{alive.current=false;window.removeEventListener('hashchange',changed)}},[load])
 async function decide(operation:'accept'|'decline'){if(!actorId||!context||pending||busy||!confirmed)return;setBusy(true);setError('');try{const r=await postTeam(scope,{operation,invitationHash:context.invitationHash,confirmed:true,reason},true);if(alive.current){setResult(r);setContext(null);setConfirmed(false)}}catch(e){if(alive.current){setError(e instanceof Error?e.message:'The invitation decision could not be confirmed.');setPending(pendingTeam(scope));if(e instanceof Error&&'status'in e&&[403,409].includes(Number(e.status))){setContext(null);setConfirmed(false)}}}finally{if(alive.current)setBusy(false)}}
 async function recover(){if(!pending||!actorId)return;setBusy(true);setError('');try{const r=await request('/api/team/join?decisionId='+encodeURIComponent(pending.id));if(r.decisionId!==pending.id||r.state!=='ready')throw new Error('The saved invitation result does not match.');clearPendingTeam(scope,pending.id);if(alive.current){setPending(null);if(r.cancelled){setResult(null);await load()}else{setResult(r);setContext(null)}}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'The saved invitation could not be confirmed.')}finally{if(alive.current)setBusy(false)}}
 async function cancelUnused(){if(!pending||!actorId)return;setBusy(true);setError('');try{const r=await request('/api/team/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:pending.id,operation:'cancel_unused',inputHash:pending.hash})});if(r.decisionId!==pending.id||!['saved','replayed'].includes(r.state))throw new Error('The saved invitation result does not match.');clearPendingTeam(scope,pending.id);if(!alive.current)return;setPending(null);if(r.cancelled){setResult(null);await load()}else{setResult(r);setContext(null)}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'The unused request could not be cancelled.')}finally{if(alive.current)setBusy(false)}}

 return<main className="min-h-screen bg-slate-50 px-4 py-12 text-slate-900"><section aria-label="Review team invitation" className="mx-auto max-w-2xl space-y-5 rounded-2xl border bg-white p-6 shadow-sm"><h1 className="text-2xl font-semibold">Review your team invitation</h1><p className="text-sm text-slate-600">An invitation only grants organization access after you review and accept it with the matching verified account.</p>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}{busy&&<p role="status">Checking the invitation…</p>}
 {!actorId&&prepared&&<div className="space-y-3"><p>Sign in with the invited email address, or create and verify that account. Your invitation is held privately in this browser for 30 minutes.</p><div className="flex flex-wrap gap-3"><Link className={button} href="/auth/login?redirect=%2Fjoin%2Fteam">Sign in to review invitation</Link><Link className={button} href="/auth/signup?redirect=%2Fjoin%2Fteam">Create an account</Link></div><p className="text-sm">If you verify your account in another browser, reopen the original invitation link there.</p></div>}
 {actorId&&!result&&<div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>void load()}>Reload invitation</button><button className={button} disabled={busy} onClick={()=>{setBusy(true);void switchTeamAccount().catch(e=>{if(alive.current){setError(e instanceof Error?e.message:'Account switching failed.');setBusy(false)}})}}>Use another account</button></div>}
 {pending&&<div className="space-y-3 rounded-lg border border-amber-300 bg-amber-50 p-3"><p>An invitation decision is unconfirmed. Check its saved result before another change.</p><button className={button} disabled={busy} onClick={()=>void recover()}>Check saved invitation decision</button><button className={button} disabled={busy} onClick={()=>void cancelUnused()}>Cancel unused invitation request</button></div>}
 {context&&<div className="space-y-4"><h2 className="text-lg font-semibold">Join {context.organization.name}</h2><p>Invited email: {context.invitation.email}</p><p>Reviewed role: <strong className="capitalize">{context.invitation.role}</strong></p><p>Expires {new Date(context.invitation.expiresAt).toLocaleString()}</p>{!context.canJoin&&<p className="rounded-lg bg-amber-50 p-3">{context.alreadyMember?'You already belong to this organization.':'Your account already belongs to another organization. This invitation cannot move that membership.'}</p>}<label className="block">Reason for invitation decision<textarea aria-label="Reason for invitation decision" className="mt-1 w-full rounded-md border p-2" disabled={busy||!!pending} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex gap-2"><input aria-label="Confirm exact team invitation" type="checkbox" disabled={busy||!!pending} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the organization, invited email, role and expiration.</label><div className="flex flex-wrap gap-3"><button className={button} disabled={busy||!!pending||!confirmed||reason.trim().length<3||!context.canJoin} onClick={()=>void decide('accept')}>Accept team invitation</button><button className={button} disabled={busy||!!pending||!confirmed||reason.trim().length<3} onClick={()=>void decide('decline')}>Decline team invitation</button></div></div>}
 {result&&<div className="space-y-4" role="status"><h2 className="text-lg font-semibold">{result.membershipGranted?'Invitation accepted':'Invitation declined'}</h2><p>{result.membershipGranted?(result.currentlyMember===false?'Your acceptance was saved. Your organization access has since changed.':'Your reviewed invitation and organization membership were saved together.'):'Your decision was saved. This invitation did not grant organization access.'}</p>{result.membershipGranted===true&&result.currentlyMember!==false&&<Link className={button} href="/dashboard/team">Open my team</Link>}<Link className={button} href="/dashboard">Return to my account</Link></div>}
 </section></main>
}
