import{beforeEach,it,expect,vi}from'vitest'
const d=vi.hoisted(()=>({actor:vi.fn(),org:vi.fn(),read:vi.fn(),save:vi.fn()}))
vi.mock('@/utils/account-settings/store',async()=>{const{InventoryError}=await import('@/utils/knowledge/inventory');return{AccountSettingsError:InventoryError,accountActor:d.actor,currentAccountOrganization:d.org,readAccountSettings:d.read,decideAccountSettings:d.save}})
import{InventoryError}from'@/utils/knowledge/inventory'
import{GET,POST,PATCH}from'./route'
const id='11111111-1111-1111-1111-111111111111',body={orgId:id,requestId:id,operation:'save_profile',section:'personal',sourceHash:'a'.repeat(64),fullName:'Reviewed name',confirmed:true,reason:'My display name edit'},req=(b:unknown=body,headers:Record<string,string>={origin:'http://local'})=>new Request('http://local/api/settings',{method:'POST',headers,body:typeof b==='string'?b:JSON.stringify(b)})
beforeEach(()=>{vi.clearAllMocks();d.actor.mockResolvedValue('actual-account');d.org.mockResolvedValue(id);d.read.mockResolvedValue({state:'ready'});d.save.mockResolvedValue({state:'saved'})})
it('authenticates before parse or scope and excludes unknown mutable fields',async()=>{d.actor.mockRejectedValueOnce(new InventoryError('Unauthorized',401));expect((await POST(req('bad'))).status).toBe(401);expect(d.save).not.toHaveBeenCalled();expect((await POST(req({...body,password:'secret'}))).status).toBe(400);expect(d.save).not.toHaveBeenCalled()})
it('binds actual account, protects same-origin writes and bounds streamed payloads',async()=>{const r=await POST(req());expect(r.status).toBe(200);expect(d.save).toHaveBeenCalledWith('actual-account',body);expect(r.headers.get('cache-control')).toBe('private, no-store');expect((await POST(req(body,{origin:'http://outside'}))).status).toBe(403);expect((await POST(req('x'.repeat(16385)))).status).toBe(413)})
it('derives current org, rejects incomplete selection, hides internal errors and closes old writes',async()=>{expect((await GET(new Request('http://local/api/settings'))).status).toBe(200);expect(d.read).toHaveBeenCalledWith('actual-account',id,{kind:'current',section:'personal',offset:0});expect((await GET(new Request('http://local/api/settings?kind=detail'))).status).toBe(400);expect((await PATCH()).status).toBe(410);d.read.mockRejectedValue(new Error('private database error'));const r=await GET(new Request('http://local/api/settings'));expect(await r.json()).toEqual({error:'Account settings are unavailable.'})})
