import {beforeEach,describe,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
import sharp from 'sharp'
const rpc=vi.fn(),from=vi.fn(),upload=vi.fn(),download=vi.fn(),getPublicUrl=vi.fn()
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc,from,storage:{from:()=>({upload,download,getPublicUrl})}})}))
vi.mock('@/utils/storage/asset-service',()=>({STORAGE_BUCKETS:{PROPERTY_ASSETS:'property-assets'}}))
const property='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',path=property+'/forgestudio/uploads/'+id+'.png'
let bytes:Buffer
async function form(){const f=new FormData();f.set('file',new File([new Uint8Array(bytes)],'pool.png',{type:'image/png'}));f.set('requestId',id);return f}
beforeEach(async()=>{vi.clearAllMocks();bytes=await sharp({create:{width:2,height:2,channels:3,background:'#abcdef'}}).png().toBuffer();rpc.mockImplementation(async name=>({data:name==='begin_forgestudio_asset_upload'?{state:'prepared',storagePath:path}:name==='forgestudio_command_start'?{state:'new'}:{state:'saved',assetId:id},error:null}));upload.mockResolvedValue({error:null});download.mockResolvedValue({data:new Blob([new Uint8Array(bytes)]),error:null});getPublicUrl.mockReturnValue({data:{publicUrl:'https://storage.invalid/'+path}})})
describe('asset upload persistence',()=>{
 it('uses an immutable file path, exact byte hash and no overwrite',async()=>{const result=await(await import('./asset-library-store')).uploadLibraryAsset(await form(),'actor',property);expect(result.assetId).toBe(id);expect(upload).toHaveBeenCalledWith(path,bytes,{contentType:'image/png',upsert:false});expect(rpc).toHaveBeenLastCalledWith('finish_forgestudio_asset_upload',expect.objectContaining({p_payload:expect.objectContaining({contentHash:createHash('sha256').update(bytes).digest('hex'),storagePath:path,storageVerified:true})}));expect(download).not.toHaveBeenCalled()})
 it('verifies existing stored bytes when the storage reply is uncertain',async()=>{upload.mockResolvedValue({error:new Error('response lost')});await(await import('./asset-library-store')).uploadLibraryAsset(await form(),'actor',property);expect(download).toHaveBeenCalledWith(path);expect(rpc).toHaveBeenLastCalledWith('finish_forgestudio_asset_upload',expect.any(Object))})
 it('an existing wrong file cannot be accepted as recovered storage',async()=>{upload.mockResolvedValue({error:new Error('response lost')});download.mockResolvedValue({data:new Blob(['different']),error:null});await expect((await import('./asset-library-store')).uploadLibraryAsset(await form(),'actor',property)).rejects.toThrow('stored file could not be confirmed');expect(rpc).toHaveBeenCalledTimes(1)})
 it('a saved upload replay cannot upload bytes again',async()=>{rpc.mockResolvedValue({data:{state:'replayed',assetId:id},error:null});const result=await(await import('./asset-library-store')).uploadLibraryAsset(await form(),'actor',property);expect(result.state).toBe('replayed');expect(upload).not.toHaveBeenCalled();expect(download).not.toHaveBeenCalled()})
 it('an existing matching asset is reused without overwriting its file',async()=>{rpc.mockImplementation(async name=>({data:name==='begin_forgestudio_asset_upload'?{state:'prepared',storagePath:path,duplicateAssetId:'existing'}:{state:'saved',assetId:'existing',duplicate:true},error:null}));expect((await(await import('./asset-library-store')).uploadLibraryAsset(await form(),'actor',property)).duplicate).toBe(true);expect(upload).not.toHaveBeenCalled();expect(download).not.toHaveBeenCalled()})
 it('losing the library save response does not delete the stored original',async()=>{rpc.mockImplementation(async name=>name==='finish_forgestudio_asset_upload'?{data:null,error:new Error('lost')}:{data:{state:'prepared',storagePath:path},error:null});await expect((await import('./asset-library-store')).uploadLibraryAsset(await form(),'actor',property)).rejects.toThrow('could not be confirmed');expect(upload).toHaveBeenCalledTimes(1)})
 it('validates the actual image format and dimensions before saving a request',async()=>{const {inspectAssetFile}=await import('./asset-library-store');expect(await inspectAssetFile(new File([new Uint8Array(bytes)],'pool.png',{type:'image/png'}))).toEqual(expect.objectContaining({width:2,height:2,asset_type:'image'}));await expect(inspectAssetFile(new File([new Uint8Array(bytes)],'wrong.jpg',{type:'image/jpeg'}))).rejects.toThrow('do not match');await expect(inspectAssetFile(new File(['not an image'],'wrong.png',{type:'image/png'}))).rejects.toThrow('could not be read')})
 it('a replayed recovery does not read or store the file again',async()=>{rpc.mockResolvedValue({data:{state:'replayed',assetId:id},error:null});await(await import('./asset-library-store')).recoverLibraryUpload({requestId:id,propertyId:property,actorId:'actor',uploadId:id,action:'recover',reason:'Checked saved upload'});expect(from).not.toHaveBeenCalled();expect(upload).not.toHaveBeenCalled();expect(download).not.toHaveBeenCalled()})
})
