import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {NextRequest} from 'next/server'
const {auth,access,rpc,from,credentials,exchange,url}=vi.hoisted(()=>({auth:vi.fn(),access:vi.fn(),rpc:vi.fn(),from:vi.fn(),credentials:vi.fn(),exchange:vi.fn(),url:vi.fn()}))
vi.mock('@/utils/supabase/server',()=>({createClient:async()=>({auth:{getUser:auth}})}))
vi.mock('@/utils/services/auth-guard',()=>({validatePropertyManagerAccess:access}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc,from})}))
vi.mock('./social-config',()=>({getSocialAppCredentials:credentials}))
vi.mock('./oauth-provider',()=>({exchangeSocialAuthorization:exchange,socialAuthorizationUrl:url}))
import {beginSocialAuthorization,completeSocialAuthorization} from './oauth-flow'
import {createSignedForgeStudioOAuthState} from '@/utils/services/forgestudio-oauth-state'
import {encryptSecret} from './crypto'
const propertyId='33333333-3333-4333-8333-333333333333',authorizationId='55555555-5555-4555-8555-555555555555',actorId='11111111-1111-4111-8111-111111111111'
let state:string
function callback(extra='code=one-use'){return new NextRequest(`http://localhost/api/forgestudio/social/callback/x?${extra}&state=${state}`,{headers:{cookie:`fs_oauth_nonce=${authorizationId.replaceAll('-','')}`}})}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('NEXT_PUBLIC_SITE_URL','http://localhost');vi.stubEnv('FORGESTUDIO_OAUTH_STATE_SECRET','state-test-secret');vi.stubEnv('ENCRYPTION_KEY','test-encryption-secret');vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');auth.mockResolvedValue({data:{user:{id:actorId}},error:null});access.mockResolvedValue({authorized:true});credentials.mockResolvedValue({appId:'client',appSecret:'secret',source:'database'});const q={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data:{id:authorizationId,state:'pending',decision_version:1},error:null})};q.select.mockReturnValue(q);q.eq.mockReturnValue(q);from.mockReturnValue(q);state=createSignedForgeStudioOAuthState({propertyId,userId:actorId,nonce:authorizationId.replaceAll('-','')});exchange.mockResolvedValue({status:'observed',observedAt:'2026-09-18T00:00:00Z',accounts:[]});url.mockReturnValue('https://x.com/i/oauth2/authorize?state=signed');rpc.mockImplementation(async(name:string)=>({data:name==='claim_forgestudio_authorization'?{state:'exchange_once',claimToken:'saved-claim',credentials:{appId:'client',appSecretEncrypted:encryptSecret('secret'),codeVerifierEncrypted:encryptSecret('saved-verifier')},input:{redirectUri:'http://localhost/api/forgestudio/social/callback/x'}}:{state:'saved',authorizationState:'review_required'},error:null}))})
afterEach(()=>vi.unstubAllEnvs())
describe('saved social authorization lifecycle',()=>{
 it('does not create authorization or contact a provider while delivery is paused',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');const r=await beginSocialAuthorization(new NextRequest(`http://localhost/start?propertyId=${propertyId}&requestId=${authorizationId}`),'x');expect(r.headers.get('location')).toContain('paused');expect(rpc).not.toHaveBeenCalled();expect(credentials).not.toHaveBeenCalled()})
 it('uses the saved verifier and timestamp on a replayed start',async()=>{rpc.mockResolvedValue({data:{state:'pending',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60_000).toISOString(),credentials:{codeVerifierEncrypted:encryptSecret('original-verifier')}},error:null});const r=await beginSocialAuthorization(new NextRequest(`http://localhost/start?propertyId=${propertyId}&requestId=${authorizationId}`),'x');expect(r.headers.get('location')).toContain('https://x.com');expect(url).toHaveBeenCalledWith('x',expect.objectContaining({codeVerifier:'original-verifier'}),expect.any(String));expect(r.cookies.get('fs_oauth_nonce')?.value).toBe(authorizationId.replaceAll('-',''))})
 it('does not trust a provider denial before verifying the signed state',async()=>{const r=await completeSocialAuthorization(new NextRequest('http://localhost/callback?error=access_denied&state=forged'),'x');expect(r.headers.get('location')).toContain('invalid_state');expect(from).not.toHaveBeenCalled();expect(rpc).not.toHaveBeenCalled()})
 it('records a verified denial without claiming or exchanging the code',async()=>{const r=await completeSocialAuthorization(callback('error=access_denied'),'x');expect(r.headers.get('location')).toContain('status=cancelled');expect(rpc).toHaveBeenCalledTimes(1);expect(rpc.mock.calls[0][0]).toBe('cancel_forgestudio_authorization');expect(exchange).not.toHaveBeenCalled()})
 it('never performs a second exchange for a claimed callback',async()=>{rpc.mockResolvedValue({data:{state:'exchanging'},error:null});const r=await completeSocialAuthorization(callback(),'x');expect(r.headers.get('location')).toContain('status=exchanging');expect(exchange).not.toHaveBeenCalled()})
 it('does not exchange after losing acknowledgement of the claim',async()=>{rpc.mockResolvedValue({data:null,error:{message:'lost response'}});await completeSocialAuthorization(callback(),'x');expect(rpc).toHaveBeenCalledTimes(1);expect(exchange).not.toHaveBeenCalled()})
 it('retries only the exact saved encrypted result after a lost finalization reply',async()=>{
  let finishes=0;const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,args:unknown)=>{if(name==='finish_forgestudio_authorization'&&finishes++===0)return{data:null,error:{message:'lost response'}};return original(name,args)})
  const r=await completeSocialAuthorization(callback(),'x');expect(r.headers.get('location')).toContain('status=review_required');expect(exchange).toHaveBeenCalledTimes(1);expect(exchange).toHaveBeenCalledWith('x',expect.objectContaining({codeVerifier:'saved-verifier'}),'one-use');const calls=rpc.mock.calls.filter(c=>c[0]==='finish_forgestudio_authorization');expect(calls).toHaveLength(2);expect(calls[0][1]).toEqual(calls[1][1]);expect(r.cookies.get('fs_oauth_nonce')?.value).toBe('')
 })
 it('checks current manager access again before any exchange',async()=>{access.mockResolvedValue({authorized:false});expect((await completeSocialAuthorization(callback(),'x')).headers.get('location')).toContain('Forbidden');expect(exchange).not.toHaveBeenCalled();expect(from).not.toHaveBeenCalled()})
 it('does not start a provider exchange when the preview pause is enabled after consent',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect((await completeSocialAuthorization(callback(),'x')).headers.get('location')).toContain('paused');expect(exchange).not.toHaveBeenCalled();expect(rpc).not.toHaveBeenCalled()})
})
