import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {exchangeSocialAuthorization,socialAuthorizationUrl} from './oauth-provider'
import {decryptSecret} from './crypto'
const fetchMock=vi.fn(),credentials={appId:'fixture-client',appSecret:'fixture-secret',redirectUri:'https://console.example.invalid/api/callback',codeVerifier:'saved-verifier'}
function reply(data:unknown,status=200){return Promise.resolve(new Response(JSON.stringify(data),{status}))}
beforeEach(()=>{vi.stubEnv('ENCRYPTION_KEY','connection-contract-key');vi.stubGlobal('fetch',fetchMock);fetchMock.mockReset()})
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs()})
describe('social provider authorization contracts',()=>{
 it('uses the saved PKCE verifier and exact redirect with the complete requested X scopes',()=>{const a=new URL(socialAuthorizationUrl('x',credentials,'signed-state')),b=new URL(socialAuthorizationUrl('x',credentials,'signed-state'));expect(a.searchParams.get('code_challenge')).toBe(b.searchParams.get('code_challenge'));expect(a.searchParams.get('redirect_uri')).toBe(credentials.redirectUri);expect(a.searchParams.get('scope')).toContain('media.write');expect(a.searchParams.get('code_challenge_method')).toBe('S256')})
 it('keeps granted LinkedIn scope and provider expiry without returning plaintext tokens',async()=>{fetchMock.mockImplementationOnce(()=>reply({access_token:'private-access',refresh_token:'private-refresh',scope:'openid profile w_member_social',expires_in:3600})).mockImplementationOnce(()=>reply({sub:'member-1',name:'Operator'}));const result=await exchangeSocialAuthorization('linkedin',credentials,'one-use-code');expect(result.status).toBe('observed');expect(result.accounts[0]).toMatchObject({accountId:'member-1',scopes:['openid','profile','w_member_social'],permissionEvidence:{source:'provider_response',expiryKnown:true}});expect(decryptSecret(result.accounts[0].accessTokenEncrypted)).toBe('private-access');expect(JSON.stringify(result)).not.toContain('private-access');expect(JSON.stringify(result)).not.toContain('private-refresh');expect(fetchMock).toHaveBeenCalledTimes(2);expect(fetchMock.mock.calls[0][1]).toMatchObject({redirect:'error',method:'POST'});expect(fetchMock.mock.calls[0][1].signal).toBeInstanceOf(AbortSignal)})
 it('does not invent requested permissions or a lifetime when the provider omits them',async()=>{fetchMock.mockImplementationOnce(()=>reply({access_token:'private-access'})).mockImplementationOnce(()=>reply({sub:'member-1'}));const result=await exchangeSocialAuthorization('linkedin',credentials,'code');expect(result.accounts[0]).toMatchObject({scopes:[],expiresAt:null,permissionEvidence:{expiryKnown:false}})})
 it.each([0,-1,'3600',Infinity])('holds unknown expiry value %s instead of applying a fallback',async expires_in=>{fetchMock.mockImplementationOnce(()=>reply({access_token:'private',expires_in,scope:'openid profile w_member_social'})).mockImplementationOnce(()=>reply({sub:'member-1'}));const result=await exchangeSocialAuthorization('linkedin',credentials,'code');expect(result.accounts[0].permissionEvidence.expiryKnown).toBe(false)})
 it('validates TikTok profile identity against the token subject',async()=>{fetchMock.mockImplementationOnce(()=>reply({access_token:'private',expires_in:3600,scope:'user.info.basic,video.publish',open_id:'one'})).mockImplementationOnce(()=>reply({data:{user:{open_id:'other',display_name:'Other'}},error:{code:'ok'}}));const result=await exchangeSocialAuthorization('tiktok',credentials,'code');expect(result.status).toBe('uncertain');expect(result.accounts).toEqual([]);expect(result.tokenReceipt?.scopes).toEqual(['user.info.basic','video.publish'])})
 it('retains encrypted grant evidence when a post-exchange profile read fails',async()=>{fetchMock.mockImplementationOnce(()=>reply({access_token:'private',refresh_token:'rotated',expires_in:3600,scope:'tweet.read tweet.write users.read'})).mockRejectedValueOnce(new Error('timeout'));const result=await exchangeSocialAuthorization('x',credentials,'code');expect(result.status).toBe('uncertain');expect(decryptSecret(result.tokenReceipt!.refreshTokenEncrypted!)).toBe('rotated');expect(fetchMock).toHaveBeenCalledTimes(2)})
 it('never retries an uncertain token exchange',async()=>{fetchMock.mockRejectedValueOnce(new Error('socket closed'));expect((await exchangeSocialAuthorization('x',credentials,'code')).status).toBe('uncertain');expect(fetchMock).toHaveBeenCalledTimes(1)})
 it('reads actual Meta grants and all candidate accounts without trusting next-page URLs',async()=>{
  fetchMock.mockImplementationOnce(()=>reply({access_token:'user-token',expires_in:3600})).mockImplementationOnce(()=>reply({data:[{permission:'pages_show_list',status:'granted'},{permission:'pages_manage_posts',status:'declined'},{permission:'pages_read_engagement',status:'granted'}]})).mockImplementationOnce(()=>reply({data:[{id:'page-1',name:'Page One',access_token:'private-page-one'}],paging:{next:'https://untrusted.example.invalid/tokens',cursors:{after:'next-cursor'}}})).mockImplementationOnce(()=>reply({data:[{id:'page-2',name:'Page Two',access_token:'private-page-two'}]}))
  const result=await exchangeSocialAuthorization('facebook',credentials,'code');expect(result.accounts.map(a=>a.accountId)).toEqual(['page-1','page-2']);expect(fetchMock.mock.calls[0][1].method).toBe('GET');expect(new URL(String(fetchMock.mock.calls[0][0])).searchParams.get('redirect_uri')).toBe(credentials.redirectUri);expect(result.accounts[0].scopes).not.toContain('pages_manage_posts');expect(new URL(String(fetchMock.mock.calls[3][0])).hostname).toBe('graph.facebook.com');expect(new URL(String(fetchMock.mock.calls[3][0])).searchParams.get('after')).toBe('next-cursor');expect(JSON.stringify(result)).not.toContain('private-page-one')
 })
 it('does not silently select the first Instagram account',async()=>{
  fetchMock.mockImplementationOnce(()=>reply({access_token:'user-token',expires_in:3600})).mockImplementationOnce(()=>reply({data:[]})).mockImplementationOnce(()=>reply({data:[{id:'page-1',access_token:'page-one',instagram_business_account:{id:'ig-1',username:'first'}},{id:'page-2',access_token:'page-two',instagram_business_account:{id:'ig-2',username:'second'}}]}))
  const result=await exchangeSocialAuthorization('instagram',credentials,'code');expect(result.accounts.map(a=>a.accountId)).toEqual(['ig-1','ig-2'])
 })
 it('holds a partial account list instead of claiming a complete grant',async()=>{fetchMock.mockImplementationOnce(()=>reply({access_token:'user-token',expires_in:3600})).mockImplementationOnce(()=>reply({data:[]})).mockImplementationOnce(()=>reply({data:[{id:'page-1',access_token:'page-token'}],paging:{next:'https://graph.facebook.com/next'}}));const result=await exchangeSocialAuthorization('facebook',credentials,'code');expect(result.status).toBe('uncertain');expect(result.accounts).toHaveLength(0)})
})
