import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
const {from,rpc,credentials,provider}=vi.hoisted(()=>({from:vi.fn(),rpc:vi.fn(),credentials:vi.fn(),provider:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({from,rpc})}))
vi.mock('./social-config',()=>({getSocialAppCredentials:credentials}))
vi.mock('./oauth-flow',()=>({getSiteUrl:()=> 'http://localhost'}))
vi.mock('./oauth-provider',()=>({renewSocialAuthorization:provider}))
import {renewSocialConnection} from './renewal'
import {encryptSecret} from './crypto'
const input={propertyId:'property',requestId:'request',connectionId:'connection',expectedVersion:3,reason:'Recover saved access'}
function row(data:unknown){const q={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data,error:null})};q.select.mockReturnValue(q);q.eq.mockReturnValue(q);return q}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('ENCRYPTION_KEY','renewal-local-key');vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','false');from.mockImplementation((name:string)=>row(name==='forgestudio_renewals'?null:{id:'connection',platform:'x'}));credentials.mockResolvedValue({appId:'app',appSecret:'secret'});provider.mockResolvedValue({status:'uncertain',observedAt:new Date().toISOString(),accounts:[],reason:'Unknown provider result'});rpc.mockImplementation(async(name:string)=>({data:name==='begin_forgestudio_renewal'?{state:'exchange_once',claimToken:'one-claim',credentials:{appId:'app',appSecretEncrypted:encryptSecret('secret'),redirectUri:'http://localhost/callback',accountId:'saved-account',accessTokenEncrypted:encryptSecret('old-access'),refreshTokenEncrypted:encryptSecret('old-refresh')}}:{state:'saved',renewalState:'held'},error:null}))})
afterEach(()=>vi.unstubAllEnvs())
describe('one-intent renewal service',()=>{
 it('honors the external pause before claiming or contacting a provider',async()=>{vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');await expect(renewSocialConnection(input,'actor')).rejects.toThrow('paused');expect(rpc).not.toHaveBeenCalled();expect(provider).not.toHaveBeenCalled()})
 it('requires encrypted credential storage before claiming',async()=>{vi.stubEnv('ENCRYPTION_KEY','');await expect(renewSocialConnection(input,'actor')).rejects.toThrow('Secure credential storage');expect(rpc).not.toHaveBeenCalled()})
 it('can recover an existing saved request while paused without reading current app secrets',async()=>{from.mockReturnValue(row({id:'request'}));rpc.mockResolvedValue({data:{state:'held'},error:null});vi.stubEnv('OUTBOUND_DELIVERY_PAUSED','true');expect(await renewSocialConnection(input,'actor')).toEqual({state:'held'});expect(credentials).not.toHaveBeenCalled();expect(provider).not.toHaveBeenCalled();expect(rpc.mock.calls[0][1].p_payload).toEqual({connectionId:'connection',expectedVersion:3,reason:input.reason})})
 it('does not exchange after the claim acknowledgement is lost',async()=>{rpc.mockResolvedValue({data:null,error:{message:'lost response'}});await expect(renewSocialConnection(input,'actor')).rejects.toThrow();expect(rpc).toHaveBeenCalledTimes(1);expect(provider).not.toHaveBeenCalled()})
 it('does not repeat an exchange already claimed by another request',async()=>{rpc.mockResolvedValue({data:{state:'exchanging'},error:null});expect(await renewSocialConnection(input,'actor')).toEqual({state:'exchanging'});expect(provider).not.toHaveBeenCalled()})
 it('retries only identical encrypted result persistence after a lost finalization reply',async()=>{let failures=0;const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,...args:unknown[])=>name==='finish_forgestudio_renewal'&&failures++===0?{data:null,error:{message:'lost response'}}:original(name,...args));const result=await renewSocialConnection(input,'actor');expect(result).toMatchObject({renewalId:'request',connectionId:'connection',renewalState:'held'});expect(provider).toHaveBeenCalledTimes(1);expect(provider).toHaveBeenCalledWith('x',expect.objectContaining({appSecret:'secret'}),expect.objectContaining({accountId:'saved-account',refreshToken:'old-refresh'}));const calls=rpc.mock.calls.filter(c=>c[0]==='finish_forgestudio_renewal');expect(calls).toHaveLength(2);expect(calls[0][1]).toEqual(calls[1][1]);expect(JSON.stringify(rpc.mock.calls[0][1])).not.toContain('old-refresh')})
 it('leaves an interrupted exchange recoverable when result storage fails twice',async()=>{const original=rpc.getMockImplementation()!;rpc.mockImplementation(async(name:string,...args:unknown[])=>name==='finish_forgestudio_renewal'?{data:null,error:{message:'storage unavailable'}}:original(name,...args));await expect(renewSocialConnection(input,'actor')).rejects.toThrow();expect(provider).toHaveBeenCalledTimes(1);expect(rpc.mock.calls.filter(c=>c[0]==='finish_forgestudio_renewal')).toHaveLength(2)})
})
