import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {NextRequest} from 'next/server'
const {auth,access,from,rpc}=vi.hoisted(()=>({auth:vi.fn(),access:vi.fn(),from:vi.fn(),rpc:vi.fn()}))
vi.mock('@/utils/supabase/server',()=>({createClient:async()=>({auth:{getUser:auth}})}))
vi.mock('@/utils/services/auth-guard',()=>({validatePropertyAccess:access,validatePropertyManagerAccess:access}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({from,rpc})}))
import * as config from '@/app/api/forgestudio/social/config/route'
import * as connections from '@/app/api/forgestudio/social/connections/route'
import * as authorizations from '@/app/api/forgestudio/social/authorizations/route'
const propertyId='33333333-3333-4333-8333-333333333333',requestId='55555555-5555-4555-8555-555555555555',connectionId='66666666-6666-4666-8666-666666666666'
const request=(path:string,body?:unknown,method='POST')=>new NextRequest(`http://localhost/api/forgestudio/social/${path}${body?'':`?propertyId=${propertyId}`}`,body?{method,body:JSON.stringify(body),headers:{'Content-Type':'application/json'}}:undefined)
function chain(data:unknown,error:unknown=null){const result={data,error},q={select:vi.fn(),eq:vi.fn(),order:vi.fn(),limit:vi.fn(),gt:vi.fn(),or:vi.fn(),maybeSingle:vi.fn(),then:vi.fn()};for(const key of ['select','eq','order','limit','gt','or'] as const)q[key].mockReturnValue(q);q.maybeSingle.mockResolvedValue(result);q.then.mockImplementation((r:(v:unknown)=>unknown)=>Promise.resolve(result).then(r));from.mockReturnValue(q);return q}
beforeEach(()=>{vi.clearAllMocks();auth.mockResolvedValue({data:{user:{id:'operator'}},error:null});access.mockResolvedValue({authorized:true});rpc.mockResolvedValue({data:{state:'saved'},error:null});vi.stubEnv('ENCRYPTION_KEY','local-api-test-key')})
afterEach(()=>vi.unstubAllEnvs())
describe('versioned social connection APIs',()=>{
 it('requires an authenticated session for every private read',async()=>{auth.mockResolvedValue({data:{user:null},error:null});for(const [name,route]of Object.entries({config,connections,authorizations}))expect((await route.GET(request(name))).status).toBe(401);expect(from).not.toHaveBeenCalled()})
 it('checks current property access before account reads',async()=>{access.mockResolvedValue({authorized:false});expect((await connections.GET(request('connections'))).status).toBe(403);expect(from).not.toHaveBeenCalled()})
 it('does not present a failed account read as an empty success',async()=>{chain(null,{message:'database failure'});const r=await connections.GET(request('connections'));expect(r.status).toBe(503);expect(await r.json()).not.toHaveProperty('connections')})
 it('uses an account cursor and does not select private credential columns',async()=>{const q=chain(Array.from({length:31},(_,i)=>({id:String(i),refresh_token:'secret-refresh',permission_evidence:{source:'provider_response',expiryKnown:true,access_token:'secret'},token_expires_at:null})));const r=await connections.GET(new NextRequest(`http://localhost/api/forgestudio/social/connections?propertyId=${propertyId}&cursor=${connectionId}`)),data=await r.json();expect(data.connections).toHaveLength(30);expect(data.nextCursor).toBe('29');expect(q.gt).toHaveBeenCalledWith('id',connectionId);expect(q.select.mock.calls[0][0]).not.toContain('access_token');expect(JSON.stringify(data)).not.toContain('secret')})
 it('retires unversioned disconnect rather than deleting account rows',async()=>{expect((await connections.DELETE(request('connections',{},'DELETE'))).status).toBe(400);expect(rpc).not.toHaveBeenCalled()})
 it('requires manager access for disconnect and retains the exact request identity',async()=>{const body={propertyId,requestId,connectionId,expectedVersion:4,reason:'Disconnect reviewed account'};access.mockResolvedValueOnce({authorized:false});expect((await connections.DELETE(request('connections',body,'DELETE'))).status).toBe(403);expect(rpc).not.toHaveBeenCalled();expect((await connections.DELETE(request('connections',body,'DELETE'))).status).toBe(200);expect(rpc).toHaveBeenCalledWith('disconnect_forgestudio_connection',{p_id:requestId,p_property_id:propertyId,p_actor_id:'operator',p_payload:{connectionId,expectedVersion:4,reason:body.reason}})})
 it('returns stale account decisions as a conflict',async()=>{rpc.mockResolvedValue({data:{state:'stale_connection'},error:null});expect((await connections.DELETE(request('connections',{propertyId,requestId,connectionId,expectedVersion:4,reason:'Disconnect reviewed account'},'DELETE'))).status).toBe(409)})
 it('never exposes a configured app secret and respects a disabled tombstone',async()=>{vi.stubEnv('META_APP_ID','env-app');vi.stubEnv('META_APP_SECRET','env-secret');const q=chain({id:connectionId,platform:'meta',app_id:'saved-app',is_configured:false,configuration_version:3});const r=await config.GET(request('config')),data=await r.json();expect(data).toMatchObject({hasConfig:false,disabled:true,version:3,configSource:'database'});expect(q.select.mock.calls[0][0]).not.toContain('secret');expect(JSON.stringify(data)).not.toContain('env-secret')})
 it('sends only a keyed secret fingerprint in the replayable app decision',async()=>{const body={propertyId,requestId,platform:'meta',expectedVersion:0,action:'save',appId:'fixture-app',appSecret:'fixture-secret'};expect((await config.POST(request('config',body))).status).toBe(200);const args=rpc.mock.calls[0][1];expect(args.p_encrypted_secret).toMatch(/^encv1:/);expect(args.p_payload.secretFingerprint).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(args)).not.toContain('fixture-secret')})
 it('explains missing server encryption setup and refuses plaintext credential saves',async()=>{vi.stubEnv('ENCRYPTION_KEY','');chain(null);const read=await config.GET(request('config'));expect((await read.json()).credentialStorageAvailable).toBe(false);const saved=await config.POST(request('config',{propertyId,requestId,platform:'meta',expectedVersion:0,action:'save',appId:'fixture',appSecret:'private'}));expect(saved.status).toBe(503);expect((await saved.json()).error).toContain('Secure credential storage');expect(rpc).not.toHaveBeenCalled()})
 it('rejects legacy config deletion and unknown writes',async()=>{expect((await config.DELETE()).status).toBe(409);expect((await config.POST(request('config',{propertyId,requestId,platform:'meta',expectedVersion:0,action:'disable',untrusted:'field'}))).status).toBe(400)})
 it('returns only safe candidate account evidence from a private authorization receipt',async()=>{chain([{id:requestId,platform:'facebook',state:'review_required',decision_version:2,result:{status:'observed',accounts:[{accountId:'one',accountName:'Candidate',accessTokenEncrypted:'encv1:private',refreshTokenEncrypted:'encv1:refresh',permissionEvidence:{expiryKnown:true}}]}}]);const r=await authorizations.GET(request('authorizations')),data=await r.json();expect(data.authorizations[0].accounts[0].accountId).toBe('one');expect(JSON.stringify(data)).not.toContain('encv1:')})
 it('applies only a versioned explicit selection with the operator reason',async()=>{const body={propertyId,requestId,authorizationId:connectionId,expectedVersion:2,action:'apply',accountIds:['reviewed-one'],reason:'Reviewed property ownership'};expect((await authorizations.POST(request('authorizations',body))).status).toBe(200);expect(rpc).toHaveBeenCalledWith('apply_forgestudio_authorization',expect.objectContaining({p_id:requestId,p_payload:{authorizationId:connectionId,expectedVersion:2,accountIds:['reviewed-one'],reason:body.reason}}));expect((await authorizations.POST(request('authorizations',{...body,accountIds:[]}))).status).toBe(400)})
})
