import type{AccountCommand,Section}from'./contracts'
import{teamFetch}from'@/utils/team/client'
export{teamFetch as accountFetch}
export type AccountWrite=AccountCommand extends infer C?C extends{requestId:string}?Omit<C,'requestId'>:never:never
export type PendingAccount={id:string;hash:string}
const key=(actor:string,org:string,section:Section)=>`p11.account-settings.pending.v1:${actor}:${org}:${section}`
export function pendingAccount(actor:string,org:string,section:Section):PendingAccount|null{try{const v=JSON.parse(sessionStorage.getItem(key(actor,org,section))||'null');return typeof v?.id==='string'&&typeof v?.hash==='string'?v:null}catch{return null}}
export function clearPendingAccount(actor:string,org:string,section:Section,id:string){if(pendingAccount(actor,org,section)?.id===id)sessionStorage.removeItem(key(actor,org,section))}
export function accountUrl(input:Record<string,string|number|undefined>={}){const q=new URLSearchParams();for(const[k,v]of Object.entries(input))if(v!==undefined)q.set(k,String(v));return'/api/settings?'+q}
export async function postAccount(actor:string,command:AccountWrite){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(command))),hash=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join(''),prior=pendingAccount(actor,command.orgId,command.section);if(prior&&prior.hash!==hash)throw new Error('Check the earlier settings decision before changing this request.');const id=prior?.id||crypto.randomUUID();sessionStorage.setItem(key(actor,command.orgId,command.section),JSON.stringify({id,hash}));try{const r=await teamFetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,requestId:id})});if(!['saved','replayed'].includes(r.state)||r.decisionId!==id||r.orgId!==command.orgId||r.actorId!==actor||r.section!==command.section)throw new Error('The settings receipt could not be verified. Check its saved decision.');clearPendingAccount(actor,command.orgId,command.section,id);return r}catch(e){if(e instanceof Error&&'status'in e&&[400,403,409,413].includes(Number(e.status)))clearPendingAccount(actor,command.orgId,command.section,id);throw e}}
