import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest'
const mocks=vi.hoisted(()=>({actor:vi.fn(),rpc:vi.fn()}))
vi.mock('@/utils/propertyaudit/decision-store',async()=>{const actual=await vi.importActual<typeof import('@/utils/propertyaudit/decision-store')>('@/utils/propertyaudit/decision-store');return {...actual,auditActor:mocks.actor,auditRpc:mocks.rpc}})
import {GET,POST} from './route'
const id='aa790000-0000-4000-8000-000000000001',propertyId='aa790000-0000-4000-8000-000000000002',actor='aa790000-0000-4000-8000-000000000003'
const input={id,propertyId,expectedActorId:actor,operation:'prepare',batchId:id,crawlId:id,sourceHash:'a'.repeat(64),modelHash:'b'.repeat(64)}
const request=(body:unknown,origin='http://localhost')=>new Request('http://localhost/api/propertyaudit/recommendation-work',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)})
beforeEach(()=>{vi.clearAllMocks();mocks.actor.mockResolvedValue(actor);mocks.rpc.mockResolvedValue({state:'ready',propertyId,id,items:[],count:55});vi.stubEnv('SITEAUDIT_ANALYST_PROVIDER','openai');vi.stubEnv('SITEAUDIT_ANALYST_OPENAI_MODEL','fixture-model');vi.stubEnv('SITEAUDIT_ANALYST_ENABLED','false')})
afterEach(()=>vi.unstubAllEnvs())
async function configured(){return(await GET(new Request('http://localhost/api/propertyaudit/recommendation-work?propertyId='+propertyId))).json()}
describe('retained recommendation API',()=>{
 it('requires same-origin and rejects browser-injected provider output',async()=>{expect((await POST(request(input,'https://elsewhere.invalid'))).status).toBe(403);expect((await POST(request({...input,preview:{recommendations:[]}}))).status).toBe(400);expect(mocks.rpc).not.toHaveBeenCalled()})
 it('holds changed identity before native mutation',async()=>{mocks.actor.mockResolvedValue(id);expect((await POST(request(input))).status).toBe(409);expect(mocks.rpc).not.toHaveBeenCalled()})
 it('holds a changed provider plan before saving work',async()=>{expect((await POST(request(input))).status).toBe(409);expect(mocks.rpc).not.toHaveBeenCalled()})
 it('pins the actual server model and queues one source without invoking a provider',async()=>{const config=await configured();mocks.rpc.mockClear();expect((await POST(request({...input,modelHash:config.modelHash}))).status).toBe(200);expect(mocks.rpc).toHaveBeenCalledTimes(1);expect(mocks.rpc).toHaveBeenCalledWith('prepare_geo_analysis',expect.objectContaining({p_actor_id:actor,p_plan:{provider:'openai',model:'fixture-model'},p_source_hash:input.sourceHash,p_batch_id:id,p_crawl_id:id}));expect(config.workerEnabled).toBe(false)})
 it('retains explicit retry ancestry',async()=>{const config=await configured();await POST(request({...input,modelHash:config.modelHash,parentId:id}));expect(mocks.rpc).toHaveBeenLastCalledWith('prepare_geo_analysis',expect.objectContaining({p_parent_id:id}))})
 it.each(['apply','discard','stop','resume'])('records %s against the exact retained preview identity',async(operation)=>{const r=await POST(request({id,propertyId,expectedActorId:actor,operation,analysisId:id,previewHash:'a'.repeat(64),reason:'Reviewed exact retained evidence'}));expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('decide_geo_analysis',expect.objectContaining({p_operation:operation,p_analysis_id:id,p_preview_hash:'a'.repeat(64),p_actor_id:actor}))})
 it('reads current property-scoped history and source pages',async()=>{const r=await GET(new Request('http://localhost/api/propertyaudit/recommendation-work?propertyId='+propertyId+'&kind=sources&offset=50'));expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('read_geo_analyses',expect.objectContaining({p_actor_id:actor,p_property_id:propertyId,p_kind:'sources',p_offset:50}));expect((await r.json()).count).toBe(55)})
 it('recovers a saved decision without another mutation',async()=>{await GET(new Request('http://localhost/api/propertyaudit/recommendation-work?propertyId='+propertyId+'&commandId='+id));expect(mocks.rpc).toHaveBeenCalledWith('read_geo_operator',expect.objectContaining({p_input:{kind:'command',id}}))})
 it('cancels unused prepare and decision identities through their native fences',async()=>{await POST(request({id,propertyId,expectedActorId:actor,operation:'cancel'}));expect(mocks.rpc).toHaveBeenLastCalledWith('prepare_geo_analysis',expect.objectContaining({p_cancel:true,p_plan:null}));await POST(request({id,propertyId,expectedActorId:actor,operation:'cancel_decision'}));expect(mocks.rpc).toHaveBeenLastCalledWith('decide_geo_operator',expect.objectContaining({p_input:{operation:'cancel_request'}}))})
})
