import {beforeEach,describe,expect,it,vi}from 'vitest'
const{actor,rpc}=vi.hoisted(()=>({actor:vi.fn(),rpc:vi.fn()}))
vi.mock('@/utils/property-setup/store',async(importOriginal)=>{const actual=await importOriginal<typeof import('@/utils/property-setup/store')>();return{...actual,requireSetupActor:actor,setupRpc:rpc}})
import {GET,PUT}from './route'
import {PropertySetupError}from '@/utils/property-setup/store'
const property='33333333-3333-3333-3333-333333333333',id='11111111-1111-1111-1111-111111111111',params={params:Promise.resolve({id:property})}
const profile={name:'Synthetic property',propertyType:null,address:{street:'',city:'Only city',state:'',zip:''},websiteUrl:'',additionalUrls:[],unitCount:0,yearBuilt:null,amenities:[],specialFeatures:[],brandVoice:'',targetAudience:''}
const payload=()=>({requestId:id,expectedHash:'a'.repeat(64),profile,contacts:[],connectionRequests:[],reason:'Correct the property record'})
const put=(v:unknown)=>PUT(new Request(`http://local/api/properties/${property}/setup`,{method:'PUT',body:JSON.stringify(v)}),params)
describe('versioned property editing routes',()=>{beforeEach(()=>{vi.clearAllMocks();actor.mockResolvedValue(id);rpc.mockResolvedValue({state:'saved',id})})
 it('uses the authenticated actor and retains explicit zero, blank street and contact removal',async()=>{expect((await put(payload())).status).toBe(200);expect(rpc).toHaveBeenCalledWith('save_property_setup',{p_id:id,p_property_id:property,p_actor_id:id,p_input:{...payload(),requestId:undefined}});const input=rpc.mock.calls[0][1].p_input;expect(input).not.toHaveProperty('requestId');expect(input.profile.unitCount).toBe(0);expect(input.profile.address.city).toBe('Only city');expect(input.contacts).toEqual([])})
 it('rejects actor injection, credential fields and unversioned legacy property saves',async()=>{for(const value of[{...payload(),actorId:id},{...payload(),connectionRequests:[{platform:'google_ads',accountId:'a',accountName:'a',notes:'',status:'verified'}]},{property:profile,contacts:[]}])expect((await put(value)).status).toBe(400);expect(rpc).not.toHaveBeenCalled()})
 it('rejects fractional counts and unsafe URL schemes without a write',async()=>{for(const p of[{...profile,unitCount:1.5},{...profile,websiteUrl:'javascript:alert(1)'},{...profile,websiteUrl:'https://user:password@example.test'}])expect((await put({...payload(),profile:p})).status).toBe(400);expect(rpc).not.toHaveBeenCalled()})
 it('requires a current actor and surfaces stale saves as conflicts',async()=>{actor.mockRejectedValueOnce(new PropertySetupError('Unauthorized',401));expect((await put(payload())).status).toBe(401);rpc.mockRejectedValueOnce(new PropertySetupError('Property details changed',409));const response=await put(payload());expect(response.status).toBe(409);expect(await response.json()).toEqual({error:'Property details changed'})})
 it('passes exact scoped history identities and returns private no-store reads',async()=>{rpc.mockResolvedValue({state:'ready',propertyId:property});const response=await GET(new Request(`http://local/api/properties/${property}/setup?cursor=${id}&changeId=${id}`),params);expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('private, no-store');expect(rpc).toHaveBeenCalledWith('read_property_setup',{p_property_id:property,p_actor_id:id,p_cursor:id,p_change_id:id});expect((await GET(new Request(`http://local/api/properties/${property}/setup?actorId=${id}`),params)).status).toBe(400)})
})
