import {beforeEach,afterEach,describe,expect,it,vi}from 'vitest'
import {savePropertySetup}from './client'
const property='33333333-3333-3333-3333-333333333333'
const payload={expectedHash:'a'.repeat(64),reason:'Private operator reason',profile:{name:'Private client name',propertyType:null,address:{street:'Private address',city:'',state:'',zip:''},websiteUrl:'',additionalUrls:[],unitCount:0,yearBuilt:null,amenities:[],specialFeatures:[],brandVoice:'',targetAudience:''},contacts:[],connectionRequests:[]}
describe('recoverable property save',()=>{let items:Map<string,string>;beforeEach(()=>{items=new Map();vi.stubGlobal('sessionStorage',{getItem:(k:string)=>items.get(k)??null,setItem:(k:string,v:string)=>items.set(k,v),removeItem:(k:string)=>items.delete(k)})});afterEach(()=>vi.unstubAllGlobals())
 it('reuses exact identity after a lost response without retaining private text in session storage',async()=>{const fetcher=vi.fn().mockRejectedValueOnce(new Error('Lost reply')).mockImplementationOnce(async(_url:string,init:RequestInit)=>Response.json({state:'replayed',id:JSON.parse(String(init.body)).requestId,afterHash:'a'.repeat(64),contextInvalidated:false,changedSections:['profile']}));vi.stubGlobal('fetch',fetcher);await expect(savePropertySetup(property,payload)).rejects.toThrow('Lost reply');const stored=JSON.stringify([...items]);expect(stored).not.toContain('Private');expect(stored).toMatch(/p11\.property-edit\.[a-f0-9]{64}/);await savePropertySetup(property,{...payload,profile:{...payload.profile}});expect(JSON.parse(fetcher.mock.calls[0][1].body).requestId).toBe(JSON.parse(fetcher.mock.calls[1][1].body).requestId);expect(items.size).toBe(0)})
 it('separates new property baselines and changed decisions',async()=>{const fetcher=vi.fn().mockRejectedValue(new Error('Lost reply'));vi.stubGlobal('fetch',fetcher);await savePropertySetup(property,payload).catch(()=>{});await savePropertySetup(property,{...payload,expectedHash:'b'.repeat(64)}).catch(()=>{});await savePropertySetup('44444444-4444-4444-4444-444444444444',payload).catch(()=>{});expect(new Set(fetcher.mock.calls.map(c=>JSON.parse(c[1].body).requestId)).size).toBe(3)})
 it('keeps the retry identity when a success response has an unverifiable receipt',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({state:'saved',id:'wrong'})));await expect(savePropertySetup(property,payload)).rejects.toThrow('receipt could not be verified');expect(items.size).toBe(1)})
 it('blocks submission if a recoverable session identity cannot be retained',async()=>{vi.stubGlobal('sessionStorage',{getItem:()=>{throw new Error('blocked')}});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(savePropertySetup(property,payload)).rejects.toThrow('session storage');expect(fetcher).not.toHaveBeenCalled()})
})

it('requires an explicit completion receipt and preserves the same completion identity on retry',async()=>{const values=new Map<string,string>();vi.stubGlobal('sessionStorage',{getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)});const fetcher=vi.fn().mockImplementation(async(_url:string,init:RequestInit)=>Response.json({state:'saved',id:JSON.parse(String(init.body)).requestId,afterHash:'a'.repeat(64),contextInvalidated:false,changedSections:[]}));vi.stubGlobal('fetch',fetcher);try{await expect(savePropertySetup(property,payload,true)).rejects.toThrow('receipt could not be verified');expect(values.size).toBe(1);fetcher.mockImplementation(async(_url:string,init:RequestInit)=>Response.json({state:'replayed',id:JSON.parse(String(init.body)).requestId,afterHash:'a'.repeat(64),contextInvalidated:false,changedSections:[],setupCompleted:true}));await savePropertySetup(property,payload,true);expect(fetcher.mock.calls[0][0]).toBe(`/api/properties/create?propertyId=${property}`);expect(fetcher.mock.calls[0][1].method).toBe('POST');expect(JSON.parse(String(fetcher.mock.calls[0][1].body)).requestId).toBe(JSON.parse(String(fetcher.mock.calls[1][1].body)).requestId);expect(values.size).toBe(0)}finally{vi.unstubAllGlobals()}})
