import {z} from 'zod'
export const propertyIdSchema=z.string().regex(/^[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}$/i)
const addressSchema=z.object({street:z.string().max(500),city:z.string().max(500),state:z.string().max(500),zip:z.string().max(500)}).strict()
const website=z.string().max(4000).refine(value=>{if(!value)return true;try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&!/\s/.test(value)}catch{return false}},'Use a complete HTTP or HTTPS website address without embedded credentials.')
export const profileSchema=z.object({name:z.string().trim().min(1).max(300),propertyType:z.string().max(100).nullable(),address:addressSchema,websiteUrl:website,additionalUrls:z.array(website.refine(Boolean,'An additional website address cannot be blank.')).max(50),unitCount:z.number().int().min(0).max(1000000).nullable(),yearBuilt:z.number().int().min(1).max(9999).nullable(),amenities:z.array(z.string().trim().min(1).max(4000)).max(200),specialFeatures:z.array(z.string().trim().min(1).max(4000)).max(200),brandVoice:z.string().max(4000),targetAudience:z.string().max(4000)}).strict()
export const contactSchema=z.object({id:propertyIdSchema,type:z.enum(['primary','secondary','billing','emergency']),name:z.string().trim().min(1).max(500),email:z.string().trim().email().max(500),phone:z.string().max(500),role:z.string().max(500),billingAddress:addressSchema,billingMethod:z.enum(['','ops_merchant','nexus','ach','check','credit_card','other']),specialInstructions:z.string().max(4000),needsW9:z.boolean(),isPrimary:z.boolean()}).strict()
export const CONNECTION_PLATFORMS={google_analytics:'Google Analytics',google_search_console:'Google Search Console',google_tag_manager:'Google Tag Manager',google_ads:'Google Ads',google_business_profile:'Google Business Profile',meta_ads:'Meta Ads',linkedin_ads:'LinkedIn Ads',tiktok_ads:'TikTok Ads',email_marketing:'Email marketing',crm:'CRM',pms:'Property management system'}as const
export const connectionRequestSchema=z.object({platform:z.enum(Object.keys(CONNECTION_PLATFORMS)as[keyof typeof CONNECTION_PLATFORMS,...(keyof typeof CONNECTION_PLATFORMS)[]]),accountId:z.string().max(500),accountName:z.string().max(500),notes:z.string().max(4000)}).strict()
export const propertySetupSaveSchema=z.object({requestId:propertyIdSchema,expectedHash:z.string().regex(/^[a-f0-9]{64}$/),profile:profileSchema,contacts:z.array(contactSchema).max(100),connectionRequests:z.array(connectionRequestSchema).max(11),reason:z.string().trim().min(3).max(2000)}).strict().superRefine((v,ctx)=>{if(new Set(v.contacts.map(c=>c.id)).size!==v.contacts.length)ctx.addIssue({code:'custom',message:'Contact identities must be unique.'});if(v.contacts.filter(c=>c.type==='primary'||c.isPrimary).length>1)ctx.addIssue({code:'custom',message:'Choose at most one primary contact.'});if(new Set(v.connectionRequests.map(c=>c.platform)).size!==v.connectionRequests.length)ctx.addIssue({code:'custom',message:'Connection requests must be unique.'})})
export const setupReadSchema=z.object({cursor:propertyIdSchema.optional(),changeId:propertyIdSchema.optional()}).strict()
export type PropertyProfile=z.infer<typeof profileSchema>
export type SetupContact=z.infer<typeof contactSchema>
export type ConnectionRequest=z.infer<typeof connectionRequestSchema>
export type SetupSnapshot={profile:PropertyProfile;contacts:SetupContact[];connectionRequests:ConnectionRequest[]}
export type SetupChange={kind?:'created'|'edited'|'setup_completed';id:string;actorId:string;actorName:string|null;createdAt:string;reason:string;changedSections:string[];contextInvalidated:boolean}
export type SetupHistoryDetail=SetupChange&{before:SetupSnapshot;after:SetupSnapshot;beforeHash:string;afterHash:string}
export type SetupWorkspace={state:'ready';propertyId:string;canEdit:boolean;snapshot:SetupSnapshot;snapshotHash:string;property:Record<string,unknown>;connections:Array<{id:string;platform:string;status:string|null;account_id:string|null;account_name:string|null;notes:string|null}>;context:{status:string;requiresReview:boolean;lastGeneratedAt:string|null;changeSummary:string|null}|null;changes:SetupChange[];total:number;nextCursor:string|null;selected:SetupHistoryDetail|null}
export function newSetupContact():SetupContact{return{id:crypto.randomUUID(),type:'secondary',name:'',email:'',phone:'',role:'',billingAddress:{street:'',city:'',state:'',zip:''},billingMethod:'',specialInstructions:'',needsW9:false,isPrimary:false}}
