import {propertyIdSchema,profileSchema,contactSchema,connectionRequestSchema}from './contracts'
import {creationSchema,type CreationReceipt,type TemplateSelection,type PropertyProfile}from './creation-contracts'
// Only an opaque in-progress identity is retained, never the private form or template data.
const key='p11.property-create.pending.v1'
export function pendingCreationId(){try{const id=sessionStorage.getItem(key);if(!id)return null;if(!propertyIdSchema.safeParse(id).success)throw new Error('Invalid saved identity');return id}catch{throw new Error('Allow session storage to retain one recoverable property-creation identity.')}}
function receipt(data:unknown,id:string):CreationReceipt{const r=data as Partial<CreationReceipt>|null;if(!r||!['ready','created','replayed'].includes(r.state||'')||r.requestId!==id||r.propertyId!==id||r.property?.id!==id||!r.snapshot||!profileSchema.safeParse(r.snapshot.profile).success||!Array.isArray(r.snapshot.contacts)||!r.snapshot.contacts.every(c=>contactSchema.safeParse(c).success)||!Array.isArray(r.snapshot.connectionRequests)||!r.snapshot.connectionRequests.every(c=>connectionRequestSchema.safeParse(c).success)||typeof r.snapshotHash!=='string'||!/^[a-f0-9]{64}$/.test(r.snapshotHash))throw new Error('The saved property receipt could not be verified. Keep the request and check again.');return r as CreationReceipt}
export function acknowledgeCreation(id:string){try{if(sessionStorage.getItem(key)===id)sessionStorage.removeItem(key)}catch{/* A retained confirmed identity is safe to recover again. */}}
async function request(url:string,init?:RequestInit){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{...init,cache:'no-store',signal:controller.signal});const data=response.status===404?null:await response.json();return{response,data}}finally{clearTimeout(timeout)}}
export async function recoverPendingCreation(){const id=pendingCreationId();if(!id)return null;const {response:r,data}=await request(`/api/properties/creation?requestId=${id}`);if(r.status===404)return null;if(!r.ok)throw new Error(data.error||'Saved creation could not be checked.');return receipt(data,id)}
export async function createProperty(profile:PropertyProfile,template:TemplateSelection|null){let id=pendingCreationId();if(!id){id=crypto.randomUUID();try{sessionStorage.setItem(key,id)}catch{throw new Error('Allow session storage before creating this property.')}}const parsed=creationSchema.safeParse({requestId:id,profile,template});if(!parsed.success)throw new Error(parsed.error.issues[0]?.message||'Review the new property details.');const {response:r,data}=await request('/api/properties/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});if(!r.ok)throw new Error(data.error||'The property creation could not be confirmed. Retry the same request.');return receipt(data,id)}
