import {knowledgeFetch} from '@/utils/knowledge/material-client'
import type {OrganizationCommand} from './organization-contracts'
export type PendingOrganization={id:string;actorId:string;hash:string;operation:string}
const key=(actor:string)=>`p11.organization.pending.v1:${actor}`
export function pendingOrganization(actor:string):PendingOrganization|null{try{const p=JSON.parse(sessionStorage.getItem(key(actor))||'null');return p?.actorId===actor&&typeof p.id==='string'&&typeof p.hash==='string'?p:null}catch{return null}}
export function clearPendingOrganization(actor:string,id:string){if(pendingOrganization(actor)?.id===id)sessionStorage.removeItem(key(actor))}
export function organizationUrl(input:Record<string,string|number|undefined>={}){const q=new URLSearchParams();for(const[k,v]of Object.entries(input))if(v!==undefined)q.set(k,String(v));return`/api/onboarding?${q}`}
type Command=OrganizationCommand extends infer C?C extends OrganizationCommand?Omit<C,'requestId'>:never:never
export async function postOrganization(actor:string,command:Command){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(command))),hash=Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join(''),prior=pendingOrganization(actor);if(prior&&prior.hash!==hash)throw new Error('Check the earlier setup decision before changing this request.');const id=prior?.id||crypto.randomUUID();sessionStorage.setItem(key(actor),JSON.stringify({id,actorId:actor,hash,operation:command.operation}));try{const result=await knowledgeFetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,requestId:id})});if(!['saved','replayed'].includes(result.state)||result.decisionId!==id)throw new Error('The setup receipt could not be verified. Check its saved decision.');clearPendingOrganization(actor,id);return result}catch(e){if(e instanceof Error&&'status'in e&&[400,403,409,413].includes(Number(e.status)))clearPendingOrganization(actor,id);throw e}}
