import {z} from 'zod'
import {profileSchema,contactSchema,connectionRequestSchema,propertyIdSchema as id} from './contracts'
import {creationProfile} from './creation-contracts'
import type {OnboardingFormData,OnboardingStep} from '@/app/onboarding/types'
const digest=z.string().regex(/^[a-f0-9]{64}$/)
export const organizationDraft=z.object({organization:z.object({name:z.string().max(300),type:z.enum(['','pmc','owner_operator','developer','reit','other']),legalName:z.string().max(500)}).strict(),profile:profileSchema.extend({name:z.string().max(300)}),contacts:z.array(contactSchema.extend({name:z.string().max(500),email:z.string().max(500)})).max(100),connectionRequests:z.array(connectionRequestSchema).max(11),step:z.enum(['organization','community','contacts','integrations','knowledge','review'])}).strict()
const base={requestId:id,reason:z.string().trim().min(3).max(2000)},revision=z.number().int().min(0).max(999999999)
export const organizationCommand=z.discriminatedUnion('operation',[
 z.object({...base,operation:z.literal('save'),expectedRevision:revision,draft:organizationDraft}).strict(),
 z.object({...base,operation:z.literal('complete'),expectedRevision:revision,draftHash:digest,confirmed:z.literal(true)}).strict(),
 z.object({...base,operation:z.literal('cancel_unused'),inputHash:digest}).strict()
])
export const organizationQuery=z.object({decisionId:id.optional(),offset:z.coerce.number().int().min(0).max(1000000).default(0),expectedHash:digest.optional()}).strict()
export type OrganizationDraft=z.infer<typeof organizationDraft>
export type OrganizationCommand=z.infer<typeof organizationCommand>
export type OrganizationWorkspace={actorId:string;alreadyMember:boolean;setup:{id:string;state:'draft'|'completed';revision:number;draft:OrganizationDraft;draftHash:string;org_id:string|null;property_id:string|null;completed_at:string|null}|null;items:Array<{id:string;kind:'save'|'complete';createdAt:string;reason:string;revision:number}>;total:number;historyHash:string;nextOffset:number|null}
export function draftFromForm(form:OnboardingFormData,step:OnboardingStep,prior?:OrganizationDraft):OrganizationDraft{return organizationDraft.parse({organization:form.organization,profile:{...creationProfile(form.community),specialFeatures:prior?.profile.specialFeatures||[],brandVoice:prior?.profile.brandVoice||'',targetAudience:prior?.profile.targetAudience||''},contacts:form.contacts.map(c=>({id:c.id,type:c.type,name:c.name,email:c.email,phone:c.phone||'',role:c.role||'',billingAddress:c.billingAddress||{street:'',city:'',state:'',zip:''},billingMethod:c.billingMethod||'',specialInstructions:c.specialInstructions||'',needsW9:c.needsW9||false,isPrimary:c.type==='primary'})),connectionRequests:form.integrations.map(i=>({platform:i.platform,accountId:i.accountId||'',accountName:i.accountName||'',notes:i.notes||''})),step:step==='complete'?'review':step})}
export function formFromDraft(draft:OrganizationDraft):OnboardingFormData{const p=draft.profile;return{organization:draft.organization,community:{name:p.name,type:(p.propertyType||'')as OnboardingFormData['community']['type'],address:p.address,websiteUrl:p.websiteUrl,additionalUrls:p.additionalUrls,unitCount:p.unitCount===null?'':String(p.unitCount),yearBuilt:p.yearBuilt===null?'':String(p.yearBuilt),amenities:p.amenities},contacts:draft.contacts.map(c=>({...c,billingMethod:c.billingMethod||undefined})),integrations:draft.connectionRequests.map(i=>({...i,status:'pending'})),documents:[]}}

export function validateCompleteDraft(draft:OrganizationDraft){const profile=profileSchema.safeParse(draft.profile),contacts=z.array(contactSchema).safeParse(draft.contacts);if(!draft.organization.name.trim())throw new Error('Organization name is required.');if(!profile.success)throw new Error(profile.error.issues[0]?.message||'Review the property details.');if(!contacts.success)throw new Error('Review the name and email of every saved contact.');if(draft.contacts.filter(c=>c.type==='primary').length!==1)throw new Error('Choose one primary contact before completing setup.');if(new Set(draft.contacts.map(c=>c.id)).size!==draft.contacts.length)throw new Error('Review duplicate contact identities.')}
