import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import type {Database} from '@/types/supabase'
import type {SupabaseClient} from '@supabase/supabase-js'
import {renewCalendarCredentials,type CalendarCredentials} from './calendar-credentials'
import {refreshAccessTokenIfNeeded} from './google-calendar'
const d=vi.hoisted(()=>({rpc:vi.fn(),fetch:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc:d.rpc})}))
const db={rpc:d.rpc} as unknown as SupabaseClient<Database>
const config=():CalendarCredentials=>({id:'calendar',property_id:'property',provider:'microsoft',account_email:'fixture@example.invalid',google_email:'fixture@example.invalid',calendar_id:'primary',credential_version:1,access_token:'old-access',refresh_token:'old-refresh',token_expires_at:'2020-01-01',token_status:'healthy'})
const saved={state:'saved',permissionState:'confirmed',accessToken:'new-access',refreshToken:'rotated-refresh',expiresAt:'2099-01-01T00:00:00Z',version:2}
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv('MICROSOFT_CLIENT_ID','fixture-client');vi.stubEnv('MICROSOFT_CLIENT_SECRET','fixture-secret');vi.stubEnv('GOOGLE_CLIENT_ID','google-fixture');vi.stubEnv('GOOGLE_CLIENT_SECRET','google-fixture-secret');vi.stubGlobal('fetch',d.fetch)
 d.rpc.mockImplementation(async(name:string,args:Record<string,unknown>)=>({data:name==='claim_calendar_token_refresh'?{state:'claimed',refreshToken:'db-refresh',version:1}:args.p_outcome==='success'?saved:{state:args.p_outcome==='unconfirmed'?'review':args.p_outcome==='temporary_failure'?'failed':'revoked'}}))
 d.fetch.mockResolvedValue({ok:true,json:async()=>({access_token:'new-access',refresh_token:'rotated-refresh',expires_in:3600,token_type:'Bearer'})})})
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals()})
it('persists rotated Microsoft credentials before returning and updates the request config',async()=>{const c=config();expect(await renewCalendarCredentials(c,false,db)).toEqual({accessToken:'new-access',expiresAt:saved.expiresAt});expect(c).toMatchObject({refresh_token:'rotated-refresh',credential_version:2});expect(d.rpc).toHaveBeenLastCalledWith('finish_calendar_token_refresh',expect.objectContaining({p_outcome:'success',p_tokens:expect.objectContaining({refreshToken:'rotated-refresh'})}));expect(d.fetch.mock.calls[0][1].body.get('refresh_token')).toBe('db-refresh');expect(d.fetch.mock.calls[0][1].signal).toBeInstanceOf(AbortSignal)})
it('allows Google to preserve its existing refresh token when none is returned',async()=>{d.fetch.mockResolvedValue({ok:true,json:async()=>({access_token:'new',expires_in:3600})});await renewCalendarCredentials({...config(),provider:'google'},false,db);expect(d.fetch.mock.calls[0][0]).toBe('https://oauth2.googleapis.com/token');expect(d.rpc.mock.calls.at(-1)?.[1].p_tokens).not.toHaveProperty('refreshToken')})
it('recovers an unacknowledged save by retrying only identical database finalization',async()=>{let writes=0;d.rpc.mockImplementation(async(name:string)=>{if(name==='claim_calendar_token_refresh')return {data:{state:'claimed',refreshToken:'db-refresh'}};if(++writes===1)throw new Error('Lost response');return {data:saved}});await renewCalendarCredentials(config(),false,db);expect(d.fetch).toHaveBeenCalledTimes(1);expect(d.rpc.mock.calls[1]).toEqual(d.rpc.mock.calls[2])})
it('returns no access token after both persistence attempts fail',async()=>{d.rpc.mockImplementation(async(name:string)=>name==='claim_calendar_token_refresh'?{data:{state:'claimed',refreshToken:'db-refresh'}}:{error:new Error('Save down')});await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow('could not be saved');expect(d.fetch).toHaveBeenCalledTimes(1)})
it('reuses a concurrently saved revision without another provider call',async()=>{d.rpc.mockResolvedValue({data:{...saved,state:'ready'}});await renewCalendarCredentials(config(),true,db);expect(d.fetch).not.toHaveBeenCalled()})
it.each(['busy','retry_later','connection_changed','refresh_unconfirmed','reconnect_required','permissions_unconfirmed','permissions_incomplete'])('holds %s before provider access',async state=>{d.rpc.mockResolvedValue({data:{state}});await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow();expect(d.fetch).not.toHaveBeenCalled()})
it('cannot resurrect credentials disconnected during the provider response',async()=>{d.rpc.mockImplementation(async(name:string)=>({data:name==='claim_calendar_token_refresh'?{state:'claimed',refreshToken:'db-refresh'}:{state:'connection_changed'}}));await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow('connection changed')})
it('records structured invalid_grant without retaining raw error details',async()=>{d.fetch.mockResolvedValue({ok:false,json:async()=>({error:'invalid_grant',error_description:'PRIVATE PROVIDER RESPONSE'})});await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow('revoked');expect(JSON.stringify(d.rpc.mock.calls)).not.toContain('PRIVATE PROVIDER RESPONSE');expect(d.rpc.mock.calls.at(-1)?.[1].p_outcome).toBe('revoked')})
it('treats network timeout as uncertain and does not repeat the OAuth request',async()=>{d.fetch.mockRejectedValue(new Error('SECRET NETWORK DETAILS'));await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow('could not be confirmed');expect(d.fetch).toHaveBeenCalledTimes(1);expect(d.rpc.mock.calls.at(-1)?.[1].p_outcome).toBe('unconfirmed')})
it('keeps explicit provider failure retryable',async()=>{d.fetch.mockResolvedValue({ok:false,json:async()=>({error:'temporarily_unavailable'})});await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow('unavailable');expect(d.rpc.mock.calls.at(-1)?.[1].p_outcome).toBe('temporary_failure')})
it.each([{access_token:'x',expires_in:0},{access_token:'',expires_in:3600},{access_token:'x',expires_in:'3600'},{access_token:'x',expires_in:3600,refresh_token:null},{access_token:'x',expires_in:3600,token_type:'MAC'},null])('does not accept malformed refresh result %j',async payload=>{d.fetch.mockResolvedValue({ok:true,json:async()=>payload});await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow();expect(d.rpc.mock.calls.at(-1)?.[1].p_outcome).toBe('unconfirmed')})
it('does not silently use an invalid expiry as a valid token',async()=>{await refreshAccessTokenIfNeeded({...config(),token_expires_at:'invalid'} as import('./google-calendar').CalendarConfig);expect(d.rpc).toHaveBeenCalled();expect(d.fetch).toHaveBeenCalledTimes(1)})
it('requires credentials and a recorded connection version before claiming',async()=>{await expect(renewCalendarCredentials({...config(),credential_version:undefined},false,db)).rejects.toThrow('Reload');expect(d.rpc).not.toHaveBeenCalled()})

it.each(['disconnected','revoked','refresh_unconfirmed'])('does not use unexpired credentials in %s state',async token_status=>{d.rpc.mockResolvedValue({data:{state:'reconnect_required'}});await expect(refreshAccessTokenIfNeeded({...config(),token_expires_at:'2099-01-01',token_status} as import('./google-calendar').CalendarConfig)).rejects.toThrow('Reconnect');expect(d.fetch).not.toHaveBeenCalled()})

it('passes explicit refreshed permissions to the atomic save',async()=>{d.fetch.mockResolvedValue({ok:true,json:async()=>({access_token:'new',expires_in:3600,scope:'User.Read'})});await renewCalendarCredentials(config(),false,db);expect(d.rpc.mock.calls.at(-1)?.[1].p_tokens.scope).toBe('User.Read')})
it('preserves explicitly malformed scope as unconfirmed evidence',async()=>{d.fetch.mockResolvedValue({ok:true,json:async()=>({access_token:'new',expires_in:3600,scope:null})});await renewCalendarCredentials(config(),false,db);expect(d.rpc.mock.calls.at(-1)?.[1].p_tokens).toHaveProperty('scope',null)})
it('requires the database permission verdict before returning saved credentials',async()=>{d.rpc.mockResolvedValue({data:{...saved,state:'ready',permissionState:undefined}});await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow('could not be confirmed');expect(d.fetch).not.toHaveBeenCalled()})
it('holds reduced permissions even after a successful token exchange',async()=>{d.rpc.mockImplementation(async(name:string)=>({data:name==='claim_calendar_token_refresh'?{state:'claimed',refreshToken:'db-refresh'}:{state:'permissions_incomplete'}}));await expect(renewCalendarCredentials(config(),false,db)).rejects.toThrow('missing required permissions');expect(d.fetch).toHaveBeenCalledTimes(1)})

it('checks fresh calendar credentials against the saved permission verdict',async()=>{d.rpc.mockResolvedValue({data:{state:'permissions_unconfirmed'}});await expect(refreshAccessTokenIfNeeded({...config(),token_expires_at:'2099-01-01'} as import('./google-calendar').CalendarConfig)).rejects.toThrow('permissions could not be confirmed');expect(d.fetch).not.toHaveBeenCalled()})
it('reuses verified fresh credentials without OAuth client configuration',async()=>{vi.stubEnv('MICROSOFT_CLIENT_ID','');vi.stubEnv('MICROSOFT_CLIENT_SECRET','');d.rpc.mockResolvedValue({data:{...saved,state:'ready'}});expect(await renewCalendarCredentials(config(),false,db)).toMatchObject({accessToken:saved.accessToken});expect(d.fetch).not.toHaveBeenCalled()})
