import {beforeEach,afterEach,expect,it,vi} from 'vitest'
import {createIntegrationAuthInvite,revokeIntegrationAuthInvite,hashInviteToken} from './integration-auth-invites'
const d=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc:d.rpc})}))
const input={requestId:'33333333-3333-4333-8333-333333333333',propertyId:'property',createdByProfileId:'actor',provider:'google' as const,capabilities:['calendar'] as ('calendar'|'email')[]}
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv('INTEGRATION_INVITE_SECRET','fixture-invite-key');vi.stubEnv('NEXT_PUBLIC_SITE_URL','http://127.0.0.1:9430');d.rpc.mockImplementation(async(name:string,args:Record<string,unknown>)=>({data:{state:name.startsWith('create')?'created':'revoked',actionEventId:args.p_request_id,invite:{id:args.p_request_id,property_id:args.p_property_id,expires_at:'2099-01-01'}}}))})
afterEach(()=>vi.unstubAllEnvs())
it('recovers the same capability token without storing it in the database request',async()=>{const first=await createIntegrationAuthInvite(input),second=await createIntegrationAuthInvite(input);expect(first.token).toBe(second.token);expect(first.url).toBe(second.url);expect(d.rpc.mock.calls[0][1]).toMatchObject({p_token_hash:hashInviteToken(first.token)});expect(JSON.stringify(d.rpc.mock.calls)).not.toContain(first.token)})
it('binds recovered capabilities to the property and authorizing operator',async()=>{const a=await createIntegrationAuthInvite(input),b=await createIntegrationAuthInvite({...input,propertyId:'different'}),c=await createIntegrationAuthInvite({...input,createdByProfileId:'different'});expect(new Set([a.token,b.token,c.token]).size).toBe(3)})
it('retries only the identical recorded operation after a lost acknowledgement',async()=>{d.rpc.mockRejectedValueOnce(new Error('Lost response'));await createIntegrationAuthInvite(input);expect(d.rpc.mock.calls).toHaveLength(2);expect(d.rpc.mock.calls[0]).toEqual(d.rpc.mock.calls[1])})
it('never returns a link after unconfirmed persistence',async()=>{d.rpc.mockResolvedValue({error:{message:'PRIVATE DB DETAILS'}});await expect(createIntegrationAuthInvite(input)).rejects.toThrow('could not be confirmed');expect(d.rpc).toHaveBeenCalledTimes(2)})
it.each(['forbidden','request_conflict','link_unavailable'])('does not expose a token for %s',async state=>{d.rpc.mockResolvedValue({data:{state}});await expect(createIntegrationAuthInvite(input)).rejects.toThrow();expect(d.rpc).toHaveBeenCalledTimes(1)})
it('requires the acknowledged action and invitation identities',async()=>{d.rpc.mockResolvedValue({data:{state:'created',actionEventId:'different',invite:{id:input.requestId,property_id:input.propertyId,expires_at:'2099-01-01'}}});await expect(createIntegrationAuthInvite(input)).rejects.toThrow('could not be confirmed')})
it('preserves the actual used-link revocation result',async()=>{d.rpc.mockResolvedValue({data:{state:'already_used',actionEventId:input.requestId}});expect(await revokeIntegrationAuthInvite({propertyId:input.propertyId,actorId:'actor',requestId:input.requestId,inviteId:'invite'})).toMatchObject({state:'already_used'})})
it('has no fallback to an empty or public invitation key',async()=>{for(const name of ['INTEGRATION_INVITE_SECRET','INTEGRATION_OAUTH_STATE_SECRET','GMAIL_OAUTH_STATE_SECRET','GOOGLE_CLIENT_SECRET','MICROSOFT_CLIENT_SECRET'])vi.stubEnv(name,'');await expect(createIntegrationAuthInvite(input)).rejects.toThrow('not configured');expect(d.rpc).not.toHaveBeenCalled()})
