import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import type {WorkflowDelivery} from './workflow-delivery'
const d=vi.hoisted(()=>({rpc:vi.fn(),email:vi.fn(),sms:vi.fn(),configured:vi.fn(),paused:vi.fn()}))
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc:d.rpc})}))
vi.mock('./delivery-guard',()=>({isDeliveryPaused:d.paused,DELIVERY_PAUSED_MESSAGE:'Paused'}))
vi.mock('./messaging',async importOriginal=>({...await importOriginal<object>(),sendEmail:d.email,sendMessage:d.sms,isMessagingConfigured:d.configured}))
import {processWorkflowDeliveries,workflowContent} from './workflow-delivery'
const work={id:'delivery',lead_workflow_id:'workflow',state:'running',channel:'email',recipient:'guest@example.invalid',lease_token:'token',body:null,subject:null,sender:null,snapshot:{firstName:'Guest',lastName:'Example',propertyName:'Fixture',tourLink:'https://example.invalid/tour',template:{body:'Hello {first_name} at {property_name}. {tour_link}',subject:'Hello'}}} as WorkflowDelivery
function rpc(name:string){if(name==='pending_workflow_deliveries')return {candidates:['workflow'],review:0};if(name==='prepare_workflow_delivery'||name==='start_workflow_delivery')return structuredClone(work);return true}
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv('RESEND_FROM_EMAIL','sender@example.invalid');vi.stubEnv('WORKFLOW_DELIVERY_PAUSED','false');d.paused.mockReturnValue(false);d.configured.mockReturnValue({email:true,sms:true});d.rpc.mockImplementation(async name=>({data:rpc(name),error:null}));d.email.mockResolvedValue({success:true,messageId:'receipt'});d.sms.mockResolvedValue({success:true,messageId:'sms-receipt'})})
afterEach(()=>vi.unstubAllEnvs())
it('does no database or transport work while paused',async()=>{d.paused.mockReturnValue(true);expect((await processWorkflowDeliveries()).errors).toEqual(['Paused']);expect(d.rpc).not.toHaveBeenCalled();expect(d.email).not.toHaveBeenCalled()})
it('also honors the workflow-only hold',async()=>{vi.stubEnv('WORKFLOW_DELIVERY_PAUSED','true');await processWorkflowDeliveries();expect(d.rpc).not.toHaveBeenCalled()})
it('requires durable attempt before transport and exact receipt acknowledgement afterward',async()=>{expect(await processWorkflowDeliveries()).toMatchObject({succeeded:1,failed:0});expect(d.rpc.mock.invocationCallOrder[2]).toBeLessThan(d.email.mock.invocationCallOrder[0]);expect(d.email.mock.calls[0][6]).toBe('workflow/delivery');expect(d.rpc).toHaveBeenLastCalledWith('finish_workflow_delivery',{p_id:'delivery',p_token:'token',p_provider_id:'receipt'})})
it('does not send when attempt acknowledgement is lost',async()=>{d.rpc.mockImplementation(async n=>n==='start_workflow_delivery'?{error:{message:'lost'}}:{data:rpc(n)});expect((await processWorkflowDeliveries()).failed).toBe(1);expect(d.email).not.toHaveBeenCalled();expect(d.rpc.mock.calls.map(c=>c[0])).not.toContain('finish_workflow_delivery')})
it('does not overwrite a potentially saved receipt after its response is lost',async()=>{d.rpc.mockImplementation(async n=>n==='finish_workflow_delivery'?{error:{message:'lost'}}:{data:rpc(n)});expect((await processWorkflowDeliveries()).failed).toBe(1);expect(d.email).toHaveBeenCalledOnce();expect(d.rpc.mock.calls.filter(c=>c[0]==='finish_workflow_delivery')).toHaveLength(1)})
it('requires explicit true acknowledgement for receipt persistence',async()=>{d.rpc.mockImplementation(async n=>({data:n==='finish_workflow_delivery'?false:rpc(n)}));expect((await processWorkflowDeliveries()).succeeded).toBe(0)})
it('does not retry a thrown transport error',async()=>{d.email.mockRejectedValue(new Error('lost response'));expect(await processWorkflowDeliveries()).toMatchObject({review:1,succeeded:0});expect(d.email).toHaveBeenCalledOnce();expect(d.rpc).toHaveBeenLastCalledWith('finish_workflow_delivery',expect.objectContaining({p_provider_id:null}))})
it('requires an actual provider ID',async()=>{d.email.mockResolvedValue({success:true});expect((await processWorkflowDeliveries()).review).toBe(1);expect(d.rpc).toHaveBeenLastCalledWith('finish_workflow_delivery',expect.objectContaining({p_provider_id:null}))})
it('skips competing claims without counting a send as successful',async()=>{d.rpc.mockImplementation(async n=>({data:n==='prepare_workflow_delivery'?null:rpc(n)}));expect(await processWorkflowDeliveries()).toMatchObject({skipped:1,succeeded:0});expect(d.email).not.toHaveBeenCalled()})
it('reconciles already saved receipts without crossing provider boundary',async()=>{d.rpc.mockImplementation(async n=>({data:n==='prepare_workflow_delivery'?{state:'accepted',settled:true}:rpc(n)}));expect((await processWorkflowDeliveries()).succeeded).toBe(1);expect(d.email).not.toHaveBeenCalled()})
it('surfaces held backlog and legacy attempts',async()=>{d.rpc.mockImplementation(async n=>({data:n==='pending_workflow_deliveries'?{candidates:[],review:5}:rpc(n)}));expect(await processWorkflowDeliveries()).toMatchObject({review:5,errors:['5 follow-ups need delivery review']})})
it('holds missing provider configuration before transport',async()=>{d.configured.mockReturnValue({email:false,sms:false});d.rpc.mockImplementation(async n=>({data:n==='start_workflow_delivery'?null:rpc(n)}));expect((await processWorkflowDeliveries()).review).toBe(1);expect(d.email).not.toHaveBeenCalled();expect(d.rpc).toHaveBeenCalledWith('start_workflow_delivery',expect.objectContaining({p_issue:'configuration_missing'}))})
it('continues independent work after a failed claim',async()=>{let claims=0;d.rpc.mockImplementation(async n=>n==='pending_workflow_deliveries'?{data:{candidates:['one','two'],review:0}}:n==='prepare_workflow_delivery'&&claims++===0?{error:{message:'failed'}}:{data:rpc(n)});expect(await processWorkflowDeliveries()).toMatchObject({failed:1,succeeded:1})})
it('fails closed on queue read errors',async()=>{d.rpc.mockResolvedValue({error:{message:'offline'}});await expect(processWorkflowDeliveries()).rejects.toThrow('could not be loaded');expect(d.email).not.toHaveBeenCalled()})
it('uses saved content and sender for reviewed SMS retries',async()=>{const saved={...work,channel:'sms',recipient:'+15550000000',body:'Pinned text',sender:'+15550000001'};d.rpc.mockImplementation(async n=>({data:n==='prepare_workflow_delivery'?saved:rpc(n)}));await processWorkflowDeliveries();expect(d.sms).toHaveBeenCalledWith({to:'+15550000000',channel:'sms',body:'Pinned text',from:'+15550000001'});expect(d.email).not.toHaveBeenCalled()})
it('holds unknown template variables and internal dashboard links',()=>{const invalid=structuredClone(work);invalid.snapshot.tourLink='https://example.invalid/dashboard/leads';expect(workflowContent(invalid).issue).toBe('template_variables_missing');invalid.snapshot.tourLink=null;expect(workflowContent(invalid).issue).toBe('template_variables_missing');expect(workflowContent(work).body).toContain('https://example.invalid/tour')})
