import { describe, it, expect } from 'vitest';
import { renderRetainedAuditReport, reportCsvCell, auditReportArtifactMeta } from './retained-report';
import { reportOptions, reportDecision } from './report-contracts';
const id = 'aa760000-0000-4000-8000-000000000001';
const options = { format: 'html' as const, template: 'comprehensive' as const, sections: ['summary', 'scores', 'models', 'competitors', 'recommendations', 'queries', 'appendix'] as ('summary' | 'scores' | 'models' | 'competitors' | 'recommendations' | 'queries' | 'appendix')[] };
function source() { return { version: 1, capturedAt: '2026-09-23T00:00:00Z', property: { id, name: 'Private <script>alert(1)</script>', website_url: 'https://fixture.invalid' }, queries: [{ id: 'q', text: 'A CURRENT replacement', decision_revision: 3, type: 'branded' }], performance: { answers: [] }, runs: [{ run: { id, surface: 'chatgpt', model_name: 'fixture', status: 'completed', query_count: 2, measurement_mode: 'local_fixture' }, job: { snapshot: { property: { name: 'ORIGINAL property name' } } }, scores: [{ overall_score: 42, visibility_pct: 50 }], items: [{ id: 'i1', query: { id: 'q', text: 'ORIGINAL question', type: 'branded' }, answerId: 'a1', state: 'completed' }, { id: 'i2', query: { id: 'q2', text: 'FAILED question', type: 'category' }, state: 'failed', errorCode: 'provider_unavailable' }], answers: [{ answer: { id: 'a1', query_id: 'q', presence: true, natural_response: 'ACTUAL <img onerror="evil()">', ordered_entities: [{ name: 'Ambiguous name', domain: 'example.invalid', position: 1 }] }, citations: [{ url: 'javascript:evil()', domain: 'example.invalid' }] }] }], findings: [{ id: 'f', title: '=HYPERLINK("evil")', status: 'fixed', notes: 'Staff reported', occurrences: 2 }], recommendations: [{ title: 'Saved recommendation', narrative: 'Grounded retained narrative', batch_id: 'batch', grounding: { citation: 'exact source' } }], trends: [], crawls: [], trendScope: 'Exact retained trend scope', findingScope: 'Staff-reported status only' }; }
describe('retained audit artifacts', () => {
    it('is deterministic, retains original words and complete failed coverage', () => { const a = renderRetainedAuditReport(source(), options); expect(a).toBe(renderRetainedAuditReport(source(), options)); expect(a).toContain('ORIGINAL question'); expect(a).not.toContain('A CURRENT replacement'); expect(a).toContain('FAILED question'); expect(a).toContain('Not measured'); expect(a).toContain('provider_unavailable'); expect(a).toContain('SYNTHETIC LOCAL TEST EVIDENCE'); expect(a).toContain('ORIGINAL property name'); expect(a).toContain('exact source'); });
    it('escapes hostile property names, responses and citations', () => { const a = renderRetainedAuditReport(source(), options); expect(a).not.toContain('<script>'); expect(a).not.toContain('<img'); expect(a).toContain('&lt;script&gt;'); expect(a).not.toContain('href="javascript:'); expect(a).toContain('javascript:evil()'); });
    it('does not substitute present question wording for older unlinked answers', () => { const s = source(); s.runs[0].items = []; const a = renderRetainedAuditReport(s, options); expect(a).toContain('Original question unavailable'); expect(a).not.toContain('A CURRENT replacement'); expect(a).toContain('ACTUAL'); });
    it('respects chosen sections while retaining source/coverage disclosure', () => { const a = renderRetainedAuditReport(source(), { ...options, sections: ['summary'] }); expect(a).not.toContain('Complete selected question'); expect(a).not.toContain('Retained recommendations'); expect(a).toContain('Saved evidence'); expect(a).toContain('Measured surfaces'); });
    it('exports all active inventory rows rather than truncating at API defaults', () => { const s = source(); s.queries = Array.from({ length: 1051 }, (_, n) => ({ id: `q${n}`, text: `Question ${n}`, type: 'branded', decision_revision: 1 })); const a = renderRetainedAuditReport(s, { ...options, format: 'queries_csv' }); expect(a.split('\r\n')).toHaveLength(1052); expect(a).toContain('Question 1050'); expect(a).toContain('Not measured'); expect(a).not.toContain('"false"'); });
    it('exports every retained finding and protects spreadsheet formula cells', () => { const a = renderRetainedAuditReport(source(), { ...options, format: 'findings_csv' }); expect(a).toContain("'=HYPERLINK"); expect(a).toContain('Staff-reported fixed at (UTC)'); expect(a).toContain('Staff reported'); });
    it.each(['=SUM(1,2)', '+cmd', '-cmd', '@cmd', '  =cmd', '\tcmd', '\rcmd', '\ncmd'])('fences formula-like CSV text %j', v => expect(reportCsvCell(v)).toMatch(/^"'/));
    it('escapes multiline quoted CSV without discarding its exact value', () => expect(reportCsvCell('A "quoted"\nline')).toBe('"A ""quoted""\nline"'));
    it('keeps zero measurements and numeric negative values distinct from missing', () => { expect(reportCsvCell(0)).toBe('"0"'); expect(reportCsvCell(-2)).toBe('"-2"'); expect(reportCsvCell(null)).toBe('""'); const s = source(); s.runs[0].scores[0].overall_score = 0; expect(renderRetainedAuditReport(s, options)).toContain('<td>0</td>'); });
    it('renders markdown with original evidence and honest scope', () => { const a = renderRetainedAuditReport(source(), { ...options, format: 'markdown' }); expect(a).toContain('ORIGINAL question'); expect(a).toContain('Actual answer'); expect(a).toContain('Exact retained trend scope'); expect(a).toContain('business outcomes require separate verification'); expect(a).not.toContain('<script>'); });
    it('rejects incomplete retained sources instead of substituting live data', () => expect(() => renderRetainedAuditReport({}, options)).toThrow('incomplete'));
    it('uses actual artifact extensions and never labels HTML as PDF bytes', () => { expect(auditReportArtifactMeta(id, options).filename).toMatch(/\.html$/); expect(auditReportArtifactMeta(id, { ...options, format: 'markdown' }).mime).toContain('markdown'); expect(auditReportArtifactMeta(id, { ...options, format: 'queries_csv' }).filename).toMatch(/\.csv$/); });
    it('rejects unknown formats, recipients, schedules, duplicate sections and ambiguous scope', () => {
        for (const x of [{ ...options, format: 'pdf' }, { ...options, recipients: ['x@y.test'] }, { ...options, schedule: true }, { ...options, sections: ['summary', 'summary'] }, { ...options, runId: id, batchId: id }])
            expect(reportOptions.safeParse(x).success).toBe(false);
    });
    it('requires a stable actor/request identity and rejects artifact injection from browser', () => { expect(reportDecision.safeParse({ operation: 'prepare', id, propertyId: id, expectedActorId: id, options }).success).toBe(true); expect(reportDecision.safeParse({ operation: 'resume', id, propertyId: id, expectedActorId: id, artifact: 'malicious' }).success).toBe(false); });
});
