'use client'
import {useCallback,useEffect,useState} from 'react'
import Link from 'next/link'
import {sessionMessage,sessionDeviceLabel,type SessionSource,type SessionReceipt} from '@/utils/account-sessions/contracts'
import {sessionFetch,sessionUrl,pendingSession,postSession,recoverSession,type PendingSession} from '@/utils/account-sessions/client'
const button='rounded-lg border border-border px-3 py-2 text-sm hover:bg-muted disabled:opacity-50'
const date=(v:string|null)=>v?new Date(v).toLocaleString():'Not supplied'
export function AccountSessions({actorId}:{actorId:string}){
 const [source,setSource]=useState<SessionSource|null>(null),[pending,setPending]=useState<PendingSession|null>(null),[receipt,setReceipt]=useState<SessionReceipt|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<'local'|'others'|null>(null),[history,setHistory]=useState<SessionReceipt[]>([]),[historyMeta,setHistoryMeta]=useState<{total:number;hash:string}|null>(null)
 const load=useCallback(async()=>{setSource(null);setReview(null);const r:SessionSource=await sessionFetch(sessionUrl());if(r.actorId!==actorId)throw new Error('Your account changed. Sign in again before reviewing sessions.');setSource(r);setPending(pendingSession(actorId))},[actorId])
 useEffect(()=>{let active=true;sessionFetch(sessionUrl()).then((r:SessionSource)=>{if(active){if(r.actorId!==actorId)throw new Error('Your account changed. Reload this page.');setSource(r);setPending(pendingSession(actorId))}}).catch(e=>{if(active){setError(e.message);setPending(pendingSession(actorId))}});return()=>{active=false}},[actorId])
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Session controls are unavailable.');if(e instanceof Error&&'status'in e&&[401,403].includes(Number(e.status)))setSource(null)}finally{setPending(pendingSession(actorId));setBusy(false)}}
 async function act(){if(!source||!review)return;const r=await postSession(actorId,review,source.sourceHash,crypto.randomUUID());setReceipt(r);setReview(null);setHistoryMeta(null);if(r.scope==='local'&&r.status==='acknowledged'){window.location.assign('/auth/login?redirect=%2Faccount%2Fsecurity');return}await load()}
 async function recover(operation:'check'|'cancel_unused',id=pending?.id){if(!id)return;const r=await recoverSession(actorId,id,operation);setReceipt(r);setHistoryMeta(null);await load()}
 async function historyPage(more=false){const r=await sessionFetch(sessionUrl({kind:'history',offset:more?history.length:0,expectedHash:more?historyMeta?.hash:undefined}));if(r.actorId!==actorId)throw new Error('Your account changed. Reload this page.');setHistory(more?[...history,...r.items]:r.items);setHistoryMeta({total:r.total,hash:r.pageHash})}
 const others=source?.sessions.filter(s=>!s.current).length||0
 return <section aria-label="Private account sessions" className="space-y-4 rounded-xl border border-border bg-card p-5 text-card-foreground">
 <div><h2 className="text-lg font-semibold">Your sessions</h2><p className="text-sm text-muted-foreground">Only you can see this list and its history. Leaving an organization does not remove access to your account security.</p></div>
 <p className="text-sm text-muted-foreground">Sign-out prevents future session refreshes. Existing access tokens can remain valid until they expire. A listed session is not proof a device is online.</p>
 {error&&<div role="alert" className="rounded-lg border border-destructive p-3 text-sm">{error}</div>}
 {receipt&&<div role="status" className="rounded-lg bg-muted p-3 text-sm">{sessionMessage(receipt)}{['claimed','uncertain'].includes(receipt.status)&&<Link href="/auth/login?redirect=%2Faccount%2Fsecurity&reauth=1" className="mt-2 block underline">Sign in again to review from a fresh session</Link>}</div>}
 <div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void run(load)}>Reload sessions</button><button className={button} disabled={busy} onClick={()=>void run(()=>historyPage())}>Session request history</button></div>
 {!source&&<Link className="block text-sm underline" href="/auth/login?redirect=%2Faccount%2Fsecurity&reauth=1">Sign in again to recover session history</Link>}
 {pending&&<div className="space-y-2 rounded-lg border border-border p-3"><p>A session request is unconfirmed. Check it without sending another sign-out.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void run(()=>recover('check'))}>Check saved session request</button><button className={button} disabled={busy} onClick={()=>void run(()=>recover('cancel_unused'))}>Cancel only if not started</button></div><p className="text-xs text-muted-foreground">Cancellation cannot undo a request that has already contacted the provider.</p></div>}
 {source&&<><p className="text-sm">{source.sessions.length} recorded {source.sessions.length===1?'session':'sessions'}</p><ul className="space-y-2">{source.sessions.map(s=><li key={s.id} className="rounded-lg border border-border p-3 text-sm"><p className="font-medium">{s.current?'This session':'Other session'}</p><p className="break-words text-muted-foreground">{sessionDeviceLabel(s.agent)}</p><p>Started {date(s.createdAt)}</p><p>Last refresh {date(s.lastSeenAt)}</p></li>)}</ul>
 {!source.canRevoke&&<p role="status" className="text-sm">Your account has a verified second factor. Complete second-factor verification before signing out other sessions. You can still sign out this session.</p>}
 <div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!!pending||!source.canRevoke||!others} onClick={()=>setReview('others')}>Review other-session sign-out</button><button className={button} disabled={busy||!!pending} onClick={()=>setReview('local')}>Review this-session sign-out</button></div>
 {review&&<div className="space-y-3 rounded-lg border border-border bg-muted p-4"><h3 className="font-medium">{review==='others'?'Sign out all other sessions?':'Sign out this session?'}</h3><p className="text-sm">{review==='others'?`You reviewed ${others} other sessions. The provider signs out all other sessions that exist when it processes this request, including any opened just afterward. This session stays signed in.`:'You will return to sign-in. Other sessions remain signed in. Your saved request can be recovered after you sign in again.'}</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void run(act)}>{review==='others'?'Confirm other-session sign-out':'Confirm this-session sign-out'}</button><button className={button} disabled={busy} onClick={()=>setReview(null)}>Keep sessions</button></div></div>}
 </>}
 {historyMeta&&<div className="space-y-2"><h3 className="font-medium">Your session requests</h3><p className="text-sm">Showing {history.length} of {historyMeta.total} session requests</p>{history.map(r=><button key={r.requestId} className={button+' block w-full text-left'} disabled={busy} onClick={()=>void run(async()=>{const d=await sessionFetch(sessionUrl({kind:'detail',requestId:r.requestId}));if(d.actorId!==actorId)throw new Error('Your account changed.');setReceipt(d)})}>{r.scope==='others'?'Other sessions':r.scope==='local'?'This session':'Unused request'} · {r.status} · {date(r.createdAt)}</button>)}{history.length<historyMeta.total&&<button className={button} disabled={busy} onClick={()=>void run(()=>historyPage(true))}>Load more session requests</button>}</div>}
 {receipt?.events&&<div aria-label="Saved session request details" className="space-y-2 rounded-lg border border-border p-3 text-sm"><h3 className="font-medium">Saved request evidence</h3><p>{receipt.reviewedCount} sessions in the original review</p>{receipt.events.map(e=><p key={e.id}>{e.kind} · {date(e.createdAt)}</p>)}{['claimed','uncertain','observed'].includes(receipt.status)&&<button className={button} disabled={busy} onClick={()=>void run(()=>recover('check',receipt.requestId))}>Check current session evidence</button>}</div>}
 </section>
}
