'use client'
import {useCallback,useEffect,useState} from 'react'
import Link from 'next/link'
import {credentialMessage,type CredentialSource,type CredentialReceipt} from '@/utils/account-credentials/contracts'
import {credentialFetch,credentialUrl,pendingCredential,postCredential,recoverCredential} from '@/utils/account-credentials/client'
const button='rounded-lg border border-border px-3 py-2 text-sm hover:bg-muted disabled:opacity-50'
type Event={id:string;requestId:string|null;kind:string;createdAt:string}
export function AccountPassword({actorId,recovery=false}:{actorId:string;recovery?:boolean}){
 const[source,setSource]=useState<CredentialSource|null>(null),[pending,setPending]=useState<string|null>(null),[receipt,setReceipt]=useState<CredentialReceipt|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[history,setHistory]=useState<Event[]>([]),[meta,setMeta]=useState<{total:number;hash:string}|null>(null)
 const load=useCallback(async()=>{setSource(null);const r:CredentialSource=await credentialFetch(credentialUrl());if(r.actorId!==actorId)throw new Error('Your account changed. Sign in again before changing a password.');setSource(r);setPending(pendingCredential(actorId)||r.pendingRequestId)},[actorId])
 useEffect(()=>{let active=true;credentialFetch(credentialUrl()).then((r:CredentialSource)=>{if(active){if(r.actorId!==actorId)throw new Error('Your account changed. Reload this page.');setSource(r);setPending(pendingCredential(actorId)||r.pendingRequestId)}}).catch(e=>{if(active){setError(e.message);setPending(pendingCredential(actorId))}});return()=>{active=false}},[actorId])
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Password controls are unavailable.');if(e instanceof Error&&'status'in e&&[401,403].includes(Number(e.status)))setSource(null);setPending(previous=>pendingCredential(actorId)||previous)}finally{setBusy(false)}}
 async function change(){if(!source)return;if(password!==confirm){setError('Passwords do not match');return}const old=current,next=password;setCurrent('');setPassword('');setConfirm('');const r=await postCredential(actorId,source.sourceHash,old,next,recovery);setReceipt(r);setMeta(null);await load()}
 async function recover(operation:'check'|'cancel',id=pending){if(!id)return;const r=await recoverCredential(actorId,id,operation);setReceipt(r);setMeta(null);await load()}
 async function page(more=false){const r=await credentialFetch(credentialUrl({kind:'history',offset:more?history.length:0,expectedHash:more?meta?.hash:undefined}));if(r.actorId!==actorId)throw new Error('Your account changed.');setHistory(more?[...history,...r.items]:r.items);setMeta({total:r.total,hash:r.pageHash})}
 const allowed=!!source?.canChange&&(!recovery||!!source.canRecover)
 return<section aria-label="Recorded password changes" className="space-y-4 rounded-xl border border-border bg-card p-5 text-card-foreground"><div><h2 className="text-lg font-semibold">{recovery?'Reset password':'Change password'}</h2><p className="text-sm text-muted-foreground">{recovery?'Use your verified recovery session to set a new password. The recovery session expires after 15 minutes and permits one completed reset.':'Verify your current password before changing it.'} Passwords are never stored in console history.</p></div>
 {error&&<p role="alert" className="rounded-lg border border-destructive p-3 text-sm">{error}</p>}{receipt&&<p role="status" className="rounded-lg bg-muted p-3 text-sm">{credentialMessage(receipt)}</p>}
 <div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void run(load)}>Reload password controls</button><button className={button} disabled={busy} onClick={()=>void run(()=>page())}>Password request history</button></div>
 {!source&&<Link className="block text-sm underline" href="/auth/login?redirect=%2Faccount%2Fsecurity&reauth=1">Sign in again to recover password history</Link>}
 {pending&&<div className="space-y-2 rounded-lg border border-border p-3"><p>A password request needs review. Checking it does not submit a password again.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void run(()=>recover('check'))}>Check saved password request</button><button className={button} disabled={busy} onClick={()=>void run(()=>recover('cancel'))}>Cancel uncommitted password change</button></div><p className="text-xs text-muted-foreground">A completed change is recovered. An uncommitted change is cancelled and any late attempt is blocked.</p></div>}
 {source&&recovery&&!source.canRecover&&<p role="status">A fresh recovery link is required for another reset. <Link className="underline" href="/auth/forgot-password">Request a recovery link</Link></p>}
 {source&&!pending&&(!recovery||source.canRecover)&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void run(change)}}>{!source.canChange&&<p role="status">Verify your second factor before changing your password.</p>}
 {!recovery&&<label className="block text-sm font-medium">Current password<input aria-label="Current password" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} disabled={busy||!allowed} className="mt-1 w-full rounded-lg border border-border bg-background p-2"/></label>}
 <label className="block text-sm font-medium">New password<input aria-label="New password" type="password" autoComplete="new-password" minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy||!allowed} className="mt-1 w-full rounded-lg border border-border bg-background p-2"/></label>
 <label className="block text-sm font-medium">Confirm new password<input aria-label="Confirm new password" type="password" autoComplete="new-password" minLength={8} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={busy||!allowed} className="mt-1 w-full rounded-lg border border-border bg-background p-2"/></label>
 <p className="text-xs text-muted-foreground">Use at least eight characters. Other sessions may be signed out by the authentication service after a password change.</p><button className={button} type="submit" disabled={busy||!allowed||(!recovery&&!current)||password.length<8||!confirm}>{busy?'Updating…':'Update Password'}</button></form>}
 {meta&&<div className="space-y-2"><h3 className="font-medium">Your password history</h3><p className="text-sm">Showing {history.length} of {meta.total} password events</p>{history.map(e=>e.requestId?<button key={e.id} className={button+' block w-full text-left'} disabled={busy} onClick={()=>void run(async()=>{const r=await credentialFetch(credentialUrl({kind:'detail',requestId:e.requestId!}));if(r.actorId!==actorId)throw new Error('Your account changed.');setReceipt(r)})}>{e.kind.replaceAll('_',' ')} · {new Date(e.createdAt).toLocaleString()}</button>:<p key={e.id} className="text-sm">Authentication service updated the credential record · {new Date(e.createdAt).toLocaleString()}. No console request was linked.</p>)}{history.length<meta.total&&<button className={button} disabled={busy} onClick={()=>void run(()=>page(true))}>Load more password events</button>}</div>}
 {receipt?.events&&<div aria-label="Saved password request details" className="space-y-2 rounded-lg border border-border p-3 text-sm">{receipt.events.map(e=><p key={e.id}>{e.kind.replaceAll('_',' ')} · {new Date(e.createdAt).toLocaleString()}</p>)}{['verifying','changing','uncertain'].includes(receipt.status)&&<button className={button} disabled={busy} onClick={()=>void run(()=>recover('cancel',receipt.requestId))}>Cancel this uncommitted request</button>}</div>}
 <Link className="block text-sm underline" href="/account/security">Review your account sessions</Link>
 </section>
}
