'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import Image from 'next/image'
import Link from 'next/link'
import {savedEditorialRequest} from '@/utils/forgestudio/client'
import type {LibraryAsset} from '@/utils/forgestudio/asset-library'
import {getAssetUsability} from '@/utils/siteforge/assets/curation'
import {AssetGeneratorModal} from './AssetGeneratorModal'
import {AssetUploadForm} from './AssetUploadForm'
import {AssetUploadRequests} from './AssetUploadRequests'
import {MediaRequests} from './MediaRequests'
import {AssetDetails} from './AssetDetails'
type Props={propertyId:string;onSelectAsset?:(asset:LibraryAsset)=>void;selectionMode?:boolean;filterType?:'image'|'video'|'all'}
export function AssetGallery({propertyId,onSelectAsset,selectionMode=false,filterType='all'}:Props){
 const [assets,setAssets]=useState<LibraryAsset[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[type,setType]=useState(filterType),[favorites,setFavorites]=useState(false),[archived,setArchived]=useState(false),[aiOnly,setAiOnly]=useState(false),[searchDraft,setSearchDraft]=useState(''),[search,setSearch]=useState(''),[folderDraft,setFolderDraft]=useState(''),[folder,setFolder]=useState(''),[uploading,setUploading]=useState(false),[generating,setGenerating]=useState(false),[selected,setSelected]=useState<LibraryAsset|null>(null),[busy,setBusy]=useState(''),[requestRefresh,setRequestRefresh]=useState(0)
 const controller=useRef<AbortController|null>(null)
 const load=useCallback(async(after?:string)=>{controller.current?.abort();const current=new AbortController();controller.current=current;setLoading(true);setError('');try{
  const params=new URLSearchParams({propertyId,assetType:type,...(favorites?{favorites:'true'}:{}),...(archived?{archived:'true'}:{}),...(aiOnly?{aiGenerated:'true'}:{}),...(selectionMode?{usable:'true'}:{}),...(search?{search}:{}),...(folder?{folder}:{}),...(after?{cursor:after}:{})})
  const response=await fetch('/api/forgestudio/assets?'+params,{signal:current.signal}),data=await response.json();if(!response.ok)throw new Error(data.error||'Asset library unavailable');if(current.signal.aborted)return
  setAssets(old=>after?[...old,...data.assets.filter((a:LibraryAsset)=>!old.some(o=>o.id===a.id))]:data.assets);setCursor(data.nextCursor)
 }catch(error){if(!current.signal.aborted)setError(error instanceof Error?error.message:'Asset library unavailable')}finally{if(!current.signal.aborted)setLoading(false)}},[propertyId,type,favorites,archived,aiOnly,selectionMode,search,folder])
 useEffect(()=>{void load();return()=>controller.current?.abort()},[load])
 const saved=(asset:LibraryAsset,message:string)=>{setNotice(message);setUploading(false);setSelected(asset);setRequestRefresh(n=>n+1);void load()}
 async function reloadSelected(){if(!selected)return;const response=await fetch(`/api/forgestudio/assets?mode=asset&propertyId=${propertyId}&assetId=${selected.id}`),data=await response.json();if(!response.ok)throw new Error(data.error||'Saved asset unavailable');setSelected(data.asset)}
 async function favorite(asset:LibraryAsset){setBusy(asset.id);setError('');try{const request=await savedEditorialRequest('asset-'+asset.id,{propertyId,assetId:asset.id,revision:asset.governance_revision,action:'save',patch:{is_favorite:!asset.is_favorite}}),response=await fetch('/api/forgestudio/assets',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(request.body)}),data=await response.json();if(!response.ok)throw new Error(data.error||'Favorite change could not be confirmed');request.acknowledge();await load()}catch(error){setError(error instanceof Error?error.message:'Favorite change could not be confirmed')}finally{setBusy('')}}
 return <div className="space-y-4" aria-label="Asset library">
  <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{selectionMode?'Choose a library asset':'Asset library'}</h2><div className="flex flex-wrap gap-2"><button className="rounded-lg border px-3 py-2 text-sm" disabled={loading} onClick={()=>void load()}>Reload library</button>{!selectionMode&&<><button className="rounded-lg border px-3 py-2 text-sm" onClick={()=>setUploading(v=>!v)}>Upload asset</button><button className="rounded-lg border px-3 py-2 text-sm" onClick={()=>setGenerating(true)}>Generate media</button></>}</div></div>
  {notice&&!selectionMode&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}
  {uploading&&!selectionMode&&<div className="rounded-xl border p-4"><AssetUploadForm propertyId={propertyId} onSaved={saved} onRequestChanged={()=>setRequestRefresh(n=>n+1)}/></div>}
  <form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();setSearch(searchDraft.trim());setFolder(folderDraft.trim())}}><input aria-label="Search asset names" placeholder="Search names" value={searchDraft} onChange={e=>setSearchDraft(e.target.value)} className="min-w-0 flex-1 rounded-lg border bg-transparent px-3 py-2 text-sm"/><input aria-label="Filter by folder" placeholder="Folder" value={folderDraft} onChange={e=>setFolderDraft(e.target.value)} className="w-40 max-w-full rounded-lg border bg-transparent px-3 py-2 text-sm"/><button className="rounded-lg border px-3 py-2 text-sm">Search library</button></form>
  <div className="flex flex-wrap items-center gap-4 text-sm"><label>Media type<select aria-label="Media type" className="ml-2 rounded border bg-transparent p-2" value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">All media</option><option value="image">Images</option><option value="video">Videos</option></select></label><label className="flex items-center gap-2"><input type="checkbox" checked={favorites} onChange={e=>setFavorites(e.target.checked)}/>Favorites</label><label className="flex items-center gap-2"><input type="checkbox" checked={aiOnly} onChange={e=>setAiOnly(e.target.checked)}/>AI generated</label>{!selectionMode&&<label className="flex items-center gap-2"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Archived assets</label>}</div>
  {selectionMode&&<p className="text-xs text-slate-500">Only approved, active assets appear. Rights and expiry information remains advisory.</p>}
  {error&&<p role="alert" className="rounded-lg border border-red-300 p-3 text-sm text-red-700">{error}</p>}{loading&&<p className="text-sm">Loading library…</p>}
  {!loading&&!error&&assets.length===0&&<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500 dark:bg-slate-900">No assets match these filters.</p>}
  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{assets.map(asset=>{const usable=getAssetUsability(asset),pickable=usable.usable&&['image','video','gif'].includes(asset.asset_type)&&!asset.archived_at,source=asset.thumbnail_url||asset.file_url;return <article key={asset.id} aria-label={asset.name} className="overflow-hidden rounded-xl border bg-white dark:bg-slate-900">
   {['image','gif'].includes(asset.asset_type)&&/^https?:\/\//.test(source)?<Image unoptimized src={source} width={400} height={220} alt={asset.alt_text||asset.name} className="h-44 w-full object-cover"/>:asset.asset_type==='video'&&/^https?:\/\//.test(asset.file_url)?<video src={asset.file_url} controls preload="none" className="h-44 w-full bg-slate-100"/>:<div className="flex h-32 items-center justify-center bg-slate-100 text-sm">{asset.asset_type}</div>}
   <div className="space-y-2 p-3"><div className="flex items-start justify-between gap-2"><h3 className="break-words font-medium">{asset.name}</h3>{!selectionMode&&<button aria-pressed={asset.is_favorite === true} aria-label={`${asset.is_favorite?'Remove favorite':'Favorite'} ${asset.name}`} disabled={!!busy||loading||!!error} onClick={()=>void favorite(asset)} className="shrink-0 rounded border px-2 py-1">{asset.is_favorite?'★':'☆'}</button>}</div><p className="text-xs text-slate-500">{asset.archived_at?'Archived':asset.approval_status} · rights {asset.rights_status}{asset.folder?` · ${asset.folder}`:''}</p>{asset.description&&<p className="line-clamp-2 text-sm text-slate-600">{asset.description}</p>}{usable.advisories.length>0&&<p className="text-xs text-amber-800">{usable.advisories.map(a=>a.replaceAll('_',' ')).join(' · ')} (advisory)</p>}
    {selectionMode?<button className="rounded-lg bg-violet-600 px-3 py-2 text-sm text-white disabled:opacity-50" disabled={!pickable||loading||!!error} onClick={()=>onSelectAsset?.(asset)}>Select {asset.name}</button>:<div className="flex flex-wrap gap-2"><button className="rounded-lg border px-3 py-2 text-sm" aria-label={`Review asset ${asset.name}`} onClick={()=>setSelected(asset)}>Review asset</button>{pickable&&<Link className="rounded-lg border px-3 py-2 text-sm" href={`/dashboard/forgestudio?tab=campaigns&assetId=${asset.id}`}>Use in campaign brief</Link>}</div>}
   </div></article>})}</div>
  {cursor&&<button className="rounded-lg border px-4 py-2 text-sm" disabled={loading||!!error} onClick={()=>void load(cursor)}>Load more assets</button>}
  {!selectionMode&&<AssetUploadRequests propertyId={propertyId} refreshKey={requestRefresh} onSaved={saved}/>}
  {!selectionMode&&<MediaRequests propertyId={propertyId} refreshKey={requestRefresh} onSaved={()=>void load()}/>}
  {!selectionMode&&selected&&<AssetDetails key={`${selected.id}:${selected.governance_revision}`} asset={selected} propertyId={propertyId} onClose={()=>setSelected(null)} onReload={()=>reloadSelected()} onSaved={saved} onRequestChanged={()=>setRequestRefresh(n=>n+1)}/>}
  {generating&&<AssetGeneratorModal propertyId={propertyId} onClose={()=>setGenerating(false)} onGenerated={()=>{setGenerating(false);setRequestRefresh(n=>n+1);setNotice('Media request saved. Follow its progress in saved media requests.');void load()}}/>}
 </div>
}
