'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {savedEditorialRequest} from '@/utils/forgestudio/client'
import type {LibraryAsset} from '@/utils/forgestudio/asset-library'
type SavedUpload={id:string;createdAt:string;name:string;size:number;replacesAssetId:string|null}
export function AssetUploadRequests({propertyId,refreshKey,onSaved}:{propertyId:string;refreshKey:number;onSaved:(asset:LibraryAsset,message:string)=>void}){
 const [rows,setRows]=useState<SavedUpload[]>([]),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(''),[reason,setReason]=useState<Record<string,string>>({})
 const controller=useRef<AbortController|null>(null)
 const load=useCallback(async(after?:string)=>{controller.current?.abort();const current=new AbortController();controller.current=current;setLoading(true);setError('');try{const params=new URLSearchParams({propertyId,mode:'uploads',...(after?{cursor:after}:{})}),response=await fetch('/api/forgestudio/assets?'+params,{signal:current.signal}),data=await response.json();if(!response.ok)throw new Error(data.error||'Saved uploads unavailable');if(current.signal.aborted)return;setRows(old=>after?[...old,...data.uploads]:data.uploads);setCursor(data.nextCursor)}catch(error){if(!current.signal.aborted)setError(error instanceof Error?error.message:'Saved uploads unavailable')}finally{if(!current.signal.aborted)setLoading(false)}},[propertyId])
 useEffect(()=>{void load();return()=>controller.current?.abort()},[load,refreshKey])
 async function recover(row:SavedUpload,action:'recover'|'keep_separate'){setBusy(row.id);setError('');try{
  const request=await savedEditorialRequest('asset-recovery-'+row.id,{propertyId,uploadId:row.id,action,reason:(reason[row.id]||'').trim()}),response=await fetch('/api/forgestudio/assets',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(request.body)}),data=await response.json();if(!response.ok)throw new Error(data.error||'Upload recovery could not be confirmed');request.acknowledge();onSaved(data.asset,'Recovered the stored file without uploading it again.');await load()
 }catch(error){setError(error instanceof Error?error.message:'Upload recovery could not be confirmed')}finally{setBusy('')}}
 return <section aria-label="Saved asset uploads" className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Saved uploads</h3><button disabled={loading||!!busy} className="rounded border px-3 py-2 text-sm" onClick={()=>void load()}>Reload saved uploads</button></div>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{loading&&<p className="text-sm">Loading upload records…</p>}{!loading&&!error&&rows.length===0&&<p className="text-sm text-slate-500">No unconfirmed uploads.</p>}{rows.map(row=><div key={row.id} className="space-y-2 rounded-lg bg-slate-50 p-3 dark:bg-slate-900"><p className="text-sm font-medium">{row.name} · {(row.size/1024/1024).toFixed(1)} MB</p><p className="text-xs text-slate-500">Started {new Date(row.createdAt).toLocaleString()}. The library save is not yet confirmed. Recovery checks the stored file before saving it.</p><label className="block text-sm">Reason for recovering this upload<input className="mt-1 block w-full rounded border bg-transparent p-2" value={reason[row.id]||''} maxLength={2000} onChange={e=>setReason(old=>({...old,[row.id]:e.target.value}))}/></label><div className="flex flex-wrap gap-2"><button disabled={!!busy||(reason[row.id]||'').trim().length<3} className="rounded border px-3 py-2 text-sm disabled:opacity-50" onClick={()=>void recover(row,'recover')}>Recover stored file</button>{row.replacesAssetId&&<button disabled={!!busy||(reason[row.id]||'').trim().length<3} className="rounded border px-3 py-2 text-sm disabled:opacity-50" onClick={()=>void recover(row,'keep_separate')}>Keep as a separate asset</button>}</div></div>)}{cursor&&<button disabled={loading||!!busy} className="rounded border px-3 py-2 text-sm" onClick={()=>void load(cursor)}>Load more uploads</button>}</section>
}
