'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {savedEditorialRequest} from '@/utils/forgestudio/client'
const fields=[['impressions','Impressions'],['reach','Reach'],['clicks','Clicks'],['reactions','Reactions'],['comments','Comments'],['shares','Shares'],['saves','Saves'],['video_views','Video views'],['video_completions','Video completions']] as const
type Metrics=Record<string,number|null>
type Publication={id:string;platform:string;remotePostUrl:string|null;publishedAt:string;revisionId:string;title:string;legacy:boolean}
type Measurement={id:string;origin:string;state:string;metrics:Metrics|null;observedAt:string|null;definition:string|null;source:string|null;reason:string|null;errorCode:string|null;reviewStatus:string;reviewVersion:number;remotePostId:string;revisionId:string;createdAt:string}
type Attribution={id:string;event_type:string;occurred_at:string;created_at:string;evidence_kind:string;source_system:string|null;event_state:string;decision_version:number}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50'
async function read(url:string,signal?:AbortSignal){const response=await fetch(url,{signal}),data=await response.json();if(!response.ok)throw new Error(data.error||'Saved results unavailable');return data}
async function command(action:string,input:Record<string,unknown>,method:'POST'|'PATCH'){
 const saved=await savedEditorialRequest(action,input),response=await fetch('/api/forgestudio/outcomes',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(saved.body)}),data=await response.json();if(!response.ok)throw new Error(data.error||'The outcome decision could not be confirmed. Retry the same decision or reload.');saved.acknowledge();return data
}
export function PublicationResults({propertyId}:{propertyId:string}){
 const [rows,setRows]=useState<Publication[]>([]),[cursor,setCursor]=useState<string|null>(null),[selected,setSelected]=useState<Publication|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[paused,setPaused]=useState(false)
 const controller=useRef<AbortController|null>(null)
 const load=useCallback(async(after?:string)=>{controller.current?.abort();const current=new AbortController();controller.current=current;setLoading(true);setError('');try{const data=await read('/api/forgestudio/outcomes?'+new URLSearchParams({propertyId,...(after?{cursor:after}:{})}),current.signal);if(current.signal.aborted)return;setRows(old=>after?[...old,...data.publications.filter((r:Publication)=>!old.some(o=>o.id===r.id))]:data.publications);setCursor(data.nextCursor);setPaused(data.paused)}catch(e){if(!current.signal.aborted)setError(e instanceof Error?e.message:'Saved results unavailable')}finally{if(!current.signal.aborted)setLoading(false)}},[propertyId])
 useEffect(()=>{void load();return()=>controller.current?.abort()},[load])
 return <section aria-label="Campaign results" className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Campaign results</h2><button className={button} disabled={loading} onClick={()=>void load()}>Reload published posts</button></div><p className="text-sm text-slate-600">Review the evidence behind each published post. Reported outcomes and tracked redirects show associations; they do not establish that a campaign caused a lead or lease.</p>{paused&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Provider checks are paused. You can save check requests, report sourced measurements and review existing evidence.</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{loading&&<p className="text-sm">Loading published posts…</p>}{!loading&&!error&&!rows.length&&<p className="rounded-lg border p-4 text-sm">Results appear after a post has a confirmed publication record.</p>}
 <div className="grid gap-2 sm:grid-cols-2">{rows.map(row=><button key={row.id} aria-pressed={selected?.id===row.id} aria-label={`Review results for ${row.title}`} className={`rounded-lg border p-3 text-left ${selected?.id===row.id?'border-violet-500 bg-violet-50 dark:bg-violet-950':''}`} onClick={()=>setSelected(row)}><span className="line-clamp-2 block font-medium">{row.title}</span><span className="mt-1 block text-xs text-slate-500">{row.platform} · {new Date(row.publishedAt).toLocaleString()}{row.legacy?' · earlier publication evidence':''}</span></button>)}</div>{cursor&&<button className={button} disabled={loading||!!error} onClick={()=>void load(cursor)}>Load more published posts</button>}
 {selected&&<ResultDetail key={selected.id} publication={selected} propertyId={propertyId} paused={paused}/>}
 </section>
}
function ResultDetail({publication,propertyId,paused}:{publication:Publication;propertyId:string;paused:boolean}){
 const [measurements,setMeasurements]=useState<Measurement[]>([]),[events,setEvents]=useState<Attribution[]>([]),[metricCursor,setMetricCursor]=useState<string|null>(null),[eventCursor,setEventCursor]=useState<string|null>(null),[legacy,setLegacy]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reasons,setReasons]=useState<Record<string,string>>({}),[report,setReport]=useState(false)
 const controller=useRef<AbortController|null>(null)
 const load=useCallback(async(mode?:'measurements'|'attribution',cursor?:string)=>{controller.current?.abort();const current=new AbortController();controller.current=current;setLoading(true);setError('');try{
  const modes=mode?[mode]:['measurements','attribution'] as const
  const results=await Promise.all(modes.map(async m=>({mode:m,data:await read('/api/forgestudio/outcomes?'+new URLSearchParams({propertyId,publicationId:publication.id,mode:m,...(cursor?{cursor}:{})}),current.signal)})))
  if(current.signal.aborted)return
  for(const result of results)if(result.mode==='measurements'){setMeasurements(old=>cursor?[...old,...result.data.measurements.filter((r:Measurement)=>!old.some(o=>o.id===r.id))]:result.data.measurements);setMetricCursor(result.data.nextCursor);setLegacy(result.data.legacyCount)}else{setEvents(old=>cursor?[...old,...result.data.events.filter((r:Attribution)=>!old.some(o=>o.id===r.id))]:result.data.events);setEventCursor(result.data.nextCursor)}
 }catch(e){if(!current.signal.aborted)setError(e instanceof Error?e.message:'Outcome evidence unavailable')}finally{if(!current.signal.aborted)setLoading(false)}},[propertyId,publication.id])
 useEffect(()=>{void load();return()=>controller.current?.abort()},[load])
 async function requestMetrics(){setBusy('request');setError('');try{await command('metrics-request',{propertyId,publicationId:publication.id,action:'request'},'POST');setNotice(paused?'Provider check request saved. It will remain queued while checks are paused.':'Provider check request saved. Reload evidence after the scheduled check.');await load('measurements')}catch(e){setError(e instanceof Error?e.message:'Check request could not be confirmed')}finally{setBusy('')}}
 async function reviewMetric(row:Measurement,decision:'included'|'excluded'){setBusy(row.id);setError('');try{const result=await command('metrics-review',{propertyId,action:'review_metrics',measurementId:row.id,decision,expectedVersion:row.reviewVersion,reason:(reasons[row.id]||'').trim()},'PATCH');setMeasurements(old=>old.map(r=>r.id===row.id?{...r,reviewStatus:result.decision,reviewVersion:result.reviewVersion}:r));setNotice('Measurement review saved. This does not establish causal impact or enable training.')}catch(e){setError(e instanceof Error?e.message:'Review could not be confirmed')}finally{setBusy('')}}
 async function reviewEvent(row:Attribution,decision:'active'|'excluded'){setBusy(row.id);setError('');try{const result=await command('attribution-review',{propertyId,action:'review_attribution',eventId:row.id,decision,expectedVersion:row.decision_version,reason:(reasons[row.id]||'').trim()},'PATCH');setEvents(old=>old.map(r=>r.id===row.id?{...r,event_state:result.decision,decision_version:result.decisionVersion}:r));setNotice('Attribution evidence review saved. The event retains its original source and trust level.')}catch(e){setError(e instanceof Error?e.message:'Review could not be confirmed')}finally{setBusy('')}}
 const reason=(id:string,label:string)=><label className="block text-sm">Reason for evidence decision<input aria-label={`Reason for ${label}`} value={reasons[id]||''} maxLength={2000} onChange={e=>setReasons(old=>({...old,[id]:e.target.value}))} className="mt-1 w-full rounded border bg-transparent p-2"/></label>
 return <section aria-label="Publication result evidence" className="space-y-4 rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{publication.title}</h3><p className="text-xs text-slate-500">Published {new Date(publication.publishedAt).toLocaleString()} · {publication.platform}</p></div>{publication.remotePostUrl?.startsWith('https://')&&<a href={publication.remotePostUrl} target="_blank" rel="noreferrer" className="text-sm text-violet-700 underline">Open published post</a>}</div><div className="flex flex-wrap gap-2"><button className={button} disabled={loading||!!busy} onClick={()=>void load()}>Reload result evidence</button><button className={button} disabled={loading||!!busy} onClick={()=>void requestMetrics()}>Request provider check</button><button className={button} onClick={()=>setReport(v=>!v)}>Report sourced metrics</button></div>{notice&&<p role="status" className="text-sm text-green-800">{notice}</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{loading&&<p className="text-sm">Loading outcome evidence…</p>}
 {report&&<MetricReport propertyId={propertyId} publicationId={publication.id} onSaved={()=>{setReport(false);setNotice('Sourced report saved for evidence review.');void load('measurements')}}/>}
 <div className="space-y-3"><h4 className="font-semibold">Measurement history</h4><p className="text-xs text-slate-500">Each card is a separate snapshot. Missing fields stay unknown; snapshots are never added together. Included evidence remains an observation, with training disabled.</p>{legacy>0&&<p className="text-sm text-amber-800">{legacy} earlier daily measurement records are unqualified and excluded from this view.</p>}{!loading&&!error&&!measurements.length&&<p className="text-sm text-slate-500">No measurement evidence has been saved.</p>}
 {measurements.map(row=><article key={row.id} aria-label={`Measurement ${row.id}`} className="space-y-3 rounded-lg border p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{row.origin==='operator_report'?'Operator-reported totals':'Provider measurement request'}</p><span className="text-xs text-slate-500">{row.state} · {row.reviewStatus}</span></div>{row.observedAt&&<p className="text-xs">Observed {new Date(row.observedAt).toLocaleString()}</p>}{row.state==='queued'&&<p className="text-sm">Waiting for a provider check{paused?' while checks are paused':''}.</p>}{row.state==='reading'&&<p className="text-sm">Reading the saved post’s metrics. Reload to check the result.</p>}{['failed','unsupported','held'].includes(row.state)&&<p className="text-sm text-amber-800">{row.state==='unsupported'?'This channel does not support a qualified metrics read.':row.state==='failed'?'The provider check failed; no replacement values were invented.':'The saved destination or access needs review before these results can be used.'} Reload connections and request a fresh check when resolved.</p>}
 {row.metrics&&<><p className="text-xs text-slate-500">{row.origin==='operator_report'?'Reported cumulative totals since publication.':'Provider-reported snapshot. Its reporting period has not been independently qualified.'}</p><dl className="grid grid-cols-2 gap-2 sm:grid-cols-3">{fields.map(([key,label])=><div key={key}><dt className="text-xs text-slate-500">{label}</dt><dd className="text-sm font-medium">{row.metrics?.[key]===null||row.metrics?.[key]===undefined?'Unavailable':row.metrics[key]!.toLocaleString()}</dd></div>)}</dl></>}{row.source&&<p className="break-words text-sm">Reported source: {row.source}</p>}{row.reason&&<p className="break-words text-sm">Report note: {row.reason}</p>}
 {row.state==='completed'&&<>{reason(row.id,'measurement '+row.id)}<div className="flex flex-wrap gap-2"><button className={button} disabled={loading||!!busy||(reasons[row.id]||'').trim().length<3} onClick={()=>void reviewMetric(row,'included')}>Include this evidence</button><button className={button} disabled={loading||!!busy||(reasons[row.id]||'').trim().length<3} onClick={()=>void reviewMetric(row,'excluded')}>Exclude this evidence</button></div></>}
 </article>)}{metricCursor&&<button className={button} disabled={loading||!!busy||!!error} onClick={()=>void load('measurements',metricCursor)}>Load older measurements</button>}</div>
 <div className="space-y-3"><h4 className="font-semibold">Attributed reports and redirects</h4><p className="text-xs text-slate-500">Business events are source reports within 30 days of publication. Redirect observations do not prove a landing-page view. Neither establishes incremental campaign impact.</p>{!loading&&!error&&!events.length&&<p className="text-sm text-slate-500">No attributed observations have been saved.</p>}{events.map(event=><article key={event.id} aria-label={`Attributed event ${event.id}`} className="space-y-2 rounded-lg border p-3"><p className="font-medium">{event.event_type==='landing_view'?'Tracked redirect':event.event_type.replaceAll('_',' ')+' reported'} · {event.event_state}</p><p className="text-xs text-slate-500">{new Date(event.occurred_at).toLocaleString()} · {event.source_system||'Earlier source'} · {event.evidence_kind==='legacy_unqualified'?'Legacy evidence — unqualified':event.evidence_kind==='system_report'?'Source report — not independently verified':'Redirect observation'}</p>{reason(event.id,'event '+event.id)}<button className={button} disabled={loading||!!busy||(reasons[event.id]||'').trim().length<3} onClick={()=>void reviewEvent(event,event.event_state==='excluded'?'active':'excluded')}>{event.event_state==='excluded'?'Restore reported evidence':'Exclude reported evidence'}</button></article>)}{eventCursor&&<button className={button} disabled={loading||!!busy||!!error} onClick={()=>void load('attribution',eventCursor)}>Load older attributed events</button>}</div>
 </section>
}
function MetricReport({propertyId,publicationId,onSaved}:{propertyId:string;publicationId:string;onSaved:()=>void}){
 const [counts,setCounts]=useState<Record<string,string>>({}),[source,setSource]=useState(''),[reason,setReason]=useState(''),[observed,setObserved]=useState(()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16)}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(){setBusy(true);setError('');try{const metrics=Object.fromEntries(fields.map(([key])=>[key,counts[key]?.trim()?Number(counts[key]):null]));await command('metrics-report',{action:'report',propertyId,publicationId,metrics,observedAt:new Date(observed).toISOString(),source:source.trim(),reason:reason.trim()},'POST');onSaved()}catch(e){setError(e instanceof Error?e.message:'Report could not be confirmed')}finally{setBusy(false)}}
 return <form aria-label="Report campaign metrics" onSubmit={e=>{e.preventDefault();void save()}} className="space-y-3 rounded-lg bg-slate-50 p-4 dark:bg-slate-950"><h4 className="font-medium">Report cumulative totals since publication</h4><p className="text-xs text-slate-500">Use a named provider report or source. Leave unavailable counts blank; enter zero only when the source reports zero. This is operator-reported evidence.</p><label className="block text-sm">Observed at (your local time)<input type="datetime-local" required value={observed} onChange={e=>setObserved(e.target.value)} className="mt-1 block max-w-full rounded border bg-transparent p-2"/></label><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{fields.map(([key,label])=><label key={key} className="text-sm">{label}<input aria-label={`Reported ${label.toLowerCase()}`} type="number" min={0} step={1} max={1000000000000} value={counts[key]||''} onChange={e=>setCounts(old=>({...old,[key]:e.target.value}))} className="mt-1 w-full min-w-0 rounded border bg-transparent p-2"/></label>)}</div><label className="block text-sm">Source report or citation<input required minLength={3} maxLength={2000} value={source} onChange={e=>setSource(e.target.value)} className="mt-1 w-full rounded border bg-transparent p-2"/></label><label className="block text-sm">Reason or correction note<textarea required minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded border bg-transparent p-2"/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button className={button} disabled={busy||!Object.values(counts).some(v=>v.trim())}>Save sourced report</button></form>
}
