'use client'
import {useEffect,useState} from 'react'
import {savedEditorialRequest} from '@/utils/forgestudio/client'
interface Brief {id:string;title:string;objective:string;source_facts:Array<{text:string;source?:string}>;constraints:{mustAvoid?:string[];mustInclude?:string[]};format_plan:Array<{platform:string;contentFormat:string;quantity:number}>;status:string}
export function SavedDraft({propertyId,briefId,onRequestChanged,onGenerated}:{propertyId:string;briefId:string;onRequestChanged:()=>void;onGenerated:(result:{packageId:string;revisionId:string})=>void}){
 const [brief,setBrief]=useState<Brief|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[reload,setReload]=useState(0)
 useEffect(()=>{const c=new AbortController();setLoading(true);setBrief(null);setError('');fetch(`/api/forgestudio/briefs/${briefId}?${new URLSearchParams({propertyId})}`,{signal:c.signal,cache:'no-store'}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'The saved draft could not be loaded.');if(!c.signal.aborted)setBrief(data.brief)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'The saved draft could not be loaded.')}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[propertyId,briefId,reload])
 const generate=async()=>{setBusy(true);setError('');try{const saved=await savedEditorialRequest('generate-'+briefId,{briefId}),response=await fetch(`/api/forgestudio/briefs/${briefId}/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(saved.body)}),data=await response.json();if(!response.ok||response.status===202)throw new Error(data.error||'Reload the saved generation request before trying again.');saved.acknowledge();onGenerated({packageId:data.result.packageId,revisionId:data.result.revisionId})}catch(e){setError(e instanceof Error?e.message:'The generation could not be confirmed.')}finally{setBusy(false);onRequestChanged()}}
 return <section aria-label="Saved ForgeStudio draft" className="space-y-3 rounded-xl border border-violet-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">Saved ForgeStudio draft</h3><button disabled={busy||loading} onClick={()=>setReload(v=>v+1)} className="rounded border px-3 py-2 text-sm">Reload saved draft</button></div>{loading&&<p role="status">Loading the exact saved draft…</p>}{error&&<p role="alert" className="rounded bg-amber-50 p-3 text-sm">{error}</p>}{brief&&<><h4 className="font-medium">{brief.title}</h4><p className="whitespace-pre-wrap text-sm">{brief.objective}</p><p className="text-sm">{brief.format_plan.map(f=>`${f.quantity} ${f.contentFormat} for ${f.platform}`).join(', ')}</p><details className="rounded border p-3"><summary>Saved context and constraints</summary><ul className="mt-2 list-disc space-y-2 pl-5 text-sm">{[...brief.source_facts.map(f=>f.text),...(brief.constraints.mustInclude??[]),...(brief.constraints.mustAvoid??[])].map(t=><li key={t}>{t}</li>)}</ul></details><p className="text-sm text-slate-600">Market signals guide topic, timing and format. Content claims need approved property sources. Generation uses this saved draft; its results still need review before publishing.</p><button disabled={busy||loading} onClick={()=>void generate()} className="rounded bg-violet-700 px-4 py-2 text-white disabled:opacity-50">{busy?'Saving generation request…':'Generate from saved draft'}</button></>}</section>
}
