'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {useSearchParams} from 'next/navigation'
import {socialJson,type SavedSocialConnection} from '@/utils/forgestudio/connections-client'
import {SocialAppSetup} from './SocialAppSetup'
const platforms=[{id:'instagram',name:'Instagram',config:'meta'},{id:'facebook',name:'Facebook',config:'meta'},{id:'linkedin',name:'LinkedIn',config:'linkedin'},{id:'tiktok',name:'TikTok',config:'tiktok'},{id:'x',name:'X',config:'x'}]
type Authorization={id:string;platform:string;state:string;version:number;createdAt:string;expiresAt:string;reason:string|null;accounts:Array<{accountId:string;accountName:string|null;accountUsername:string|null;scopes:string[];expiresAt:string|null;expiryKnown:boolean}>}
type Renewal={id:string;connection_id:string;connection_version:number;platform:string;state:string;reason:string|null;created_at:string;finished_at:string|null}
type RenewalPage={renewals:Renewal[];nextCursor:string|null}
type Decision={url:string;method:string;body:Record<string,unknown>}
type ConnectionPage={connections:SavedSocialConnection[];nextCursor:string|null;authorizationPaused:boolean;credentialStorageAvailable:boolean}
type AuthorizationPage={authorizations:Authorization[];nextCursor:string|null}
const stateLabels:Record<string,string>={pending:'Awaiting provider consent',exchanging:'Exchange started; result not yet confirmed',review_required:'Choose accounts to connect',completed:'Account review saved',cancelled:'Cancelled',failed:'Authorization failed',held:'New authorization required'}
const button='rounded-lg border px-3 py-2 text-sm disabled:opacity-50'
export function SocialConnections({propertyId}:{propertyId:string}){return <Connections key={propertyId} propertyId={propertyId}/>}
function Connections({propertyId}:{propertyId:string}){
 const query=useSearchParams(),[connections,setConnections]=useState<SavedSocialConnection[]>([]),[authorizations,setAuthorizations]=useState<Authorization[]>([]),[cursor,setCursor]=useState<string|null>(null),[authCursor,setAuthCursor]=useState<string|null>(null),[paused,setPaused]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState(''),[historyError,setHistoryError]=useState(''),[message,setMessage]=useState(''),[setup,setSetup]=useState<string|null>(null),[busy,setBusy]=useState(false),[pending,setPending]=useState<Decision|null>(null),[reason,setReason]=useState(''),[selected,setSelected]=useState<Record<string,string[]>>({})
 const [renewals,setRenewals]=useState<Renewal[]>([]),[renewalCursor,setRenewalCursor]=useState<string|null>(null),[renewalError,setRenewalError]=useState(''),[secureStorage,setSecureStorage]=useState(false)
 const mounted=useRef(true),controller=useRef<AbortController|null>(null),starts=useRef<Record<string,string>>({})
 const reload=useCallback(async()=>{
  controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);setError('');setHistoryError('');setRenewalError('')
  const results=await Promise.allSettled([socialJson<ConnectionPage>(`/api/forgestudio/social/connections?propertyId=${propertyId}`,{signal:c.signal}),socialJson<AuthorizationPage>(`/api/forgestudio/social/authorizations?propertyId=${propertyId}`,{signal:c.signal}),socialJson<RenewalPage>(`/api/forgestudio/social/renewal?propertyId=${propertyId}`,{signal:c.signal})]);if(c.signal.aborted)return
  const [accounts,requests,accessHistory]=results
  if(accounts.status==='fulfilled'){setConnections(accounts.value.connections);setCursor(accounts.value.nextCursor);setPaused(accounts.value.authorizationPaused);setSecureStorage(accounts.value.credentialStorageAvailable)}else{setConnections([]);setCursor(null);setPaused(true);setError(accounts.reason instanceof Error?accounts.reason.message:'Accounts could not be loaded.')}
  if(requests.status==='fulfilled'){setAuthorizations(requests.value.authorizations);setAuthCursor(requests.value.nextCursor)}else{setAuthorizations([]);setAuthCursor(null);setHistoryError(requests.reason instanceof Error?requests.reason.message:'Authorization history could not be loaded.')}
  if(accessHistory.status==='fulfilled'){setRenewals(accessHistory.value.renewals);setRenewalCursor(accessHistory.value.nextCursor)}else{setRenewals([]);setRenewalCursor(null);setRenewalError(accessHistory.reason instanceof Error?accessHistory.reason.message:'Renewal history could not be loaded.')}
  setLoading(false)
 },[propertyId])
 useEffect(()=>{mounted.current=true;void reload();return()=>{mounted.current=false;controller.current?.abort()}},[reload])
 useEffect(()=>{if(query.get('propertyId')&&query.get('propertyId')!==propertyId)return;const required=query.get('setup_required'),platform=platforms.find(p=>p.id===required);if(platform)setSetup(platform.config)},[query,propertyId])
 async function more(kind:'accounts'|'requests'|'renewals'){
  setBusy(true);setError('');try{if(kind==='accounts'){const data=await socialJson<ConnectionPage>(`/api/forgestudio/social/connections?propertyId=${propertyId}&cursor=${cursor}`);if(mounted.current){setConnections(prev=>[...prev,...data.connections.filter(row=>!prev.some(p=>p.id===row.id))]);setCursor(data.nextCursor)}}else if(kind==='renewals'){const data=await socialJson<RenewalPage>(`/api/forgestudio/social/renewal?propertyId=${propertyId}&cursor=${renewalCursor}`);if(mounted.current){setRenewals(prev=>[...prev,...data.renewals.filter(row=>!prev.some(p=>p.id===row.id))]);setRenewalCursor(data.nextCursor)}}else{const data=await socialJson<AuthorizationPage>(`/api/forgestudio/social/authorizations?propertyId=${propertyId}&cursor=${authCursor}`);if(mounted.current){setAuthorizations(prev=>[...prev,...data.authorizations.filter(row=>!prev.some(p=>p.id===row.id))]);setAuthCursor(data.nextCursor)}}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'More history could not be loaded.')}finally{if(mounted.current)setBusy(false)}
 }
 async function decide(decision:Decision){
  if(busy)return;setPending(decision);setBusy(true);setError('');setMessage('')
  try{const result=await socialJson<Record<string,unknown>>(decision.url,{method:decision.method,headers:{'Content-Type':'application/json'},body:JSON.stringify(decision.body)});if(mounted.current){setPending(null);setReason('');setSelected({});setMessage(decision.url.endsWith('/renewal')?(result.renewalState==='completed'||result.state==='completed'?'Renewed access saved. No publication was started.':result.renewalState==='held'||result.state==='held'?String(result.reason||'Renewal needs fresh authorization.'):'Renewal has started, but its result is not confirmed. Reload its saved history before continuing.'):decision.method==='DELETE'?`Account disconnected locally. ${result.cancelledCount??0} queued publications cancelled; ${result.inFlightCount??0} already-started publications still require review. Provider consent remains separate.`:decision.body.action==='apply'?'Selected accounts connected. No publication was started.':'Authorization cancelled. Provider consent remains separate.');await reload()}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Decision could not be confirmed. Retry the same decision.')}finally{if(mounted.current)setBusy(false)}
 }
 function authorize(platform:string){starts.current[platform]??=crypto.randomUUID();window.location.assign(`/api/forgestudio/social/connect/${platform}?propertyId=${propertyId}&requestId=${starts.current[platform]}`)}
 function review(a:Authorization,action:'apply'|'cancel'){void decide({url:'/api/forgestudio/social/authorizations',method:'POST',body:{propertyId,requestId:crypto.randomUUID(),authorizationId:a.id,expectedVersion:a.version,action,reason,...action==='apply'?{accountIds:selected[a.id]??[]}:{}}})}
 const locked=busy||loading||!!pending
 const callbackProperty=query.get('propertyId'),callbackStatus=query.get('status'),callbackError=query.get('error')
 return <div className="space-y-6">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Connected accounts</h2><p className="mt-1 max-w-3xl text-sm text-slate-500">Review the accounts for this property. Disconnecting preserves campaign history and stops queued publications that have not started.</p></div><button className={button} disabled={busy||loading} onClick={()=>{setPending(null);setSelected({});void reload()}}>Reload connections</button></div>
  {callbackProperty&&callbackProperty!==propertyId?<p role="status" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">The returned authorization belongs to another property. Select that property to review its saved request.</p>:(callbackError||callbackStatus)&&<p role="status" className="rounded-lg bg-slate-100 p-3 text-sm text-slate-700">{callbackError||stateLabels[callbackStatus??'']||'Review saved authorization history below.'}</p>}
  {paused&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">External authorization and delivery are paused in this environment. Saved accounts and decisions remain available for review.</p>}
  {!loading&&!secureStorage&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Secure credential storage must be configured on this server before authorizing or renewing accounts.</p>}
  {error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-700">{message}</p>}
  <div><label htmlFor="social-decision-reason" className="block text-sm font-medium">Reason for account decision</label><textarea id="social-decision-reason" value={reason} onChange={e=>setReason(e.target.value)} disabled={locked} maxLength={2000} placeholder="Why are you connecting, renewing, disconnecting or cancelling?" className="mt-1 w-full rounded-lg border bg-transparent p-3"/></div>
  {pending&&<div className="flex flex-wrap items-center gap-3 rounded-lg border border-amber-300 p-3 text-sm"><p>The last decision is unconfirmed. Retry it or reload the saved state.</p><button className={button} disabled={busy} onClick={()=>void decide(pending)}>Retry same account decision</button></div>}
  {loading?<p role="status">Loading saved accounts…</p>:<div className="grid gap-4 md:grid-cols-2">{platforms.map(platform=><section key={platform.id} aria-label={`${platform.name} accounts`} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{platform.name}</h3><button className={button} disabled={locked} onClick={()=>setSetup(platform.config)}>App setup</button></div>
   {connections.filter(c=>c.platform===platform.id).map(c=><article key={c.id} className="space-y-2 rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><p className="break-words font-medium">{c.account_name||c.account_username||c.account_id}</p><p className="break-all text-xs text-slate-500">Account: {c.account_id}</p><p className="text-sm">{c.disconnected_at?'Disconnected locally':c.renewal_state==='held'?'Access renewal unconfirmed — authorize again':c.renewal_state==='exchanging'?'Access renewal started — awaiting a saved result':!c.is_active?'Inactive':!c.permission_evidence?'Existing account — permission evidence needs fresh authorization':c.token_expires_at&&Date.parse(c.token_expires_at)<=Date.now()?(c.can_renew?'Saved access expired — renew access below':'Saved access expired — authorize again'):c.needs_refresh?'Authorization renewal recommended':'Active account with saved grant evidence'}</p>{c.token_expires_at&&<p className="text-xs text-slate-500">Saved access expiry: {new Date(c.token_expires_at).toLocaleString()}</p>}{c.can_renew&&<button className={button} disabled={locked||paused||!secureStorage||reason.trim().length<3} onClick={()=>void decide({url:'/api/forgestudio/social/renewal',method:'POST',body:{propertyId,requestId:crypto.randomUUID(),connectionId:c.id,expectedVersion:c.security_version,reason}})}>Renew saved access for {c.account_name||c.account_id}</button>}{!c.disconnected_at&&<button className={button} disabled={locked||reason.trim().length<3} onClick={()=>void decide({url:'/api/forgestudio/social/connections',method:'DELETE',body:{propertyId,requestId:crypto.randomUUID(),connectionId:c.id,expectedVersion:c.security_version,reason}})}>Disconnect {c.account_name||c.account_id}</button>}</article>)}
   {!connections.some(c=>c.platform===platform.id)&&<p className="text-sm text-slate-500">No accounts on this page.</p>}
   <button className={`${button} w-full`} disabled={locked||paused||!secureStorage} onClick={()=>authorize(platform.id)}>Authorize or renew {platform.name}</button>
  </section>)}</div>}
  {cursor&&<button className={button} disabled={locked} onClick={()=>void more('accounts')}>Load more accounts</button>}
  <section className="space-y-4"><div><h3 className="font-semibold">Authorization history</h3><p className="text-sm text-slate-500">Provider consent is saved for review first. Choose the exact accounts for this property. An interrupted exchange requires fresh consent; it is never automatically repeated.</p></div>
   {historyError&&<p role="alert" className="text-sm text-red-600">{historyError}</p>}
   {authorizations.map(a=><article key={a.id} aria-label={`${platforms.find(p=>p.id===a.platform)?.name??a.platform} authorization ${a.id}`} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium">{platforms.find(p=>p.id===a.platform)?.name??a.platform} — {stateLabels[a.state]||'Review needed'}</h4><span className="text-xs text-slate-500">{new Date(a.createdAt).toLocaleString()}</span></div>{a.state==='pending'&&<p className="text-xs text-slate-500">Consent link expires {new Date(a.expiresAt).toLocaleString()}.</p>}{a.reason&&<p className="text-sm text-slate-500">{a.reason.replaceAll('_',' ')}</p>}
    {a.state==='review_required'&&a.accounts.map(account=><label key={account.accountId} className="flex items-start gap-3 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><input type="checkbox" className="mt-1" disabled={locked||!account.expiryKnown} checked={(selected[a.id]??[]).includes(account.accountId)} onChange={e=>setSelected(prev=>({...prev,[a.id]:e.target.checked?[...prev[a.id]??[],account.accountId]:(prev[a.id]??[]).filter(id=>id!==account.accountId)}))}/><span className="min-w-0"><span className="block break-words font-medium">{account.accountName||account.accountUsername||account.accountId}</span><span className="block break-all text-xs">Account: {account.accountId}</span><span className="mt-1 block break-words text-xs text-slate-500">{account.scopes.length?`Granted: ${account.scopes.join(', ')}`:'Permission evidence missing. Start fresh authorization.'}</span><span className="block text-xs text-slate-500">{account.expiryKnown&&account.expiresAt?`Access expires ${new Date(account.expiresAt).toLocaleString()}`:'Expiry is unconfirmed. Start fresh authorization.'}</span></span></label>)}
    <div className="flex flex-wrap gap-3">{a.state==='review_required'&&<button className={button} disabled={locked||reason.trim().length<3||!selected[a.id]?.length} onClick={()=>review(a,'apply')}>Connect selected accounts</button>}{['pending','exchanging','review_required'].includes(a.state)&&<button className={button} disabled={locked||reason.trim().length<3} onClick={()=>review(a,'cancel')}>Cancel authorization</button>}</div>
   </article>)}
   {!loading&&!historyError&&!authorizations.length&&<p className="text-sm text-slate-500">No saved authorization requests.</p>}{authCursor&&<button className={button} disabled={locked} onClick={()=>void more('requests')}>Load more authorization history</button>}
  </section>
  <section aria-label="Access renewal history" className="space-y-3"><h3 className="font-semibold">Access renewal history</h3><p className="text-sm text-slate-500">Renewal uses saved consent. An unconfirmed exchange is held for fresh authorization; an earlier token is never automatically retried.</p>{renewalError&&<p role="alert" className="text-sm text-red-600">{renewalError}</p>}{renewals.map(r=><article key={r.id} className="space-y-1 rounded-lg border p-3 text-sm"><p className="font-medium">{platforms.find(p=>p.id===r.platform)?.name??r.platform} — {r.state==='completed'?'Renewed access saved':r.state==='held'?'New authorization required':Date.parse(r.created_at)<Date.now()-15*60_000?'Unconfirmed renewal — authorize again':'Renewal started; result unconfirmed'}</p><p className="break-all text-xs text-slate-500">Account record: {r.connection_id}</p><p className="text-xs text-slate-500">{new Date(r.created_at).toLocaleString()}</p>{r.reason&&<p>{r.reason}</p>}</article>)}{!loading&&!renewalError&&!renewals.length&&<p className="text-sm text-slate-500">No saved access renewal requests.</p>}{renewalCursor&&<button className={button} disabled={locked} onClick={()=>void more('renewals')}>Load more access renewal history</button>}</section>
  {setup&&<SocialAppSetup propertyId={propertyId} platform={setup} onClose={()=>setSetup(null)} onConfigured={()=>void reload()}/>}
 </div>
}
