import {beforeEach,it,expect,vi} from 'vitest'
vi.mock('@/utils/supabase/admin',()=>({createServiceClient:vi.fn()}))
import {executeSessionDecision,providerSessionOutcome,readSessions} from './store'
const actor={actorId:'11111111-1111-1111-1111-111111111111',sessionId:'22222222-2222-2222-2222-222222222222',aal:'aal1'},command={operation:'revoke' as const,requestId:'33333333-3333-3333-3333-333333333333',scope:'others' as const,sourceHash:'a'.repeat(64),confirmed:true as const}
const result=(state:string,extra={})=>({data:{state,actorId:actor.actorId,requestId:command.requestId,...extra},error:null})
const rpc=vi.fn(),provider=vi.fn()
beforeEach(()=>{vi.clearAllMocks();provider.mockResolvedValue({error:null})})
it('claims once, invokes the exact provider scope, and records acknowledgement',async()=>{rpc.mockResolvedValueOnce(result('claimed',{claimId:'claim'})).mockResolvedValueOnce(result('saved',{status:'acknowledged'}));expect((await executeSessionDecision(actor,command,provider,{rpc})).status).toBe('acknowledged');expect(provider).toHaveBeenCalledExactlyOnceWith('others');expect(rpc).toHaveBeenLastCalledWith('finish_account_session',expect.objectContaining({p_claim_id:'claim',p_outcome:'acknowledged',p_actor_id:actor.actorId}));expect(rpc.mock.calls[0][1]).not.toHaveProperty('token')})
it.each(['replayed','saved'])('does not contact the provider after %s',async state=>{rpc.mockResolvedValue(result(state,{status:'claimed'}));await executeSessionDecision(actor,command,provider,{rpc});expect(provider).not.toHaveBeenCalled()})
it('records network ambiguity without a retry or false rejection',async()=>{rpc.mockResolvedValueOnce(result('claimed',{claimId:'claim'})).mockResolvedValueOnce(result('saved',{status:'uncertain'}));provider.mockRejectedValue(new Error('private transport details'));await executeSessionDecision(actor,command,provider,{rpc});expect(provider).toHaveBeenCalledTimes(1);expect(rpc).toHaveBeenLastCalledWith('finish_account_session',expect.objectContaining({p_outcome:'uncertain'}))})
it('failed provider-result persistence never executes the provider again',async()=>{rpc.mockResolvedValueOnce(result('claimed',{claimId:'claim'})).mockResolvedValueOnce({data:null,error:{message:'private'}});await expect(executeSessionDecision(actor,command,provider,{rpc})).rejects.toThrow('saved request');expect(provider).toHaveBeenCalledTimes(1)})
it('unverified actor and request claims cannot contact the provider',async()=>{for(const extra of[{actorId:'other',claimId:'claim'},{requestId:'other',claimId:'claim'},{claimId:null}]){rpc.mockResolvedValue(result('claimed',extra));await expect(executeSessionDecision(actor,command,provider,{rpc})).rejects.toThrow();expect(provider).not.toHaveBeenCalled()}})
it.each([[null,'acknowledged'],[{status:403},'rejected'],[{status:500},'uncertain'],[{},'uncertain']] as const)('classifies bounded provider evidence %j', (error,outcome)=>expect(providerSessionOutcome(error)).toBe(outcome))
it('native session and history holds remain explicit',async()=>{for(const[state,status]of[['forbidden',401],['not_found',404],['history_changed',409],['mfa_required',409]]){rpc.mockResolvedValue(result(String(state)));await expect(readSessions(actor,{}, {rpc})).rejects.toMatchObject({status})}})
