import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({actor:vi.fn(),read:vi.fn(),decide:vi.fn()}))
vi.mock('@/utils/knowledge/fact-store',()=>({factActor:d.actor,readFacts:d.read,decideFacts:d.decide,FactError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {GET,POST} from './route'
import {FactError} from '@/utils/knowledge/fact-store'
const property='33333333-3333-3333-3333-333333333333',id='11111111-1111-1111-1111-111111111111',value={requestId:id,propertyId:property,operation:'prepare',expectedDraftId:null,expectedSourceHash:'a'.repeat(64),expectedContextHash:'b'.repeat(64),markdown:null,reason:'Review complete property facts'}
beforeEach(()=>{vi.clearAllMocks();d.actor.mockResolvedValue('actor');d.read.mockResolvedValue({state:'ready',propertyId:property});d.decide.mockResolvedValue({state:'saved',versionId:id,published:false})})
it('authenticates before processing draft material',async()=>{d.actor.mockRejectedValue(new FactError('Unauthorized',401));expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(value)}))).status).toBe(401);expect(d.decide).not.toHaveBeenCalled()})
it('rejects immediate legacy edits, unknown fields and injected prepare text',async()=>{for(const v of[{propertyId:property,contextMarkdown:'replace now'},{...value,markdown:'override'},{...value,extra:true}])expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(v)}))).status).toBe(400);expect(d.decide).not.toHaveBeenCalled()})
it('routes exact preparation intent to the current actor without a model',async()=>{const result=await POST(new Request('http://local',{method:'POST',body:JSON.stringify(value)}));expect(result.status).toBe(200);expect(d.decide).toHaveBeenCalledWith('actor',value);expect(result.headers.get('Cache-Control')).toBe('private, no-store')})
it('requires explicit confirmation and complete publication baseline',async()=>{const publish={...value,operation:'publish'};expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(publish)}))).status).toBe(400);expect(d.decide).not.toHaveBeenCalled()})
it('preserves exact correction whitespace and rejects invalid Unicode',async()=>{const edit={...value,operation:'edit',expectedDraftId:id,markdown:'\ufeffExact\r\n🏡 facts'};expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify(edit)}))).status).toBe(200);expect(d.decide).toHaveBeenCalledWith('actor',edit);expect((await POST(new Request('http://local',{method:'POST',body:JSON.stringify({...edit,markdown:'bad\ud800'})}))).status).toBe(400)})
it('preserves denied and unavailable reads instead of presenting an empty context',async()=>{d.read.mockRejectedValue(new FactError('Forbidden',403));expect((await GET(new Request(`http://local?propertyId=${property}`))).status).toBe(403);d.read.mockRejectedValue(new Error('internal details'));const response=await GET(new Request(`http://local?propertyId=${property}`));expect(response.status).toBe(503);expect(await response.json()).toEqual({error:'Assistant facts are unavailable.'});expect(d.decide).not.toHaveBeenCalled()})
it('checks bounded body size and exact query shape',async()=>{expect((await POST(new Request('http://local',{method:'POST',headers:{'content-length':'6291457'},body:'{}'}))).status).toBe(413);expect((await GET(new Request(`http://local?propertyId=${property}&kind=decision`))).status).toBe(400);expect(d.decide).not.toHaveBeenCalled()})
