'use client'
import {useState} from 'react'
import {useOnboarding} from './OnboardingProvider'
const button='rounded-lg border border-slate-600 bg-slate-800 px-3 py-2 text-sm text-white disabled:opacity-40'
function RetainedDetails({value}:{value:unknown}){if(value===null||value===undefined||value==='')return <span className="text-slate-500">Not provided</span>;if(Array.isArray(value))return value.length?<ul className="space-y-2">{value.map((v,i)=><li key={i} className="border-l border-slate-700 pl-3"><RetainedDetails value={v}/></li>)}</ul>:<span className="text-slate-500">None</span>;if(typeof value==='object')return <dl className="space-y-1">{Object.entries(value).filter(([key])=>key!=='id').map(([key,v])=><div key={key}><dt className="font-medium capitalize text-slate-300">{key.replace(/([A-Z])/g,' $1')}</dt><dd className="whitespace-pre-wrap [overflow-wrap:anywhere] pl-2"><RetainedDetails value={v}/></dd></div>)}</dl>;return <span>{typeof value==='boolean'?(value?'Yes':'No'):String(value)}</span>}
export function SetupStatus(){const{workspace,pending,notice,error,isLoading,step,saveDraft,reloadDraft,recoverDecision,loadHistory,selectedHistory,readDecision}=useOnboarding();const[history,setHistory]=useState(false);return <section aria-label="Saved organization setup" className="mb-6 space-y-3 rounded-xl border border-slate-700 bg-slate-900 p-4 text-slate-300">
 <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-white">Saved setup</h2><button type="button" className={button} disabled={isLoading} onClick={()=>void reloadDraft()}>Reload saved setup</button></div>
 {!workspace&&!error&&<p className="text-sm">Loading your private saved setup…</p>}
 {error&&<p role="alert" className="rounded-lg bg-red-950 p-3 text-sm text-red-200">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-emerald-950 p-3 text-sm text-emerald-200">{notice}</p>}
 {pending&&<div className="space-y-2 rounded-lg bg-amber-950 p-3 text-sm"><p>A setup {pending.operation} decision is unconfirmed.</p><button className={button} disabled={isLoading} onClick={()=>void recoverDecision()}>Check saved setup decision</button><button className={button} disabled={isLoading} onClick={()=>void recoverDecision(true)}>Cancel unused setup decision</button></div>}
 {workspace&&!workspace.alreadyMember&&<><p className="text-sm">{workspace.setup?.state==='completed'?'Organization setup is complete. You can return to this saved confirmation.':workspace.setup?`Private draft revision ${workspace.setup.revision}. Save changes before leaving this page.`:'No saved draft yet. Save at any step to continue later.'}</p>{workspace.setup?.state!=='completed'&&<button className={button} disabled={isLoading||!!pending} onClick={()=>void saveDraft(step)}>Save setup draft</button>}<button className={button} disabled={isLoading} onClick={()=>setHistory(!history)}>{history?'Hide setup history':'Setup decision history'}</button>
 {history&&<div aria-label="Retained setup history" className="space-y-2"><p className="text-sm">Showing {workspace.items.length} of {workspace.total} decisions.</p><ol className="space-y-2">{workspace.items.map(row=><li key={row.id}><button className={`${button} w-full text-left`} disabled={isLoading} onClick={()=>void readDecision(row.id)}>{row.kind==='complete'?'Completed organization setup':'Saved setup draft'} · revision {row.revision} · {new Date(row.createdAt).toLocaleString()}</button></li>)}</ol>{workspace.nextOffset!==null&&<button className={button} disabled={isLoading} onClick={()=>void loadHistory()}>Load more setup decisions</button>}</div>}
 </>}
 {selectedHistory&&<div aria-label="Saved setup decision detail" className="space-y-3 text-sm"><p>Retained decision by your account. These are the exact drafts at that time.</p><p>{String((selectedHistory.input as {reason?:string})?.reason||'')}</p>{(['before_state','after_state']as const).map(key=><details key={key}><summary>{key==='before_state'?'Earlier saved draft':'This saved draft'}</summary><div className="max-h-96 overflow-auto rounded-lg bg-slate-950 p-3"><RetainedDetails value={(selectedHistory[key]as {draft?:unknown}|null)?.draft}/></div></details>)}</div>}
 </section>}
