'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import type {FactRead,FactCommand} from '@/utils/knowledge/fact-contracts'
import {factFetch,factsUrl,postFact,pendingFact,clearPendingFact,type PendingFact} from '@/utils/knowledge/fact-client'
type HistoryRow={id:string;origin?:string;kind?:string;actor_id:string;created_at:string;reason?:string;bytes?:number;result?:Record<string,unknown>}
type History={items:HistoryRow[];historyHash:string;total:number;nextOffset:number|null}
const button='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 disabled:opacity-40'
const field='block w-full rounded-lg border border-slate-300 p-3 text-sm text-slate-900'
const explanations:Record<string,string>={withdrawn:'Published facts were withdrawn.',sources_changed:'Property knowledge changed after the last review. Prepare and review a new draft.',review_required:'Saved facts need review before Luma can use them.',publication_review_due:'A routine review of the published facts is recommended.',website_freshness_review_due:'A website source needs a current freshness check.',publication_unavailable:'The retained publication is unavailable.',property_scope_changed:'The property organization changed.'}
function message(e:unknown){return e instanceof Error?e.message:'Assistant facts could not be confirmed.'}
export function AssistantFactsWorkbench({propertyId}:{propertyId:string}){
 const[data,setData]=useState<FactRead|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[editing,setEditing]=useState(false),[draft,setDraft]=useState(''),[history,setHistory]=useState<History|null>(null),[historyKind,setHistoryKind]=useState<'versions'|'decisions'>('versions'),[held,setHeld]=useState(false),[pending,setPending]=useState<PendingFact|null>(null)
 const mounted=useRef(false),sequence=useRef(0)
 const load=useCallback(async(versionId?:string)=>{const token=++sequence.current;const result=await factFetch(factsUrl(propertyId,{versionId}))as FactRead;if(!mounted.current||token!==sequence.current)return;setHistory(null);setEditing(false);setReason('');setConfirmed(false);setHeld(false);setData(result);const url=new URL(window.location.href);if(result.selected)url.searchParams.set('assistantFactVersion',result.selected.id);else url.searchParams.delete('assistantFactVersion');window.history.replaceState(null,'',url)},[propertyId])
 useEffect(()=>{mounted.current=true;void load(new URL(window.location.href).searchParams.get('assistantFactVersion')||undefined).finally(()=>{if(mounted.current)setPending(pendingFact(propertyId))}).catch(e=>{if(mounted.current)setError(message(e))});return()=>{mounted.current=false}},[propertyId,load])
 async function reload(versionId?:string){setBusy(true);setError('');try{setData(null);await load(versionId)}catch(e){if(mounted.current)setError(message(e))}finally{if(mounted.current)setBusy(false)}}
 async function act(command:Omit<FactCommand,'requestId'>){setBusy(true);setError('');setNotice('');try{const saved=await postFact(command);if(!mounted.current)return;setPending(null);setNotice(command.operation==='prepare'?'Complete facts draft retained. The current publication has not changed.':command.operation==='edit'?'Facts correction retained as a new draft. Review it before publishing.':command.operation==='publish'?'Exact reviewed facts publication saved. Current serving status is shown below.':'Published facts withdrawn. Earlier versions remain in history and are not served.');setData(null);await load(String(saved.versionId))}catch(e){if(mounted.current){setError(message(e));setPending(pendingFact(propertyId))}}finally{if(mounted.current)setBusy(false)}}
 async function recover(cancel=false){if(!pending)return;setBusy(true);setError('');try{const value=cancel?await factFetch('/api/assistant-facts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:pending.id,propertyId,operation:'cancel_unused',inputHash:pending.hash,reason:'Cancel the unused facts request before making another reviewed decision'})}):await factFetch(factsUrl(propertyId,{kind:'decision',decisionId:pending.id}));if(!mounted.current)return;if(cancel&&!['cancelled','replayed'].includes(value.state))throw new Error('Cancellation could not be confirmed.');if(!cancel&&value.decision?.id!==pending.id)throw new Error('The retained facts decision could not be verified.');clearPendingFact(propertyId,pending.id);setPending(null);setNotice(value.cancelled?'Unused facts request cancelled; a delayed copy cannot save it.':'The original facts decision was already saved. Its exact version is open.');setData(null);await load(value.cancelled?undefined:(value.decision?.result.versionId||value.versionId))}catch(e){if(mounted.current)setError(e instanceof Error&&'status'in e&&e.status===404?'No saved decision is visible yet. Retry the unchanged request, or cancel its unused identity.':message(e))}finally{if(mounted.current)setBusy(false)}}
 async function historyPage(kind:'versions'|'decisions',prior?:History){setBusy(true);setError('');setHistoryKind(kind);if(!prior)setHistory(null);try{const result=await factFetch(factsUrl(propertyId,{kind,offset:prior?.nextOffset??0,expectedHash:prior?.historyHash}))as History;if(mounted.current)setHistory({...result,items:prior?[...prior.items,...result.items]:result.items})}catch(e){if(mounted.current){setError(message(e));setHeld(true)}}finally{if(mounted.current)setBusy(false)}}
 const selected=data?.selected,workspace=data?.workspace,isLatest=selected?.id===workspace?.latest_version_id,isActive=selected?.id===workspace?.active_version_id
 const disabled=busy||held||!data?.canManage||reason.trim().length<3
 function prepare(){if(!data)return;void act({propertyId,operation:'prepare',expectedDraftId:workspace?.latest_version_id??null,expectedSourceHash:data.sourceHash,expectedContextHash:data.contextHash,markdown:null,reason}as Omit<FactCommand,'requestId'>)}
 function release(operation:'publish'|'withdraw'){if(!data||!selected||!workspace?.latest_version_id)return;void act({propertyId,operation,versionId:selected.id,expectedDraftId:workspace.latest_version_id,expectedActiveId:workspace.active_version_id,expectedReleaseId:workspace.last_release_id,expectedContextHash:data.contextHash,markdownHash:selected.markdown_hash,confirmed:true,reason}as Omit<FactCommand,'requestId'>)}
 return <section aria-label="Reviewed assistant facts" aria-busy={busy} className="min-w-0 space-y-4 rounded-xl border border-slate-200 bg-white p-4 sm:p-6">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-slate-900">Luma’s reviewed facts</h3><p className="text-sm text-slate-600">Retain a complete draft, review its sources, then publish the exact facts Luma may use.</p></div><button className={button} disabled={busy} onClick={()=>void reload()}>Reload current facts</button></div>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}
  {pending&&<div className="space-y-2 rounded-lg border border-amber-300 p-3 text-sm"><p>A previous {pending.operation} facts decision is unconfirmed. Draft text is not stored in this browser.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void recover()}>Check saved facts decision</button><button className={button} disabled={busy} onClick={()=>void recover(true)}>Cancel unused facts request</button></div><p>Cancellation opens an already saved result instead of undoing it.</p></div>}
  {!data&&!error&&<p className="text-sm">Reading retained facts…</p>}
  {data&&<>
   <div className={`rounded-lg p-3 text-sm ${data.serving.state==='ready'?'bg-emerald-50 text-emerald-900':'bg-amber-50 text-amber-900'}`}><p className="font-semibold">{data.serving.state==='ready'?'Reviewed facts available to Luma':data.serving.state==='legacy'?'Earlier context has no recorded facts publication':'Reviewed facts withheld from Luma'}</p><p>{data.serving.state==='legacy'?'Preparing a draft retains the earlier context. Publish a reviewed version to adopt this workflow.':data.serving.reason?explanations[data.serving.reason]||'Review the current property sources.':'The exact publication and current source identities match. This does not certify a live model answer.'}</p></div>
   {data.serving.freshnessReviewDue&&<p role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Routine facts review recommended. Older approved facts remain available unless they are changed, withdrawn or marked for review.</p>}
   <div className="rounded-lg bg-slate-50 p-3 text-sm"><h4 className="font-semibold">Complete current source set</h4><p>{data.sourceSummary.documents} stored text chunks · {data.sourceSummary.legacyDocuments} from earlier imports with unverified original identity.</p><p>{data.sourceSummary.eligibleUnits} of {data.sourceSummary.units} floorplans qualify as active, approved and within their recorded dates.</p><p>{data.sourceSummary.completedSources} of {data.sourceSummary.sources} source records report completed processing. These reports are not independent fact verification.</p><p>Drafts retain up to 5 MiB of source evidence. Publication supports 64 KiB of reviewed text. Nothing is silently shortened.</p></div>
   {data.currentContext&&<details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer font-medium">Inspect the currently stored assistant context</summary><p>Recorded state: {data.currentContext.status} · Review required: {data.currentContext.requires_review?'yes':'no'}</p><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-3">{data.currentContext.context_markdown}</pre></details>}
   <div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void historyPage('versions')}>Facts version history</button><button className={button} disabled={busy} onClick={()=>void historyPage('decisions')}>Facts decision history</button>{workspace?.active_version_id&&!isActive&&<button className={button} disabled={busy||!!pending} onClick={()=>void reload(workspace.active_version_id!)}>Read published facts</button>}{selected&&!isLatest&&<button className={button} disabled={busy||!!pending} onClick={()=>void reload()}>Read latest facts draft</button>}</div>
   {selected&&<div className="space-y-3 rounded-lg border border-slate-200 p-3" aria-label="Retained facts version"><h4 className="font-semibold">{isActive?'Published facts version':isLatest?'Latest facts draft':'Historical facts version'}</h4><p className="text-sm text-slate-600">{selected.origin==='edited'?'Operator-authored correction retaining its source evidence.':'Complete deterministic source draft; no model was called.'}</p><p className="break-all text-xs text-slate-500">Version {selected.id} · {new Date(selected.created_at).toLocaleString()}</p><p className="text-sm">{selected.bytes.toLocaleString()} of 65,536 publication bytes · {selected.sourcesCurrent?'Source set matches the current read.':'Sources changed; prepare a new complete draft before publishing.'}</p>{!selected.withinBudget&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">This complete draft is too large to publish. Save a deliberate shorter correction after reviewing its retained evidence.</p>}
    {editing?<label className="block text-sm">Corrected facts text<textarea aria-label="Corrected facts text" className={field} rows={15} disabled={busy} value={draft} onChange={e=>setDraft(e.target.value)}/><span>{new TextEncoder().encode(draft).length.toLocaleString()} bytes; saving makes a new private draft.</span></label>:<pre aria-label="Exact retained facts" className="max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-3 text-sm">{selected.markdown}</pre>}
    <details className="text-sm"><summary className="cursor-pointer font-medium">Inspect the complete retained source evidence</summary><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(selected.source_snapshot,null,2)}</pre></details>
    {data.canManage&&isLatest&&!editing&&<button className={button} disabled={busy||!!pending} onClick={()=>{setEditing(true);setDraft(selected.markdown);setReason('');setConfirmed(false)}}>Correct facts draft</button>}
   </div>}
   {data.canManage&&<div className="space-y-3"><label className="block text-sm">Reason for this facts decision<textarea aria-label="Reason for this facts decision" className={field} rows={2} minLength={3} maxLength={2000} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label>
    {selected&&!editing&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed these exact facts and their source limitations and approve this decision for Luma.</span></label>}
    <div className="flex flex-wrap gap-2">{editing&&selected?<><button className={button} disabled={disabled||!draft.trim()} onClick={()=>void act({propertyId,operation:'edit',expectedDraftId:selected.id,expectedSourceHash:selected.source_hash,expectedContextHash:data.contextHash,markdown:draft,reason}as Omit<FactCommand,'requestId'>)}>Save facts correction</button><button className={button} disabled={busy} onClick={()=>setEditing(false)}>Discard unsaved correction</button></>:<><button className={button} disabled={disabled||!!pending||data.sourceSummary.snapshotBytes>data.sourceBudgetBytes} onClick={prepare}>Prepare complete facts draft</button>{selected&&<><button className={button} disabled={disabled||!confirmed||!selected.withinBudget||!selected.sourcesCurrent||!!pending} onClick={()=>release('publish')}>{isActive?'Reconfirm published facts':'Publish reviewed facts'}</button>{isActive&&<button className={button} disabled={disabled||!confirmed||!!pending} onClick={()=>release('withdraw')}>Withdraw published facts</button>}</>}</>}</div>
   </div>}
  </>}
  {history&&<div className="rounded-lg border p-3"><h4 className="font-semibold">Retained {historyKind==='versions'?'facts versions':'facts decisions'}</h4><p className="text-sm">Showing {history.items.length} of {history.total}.</p><ol className="mt-3 space-y-3">{history.items.map(row=><li key={row.id} className="border-b pb-3 text-sm"><p>{row.origin||row.kind} · {new Date(row.created_at).toLocaleString()}</p>{row.reason&&<p>{row.reason}</p>}<p className="break-all text-xs text-slate-500">Recorded actor: {row.actor_id}</p>{historyKind==='versions'?<button className={button} disabled={busy||!!pending} onClick={()=>void reload(row.id)}>Read retained facts version</button>:<p className="break-all text-xs text-slate-500">Decision {row.id} · {row.result?.published===true?'Published':row.result?.published===false?'Not published':'Retained decision'}</p>}</li>)}</ol>{history.nextOffset!==null&&<button className={button} disabled={busy||held} onClick={()=>void historyPage(historyKind,history)}>Load more facts history</button>}</div>}
 </section>
}
