'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import type {Material,MaterialDetail,MaterialCommand} from '@/utils/knowledge/material-contracts'
import {clearPendingKnowledge,knowledgeFetch,knowledgeUrl,pendingKnowledge,postKnowledge,type PendingKnowledge} from '@/utils/knowledge/material-client'
type PageData={items:Material[];historyHash:string;total:number;nextOffset:number|null;canManage:boolean;execution:{paused:boolean;configured:boolean}}
type HistoryItem={id:string;title?:string;kind?:string;reason?:string;actor_id:string;created_at:string;content_hash?:string;result?:Record<string,unknown>}
type History={items:HistoryItem[];historyHash:string;total:number;nextOffset:number|null}
const button='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 disabled:opacity-40'
const field='block w-full rounded-lg border border-slate-300 p-3 text-sm text-slate-900'
function message(e:unknown){return e instanceof Error?e.message:'Knowledge could not be confirmed. Check its saved decision.'}
export function KnowledgeWorkbench({propertyId,onChange}:{propertyId:string;onChange?:()=>void}){
 const[page,setPage]=useState<PageData|null>(null),[detail,setDetail]=useState<MaterialDetail|null>(null),[history,setHistory]=useState<History|null>(null),[historyKind,setHistoryKind]=useState<'versions'|'decisions'>('versions'),[newSource,setNewSource]=useState(false),[editing,setEditing]=useState(false),[title,setTitle]=useState(''),[content,setContent]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<PendingKnowledge|null>(null),[held,setHeld]=useState(false)
 const mounted=useRef(false),sequence=useRef(0)
 const loadPage=useCallback(async(offset=0,prior?:PageData)=>{const value=await knowledgeFetch(knowledgeUrl(propertyId,{offset,expectedHash:prior?.historyHash}))as PageData;if(mounted.current)setPage({...value,items:prior?[...prior.items,...value.items]:value.items})},[propertyId])
 const select=useCallback(async(materialId:string,versionId?:string)=>{const token=++sequence.current;setDetail(null);setHistory(null);setEditing(false);setNewSource(false);setError('');setReason('');setConfirmed(false);setHeld(false);try{const value=await knowledgeFetch(knowledgeUrl(propertyId,{kind:'version',materialId,versionId}))as MaterialDetail;if(!mounted.current||token!==sequence.current)return;setDetail(value);const url=new URL(window.location.href);url.searchParams.set('knowledgeSource',materialId);url.searchParams.set('knowledgeVersion',value.version.id);window.history.replaceState(null,'',url)}catch(e){if(mounted.current&&token===sequence.current)setError(message(e))}},[propertyId])
 useEffect(()=>{mounted.current=true;setPending(pendingKnowledge(propertyId));loadPage().catch(e=>{if(mounted.current)setError(message(e))});const url=new URL(window.location.href),source=url.searchParams.get('knowledgeSource');if(source)void select(source,url.searchParams.get('knowledgeVersion')||undefined);return()=>{mounted.current=false}},[propertyId,loadPage,select])
 async function reload(){setBusy(true);setError('');setHeld(false);setPage(null);try{await loadPage();if(detail)await select(detail.material.id,detail.version.id)}catch(e){if(mounted.current)setError(message(e))}finally{if(mounted.current)setBusy(false)}}
 async function historyPage(kind:'versions'|'decisions',previous?:History){if(!detail)return;setBusy(true);setError('');if(!previous)setHistory(null);setHistoryKind(kind);try{const value=await knowledgeFetch(knowledgeUrl(propertyId,{kind,materialId:detail.material.id,offset:previous?.nextOffset??0,expectedHash:previous?.historyHash}))as History;if(mounted.current)setHistory({...value,items:previous?[...previous.items,...value.items]:value.items})}catch(e){if(mounted.current){setError(message(e));setHeld(true)}}finally{if(mounted.current)setBusy(false)}}
 async function act(command:Omit<MaterialCommand,'requestId'>,sourceId?:string){setBusy(true);setError('');setNotice('');try{const result=await postKnowledge(command,sourceId);if(!mounted.current)return;setPending(null);setNotice(result.execution?.state==='paused'?'Preparation saved. Model execution is paused; publication has not changed.':result.execution?.state==='provider_unavailable'?'Preparation saved. A model connection is required before it can run.':command.operation==='save'?'Exact source version saved. Its publication has not changed.':command.operation==='publish'?'Reviewed version published for retrieval. Assistant facts require a separate refresh.':command.operation==='withdraw'?'Published version withdrawn. Original text and decisions are retained.':'Search preparation status saved.');await loadPage();await select(String(result.materialId),command.operation==='save'?String(result.versionId):detail?.version.id);onChange?.()}catch(e){if(mounted.current){setPending(pendingKnowledge(propertyId));setError(message(e))}}finally{if(mounted.current)setBusy(false)}}
 async function recoverDecision(){if(!pending)return;setBusy(true);setError('');try{const result=await knowledgeFetch(knowledgeUrl(propertyId,{kind:'decision',materialId:pending.materialId,decisionId:pending.id}));if(!mounted.current)return;if(result.decision?.id!==pending.id)throw new Error('The saved decision could not be verified.');clearPendingKnowledge(propertyId,pending.id);setPending(null);setNotice('The previous decision was saved. Its retained result is now open.');await loadPage();await select(pending.materialId,result.decision.result.versionId);onChange?.()}catch(e){if(mounted.current)setError(e instanceof Error&&'status'in e&&e.status===404?'No saved decision is visible yet. Retry the unchanged request using its retained identity.':message(e))}finally{if(mounted.current)setBusy(false)}}
 async function cancelUnused(){if(!pending)return;setBusy(true);setError('');try{const result=await knowledgeFetch('/api/knowledge/materials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:pending.id,propertyId,operation:'cancel_unused',inputHash:pending.hash,reason:'Cancel the unused browser request before making another reviewed decision'})});if(!mounted.current)return;if(!['cancelled','replayed'].includes(result.state))throw new Error('Cancellation could not be confirmed.');clearPendingKnowledge(propertyId,pending.id);setPending(null);if(result.cancelled){setNotice('Unused request cancelled. A delayed copy cannot save it. You can start a new decision.')}else{setNotice('The original decision had already saved. Its retained result is open.');await loadPage();await select(String(result.materialId),result.versionId)}}catch(e){if(mounted.current)setError(message(e))}finally{if(mounted.current)setBusy(false)}}
 function startNew(){sequence.current++;setDetail(null);setHistory(null);setNewSource(true);setEditing(false);setTitle('');setContent('');setReason('');setConfirmed(false);setNotice('');setError('');const url=new URL(window.location.href);url.searchParams.delete('knowledgeSource');url.searchParams.delete('knowledgeVersion');window.history.replaceState(null,'',url)}
 const canManage=!!page?.canManage,source=detail?.material,version=detail?.version,search=detail?.search,isLatest=version?.id===source?.latest_version_id,isActive=version?.id===source?.active_version_id
 const disabled=busy||held||!canManage||!reason.trim()||reason.trim().length<3
 return <section id="knowledge-workbench" aria-label="Reviewed knowledge sources" className="space-y-4 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:p-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold text-slate-900">Reviewed text sources</h3><p className="text-sm text-slate-600">Save the original. Prepare search data. Review and publish the exact version.</p></div><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void reload()}>Reload saved sources</button><button className={button} disabled={busy||!canManage||!!pending} onClick={startNew}>New text source</button></div></div>
  {page?.execution.paused&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Model execution is paused. You can save text, review retained results, and change existing publications.</p>}
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  {notice&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}
  {pending&&<div className="rounded-lg border border-amber-300 p-3 text-sm"><p>A previous {pending.operation} decision is unconfirmed. Source text is not stored in this browser.</p><button className={button} disabled={busy} onClick={()=>void recoverDecision()}>Check previous saved decision</button><p className="my-2">Cancel only an unused request to release this browser. If it already saved, its result opens instead.</p><button className={button} disabled={busy} onClick={()=>void cancelUnused()}>Cancel unused request</button></div>}
  {!page&&!error&&<p>Loading saved text sources…</p>}
  {page&&<div><p className="text-sm text-slate-600">Showing {page.items.length} of {page.total} saved text sources.</p>{page.total===0&&<p className="mt-2 text-sm">No reviewed text sources in this property. Earlier imports remain in the inventory below.</p>}<ul className="mt-3 grid gap-3 sm:grid-cols-2">{page.items.map(item=><li key={item.id} className="rounded-lg border bg-white p-3"><h4 className="font-medium text-slate-900 break-words">{item.title}</h4><p className="text-sm text-slate-600">{item.active_version_id===item.latest_version_id?'Latest version published':item.active_version_id?'Earlier version published · newer draft retained':item.last_release_id?'Publication withdrawn':'Saved draft · not published'}</p><button className={button+' mt-2'} disabled={busy||!!pending} onClick={()=>void select(item.id)}>Review source</button></li>)}</ul>{page.nextOffset!==null&&<button className={button+' mt-3'} disabled={busy||held} onClick={async()=>{setBusy(true);try{await loadPage(page.nextOffset!,page)}catch(e){setError(message(e));setHeld(true)}finally{setBusy(false)}}}>Load more saved sources</button>}</div>}
  {(newSource||editing)&&<form className="space-y-3 rounded-lg border bg-white p-4" onSubmit={e=>{e.preventDefault();void act({propertyId,operation:'save',materialId:editing?source!.id:null,previousVersionId:editing?source!.latest_version_id:null,title,content,reason}as Omit<MaterialCommand,'requestId'>,editing?source!.id:undefined)}}>
   <h4 className="font-semibold">{editing?'Correct source text':'Save a new text source'}</h4><p className="text-sm text-slate-600">Saving retains the complete text privately. Existing published text remains active until you explicitly replace or withdraw it.</p>
   <label className="block text-sm">Source title<input disabled={busy} required maxLength={300} value={title} onChange={e=>setTitle(e.target.value)} className={field}/></label>
   <label className="block text-sm">Original text<textarea aria-label="Original text" disabled={busy} required rows={10} value={content} onChange={e=>setContent(e.target.value)} className={field}/></label>
   <label className="block text-sm">Or read a UTF-8 text file (.txt or .md, up to 256 KiB)<input type="file" accept=".txt,.md,text/plain,text/markdown" disabled={busy} className="mt-2 block max-w-full" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>262144||!/\.(txt|md)$/i.test(file.name))throw new Error('Choose a UTF-8 .txt or .md file up to 256 KiB.');const exact=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await file.arrayBuffer());if(mounted.current){setContent(exact);if(!title)setTitle(file.name)}}catch(e){setError(message(e))}}}/></label>
   <p className="text-xs text-slate-500">{new TextEncoder().encode(content).length.toLocaleString()} bytes. Short text, line breaks and Unicode are retained.</p>
   <label className="block text-sm">Reason for this version<textarea disabled={busy} required minLength={3} maxLength={2000} rows={2} className={field} value={reason} onChange={e=>setReason(e.target.value)}/></label>
   <button type="submit" className={button} disabled={disabled||!title.trim()||!content.trim()}>Save exact text</button>
  </form>}
  {detail&&source&&version&&!editing&&<div className="space-y-3 rounded-lg border bg-white p-4" aria-label="Selected text version">
   <h4 className="font-semibold text-slate-900">{version.title}</h4><p className="text-sm text-slate-600">{isActive?'This exact version is published for retrieval.':isLatest?'This is the latest saved version. It is not published.':'Historical version. Review carefully before deliberately publishing it.'}</p>
   {detail.webOrigin&&<p className="text-sm">Website original: <a className="underline" href={`/dashboard/community?knowledgeCapture=${detail.webOrigin.captureId}`}>Read retained capture</a> · fetched {new Date(detail.webOrigin.fetchedAt).toLocaleString()}{detail.webOrigin.inherited?" · inherited by this correction":""}.</p>}{detail.fileOrigin&&<p className="text-sm text-slate-600">Original file: <a className="underline" href={`/dashboard/community?knowledgeFile=${detail.fileOrigin.fileId}`}>{detail.fileOrigin.fileName}</a>{detail.fileOrigin.inherited?' · retained from an earlier source version':''}. The reviewed text may contain operator corrections.</p>}
   <p className="break-all text-xs text-slate-500">Version {version.id} · saved {new Date(version.created_at).toLocaleString()}</p>
   <pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-3 text-sm text-slate-800" aria-label="Retained original text">{version.content}</pre>
   {search?<div className="rounded-lg bg-slate-50 p-3 text-sm"><p>Search preparation: <strong>{search.state==='ready'?'Prepared; publication is separate':search.state==='result_ready'?'Receipt retained; validation pending':search.state}</strong></p><p>{search.chunks} chunks · {search.receiptModel||search.model}</p>{search.errorCode&&<p>Review required: {search.errorCode.replaceAll('_',' ')}</p>}<p>Recorded usage: {search.usage?JSON.stringify(search.usage):'Unavailable'} · Billed cost: unavailable</p>{search.providerRequestId&&<p className="break-all">Provider receipt: {search.providerRequestId}</p>}<p>{search.invocationClaimed?'One invocation was claimed. An uncertain result is never automatically repeated.':'No model invocation has been claimed.'}</p></div>:<p className="text-sm">Search data has not been prepared for this version.</p>}
   <div className="flex flex-wrap gap-2">{source.active_version_id&&!isActive&&<button className={button} disabled={busy||!!pending} onClick={()=>void select(source.id,source.active_version_id!)}>Read published version</button>}{!isLatest&&<button className={button} disabled={busy||!!pending} onClick={()=>void select(source.id)}>Read latest draft</button>}<button className={button} disabled={busy||!canManage||!isLatest||!!pending} onClick={()=>{setEditing(true);setTitle(version.title);setContent(version.content);setReason('');setConfirmed(false)}}>Correct latest text</button><button className={button} disabled={busy} onClick={()=>void historyPage('versions')}>Version history</button><button className={button} disabled={busy} onClick={()=>void historyPage('decisions')}>Decision history</button></div>
   {canManage&&<><label className="block text-sm">Reason for the next decision<textarea minLength={3} maxLength={2000} rows={2} className={field} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed this exact text and the currently published version. Preparing search data sends this text to the configured model once.</span></label>
   <div className="flex flex-wrap gap-2">
    {!search&&isLatest&&<button className={button} disabled={disabled||!confirmed} onClick={()=>void act({propertyId,operation:'prepare',materialId:source.id,versionId:version.id,contentHash:version.content_hash,confirmed:true,reason}as Omit<MaterialCommand,'requestId'>,source.id)}>Prepare search data</button>}
    {search&&['queued','running','result_ready'].includes(search.state)&&<button className={button} disabled={disabled} onClick={()=>void act({propertyId,operation:'recover',searchId:search.id,expectedRevision:search.revision,reason}as Omit<MaterialCommand,'requestId'>,source.id)}>Check or resume preparation</button>}
    {search&&['queued','running','result_ready','held'].includes(search.state)&&<button className={button} disabled={disabled} onClick={()=>void act({propertyId,operation:'stop',searchId:search.id,expectedRevision:search.revision,reason}as Omit<MaterialCommand,'requestId'>,source.id)}>Stop preparation</button>}
    {((search?.state==='ready'&&!isActive)||isActive)&&<button className={button} disabled={disabled||!confirmed} onClick={()=>void act({propertyId,operation:isActive?'withdraw':'publish',materialId:source.id,versionId:version.id,expectedLatestVersionId:source.latest_version_id,expectedActiveVersionId:source.active_version_id,expectedReleaseId:source.last_release_id,resultHash:isActive?null:search!.resultHash,confirmed:true,reason}as Omit<MaterialCommand,'requestId'>,source.id)}>{isActive?'Withdraw this published version':'Publish this exact version'}</button>}
   </div></>}
   <p className="text-xs text-slate-500">Publication changes retrieval material and marks saved assistant facts as needing refresh. It does not certify live answers or rebuild those facts.</p>
  </div>}
  {history&&<div className="rounded-lg border bg-white p-4"><h4 className="font-semibold">{historyKind==='versions'?'Retained versions':'Retained decisions'}</h4><p className="text-sm">Showing {history.items.length} of {history.total}.</p><ol className="mt-3 space-y-3">{history.items.map(row=><li key={row.id} className="border-b pb-3 text-sm"><p className="font-medium">{row.title||row.kind?.replaceAll('.',' ')}</p><p>{new Date(row.created_at).toLocaleString()} · {row.reason}</p><p className="break-all text-xs text-slate-500">Recorded actor: {row.actor_id}</p>{historyKind==='versions'?<button className={button} disabled={busy||!!pending} onClick={()=>void select(detail!.material.id,row.id)}>Read exact version</button>:<p className="break-all text-xs text-slate-500">Decision {row.id} · {row.result?.published===true?'Published':row.result?.published===false?'Not published':'Retained decision'}</p>}</li>)}</ol>{history.nextOffset!==null&&<button className={button} disabled={busy||held} onClick={()=>void historyPage(historyKind,history)}>Load more history</button>}</div>}
 </section>
}
