'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {legalDocumentKeys,legalDocumentLabels,emptyLegalDraft,canApproveLegalDraft,type LegalDraft,type LegalPage,type LegalDetail,type LegalHistory} from '@/utils/legal-review/contracts'
import {legalReviewFetch,legalReviewUrl,postLegal,pendingLegal,clearPendingLegal,type PendingLegal,type LegalWrite} from '@/utils/legal-review/client'
const inputClass='mt-1 w-full rounded-md border border-slate-300 bg-white p-2 text-slate-900',buttonClass='rounded-md border border-slate-300 px-3 py-2 text-sm disabled:opacity-50'
function errorText(e:unknown){return e instanceof Error?e.message:'Legal review is unavailable.'}
function utcInput(instant:string|null|undefined){return instant&&Number.isFinite(Date.parse(instant))?new Date(instant).toISOString().slice(0,16):''}
function fromUtc(value:string){return value?new Date(value+'Z').toISOString():null}
function DraftSummary({draft}:{draft:LegalDraft}){return<div className="space-y-3"><p>{draft.legalEntityName||'No legal entity'} · {draft.jurisdiction||'No jurisdiction'}</p><p>Effective: {draft.effectiveAt||'Not set'}</p>{legalDocumentKeys.map(k=><details key={k}><summary>{legalDocumentLabels[k]}</summary><p className="whitespace-pre-wrap break-words text-sm">{draft.documents[k]?.text||'No text'}</p>{draft.documents[k]?.sourceUrl&&<p className="break-all text-sm">Source: {draft.documents[k].sourceUrl}</p>}<p className="text-sm">Reported source review: {draft.documents[k]?.reviewedAt||'Not supplied'}</p></details>)}<p className="text-sm">{draft.sourceReferences.length} retained source references</p></div>}
function rowDraft(value:unknown):LegalDraft|null{if(!value||typeof value!=='object'||Array.isArray(value))return null;const r=value as Record<string,unknown>;return{jurisdiction:String(r.jurisdiction||''),legalEntityName:String(r.legal_entity_name||''),effectiveAt:typeof r.effective_at==='string'?r.effective_at:null,documents:Object.fromEntries(legalDocumentKeys.map(k=>[k,r[k]||{text:''}]))as LegalDraft['documents'],sourceReferences:Array.isArray(r.source_references)?r.source_references:[]}}
export function LegalReviewWorkbench({propertyId}:{propertyId:string}){
 const [page,setPage]=useState<LegalPage|null>(null),[detail,setDetail]=useState<LegalDetail|null>(null),[draft,setDraft]=useState<LegalDraft>(emptyLegalDraft),[editing,setEditing]=useState(false),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[history,setHistory]=useState<LegalHistory|null>(null),[historyDetail,setHistoryDetail]=useState<Record<string,unknown>|null>(null),[pending,setPending]=useState<PendingLegal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[unsaved,setUnsaved]=useState<LegalDraft|null>(null)
 const alive=useRef(false),generation=useRef(0),invalidate=useCallback(()=>{alive.current=false;generation.current++},[])
 const reload=useCallback(async()=>{const n=++generation.current;setBusy(true);setError('');setPage(null);setDetail(null);setEditing(false);setHistory(null);setHistoryDetail(null);try{const p=await legalReviewFetch(legalReviewUrl(propertyId));if(alive.current&&n===generation.current){setPage(p);setPending(pendingLegal(propertyId))}}catch(e){if(alive.current&&n===generation.current)setError(errorText(e))}finally{if(alive.current&&n===generation.current)setBusy(false)}},[propertyId])
 useEffect(()=>{alive.current=true;setPending(pendingLegal(propertyId));void reload();return invalidate},[propertyId,reload,invalidate])
 async function select(id:string){const n=++generation.current;setBusy(true);setError('');setDetail(null);setEditing(false);setHistoryDetail(null);try{const d=await legalReviewFetch(legalReviewUrl(propertyId,{kind:'version',versionId:id}));if(alive.current&&n===generation.current){setDetail(d);setDraft(d.draft);setReason('');setConfirmed(false);setEditing(true)}}catch(e){if(alive.current&&n===generation.current)setError(errorText(e))}finally{if(alive.current&&n===generation.current)setBusy(false)}}
 async function more(){if(!page||page.nextOffset===null)return;setBusy(true);try{const next=await legalReviewFetch(legalReviewUrl(propertyId,{offset:page.nextOffset,expectedHash:page.pageHash}));if(alive.current)setPage({...next,items:[...page.items,...next.items]})}catch(e){if(alive.current){setError(errorText(e));setPage(null);setDetail(null);setEditing(false)}}finally{if(alive.current)setBusy(false)}}
 function change(next:LegalDraft){setDraft(next);setConfirmed(false)}
 async function save(operation:'save'|'approve'|'reject'|'withdraw'){
  if(!page?.canManage||pending||busy||operation!=='save'&&!detail)return
  const command:LegalWrite=operation==='save'?{propertyId,operation,expectedStateHash:detail?.stateHash||page.stateHash,sourceVersionId:detail?.version.id||null,draft,reason}:{propertyId,operation,expectedStateHash:detail!.stateHash,versionId:detail!.version.id,versionHash:detail!.versionHash,confirmed:true,reason}
  setBusy(true);setError('');setNotice('')
  try{const result=await postLegal(command);if(!alive.current)return;setUnsaved(null);await reload();if(!alive.current)return;await select(result.versionId);if(!alive.current)return;setNotice(`Legal decision saved. ${result.staleReadinessCount} readiness checks need a new review.`);if(operation==='approve'||operation==='withdraw')window.dispatchEvent(new CustomEvent('p11:onboarding-evidence-changed',{detail:{propertyId}}))}catch(e){if(alive.current){setError(errorText(e));setPending(pendingLegal(propertyId));if(e instanceof Error&&'status'in e&&Number(e.status)===409){setUnsaved(draft);setDetail(null);setEditing(false)}if(e instanceof Error&&'status'in e&&Number(e.status)===403){setPage(null);setDetail(null);setEditing(false)}}}finally{if(alive.current)setBusy(false)}
 }
 async function recover(cancel=false){if(!pending)return;setBusy(true);setError('');try{const result=await legalReviewFetch(cancel?'/api/onboarding/legal':legalReviewUrl(propertyId,{kind:'decision',decisionId:pending.id}),cancel?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId,requestId:pending.id,operation:'cancel_unused',inputHash:pending.hash,reason:'Stop the unused legal request after checking its saved result'})}:undefined);if(result.propertyId!==propertyId||result.decisionId!==pending.id||!['ready','replayed','cancelled'].includes(result.state))throw new Error('The saved legal decision could not be verified.');clearPendingLegal(propertyId,pending.id);if(!alive.current)return;setPending(null);await reload();if(!alive.current)return;if(result.versionId)await select(result.versionId);if(!alive.current)return;setNotice(result.state==='cancelled'?'Unused legal decision cancelled.':'Saved legal decision recovered.');window.dispatchEvent(new CustomEvent('p11:onboarding-evidence-changed',{detail:{propertyId}}))}catch(e){if(alive.current)setError(errorText(e))}finally{if(alive.current)setBusy(false)}}
 async function loadHistory(more=false){setBusy(true);setError('');try{const h=await legalReviewFetch(legalReviewUrl(propertyId,{kind:'history',offset:more?history?.nextOffset??0:0,expectedHash:more?history?.pageHash:undefined}));if(alive.current)setHistory({...h,items:more?[...history!.items,...h.items]:h.items})}catch(e){if(alive.current){setError(errorText(e));setHistory(null)}}finally{if(alive.current)setBusy(false)}}
 async function showDecision(id:string){setBusy(true);setHistoryDetail(null);try{const d=await legalReviewFetch(legalReviewUrl(propertyId,{kind:'history_detail',decisionId:id}));if(alive.current)setHistoryDetail(d.decision)}catch(e){if(alive.current)setError(errorText(e))}finally{if(alive.current)setBusy(false)}}
 const enabled=!!page?.canManage&&!busy&&!pending,dirty=!!detail&&JSON.stringify(draft)!==JSON.stringify(detail.draft),reviewable=enabled&&!!detail&&!dirty&&confirmed&&reason.trim().length>=3
 const before=historyDetail?.before_state as Record<string,unknown>|undefined,after=historyDetail?.after_state as Record<string,unknown>|undefined,beforeDraft=rowDraft(before?.selectedVersion),afterDraft=rowDraft(after?.version)
 return<section aria-label="Reviewed legal and disclosure versions" className="rounded-xl border border-slate-200 bg-white p-5 text-slate-900 space-y-4">
  <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-semibold">Legal and disclosure review</h3><p className="mt-1 text-sm text-slate-600">Save supplied statements as drafts, then approve the exact saved version for use. Saving a draft leaves the current approval in place. Approval records your review; it does not publish a website or establish legal compliance.</p></div><button className={buttonClass} disabled={busy} onClick={()=>void reload()}>Reload legal versions</button></div>
  {error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-md bg-green-50 p-3 text-green-800">{notice}</p>}{busy&&<p role="status">Loading or saving legal review…</p>}
  {pending&&<div className="rounded-md border border-amber-300 bg-amber-50 p-3 space-y-2"><p>A legal decision is unconfirmed. Check its saved result before another change.</p><div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void recover()}>Check saved legal decision</button><button className={buttonClass} disabled={busy} onClick={()=>void recover(true)}>Cancel unused legal decision</button></div><p className="text-sm">Only an unused request is cancelled. A saved approval is recovered.</p></div>}
  {unsaved&&<details><summary>Your unsaved legal draft for comparison</summary><DraftSummary draft={unsaved}/></details>}
  {page&&<><p>{page.activeVersionId?'An effective approved version is available.':'No effective approved version is available.'} {page.approvedCount} versions currently marked approved.</p>{page.approvedCount>1&&<p className="text-amber-800">Earlier approvals need reconciliation. Approving a new exact draft replaces every prior approval; withdrawing approval clears them all.</p>}<div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={!enabled} onClick={()=>{setDetail(null);setDraft(emptyLegalDraft());setEditing(true);setReason('');setConfirmed(false);setNotice('')}}>New legal draft</button><button className={buttonClass} disabled={busy} onClick={()=>void loadHistory()}>Legal decision history</button></div>{!page.canManage&&<p>View only. A property manager can save and review legal versions.</p>}<ul className="divide-y rounded-md border">{page.items.map(v=><li key={v.id}><button className="w-full p-3 text-left disabled:opacity-50" disabled={busy||!!pending} onClick={()=>void select(v.id)}><span className="block font-medium">Legal version {v.version} · {v.status}{page.activeVersionId===v.id?' · Current effective approval':''}</span><span className="text-sm">{v.legalEntityName||'Unnamed entity'} · {v.recorded?'Recorded review':'Earlier version; no retained decision'} · {v.effectiveAt||'Effective time not set'}</span></button></li>)}</ul><p className="text-sm">Showing {page.items.length} of {page.total} legal versions.</p>{page.nextOffset!==null&&<button className={buttonClass} disabled={busy} onClick={()=>void more()}>Load more legal versions</button>}</>}
  {editing&&<div aria-label="Selected legal version" className="space-y-4 border-t pt-4"><h4 className="font-semibold">{detail?`Legal version ${detail.version.version} · ${detail.version.status}`:'New legal draft'}</h4>{detail&&!detail.recorded&&<p>This earlier version has no retained decision history. Saving creates a new recorded draft and preserves the earlier content.</p>}<p className="text-sm">Changes are saved as a new draft. Effective and source review times below use UTC; source review times are supplied provenance, separate from the person and time recorded for approval.</p>
   <fieldset disabled={!enabled} className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><label>Jurisdiction<input aria-label="Legal jurisdiction" className={inputClass} value={draft.jurisdiction} maxLength={200} onChange={e=>change({...draft,jurisdiction:e.target.value})}/></label><label>Legal entity<input aria-label="Legal entity name" className={inputClass} value={draft.legalEntityName} maxLength={300} onChange={e=>change({...draft,legalEntityName:e.target.value})}/></label><label>Effective time (UTC)<input aria-label="Legal effective time (UTC)" type="datetime-local" className={inputClass} value={utcInput(draft.effectiveAt)} onChange={e=>change({...draft,effectiveAt:fromUtc(e.target.value)})}/></label></div>
   {legalDocumentKeys.map(k=><details key={k} className="rounded-md border p-3"><summary className="font-medium">{legalDocumentLabels[k]} · {draft.documents[k]?.text?.length||0} characters</summary><div className="mt-3 space-y-3"><label className="block">Supplied text<textarea aria-label={legalDocumentLabels[k]+' text'} className={inputClass} rows={5} maxLength={100000} value={draft.documents[k]?.text||''} onChange={e=>change({...draft,documents:{...draft.documents,[k]:{...draft.documents[k],text:e.target.value}}})}/></label><label className="block">Source link<input aria-label={legalDocumentLabels[k]+' source link'} className={inputClass} type="url" value={draft.documents[k]?.sourceUrl||''} onChange={e=>change({...draft,documents:{...draft.documents,[k]:{...draft.documents[k],sourceUrl:e.target.value}}})}/></label><label className="block">Reported source review time (UTC)<input aria-label={legalDocumentLabels[k]+' reported review time (UTC)'} className={inputClass} type="datetime-local" value={utcInput(draft.documents[k]?.reviewedAt)} onChange={e=>change({...draft,documents:{...draft.documents,[k]:{...draft.documents[k],reviewedAt:fromUtc(e.target.value)}}})}/></label></div></details>)}
   <div className="space-y-3"><h5 className="font-medium">Additional source references</h5>{draft.sourceReferences.map((reference,index)=><div key={index} className="rounded-md border p-3"><label>Source label<input aria-label={`Legal source ${index+1} label`} className={inputClass} value={typeof reference.sourceType==='string'?reference.sourceType:''} onChange={e=>change({...draft,sourceReferences:draft.sourceReferences.map((r,i)=>i===index?{...r,sourceType:e.target.value}:r)})}/></label><label>Source link<input aria-label={`Legal source ${index+1} link`} className={inputClass} value={typeof reference.sourceUrl==='string'?reference.sourceUrl:''} onChange={e=>change({...draft,sourceReferences:draft.sourceReferences.map((r,i)=>i===index?{...r,sourceUrl:e.target.value}:r)})}/></label><button type="button" className={buttonClass} onClick={()=>change({...draft,sourceReferences:draft.sourceReferences.filter((_,i)=>i!==index)})}>Remove source reference {index+1}</button></div>)}<button type="button" className={buttonClass} disabled={draft.sourceReferences.length>=200} onClick={()=>change({...draft,sourceReferences:[...draft.sourceReferences,{sourceType:'',sourceUrl:''}]})}>Add legal source reference</button></div>
   <label className="block">Reason for legal decision<textarea aria-label="Reason for legal decision" className={inputClass} value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>
   <label className="flex gap-2"><input type="checkbox" aria-label="Confirm exact saved legal decision" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the exact saved version, source details and intended approval change. Withdrawal clears all current approvals for this property.</label>
   </fieldset><div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={!enabled||reason.trim().length<3} onClick={()=>void save('save')}>Save new legal draft</button>{detail&&<><button className={buttonClass} disabled={!reviewable||!detail.isLatest||detail.version.status!=='draft'||!canApproveLegalDraft(detail.draft)} onClick={()=>void save('approve')}>Approve saved legal version</button><button className={buttonClass} disabled={!reviewable||!detail.isLatest||detail.version.status!=='draft'} onClick={()=>void save('reject')}>Reject saved legal draft</button><button className={buttonClass} disabled={!reviewable||detail.version.status!=='approved'} onClick={()=>void save('withdraw')}>Withdraw property legal approval</button></>}</div>{dirty&&<p className="text-sm">Save edited text as a new draft before approving it.</p>}{detail?.version.status==='draft'&&!canApproveLegalDraft(detail.draft)&&<p className="text-sm">Approval requires all seven statements, a jurisdiction, legal entity and an effective time that has arrived.</p>}
  </div>}
  {history&&<div aria-label="Legal decision history" className="border-t pt-4 space-y-3"><p>Showing {history.items.length} of {history.total} legal decisions.</p><ul>{history.items.map(d=><li key={d.id}><button className="w-full border-b py-3 text-left" disabled={busy} onClick={()=>void showDecision(d.id)}>{d.kind} · {new Date(d.createdAt).toLocaleString()} · {d.reason}<span className="block text-sm">Reviewed by {d.actorId}</span></button></li>)}</ul>{history.nextOffset!==null&&<button className={buttonClass} disabled={busy} onClick={()=>void loadHistory(true)}>Load more legal decisions</button>}{historyDetail&&<div aria-label="Saved legal decision details" className="grid gap-4 md:grid-cols-2"><div><h5 className="font-medium">Earlier selected version</h5>{beforeDraft?<DraftSummary draft={beforeDraft}/>:<p>No earlier selected version.</p>}</div><div><h5 className="font-medium">Resulting version</h5>{afterDraft&&<DraftSummary draft={afterDraft}/>}</div><p className="text-sm">{Array.isArray(after?.invalidatedReadiness)?after.invalidatedReadiness.length:0} saved readiness checks marked stale.</p></div>}</div>}
 </section>
}
