'use client'

import {useCallback,useEffect,useRef,useState} from 'react'
import type {ChecklistPage,ChecklistHistory,TaskDetail,TaskFields,TaskSnapshot,ChecklistDecision} from '@/utils/checklist/contracts'
import {checklistFetch,checklistUrl,postChecklist,pendingChecklist,clearPendingChecklist,type PendingChecklist,type ChecklistWrite} from '@/utils/checklist/client'
const blank:TaskFields={name:'',description:'',category:'general',priority:50,status:'pending',notes:'',blockedReason:''}
const statusLabels={pending:'Pending',in_progress:'In progress',completed:'Reported complete',blocked:'Blocked',skipped:'Skipped'}
const inputClass='mt-1 w-full rounded-md border border-slate-300 bg-white p-2 text-slate-900'
const buttonClass='rounded-md border border-slate-300 px-3 py-2 text-sm disabled:opacity-50'
function message(e:unknown){return e instanceof Error?e.message:'The checklist could not be confirmed.'}
function fromTask(snapshot:TaskSnapshot):TaskFields{const t=snapshot.task;return{name:t.task_name,description:t.description||'',category:t.category||'general',priority:t.priority??0,status:t.status||'pending',notes:t.notes||'',blockedReason:t.blocked_reason||''}}
function Snapshot({value}:{value:TaskSnapshot|null}){if(!value)return<p>No earlier task.</p>;const t=value.task;return<dl className="grid gap-2 text-sm"><dt>Task</dt><dd>{t.task_name}</dd><dt>Status</dt><dd>{t.status?statusLabels[t.status]:'Unknown'}{value.workspace?.archived?' · Archived':''}</dd><dt>Description</dt><dd className="whitespace-pre-wrap">{t.description||'None'}</dd><dt>Category / priority</dt><dd>{t.category||'Unknown'} / {t.priority??'Unknown'}</dd><dt>Notes</dt><dd className="whitespace-pre-wrap">{t.notes||'None'}</dd><dt>Blocker</dt><dd className="whitespace-pre-wrap">{t.blocked_reason||'None'}</dd><dt>Assigned person / due date</dt><dd>{t.assigned_to||'Unassigned'} / {t.due_date||'None'}</dd><dt>Completion recorded</dt><dd>{t.completed_at||'No timestamp'} · {t.completed_by||'No person recorded'}</dd><dt>Revision</dt><dd>{value.workspace?.revision??'Unrecorded legacy task'}</dd></dl>}
export function OnboardingChecklist({propertyId}:{propertyId:string}){
 const [list,setList]=useState<ChecklistPage|null>(null),[detail,setDetail]=useState<TaskDetail|null>(null),[fields,setFields]=useState<TaskFields>(blank),[creating,setCreating]=useState(false),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[history,setHistory]=useState<ChecklistHistory|null>(null),[decision,setDecision]=useState<ChecklistDecision|null>(null),[pending,setPending]=useState<PendingChecklist|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[staleDraft,setStaleDraft]=useState<TaskFields|null>(null)
 const alive=useRef(false),sequence=useRef(0)
 const invalidate=useCallback(()=>{alive.current=false;sequence.current++},[])
 const reload=useCallback(async()=>{const n=++sequence.current;setBusy(true);setError('');setList(null);setDetail(null);setCreating(false);setHistory(null);setDecision(null);try{const data=await checklistFetch(checklistUrl(propertyId));if(alive.current&&n===sequence.current){setList(data);setPending(pendingChecklist(propertyId))}}catch(e){if(alive.current&&n===sequence.current)setError(message(e))}finally{if(alive.current&&n===sequence.current)setBusy(false)}},[propertyId])
 useEffect(()=>{alive.current=true;setPending(pendingChecklist(propertyId));void reload();return invalidate},[propertyId,reload,invalidate])
 async function selectTask(id:string){const n=++sequence.current;setBusy(true);setError('');setDetail(null);setCreating(false);setHistory(null);setDecision(null);try{const data=await checklistFetch(checklistUrl(propertyId,{kind:'task',taskId:id}));if(alive.current&&n===sequence.current){setDetail(data);setFields(fromTask(data.snapshot));setReason('');setConfirmed(false)}}catch(e){if(alive.current&&n===sequence.current)setError(message(e))}finally{if(alive.current&&n===sequence.current)setBusy(false)}}
 async function moreTasks(){if(!list||list.nextOffset===null)return;setBusy(true);try{const page=await checklistFetch(checklistUrl(propertyId,{offset:list.nextOffset,expectedHash:list.pageHash}));if(alive.current)setList({...page,items:[...list.items,...page.items]})}catch(e){if(alive.current){setError(message(e));setList(null);setDetail(null)}}finally{if(alive.current)setBusy(false)}}
 async function loadHistory(more=false){if(!detail)return;setBusy(true);setError('');try{const page=await checklistFetch(checklistUrl(propertyId,{kind:'history',taskId:detail.snapshot.task.id,offset:more?history?.nextOffset??0:0,expectedHash:more?history?.pageHash:undefined}));if(alive.current)setHistory({...page,items:more?[...history!.items,...page.items]:page.items})}catch(e){if(alive.current){setError(message(e));setHistory(null)}}finally{if(alive.current)setBusy(false)}}
 async function save(operation:'create'|'save'|'archive'|'restore'){
  if(!list?.canManage||pending||(!detail&&operation!=='create'))return
  const command:ChecklistWrite=operation==='create'?{propertyId,operation,fields,reason,confirmed}:operation==='save'?{propertyId,operation,taskId:detail!.snapshot.task.id,expectedHash:detail!.sourceHash,fields,reason,confirmed}:{propertyId,operation,taskId:detail!.snapshot.task.id,expectedHash:detail!.sourceHash,reason}
  setBusy(true);setError('');setNotice('')
  try{const result=await postChecklist(command);if(!alive.current)return;setStaleDraft(null);await reload();if(!alive.current)return;setNotice('Checklist decision saved. Verified readiness is unchanged.');await selectTask(result.taskId)}catch(e){if(alive.current){setError(message(e));setPending(pendingChecklist(propertyId));if(e instanceof Error&&'status'in e&&Number(e.status)===403){setList(null);setDetail(null);setCreating(false)}if(e instanceof Error&&'status'in e&&Number(e.status)===409){setStaleDraft(fields);setDetail(null);setCreating(false)}}}finally{if(alive.current)setBusy(false)}
 }
 async function recover(cancel=false){if(!pending)return;setBusy(true);setError('');setNotice('');try{const result=await checklistFetch(cancel?'/api/community/tasks':checklistUrl(propertyId,{kind:'decision',decisionId:pending.id}),cancel?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId,requestId:pending.id,operation:'cancel_unused',inputHash:pending.hash,reason:'Cancel the unused checklist request after checking its saved result'})}:undefined);if(result.propertyId!==propertyId||result.decisionId!==pending.id||!['ready','replayed','cancelled'].includes(result.state))throw new Error('The saved checklist decision could not be verified.');clearPendingChecklist(propertyId,pending.id);if(!alive.current)return;setPending(null);await reload();if(!alive.current)return;setNotice(result.state==='cancelled'?'Unused checklist decision cancelled.':'Saved checklist decision recovered.');if(result.taskId)await selectTask(result.taskId)}catch(e){if(alive.current)setError(message(e))}finally{if(alive.current)setBusy(false)}}
 const editable=!!list?.canManage&&!busy&&!pending,archived=!!detail?.snapshot.workspace?.archived
 function update<K extends keyof TaskFields>(key:K,value:TaskFields[K]){setFields(old=>({...old,[key]:value}));setConfirmed(false)}
 return<section aria-label="Reviewed property checklist" className="rounded-xl border border-slate-200 bg-white p-5 text-slate-900 space-y-4">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Property checklist</h2><p className="mt-1 text-sm text-slate-600">Track reported progress and retain the reason for each change. Completed tasks do not verify connections, approve a launch, publish knowledge or authorize training.</p></div><button className={buttonClass} disabled={busy} onClick={()=>void reload()}>Reload checklist</button></div>
  {error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-md bg-green-50 p-3 text-green-800">{notice}</p>}
  {pending&&<div className="rounded-md border border-amber-300 bg-amber-50 p-3 space-y-2"><p>A checklist decision is unconfirmed. Check its saved result before making another change.</p><div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={busy} onClick={()=>void recover()}>Check saved checklist decision</button><button className={buttonClass} disabled={busy} onClick={()=>void recover(true)}>Cancel unused checklist decision</button></div><p className="text-sm">Cancellation only stops an unused request. An already saved change is recovered.</p></div>}
  {staleDraft&&<details className="rounded-md border p-3"><summary>Your unsaved changes for comparison</summary><p className="text-sm">Reload and select the current task before editing again.</p><dl>{Object.entries(staleDraft).map(([key,value])=><div key={key}><dt className="font-medium">{key}</dt><dd className="whitespace-pre-wrap break-words">{String(value)}</dd></div>)}</dl></details>}
  {busy&&<p role="status">Loading or saving the checklist…</p>}
  {list&&<>
   <p>{list.stats.completed} of {list.stats.total} active tasks reported complete · {list.stats.blocked} blocked · {list.stats.skipped} skipped · {list.stats.archived} archived.</p>
   <nav aria-label="Checklist evidence workflows" className="flex flex-wrap gap-4 text-sm text-blue-700"><a href="/dashboard/properties">Property details and contacts</a><a href="/dashboard/community?knowledgeSource=review">Knowledge Base</a><a href="/dashboard/settings">Connection settings</a></nav>
   {!list.canManage&&<p>View only. A property manager can record changes.</p>}
   <button className={buttonClass} disabled={!editable} onClick={()=>{setCreating(true);setDetail(null);setFields(blank);setReason('');setConfirmed(false);setHistory(null);setDecision(null);setError('');setNotice('')}}>Add checklist task</button>
   <ul className="divide-y rounded-md border">{list.items.map(t=><li key={t.id}><button className="w-full p-3 text-left disabled:opacity-50" disabled={busy||!!pending} onClick={()=>void selectTask(t.id)}><span className="block font-medium">{t.task_name}</span><span className="text-sm text-slate-600">{t.archived?'Archived · ':''}{t.status?statusLabels[t.status]:'Unknown'} · {t.recorded?'Recorded history':'Earlier task; no recorded review yet'}</span></button></li>)}</ul>
   <p className="text-sm">Showing {list.items.length} of {list.total} tasks, including archived tasks.</p>{list.nextOffset!==null&&<button className={buttonClass} disabled={busy||!!pending} onClick={()=>void moreTasks()}>Load more checklist tasks</button>}
  </>}
  {(creating||detail)&&<div aria-label="Selected checklist task" className="space-y-4 border-t pt-4">
   <h3 className="font-semibold">{creating?'New task':detail!.snapshot.task.task_name}{archived?' · Archived':''}</h3>
   {detail&&!detail.snapshot.workspace&&<p className="text-sm">Earlier task: its existing details will be retained as the first before-state when you record a change. Older changes have no recorded history.</p>}
   {detail&&<p className="text-sm">Saved revision {detail.snapshot.workspace?.revision??0}. Assignment, due date and other retained metadata are preserved by this editor.</p>}
   <fieldset disabled={!editable||archived} className="grid gap-4 sm:grid-cols-2">
    <label className="sm:col-span-2">Task name<input className={inputClass} value={fields.name} maxLength={200} onChange={e=>update('name',e.target.value)}/></label>
    <label className="sm:col-span-2">Task description<textarea aria-label="Task description" className={inputClass} value={fields.description} maxLength={4000} onChange={e=>update('description',e.target.value)}/></label>
    <label>Task category<select className={inputClass} value={fields.category} onChange={e=>update('category',e.target.value as TaskFields['category'])}>{['setup','documents','integrations','billing','training','general'].map(s=><option key={s} value={s}>{s==='training'?'Training (legacy category only)':s}</option>)}</select></label>
    <label>Task priority (0–100)<input type="number" className={inputClass} min={0} max={100} value={fields.priority} onChange={e=>update('priority',Number(e.target.value))}/></label>
    <label>Reported task status<select className={inputClass} value={fields.status} disabled={creating} onChange={e=>update('status',e.target.value as TaskFields['status'])}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label>Task blocker<textarea aria-label="Task blocker" className={inputClass} value={fields.blockedReason} maxLength={4000} onChange={e=>update('blockedReason',e.target.value)}/></label>
    <label className="sm:col-span-2">Task notes<textarea aria-label="Task notes" className={inputClass} value={fields.notes} maxLength={4000} onChange={e=>update('notes',e.target.value)}/></label>
   </fieldset>
   <label className="block">Reason for checklist change<textarea aria-label="Reason for checklist change" className={inputClass} disabled={!editable} value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>
   {!archived&&fields.status==='completed'&&<label className="flex gap-2"><input type="checkbox" disabled={!editable} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this reports progress and does not verify readiness or enable a service.</label>}
   <div className="flex flex-wrap gap-2">{!archived&&<button className={buttonClass} disabled={!editable||reason.trim().length<3||!fields.name.trim()||fields.status==='completed'&&!confirmed||fields.status==='blocked'&&fields.blockedReason.trim().length<3} onClick={()=>void save(creating?'create':'save')}>{creating?'Create pending task':'Save checklist change'}</button>}{detail&&<><button className={buttonClass} disabled={!editable||reason.trim().length<3} onClick={()=>void save(archived?'restore':'archive')}>{archived?'Restore checklist task':'Archive checklist task'}</button><button className={buttonClass} disabled={busy} onClick={()=>void loadHistory()}>Checklist task history</button></>}</div>
   {detail&&<details><summary>Current saved task</summary><Snapshot value={detail.snapshot}/></details>}
   {history&&<div aria-label="Checklist task history" className="space-y-3"><p>Showing {history.items.length} of {history.total} decisions.</p>{history.total===0&&<p>No recorded decisions for this earlier task.</p>}<ul>{history.items.map(d=><li key={d.id}><button className="w-full border-b py-3 text-left" onClick={()=>setDecision(d)}><span className="block">{d.kind.replaceAll('_',' ')} · {new Date(d.created_at).toLocaleString()}</span><span className="block text-sm">{d.origin==='default_setup'?'System: property setup':d.origin==='property_setup'?'Property setup completed by':'Reported by'} {d.actor_id||''} · {d.input.reason}</span></button></li>)}</ul>{history.nextOffset!==null&&<button className={buttonClass} disabled={busy} onClick={()=>void loadHistory(true)}>Load more checklist decisions</button>}{decision&&<div aria-label="Checklist decision details"><p className="font-medium">{decision.input.reason}</p><div className="grid gap-6 md:grid-cols-2"><div><h4 className="font-semibold">Before</h4><Snapshot value={decision.before_state}/></div><div><h4 className="font-semibold">After</h4><Snapshot value={decision.after_state}/></div></div></div>}</div>}
  </div>}
 </section>
}
