'use client'
import {useEffect,useRef,useState,type ReactNode}from 'react'
import Link from 'next/link'
import {usePropertyContext}from '@/components/layout/PropertyContext'
import {PROPERTY_TYPE_OPTIONS}from '@/utils/property-types'
import {CONNECTION_PLATFORMS,newSetupContact,propertySetupSaveSchema,type ConnectionRequest,type SetupChange,type SetupContact,type SetupHistoryDetail,type SetupSnapshot,type SetupWorkspace}from '@/utils/property-setup/contracts'
import {savePropertySetup}from '@/utils/property-setup/client'
const box='rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900'
const button='rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium disabled:opacity-50 dark:border-slate-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500'
const input='mt-1 w-full min-w-0 rounded-lg border border-slate-300 bg-white p-2 text-sm text-slate-900 dark:border-slate-600 dark:bg-slate-950 dark:text-slate-100'
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block min-w-0 text-sm font-medium">{label}{children}</label>}
function Text({label,value,onChange,area=false,type='text'}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean;type?:string}){return <Field label={label}>{area?<textarea aria-label={label} rows={3} className={input} value={value} onChange={e=>onChange(e.target.value)}/>:<input aria-label={label} className={input} type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</Field>}
const date=(value:string)=>new Date(value).toLocaleString()
const sections=(v:string[])=>v.map(k=>({profile:'Property facts',contacts:'Contacts',connectionRequests:'Connection plans'}[k]||k)).join(', ')||'No changed values'
function Snapshot({title,value}:{title:string;value:SetupSnapshot}){const p=value.profile;return <section aria-label={title} className="min-w-0 space-y-3 rounded-lg bg-slate-50 p-4 text-sm dark:bg-slate-950"><h3 className="font-semibold">{title}</h3><dl className="space-y-2 break-words">{Object.entries({Name:p.name,Classification:p.propertyType||'Not specified',Address:Object.values(p.address).filter(Boolean).join(', ')||'Not specified',Website:p.websiteUrl||'Not specified','Additional websites':p.additionalUrls.join('\n')||'None','Units or homes':p.unitCount??'Unknown','Year built':p.yearBuilt??'Unknown',Amenities:p.amenities.join(', ')||'None','Special features':p.specialFeatures.join(', ')||'None','Brand voice':p.brandVoice||'Not specified','Audience notes':p.targetAudience||'Not specified'}).map(([k,v])=><div key={k}><dt className="font-medium">{k}</dt><dd className="whitespace-pre-wrap text-slate-600 dark:text-slate-300">{v}</dd></div>)}</dl><h4 className="font-semibold">Contacts ({value.contacts.length})</h4>{value.contacts.map(c=><div key={c.id} className="break-words border-t border-slate-200 pt-2 dark:border-slate-700"><p>{c.name} · {c.type}{c.isPrimary?' · Primary recipient':''}</p><p>{c.email} · {c.phone||'No phone'}</p><p>{c.role||'No role specified'}</p><p>{Object.values(c.billingAddress).filter(Boolean).join(', ')}</p><p>{c.billingMethod||'No billing method'}{c.needsW9?' · W-9 requested':''}</p>{c.specialInstructions&&<p className="whitespace-pre-wrap">{c.specialInstructions}</p>}</div>)}<h4 className="font-semibold">Connection plans ({value.connectionRequests.length})</h4>{value.connectionRequests.map(c=><div key={c.platform} className="break-words"><p>{CONNECTION_PLATFORMS[c.platform]} · {c.accountName||'Account not named'} · {c.accountId||'No account reference'}</p><p className="whitespace-pre-wrap">{c.notes}</p></div>)}</section>}
function ContactEditor({contact,index,onChange,onRemove}:{contact:SetupContact;index:number;onChange:(p:Partial<SetupContact>)=>void;onRemove:()=>void}){const prefix=`Contact ${index+1}`;return <fieldset className="min-w-0 space-y-3 rounded-lg border border-slate-200 p-4 dark:border-slate-700"><legend className="px-2 font-medium">{prefix}{contact.name?` · ${contact.name}`:''}</legend><div className="grid gap-3 sm:grid-cols-2"><Text label={`${prefix} name`} value={contact.name} onChange={name=>onChange({name})}/><Text label={`${prefix} email`} type="email" value={contact.email} onChange={email=>onChange({email})}/><Field label={`${prefix} type`}><select aria-label={`${prefix} type`} className={input} value={contact.type} onChange={e=>onChange({type:e.target.value as SetupContact['type'],isPrimary:e.target.value==='primary'})}>{['primary','secondary','billing','emergency'].map(v=><option key={v} value={v}>{v}</option>)}</select></Field><Text label={`${prefix} phone`} value={contact.phone} onChange={phone=>onChange({phone})}/><Text label={`${prefix} role`} value={contact.role} onChange={role=>onChange({role})}/><label className="self-end py-2 text-sm"><input type="checkbox" aria-label={`${prefix} primary recipient`} checked={contact.isPrimary} onChange={e=>onChange({isPrimary:e.target.checked})}/> Primary recipient</label></div><details><summary className="cursor-pointer text-sm font-medium">Billing and contact instructions</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{(['street','city','state','zip']as const).map(k=><Text key={k} label={`${prefix} billing ${k}`} value={contact.billingAddress[k]} onChange={v=>onChange({billingAddress:{...contact.billingAddress,[k]:v}})}/>)}<Field label={`${prefix} billing method`}><select className={input} aria-label={`${prefix} billing method`} value={contact.billingMethod} onChange={e=>onChange({billingMethod:e.target.value as SetupContact['billingMethod']})}>{Object.entries({'':'Not specified',ops_merchant:'Ops Merchant',nexus:'Nexus',ach:'ACH',check:'Check',credit_card:'Credit card',other:'Other'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><label className="self-end py-2"><input type="checkbox" aria-label={`${prefix} needs W-9`} checked={contact.needsW9} onChange={e=>onChange({needsW9:e.target.checked})}/> W-9 requested</label><div className="sm:col-span-2"><Text label={`${prefix} special instructions`} area value={contact.specialInstructions} onChange={specialInstructions=>onChange({specialInstructions})}/></div></div></details><button type="button" className={button} onClick={onRemove}>Remove {prefix.toLowerCase()} from draft</button></fieldset>}
export function PropertySetupEditor({propertyId}:{propertyId:string}){
 const{currentProperty,refreshProperties}=usePropertyContext()
 const[workspace,setWorkspace]=useState<SetupWorkspace|null>(null),[draft,setDraft]=useState<SetupSnapshot|null>(null),[baseline,setBaseline]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState<string|null>(null),[readError,setReadError]=useState<string|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[reloadKey,setReloadKey]=useState(0),[receipt,setReceipt]=useState<{id:string;contextInvalidated:boolean}|null>(null),[comparison,setComparison]=useState<SetupWorkspace|null>(null),[reviewed,setReviewed]=useState(false),[history,setHistory]=useState<SetupChange[]>([]),[cursor,setCursor]=useState<string|null>(null),[detail,setDetail]=useState<SetupHistoryDetail|null>(null),[selectorFailed,setSelectorFailed]=useState(false),[confirmReplace,setConfirmReplace]=useState(false)
 const alive=useRef(true),readGeneration=useRef(0),detailGeneration=useRef(0)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 async function read(query='',signal?:AbortSignal){const r=await fetch(`/api/properties/${propertyId}/setup${query}`,{cache:'no-store',signal});const data=await r.json();if(!r.ok)throw new Error(data.error||'Saved property details could not be read.');if(data.propertyId!==propertyId||!data.snapshot||!Array.isArray(data.changes))throw new Error('The property response could not be verified.');return data as SetupWorkspace}
 function accept(data:SetupWorkspace){setWorkspace(data);setDraft(data.snapshot);setBaseline(data.snapshotHash);setHistory(data.changes);setCursor(data.nextCursor);setComparison(null);setReviewed(false);setReadError(null);setConfirmReplace(false);if(data.selected)setDetail(data.selected)}
 useEffect(()=>{const controller=new AbortController(),generation=++readGeneration.current;setLoading(true);setReadError(null);void read(new URLSearchParams(window.location.search).has('propertyChangeId')?`?changeId=${encodeURIComponent(new URLSearchParams(window.location.search).get('propertyChangeId')||'')}`:'',controller.signal).then(data=>{if(!controller.signal.aborted&&alive.current&&generation===readGeneration.current)accept(data)}).catch(e=>{if(!controller.signal.aborted&&alive.current)setReadError(e instanceof Error?e.message:'Property details are unavailable.')}).finally(()=>{if(!controller.signal.aborted&&alive.current)setLoading(false)});return()=>controller.abort()
 // The component is keyed by exact route property; reload intentionally replaces the accepted snapshot.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[propertyId,reloadKey])
 async function compareLatest(){setBusy(true);setError(null);try{const latest=await read();if(!alive.current)return;setComparison(latest);setReviewed(false)}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Latest details are unavailable.')}finally{if(alive.current)setBusy(false)}}
 async function save(){if(!draft||!workspace)return;const parsed=propertySetupSaveSchema.safeParse({...draft,profile:{...draft.profile,additionalUrls:draft.profile.additionalUrls.map(v=>v.trim()).filter(Boolean),amenities:draft.profile.amenities.map(v=>v.trim()).filter(Boolean),specialFeatures:draft.profile.specialFeatures.map(v=>v.trim()).filter(Boolean)},reason,expectedHash:baseline,requestId:'11111111-1111-1111-1111-111111111111'});if(!parsed.success){setError(parsed.error.issues[0]?.message||'Review the property details.');return}setBusy(true);setError(null);setReceipt(null);try{const{requestId,...payload}=parsed.data;void requestId;const saved=await savePropertySetup(propertyId,payload);if(!alive.current)return;setReceipt(saved);setReason('');try{const refreshed=await read();if(alive.current)accept(refreshed)}catch(e){if(alive.current)setReadError(`The change was saved. ${e instanceof Error?e.message:'Reload to view the current property.'}`)}if(alive.current)setSelectorFailed(!(await refreshProperties(propertyId)))}catch(e){if(alive.current)setError(e instanceof Error?e.message:'The save could not be confirmed. Retry the same draft.')}finally{if(alive.current)setBusy(false)}}
 async function more(){if(!cursor)return;setBusy(true);setError(null);try{const data=await read(`?cursor=${cursor}`);if(!alive.current)return;setHistory(v=>[...v,...data.changes.filter(c=>!v.some(x=>x.id===c.id))]);setCursor(data.nextCursor)}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Older changes are unavailable.')}finally{if(alive.current)setBusy(false)}}
 async function openChange(id:string){const generation=++detailGeneration.current;setBusy(true);setError(null);try{const data=await read(`?changeId=${id}`);if(alive.current&&generation===detailGeneration.current){setDetail(data.selected);const url=new URL(window.location.href);url.searchParams.set('propertyChangeId',id);window.history.replaceState(null,'',url)}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'The saved change is unavailable.')}finally{if(alive.current&&generation===detailGeneration.current)setBusy(false)}}
 function updateProfile(p:Partial<SetupSnapshot['profile']>){setDraft(d=>d?{...d,profile:{...d.profile,...p}}:d)}
 function updateContact(id:string,p:Partial<SetupContact>){setDraft(d=>d?{...d,contacts:d.contacts.map(c=>c.id===id?{...c,...p}:c)}:d)}
 function updateConnection(platform:ConnectionRequest['platform'],p:Partial<ConnectionRequest>){setDraft(d=>d?{...d,connectionRequests:d.connectionRequests.map(c=>c.platform===platform?{...c,...p}:c)}:d)}
 const dirty=!!draft&&!!workspace&&JSON.stringify(draft)!==JSON.stringify(workspace.snapshot)
 return <section aria-label="Property editor" className="mx-auto max-w-5xl space-y-6 p-4 text-slate-900 sm:p-8 dark:text-slate-100"><header><Link className="text-sm text-indigo-600 dark:text-indigo-300" href="/dashboard/properties">All properties</Link><h1 className="mt-3 text-3xl font-semibold">Edit property</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Save property facts, contacts and connection plans together, with a reason and retained history.</p>{workspace&&<p className="mt-2 font-medium">Editing {workspace.snapshot.profile.name}</p>}{currentProperty.id&&currentProperty.id!==propertyId&&<p role="status" className="mt-2 text-amber-700 dark:text-amber-300">The selector shows {currentProperty.name}; this editor still belongs to {workspace?.snapshot.profile.name||'the property in its address'}. <Link className="underline" href={`/dashboard/properties/${currentProperty.id}/edit`}>Open the selected property’s editor</Link></p>}</header>
 {loading&&<p role="status">Loading saved property details…</p>}{readError&&<div role="alert" className={box}><p>{readError}</p><button className={`${button} mt-3`} disabled={busy||loading} onClick={()=>setReloadKey(k=>k+1)}>Retry reading saved property</button></div>}
 {receipt&&<div role="status" className="rounded-xl border border-emerald-300 bg-emerald-50 p-4 text-emerald-950"><p>Property change saved. {receipt.contextInvalidated?'Assistant facts need a refresh before the revised information is served.':'Connection plans remain separate from actual authorization.'}</p><button className={`${button} mt-2`} disabled={busy} onClick={()=>void openChange(receipt.id)}>View this saved change</button></div>}
 {selectorFailed&&<div role="alert" className={box}>The property change is saved, but the console selector could not refresh. <button className={button} onClick={()=>void refreshProperties(propertyId).then(ok=>setSelectorFailed(!ok))}>Refresh property selector</button></div>}
 {error&&<p role="alert" className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-amber-950">{error}</p>}
 {workspace&&draft&&<><form aria-label="Edit property details" onSubmit={e=>{e.preventDefault();void save()}} className="space-y-5"><fieldset disabled={!workspace.canEdit||busy||loading||!!readError} className="min-w-0 space-y-5">
 {!workspace.canEdit&&<p role="status">Your account can read this property. A current manager can save changes.</p>}
 <section aria-label="Property facts" className={`${box} space-y-4`}><h2 className="text-xl font-semibold">Property facts</h2><div className="grid gap-4 sm:grid-cols-2"><Text label="Property name" value={draft.profile.name} onChange={name=>updateProfile({name})}/><Field label="Property classification"><select className={input} aria-label="Property classification" value={draft.profile.propertyType||''} onChange={e=>updateProfile({propertyType:e.target.value||null})}><option value="">Not specified</option>{draft.profile.propertyType&&!PROPERTY_TYPE_OPTIONS.some(o=>o.value===draft.profile.propertyType)&&<option value={draft.profile.propertyType}>Legacy classification: {draft.profile.propertyType}</option>}{PROPERTY_TYPE_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>{(['street','city','state','zip']as const).map(k=><Text key={k} label={`Property ${k}`} value={draft.profile.address[k]} onChange={v=>updateProfile({address:{...draft.profile.address,[k]:v}})}/>)}<Text label="Website address" value={draft.profile.websiteUrl} onChange={websiteUrl=>updateProfile({websiteUrl})}/><Text label="Units or homes" type="number" value={draft.profile.unitCount?.toString()??''} onChange={v=>updateProfile({unitCount:v===''?null:Number(v)})}/><Text label="Year built" type="number" value={draft.profile.yearBuilt?.toString()??''} onChange={v=>updateProfile({yearBuilt:v===''?null:Number(v)})}/></div><p className="text-sm text-slate-600 dark:text-slate-300">Classification does not determine rental or ownership terms. Review those separately in the <Link className="underline" href="/dashboard/community">property checklist</Link>. Website addresses are saved references; saving does not fetch their content.</p><Text label="Additional website addresses — one per line" area value={draft.profile.additionalUrls.join('\n')} onChange={v=>updateProfile({additionalUrls:v.split('\n')})}/><Text label="Amenities — one per line" area value={draft.profile.amenities.join('\n')} onChange={v=>updateProfile({amenities:v.split('\n')})}/><Text label="Special features — one per line" area value={draft.profile.specialFeatures.join('\n')} onChange={v=>updateProfile({specialFeatures:v.split('\n')})}/><details><summary className="cursor-pointer font-medium">Brand voice and audience notes</summary><div className="mt-3 space-y-3"><Text label="Brand voice" area value={draft.profile.brandVoice} onChange={brandVoice=>updateProfile({brandVoice})}/><Text label="Audience notes" area value={draft.profile.targetAudience} onChange={targetAudience=>updateProfile({targetAudience})}/></div></details></section>
 <section aria-label="Property contacts" id="contacts" className={`${box} space-y-4`}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">Contacts</h2><button type="button" className={button} disabled={draft.contacts.length>=100} onClick={()=>setDraft({...draft,contacts:[...draft.contacts,newSetupContact()]})}>Add contact to draft</button></div><p className="text-sm text-slate-600 dark:text-slate-300">Removing a contact takes effect when you save. Earlier values remain in private property history. Only one primary contact or recipient is supported.</p>{draft.contacts.length===0&&<p>No contacts in this draft. Saving will leave this property without contacts.</p>}{draft.contacts.map((c,i)=><ContactEditor key={c.id} contact={c} index={i} onChange={p=>updateContact(c.id,p)} onRemove={()=>setDraft({...draft,contacts:draft.contacts.filter(x=>x.id!==c.id)})}/>)}</section>
 <section aria-label="Connection plans" className={`${box} space-y-4`}><h2 className="text-xl font-semibold">Connection plans</h2><p className="text-sm text-slate-600 dark:text-slate-300">Record which services you want to set up. These are planning notes; they do not connect accounts, change credentials or verify access. Keep passwords and tokens out of notes.</p><Field label="Add connection plan"><select aria-label="Add connection plan" className={input} value="" onChange={e=>{if(e.target.value)setDraft({...draft,connectionRequests:[...draft.connectionRequests,{platform:e.target.value as ConnectionRequest['platform'],accountId:'',accountName:'',notes:''}]})}}><option value="">Choose a service</option>{Object.entries(CONNECTION_PLATFORMS).filter(([k])=>!draft.connectionRequests.some(c=>c.platform===k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>{draft.connectionRequests.map(c=><fieldset key={c.platform} className="space-y-3 rounded-lg border border-slate-200 p-4 dark:border-slate-700"><legend>{CONNECTION_PLATFORMS[c.platform]}</legend><Text label={`${CONNECTION_PLATFORMS[c.platform]} account reference`} value={c.accountId} onChange={accountId=>updateConnection(c.platform,{accountId})}/><Text label={`${CONNECTION_PLATFORMS[c.platform]} account name`} value={c.accountName} onChange={accountName=>updateConnection(c.platform,{accountName})}/><Text label={`${CONNECTION_PLATFORMS[c.platform]} setup notes`} area value={c.notes} onChange={notes=>updateConnection(c.platform,{notes})}/><button type="button" className={button} onClick={()=>setDraft({...draft,connectionRequests:draft.connectionRequests.filter(x=>x.platform!==c.platform)})}>Remove {CONNECTION_PLATFORMS[c.platform]} plan from draft</button></fieldset>)}</section>
 <div className={`${box} space-y-3`}><Text label="Reason for this property change" area value={reason} onChange={setReason}/><p className="text-sm text-slate-600 dark:text-slate-300">Changes to facts make the assistant’s existing fact sheet stale until it is refreshed. Existing website releases, integrations and approved brand packages are not republished by this save.</p><div className="flex flex-wrap gap-3"><button type="submit" className="rounded-lg bg-indigo-600 px-4 py-2 font-medium text-white disabled:opacity-50" disabled={!dirty||busy}>{busy?'Saving or reading…':'Save property changes'}</button><button type="button" className={button} onClick={()=>void compareLatest()}>Compare latest saved details</button></div></div></fieldset></form>
 {comparison&&<section aria-label="Compare property changes" className={`${box} space-y-4`}><h2 className="text-xl font-semibold">Compare before continuing</h2><p className="text-sm">Your draft is preserved below. Review differences before choosing which values to save.</p><div className="grid gap-4 lg:grid-cols-2"><Snapshot title="Your unsaved draft" value={draft}/><Snapshot title="Latest saved property" value={comparison.snapshot}/></div><label className="block text-sm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I have reviewed the latest saved details and these differences.</label><div className="flex flex-wrap gap-3"><button className={button} disabled={!reviewed||busy} onClick={()=>{setBaseline(comparison.snapshotHash);setWorkspace(comparison);setComparison(null);setReviewed(false);setError(null)}}>Keep my draft against this reviewed version</button><button className={button} disabled={!reviewed||busy} onClick={()=>setConfirmReplace(true)}>Replace my draft with saved details</button></div>{confirmReplace&&<div role="alert"><p>This discards your unsaved draft values.</p><button className={`${button} mt-2`} onClick={()=>{accept(comparison);setReason('');setError(null)}}>Confirm replacing this draft</button></div>}</section>}
 <section aria-label="Existing connections" className={`${box} space-y-3`}><h2 className="text-xl font-semibold">Existing connection records</h2><p className="text-sm">These are recorded statuses, not a fresh provider check. <Link className="underline text-indigo-600 dark:text-indigo-300" href="/dashboard/integrations">Open integrations to verify or manage access</Link>.</p>{workspace.connections.length===0?<p>No connection records.</p>:<ul className="space-y-2">{workspace.connections.map(c=><li key={c.id} className="break-words">{CONNECTION_PLATFORMS[c.platform as keyof typeof CONNECTION_PLATFORMS]||c.platform} · {c.account_name||c.account_id||'Account not named'} · Recorded status: {c.status||'unknown'}</li>)}</ul>}<p className="text-sm">Assistant facts: {workspace.context?.status||'not prepared'}. <Link className="underline text-indigo-600 dark:text-indigo-300" href="/dashboard/lumaleasing">Review or refresh assistant facts</Link>.</p><p className="text-sm"><Link className="underline text-indigo-600 dark:text-indigo-300" href="/dashboard/community">Manage knowledge sources, offerings and the property checklist</Link>.</p></section>
 <section aria-label="Property change history" className={`${box} space-y-3`}><h2 className="text-xl font-semibold">Saved change history</h2><p className="text-sm">{workspace.total} retained changes. Earlier setup activity may predate this history.</p>{history.length===0?<p>No property changes recorded in this history.</p>:<ul className="space-y-3">{history.map(c=><li key={c.id}><button className="text-left text-indigo-600 underline dark:text-indigo-300" disabled={busy} onClick={()=>void openChange(c.id)}>{c.reason}</button><p className="text-xs text-slate-600 dark:text-slate-300">{date(c.createdAt)} · {c.actorName||c.actorId} · {sections(c.changedSections)}</p></li>)}</ul>}{cursor&&<button className={button} disabled={busy} onClick={()=>void more()}>Older property changes</button>}</section>
 {detail&&<section aria-label="Saved property change" className={`${box} space-y-3`}><h2 className="text-xl font-semibold">{detail.reason}</h2><p className="text-sm">Saved {date(detail.createdAt)} by {detail.actorName||detail.actorId}. {sections(detail.changedSections)}.</p><div className="grid gap-4 lg:grid-cols-2"><Snapshot title={detail.kind==='created'?'Initial property defaults':'Before this saved change'} value={detail.before}/><Snapshot title="After this saved change" value={detail.after}/></div><button className={button} onClick={()=>setDetail(null)}>Close saved change</button></section>}
 </>}
 </section>
}
