'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {readinessCapabilities,type ReadinessCapability,type ReadinessPage,type ReadinessDetail,type ReadinessHistory,type DomainReport} from '@/utils/readiness/contracts'
import {readinessReviewFetch as request,readinessReviewUrl as url,postReadiness,pendingReadiness,clearPendingReadiness,type PendingReadiness,type ReadinessWrite} from '@/utils/readiness/client'
const field='mt-1 w-full rounded-md border border-slate-300 bg-white p-2 text-slate-900',button='rounded-md border border-slate-300 px-3 py-2 text-sm disabled:opacity-50'
const domains:Record<string,string>={identityContact:'Property identity and contacts',brand:'Approved brand',assets:'Images and logo',propertyFacts:'Property facts',units:'Floor plans and pricing',neighborhood:'Neighborhood sources',legal:'Legal and disclosures',integrations:'Selected connections'}
const capabilities:Record<ReadinessCapability,string>={crm:'CRM lead delivery',tours:'Tour scheduling',chatbot:'Property chatbot',analytics:'Analytics and tag manager'}
const message=(e:unknown)=>e instanceof Error?e.message:'Readiness review is unavailable.'
const label=(key:string)=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ')
function Evidence({value}:{value:unknown}){const [count,setCount]=useState(20);if(value===null||value===undefined)return<span>Not supplied</span>;if(Array.isArray(value))return<div className="space-y-2"><p>{value.length} retained items</p>{value.slice(0,count).map((item,i)=><details className="rounded border p-2" key={i}><summary>Item {i+1}{item&&typeof item==='object'&&'name'in item?` · ${String(item.name)}`:''}</summary><Evidence value={item}/></details>)}{count<value.length&&<button className={button} onClick={()=>setCount(n=>n+20)}>Show more retained items</button>}</div>;if(typeof value==='object')return<dl className="space-y-2">{Object.entries(value).map(([k,v])=><div key={k}><dt className="font-medium capitalize">{label(k)}</dt><dd className="break-words whitespace-pre-wrap text-sm">{v&&typeof v==='object'?<details><summary>View retained details</summary><Evidence value={v}/></details>:String(v??'Not supplied')}</dd></div>)}</dl>;return<p className="break-words whitespace-pre-wrap text-sm">{String(value)}</p>}
function Reports({reports,propertyId}:{reports:Record<string,DomainReport>;propertyId:string}){return<div className="grid gap-3 sm:grid-cols-2">{Object.entries(reports).map(([key,r])=><div key={key} className="rounded border p-3"><h5 className="font-medium">{domains[key]||label(key)}</h5><p className="text-sm capitalize">{label(r.state)} · {r.approvalPolicy==='advisory'?'Advisory':r.approvalPolicy==='manager_override'?'Manager review allowed':'Required'}</p><ul className="mt-2 list-inside list-disc text-sm">{r.reasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul>{r.state!=='ready'&&<a className="mt-2 inline-block text-sm text-indigo-700 underline" href={key==='brand'?`/dashboard/brandforge/${propertyId}`:key==='identityContact'?'/dashboard/properties':key==='integrations'?'/dashboard/settings':'/dashboard/community'}>Review {domains[key]?.toLowerCase()||label(key)}</a>}</div>)}</div>}
type Invalidations={items:Array<{id:string;cause:string;previous_status:string;created_at:string;snapshot_id:string}>;total:number;nextOffset:number|null;pageHash:string}
export function ReadinessReviewWorkbench({propertyId,onChanged}:{propertyId:string;onChanged?:()=>void}){
 const [page,setPage]=useState<ReadinessPage|null>(null),[detail,setDetail]=useState<ReadinessDetail|null>(null),[selectedCapabilities,setCapabilities]=useState<ReadinessCapability[]>([]),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[override,setOverride]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<PendingReadiness|null>(null),[history,setHistory]=useState<ReadinessHistory|null>(null),[historyDetail,setHistoryDetail]=useState<Record<string,unknown>|null>(null),[invalidations,setInvalidations]=useState<Invalidations|null>(null)
 const alive=useRef(false),generation=useRef(0),invalidate=useCallback(()=>{alive.current=false;generation.current++},[])
 const reload=useCallback(async()=>{const g=++generation.current;setBusy(true);setError('');setPage(null);setDetail(null);setHistory(null);setHistoryDetail(null);setInvalidations(null);setConfirmed(false);setOverride(false);try{const p=await request(url(propertyId));if(alive.current&&g===generation.current){setPage(p);setPending(pendingReadiness(propertyId))}}catch(e){if(alive.current&&g===generation.current)setError(message(e))}finally{if(alive.current&&g===generation.current)setBusy(false)}},[propertyId])
 useEffect(()=>{alive.current=true;setPending(pendingReadiness(propertyId));void reload();return invalidate},[propertyId,reload,invalidate])
 useEffect(()=>{const changed=(event:Event)=>{if((event as CustomEvent<{propertyId:string}>).detail?.propertyId===propertyId)void reload()};window.addEventListener('p11:onboarding-evidence-changed',changed);return()=>window.removeEventListener('p11:onboarding-evidence-changed',changed)},[propertyId,reload])
 function fail(e:unknown){setError(message(e));if(e instanceof Error&&'status'in e&&Number(e.status)===403){setPage(null);setDetail(null)}}
 async function select(id:string){const g=++generation.current;setBusy(true);setError('');setDetail(null);setConfirmed(false);setOverride(false);try{const d=await request(url(propertyId,{kind:'snapshot',snapshotId:id}));if(alive.current&&g===generation.current){setDetail(d);setReason('');setCapabilities(d.snapshot.snapshot_payload.requestedCapabilities||[])}}catch(e){if(alive.current&&g===generation.current)fail(e)}finally{if(alive.current&&g===generation.current)setBusy(false)}}
 async function more(){if(!page||page.nextOffset===null)return;setBusy(true);try{const p=await request(url(propertyId,{offset:page.nextOffset,expectedHash:page.pageHash}));if(alive.current)setPage({...p,items:[...page.items,...p.items]})}catch(e){if(alive.current){fail(e);setPage(null);setDetail(null)}}finally{if(alive.current)setBusy(false)}}
 async function save(operation:'build'|'approve'|'reject'|'withdraw'){
  if(!page?.canManage||pending||busy||operation!=='build'&&(!detail||!detail.sourceHash))return
  const command:ReadinessWrite=operation==='build'?{propertyId,operation,enabledCapabilities:selectedCapabilities,reason}:{propertyId,operation,snapshotId:detail!.snapshot.id,snapshotHash:detail!.snapshotHash,sourceHash:detail!.sourceHash!,confirmed:true,allowManagerOverride:override,reason}
  setBusy(true);setError('');setNotice('');try{const r=await postReadiness(command);if(!alive.current)return;await reload();if(!alive.current)return;await select(r.snapshotId);if(!alive.current)return;setNotice(operation==='build'?(r.status==='approved'?'Current saved check recovered. Its earlier approval remains in place.':'Readiness check saved for review.'):'Readiness decision saved.');onChanged?.()}catch(e){if(alive.current){fail(e);setPending(pendingReadiness(propertyId));if(e instanceof Error&&'status'in e&&Number(e.status)===409){setDetail(null);setConfirmed(false);setOverride(false)}}}finally{if(alive.current)setBusy(false)}
 }
 async function recover(cancel=false){if(!pending)return;setBusy(true);setError('');try{const r=await request(cancel?'/api/onboarding/readiness':url(propertyId,{kind:'decision',decisionId:pending.id}),cancel?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId,requestId:pending.id,operation:'cancel_unused',inputHash:pending.hash,reason:'Stop the unused readiness request after checking its saved result'})}:undefined);if(r.propertyId!==propertyId||r.decisionId!==pending.id||!['ready','replayed','cancelled'].includes(r.state))throw new Error('The saved readiness decision could not be verified.');clearPendingReadiness(propertyId,pending.id);if(!alive.current)return;setPending(null);await reload();if(!alive.current)return;if(r.snapshotId)await select(r.snapshotId);if(!alive.current)return;setNotice(r.state==='cancelled'?'Unused readiness request cancelled.':'Saved readiness decision recovered.');onChanged?.()}catch(e){if(alive.current)fail(e)}finally{if(alive.current)setBusy(false)}}
 async function loadHistory(more=false){setBusy(true);setError('');try{const h=await request(url(propertyId,{kind:'history',offset:more?history?.nextOffset??0:0,expectedHash:more?history?.pageHash:undefined}));if(alive.current)setHistory({...h,items:more?[...history!.items,...h.items]:h.items})}catch(e){if(alive.current){fail(e);setHistory(null)}}finally{if(alive.current)setBusy(false)}}
 async function showDecision(id:string){setBusy(true);setHistoryDetail(null);try{const h=await request(url(propertyId,{kind:'history_detail',decisionId:id}));if(alive.current)setHistoryDetail(h.decision)}catch(e){if(alive.current)fail(e)}finally{if(alive.current)setBusy(false)}}
 async function loadInvalidations(more=false){setBusy(true);setError('');try{const h=await request(url(propertyId,{kind:'invalidations',offset:more?invalidations?.nextOffset??0:0,expectedHash:more?invalidations?.pageHash:undefined}));if(alive.current)setInvalidations({...h,items:more?[...invalidations!.items,...h.items]:h.items})}catch(e){if(alive.current){fail(e);setInvalidations(null)}}finally{if(alive.current)setBusy(false)}}
 const enabled=!!page?.canManage&&!busy&&!pending,reviewable=enabled&&!!detail?.sourceHash&&confirmed&&reason.trim().length>=3
 return<section aria-label="Recorded readiness review" className="rounded-xl border border-slate-200 bg-white p-5 text-slate-900 space-y-4">
  <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-semibold">Readiness review</h3><p className="mt-1 text-sm text-slate-600">Build a saved check of current property, brand, legal and selected connection facts. Review that exact check before approving it for use. Approval does not publish a site or activate a provider.</p></div><button className={button} disabled={busy} onClick={()=>void reload()}>Reload readiness checks</button></div>
  {error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-md bg-green-50 p-3 text-green-800">{notice}</p>}{busy&&<p role="status">Loading or saving readiness…</p>}
  {pending&&<div className="rounded-md border border-amber-300 bg-amber-50 p-3 space-y-2"><p>A readiness decision is unconfirmed. Check its saved result before another change.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void recover()}>Check saved readiness decision</button><button className={button} disabled={busy} onClick={()=>void recover(true)}>Cancel unused readiness request</button></div><p className="text-sm">Cancellation only stops an unused request. Saved decisions are recovered.</p></div>}
  {page&&<><fieldset disabled={!enabled} className="space-y-3"><legend className="font-medium">Connections to check</legend><div className="flex flex-wrap gap-4">{readinessCapabilities.map(c=><label className="flex gap-2" key={c}><input type="checkbox" checked={selectedCapabilities.includes(c)} onChange={e=>{setCapabilities(current=>e.target.checked?[...current,c]:current.filter(v=>v!==c));setConfirmed(false)}}/>{capabilities[c]}</label>)}</div><label className="block">Reason for readiness decision<textarea aria-label="Reason for readiness decision" className={field} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset><button className={button} disabled={!enabled||reason.trim().length<3} onClick={()=>void save('build')}>Build readiness check</button>{!page.canManage&&<p>View only. A property manager can build and review readiness.</p>}
  <ul className="divide-y rounded-md border">{page.items.map((s,i)=><li key={s.id}><button className="w-full p-3 text-left disabled:opacity-50" disabled={busy||!!pending} onClick={()=>void select(s.id)}><span className="block font-medium">Readiness check {i+1} · {s.status}{!s.eligibility.current?' · Needs current evidence':''}</span><span className="text-sm">{new Date(s.createdAt).toLocaleString()} · {s.recorded?'Recorded sources':'Earlier check; rebuild required'}</span></button></li>)}</ul><p className="text-sm">Showing {page.items.length} of {page.total} readiness checks.</p>{page.nextOffset!==null&&<button className={button} disabled={busy} onClick={()=>void more()}>Load more readiness checks</button>}<div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void loadHistory()}>Readiness decision history</button><button className={button} disabled={busy} onClick={()=>void loadInvalidations()}>Source change history</button></div></>}
  {detail&&<div aria-label="Selected readiness check" className="space-y-4 border-t pt-4"><h4 className="font-semibold">Saved readiness · {detail.snapshot.status}</h4><p className="text-sm">{detail.eligibility.current?'Saved sources still match the current property.':detail.eligibility.reason||'Source facts changed; build a new check.'}</p>{detail.snapshot.approved_at&&<p className="text-sm">Approval recorded by {detail.snapshot.approved_by} at {detail.snapshot.approved_at}.</p>}<Reports reports={detail.snapshot.domain_reports} propertyId={propertyId}/><details><summary>Exact saved source evidence</summary>{detail.sources?<Evidence value={detail.sources}/>:<p>This earlier check lacks a complete recorded source set. Build a new check before approval.</p>}</details>
  <fieldset disabled={!enabled} className="space-y-3">{detail.eligibility.requiresManagerOverride&&<label className="flex gap-2"><input type="checkbox" aria-label="Accept listed readiness warnings" checked={override} onChange={e=>setOverride(e.target.checked)}/>I accept the listed manager-review warnings and have explained why in the decision reason. Missing required evidence cannot be overridden.</label>}<label className="flex gap-2"><input type="checkbox" aria-label="Confirm exact saved readiness decision" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this exact saved check, its source evidence and the intended decision.</label></fieldset>
  <div className="flex flex-wrap gap-2"><button className={button} disabled={!reviewable||!detail.eligibility.canApprove||!!detail.eligibility.requiresManagerOverride&&(!override||reason.trim().length<10)} onClick={()=>void save('approve')}>Approve saved readiness check</button><button className={button} disabled={!reviewable||!['ready','needs_review'].includes(detail.snapshot.status)} onClick={()=>void save('reject')}>Reject saved readiness check</button><button className={button} disabled={!reviewable||detail.snapshot.status!=='approved'} onClick={()=>void save('withdraw')}>Withdraw readiness approval</button></div></div>}
  {history&&<div aria-label="Readiness decision history" className="space-y-3 border-t pt-3"><p>Showing {history.items.length} of {history.total} readiness decisions.</p>{history.items.map(d=><button key={d.id} className="block w-full border-b py-3 text-left" disabled={busy} onClick={()=>void showDecision(d.id)}>{d.kind} · {d.createdAt} · {d.reason}<span className="block text-sm">Reviewed by {d.actorId}</span></button>)}{history.nextOffset!==null&&<button className={button} disabled={busy} onClick={()=>void loadHistory(true)}>Load more readiness decisions</button>}{historyDetail&&<div aria-label="Saved readiness decision details" className="grid gap-4 sm:grid-cols-2"><details><summary>Earlier saved evidence</summary><Evidence value={historyDetail.before_state}/></details><details><summary>Resulting saved evidence</summary><Evidence value={historyDetail.after_state}/></details></div>}</div>}
  {invalidations&&<div aria-label="Readiness source change history" className="space-y-3 border-t pt-3"><p>Showing {invalidations.items.length} of {invalidations.total} recorded source changes. These are system checks against the saved evidence.</p>{invalidations.items.map(i=><p key={i.id} className="text-sm">{new Date(i.created_at).toLocaleString()} · {label(i.cause.split(':')[0])} · Earlier {label(i.previous_status)} check now needs review.</p>)}{invalidations.nextOffset!==null&&<button className={button} disabled={busy} onClick={()=>void loadInvalidations(true)}>Load more source changes</button>}</div>}
 </section>
}
