'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import type {PolicyPage} from '@/utils/knowledge/web-policy-contracts'
import {clearPendingWebPolicy,pendingWebPolicy,postWebPolicy,webPolicyUrl,type PendingWebPolicy} from '@/utils/knowledge/web-policy-client'
import {knowledgeFetch} from '@/utils/knowledge/material-client'
const button='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 disabled:opacity-40'
const field='block w-full rounded-lg border border-slate-300 p-2 text-sm text-slate-900'
const message=(e:unknown)=>e instanceof Error?e.message:'Website monitoring could not be confirmed.'
export function WebsiteMonitoringPolicy({propertyId,onSaved}:{propertyId:string;onSaved:()=>void}){
 const[data,setData]=useState<PolicyPage|null>(null),[pending,setPending]=useState<PendingWebPolicy|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[enabled,setEnabled]=useState(false),[hours,setHours]=useState(72),[limit,setLimit]=useState(1),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[history,setHistory]=useState(false)
 const mounted=useRef(false)
 const load=useCallback(async(prior?:PolicyPage)=>{const next=await knowledgeFetch(webPolicyUrl(propertyId,{offset:prior?.nextOffset??0,expectedHash:prior?.historyHash}))as PolicyPage;if(!mounted.current)return;setData({...next,items:prior?[...prior.items,...next.items]:next.items});if(!prior){setEnabled(next.policy?.enabled??false);setHours(next.policy?.interval_hours??72);setLimit(next.policy?.daily_limit??1);setConfirmed(false);setReason('')}},[propertyId])
 useEffect(()=>{mounted.current=true;setPending(pendingWebPolicy(propertyId));load().catch(e=>{if(mounted.current){setData(null);setError(message(e))}});return()=>{mounted.current=false}},[propertyId,load])
 async function reload(prior?:PolicyPage){setBusy(true);setError('');if(!prior)setData(null);try{await load(prior)}catch(e){if(mounted.current){setData(null);setError(message(e))}}finally{if(mounted.current)setBusy(false)}}
 async function save(){if(!data)return;setBusy(true);setError('');setNotice('');try{const result=await postWebPolicy({propertyId,operation:'save',expectedRevision:data.policy?.revision??0,enabled,intervalHours:hours,dailyLimit:limit,confirmed:true,reason});if(!mounted.current)return;setPending(null);setNotice(`Monitoring policy saved. ${result.stoppedCaptures} unfinished scheduled captures stopped. Published knowledge is unchanged.`);await load();onSaved()}catch(e){if(mounted.current){setError(message(e));setPending(pendingWebPolicy(propertyId))}}finally{if(mounted.current)setBusy(false)}}
 async function recover(cancel=false){if(!pending)return;setBusy(true);setError('');try{const value=cancel?await knowledgeFetch('/api/knowledge/websites/policy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:pending.id,propertyId,operation:'cancel_unused',inputHash:pending.hash,reason:'Cancel only unused website monitoring decision after checking saved state'})}):await knowledgeFetch(webPolicyUrl(propertyId,{kind:'decision',decisionId:pending.id}));if(!mounted.current)return;if(value.cancelled!==true&&value.propertyId!==propertyId)throw new Error('The saved policy decision did not match.');clearPendingWebPolicy(propertyId,pending.id);setPending(null);setNotice(value.cancelled?'Unused monitoring decision cancelled. A delayed copy cannot save.':'Saved monitoring decision recovered.');await load();onSaved()}catch(e){if(mounted.current)setError(message(e))}finally{if(mounted.current)setBusy(false)}}
 const disabled=busy||!!pending||!data?.canManage
 return <section aria-label="Automatic website checks" aria-busy={busy} className="space-y-3 rounded-lg border border-slate-200 bg-slate-50 p-4">
  <div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-semibold">Automatic website checks</h4><button className={button} disabled={busy} onClick={()=>void reload()}>Reload monitoring policy</button></div>
  <p className="text-sm text-slate-600">Prepare a new private capture when a published website source becomes old enough for review. This includes website sources published later. Each published version gets at most one request under the same policy; held or unfinished captures need your attention before further checks.</p>
  <p className="text-sm text-slate-600">Every new capture needs review, search preparation and explicit publication before it changes assistant knowledge.</p>
  {error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="rounded bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
  {pending&&<div className="space-y-2 rounded bg-amber-50 p-3 text-sm"><p>A monitoring decision is unconfirmed.</p><button className={button} disabled={busy} onClick={()=>void recover()}>Check saved monitoring decision</button><button className={button} disabled={busy} onClick={()=>void recover(true)}>Cancel unused monitoring decision</button></div>}
  {data&&<><p className="text-sm">Saved policy: <strong>{data.policy?.enabled?'Enabled':'Off'}</strong>. {data.publishedWebsites} published website sources · {data.scheduledToday} requests today (UTC).</p>
   {data.execution.paused&&<p className="text-sm text-amber-800">Website fetching is paused for this environment. No automatic requests are created or fetched while paused.</p>}
   {!data.ownerAuthorized&&<p className="text-sm text-amber-800">The policy author no longer has permission. A current manager must review and save a new policy before automatic checks resume.</p>}
   {data.canManage&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void save()}}>
    <label className="flex items-start gap-2 text-sm"><input aria-label="Enable automatic website checks" type="checkbox" checked={enabled} disabled={disabled} onChange={e=>{setEnabled(e.target.checked);setConfirmed(false)}}/><span>Prepare new captures when published sources need review</span></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Source age before review (hours)<input aria-label="Source age before review (hours)" className={field} type="number" min={24} max={168} step={1} value={hours} disabled={disabled} onChange={e=>{setHours(Number(e.target.value));setConfirmed(false)}} required/></label><label className="text-sm">Maximum new requests per day (UTC)<input aria-label="Maximum new requests per day (UTC)" className={field} type="number" min={1} max={5} step={1} value={limit} disabled={disabled} onChange={e=>{setLimit(Number(e.target.value));setConfirmed(false)}} required/></label></div>
    <p className="text-xs text-slate-500">Saving any policy change stops its unfinished scheduled captures. Ready captures and all history remain available for review.</p>
    <label className="block text-sm">Reason for monitoring policy<textarea aria-label="Reason for monitoring policy" className={field} value={reason} maxLength={2000} minLength={3} disabled={disabled} onChange={e=>setReason(e.target.value)} required/></label>
    <label className="flex items-start gap-2 text-sm"><input aria-label="Confirm monitoring policy scope and limits" type="checkbox" checked={confirmed} disabled={disabled} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed the published-source scope, source age, daily limit and effect on unfinished captures.</span></label>
    <button className={button} disabled={disabled||!confirmed||reason.trim().length<3}>Save monitoring policy</button>
   </form>}
   <button className={button} disabled={busy} onClick={()=>setHistory(!history)}>{history?'Hide monitoring history':'Monitoring policy history'}</button>
   {history&&<div aria-label="Monitoring policy history"><p className="text-sm">Showing {data.items.length} of {data.total} decisions.</p><ol className="space-y-2">{data.items.map(row=><li key={row.id} className="border-t py-2 text-sm"><p>{new Date(row.created_at).toLocaleString()} · {row.before_state.policy?.enabled?'Enabled':'Off'} → {row.after_state.enabled?'Enabled':'Off'}</p><p>{row.after_state.interval_hours} hours · {row.after_state.daily_limit} requests per day · {row.result.stoppedCaptures} unfinished captures stopped</p><p className="whitespace-pre-wrap [overflow-wrap:anywhere]">{row.reason}</p><p className="break-all text-xs text-slate-500">Recorded actor: {row.actor_id}</p></li>)}</ol>{data.nextOffset!==null&&<button className={button} disabled={busy} onClick={()=>void reload(data)}>Load more monitoring decisions</button>}</div>}
  </>}
 </section>
}
