import {beforeEach,it,expect,vi}from 'vitest'
vi.mock('next/headers',()=>({headers:async()=>new Headers({'user-agent':'Synthetic fixture browser'})}))
const d=vi.hoisted(()=>({signIn:vi.fn(),identity:vi.fn(),profile:vi.fn(),redirect:vi.fn(),revalidate:vi.fn(),signOut:vi.fn(),signUp:vi.fn(),reset:vi.fn()}));vi.mock('@/utils/supabase/server',()=>({createClient:async()=>({rpc:d.identity,auth:{signInWithPassword:d.signIn,signOut:d.signOut,signUp:d.signUp,resetPasswordForEmail:d.reset},from:()=>({select:()=>({eq:()=>({single:d.profile})})})})}));vi.mock('next/navigation',()=>({redirect:d.redirect}));vi.mock('next/cache',()=>({revalidatePath:d.revalidate}));vi.mock('@/utils/services/runtime-config',()=>({getAppBaseUrl:()=> 'http://local'}))
vi.mock('@/utils/account-sessions/server',()=>({recordedCurrentSignOut:d.signOut}))
import {signIn,signUp,switchTeamAccount,forgotPassword}from './actions'
const input=(redirect?:string)=>{const f=new FormData();f.set('email','fixture@example.test');f.set('password','local-fixture');if(redirect)f.set('redirect',redirect);return f}
beforeEach(()=>{vi.clearAllMocks();d.identity.mockResolvedValue({data:{kind:'internal'},error:null});d.signIn.mockResolvedValue({data:{user:{id:'actor'}},error:null});d.profile.mockResolvedValue({data:{org_id:null},error:null});d.redirect.mockImplementation((path:string)=>{throw new Error('redirect:'+path)})})
it('routes a new account directly to its actual setup page',async()=>{await expect(signIn(null,input('/dashboard/community'))).rejects.toThrow('redirect:/onboarding')})
it('routes an existing member to a local requested page',async()=>{d.profile.mockResolvedValue({data:{org_id:'org'},error:null});await expect(signIn(null,input('/dashboard/community'))).rejects.toThrow('redirect:/dashboard/community')})
it.each(['//outside.example','/\\outside.example','https://outside.example','/\t/outside.example','/\n/outside.example'])('does not redirect a signed-in member outside the app: %s',async path=>{d.profile.mockResolvedValue({data:{org_id:'org'},error:null});await expect(signIn(null,input(path))).rejects.toThrow('redirect:/dashboard')})
it('keeps a failed profile read explicit instead of inferring new membership',async()=>{d.profile.mockResolvedValue({data:null,error:{message:'private database error'}});expect(await signIn(null,input())).toEqual({error:'Sign-in succeeded, but your account setup could not be read. Please try again.'});expect(d.redirect).not.toHaveBeenCalled()})

it('returns an invited account to exact review before organization setup',async()=>{await expect(signIn(null,input('/join/team'))).rejects.toThrow('redirect:/join/team')})

it('switches only the local session and preserves invitation return',async()=>{d.signOut.mockResolvedValue({error:null});await expect(switchTeamAccount()).rejects.toThrow('redirect:/auth/login?redirect=%2Fjoin%2Fteam');expect(d.signOut).toHaveBeenCalledExactlyOnceWith()})
it('failed sign-out does not pretend an account switch succeeded',async()=>{d.signOut.mockRejectedValue(new Error('Your current session could not be signed out'));await expect(switchTeamAccount()).rejects.toThrow('could not be signed out');expect(d.redirect).not.toHaveBeenCalled()})
it('new account verification links preserve review without invitation secrets',async()=>{d.signUp.mockResolvedValue({error:null});await expect(signUp(null,input('/join/team'))).resolves.toEqual({success:true});expect(d.signUp).toHaveBeenCalledWith(expect.objectContaining({options:expect.objectContaining({emailRedirectTo:'http://local/auth/callback?next=%2Fjoin%2Fteam'})}))})

it('recovery request has bounded email validation and an exact configured redirect',async()=>{d.reset.mockResolvedValue({error:null});expect(await forgotPassword(null,input())).toEqual({success:true});expect(d.reset).toHaveBeenCalledWith('fixture@example.test',{redirectTo:'http://local/auth/reset-password'});const f=input();f.set('email','invalid');expect((await forgotPassword(null,f)).error).toContain('valid email');expect(d.reset).toHaveBeenCalledTimes(1)})
it('recovery email does not reveal provider account details on failure',async()=>{d.reset.mockResolvedValue({error:{message:'PRIVATE ACCOUNT DATA'}});const r=await forgotPassword(null,input());expect(r.error).toContain('could not be requested');expect(JSON.stringify(r)).not.toContain('PRIVATE')})

it('sends client sign-in to the assigned-property portal',async()=>{d.identity.mockResolvedValue({data:{kind:'client'},error:null});await expect(signIn(null,input('/dashboard/leads'))).rejects.toThrow('redirect:/client');await expect(signIn(null,input('/client/reports'))).rejects.toThrow('redirect:/client/reports')})
it('preserves client invitation review before an account has joined',async()=>{await expect(signIn(null,input('/join/client'))).rejects.toThrow('redirect:/join/client')})
