import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import {postReview,pendingReview,recoverReview} from './client'
const id='11111111-1111-4111-8111-111111111111',store=new Map<string,string>(),fetcher=vi.fn()
const command={propertyId:id,operation:'review' as const,product:'siteforge' as const,sourceHash:'a'.repeat(64),decision:'watch' as const,reason:'Private review note'}
function receipt(requestId:string,kind='cancel_unused'){return {state:'ready',propertyId:id,decisionId:requestId,record:{id:requestId,property_id:id,org_id:id,actor_id:id,kind,input:{},input_hash:'a'.repeat(64),evidence:null,decision:null,reason:null,created_at:new Date().toISOString(),sequence:1}}}
beforeEach(()=>{store.clear();vi.stubGlobal('sessionStorage',{getItem:(k:string)=>store.get(k)||null,setItem:(k:string,v:string)=>store.set(k,v),removeItem:(k:string)=>store.delete(k)});vi.stubGlobal('fetch',fetcher);fetcher.mockReset()})
afterEach(()=>vi.unstubAllGlobals())
it('retains only request metadata after a lost reply and prevents another write',async()=>{fetcher.mockRejectedValue(new Error('lost reply'));await expect(postReview(command)).rejects.toThrow();expect(pendingReview(id)).not.toBeNull();expect([...store.values()].join()).not.toContain('Private');await expect(postReview(command)).rejects.toThrow('earlier review');expect(fetcher).toHaveBeenCalledTimes(1)})
it('recovers the same id after reload and clears only a verified receipt',async()=>{fetcher.mockRejectedValueOnce(new Error('lost'));await expect(postReview(command)).rejects.toThrow();const pending=pendingReview(id)!;fetcher.mockResolvedValueOnce(new Response(JSON.stringify(receipt(pending.id))));await recoverReview(pending);expect(pendingReview(id)).toBeNull();expect(fetcher.mock.calls[1][0]).toContain(pending.id)})
it('a missing or mismatched receipt preserves the pending identity',async()=>{fetcher.mockRejectedValueOnce(new Error('lost'));await expect(postReview(command)).rejects.toThrow();const pending=pendingReview(id)!;fetcher.mockResolvedValueOnce(new Response(JSON.stringify({error:'not found'}),{status:404}));await expect(recoverReview(pending)).rejects.toThrow();fetcher.mockResolvedValueOnce(new Response(JSON.stringify(receipt(id))));await expect(recoverReview(pending)).rejects.toThrow();expect(pendingReview(id)?.id).toBe(pending.id)})
it('explicit stale evidence rejection releases the unused identity',async()=>{fetcher.mockResolvedValueOnce(new Response(JSON.stringify({error:'Evidence changed'}),{status:409}));await expect(postReview(command)).rejects.toThrow();expect(pendingReview(id)).toBeNull()})
it('closing an unused request fences the same identity without the note',async()=>{fetcher.mockRejectedValueOnce(new Error('lost'));await expect(postReview(command)).rejects.toThrow();const p=pendingReview(id)!;fetcher.mockResolvedValueOnce(new Response(JSON.stringify(receipt(p.id))));await recoverReview(p,true);const sent=JSON.parse(fetcher.mock.calls[1][1].body);expect(sent).toEqual({propertyId:id,requestId:p.id,operation:'cancel_unused',inputHash:p.hash});expect(pendingReview(id)).toBeNull()})
