import {expect,it} from 'vitest'
import {executionCommand,executionQuery,executionResult} from './execution'
const id='11111111-1111-4111-8111-111111111111',hash='a'.repeat(64)
const prepare={propertyId:id,requestId:id,operation:'prepare',planRevision:id,steps:[{action:'lead.note.add',targetId:id,sourceHash:hash,content:'Follow up after reviewing the lead'}],reason:'Bounded local rehearsal'}
it('accepts the exact rehearsal vocabulary and two bounded steps',()=>{expect(executionCommand.safeParse(prepare).success).toBe(true);expect(executionCommand.safeParse({...prepare,steps:[...prepare.steps,{action:'market.alert.dismiss',targetId:id,sourceHash:hash}]}).success).toBe(true)})
it.each([{...prepare,actorId:id},{...prepare,steps:[]},{...prepare,steps:[...prepare.steps,...prepare.steps,...prepare.steps]},{...prepare,steps:[{...prepare.steps[0],action:'email.send'}]},{...prepare,steps:[{...prepare.steps[0],approved:true}]}])('rejects unbounded or caller-supplied authority',command=>{expect(executionCommand.safeParse(command).success).toBe(false)})
it('requires exact positive integral version and source hash for every effect',()=>{const command={propertyId:id,requestId:id,operation:'advance',runId:id,expectedVersion:1,specHash:hash,reason:'Run the exact reviewed step'};expect(executionCommand.safeParse(command).success).toBe(true);for(const change of[{expectedVersion:1.5},{expectedVersion:0},{specHash:'wrong'},{providerBudget:20}])expect(executionCommand.safeParse({...command,...change}).success).toBe(false)})
it('rejects ambiguous queries and overflowing cursors',()=>{for(const query of[{propertyId:id,kind:'decision'},{propertyId:id,kind:'run',runId:id,decisionId:id},{propertyId:id,kind:'board',before:'1'},{propertyId:id,kind:'history',before:'9223372036854775808'}])expect(executionQuery.safeParse(query).success).toBe(false);expect(executionQuery.safeParse({propertyId:id,kind:'run',runId:id}).success).toBe(true)})
it('does not accept live delivery or measured business outcomes in a rehearsal receipt',()=>{const result={runId:id,status:'completed',version:2,appliedCount:1,reversedCount:0,interventions:0,issue:null,nativeReceiptId:id,stepId:id,ordinal:0,mode:'local_rehearsal_only',nativeEffect:true,providerCalls:0,providerSpendUsd:0,businessOutcome:'unmeasured'};expect(executionResult.safeParse(result).success).toBe(true);expect(executionResult.safeParse({...result,businessOutcome:'success'}).success).toBe(false);expect(executionResult.safeParse({...result,providerCalls:1}).success).toBe(false)})
