import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc:d.rpc})}));vi.mock('@/utils/knowledge/inventory',()=>({inventoryActor:vi.fn(),InventoryError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {readExecution,operateExecution} from './execution-store'
const id='11111111-1111-4111-8111-111111111111'
beforeEach(()=>{vi.clearAllMocks();d.rpc.mockResolvedValue({data:{state:'ready',propertyId:id,mode:'local_rehearsal_only',enabled:false,canManage:true,items:[],nextBefore:null},error:null})})
it('reads the actual disabled state using the authenticated actor',async()=>{expect(await readExecution('actual-actor',id,{})).toMatchObject({enabled:false});expect(d.rpc).toHaveBeenCalledWith('read_agency_execution',{p_actor_id:'actual-actor',p_property_id:id,p_input:{}})})
it.each(['forbidden','evidence_changed','execution_disabled','scope_expired','plan_changed','source_changed','target_denied','run_changed','state_changed','request_conflict','not_found','decision_cancelled','invalid'])('fails closed on %s',async state=>{d.rpc.mockResolvedValue({data:{state},error:null});await expect(readExecution(id,id,{})).rejects.toThrow()})
it('does not leak native database errors',async()=>{d.rpc.mockResolvedValue({data:null,error:{message:'private connection secret'}});await expect(readExecution(id,id,{})).rejects.toThrow('receipt could not be confirmed')})
it('requires exact actor, command, property and run identities for recovery',async()=>{const result={runId:null,status:null,version:null,appliedCount:null,reversedCount:null,interventions:null,issue:null,nativeReceiptId:null,stepId:null,ordinal:null,mode:'local_rehearsal_only',nativeEffect:false,providerCalls:0,providerSpendUsd:0,businessOutcome:'unmeasured'};const data={state:'saved',propertyId:id,decisionId:id,record:{id,property_id:id,org_id:id,actor_id:id,run_id:null,input:{},input_hash:'a'.repeat(64),result,created_at:new Date().toISOString(),sequence:1}};d.rpc.mockResolvedValue({data,error:null});await expect(operateExecution(id,{propertyId:id,requestId:id,operation:'cancel_unused',inputHash:'a'.repeat(64)})).resolves.toMatchObject({state:'saved'});d.rpc.mockResolvedValue({data:{...data,record:{...data.record,actor_id:'22222222-2222-4222-8222-222222222222'}},error:null});await expect(operateExecution(id,{propertyId:id,requestId:id,operation:'cancel_unused',inputHash:'a'.repeat(64)})).rejects.toThrow('does not match')})
