import {beforeEach,it,expect,vi} from 'vitest'
const d=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/utils/supabase/admin',()=>({createServiceClient:()=>({rpc:d.rpc})}));vi.mock('@/utils/knowledge/inventory',()=>({inventoryActor:vi.fn(),InventoryError:class extends Error{constructor(message:string,readonly status=503){super(message)}}}))
import {readAgency,decideAgency} from './store'
const id='11111111-1111-4111-8111-111111111111'
beforeEach(()=>{vi.clearAllMocks();d.rpc.mockResolvedValue({data:{state:'ready',propertyId:id,items:[],nextBefore:null},error:null})})
it('uses the server actor and exact property for scoped reads',async()=>{await readAgency('actor',id,{kind:'history',before:'12'});expect(d.rpc).toHaveBeenCalledWith('read_agency_observation',{p_actor_id:'actor',p_property_id:id,p_input:{kind:'history',before:'12'}})})
it.each(['forbidden','evidence_changed','request_conflict','no_recommendation','not_found','decision_cancelled','invalid'])('fails closed on %s',async state=>{d.rpc.mockResolvedValue({data:{state},error:null});await expect(readAgency('actor',id,{})).rejects.toThrow()})
it('holds incomplete and wrong-property receipts without disclosing errors',async()=>{d.rpc.mockResolvedValue({data:{state:'saved',propertyId:id},error:null});await expect(decideAgency('actor',{requestId:id,propertyId:id,operation:'cancel_unused',inputHash:'a'.repeat(64)})).rejects.toThrow('verified');d.rpc.mockResolvedValue({data:null,error:{message:'secret db error'}});await expect(readAgency('actor',id,{})).rejects.toThrow('could not be confirmed')})
it('checks identity even when a receipt shape looks valid',async()=>{d.rpc.mockResolvedValue({error:null,data:{state:'saved',propertyId:id,decisionId:id,record:{id,property_id:id,org_id:id,actor_id:'22222222-2222-4222-8222-222222222222',kind:'cancel_unused',input:{},input_hash:'a'.repeat(64),evidence:null,decision:null,reason:null,created_at:new Date().toISOString(),sequence:1}}});await expect(decideAgency(id,{requestId:id,propertyId:id,operation:'cancel_unused',inputHash:'a'.repeat(64)})).rejects.toThrow('does not match')})
