import {beforeEach,afterEach,it,expect,vi}from 'vitest'
import {briefDraftKey,briefRequest,reserveBriefReport,reportBriefExport,retryBriefReports}from './brief-history-client'
const send=vi.fn(),values:Record<string,string>={}
const storage={getItem:(k:string)=>values[k]??null,setItem:(k:string,v:string)=>{values[k]=v;Object.defineProperty(storage,k,{value:v,configurable:true,enumerable:true})},removeItem:(k:string)=>{delete values[k];delete (storage as Record<string,unknown>)[k]}}
beforeEach(()=>{for(const k of Object.keys(values))storage.removeItem(k);send.mockReset();vi.stubGlobal('sessionStorage',storage);vi.stubGlobal('fetch',send)})
afterEach(()=>vi.unstubAllGlobals())
it('reuses only a hashed request identity after a lost reply and clears it after confirmation',async()=>{send.mockRejectedValueOnce(new Error('Lost reply')).mockResolvedValueOnce(new Response(JSON.stringify({result:{state:'saved'}})));const input={propertyId:'property',draft:{request:'Private client context'}};await expect(briefRequest('',input,['saved'])).rejects.toThrow('Lost reply');expect(Object.keys(values)).toEqual([expect.stringMatching(/^p11\.codex-brief\.request\.[a-f0-9]{64}$/)]);expect(JSON.stringify(values)).not.toContain('Private');await briefRequest('',input,['saved']);expect(JSON.parse(send.mock.calls[0][1].body).requestId).toBe(JSON.parse(send.mock.calls[1][1].body).requestId);expect(Object.keys(values)).toHaveLength(0)})
it('retains browser reports after a lost acknowledgement and retries only the selected property',async()=>{send.mockRejectedValueOnce(new Error('Lost report')).mockResolvedValueOnce(new Response(JSON.stringify({result:{state:'replayed'}})));const report={propertyId:'one',exportId:'export',result:'clipboard_failed' as const};await expect(reportBriefExport(report)).rejects.toThrow();await retryBriefReports('other');expect(send).toHaveBeenCalledTimes(1);await retryBriefReports('one');expect(send).toHaveBeenCalledTimes(2);expect(JSON.parse(send.mock.calls[1][1].body)).toEqual({action:'report',...report});expect(Object.keys(values)).toHaveLength(0)})
it('never infers a browser outcome from a reserved export after interruption',async()=>{reserveBriefReport('unknown');await retryBriefReports('one');expect(send).not.toHaveBeenCalled();expect(JSON.parse(values['p11.codex-brief.report.unknown'])).toEqual({exportId:'unknown',pending:true})})
it('blocks before mutation if recovery storage cannot retain intent',async()=>{vi.stubGlobal('sessionStorage',{getItem:()=>{throw new Error('Full')}});await expect(briefRequest('',{draft:'private'},['saved'])).rejects.toThrow('recovery storage');expect(send).not.toHaveBeenCalled()})

it('recognizes the same draft after database JSON key ordering changes',()=>{const property={id:'property',name:'Property',city:null},draft={request:' Update gallery ',references:'Sources',target:'existing' as const,revision:{parentVersion:'old',keepUnchanged:'Home'},delivery:{projectLocation:'project',inquiryDestination:'',contentOwnership:''}};expect(briefDraftKey(property,draft)).toBe(briefDraftKey({city:null,name:'Property',id:'property'},{delivery:{contentOwnership:'',inquiryDestination:'',projectLocation:'project'},revision:{keepUnchanged:'Home',parentVersion:'old'},target:'existing',references:'Sources',request:'Update gallery'}))})
