import {beforeEach,afterEach,it,expect,vi}from 'vitest'
import {decodeDeliveryText,saveDeliveryDecision}from './delivery-record-client'
const values=new Map<string,string>(),send=vi.fn()
beforeEach(()=>{values.clear();send.mockReset();vi.stubGlobal('sessionStorage',{getItem:(k:string)=>values.get(k)||null,setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)});vi.stubGlobal('fetch',send)})
afterEach(()=>vi.unstubAllGlobals())
it('retains only a hashed identity and retries an exact supplied report after a lost reply',async()=>{send.mockRejectedValueOnce(new Error('Lost response')).mockResolvedValueOnce(new Response(JSON.stringify({result:{state:'replayed',recordId:'saved'}})));const input={propertyId:'property',action:'record',sourceText:'Private original delivery report'};await expect(saveDeliveryDecision(input)).rejects.toThrow('Lost response');expect([...values.keys()]).toEqual([expect.stringMatching(/^p11\.site-delivery\.[a-f0-9]{64}$/)]);expect(JSON.stringify([...values])).not.toContain(input.sourceText);expect(await saveDeliveryDecision(input)).toMatchObject({recordId:'saved'});expect(JSON.parse(send.mock.calls[0][1].body).requestId).toBe(JSON.parse(send.mock.calls[1][1].body).requestId);expect(values.size).toBe(0)})
it('keeps correction and property identities separate after a stale review failure',async()=>{send.mockImplementation(()=>Promise.resolve(new Response(JSON.stringify({error:'Review changed'}),{status:409})));const input={propertyId:'one',action:'review',expectedReviewId:null,reason:'Review retained checks'};for(const value of [input,{...input,expectedReviewId:'new'},{...input,propertyId:'other'}])await expect(saveDeliveryDecision(value)).rejects.toThrow('Review changed');expect(new Set(send.mock.calls.map(c=>JSON.parse(c[1].body).requestId)).size).toBe(3);expect(values.size).toBe(3)})
it('does not mutate without recovery storage or pretend a successful HTTP status confirms persistence',async()=>{vi.stubGlobal('sessionStorage',{getItem:()=>{throw new Error('Unavailable')}});await expect(saveDeliveryDecision({action:'record'})).rejects.toThrow('recovery storage');expect(send).not.toHaveBeenCalled();vi.stubGlobal('sessionStorage',{getItem:()=>null,setItem:vi.fn(),removeItem:vi.fn()});send.mockResolvedValue(new Response('{}'));await expect(saveDeliveryDecision({action:'record'})).rejects.toThrow('could not be confirmed')})

it('retains UTF-8 byte identity including a BOM and CRLF, and rejects malformed text rather than replacing it',()=>{const source='\uFEFF# Source report\r\nOriginal café and 🌿 evidence';expect(decodeDeliveryText(new TextEncoder().encode(source).buffer)).toBe(source);expect(()=>decodeDeliveryText(new Uint8Array([0xc3,0x28]).buffer)).toThrow('not valid UTF-8')})
