import {describe,it,expect,vi,beforeEach} from 'vitest'
const mock=vi.hoisted(()=>({actor:vi.fn(),rpc:vi.fn()}))
vi.mock('@/utils/analytics/import-store',async()=>{const actual=await vi.importActual<typeof import('@/utils/analytics/import-store')>('@/utils/analytics/import-store');return {...actual,csvActor:mock.actor,csvRpc:mock.rpc}})
import {GET,POST} from './route'
const id='aa810000-0000-4000-8000-000000000001',propertyId='aa810000-0000-4000-8000-000000000002',actor='aa810000-0000-4000-8000-000000000003'
const original={filename:'daily.csv',csvContent:'Date,Campaign ID,Impressions,Clicks,Cost,Conversions\n2026-09-10,123,100,10,12.50,0.125',platform:'google_ads',sourceAccountId:'123-456-7890',campaignName:'Campaign',currencyCode:'USD'}
const input={id,propertyId,expectedActorId:actor,operation:'prepare',original},request=(body:unknown,origin='http://localhost')=>new Request('http://localhost/api/analytics/csv-imports',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)})
beforeEach(()=>{vi.clearAllMocks();mock.actor.mockResolvedValue(actor);mock.rpc.mockResolvedValue({state:'ready',propertyId,id,items:[],count:55})})
describe('retained CSV import API',()=>{
 it('pins exact original and server-derived parsing without accepting browser rows',async()=>{expect((await POST(request(input))).status).toBe(200);expect(mock.rpc).toHaveBeenCalledWith('prepare_bi_csv',expect.objectContaining({p_original:original,p_preview:expect.objectContaining({sourceAccountId:'1234567890',rows:[expect.objectContaining({campaign_id:'123',conversions:0.125})]})}));mock.rpc.mockClear();expect((await POST(request({...input,preview:{rows:[]}}))).status).toBe(400);expect(mock.rpc).not.toHaveBeenCalled()})
 it('requires same-origin before processing file contents',async()=>{expect((await POST(request(input,'https://other.invalid'))).status).toBe(403);expect(mock.rpc).not.toHaveBeenCalled();expect(mock.actor).not.toHaveBeenCalled()})
 it('holds changed signed-in actor',async()=>{mock.actor.mockResolvedValue(id);expect((await POST(request(input))).status).toBe(409);expect(mock.rpc).not.toHaveBeenCalled()})
 it('rejects bad numeric source rather than storing fabricated values',async()=>{expect((await POST(request({...input,original:{...original,csvContent:original.csvContent.replace('12.50','unknown')}}))).status).toBe(400);expect(mock.rpc).not.toHaveBeenCalled()})
 it('bounds incoming body before creating a private source',async()=>{const r=request(input);r.headers.set('content-length',String(13*1024*1024));expect((await POST(r)).status).toBe(413);expect(mock.rpc).not.toHaveBeenCalled()})
 it('retains explicit new-preview ancestry',async()=>{await POST(request({...input,parentId:id}));expect(mock.rpc).toHaveBeenCalledWith('prepare_bi_csv',expect.objectContaining({p_parent_id:id}))})
 it.each(['apply','discard'])('records %s against the exact source and destination review',async operation=>{expect((await POST(request({id,propertyId,expectedActorId:actor,operation,importId:id,previewHash:'a'.repeat(64),targetHash:'b'.repeat(64),reason:'Reviewed source and existing rows'}))).status).toBe(200);expect(mock.rpc).toHaveBeenCalledWith('decide_bi_csv',expect.objectContaining({p_import_id:id,p_input:{operation,previewHash:'a'.repeat(64),targetHash:'b'.repeat(64),reason:'Reviewed source and existing rows'}}))})
 it.each(['cancel_preview','cancel_decision'])('fences unused %s identities without another file',async operation=>{expect((await POST(request({id,propertyId,expectedActorId:actor,operation}))).status).toBe(200);expect(mock.rpc).toHaveBeenCalledTimes(1)})
 it('reads complete versioned pages and legacy history under current membership',async()=>{const r=await GET(new Request(`http://localhost/api/analytics/csv-imports?propertyId=${propertyId}&kind=legacy&offset=25&hash=${'a'.repeat(64)}`));expect(r.status).toBe(200);expect(mock.rpc).toHaveBeenCalledWith('read_bi_csv',expect.objectContaining({p_actor_id:actor,p_property_id:propertyId,p_kind:'legacy',p_offset:25,p_hash:'a'.repeat(64)}))})
 it('recovers decision identity without another write',async()=>{await GET(new Request(`http://localhost/api/analytics/csv-imports?propertyId=${propertyId}&commandId=${id}`));expect(mock.rpc).toHaveBeenCalledWith('read_bi_csv',expect.objectContaining({p_command_id:id}))})
 it.each(['&offset=-1','&kind=other','&actorId='+actor])('rejects malformed read selectors %s',async extra=>{expect((await GET(new Request(`http://localhost/api/analytics/csv-imports?propertyId=${propertyId}${extra}`))).status).toBe(400);expect(mock.rpc).not.toHaveBeenCalled()})
 it('does not disclose database errors',async()=>{mock.rpc.mockRejectedValue(new Error('private source failure'));const r=await GET(new Request(`http://localhost/api/analytics/csv-imports?propertyId=${propertyId}`));expect(r.status).toBe(503);expect(JSON.stringify(await r.json())).not.toContain('private source failure')})
})
