import {beforeEach,it,expect,vi} from 'vitest'
import {NextRequest} from 'next/server'
const d=vi.hoisted(()=>({access:vi.fn(),rpc:vi.fn()}))
vi.mock('@/utils/leads/activity-store',async original=>({...await original<typeof import('@/utils/leads/activity-store')>(),requireActivityActor:d.access,activityRpc:d.rpc}))
import {ActivityError} from '@/utils/leads/activity-store'
import {GET,POST} from './route'
const id='33333333-3333-3333-3333-333333333333',ctx={params:Promise.resolve({id})},input={requestId:id,propertyId:id,action:'add',content:'Internal note',reason:'Save operator note'}
const req=(method:string,body?:unknown,query='')=>new NextRequest(`http://localhost/api/leads/${id}/activities${query}`,{method,...(body?{body:JSON.stringify(body)}:{})})
beforeEach(()=>{vi.clearAllMocks();d.access.mockResolvedValue('actor');d.rpc.mockResolvedValue({state:'saved',noteId:id})})
it('requires explicit property and rejects earlier generic system writes',async()=>{expect((await GET(req('GET'),ctx)).status).toBe(400);for(const type of ['email_sent','tour_completed','workflow_started','note'])expect((await POST(req('POST',{type,description:'Claimed success',metadata:{providerReceipt:'forged'}}),ctx)).status).toBe(400);expect(d.rpc).not.toHaveBeenCalled()})
it('checks current actor before any timeline or note access',async()=>{d.access.mockRejectedValue(new ActivityError('Forbidden',403));expect((await POST(req('POST',input),ctx)).status).toBe(403);expect((await GET(req('GET',undefined,`?propertyId=${id}`),ctx)).status).toBe(403);expect(d.rpc).not.toHaveBeenCalled()})
it('passes exact note intent and current server actor to the native transaction',async()=>{const r=await POST(req('POST',input),ctx);expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('private, no-store');expect(d.rpc).toHaveBeenCalledWith('save_lead_note',{p_id:id,p_property_id:id,p_lead_id:id,p_actor_id:'actor',p_input:{action:'add',content:'Internal note',reason:'Save operator note'}})})
it('requires source hash and version for corrections and prevents injected metadata',async()=>{const body={requestId:id,propertyId:id,action:'correct',noteId:id,expectedVersion:0,sourceHash:'a'.repeat(64),content:'Corrected legacy note',reason:'Reviewed original source'};expect((await POST(req('POST',body),ctx)).status).toBe(200);expect((await POST(req('POST',{...body,metadata:{source:'verified'}}),ctx)).status).toBe(400);expect((await POST(req('POST',{...body,sourceHash:undefined}),ctx)).status).toBe(400)})
it('scopes paged original-note history to the selected lead and property',async()=>{expect((await GET(req('GET',undefined,`?propertyId=${id}&cursor=${id}&noteId=${id}`),ctx)).status).toBe(200);expect(d.rpc).toHaveBeenCalledWith('read_lead_activity',{p_property_id:id,p_lead_id:id,p_actor_id:'actor',p_cursor:id,p_note_id:id})})
it('returns visible conflicts and persistence failures without fabricated success',async()=>{d.rpc.mockRejectedValueOnce(new ActivityError('Note changed',409)).mockRejectedValueOnce(new ActivityError('History could not be confirmed'));expect((await POST(req('POST',input),ctx)).status).toBe(409);const r=await GET(req('GET',undefined,`?propertyId=${id}`),ctx);expect(r.status).toBe(503);expect(await r.json()).toEqual({error:'History could not be confirmed'})})
