create function public.read_reviewflow_statistics(p_property_id uuid,p_actor_id uuid,p_days integer default 0) returns jsonb language plpgsql stable security invoker set search_path='' as $$declare output jsonb;begin
 if not exists(select 1 from public.properties p join public.profiles u on u.org_id=p.org_id where p.id=p_property_id and u.id=p_actor_id) then return '{"state":"forbidden"}';end if;
 if p_days is null or p_days not between 0 and 365 then raise exception 'Choose a valid statistics window';end if;
 with selected as materialized(
  select r.*,a.status analysis_status,case when a.status='completed' then a.sentiment end current_sentiment,case when a.status='completed' then a.topics else '[]'::jsonb end current_topics
  from public.reviews r left join lateral(select a.status,a.sentiment,a.topics from public.review_analyses a where a.review_id=r.id and a.property_id=p_property_id and a.source_version=r.source_version and a.status in('completed','manual_review_required') order by a.analysis_version desc,a.id desc limit 1) a on true
  where r.property_id=p_property_id and coalesce(r.review_date,r.created_at)<=now() and(p_days=0 or coalesce(r.review_date,r.created_at)>=now()-make_interval(days=>p_days))
 ),case_rows as materialized(select c.* from public.reputation_cases c where c.property_id=p_property_id),ticket_rows as materialized(select t.status from public.review_tickets t where t.property_id=p_property_id),reported as materialized(
  select distinct r.id from selected r join public.reviewflow_publications p on p.review_id=r.id and p.property_id=p_property_id and p.source_version=r.source_version and p.state='reported' where r.response_status='posted'
 ) select jsonb_build_object(
  'totalReviews',(select count(*) from selected),'ratedReviews',(select count(rating) from selected),'avgRating',(select round(avg(rating),1) from selected),
  'responseRate',(select round(100.0*count(*) filter(where response_status='posted')/nullif(count(*) filter(where response_status is distinct from 'skipped'),0)) from selected),
  'sentimentCounts',(select jsonb_build_object('positive',count(*) filter(where current_sentiment='positive'),'neutral',count(*) filter(where current_sentiment='neutral'),'negative',count(*) filter(where current_sentiment='negative')) from selected),
  'analysisCoverage',(select jsonb_build_object('current',count(*) filter(where analysis_status='completed'),'staffReview',count(*) filter(where analysis_status='manual_review_required'),'unclassified',count(*) filter(where analysis_status is null)) from selected),
  'responseCounts',(select jsonb_build_object('pending',count(*) filter(where response_status='pending'),'draft_ready',count(*) filter(where response_status='draft_ready'),'approved',count(*) filter(where response_status='approved'),'posted',count(*) filter(where response_status='posted'),'skipped',count(*) filter(where response_status='skipped')) from selected),
  'responseEvidence',jsonb_build_object('staffReported',(select count(*) from reported),'legacyUnverified',(select count(*) from selected where response_status='posted' and id not in(select id from reported)),'providerConfirmed',0),
  'platformCounts',coalesce((select jsonb_object_agg(platform,amount) from(select platform,count(*) amount from selected group by platform) q),'{}'),
  'ticketCounts',(select jsonb_build_object('open',count(*) filter(where status='open'),'in_progress',count(*) filter(where status='in_progress'),'resolved',count(*) filter(where status='resolved'),'closed',count(*) filter(where status='closed')) from ticket_rows),
  'caseCounts',(select jsonb_build_object('open',count(*) filter(where status='open'),'triaged',count(*) filter(where status='triaged'),'awaiting_approval',count(*) filter(where status='awaiting_approval'),'ready_to_post',count(*) filter(where status='ready_to_post'),'remediation',count(*) filter(where status='remediation'),'resolved',count(*) filter(where status='resolved'),'dismissed',count(*) filter(where status='dismissed'),'slaBreached',count(*) filter(where status not in('resolved','dismissed') and sla_due_at<now())) from case_rows),
  'topTopics',coalesce((select jsonb_agg(jsonb_build_object('topic',topic,'count',amount) order by amount desc,topic) from(select topic,count(*) amount from selected r cross join lateral(select distinct t as topic from jsonb_array_elements_text(case when jsonb_typeof(r.current_topics)='array' then r.current_topics else '[]' end) t) topics group by topic order by amount desc,topic limit 5) q),'[]'),
  'ratingDistribution',(select jsonb_agg(jsonb_build_object('rating',rating,'count',(select count(*) from selected r where r.rating=n.rating)) order by rating) from generate_series(1,5)n(rating)),
  'recentReviews',coalesce((select jsonb_agg(to_jsonb(q) order by observed_at desc,id desc) from(select id,reviewer_name,rating,current_sentiment as sentiment,platform,created_at,coalesce(review_date,created_at) observed_at,case when review_date is null then 'import_date' else 'review_date' end date_basis from selected order by observed_at desc,id desc limit 5)q),'[]'),
  'periodDays',p_days,'asOf',now(),'dateFallbackReviews',(select count(*) from selected where review_date is null),'coverageNote','All saved reviews in the selected review-date window are counted. External source completeness is unknown. Open cases and tickets cover all dates. Recorded responses include staff reports and unverified legacy records; provider verification is separate.'
 ) into output;
 return jsonb_build_object('state','ready','stats',output);
end$$;

create function public.reviewflow_queue_members(p_property_id uuid) returns table(review_id uuid,bucket text,created_at timestamptz) language sql stable security invoker set search_path='' as $$
 select r.id,case
  when (c.status not in('resolved','dismissed') and(c.priority in('high','urgent') or c.risk_class='legal_regulatory' or c.policy_class in('fair_housing','discrimination','accessibility','safety','legal_threat','privacy','habitability','employee_accusation','compensation_liability'))) or(coalesce(a.is_urgent,false) and(c.id is null or c.status not in('resolved','dismissed'))) then 'high_risk'
  when c.status not in('resolved','dismissed') and c.sla_due_at<=now()+interval '24 hours' then 'sla_risk'
  when r.response_status='draft_ready' then 'awaiting_approval'
  when r.response_status='approved' then 'ready_to_post'
  when c.status not in('resolved','dismissed') and r.response_status in('posted','skipped') then 'remediation'
  when r.response_status in('posted','skipped') then 'completed'
  else 'needs_attention' end,r.created_at
 from public.reviews r left join public.reputation_cases c on c.review_id=r.id and c.property_id=r.property_id
 left join lateral(select a.is_urgent from public.review_analyses a where a.review_id=r.id and a.property_id=r.property_id and a.source_version=r.source_version and a.status in('completed','manual_review_required') order by a.analysis_version desc,a.id desc limit 1)a on true
 where r.property_id=p_property_id;
$$;

create function public.read_reviewflow_queue(p_property_id uuid,p_actor_id uuid,p_bucket text default null,p_cursor uuid default null) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare anchor_time timestamptz;output jsonb;begin
 if not exists(select 1 from public.properties p join public.profiles u on u.org_id=p.org_id where p.id=p_property_id and u.id=p_actor_id) then return '{"state":"forbidden"}';end if;
 if p_bucket is not null and p_bucket not in('high_risk','sla_risk','awaiting_approval','ready_to_post','remediation','needs_attention','completed') then raise exception 'Choose a review queue';end if;
 if p_cursor is not null then select created_at into anchor_time from public.reviewflow_queue_members(p_property_id) where review_id=p_cursor and bucket=p_bucket;if not found then return '{"state":"stale_cursor"}';end if;end if;
 with members as materialized(select * from public.reviewflow_queue_members(p_property_id)),buckets as(select b,ord from unnest(array['high_risk','sla_risk','awaiting_approval','ready_to_post','remediation','needs_attention','completed']) with ordinality v(b,ord) where p_bucket is null or b=p_bucket),pages as(
  select b.b,b.ord,(select count(*) from members where bucket=b.b) total,(select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'platform',q.platform,'reviewer_name',q.reviewer_name,'rating',q.rating,'review_text',left(q.review_text,1500),'review_date',q.review_date,'source_version',q.source_version,'response_status',q.response_status,'created_at',q.created_at) order by q.created_at,q.id),'[]') from(select r.* from members m join public.reviews r on r.id=m.review_id where m.bucket=b.b and(p_cursor is null or(m.created_at,m.review_id)>(anchor_time,p_cursor)) order by m.created_at,m.review_id limit 11)q) rows from buckets b
 ) select jsonb_build_object('buckets',coalesce(jsonb_agg(jsonb_build_object('id',b,'total',total,'items',(select coalesce(jsonb_agg(v order by n),'[]') from jsonb_array_elements(rows) with ordinality t(v,n) where n<=10),'nextCursor',case when jsonb_array_length(rows)>10 then rows->9->>'id' end) order by ord),'[]'),'sourceHash',(select public.crm_configuration_hash(coalesce(jsonb_agg(jsonb_build_array(m.review_id,m.bucket,m.created_at,r.source_version,r.response_status) order by m.review_id),'[]')) from members m join public.reviews r on r.id=m.review_id),'total',(select count(*) from members),'actionable',(select count(*) from members where bucket<>'completed'),'asOf',now()) into output from pages;
 return output||'{"state":"ready"}';
end$$;

create function public.reviewflow_recovery_rows(p_property_id uuid) returns table(id uuid,kind text,review_id uuid,platform text,reason text,occurred_at timestamptz,section text,source_version integer,current_source_version integer) language sql stable security invoker set search_path='' as $$
 with scope as(select id,org_id from public.properties where id=p_property_id),analysis as(
  select distinct on(a.review_id) a.* from public.reviewflow_analysis_requests a join scope p on p.id=a.property_id and p.org_id=a.org_id order by a.review_id,a.created_at desc,a.id desc
 ),generation as(
  select distinct on(g.review_id) g.* from public.reviewflow_response_generation_requests g join scope p on p.id=g.property_id and p.org_id=g.org_id order by g.review_id,g.created_at desc,g.id desc
 )
 select p.id,case p.state when 'held' then 'publication_uncertain' else 'manual_handoff' end,p.review_id,r.platform,case p.state when 'held' then 'Publication outcome is uncertain. Review the saved handoff before preparing a replacement.' else 'Manual publication is waiting for a staff report or confirmation that it was not published.' end,p.created_at,'review',p.source_version,r.source_version from public.reviewflow_publications p join scope s on s.id=p.property_id and s.org_id=p.org_id join public.reviews r on r.id=p.review_id and r.property_id=p.property_id where p.state in('awaiting_confirmation','held')
 union all
 select a.id,case when a.state='result_ready' then 'analysis_result' else 'analysis_review' end,a.review_id,r.platform,case when a.state='result_ready' then 'A saved analysis result is ready for recovery.' when a.state='running' then 'An analysis started but its result has not been confirmed. Inspect its saved status without repeating the model call.' else 'The latest analysis is held for review.' end,a.created_at,'review',a.source_version,r.source_version from analysis a join public.reviews r on r.id=a.review_id and r.property_id=a.property_id where a.state='result_ready' or(a.state='held' and a.source_version=r.source_version) or(a.state='running' and a.started_at<now()-interval '15 minutes')
 union all
 select g.id,case when g.state='result_ready' then 'response_result' else 'response_review' end,g.review_id,r.platform,case when g.state='result_ready' then 'A saved response draft result is ready for recovery.' when g.state='running' then 'Response generation started but its result is unconfirmed. Inspect saved history without repeating the model call.' else 'The latest response generation is held for review.' end,g.created_at,'review',g.source_version,r.source_version from generation g join public.reviews r on r.id=g.review_id and r.property_id=g.property_id where g.state='result_ready' or(g.state='held' and g.source_version=r.source_version) or(g.state='running' and g.started_at<now()-interval '15 minutes')
 union all
 select i.id,case when i.state='preview' then 'source_preview' else 'source_review' end,null,null,case when i.state='preview' then 'A saved import preview is waiting for a reviewed application.' when i.state='result_ready' then 'A source result is saved and ready to rebuild its import preview.' when i.state='running' then 'A source check started but its result is unconfirmed. Inspect the saved request.' else 'A saved import is held and needs a source decision.' end,i.created_at,'intake',null,null from public.reviewflow_intake_requests i join scope s on s.id=i.property_id and s.org_id=i.org_id where i.state in('preview','held','result_ready') or(i.state='running' and i.started_at<now()-interval '15 minutes')
 union all
 select b.id,'analysis_queue',null,null,case b.state when 'prepared' then 'A complete review selection is waiting for scope approval.' else 'A saved analysis queue has items needing staff review.' end,b.created_at,'batch',null,null from public.reviewflow_analysis_batches b join scope s on s.id=b.property_id and s.org_id=b.org_id where b.state='prepared' or(b.state='needs_review' and exists(select 1 from public.reviewflow_analysis_batch_items i join public.reviews r on r.id=i.review_id and r.property_id=b.property_id where i.batch_id=b.id and((i.state='held' and not exists(select 1 from public.review_analyses a where a.review_id=r.id and a.property_id=r.property_id and a.source_version=r.source_version and a.status='completed')) or(i.state='staff_review' and exists(select 1 from public.reputation_cases c where c.review_id=r.id and c.status not in('resolved','dismissed'))))))
 union all
 select d.id,case when d.status='posted' then 'legacy_publication' else 'approved_waiting' end,d.review_id,r.platform,case when d.status='posted' then 'A legacy provider publication has no qualified readback receipt. Review the saved destination evidence.' when d.source_version is distinct from r.source_version then 'An approved response belongs to an earlier review source. Recheck the current source before publication.' else 'An approved response has been waiting for publication review for more than 24 hours.' end,coalesce(d.approved_at,d.created_at),'review',d.source_version,r.source_version
 from public.review_responses d join public.reviews r on r.id=d.review_id and r.property_id=p_property_id join scope s on s.id=r.property_id where d.superseded_at is null and not exists(select 1 from public.reviewflow_publications p where p.response_id=d.id) and((d.status='posted' and d.posting_mode='provider_api') or(d.status='approved' and not exists(select 1 from public.shared_action_attempts a where a.id=d.shared_action_attempt_id and a.execution_status='failed') and(d.approved_at<now()-interval '24 hours' or d.source_version is distinct from r.source_version)))
 union all
 select d.id,'legacy_failed_execution',d.review_id,r.platform,'A legacy response execution failed. Inspect its saved destination and outcome before any new publication.',coalesce(a.executed_at,a.updated_at,d.created_at),'review',d.source_version,r.source_version
 from public.review_responses d join public.reviews r on r.id=d.review_id and r.property_id=p_property_id join scope s on s.id=r.property_id join public.shared_action_attempts a on a.id=d.shared_action_attempt_id and a.property_id=s.id and a.org_id=s.org_id where a.execution_status='failed' and d.status<>'posted' and d.superseded_at is null and not exists(select 1 from public.reviewflow_publications p where p.response_id=d.id);
$$;

create function public.read_reviewflow_recovery(p_property_id uuid,p_actor_id uuid,p_cursor text default null) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare anchor_time timestamptz;anchor_key text;output jsonb;begin
 if not exists(select 1 from public.properties p join public.profiles u on u.org_id=p.org_id where p.id=p_property_id and u.id=p_actor_id) then return '{"state":"forbidden"}';end if;
 if p_cursor is not null then select occurred_at,kind||':'||id::text into anchor_time,anchor_key from public.reviewflow_recovery_rows(p_property_id) where kind||':'||id::text=p_cursor;if not found then return '{"state":"stale_cursor"}';end if;end if;
 with rows as materialized(select *,kind||':'||id::text key from public.reviewflow_recovery_rows(p_property_id)),page as(select * from rows where p_cursor is null or(occurred_at,key)>(anchor_time,anchor_key) order by occurred_at,key limit 21)
 select jsonb_build_object('state','ready','sourceHash',(select public.crm_configuration_hash(coalesce(jsonb_agg(jsonb_build_array(key,occurred_at,source_version,current_source_version,reason) order by key),'[]')) from rows),'total',(select count(*) from rows),'counts',coalesce((select jsonb_object_agg(kind,amount) from(select kind,count(*) amount from rows group by kind)q),'{}'),
  'items',coalesce((select jsonb_agg(jsonb_build_object('id',id,'kind',kind,'reviewId',review_id,'platform',platform,'reason',reason,'occurredAt',occurred_at,'section',section,'sourceVersion',source_version,'currentSourceVersion',current_source_version) order by occurred_at,key) from(select * from page limit 20)q),'[]'),
  'nextCursor',case when(select count(*) from page)>20 then(select key from page offset 19 limit 1) end,'asOf',now()) into output;
 return output;
end$$;

revoke all on function public.read_reviewflow_statistics(uuid,uuid,integer),public.reviewflow_queue_members(uuid),public.read_reviewflow_queue(uuid,uuid,text,uuid),public.reviewflow_recovery_rows(uuid),public.read_reviewflow_recovery(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.read_reviewflow_statistics(uuid,uuid,integer),public.reviewflow_queue_members(uuid),public.read_reviewflow_queue(uuid,uuid,text,uuid),public.reviewflow_recovery_rows(uuid),public.read_reviewflow_recovery(uuid,uuid,text) to service_role;
notify pgrst,'reload schema';
